In [2]:
library(tidyverse)
library(dbplyr)
library(bigrquery)
library(lubridate)

bq_auth()

project_id = "yhcr-prd-bradfor-bia-core"

# create connection to database
con <- DBI::dbConnect(bigrquery::bigquery(), 
                      project = project_id)

print(paste0("Connected to : ", project_id))

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘dbplyr’


The following objects are masked from ‘package:dplyr’:

    ident, sql

[1] "Connected to : yhcr-prd-bradfor-bia-core"

# Read in person cohort csv

In [176]:
person <- read.csv('data/person_cohorts.csv', header = TRUE)

In [177]:
head(person)

  person_id                                                        birth_date
1 D27CE553B8DA52E66BCBA43420F6F53DAEBF9FE2864361849339028B6B002695 2000-09-15
2 9F33F6D292805042AF92186788B71C7302C7E976F6C148C34FDE62B157C03928 2000-09-15
3 C38AD0B73560547A95C529E42A9CF6E1E06282163BB419DC2C1451422CD20CE0 2000-09-15
4 03A81FF3A58E65546A42780919E74680BF016F6D3E8FE1FA64FFD9B9E436B795 2000-09-15
5 8C9979BE485657CDE5AC92361D6E454DC61C1396BCC38F77933217649F802EFF 2000-09-15
6 00ED2E8CBC0AE48B370DBB70FB9440A00BD65113392DE33A5E14380D5C306075 2000-09-15
  gender CombinedEthnicity cohort
1 F      South Asian       2000/01
2 F      South Asian       2000/01
3 F      South Asian       2000/01
4 F      NA                2000/01
5 F      White British     2000/01
6 F      White British     2000/01

In [178]:
person |>
nrow()

[1] 22101

In [179]:
person_ids <- read.csv('data/person_ids.csv', header = TRUE)

In [180]:
head(person_ids)

  person_id                                                        NCCIS_ACADYR
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2017/2018
2 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2017/2018
3 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2018/2019
4 0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2018/2019
5 00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66 2017/2018
6 0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D 2017/2018

In [181]:
person_ids |>
nrow()

[1] 17361

In [182]:
# Check if all person_ids in person_id are in person
all(person_ids$person_id %in% person$person_id)

[1] TRUE

In [183]:
# filter person to only matching IDs
person_filtered <- person |>
    filter(person_id %in% person_ids$person_id)

In [184]:
person_filtered |>
nrow()

[1] 17361

In [185]:
all(person_ids$person_id %in% person_filtered$person_id)

[1] TRUE

# Siblings / home indicators

In [186]:
school_census_data = "CB_2489.cb_StudentAdditionalInfoFromCensus"

In [187]:
home_table <- tbl(con, school_census_data) |>
    select(person_id, SourceTable, DistCurrSch, DistNearSch, ModeOfTravel, Boarder, Language, IDACIScore_Home, LSOA11_Home, AdoptedFromCare, InCare, NSiblings_SGA, BirthOrder_SGA, GroupID_SGA) |>
    filter(!is.na(person_id))

Auto-refreshing stale OAuth token.

In [188]:
# SGA means based on shared address (vs. on address and surname)
# BirthOrder_SGA 1 is the oldest

In [189]:
home_table

# Source:   SQL [?? x 14]
# Database: BigQueryConnection
   person_id   SourceTable DistCurrSch DistNearSch ModeOfTravel Boarder Language
   <chr>       <chr>             <dbl>       <dbl> <chr>        <chr>   <chr>
 1 1599DBDF7E… Spring_Cen…        0.19        0.19 NA           N       HGR
 2 767B260381… Spring_Cen…        0.93        0.25 NA           N       PRSD
 3 4351EA3E9D… Spring_Cen…        0.52        0.28 NA           N       CZE
 4 806A603473… Spring_Cen…        4.78       NA    NA           N       ARA
 5 A1E1773668… Spring_Cen…        2.61        0.2  NA           N       PRS
 6 94D9517B50… Spring_Cen…        0.15        0.12 NA           N       SOM
 7 DF5B98D405… Spring_Cen…        0.13        0.13 NA           N       ALB
 8 E6763D54CB… Spring_Cen…        0.18        0.18 NA           N       ENG
 9 CAA9275D57… Spring_Cen…        3.1        NA    NA           N       ENG
10 1C02B5DDD6… Spring_Cen…        0.53        0.23 NA           N       LTV
# ℹ more rows
# ℹ 7 more variables: IDACIScore_Home <dbl>, LSOA11_Home <chr>,
#   AdoptedFromCare <chr>, InCare <chr>, NSiblings_SGA <dbl>,
#   BirthOrder_SGA <dbl>, GroupID_SGA <dbl>

In [190]:
home_table_df <- home_table |>
    collect()

In [191]:
home_table_df |>
    nrow()

[1] 6656974

In [192]:
home_table_df |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 302369

In [193]:
home_table_filtered <- home_table_df |>
    filter(person_id %in% person_ids$person_id)

In [194]:
home_table_filtered |>
    nrow()

[1] 599106

In [195]:
home_table_filtered |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 17224

In [196]:
home_table_filtered |>
    filter(person_id == '0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD')

   person_id
1  0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2  0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
3  0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
4  0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
5  0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
6  0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
7  0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
8  0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
9  0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
10 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
11 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
12 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
13 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
14 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
15 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
16 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
17 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
18 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
19 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
20 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
21 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
22 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
23 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
24 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
25 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
26 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
27 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
28 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
29 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
30 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
31 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
32 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
33 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
34 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
   SourceTable        DistCurrSch DistNearSch ModeOfTravel Boarder Language
1  Autumn_Census_2014   NA          NA        NA           N       ENG
2  Spring_Census_2012 0.15        0.15        NA           N       ENG
3  Spring_Census_2016 0.66        0.66        NA           N       ENG
4  Autumn_Census_2012   NA          NA        NA           N       ENG
5  PLASC_2005         0.15          NA        NA           N       NA
6  Summer_Census_2013   NA          NA        NA           N       ENG
7  Summer_Census_2009   NA          NA        NA           N       ENG
8  Summer_Census_2016   NA          NA        NA           N       ENG
9  Spring_Census_2013 0.66        0.66        NA           N       ENG
10 Spring_Census_2014 0.66        0.66        NA           N       ENG
11 Autumn_Census_2013   NA          NA        NA           N       ENG
12 Autumn_Census_2017   NA          NA        NA           N       ENG
13 Autumn_Census_2015   NA          NA        NA           N       ENG
14 Autumn_Census_2016   NA          NA        NA           N       ENG
15 Summer_Census_2008   NA          NA        NA           N       ENG
16 Spring_Census_2009 0.15        0.15        WLK          N       ENG
17 Autumn_Census_2008   NA          NA        NA           N       ENG
18 Summer_Census_2014   NA          NA        NA           N       ENG
19 Summer_Census_2015   NA          NA        NA           N       ENG
20 Spring_Census_2012 0.15        0.15        WLK          N       ENG
21 Summer_Census_2011   NA          NA        NA           N       ENG
22 Autumn_Census_2009   NA          NA        NA           N       ENG
23 Summer_Census_2017   NA          NA        NA           N       ENG
24 Spring_Census_2010 0.15        0.15        WLK          N       ENG
25 Spring_Census_2017 0.66        0.66        NA           N       ENG
26 Autumn_Census_2011   NA          NA        NA           N       ENG
27 Summer_Census_2012   NA          NA        NA           N       ENG
28 Summer_Census_2007   NA          NA        NA           N       ENG
29 Autumn_Census_2010   NA          NA        NA           N       ENG
30 Spring_Census_2006 0.15        0.15        NA           N       NA
31 Spring_Census_2015 0.66        0.66        NA           N       ENG
32 Spring_Census_2008 0.15        0.15        WLK          N       ENG
33 Spring_Census_2007 0.15        0.15        WLK          N       ENG
34 Summer_Census_2010   NA          NA        NA           N       ENG
   IDACIScore_Home LSOA11_Home AdoptedFromCare InCare NSiblings_SGA
1  0.32444         E01010635   NA              NA     NA
2  0.32444         NA          NA              NA     NA
3       NA         E01010635   N               NA      2
4       NA         NA          NA              NA     NA
5  0.37623         NA          NA              0      NA
6  0.32444         E01010635   NA              NA     NA
7  0.35747         NA          NA              NA     NA
8       NA         E01010635   N               NA     NA
9  0.32444         E01010635   NA              NA      2
10 0.32444         E01010635   N               NA     NA
11 0.32444         NA          NA              NA     NA
12      NA         E01010635   NA              NA     NA
13 0.32444         E01010635   N               NA     NA
14      NA         E01010635   N               NA     NA
15 0.35747         NA          NA              NA     NA
16 0.35747         NA          NA              0      NA
17 0.37623         NA          NA              NA     NA
18 0.32444         E01010635   N               NA     NA
19 0.32444         E01010635   N               NA     NA
20 0.32444         NA          NA              NA     NA
21      NA         NA          NA              NA     NA
22 0.35747         NA          NA              NA     NA
23      NA         E01010635   NA              NA     NA
24 0.35747         NA          NA              0      NA
25 0.41000         E01010635   NA              NA     NA
26 0.35747         NA          NA              NA     NA
27 0.32444         NA          NA              NA     NA
28 0.37623         NA          NA              NA     NA
29 0.35747         NA          NA              NA     NA
30 0.37623         NA          NA              NA     NA
31 0.32444         E01010635   N               NA     NA
32 0.35747         NA          NA              0       1
33 0.37623         NA          NA              0      NA
34 0.35747         NA          NA              NA     NA
   BirthOrder_SGA GroupID_SGA
1  NA                 NA
2  NA                 NA
3   1             733638
4  NA                 NA
5  NA                 NA
6  NA                 NA
7  NA                 NA
8  NA                 NA
9   1             535577
10 NA                 NA
11 NA                 NA
12 NA                 NA
13 NA                 NA
14 NA                 NA
15 NA                 NA
16 NA                 NA
17 NA                 NA
18 NA                 NA
19 NA                 NA
20 NA                 NA
21 NA                 NA
22 NA                 NA
23 NA                 NA
24 NA                 NA
25 NA                 NA
26 NA                 NA
27 NA                 NA
28 NA                 NA
29 NA                 NA
30 NA                 NA
31 NA                 NA
32  1             571778
33 NA                 NA
34 NA                 NA

In [197]:
# extract year from source table
home_table_filtered$Year <- substr(home_table_filtered$SourceTable, nchar(home_table_filtered$SourceTable) - 3, nchar(home_table_filtered$SourceTable))

In [198]:
head(home_table_filtered)

  person_id
1 90BB0A71C61559E8739BB61BB06DF5219E61B68C1473EF196EE2E636FA7EBD66
2 63D51806BF39CD8BA75B167A225A6265CACB64C2BCC450D1CC6A8D1B7762C51A
3 7E85C178F3746E87FD206106D7DE8A60C6A3673D85F289AFA7260A41DBFD52C8
4 E625DCFFBF76BE04A4AF39A037ECC571BC1E9DB022EF1866EA592F0F453E897E
5 8FD16984BBF636D0A880EBDE8C0752AF282E2FEDE469927D33EA1C8A87CB4102
6 52F485644A0C4A92B167EA8FAD081A9F07FD525D52E6DA83F5FBA5386AE9B528
  SourceTable        DistCurrSch DistNearSch ModeOfTravel Boarder Language
1 Spring_Census_2020 0.57        NA          NA           N       ENG
2 Summer_Census_2007   NA        NA          NA           N       ENG
3 Summer_Census_2007   NA        NA          NA           N       ENG
4 Summer_Census_2007   NA        NA          NA           N       OTB
5 Summer_Census_2007   NA        NA          NA           N       URD
6 Autumn_Census_2008   NA        NA          NA           N       ARA
  IDACIScore_Home LSOA11_Home AdoptedFromCare InCare NSiblings_SGA
1      NA         E01010805   NA              NA     NA
2 0.62848         NA          NA              NA     NA
3 0.58800         NA          NA              NA     NA
4 0.38284         NA          NA              NA     NA
5 0.35253         NA          NA              NA     NA
6 0.35479         NA          NA              NA     NA
  BirthOrder_SGA GroupID_SGA Year
1 NA             NA          2020
2 NA             NA          2007
3 NA             NA          2007
4 NA             NA          2007
5 NA             NA          2007
6 NA             NA          2008

In [199]:
# drop source table col and then merge / remove duplicate rows
home_table_filtered <- home_table_filtered |>
    select(-SourceTable)

In [200]:
home_table_filtered <- home_table_filtered |>
    distinct()

In [201]:
home_table_filtered |>
    nrow()

[1] 507335

In [202]:
home_table_filtered |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 17224

#### drop cols

In [203]:
home_table_filtered |> distinct(ModeOfTravel) |> pull(ModeOfTravel)

 [1] NA    "CRS" "CAR" "WLK" "DSB" "CYC" "TXI" "BNK" "PSB" "LUL" "TRN" "OTH"
[13] "MTL" "BDR"

In [204]:
home_table_filtered |> distinct(Boarder) |> pull(Boarder)

[1] "N" "6" "B" NA  "7"

In [205]:
home_table_filtered |> distinct(AdoptedFromCare) |> pull(AdoptedFromCare)

[1] NA  "N" "A" "R" "G"

In [206]:
home_table_filtered |> distinct(InCare) |> pull(InCare)

 [1] NA    "0"   "1"   "810" "380" "384" "888" "382" "381" "316" "883" "856"
[13] "391" "359" "383" "352" "815" "850" "841" "343"

In [207]:
home_table_filtered <- home_table_filtered |>
    select(-c(ModeOfTravel,Boarder,AdoptedFromCare,InCare,NSiblings_SGA,BirthOrder_SGA,GroupID_SGA))

In [208]:
# add in cohort identifier so that can drop data from primary school ranges
home_table_merge <- home_table_filtered |>
  left_join(person_filtered |> select(person_id, cohort), by = "person_id")

In [209]:
home_table_merge |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 17224

In [210]:
head(home_table_merge)

  person_id                                                        DistCurrSch
1 90BB0A71C61559E8739BB61BB06DF5219E61B68C1473EF196EE2E636FA7EBD66 0.57
2 63D51806BF39CD8BA75B167A225A6265CACB64C2BCC450D1CC6A8D1B7762C51A   NA
3 7E85C178F3746E87FD206106D7DE8A60C6A3673D85F289AFA7260A41DBFD52C8   NA
4 E625DCFFBF76BE04A4AF39A037ECC571BC1E9DB022EF1866EA592F0F453E897E   NA
5 8FD16984BBF636D0A880EBDE8C0752AF282E2FEDE469927D33EA1C8A87CB4102   NA
6 52F485644A0C4A92B167EA8FAD081A9F07FD525D52E6DA83F5FBA5386AE9B528   NA
  DistNearSch Language IDACIScore_Home LSOA11_Home Year cohort
1 NA          ENG           NA         E01010805   2020 2000/01
2 NA          ENG      0.62848         NA          2007 2000/01
3 NA          ENG      0.58800         NA          2007 2000/01
4 NA          OTB      0.38284         NA          2007 2000/01
5 NA          URD      0.35253         NA          2007 2000/01
6 NA          ARA      0.35479         NA          2008 2000/01

In [211]:
home_table_merge <- home_table_merge |> 
    filter(Year %in% c('2013','2014','2015','2016','2017','2018'))

In [212]:
home_table_merge |> distinct(Year) |> pull(Year)

[1] "2017" "2013" "2018" "2014" "2015" "2016"

In [213]:
# where cohort 2001/2 drop 2013 year records
home_table_merge <- home_table_merge |> 
    filter(!(cohort == '2001/02' & Year == '2013'))

In [214]:
# where cohort 2000/1 drop 2018 year records
home_table_merge <- home_table_merge |> 
    filter(!(cohort == '2000/01' & Year == '2018'))

In [215]:
home_table_merge |>
    nrow()

[1] 191543

In [216]:
home_table_merge |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 16936

In [217]:
# drop rows per year with NAs
home_table_merge <- home_table_merge |>
    arrange(desc(Year)) |>
    group_by(person_id, Year) |>
    summarise(across(everything(), ~ ifelse(all(is.na(.)), NA, na.omit(.)[1])), .groups = "drop")

In [218]:
home_table_merge |>
    nrow()

[1] 82262

In [219]:
home_table_merge |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 16936

In [220]:
home_table_merge |>
    filter(person_id == '0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD')

  person_id                                                        Year
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2013
2 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2014
3 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2015
4 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2016
5 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2017
  DistCurrSch DistNearSch Language IDACIScore_Home LSOA11_Home cohort
1 0.66        0.66        ENG      0.32444         E01010635   2000/01
2 0.66        0.66        ENG      0.32444         E01010635   2000/01
3 0.66        0.66        ENG      0.32444         E01010635   2000/01
4 0.66        0.66        ENG           NA         E01010635   2000/01
5 0.66        0.66        ENG      0.41000         E01010635   2000/01

In [221]:
home_table_merge |>
    filter(person_id == '0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D')

  person_id                                                        Year
1 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2014
2 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2015
3 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2016
4 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2017
5 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2018
  DistCurrSch DistNearSch Language IDACIScore_Home LSOA11_Home cohort
1 1.59        0.81        ENG      0.20557         E01002616   2001/02
2 1.59        0.48        ENG      0.20557         E01002616   2001/02
3 1.59        0.48        ENG           NA         E01002616   2001/02
4 7.01        0.00        ENG      0.12500         E01002563   2001/02
5 7.01        0.00        ENG           NA         E01002563   2001/02

In [222]:
# group by all cols except year, and keep first row of duplicates
home_table_merge <- home_table_merge |>
    arrange(desc(Year)) |>
    group_by(across(-Year)) |>
    filter(row_number() == 1) |>
    ungroup()

In [223]:
home_table_merge |>
    nrow()

[1] 61118

In [224]:
home_table_merge |>
    filter(person_id == '0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD')

  person_id                                                        Year
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2017
2 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2016
3 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2015
  DistCurrSch DistNearSch Language IDACIScore_Home LSOA11_Home cohort
1 0.66        0.66        ENG      0.41000         E01010635   2000/01
2 0.66        0.66        ENG           NA         E01010635   2000/01
3 0.66        0.66        ENG      0.32444         E01010635   2000/01

In [225]:
home_table_merge |>
    filter(person_id == '0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D')

  person_id                                                        Year
1 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2018
2 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2017
3 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2016
4 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2015
5 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2014
  DistCurrSch DistNearSch Language IDACIScore_Home LSOA11_Home cohort
1 7.01        0.00        ENG           NA         E01002563   2001/02
2 7.01        0.00        ENG      0.12500         E01002563   2001/02
3 1.59        0.48        ENG           NA         E01002616   2001/02
4 1.59        0.48        ENG      0.20557         E01002616   2001/02
5 1.59        0.81        ENG      0.20557         E01002616   2001/02

In [226]:
# repeat merge rows where there are NA values keep first non NA (latest date prioritised)
home_table_merge <- home_table_merge |>
    arrange(desc(Year)) |>
    group_by(person_id) |>
    summarise(across(everything(), ~ ifelse(all(is.na(.)), NA, na.omit(.)[1])), .groups = "drop")

In [227]:
head(home_table_merge)

  person_id                                                        Year
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2017
2 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2017
3 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2018
4 0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2018
5 00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66 2017
6 0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D 2017
  DistCurrSch DistNearSch Language IDACIScore_Home LSOA11_Home cohort
1 0.66        0.66        ENG      0.410           E01010635   2000/01
2 3.50        0.62        ENG      0.397           E01010749   2000/01
3 7.01        0.00        ENG      0.125           E01002563   2001/02
4 0.57        0.57        PNJ      0.405           E01010724   2001/02
5 1.69        0.44        PNJ      0.521           E01010610   2000/01
6 1.12        0.62        ENG      0.234           E01010815   2000/01

In [228]:
home_table_merge |>
    filter(person_id == '0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD')

  person_id                                                        Year
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2017
  DistCurrSch DistNearSch Language IDACIScore_Home LSOA11_Home cohort
1 0.66        0.66        ENG      0.41            E01010635   2000/01

In [229]:
home_table_merge |>
    filter(person_id == '0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D')

  person_id                                                        Year
1 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2018
  DistCurrSch DistNearSch Language IDACIScore_Home LSOA11_Home cohort
1 7.01        0           ENG      0.125           E01002563   2001/02

In [230]:
home_table_merge |> nrow()

[1] 16936

In [231]:
home_table_merge |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 16936

#### EAL

In [232]:
home_table_merge <- home_table_merge |>
    mutate(
    EAL = case_when(
      Language == "ENG" ~ 0,
      is.na(Language) ~ NA,
      TRUE ~ 1 
    )
  )

In [233]:
home_table_merge <- home_table_merge |>
    select(-c(Language, Year))

In [234]:
head(home_table_merge)

  person_id                                                        DistCurrSch
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 0.66
2 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 3.50
3 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 7.01
4 0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 0.57
5 00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66 1.69
6 0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D 1.12
  DistNearSch IDACIScore_Home LSOA11_Home cohort  EAL
1 0.66        0.410           E01010635   2000/01 0
2 0.62        0.397           E01010749   2000/01 0
3 0.00        0.125           E01002563   2001/02 0
4 0.57        0.405           E01010724   2001/02 1
5 0.44        0.521           E01010610   2000/01 1
6 0.62        0.234           E01010815   2000/01 0

## merge person and home

In [235]:
home_table_merge <- home_table_merge |>
    select(-cohort)

In [236]:
person_home <- person_filtered |> 
    left_join(home_table_merge, by = join_by(person_id))

In [237]:
head(person_home)

  person_id                                                        birth_date
1 D27CE553B8DA52E66BCBA43420F6F53DAEBF9FE2864361849339028B6B002695 2000-09-15
2 9F33F6D292805042AF92186788B71C7302C7E976F6C148C34FDE62B157C03928 2000-09-15
3 C38AD0B73560547A95C529E42A9CF6E1E06282163BB419DC2C1451422CD20CE0 2000-09-15
4 8C9979BE485657CDE5AC92361D6E454DC61C1396BCC38F77933217649F802EFF 2000-09-15
5 00ED2E8CBC0AE48B370DBB70FB9440A00BD65113392DE33A5E14380D5C306075 2000-09-15
6 F9AA50A652E66CCDB96FE50B68A1035B2612296C86D2B839A97D5B3533FEA597 2000-09-15
  gender CombinedEthnicity cohort  DistCurrSch DistNearSch IDACIScore_Home
1 F      South Asian       2000/01 0.90        0.85        0.245
2 F      South Asian       2000/01 3.87        0.37        0.236
3 F      South Asian       2000/01 0.60        0.60        0.401
4 F      White British     2000/01 2.72        2.72        0.049
5 F      White British     2000/01 1.48        1.48        0.080
6 F      White British     2000/01 0.25        0.25        0.171
  LSOA11_Home EAL
1 E01010662   1
2 E01010743   0
3 E01010745   1
4 E01031883   0
5 E01010795   0
6 E01017898   0

In [238]:
# save as csv
write.csv(person_home, "data/person_home.csv", row.names = FALSE)

# Disability

In [236]:
student_data = "CB_2489.cb_Student"

student_table <- tbl(con, student_data) |> 
    select(person_id, Gender, Disability) |>
    filter(!is.na(person_id)) |>
    filter(!is.na(Disability))

In [237]:
student_table

# Source:   SQL [?? x 3]
# Database: BigQueryConnection
   person_id                                                   Gender Disability
   <chr>                                                       <chr>  <chr>
 1 1BB207623557A2E675505C4CA5237B7AB9EB8EA3B3D17E70CD93A68926… F      NCOL
 2 26E90FE4263275E646264F68FA34C104CD1AEE6BF45CF0D7F256E117A4… F      NCOL
 3 10BC24A12C475E751290F1DD6CE0129AE5627F2676F2E7041EC4D69026… F      NCOL
 4 EF5BDEACB889527A7BC6F6F29DC7A3CB88F77A7AF5A12E8B6DE9F88F73… F      NCOL
 5 F7FDCCAFC13BA5A4F2FC7E407D12F14C1ACE57A0DB38874412D284C4C1… M      NCOL
 6 D2630283F9C4DFDB64DA4509C55BA1ACC3E62B0D50FFD12CB01721F495… M      NCOL
 7 943242326C63FCA6AAF153271971640F2CDC932543D81CB0A3E3022D93… M      NCOL
 8 EA6F60F9824E3D26D76A78F9EC54279A433AE4390DB2953CCAB34F0300… M      NCOL
 9 24BCE3FCC408EFDB17B492DE055E5E7E7DB013199B3768B60257B4375D… M      NCOL
10 F27B849A12EB97ECE880026DB0E694F30594669BA0870B3DA7088A3B91… M      NCOL
# ℹ more rows

In [238]:
student_df <- collect(student_table)

In [239]:
# filter person to only matching IDs
student_filtered <- student_df |>
    filter(person_id %in% person_ids$person_id)

In [242]:
head(student_filtered)

  person_id                                                        Gender
1 1BB207623557A2E675505C4CA5237B7AB9EB8EA3B3D17E70CD93A68926983A83 F
2 26E90FE4263275E646264F68FA34C104CD1AEE6BF45CF0D7F256E117A4575042 F
3 10BC24A12C475E751290F1DD6CE0129AE5627F2676F2E7041EC4D690264BB58D F
4 EF5BDEACB889527A7BC6F6F29DC7A3CB88F77A7AF5A12E8B6DE9F88F7397AC87 F
5 D2630283F9C4DFDB64DA4509C55BA1ACC3E62B0D50FFD12CB01721F495611C5E M
6 EA6F60F9824E3D26D76A78F9EC54279A433AE4390DB2953CCAB34F03007267F2 M
  Disability
1 NCOL
2 NCOL
3 NCOL
4 NCOL
5 NCOL
6 NCOL

In [244]:
student_filtered |> 
  distinct(Disability) |> 
  pull(Disability)

 [1] "NCOL" "BEH"  "NONE" "LD"   "MOB"  "COMM" "HEAR" "AUT"  "CON"  "OTH"
[11] "VIS"  "HAND" "MED"  "EAT"  "PC"

In [245]:
student_table <- student_filtered |> 
  mutate(
    SEN = case_when(
      Disability %in% c('NCOL', "", NA) ~ NA_character_,
      TRUE ~ Disability  # Handle any other unexpected cases
    )
  )

In [246]:
head(student_table)

  person_id                                                        Gender
1 1BB207623557A2E675505C4CA5237B7AB9EB8EA3B3D17E70CD93A68926983A83 F
2 26E90FE4263275E646264F68FA34C104CD1AEE6BF45CF0D7F256E117A4575042 F
3 10BC24A12C475E751290F1DD6CE0129AE5627F2676F2E7041EC4D690264BB58D F
4 EF5BDEACB889527A7BC6F6F29DC7A3CB88F77A7AF5A12E8B6DE9F88F7397AC87 F
5 D2630283F9C4DFDB64DA4509C55BA1ACC3E62B0D50FFD12CB01721F495611C5E M
6 EA6F60F9824E3D26D76A78F9EC54279A433AE4390DB2953CCAB34F03007267F2 M
  Disability SEN
1 NCOL       NA
2 NCOL       NA
3 NCOL       NA
4 NCOL       NA
5 NCOL       NA
6 NCOL       NA

In [356]:
student_table |>
    group_by(SEN) |>
    tally() |>
    arrange(desc(n))

   SEN  n
1  NA   15788
2  NONE   300
3  LD      64
4  BEH     21
5  OTH     15
6  AUT     13
7  COMM    10
8  HEAR     7
9  EAT      4
10 MOB      4
11 MED      3
12 VIS      3
13 HAND     2
14 CON      1
15 PC       1

## SEN

In [3]:
sen_data = "CB_2489.cb_StudentEntitlementFromCensus"

sen_table <- tbl(con, sen_data) |> 
    select(person_id, SourceTable, EVERFSM_ALL, SENStage, SENprovision, SENprovisionMajor, PrimarySENtype) |>
    filter(!is.na(person_id))

In [4]:
head(sen_table)

# Source:   SQL [6 x 7]
# Database: BigQueryConnection
  person_id      SourceTable EVERFSM_ALL SENStage SENprovision SENprovisionMajor
  <chr>          <chr>             <dbl> <chr>    <chr>        <chr>
1 B1D77C27358C0… PLASC_2002           NA 0        NA           NA
2 B0F6576C4FD11… PLASC_2002           NA 2        NA           NA
3 743AE9CEC04DB… PLASC_2002           NA 0        NA           NA
4 F8997374AD18D… PLASC_2002           NA 2        NA           NA
5 F55EE5CB23250… PLASC_2002           NA 0        NA           NA
6 85F82007BB545… PLASC_2002           NA 0        NA           NA
# ℹ 1 more variable: PrimarySENtype <chr>

In [5]:
sen_table |> 
  distinct(SourceTable) |> 
  pull(SourceTable)

 [1] "PLASC_2002"          "PLASC_2005"          "Autumn_Census_2007"
 [4] "Autumn_Census_2009"  "Autumn_Census_2010"  "Autumn_Census_2012"
 [7] "Autumn_Census_2013"  "Autumn_Census_2014"  "Spring_Census_2006"
[10] "Spring_Census_2009"  "Spring_Census_2015"  "Summer_Census_2008"
[13] "Summer_Census_2010"  "Summer_Census_2012"  "Summer_Census_2013"
[16] "Summer_Census_2015"  "Autumn_Census_2018"  "Autumn_Census_2019"
[19] "Autumn_Census_2020"  "Autumn_Census_2021"  "Spring_Census_2016"
[22] "Summer_Census_2016"  "Summer_Census_20017" "PLASC_2003"
[25] "PLASC_2004"          "Autumn_Census_2008"  "Autumn_Census_2011"
[28] "Autumn_Census_2015"  "SUMMER_Census_2006"  "Spring_Census_2007"
[31] "Spring_Census_2008"  "Spring_Census_2010"  "Spring_Census_2011"
[34] "Spring_Census_2012"  "Spring_Census_2013"  "Spring_Census_2014"
[37] "Summer_Census_2007"  "Summer_Census_2009"  "Summer_Census_2011"
[40] "Summer_Census_2014"  "Autumn_Census_2016"  "Autumn_Census_2017"
[43] "Autumn_Census_2022"  "Spring_Census_2019"  "Spring_Census_2020"
[46] "Spring_Census_2021"  "Spring_Census_2022"  "Summer_Census_2018"
[49] "Summer_Census_2019"  "Summer_Census_2021"  "Summer_Census_2022"

Pupil Level Annual School Census (PLASC)

In [6]:
sen_df <- collect(sen_table)

In [241]:
# filter to person_ids
sen_filtered <- sen_df |>
    filter(person_id %in% person_ids$person_id)

In [242]:
# edit label for Summer_Census_20017
sen_filtered <- sen_filtered |>
    mutate(SourceTable = case_when(
        SourceTable == 'Summer_Census_20017' ~ 'Summer_Census_2017',
        TRUE ~ SourceTable)
           )

In [243]:
# extract year from source table
sen_filtered$Year <- substr(sen_filtered$SourceTable, nchar(sen_filtered$SourceTable) - 3, nchar(sen_filtered$SourceTable))

In [244]:
sen_filtered |>
    arrange(Year) |>
    filter(person_id == 'D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E')

   person_id
1  D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
2  D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
3  D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
4  D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
5  D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
6  D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
7  D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
8  D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
9  D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
10 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
11 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
12 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
13 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
14 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
15 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
16 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
17 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
18 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
19 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
20 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
21 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
22 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
23 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
24 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
25 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
26 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
27 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
28 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
29 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
30 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
31 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
32 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
33 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
34 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
35 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
36 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
37 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
38 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
39 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
40 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
41 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E
   SourceTable        EVERFSM_ALL SENStage SENprovision SENprovisionMajor
1  Summer_Census_2007 NA          NA       N            NA
2  Spring_Census_2007 NA          NA       N            NA
3  Autumn_Census_2008 NA          NA       N            NA
4  Summer_Census_2008 NA          NA       A            NA
5  Spring_Census_2008 NA          NA       A            NA
6  Autumn_Census_2009 NA          NA       A            NA
7  Spring_Census_2009 NA          NA       A            2_SNS
8  Summer_Census_2009 NA          NA       A            2_SNS
9  Spring_Census_2010  0          NA       P            2_SNS
10 Summer_Census_2010 NA          NA       P            2_SNS
11 Autumn_Census_2010 NA          NA       A            2_SNS
12 Summer_Census_2011 NA          NA       P            2_SNS
13 Spring_Census_2011  0          NA       P            2_SNS
14 Autumn_Census_2011 NA          NA       P            2_SNS
15 Spring_Census_2012  0          NA       A            2_SNS
16 Summer_Census_2012 NA          NA       A            2_SNS
17 Autumn_Census_2012 NA          NA       P            2_SNS
18 Spring_Census_2013  0          NA       N            1_NON
19 Autumn_Census_2013 NA          NA       N            1_NON
20 Summer_Census_2013 NA          NA       N            1_NON
21 Autumn_Census_2014 NA          NA       A            2_SNS
22 Spring_Census_2014  0          NA       A            2_SNS
23 Summer_Census_2014 NA          NA       A            2_SNS
24 Autumn_Census_2015 NA          NA       A            2_SNS
25 Summer_Census_2015 NA          NA       K            2_SNS
26 Spring_Census_2015  0          NA       K            2_SNS
27 Autumn_Census_2016 NA          NA       K            2_SNS
28 Summer_Census_2016 NA          NA       K            2_SNS
29 Spring_Census_2016  0          NA       K            2_SNS
30 Autumn_Census_2017 NA          NA       K            2_SNS
31 Summer_Census_2017 NA          NA       K            2_SNS
32 Summer_Census_2018 NA          NA       N            1_NON
33 Autumn_Census_2018 NA          NA       N            1_NON
34 Summer_Census_2019 NA          NA       N            1_NON
35 Spring_Census_2019 NA          NA       N            1_NON
36 Autumn_Census_2019 NA          NA       N            1_NON
37 Autumn_Census_2020 NA          NA       N            1_NON
38 Spring_Census_2020 NA          NA       N            1_NON
39 Autumn_Census_2021 NA          NA       N            1_NON
40 Summer_Census_2021 NA          NA       K            2_SNS
41 Spring_Census_2021 NA          NA       K            2_SNS
   PrimarySENtype Year
1  NA             2007
2  NA             2007
3  NA             2008
4  NA             2008
5  NA             2008
6  NA             2009
7  NA             2009
8  NA             2009
9  SPLD           2010
10 NA             2010
11 NA             2010
12 NA             2011
13 SPLD           2011
14 NA             2011
15 NA             2012
16 NA             2012
17 NA             2012
18 NA             2013
19 NA             2013
20 NA             2013
21 NA             2014
22 NA             2014
23 NA             2014
24 NA             2015
25 NA             2015
26 SPLD           2015
27 NA             2016
28 NA             2016
29 SPLD           2016
30 NA             2017
31 NA             2017
32 NA             2018
33 NA             2018
34 NA             2019
35 NA             2019
36 NA             2019
37 NA             2020
38 NA             2020
39 NA             2021
40 NA             2021
41 ASD            2021

In [245]:
head(sen_filtered)

  person_id
1 78A31FE77B8702EC379E452B50B3D3C195ECE9EC5E11E564D61F2C58BC1097B2
2 E964E0F5400562D02CB0792EC9B83867E6D88DB190C65E6C57B6800F65925C32
3 C62F1A01AE50FD58284D8BDCB7A55807DEE2EC6AC977BBAA7E42C9A14EE8C984
4 6B939B60E0C7582155BCC0EE14E628375B483FD73456FBC9E154E5BF0E0F5BFB
5 03DBAB2F9652CA5D031AE4E9DFDF1E1B449B93416D87DCF6F3FADB708C17A4E6
6 EF09AEE797A50A1A115E37691E61DE9B912780D0F0D7C6E8591347821B243374
  SourceTable        EVERFSM_ALL SENStage SENprovision SENprovisionMajor
1 PLASC_2005         NA          NA       A            NA
2 Autumn_Census_2008 NA          NA       A            NA
3 Autumn_Census_2008 NA          NA       A            NA
4 Autumn_Census_2008 NA          NA       A            NA
5 Autumn_Census_2008 NA          NA       A            NA
6 Autumn_Census_2008 NA          NA       A            NA
  PrimarySENtype Year
1 NA             2005
2 NA             2008
3 NA             2008
4 NA             2008
5 NA             2008
6 NA             2008

In [246]:
sen_filtered |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 17224

#### extract only FSM col

In [247]:
fsm <- sen_filtered |>
    select(person_id, Year, EVERFSM_ALL)

In [248]:
fsm_filtered <- fsm |>
    filter(!is.na(EVERFSM_ALL))

In [249]:
fsm_filtered |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 17009

In [250]:
# keep latest year only
fsm_filtered <- fsm_filtered |>
      arrange(person_id, desc(Year)) |>
      distinct(person_id, .keep_all = TRUE)

In [251]:
fsm_filtered|>
    nrow()

[1] 17009

In [252]:
fsm_filtered |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 17009

In [253]:
fsm_filtered |>
    group_by(EVERFSM_ALL) |>
    tally()

  EVERFSM_ALL n
1 0           10142
2 1            6867

#### merge in FSM col to main data

In [254]:
fsm_filtered <- fsm_filtered |>
    select(person_id, EVERFSM_ALL) |>
    rename(ever_fsm = EVERFSM_ALL)

In [255]:
person_home_fsm <- person_home |> 
    left_join(fsm_filtered, by = join_by(person_id))

In [256]:
head(person_home_fsm)

  person_id                                                        birth_date
1 D27CE553B8DA52E66BCBA43420F6F53DAEBF9FE2864361849339028B6B002695 2000-09-15
2 9F33F6D292805042AF92186788B71C7302C7E976F6C148C34FDE62B157C03928 2000-09-15
3 C38AD0B73560547A95C529E42A9CF6E1E06282163BB419DC2C1451422CD20CE0 2000-09-15
4 8C9979BE485657CDE5AC92361D6E454DC61C1396BCC38F77933217649F802EFF 2000-09-15
5 00ED2E8CBC0AE48B370DBB70FB9440A00BD65113392DE33A5E14380D5C306075 2000-09-15
6 F9AA50A652E66CCDB96FE50B68A1035B2612296C86D2B839A97D5B3533FEA597 2000-09-15
  gender CombinedEthnicity cohort  DistCurrSch DistNearSch IDACIScore_Home
1 F      South Asian       2000/01 0.90        0.85        0.245
2 F      South Asian       2000/01 3.87        0.37        0.236
3 F      South Asian       2000/01 0.60        0.60        0.401
4 F      White British     2000/01 2.72        2.72        0.049
5 F      White British     2000/01 1.48        1.48        0.080
6 F      White British     2000/01 0.25        0.25        0.171
  LSOA11_Home EAL ever_fsm
1 E01010662   1   0
2 E01010743   0   0
3 E01010745   1   1
4 E01031883   0   0
5 E01010795   0   0
6 E01017898   0   0

#### SEN cols

In [15]:
sen_filtered <- sen_filtered |>
    select(-c(EVERFSM_ALL)) |>
    arrange(person_id, desc(Year))

In [16]:
head(sen_filtered)

  person_id
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
3 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
4 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
5 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
6 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
  SourceTable        SENStage SENprovision SENprovisionMajor PrimarySENtype
1 Autumn_Census_2017 NA       K            2_SNS             NA
2 Summer_Census_2017 NA       K            2_SNS             NA
3 Spring_Census_2016 NA       K            2_SNS             ASD
4 Summer_Census_2016 NA       K            2_SNS             NA
5 Autumn_Census_2016 NA       N            1_NON             NA
6 Autumn_Census_2015 NA       N            1_NON             NA
  Year
1 2017
2 2017
3 2016
4 2016
5 2016
6 2015

In [17]:
sen_filtered |>
    distinct(Year) |> 
    pull(Year)

 [1] "2017" "2016" "2015" "2014" "2013" "2012" "2011" "2010" "2009" "2008"
[11] "2007" "2006" "2005" "2018" "2019" "2004" "2021" "2020" "2022" "2003"

In [18]:
sen_filtered_year <- sen_filtered |>
    filter(Year %in% c('2020','2019','2018','2017','2016','2015','2014','2013','2012','2011','2010','2009','2008','2007','2006','2005'))

In [19]:
sen_filtered_year |>
    nrow()

[1] 568825

In [20]:
sen_filtered_year |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 17224

In [103]:
sen_2020 <- sen_filtered_year |>
    filter(Year == '2020') |>
    filter(SENprovisionMajor != '1_NON')

In [108]:
all_2020 <- sen_filtered_year |>
    filter(Year == '2020')

In [106]:
no2020 <- sen_filtered_year |>
    filter(Year != '2020')

In [107]:
# check for any ids in 2020 but not in previous years - if 0 then can drop 2020 (post graduation)
sen_2020_only <- anti_join(sen_2020, no2020, by = "person_id")
sen_2020_only

     person_id SENStage SENprovision SENprovisionMajor PrimarySENtype Year

In [109]:
all_2020_only <- anti_join(all_2020, no2020, by = "person_id")
all_2020_only

  person_id                                                        SENStage
1 536620403E72C1652C40AB937B9A859788C9E4514D726C6CE941706924977A13 NA
  SENprovision SENprovisionMajor PrimarySENtype Year
1 N            1_NON             NA             2020

In [110]:
sen_filtered_year <- sen_filtered_year |>
    filter(Year %in% c('2019','2018','2017','2016','2015','2014','2013','2012','2011','2010','2009','2008','2007','2006','2005'))

In [111]:
# only keep the 2020 row for one person with data only in 2020 which is no sen anyway (rather than having unknown for this id)
sen_filtered_year <- rbind(sen_filtered_year,all_2020_only)

In [112]:
sen_filtered_year |>
    nrow()

[1] 261248

In [113]:
sen_filtered_year |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 17224

In [489]:
#missing_ids <- anti_join(person_ids, sen_filtered_year, by = "person_id") %>%
#  select(person_id) %>%
#  distinct()

In [490]:
#sen_filtered |>
#    filter(person_id %in% missing_ids$person_id) |>
#    distinct(Year) |>
#    pull(Year)

In [491]:
#sen_filtered |>
#    filter(person_id %in% missing_ids$person_id) |>
#    filter(Year =='2005') |>
#    summarise(count = n_distinct(person_id))

In [492]:
#sen_filtered |>
#    filter(person_id %in% missing_ids$person_id) |>
#    filter(Year =='2005')

In [114]:
sen_filtered |>
    filter(person_id =='D2C1319A064B0552A68F440AE60726DB822B2FFFF28F22B134C3EE9937A8A848')

   person_id                                                        SENStage
1  D2C1319A064B0552A68F440AE60726DB822B2FFFF28F22B134C3EE9937A8A848 NA
2  D2C1319A064B0552A68F440AE60726DB822B2FFFF28F22B134C3EE9937A8A848 NA
3  D2C1319A064B0552A68F440AE60726DB822B2FFFF28F22B134C3EE9937A8A848 NA
4  D2C1319A064B0552A68F440AE60726DB822B2FFFF28F22B134C3EE9937A8A848 NA
5  D2C1319A064B0552A68F440AE60726DB822B2FFFF28F22B134C3EE9937A8A848 NA
6  D2C1319A064B0552A68F440AE60726DB822B2FFFF28F22B134C3EE9937A8A848 NA
7  D2C1319A064B0552A68F440AE60726DB822B2FFFF28F22B134C3EE9937A8A848 NA
8  D2C1319A064B0552A68F440AE60726DB822B2FFFF28F22B134C3EE9937A8A848 NA
9  D2C1319A064B0552A68F440AE60726DB822B2FFFF28F22B134C3EE9937A8A848 NA
10 D2C1319A064B0552A68F440AE60726DB822B2FFFF28F22B134C3EE9937A8A848 NA
   SENprovision SENprovisionMajor PrimarySENtype Year
1  P            2_SNS             NA             2011
2  P            2_SNS             SLCN           2011
3  N            1_NON             NA             2010
4  P            2_SNS             SPLD           2010
5  P            2_SNS             NA             2010
6  P            NA                NA             2009
7  N            1_NON             NA             2009
8  P            NA                MLD            2008
9  P            NA                NA             2008
10 N            NA                NA             2008

In [119]:
# leave year arrange as asc so that first instance of new status remains 
sen_cut <- sen_filtered_year |>
    arrange(Year) |>
    group_by(person_id, Year) |>
    summarise(across(everything(), ~ ifelse(all(is.na(.)), NA, na.omit(.)[1])), .groups = "drop")

In [120]:
sen_cut |>
    nrow()

[1] 217384

In [121]:
sen_cut |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 17224

In [122]:
sen_cut |>
    filter(person_id == '0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD')

   person_id                                                        Year
1  0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2005
2  0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2006
3  0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2007
4  0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2008
5  0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2009
6  0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2010
7  0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2011
8  0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2012
9  0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2013
10 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2014
11 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2015
12 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2016
13 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2017
   SENStage SENprovision SENprovisionMajor PrimarySENtype
1  NA       N            NA                NA
2  NA       N            NA                NA
3  NA       N            NA                NA
4  NA       N            NA                NA
5  NA       N            1_NON             NA
6  NA       N            1_NON             NA
7  NA       N            1_NON             NA
8  NA       N            1_NON             NA
9  NA       N            1_NON             NA
10 NA       N            1_NON             NA
11 NA       N            1_NON             NA
12 NA       K            2_SNS             ASD
13 NA       K            2_SNS             NA

In [123]:
sen_cut |>
    filter(person_id == '4C4D6048A5783B8393F449A793B295C3A592D7FBCE4D44E2BFD93D25F6A96E69')

   person_id                                                        Year
1  4C4D6048A5783B8393F449A793B295C3A592D7FBCE4D44E2BFD93D25F6A96E69 2006
2  4C4D6048A5783B8393F449A793B295C3A592D7FBCE4D44E2BFD93D25F6A96E69 2007
3  4C4D6048A5783B8393F449A793B295C3A592D7FBCE4D44E2BFD93D25F6A96E69 2008
4  4C4D6048A5783B8393F449A793B295C3A592D7FBCE4D44E2BFD93D25F6A96E69 2009
5  4C4D6048A5783B8393F449A793B295C3A592D7FBCE4D44E2BFD93D25F6A96E69 2010
6  4C4D6048A5783B8393F449A793B295C3A592D7FBCE4D44E2BFD93D25F6A96E69 2011
7  4C4D6048A5783B8393F449A793B295C3A592D7FBCE4D44E2BFD93D25F6A96E69 2012
8  4C4D6048A5783B8393F449A793B295C3A592D7FBCE4D44E2BFD93D25F6A96E69 2013
9  4C4D6048A5783B8393F449A793B295C3A592D7FBCE4D44E2BFD93D25F6A96E69 2014
10 4C4D6048A5783B8393F449A793B295C3A592D7FBCE4D44E2BFD93D25F6A96E69 2015
11 4C4D6048A5783B8393F449A793B295C3A592D7FBCE4D44E2BFD93D25F6A96E69 2016
12 4C4D6048A5783B8393F449A793B295C3A592D7FBCE4D44E2BFD93D25F6A96E69 2017
13 4C4D6048A5783B8393F449A793B295C3A592D7FBCE4D44E2BFD93D25F6A96E69 2018
   SENStage SENprovision SENprovisionMajor PrimarySENtype
1  NA       N            NA                NA
2  NA       A            NA                NA
3  NA       A            NA                NA
4  NA       A            2_SNS             NA
5  NA       A            2_SNS             NA
6  NA       A            2_SNS             NA
7  NA       A            2_SNS             NA
8  NA       A            2_SNS             NA
9  NA       A            2_SNS             NA
10 NA       K            2_SNS             MLD
11 NA       N            1_NON             NA
12 NA       N            1_NON             NA
13 NA       N            1_NON             NA

In [124]:
head(sen_cut)

  person_id                                                        Year
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2005
2 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2006
3 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2007
4 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2008
5 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2009
6 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2010
  SENStage SENprovision SENprovisionMajor PrimarySENtype
1 NA       N            NA                NA
2 NA       N            NA                NA
3 NA       N            NA                NA
4 NA       N            NA                NA
5 NA       N            1_NON             NA
6 NA       N            1_NON             NA

#### clean SEN cols

In [125]:
sen_cut |> 
    nrow()

[1] 217384

In [126]:
sen_cut |>
    group_by(SENStage) |>
    tally()

  SENStage n
1 NA       217384

In [127]:
sen_clean <- sen_cut |>
    select(-SENStage)

In [128]:
sen_clean |>
    group_by(SENprovision) |>
    tally() |>
    arrange(desc(n))

  SENprovision n
1 N            175189
2 A             20926
3 P              9563
4 K              7049
5 S              3627
6 E              1028
7 e                 2

In [129]:
sen_clean <- sen_clean |>
    mutate(SENprovisionNEW = case_when(
        SENprovision %in% c('N') ~ 'No SEN',
        SENprovision %in% c('A','P','K') ~ 'SEN support',
        SENprovision %in% c('S','E') ~ 'EHC plan',
        TRUE ~ NA
            )
         )

In [130]:
head(sen_clean)

  person_id                                                        Year
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2005
2 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2006
3 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2007
4 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2008
5 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2009
6 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2010
  SENprovision SENprovisionMajor PrimarySENtype SENprovisionNEW
1 N            NA                NA             No SEN
2 N            NA                NA             No SEN
3 N            NA                NA             No SEN
4 N            NA                NA             No SEN
5 N            1_NON             NA             No SEN
6 N            1_NON             NA             No SEN

In [131]:
sen_clean |>
    group_by(SENprovisionMajor) |>
    tally()

  SENprovisionMajor n
1 1_NON             129857
2 2_SNS              31503
3 3_SS                4184
4 NA                 51840

In [132]:
sen_clean <- sen_clean |>
    select(-SENprovision) |>
    mutate(SENmajorNEW = case_when(
        SENprovisionMajor == '1_NON' ~ 'No SEN',
        SENprovisionMajor == '2_SNS' ~ 'SEN support',
        SENprovisionMajor == '3_SS' ~ 'EHC plan',
        TRUE ~ NA
            )
         )

In [133]:
head(sen_clean)

  person_id                                                        Year
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2005
2 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2006
3 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2007
4 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2008
5 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2009
6 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2010
  SENprovisionMajor PrimarySENtype SENprovisionNEW SENmajorNEW
1 NA                NA             No SEN          NA
2 NA                NA             No SEN          NA
3 NA                NA             No SEN          NA
4 NA                NA             No SEN          NA
5 1_NON             NA             No SEN          No SEN
6 1_NON             NA             No SEN          No SEN

In [134]:
# check where two new cols dont match
sen_clean |>
    filter(SENprovisionNEW != SENmajorNEW & !is.na(SENprovisionNEW) & !is.na(SENmajorNEW))

    person_id                                                        Year
1   0054192801954D860BB235F844AD1CB8A99956B2CF3D4E20F83C650DD6279B58 2009
2   01B893444938704BE6DF40B1FDF71CE4741DF8F2A102BA6068B1401827A8BA1E 2009
3   01DD211111ECE9C51A992B85C0E53F8F3A604974F18AD8B5C0C2A2071C05D8DC 2009
4   02186E060FD3D7B6FE18E6592CB04AF4CD2ADAA753D0CE3CDA81D2D8479CABEA 2009
5   024B506650AA53563BCC08BBC93D7746728699078E4FEAFA951991731066A93B 2009
6   035392BAC7F954291C7B2B244E0225041403D4603261ABFDAAEC64C4A2C6A6AD 2009
7   062C48DE2C8CCADC19321E70514E5A072661A4E07A7EC55FC2427710CA555127 2009
8   06855F3F21AD13B045330156289C42DD01E690C2ECD6BF45A330BF4FDBE166EE 2009
9   068E6217CC38D05AEEAFBC7827F078C4242EDC81CA0A27D4444E320868269411 2009
10  0752094453692B7C73C81F509D43683AF97513283DBB134F4DAF7D7162F02D80 2009
11  07C8C6292C6591AB6ECB8A2C853375893BE13C0E5A87F158825F62125CF895FF 2009
12  0850DF112CD7023A1B2325EAB8D60300C87FAA2065582E2AB02B416397BB9954 2009
13  08D18AB508762C2294E0A028E80E41D731B4D5824A911884F01E44C5D41BAA54 2009
14  08FD9831432E0BCF8BA1E3EEB051E6BF00D84BF6AD0DD51CFA8B0F0AD4B0C413 2009
15  0B1B78C8FF0AC3C851BA67FEBDC7C31BC6E9A765BCAA2A2266DCDDD88F509668 2009
16  0B98602A88411CF933B4803062ED9D2764F9F3CA21E7E8CF1A4E97B79DE19E16 2009
17  0C506AB0E5CAE896E9417B8DE029FAF59A8179C26936ECBD668913F76563A322 2009
18  0CBA412DFB537B02B11AD6A50C8E2C194F08AF4BE706737443776CCB282A5F98 2009
19  0CE55E1C1ECEEF9AD2F7CFADC4C074C5C5E1D44F81C453383D9EF17E65E817D2 2009
20  0D2314F894DB8B3D06A62D2AAF1FEAF53948011D5D928FA288D3EF520433EEA8 2009
21  0D5BABE74A35CC1F64DB2C1F97898AD55B2DF12975FE992FE28487B958392B33 2009
22  0DE7EC49EF234273401DC2B214B3C7F98BAFD9A537583535D74E47BAFAA8CA45 2009
23  0E0340B5F62DCA1C8165031D4B3BD2147DA439A06DC15304AB31C45A8C73B90D 2009
24  0E4F3E4F33A74560DEE913621BE1EF3B4E6C9539FFEA3B2902F5379B76CE647D 2009
25  0E87BBC376B0E27FCD64DBBECADA20D0F1CF0387B9171D2CAEEDAEDE581D1346 2009
26  0F58B15ABACF2CC2A799B53D23633B5C0DEEFC6A71596A97B6A060668D0D03D0 2009
27  100C845448933206C740C7FA71C59DB28AC345AB1B12A5822106FA6CC9D8AD58 2009
28  10B87E4FF5C1432DC80889786B503523CF800F0B167755A9CD90BA8DBB6F8409 2009
29  115D952F6012B91FB4F07100FEA8B98D14BF011D6B3528EDD92A4964A92B0407 2009
30  11FFCBF229174374C98A38E4551C77CC8A4F69E8C9DBF4A30E6FB02C3D108813 2009
⋮   ⋮                                                                ⋮
345 F0DACCB18B20E8D3A4C0E40CA4AF963989A5C88A197A7F29FE44FC0B8D7AE620 2009
346 F0F1704E532DB4E15BD14EE99D595A8DA2AA6BC3AB95BAED69E9B3CA189CE54C 2009
347 F0F5B57C0350698BED89A26E15E341E1FCD13D9AFCB7BFDD8F764CA02B7B5AFE 2009
348 F11185B3087A51DFF7DB1D6081AB997CB327D2745BC994D9B28E72F24ADA68BB 2009
349 F14C809A3BE9B7AB58086FD27FC9697883D3BB56706217DAA86BD31241B63893 2009
350 F31198C24B4E1897F697E1ECA82A7C9E47EA2730D96E383D53F813FDA0E694E1 2009
351 F4282781520289C029A234979C05103DF1DA62372669822F727B26D972D3C760 2009
352 F5C2CE6A9A8DA2D7A8A04494A9858A4DB2CEB289938AB159E9C29999E93BFFE1 2009
353 F5C439C4621F5C5E1CAD5C9D2FA149599439142A6B5C54362D1190B075D5D82E 2009
354 F5EA8F2FA88A3D8296C7921100435C7122B670B05A85B78A92DDB73AE9D74D0A 2009
355 F60BEAA253304AA82285D030F6CCBA96E5EFECF0B27EEDC7829E9A5A7B964364 2009
356 F66AA16A1973F3D07197F37976ABD513559D282752E8F35B55FBD57AD6CA4EC5 2009
357 F693D44FA1806D584174DDB40752FFC223D78CA94E4885FA4072E4B3AAFEB281 2009
358 F79E53F097830301020F9C298721EE9546557BDD77412A348F5CFE6938F228CE 2009
359 F7B2F70BAF8F9266647EA2348E35FF6BC90D65B53D54262623BD159641A2C3C6 2009
360 F7E987B129510D1D383CEE39038846EE2C4D7E537A334555CA3457F17D71B2A7 2009
361 F813187ED01DA5421BD6F3550CA3D7E5792B1A50BFE1F4F3605E9F7BB5CF24C2 2009
362 F8430F6723740BD3C474A7E982DFA61C64B3D0C63C14373817354B2CBFA20C02 2009
363 F8C0AAE5F856B0DE27F55F65FE476C0685B389C333001F76D18752742AB3F3F3 2009
364 F8D52B68D7A14929EF0EA782995B8F12F41A08B08A10713FD7CC02B95AA3F6E1 2009
365 FB3B50C7CF7C0B1A18B660F28E8F7D77280B63227DDD9C8270A666FA1EF15B38 2009
366 FB99E9F20F4B4D362724252775908D2C27E0BEF94E5DFCE2BBE2C5D214F3251E 2009
367 FC4A9A9ECC56374706EC415D1FA433DF7C815C0F5048A15BF7AF96DF0CEF3933 2009
368 FC76E4E1E31A0FFC720EB75C27B4126CAD3149966DD458DC9001B563A024F7E9 2009
369 FCD52BCF3860E78C28825736A0A768EDA5E2C53218FBD9882E9F32A4AECBC7D3 2009
370 FD5F1DCC8BB24ACE60D91BE400E31AD82217EDDCE7EDAACBB65505CDC1BBEB54 2009
371 FDBE0448D4959DB5165A9BB71940DA7AD6671E211F87870ACF8D6F72A6BA7A07 2009
372 FE0B0E1715FEC0A05ACDC10E01C64CD9C33CDE60F5197C6B7899F2DFCE590E22 2009
373 FE2450CAD4985B32D79C8E801120919C4D229C4F6192F1934D9B1CEE944DB3D7 2009
374 FE68794865B2A4C26FEB820A1FC64CBD16FBB513726F675F8059CC856169904D 2009
    SENprovisionMajor PrimarySENtype SENprovisionNEW SENmajorNEW
1   1_NON             NA             SEN support     No SEN
2   2_SNS             NA             No SEN          SEN support
3   2_SNS             SLD            No SEN          SEN support
4   1_NON             NA             SEN support     No SEN
5   2_SNS             NA             No SEN          SEN support
6   2_SNS             NA             No SEN          SEN support
7   2_SNS             NA             No SEN          SEN support
8   1_NON             NA             SEN support     No SEN
9   1_NON             NA             SEN support     No SEN
10  1_NON             NA             SEN support     No SEN
11  2_SNS             NA             No SEN          SEN support
12  2_SNS             NA             No SEN          SEN support
13  2_SNS             NA             No SEN          SEN support
14  3_SS              ASD            SEN support     EHC plan
15  2_SNS             NA             No SEN          SEN support
16  1_NON             NA             SEN support     No SEN
17  1_NON             NA             SEN support     No SEN
18  2_SNS             NA             No SEN          SEN support
19  2_SNS             NA             No SEN          SEN support
20  1_NON             NA             SEN support     No SEN
21  2_SNS             NA             No SEN          SEN support
22  2_SNS             NA             No SEN          SEN support
23  2_SNS             BESD           No SEN          SEN support
24  2_SNS             NA             No SEN          SEN support
25  2_SNS             NA             No SEN          SEN support
26  1_NON             NA             SEN support     No SEN
27  1_NON             NA             SEN support     No SEN
28  2_SNS             NA             No SEN          SEN support
29  2_SNS             NA             No SEN          SEN support
30  1_NON             NA             SEN support     No SEN
⋮   ⋮                 ⋮              ⋮               ⋮
345 2_SNS             NA             No SEN          SEN support
346 2_SNS             NA             No SEN          SEN support
347 3_SS              PD             SEN support     EHC plan
348 2_SNS             NA             No SEN          SEN support
349 3_SS              MLD            SEN support     EHC plan
350 3_SS              BESD           SEN support     EHC plan
351 1_NON             NA             SEN support     No SEN
352 2_SNS             NA             No SEN          SEN support
353 1_NON             NA             SEN support     No SEN
354 2_SNS             NA             No SEN          SEN support
355 2_SNS             SLCN           No SEN          SEN support
356 2_SNS             NA             No SEN          SEN support
357 2_SNS             NA             No SEN          SEN support
358 2_SNS             NA             No SEN          SEN support
359 2_SNS             NA             No SEN          SEN support
360 2_SNS             NA             No SEN          SEN support
361 2_SNS             NA             No SEN          SEN support
362 2_SNS             NA             No SEN          SEN support
363 2_SNS             NA             No SEN          SEN support
364 2_SNS             NA             No SEN          SEN support
365 2_SNS             NA             No SEN          SEN support
366 2_SNS             NA             No SEN          SEN support
367 2_SNS             NA             No SEN          SEN support
368 2_SNS             NA             No SEN          SEN support
369 2_SNS             NA             No SEN          SEN support
370 2_SNS             NA             No SEN          SEN support
371 2_SNS             NA             No SEN          SEN support
372 2_SNS             NA             No SEN          SEN support
373 1_NON             NA             SEN support     No SEN
374 2_SNS             NA             No SEN          SEN support

In [135]:
# merge values across two new cols
# where one of the new cols is no sen and the other is sen, keep sen
sen_clean <- sen_clean |>
    mutate(SENlevel = case_when(
        SENprovisionNEW == SENmajorNEW ~ SENprovisionNEW,  # both are the same
        is.na(SENprovisionNEW) & !is.na(SENmajorNEW) ~ SENmajorNEW,  # drop NA
        !is.na(SENprovisionNEW) & is.na(SENmajorNEW) ~ SENprovisionNEW,  # drop NA
        SENprovisionNEW == "No SEN" & SENmajorNEW == "SEN support" ~ SENmajorNEW,  # SEN support over No SEN
        SENprovisionNEW == "SEN support" & SENmajorNEW == "No SEN" ~ SENprovisionNEW,  # SEN support over No SEN
        SENprovisionNEW == "SEN support" & SENmajorNEW == "EHC plan" ~ SENmajorNEW,  # EHC plan over SEN support 
        SENprovisionNEW == "EHC plan" & SENmajorNEW == "SEN support" ~ SENprovisionNEW,  # EHC plan over SEN support 
        SENprovisionNEW == "No SEN" & SENmajorNEW == "EHC plan" ~ SENmajorNEW,  # EHC plan over SEN support 
        TRUE ~ NA
  ))

In [136]:
# check where two new cols dont match incase of EHCP col not matching
sen_clean |>
    filter(is.na(SENlevel))

     person_id Year SENprovisionMajor PrimarySENtype SENprovisionNEW
     SENmajorNEW SENlevel

In [137]:
sen_clean <- sen_clean |>
    select(-SENprovisionMajor)

In [138]:
sen_clean |>
    filter(person_id == 'A26C103463F0FCEC6212A7BCE763E627E221E9F0ABDF45246C92E7BC89F9F23E')

   person_id                                                        Year
1  A26C103463F0FCEC6212A7BCE763E627E221E9F0ABDF45246C92E7BC89F9F23E 2005
2  A26C103463F0FCEC6212A7BCE763E627E221E9F0ABDF45246C92E7BC89F9F23E 2006
3  A26C103463F0FCEC6212A7BCE763E627E221E9F0ABDF45246C92E7BC89F9F23E 2007
4  A26C103463F0FCEC6212A7BCE763E627E221E9F0ABDF45246C92E7BC89F9F23E 2008
5  A26C103463F0FCEC6212A7BCE763E627E221E9F0ABDF45246C92E7BC89F9F23E 2009
6  A26C103463F0FCEC6212A7BCE763E627E221E9F0ABDF45246C92E7BC89F9F23E 2010
7  A26C103463F0FCEC6212A7BCE763E627E221E9F0ABDF45246C92E7BC89F9F23E 2011
8  A26C103463F0FCEC6212A7BCE763E627E221E9F0ABDF45246C92E7BC89F9F23E 2012
9  A26C103463F0FCEC6212A7BCE763E627E221E9F0ABDF45246C92E7BC89F9F23E 2013
10 A26C103463F0FCEC6212A7BCE763E627E221E9F0ABDF45246C92E7BC89F9F23E 2014
11 A26C103463F0FCEC6212A7BCE763E627E221E9F0ABDF45246C92E7BC89F9F23E 2015
12 A26C103463F0FCEC6212A7BCE763E627E221E9F0ABDF45246C92E7BC89F9F23E 2016
13 A26C103463F0FCEC6212A7BCE763E627E221E9F0ABDF45246C92E7BC89F9F23E 2017
   PrimarySENtype SENprovisionNEW SENmajorNEW SENlevel
1  MLD            SEN support     NA          SEN support
2  NA             No SEN          NA          No SEN
3  NA             SEN support     NA          SEN support
4  SLCN           SEN support     NA          SEN support
5  SLCN           EHC plan        EHC plan    EHC plan
6  SLCN           EHC plan        EHC plan    EHC plan
7  SLCN           EHC plan        EHC plan    EHC plan
8  SLCN           EHC plan        EHC plan    EHC plan
9  MLD            EHC plan        EHC plan    EHC plan
10 MLD            EHC plan        EHC plan    EHC plan
11 MLD            EHC plan        EHC plan    EHC plan
12 MLD            EHC plan        EHC plan    EHC plan
13 NA             EHC plan        EHC plan    EHC plan

In [139]:
sen_clean |>
    filter(person_id == '0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7')

   person_id                                                        Year
1  0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2006
2  0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2007
3  0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2008
4  0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2009
5  0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2010
6  0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2011
7  0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2012
8  0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2013
9  0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2014
10 0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2015
11 0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2016
12 0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2017
13 0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2018
   PrimarySENtype SENprovisionNEW SENmajorNEW SENlevel
1  NA             No SEN          NA          No SEN
2  NA             No SEN          NA          No SEN
3  NA             No SEN          NA          No SEN
4  NA             No SEN          No SEN      No SEN
5  NA             No SEN          No SEN      No SEN
6  NA             No SEN          No SEN      No SEN
7  NA             No SEN          No SEN      No SEN
8  NA             No SEN          No SEN      No SEN
9  MLD            SEN support     SEN support SEN support
10 MLD            SEN support     SEN support SEN support
11 MLD            SEN support     SEN support SEN support
12 NA             SEN support     SEN support SEN support
13 NA             SEN support     SEN support SEN support

In [140]:
sen_clean <- sen_clean |>
    select(-c(SENprovisionNEW,SENmajorNEW))

In [141]:
sen_clean

       person_id                                                        Year
1      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2005
2      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2006
3      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2007
4      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2008
5      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2009
6      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2010
7      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2011
8      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2012
9      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2013
10     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2014
11     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2015
12     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2016
13     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2017
14     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2005
15     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2006
16     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2007
17     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2008
18     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2009
19     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2010
20     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2011
21     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2012
22     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2013
23     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2014
24     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2015
25     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2016
26     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2017
27     0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2005
28     0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2007
29     0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2008
30     0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2009
⋮      ⋮                                                                ⋮
217355 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77 2017
217356 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77 2018
217357 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77 2019
217358 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2005
217359 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2006
217360 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2007
217361 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2008
217362 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2009
217363 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2010
217364 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2011
217365 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2012
217366 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2013
217367 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2014
217368 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2015
217369 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2016
217370 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2017
217371 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2018
217372 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2005
217373 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2006
217374 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2007
217375 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2008
217376 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2009
217377 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2010
217378 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2011
217379 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2012
217380 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2013
217381 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2014
217382 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2015
217383 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2016
217384 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2017
       PrimarySENtype SENlevel
1      NA             No SEN
2      NA             No SEN
3      NA             No SEN
4      NA             No SEN
5      NA             No SEN
6      NA             No SEN
7      NA             No SEN
8      NA             No SEN
9      NA             No SEN
10     NA             No SEN
11     NA             No SEN
12     ASD            SEN support
13     NA             SEN support
14     NA             No SEN
15     NA             No SEN
16     MLD            SEN support
17     MLD            SEN support
18     MLD            SEN support
19     MLD            SEN support
20     MLD            SEN support
21     MLD            SEN support
22     MLD            SEN support
23     MLD            SEN support
24     MLD            SEN support
25     MLD            SEN support
26     NA             SEN support
27     SLCN           SEN support
28     NA             No SEN
29     NA             No SEN
30     MLD            SEN support
⋮      ⋮              ⋮
217355 NA             No SEN
217356 NA             No SEN
217357 NA             No SEN
217358 NA             No SEN
217359 NA             No SEN
217360 NA             No SEN
217361 NA             No SEN
217362 NA             No SEN
217363 NA             No SEN
217364 NA             No SEN
217365 NA             No SEN
217366 NA             No SEN
217367 NA             No SEN
217368 NA             No SEN
217369 NA             No SEN
217370 NA             No SEN
217371 NA             No SEN
217372 NA             No SEN
217373 NA             No SEN
217374 NA             No SEN
217375 NA             No SEN
217376 NA             SEN support
217377 NA             SEN support
217378 NA             No SEN
217379 NA             No SEN
217380 NA             No SEN
217381 NA             No SEN
217382 NA             No SEN
217383 NA             No SEN
217384 NA             No SEN

In [147]:
# copy previous value where sen level is the same but type is NA
sen_clean <- sen_clean |>
    arrange(person_id, Year) |>  
    group_by(person_id) |>
    mutate(PrimarySENtype = case_when(
          # if NA and SENlevel is same, and prev not NA take prev value
          is.na(PrimarySENtype) & lag(SENlevel) == SENlevel & !is.na(lag(PrimarySENtype)) ~ lag(PrimarySENtype),  
          TRUE ~ PrimarySENtype  # Keep original value otherwise
        )) |>
    #fill(PrimarySENtype, .direction = "down") |>
    ungroup()

In [149]:
# repeat
sen_clean <- sen_clean |>
    arrange(person_id, Year) |>  
    group_by(person_id) |>
    mutate(PrimarySENtype = case_when(
          # if NA and SENlevel is same, and prev not NA take prev value
          is.na(PrimarySENtype) & lag(SENlevel) == SENlevel & !is.na(lag(PrimarySENtype)) ~ lag(PrimarySENtype),  
          TRUE ~ PrimarySENtype  # Keep original value otherwise
        )) |>
    #fill(PrimarySENtype, .direction = "down") |>
    ungroup()

What are the implications of having an SEN but it only being identified / support being put in place when in year 11???

In [143]:
person_ids |>
    filter(person_id == '0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD')

  person_id                                                        NCCIS_ACADYR
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2017/2018

In [151]:
sen_clean |>
    filter(SENlevel != 'No SEN')

      person_id                                                        Year
1     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2016
2     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2017
3     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2007
4     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2008
5     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2009
6     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2010
7     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2011
8     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2012
9     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2013
10    00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2014
11    00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2015
12    00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2016
13    00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2017
14    0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2005
15    0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2009
16    0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2010
17    0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2011
18    0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2012
19    0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2013
20    0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2014
21    0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2015
22    0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2016
23    0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2017
24    0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2018
25    0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2014
26    0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2015
27    0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2016
28    0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2017
29    0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2018
30    0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D 2017
⋮     ⋮                                                                ⋮
42435 FFD30596592DA2C82B86241FBA35E56C7384E7EF8219DB076458B4F9ACDED786 2009
42436 FFD30596592DA2C82B86241FBA35E56C7384E7EF8219DB076458B4F9ACDED786 2010
42437 FFD30596592DA2C82B86241FBA35E56C7384E7EF8219DB076458B4F9ACDED786 2012
42438 FFD30596592DA2C82B86241FBA35E56C7384E7EF8219DB076458B4F9ACDED786 2013
42439 FFD30596592DA2C82B86241FBA35E56C7384E7EF8219DB076458B4F9ACDED786 2014
42440 FFD30596592DA2C82B86241FBA35E56C7384E7EF8219DB076458B4F9ACDED786 2017
42441 FFD391941F3AA9CB910FFFACF24CC2CEAD0BC63EED146E9C21B2C71BA77B084A 2018
42442 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2006
42443 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2009
42444 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2010
42445 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2011
42446 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2012
42447 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2013
42448 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2014
42449 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2015
42450 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2016
42451 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2017
42452 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2018
42453 FFE1AA7D705C959745A85B91C6D3F3D22A57B8E50092E9EC25046F6986F77D96 2012
42454 FFE1AA7D705C959745A85B91C6D3F3D22A57B8E50092E9EC25046F6986F77D96 2013
42455 FFE1AA7D705C959745A85B91C6D3F3D22A57B8E50092E9EC25046F6986F77D96 2014
42456 FFE1AA7D705C959745A85B91C6D3F3D22A57B8E50092E9EC25046F6986F77D96 2015
42457 FFE1AA7D705C959745A85B91C6D3F3D22A57B8E50092E9EC25046F6986F77D96 2016
42458 FFE1AA7D705C959745A85B91C6D3F3D22A57B8E50092E9EC25046F6986F77D96 2017
42459 FFE837A538A9166CC4089E844F651277391B496479F4691CE27BF1000C49223B 2014
42460 FFEFD5577D0112E9304118DB7851CF61BEE4DD3D3184EEA756C076317925508F 2008
42461 FFEFD5577D0112E9304118DB7851CF61BEE4DD3D3184EEA756C076317925508F 2009
42462 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77 2013
42463 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2009
42464 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2010
      PrimarySENtype SENlevel
1     ASD            SEN support
2     ASD            SEN support
3     MLD            SEN support
4     MLD            SEN support
5     MLD            SEN support
6     MLD            SEN support
7     MLD            SEN support
8     MLD            SEN support
9     MLD            SEN support
10    MLD            SEN support
11    MLD            SEN support
12    MLD            SEN support
13    MLD            SEN support
14    SLCN           SEN support
15    MLD            SEN support
16    MLD            SEN support
17    MLD            SEN support
18    MLD            EHC plan
19    MLD            EHC plan
20    MLD            EHC plan
21    MLD            EHC plan
22    MLD            EHC plan
23    MLD            EHC plan
24    MLD            EHC plan
25    MLD            SEN support
26    MLD            SEN support
27    MLD            SEN support
28    MLD            SEN support
29    MLD            SEN support
30    NA             SEN support
⋮     ⋮              ⋮
42435 MLD            SEN support
42436 MLD            SEN support
42437 NA             SEN support
42438 NA             SEN support
42439 NA             SEN support
42440 NA             SEN support
42441 NA             SEN support
42442 NA             SEN support
42443 NA             SEN support
42444 NA             SEN support
42445 NA             SEN support
42446 SEMH           SEN support
42447 SEMH           SEN support
42448 SEMH           SEN support
42449 ASD            SEN support
42450 ASD            SEN support
42451 NA             EHC plan
42452 NA             EHC plan
42453 NA             SEN support
42454 NA             SEN support
42455 NA             SEN support
42456 SEMH           SEN support
42457 SEMH           SEN support
42458 SEMH           SEN support
42459 SEMH           SEN support
42460 MLD            SEN support
42461 MLD            SEN support
42462 NA             SEN support
42463 NA             SEN support
42464 NA             SEN support

In [150]:
sen_clean <- sen_clean |>
    mutate(PrimarySENtype = case_when(
        PrimarySENtype == 'BESD' ~ 'SEMH',
        TRUE ~ PrimarySENtype)
           )

#### join cohort id

In [152]:
sen_clean_cohort <- sen_clean |>
    left_join(person_ids, by = join_by(person_id))

In [153]:
sen_clean_cohort

       person_id                                                        Year
1      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2005
2      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2006
3      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2007
4      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2008
5      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2009
6      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2010
7      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2011
8      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2012
9      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2013
10     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2014
11     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2015
12     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2016
13     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2017
14     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2005
15     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2006
16     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2007
17     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2008
18     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2009
19     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2010
20     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2011
21     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2012
22     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2013
23     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2014
24     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2015
25     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2016
26     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2017
27     0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2005
28     0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2007
29     0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2008
30     0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2009
⋮      ⋮                                                                ⋮
217355 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77 2017
217356 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77 2018
217357 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77 2019
217358 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2005
217359 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2006
217360 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2007
217361 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2008
217362 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2009
217363 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2010
217364 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2011
217365 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2012
217366 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2013
217367 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2014
217368 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2015
217369 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2016
217370 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2017
217371 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2018
217372 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2005
217373 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2006
217374 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2007
217375 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2008
217376 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2009
217377 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2010
217378 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2011
217379 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2012
217380 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2013
217381 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2014
217382 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2015
217383 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2016
217384 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2017
       PrimarySENtype SENlevel    NCCIS_ACADYR
1      NA             No SEN      2017/2018
2      NA             No SEN      2017/2018
3      NA             No SEN      2017/2018
4      NA             No SEN      2017/2018
5      NA             No SEN      2017/2018
6      NA             No SEN      2017/2018
7      NA             No SEN      2017/2018
8      NA             No SEN      2017/2018
9      NA             No SEN      2017/2018
10     NA             No SEN      2017/2018
11     NA             No SEN      2017/2018
12     ASD            SEN support 2017/2018
13     ASD            SEN support 2017/2018
14     NA             No SEN      2017/2018
15     NA             No SEN      2017/2018
16     MLD            SEN support 2017/2018
17     MLD            SEN support 2017/2018
18     MLD            SEN support 2017/2018
19     MLD            SEN support 2017/2018
20     MLD            SEN support 2017/2018
21     MLD            SEN support 2017/2018
22     MLD            SEN support 2017/2018
23     MLD            SEN support 2017/2018
24     MLD            SEN support 2017/2018
25     MLD            SEN support 2017/2018
26     MLD            SEN support 2017/2018
27     SLCN           SEN support 2018/2019
28     NA             No SEN      2018/2019
29     NA             No SEN      2018/2019
30     MLD            SEN support 2018/2019
⋮      ⋮              ⋮           ⋮
217355 NA             No SEN      2018/2019
217356 NA             No SEN      2018/2019
217357 NA             No SEN      2018/2019
217358 NA             No SEN      2018/2019
217359 NA             No SEN      2018/2019
217360 NA             No SEN      2018/2019
217361 NA             No SEN      2018/2019
217362 NA             No SEN      2018/2019
217363 NA             No SEN      2018/2019
217364 NA             No SEN      2018/2019
217365 NA             No SEN      2018/2019
217366 NA             No SEN      2018/2019
217367 NA             No SEN      2018/2019
217368 NA             No SEN      2018/2019
217369 NA             No SEN      2018/2019
217370 NA             No SEN      2018/2019
217371 NA             No SEN      2018/2019
217372 NA             No SEN      2017/2018
217373 NA             No SEN      2017/2018
217374 NA             No SEN      2017/2018
217375 NA             No SEN      2017/2018
217376 NA             SEN support 2017/2018
217377 NA             SEN support 2017/2018
217378 NA             No SEN      2017/2018
217379 NA             No SEN      2017/2018
217380 NA             No SEN      2017/2018
217381 NA             No SEN      2017/2018
217382 NA             No SEN      2017/2018
217383 NA             No SEN      2017/2018
217384 NA             No SEN      2017/2018

In [156]:
sen_clean_cohort |>
    filter(person_id == '0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D')

   person_id                                                        Year
1  0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2005
2  0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2007
3  0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2008
4  0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2009
5  0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2010
6  0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2011
7  0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2012
8  0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2013
9  0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2014
10 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2015
11 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2016
12 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2017
13 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2018
   PrimarySENtype SENlevel    NCCIS_ACADYR
1  SLCN           SEN support 2018/2019
2  NA             No SEN      2018/2019
3  NA             No SEN      2018/2019
4  MLD            SEN support 2018/2019
5  MLD            SEN support 2018/2019
6  MLD            SEN support 2018/2019
7  MLD            EHC plan    2018/2019
8  MLD            EHC plan    2018/2019
9  MLD            EHC plan    2018/2019
10 MLD            EHC plan    2018/2019
11 MLD            EHC plan    2018/2019
12 MLD            EHC plan    2018/2019
13 MLD            EHC plan    2018/2019

#### check missing sen type against extras from exclusion tables

In [264]:
sen <- read.csv('data/sen_extras.csv', header = TRUE)

In [265]:
head(sen)

  person_id
1 13A5184415FCC22BFF3F2EFFD8D3B69FAB1949AFB346B8A15B449CBED2CDB473
2 02304796B373267AE442202D65322A36B8844DD043A88734014D6434DD7D1F12
3 04584E57ADBD062B2BA9DB9076CF692E45F5767837BD87EEE4FED6DB521BB84B
4 66927CC16F370C097C232D8581FB0E92E89F688DE966B50CD1A128B631F9DB6A
5 778E21A7061D57C78E5986180FAE5D061F1F8B2B69F1925CDD0FCDC4B424AEF1
6 7D46116A75B15250162ECE83B71941167D4FFAE82D39C508681D25F69C50BF32
  PrimarySENtype
1 BESD
2 BESD
3 OTH
4 MLD
5 BESD
6 BESD

In [266]:
missing_type <- sen_clean_cohort |>
    filter(SENlevel != 'No SEN' & is.na(PrimarySENtype))

In [270]:
missing_type

      person_id                                                        Year
1     0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D 2017
2     0018E26A40A6299391164D4918658B0B1248367C762DCE6D2FDF1AE131A9138C 2008
3     0018E26A40A6299391164D4918658B0B1248367C762DCE6D2FDF1AE131A9138C 2009
4     0018E26A40A6299391164D4918658B0B1248367C762DCE6D2FDF1AE131A9138C 2010
5     0018E26A40A6299391164D4918658B0B1248367C762DCE6D2FDF1AE131A9138C 2011
6     0018E26A40A6299391164D4918658B0B1248367C762DCE6D2FDF1AE131A9138C 2012
7     0018E26A40A6299391164D4918658B0B1248367C762DCE6D2FDF1AE131A9138C 2013
8     0018E26A40A6299391164D4918658B0B1248367C762DCE6D2FDF1AE131A9138C 2014
9     001E539C263734CC355646811C93CF85B0C587D2EBA8B0D79290FDE8A75D6267 2013
10    00222373A6082CDBF94DA04F23E7EB4C8775BEE122FE9C29FBF521900A498EDF 2007
11    002EF3F17C7981C3D6FD842C559E9AA0626E06B3940B670DDA2B71F7070ADF7D 2010
12    002EF3F17C7981C3D6FD842C559E9AA0626E06B3940B670DDA2B71F7070ADF7D 2011
13    002EF3F17C7981C3D6FD842C559E9AA0626E06B3940B670DDA2B71F7070ADF7D 2012
14    002EF3F17C7981C3D6FD842C559E9AA0626E06B3940B670DDA2B71F7070ADF7D 2013
15    0037AB0369C14AD5CA0340E2DFDAE2FFF22062A44A7889743C152A8163C08500 2007
16    0037AB0369C14AD5CA0340E2DFDAE2FFF22062A44A7889743C152A8163C08500 2008
17    0037AB0369C14AD5CA0340E2DFDAE2FFF22062A44A7889743C152A8163C08500 2009
18    0037AB0369C14AD5CA0340E2DFDAE2FFF22062A44A7889743C152A8163C08500 2010
19    0037AB0369C14AD5CA0340E2DFDAE2FFF22062A44A7889743C152A8163C08500 2011
20    004C012DC8B27D82CC173C9590867A88C8B60E6F4C1EAE8AF73D53403DDD94B5 2008
21    004C012DC8B27D82CC173C9590867A88C8B60E6F4C1EAE8AF73D53403DDD94B5 2009
22    004C012DC8B27D82CC173C9590867A88C8B60E6F4C1EAE8AF73D53403DDD94B5 2010
23    004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894 2010
24    004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894 2011
25    004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894 2012
26    0059AC822384B93661D2AB87E93EA6AB0847122FA139A080070E86A2F6A1910E 2017
27    00650796D5BA76B502DD9A678C2B073B9C5F8F3ECC632A169825DA5EBDE0157F 2012
28    00650796D5BA76B502DD9A678C2B073B9C5F8F3ECC632A169825DA5EBDE0157F 2013
29    0067ED874A014130F29D1A8B224F04013270A3C484F05AC9283D6A456899980C 2014
30    0067ED874A014130F29D1A8B224F04013270A3C484F05AC9283D6A456899980C 2015
⋮     ⋮                                                                ⋮
18855 FF1B348829312C228B4A93DC53CD1392EF333F07D986B308C31FC51F883F7709 2008
18856 FF1B348829312C228B4A93DC53CD1392EF333F07D986B308C31FC51F883F7709 2009
18857 FF1B348829312C228B4A93DC53CD1392EF333F07D986B308C31FC51F883F7709 2010
18858 FF35E0916282ECC5BFC997AB1F6866B5289FA0C95838F318AAD4EFCF4A04D87F 2014
18859 FF40E206271C27C81CBC640537EBD223DA63168EFE943D7A0352F840B8BC79BC 2009
18860 FF40EFF70112B4162DB955BC8B70FF0763F2A509B0D8C67F5B3CC39E60EFDFCB 2013
18861 FF40EFF70112B4162DB955BC8B70FF0763F2A509B0D8C67F5B3CC39E60EFDFCB 2014
18862 FF77AAB58760E4616819BF69FA7A7D0466EC940FC1B666F5D8FC15261B05FDA7 2007
18863 FF77AAB58760E4616819BF69FA7A7D0466EC940FC1B666F5D8FC15261B05FDA7 2015
18864 FF77AAB58760E4616819BF69FA7A7D0466EC940FC1B666F5D8FC15261B05FDA7 2018
18865 FF85D28F3D4272EF3EDA67E52BC94BB3A529BD2CD31D32EF21FB8157396EF57D 2007
18866 FF85D28F3D4272EF3EDA67E52BC94BB3A529BD2CD31D32EF21FB8157396EF57D 2008
18867 FF85FB47EF271836ECDF7555602263FC0E52F8A84F39868EE7B66E30E47DF618 2010
18868 FFD30596592DA2C82B86241FBA35E56C7384E7EF8219DB076458B4F9ACDED786 2012
18869 FFD30596592DA2C82B86241FBA35E56C7384E7EF8219DB076458B4F9ACDED786 2013
18870 FFD30596592DA2C82B86241FBA35E56C7384E7EF8219DB076458B4F9ACDED786 2014
18871 FFD30596592DA2C82B86241FBA35E56C7384E7EF8219DB076458B4F9ACDED786 2017
18872 FFD391941F3AA9CB910FFFACF24CC2CEAD0BC63EED146E9C21B2C71BA77B084A 2018
18873 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2006
18874 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2009
18875 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2010
18876 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2011
18877 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2017
18878 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2018
18879 FFE1AA7D705C959745A85B91C6D3F3D22A57B8E50092E9EC25046F6986F77D96 2012
18880 FFE1AA7D705C959745A85B91C6D3F3D22A57B8E50092E9EC25046F6986F77D96 2013
18881 FFE1AA7D705C959745A85B91C6D3F3D22A57B8E50092E9EC25046F6986F77D96 2014
18882 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77 2013
18883 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2009
18884 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2010
      PrimarySENtype SENlevel    NCCIS_ACADYR
1     NA             SEN support 2017/2018
2     NA             SEN support 2018/2019
3     NA             SEN support 2018/2019
4     NA             SEN support 2018/2019
5     NA             SEN support 2018/2019
6     NA             SEN support 2018/2019
7     NA             SEN support 2018/2019
8     NA             SEN support 2018/2019
9     NA             SEN support 2017/2018
10    NA             SEN support 2017/2018
11    NA             SEN support 2018/2019
12    NA             SEN support 2018/2019
13    NA             SEN support 2018/2019
14    NA             SEN support 2018/2019
15    NA             SEN support 2017/2018
16    NA             SEN support 2017/2018
17    NA             SEN support 2017/2018
18    NA             SEN support 2017/2018
19    NA             SEN support 2017/2018
20    NA             SEN support 2018/2019
21    NA             SEN support 2018/2019
22    NA             SEN support 2018/2019
23    NA             SEN support 2017/2018
24    NA             SEN support 2017/2018
25    NA             SEN support 2017/2018
26    NA             SEN support 2017/2018
27    NA             SEN support 2017/2018
28    NA             SEN support 2017/2018
29    NA             SEN support 2018/2019
30    NA             SEN support 2018/2019
⋮     ⋮              ⋮           ⋮
18855 NA             SEN support 2017/2018
18856 NA             SEN support 2017/2018
18857 NA             SEN support 2017/2018
18858 NA             SEN support 2018/2019
18859 NA             SEN support 2018/2019
18860 NA             SEN support 2018/2019
18861 NA             SEN support 2018/2019
18862 NA             SEN support 2018/2019
18863 NA             SEN support 2018/2019
18864 NA             EHC plan    2018/2019
18865 NA             SEN support 2017/2018
18866 NA             SEN support 2017/2018
18867 NA             SEN support 2018/2019
18868 NA             SEN support 2017/2018
18869 NA             SEN support 2017/2018
18870 NA             SEN support 2017/2018
18871 NA             SEN support 2017/2018
18872 NA             SEN support 2018/2019
18873 NA             SEN support 2017/2018
18874 NA             SEN support 2017/2018
18875 NA             SEN support 2017/2018
18876 NA             SEN support 2017/2018
18877 NA             EHC plan    2017/2018
18878 NA             EHC plan    2017/2018
18879 NA             SEN support 2017/2018
18880 NA             SEN support 2017/2018
18881 NA             SEN support 2017/2018
18882 NA             SEN support 2018/2019
18883 NA             SEN support 2017/2018
18884 NA             SEN support 2017/2018

In [267]:
# Check if all person_ids in person_id are in person
any(sen$person_id %in% missing_type$person_id)

[1] TRUE

In [268]:
sum(sen$person_id %in% missing_type$person_id)

[1] 772

In [269]:
sen <- sen |>
    mutate(PrimarySENtype = case_when(
        PrimarySENtype == 'BESD' ~ 'SEMH',
        TRUE ~ PrimarySENtype)
           )

#### compute 'ever' values

In [155]:
sen_clean_cohort <- sen_clean_cohort |> 
  mutate(Year = as.integer(Year))  # Convert Year to integer

In [171]:
sen_final <- sen_clean_cohort |> 
  group_by(person_id) |> 
  summarize(
    ever_SEN_support = any(SENlevel == "SEN support"),
    first_SEN_support_year = ifelse(ever_SEN_support, min(Year[SENlevel == "SEN support"], na.rm = TRUE), NA),
    SEN_support_need = ifelse(ever_SEN_support, paste(na.omit(unique(PrimarySENtype[SENlevel == "SEN support"])), collapse = ", "), NA),

    ever_EHC_plan = any(SENlevel == "EHC plan"),
    first_EHC_plan_year = ifelse(ever_EHC_plan, min(Year[SENlevel == "EHC plan"], na.rm = TRUE), NA),
    EHC_plan_need = ifelse(ever_EHC_plan, paste(na.omit(unique(PrimarySENtype[SENlevel == "EHC plan"])), collapse = ", "), NA),

    no_SEN = all(SENlevel == "No SEN")
  )

In [172]:
sen_final

      person_id
1     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
3     0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D
4     0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7
5     00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66
6     0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D
7     0018E26A40A6299391164D4918658B0B1248367C762DCE6D2FDF1AE131A9138C
8     0019031CD62586D59268772800516ED50CDF1EF7DE46488542BB031850F6E68A
9     001B7CEB7B4CC529920A0B9F5B83D1AC0019E5DC44B3FBB3CEF665C331C0C3B6
10    001E539C263734CC355646811C93CF85B0C587D2EBA8B0D79290FDE8A75D6267
11    001E5C1FFA964716BF5E84562BC0B5D64F7742B1E8126718A5C0157D485F215D
12    001F566795F57F5D8DD92430D868A38B757699844E3E09569B33253527012932
13    001FFD3AA96B7E4FC5BB9A2F7502CD45BFCC35882335F1C34F78DD9AE5667225
14    00222373A6082CDBF94DA04F23E7EB4C8775BEE122FE9C29FBF521900A498EDF
15    002AB68E0EC9459837DD6159160BF8C592504B5F0EE3160A22051398D20C3FFC
16    002E041C5100C46E33B8A0C0220BDE85A79111C5D0E26742F6278C059930FAF6
17    002EF3F17C7981C3D6FD842C559E9AA0626E06B3940B670DDA2B71F7070ADF7D
18    003132A725233755576CF96E5AA2B3DF606A618754D4BDDFCDD5483849E7B946
19    00341B29C42EC823E9D06B625E751614D66794F1096E2F045DDE51DB64C9C623
20    0037AB0369C14AD5CA0340E2DFDAE2FFF22062A44A7889743C152A8163C08500
21    003D2F5BDBC025915EE2AA9CCB96F54F72F003BF7DC6939849ADD6CCD1048ABC
22    0048AA244E75570B74E82BDC60D09008D5E728E78E60FB96AA0E762DBD0E818E
23    004AC6875C0259256CBCBC00373E9D09131E7D064B6089B9EB26F821F8297775
24    004C012DC8B27D82CC173C9590867A88C8B60E6F4C1EAE8AF73D53403DDD94B5
25    004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
26    005087BCA7BEC31B79A3CA446453131C51CD1DC3296FE71B509E46AA984FFAE3
27    0052FF7683A04EBA481AFA53811E1707DBAB62007649EA0C4CE89C8498C06C97
28    0054192801954D860BB235F844AD1CB8A99956B2CF3D4E20F83C650DD6279B58
29    0059AC822384B93661D2AB87E93EA6AB0847122FA139A080070E86A2F6A1910E
30    005A3BB3D150E6AFDC0C4DDCEE6DB850E746A6E2F7760B727CF97B659BC2F483
⋮     ⋮
17195 FF77AAB58760E4616819BF69FA7A7D0466EC940FC1B666F5D8FC15261B05FDA7
17196 FF785EF44C283B9E43E7F206B8848D7C550C36E7E8E5DA0A2B6267CABC0AE447
17197 FF7AC7331F6B988DCFBCFA5C55F7984D5BA33735D4DDB4671F30E37176A7B40D
17198 FF7B98BFE21CD2600469C9D7B3C040C06C1AAAB58F51EE3BE5A0E0CA94470300
17199 FF7B9B8977DE09E00DDE57866479BEED54F7BC5730E38C61A15A220CAF2C507B
17200 FF85D28F3D4272EF3EDA67E52BC94BB3A529BD2CD31D32EF21FB8157396EF57D
17201 FF85FB47EF271836ECDF7555602263FC0E52F8A84F39868EE7B66E30E47DF618
17202 FF8C66C8699FEF1708ABC2DADF11D78283107FADB514F81D4219017A8D26E2DE
17203 FF9024B3D2775BB5CC65F8872CB1A8BECAD9A7E25FBB3C3DF7D46A8A1BE31AC1
17204 FF94BC38B3E8FE01672532C523A4C00ABB2F9C7B3CDFF6C78F2DA080B544B09A
17205 FF94D3F7FDB40C124787D0EBA0CD7660187135442D800F18C11487D380F55663
17206 FF9B2F9502DAFBC1EFB04109BEFF47C64A04801619DE844A3DAD073DD45D99D1
17207 FFAA13CCE7B35BA3D3A737EF1A13BCE2289A94F9778EC0C9F18CD77F1B93C979
17208 FFACDC831FAAA09353CAB36C5828F34E508AC8BFED1B4B07999BAF198CAC4EEA
17209 FFBCE0C32A37E3663F1C5159ECFC6F08CD5722E938464A58634F3263003F1D9F
17210 FFC0379FDA559C1337454C579FF36F9AE82E62D16B3223D009C57DEC3731754C
17211 FFC7129859DD885141E316248A0EB23059DB0F0DB98242C34C67F06FBBAB8041
17212 FFC96F346EC6829E7A31F60109FD729DE208D180104B50FC8B1BFAD552D6C8FC
17213 FFD30596592DA2C82B86241FBA35E56C7384E7EF8219DB076458B4F9ACDED786
17214 FFD391941F3AA9CB910FFFACF24CC2CEAD0BC63EED146E9C21B2C71BA77B084A
17215 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951
17216 FFE1AA7D705C959745A85B91C6D3F3D22A57B8E50092E9EC25046F6986F77D96
17217 FFE837A538A9166CC4089E844F651277391B496479F4691CE27BF1000C49223B
17218 FFEA068077E4464D059236951F07D7DF96542C2197AAFAC3E20C036BACB9825C
17219 FFEF2AA9E8BD72D6A0E7CE50F067E4247E12738F53AE726CD94A4D9CB588C702
17220 FFEFD5577D0112E9304118DB7851CF61BEE4DD3D3184EEA756C076317925508F
17221 FFFA6705A275195BFE8A443AF0BD2AA86B1AA0481D330D8665813206EB8DAD43
17222 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77
17223 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
17224 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
      ever_SEN_support first_SEN_support_year SEN_support_need ever_EHC_plan
1      TRUE            2016                   ASD              FALSE
2      TRUE            2007                   MLD              FALSE
3      TRUE            2005                   SLCN, MLD         TRUE
4      TRUE            2014                   MLD              FALSE
5     FALSE              NA                   NA               FALSE
6      TRUE            2017                                    FALSE
7      TRUE            2008                   PD               FALSE
8      TRUE            2015                   SEMH             FALSE
9     FALSE              NA                   NA               FALSE
10     TRUE            2013                                    FALSE
11    FALSE              NA                   NA               FALSE
12    FALSE              NA                   NA               FALSE
13     TRUE            2006                   MLD              FALSE
14     TRUE            2007                   MLD              FALSE
15    FALSE              NA                   NA               FALSE
16    FALSE              NA                   NA               FALSE
17     TRUE            2010                   MLD              FALSE
18    FALSE              NA                   NA               FALSE
19    FALSE              NA                   NA               FALSE
20     TRUE            2007                                    FALSE
21    FALSE              NA                   NA               FALSE
22    FALSE              NA                   NA               FALSE
23    FALSE              NA                   NA               FALSE
24     TRUE            2008                                    FALSE
25     TRUE            2010                   SEMH             FALSE
26    FALSE              NA                   NA               FALSE
27    FALSE              NA                   NA               FALSE
28     TRUE            2007                   SPLD, SLCN       FALSE
29     TRUE            2017                                    FALSE
30    FALSE              NA                   NA               FALSE
⋮     ⋮                ⋮                      ⋮                ⋮
17195  TRUE            2007                   SLCN              TRUE
17196 FALSE              NA                   NA               FALSE
17197 FALSE              NA                   NA               FALSE
17198  TRUE            2006                   ASD               TRUE
17199 FALSE              NA                   NA               FALSE
17200  TRUE            2007                                    FALSE
17201  TRUE            2010                   MLD              FALSE
17202 FALSE              NA                   NA               FALSE
17203  TRUE            2007                   SEMH              TRUE
17204 FALSE              NA                   NA               FALSE
17205 FALSE              NA                   NA               FALSE
17206 FALSE              NA                   NA               FALSE
17207 FALSE              NA                   NA               FALSE
17208 FALSE              NA                   NA               FALSE
17209 FALSE              NA                   NA               FALSE
17210 FALSE              NA                   NA               FALSE
17211 FALSE              NA                   NA               FALSE
17212 FALSE              NA                   NA               FALSE
17213  TRUE            2005                   MLD              FALSE
17214  TRUE            2018                                    FALSE
17215  TRUE            2006                   SEMH, ASD         TRUE
17216  TRUE            2012                   SEMH             FALSE
17217  TRUE            2014                   SEMH             FALSE
17218 FALSE              NA                   NA               FALSE
17219 FALSE              NA                   NA               FALSE
17220  TRUE            2008                   MLD              FALSE
17221 FALSE              NA                   NA               FALSE
17222  TRUE            2013                                    FALSE
17223 FALSE              NA                   NA               FALSE
17224  TRUE            2009                                    FALSE
      first_EHC_plan_year EHC_plan_need no_SEN
1       NA                NA            FALSE
2       NA                NA            FALSE
3     2012                MLD           FALSE
4       NA                NA            FALSE
5       NA                NA             TRUE
6       NA                NA            FALSE
7       NA                NA            FALSE
8       NA                NA            FALSE
9       NA                NA             TRUE
10      NA                NA            FALSE
11      NA                NA             TRUE
12      NA                NA             TRUE
13      NA                NA            FALSE
14      NA                NA            FALSE
15      NA                NA             TRUE
16      NA                NA             TRUE
17      NA                NA            FALSE
18      NA                NA             TRUE
19      NA                NA             TRUE
20      NA                NA            FALSE
21      NA                NA             TRUE
22      NA                NA             TRUE
23      NA                NA             TRUE
24      NA                NA            FALSE
25      NA                NA            FALSE
26      NA                NA             TRUE
27      NA                NA             TRUE
28      NA                NA            FALSE
29      NA                NA            FALSE
30      NA                NA             TRUE
⋮     ⋮                   ⋮             ⋮
17195 2018                              FALSE
17196   NA                NA             TRUE
17197   NA                NA             TRUE
17198 2009                ASD           FALSE
17199   NA                NA             TRUE
17200   NA                NA            FALSE
17201   NA                NA            FALSE
17202   NA                NA             TRUE
17203 2014                SEMH          FALSE
17204   NA                NA             TRUE
17205   NA                NA             TRUE
17206   NA                NA             TRUE
17207   NA                NA             TRUE
17208   NA                NA             TRUE
17209   NA                NA             TRUE
17210   NA                NA             TRUE
17211   NA                NA             TRUE
17212   NA                NA             TRUE
17213   NA                NA            FALSE
17214   NA                NA            FALSE
17215 2017                              FALSE
17216   NA                NA            FALSE
17217   NA                NA            FALSE
17218   NA                NA             TRUE
17219   NA                NA             TRUE
17220   NA                NA            FALSE
17221   NA                NA             TRUE
17222   NA                NA            FALSE
17223   NA                NA             TRUE
17224   NA                NA            FALSE

In [173]:
sen_final |> nrow()

[1] 17224

#### ARCHIVE filter to one record pp with year as first record of SEN need

In [58]:
# group by all cols except year, and keep first row of duplicates
sen_merge <- sen_clean |>
    arrange(desc(Year)) |>
    group_by(across(-Year)) |>
    filter(row_number() == 1) |>
    ungroup() |>
    arrange(person_id)

In [59]:
sen_merge |>
    filter(person_id == 'D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E')

  person_id                                                        Year
1 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E 2020
2 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E 2017
3 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E 2014
  PrimarySENtype SENlevel
1 NA             No SEN
2 SPLD           SEN support
3 NA             SEN support

In [60]:
sen_merge |>
arrange(person_id, desc(Year))

      person_id                                                        Year
1     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2017
2     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2015
3     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2017
4     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2006
5     0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2018
6     0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2017
7     0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2011
8     0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2008
9     0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2005
10    0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2018
11    0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2017
12    0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2013
13    00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66 2019
14    0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D 2017
15    0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D 2016
16    0018E26A40A6299391164D4918658B0B1248367C762DCE6D2FDF1AE131A9138C 2019
17    0018E26A40A6299391164D4918658B0B1248367C762DCE6D2FDF1AE131A9138C 2018
18    0018E26A40A6299391164D4918658B0B1248367C762DCE6D2FDF1AE131A9138C 2007
19    0019031CD62586D59268772800516ED50CDF1EF7DE46488542BB031850F6E68A 2018
20    0019031CD62586D59268772800516ED50CDF1EF7DE46488542BB031850F6E68A 2017
21    0019031CD62586D59268772800516ED50CDF1EF7DE46488542BB031850F6E68A 2014
22    001B7CEB7B4CC529920A0B9F5B83D1AC0019E5DC44B3FBB3CEF665C331C0C3B6 2018
23    001E539C263734CC355646811C93CF85B0C587D2EBA8B0D79290FDE8A75D6267 2017
24    001E539C263734CC355646811C93CF85B0C587D2EBA8B0D79290FDE8A75D6267 2013
25    001E5C1FFA964716BF5E84562BC0B5D64F7742B1E8126718A5C0157D485F215D 2020
26    001F566795F57F5D8DD92430D868A38B757699844E3E09569B33253527012932 2020
27    001FFD3AA96B7E4FC5BB9A2F7502CD45BFCC35882335F1C34F78DD9AE5667225 2020
28    001FFD3AA96B7E4FC5BB9A2F7502CD45BFCC35882335F1C34F78DD9AE5667225 2006
29    00222373A6082CDBF94DA04F23E7EB4C8775BEE122FE9C29FBF521900A498EDF 2017
30    00222373A6082CDBF94DA04F23E7EB4C8775BEE122FE9C29FBF521900A498EDF 2007
⋮     ⋮                                                                ⋮
30500 FFACDC831FAAA09353CAB36C5828F34E508AC8BFED1B4B07999BAF198CAC4EEA 2019
30501 FFBCE0C32A37E3663F1C5159ECFC6F08CD5722E938464A58634F3263003F1D9F 2020
30502 FFC0379FDA559C1337454C579FF36F9AE82E62D16B3223D009C57DEC3731754C 2020
30503 FFC7129859DD885141E316248A0EB23059DB0F0DB98242C34C67F06FBBAB8041 2020
30504 FFC96F346EC6829E7A31F60109FD729DE208D180104B50FC8B1BFAD552D6C8FC 2018
30505 FFD30596592DA2C82B86241FBA35E56C7384E7EF8219DB076458B4F9ACDED786 2017
30506 FFD30596592DA2C82B86241FBA35E56C7384E7EF8219DB076458B4F9ACDED786 2016
30507 FFD30596592DA2C82B86241FBA35E56C7384E7EF8219DB076458B4F9ACDED786 2009
30508 FFD391941F3AA9CB910FFFACF24CC2CEAD0BC63EED146E9C21B2C71BA77B084A 2018
30509 FFD391941F3AA9CB910FFFACF24CC2CEAD0BC63EED146E9C21B2C71BA77B084A 2017
30510 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2018
30511 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2016
30512 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2014
30513 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2011
30514 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2008
30515 FFE1AA7D705C959745A85B91C6D3F3D22A57B8E50092E9EC25046F6986F77D96 2017
30516 FFE1AA7D705C959745A85B91C6D3F3D22A57B8E50092E9EC25046F6986F77D96 2014
30517 FFE1AA7D705C959745A85B91C6D3F3D22A57B8E50092E9EC25046F6986F77D96 2011
30518 FFE837A538A9166CC4089E844F651277391B496479F4691CE27BF1000C49223B 2017
30519 FFE837A538A9166CC4089E844F651277391B496479F4691CE27BF1000C49223B 2014
30520 FFEA068077E4464D059236951F07D7DF96542C2197AAFAC3E20C036BACB9825C 2020
30521 FFEF2AA9E8BD72D6A0E7CE50F067E4247E12738F53AE726CD94A4D9CB588C702 2018
30522 FFEFD5577D0112E9304118DB7851CF61BEE4DD3D3184EEA756C076317925508F 2017
30523 FFEFD5577D0112E9304118DB7851CF61BEE4DD3D3184EEA756C076317925508F 2009
30524 FFFA6705A275195BFE8A443AF0BD2AA86B1AA0481D330D8665813206EB8DAD43 2020
30525 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77 2020
30526 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77 2013
30527 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2018
30528 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2017
30529 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2010
      PrimarySENtype SENlevel
1     ASD            SEN support
2     NA             No SEN
3     MLD            SEN support
4     NA             No SEN
5     NA             EHC plan
6     MLD            EHC plan
7     MLD            SEN support
8     NA             No SEN
9     SLCN           SEN support
10    NA             SEN support
11    MLD            SEN support
12    NA             No SEN
13    NA             No SEN
14    NA             SEN support
15    NA             No SEN
16    PD             SEN support
17    NA             SEN support
18    NA             No SEN
19    NA             SEN support
20    SEMH           SEN support
21    NA             No SEN
22    NA             No SEN
23    NA             No SEN
24    NA             SEN support
25    NA             No SEN
26    NA             No SEN
27    NA             No SEN
28    MLD            SEN support
29    MLD            SEN support
30    NA             SEN support
⋮     ⋮              ⋮
30500 NA             No SEN
30501 NA             No SEN
30502 NA             No SEN
30503 NA             No SEN
30504 NA             No SEN
30505 NA             SEN support
30506 NA             No SEN
30507 MLD            SEN support
30508 NA             SEN support
30509 NA             No SEN
30510 NA             EHC plan
30511 ASD            SEN support
30512 BESD           SEN support
30513 NA             SEN support
30514 NA             No SEN
30515 SEMH           SEN support
30516 NA             SEN support
30517 NA             No SEN
30518 NA             No SEN
30519 BESD           SEN support
30520 NA             No SEN
30521 NA             No SEN
30522 NA             No SEN
30523 MLD            SEN support
30524 NA             No SEN
30525 NA             No SEN
30526 NA             SEN support
30527 NA             No SEN
30528 NA             No SEN
30529 NA             SEN support

In [575]:
# copy previous value where sen level is NA but type not NA
sen_level_clean <- sen_merge |>
    arrange(person_id, Year) |>  
    group_by(person_id) |>
    mutate(SENlevel = case_when(
          # if NA and prev SENlevel is SEN support, and type not NA 
          SENlevel == 'No SEN' & lag(SENlevel) == 'SEN support' & !is.na(PrimarySENtype) ~ 'SEN support',  
          SENlevel == 'No SEN' & lag(SENlevel) == 'EHC plan' & !is.na(PrimarySENtype) ~ 'EHC plan',
          TRUE ~ SENlevel  # Keep original value otherwise
        )) |>
    ungroup()

In [576]:
sen_level_clean |>
    filter(person_id == 'D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E')

  person_id                                                        Year
1 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E 2007
2 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E 2008
3 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E 2010
4 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E 2013
  PrimarySENtype SENlevel
1 NA             No SEN
2 NA             SEN support
3 SPLD           SEN support
4 SPLD           SEN support

In [585]:
# repeat but for desc year
sen_level_desc <- sen_level_clean |>
    arrange(person_id, desc(Year)) |>  
    group_by(person_id) |>
    mutate(SENlevel = case_when(
          # if NA and prev SENlevel is SEN support, and type not NA 
          SENlevel == 'No SEN' & lag(SENlevel) == 'SEN support' & !is.na(PrimarySENtype) ~ 'SEN support',  
          SENlevel == 'No SEN' & lag(SENlevel) == 'EHC plan' & !is.na(PrimarySENtype) ~ 'EHC plan',
          TRUE ~ SENlevel  # Keep original value otherwise
        )) |>
    ungroup()

In [591]:
# repeat to catch gaps
sen_level_desc <- sen_level_desc |>
    arrange(person_id, Year) |>  
    group_by(person_id) |>
    mutate(SENlevel = case_when(
          # if NA and prev SENlevel is SEN support, and type not NA 
          SENlevel == 'No SEN' & lag(SENlevel) == 'SEN support' & !is.na(PrimarySENtype) ~ 'SEN support',  
          SENlevel == 'No SEN' & lag(SENlevel) == 'EHC plan' & !is.na(PrimarySENtype) ~ 'EHC plan',
          TRUE ~ SENlevel  # Keep original value otherwise
        )) |>
    ungroup()

In [594]:
sen_level_desc |>
    filter(person_id == 'D4D7BBA8B62A4CEB3450B49A97320FCD1E420F8D489BBA9AF698C2124BC88147')

  person_id                                                        Year
1 D4D7BBA8B62A4CEB3450B49A97320FCD1E420F8D489BBA9AF698C2124BC88147 2006
2 D4D7BBA8B62A4CEB3450B49A97320FCD1E420F8D489BBA9AF698C2124BC88147 2008
3 D4D7BBA8B62A4CEB3450B49A97320FCD1E420F8D489BBA9AF698C2124BC88147 2013
4 D4D7BBA8B62A4CEB3450B49A97320FCD1E420F8D489BBA9AF698C2124BC88147 2016
  PrimarySENtype SENlevel
1 NA             No SEN
2 SEMH           SEN support
3 SEMH           SEN support
4 SEMH           SEN support

In [595]:
missing_senlevel <- sen_level_desc |>
    filter(SENlevel == 'No SEN' & !is.na(PrimarySENtype))

In [596]:
missing_senlevel |>
    summarize(n_distinct(person_id))

  n_distinct(person_id)
1 64

In [598]:
sen_level_desc |>
    filter(person_id %in% missing_senlevel$person_id) |>
    distinct(SENlevel)

  SENlevel
1 No SEN

In [599]:
sen_level_desc |>
    filter(person_id %in% missing_senlevel$person_id) |>
    arrange(person_id, Year)

    person_id                                                        Year
1   05BECC2FA9168CC3CC4A8669F2B6BEF1235BB7A7386DDA71141D0444C1A34D87 2005
2   0607C1DA04A1A88F14F80F5DB04C9112B950A68544F2F21E241F94F3AC7D6E78 2006
3   0607C1DA04A1A88F14F80F5DB04C9112B950A68544F2F21E241F94F3AC7D6E78 2015
4   137AAFFB957B50C9C3509763EEE31B4AD73661BB93279CBBCCFB377BDE975C8D 2006
5   137AAFFB957B50C9C3509763EEE31B4AD73661BB93279CBBCCFB377BDE975C8D 2015
6   1E2DDA056F48950C6617E5D8209A6CB6E5583CD02031694903C9E11461C1B70B 2006
7   1E2DDA056F48950C6617E5D8209A6CB6E5583CD02031694903C9E11461C1B70B 2015
8   20E40E9631F550A80DC84266D8EA9118EE12F0C0498AEF95D4ED1DAC9A5124ED 2006
9   20E40E9631F550A80DC84266D8EA9118EE12F0C0498AEF95D4ED1DAC9A5124ED 2015
10  21D5645242C07A3BA957B9BB0D4FCA5919A131A16F8B0D738BE93C986D91BE19 2005
11  21D5645242C07A3BA957B9BB0D4FCA5919A131A16F8B0D738BE93C986D91BE19 2016
12  25F20084CCDCC4C36969A2B69319897EFD35547672A1BB15A74E2696CA91CB25 2011
13  25F20084CCDCC4C36969A2B69319897EFD35547672A1BB15A74E2696CA91CB25 2015
14  267E4A245B7E7853BBFE3B71279DF24E7EC5C3BA53D33D5EE67055AC6E202341 2005
15  267E4A245B7E7853BBFE3B71279DF24E7EC5C3BA53D33D5EE67055AC6E202341 2011
16  2D3529D793F5D5FE48E4D46340B0CDA08163402C37512A1D03CFBD04F5A74069 2006
17  2D3529D793F5D5FE48E4D46340B0CDA08163402C37512A1D03CFBD04F5A74069 2013
18  2D714368F0D540D3478EED42CC13DC75B3988A104484E4A29C0906E8F149CDB6 2006
19  2D714368F0D540D3478EED42CC13DC75B3988A104484E4A29C0906E8F149CDB6 2020
20  308CF0AD7F040CF19307CE47DA196814651BDDFB85B61DCDDC55646AA7D7EA3F 2016
21  308CF0AD7F040CF19307CE47DA196814651BDDFB85B61DCDDC55646AA7D7EA3F 2020
22  315A97DA7FBCC9BA54B558B8F941F6998766F57A2B7B1879F97F51D9E7A81FAF 2006
23  315A97DA7FBCC9BA54B558B8F941F6998766F57A2B7B1879F97F51D9E7A81FAF 2015
24  329713B0F69A6C27FC40A56E3541B55D5C0B602EA3DB11C5086033CE15DC765E 2016
25  341F2B5CDE9327ADDA42B452ED60EBE3320AE0B624013C59FAAE6D0B47979459 2005
26  37A5FC349F5078BA1A93905D6295C39C98CF573BED89CA3EAAFA5BCA1598117A 2006
27  37A5FC349F5078BA1A93905D6295C39C98CF573BED89CA3EAAFA5BCA1598117A 2015
28  3DFB204D7C85040E07790642ADA942B9FDF8DD6DF02950FF43387E9B3D5E7E9C 2006
29  3DFB204D7C85040E07790642ADA942B9FDF8DD6DF02950FF43387E9B3D5E7E9C 2013
30  4161459C0AA4D9B12A0068D59E8E1D30CD34833BF599E788E91967EADCCE88C1 2006
⋮   ⋮                                                                ⋮
92  CBF57090D7BE517787C6D0DC11A768A42BC9EB9FE0D1286AFBFD08C5C799F0AA 2005
93  D361AD6405F7B3035A1AB7131C0487841F609B867EB8BFDBEC924DE01C0C497B 2006
94  D361AD6405F7B3035A1AB7131C0487841F609B867EB8BFDBEC924DE01C0C497B 2012
95  D5A60DAAA3112F1E82AD2001F9E5026FA7A04EAD8ADAD19CC4C63AFBAD6B4B80 2006
96  D5A60DAAA3112F1E82AD2001F9E5026FA7A04EAD8ADAD19CC4C63AFBAD6B4B80 2007
97  D62EEA35AC8962663BC4A21CE585418D10526DF30C00D600875F983BBB6D5474 2006
98  D62EEA35AC8962663BC4A21CE585418D10526DF30C00D600875F983BBB6D5474 2014
99  D6B25EFED1431714C98FF5F5589024B572764254347F00B836A7BB594A83A3B7 2007
100 D6B25EFED1431714C98FF5F5589024B572764254347F00B836A7BB594A83A3B7 2020
101 D8758BE9A3FFD63DA723ED5D42819CD01EDFEFC30D5987E8D5A123AD7B4473A8 2013
102 D8758BE9A3FFD63DA723ED5D42819CD01EDFEFC30D5987E8D5A123AD7B4473A8 2015
103 DD60886DDF05972D479065F98B085EFBD8E30A532DBEB78219DBE41D2DFF4CC9 2007
104 DD60886DDF05972D479065F98B085EFBD8E30A532DBEB78219DBE41D2DFF4CC9 2010
105 E0876FCA4B343D1F2BD2844B5057949E021E14DA27CD8EB86BE0FE40ABB922A0 2005
106 E0876FCA4B343D1F2BD2844B5057949E021E14DA27CD8EB86BE0FE40ABB922A0 2015
107 E822DF2372856FD8EC9B701F87E7915A9374166C34280BC70E46A9C4A3B78593 2006
108 E822DF2372856FD8EC9B701F87E7915A9374166C34280BC70E46A9C4A3B78593 2016
109 E95448F90589E3FD517AD3298510EA4D8685DBD1D947D79AABFC575CAEA69244 2007
110 E95448F90589E3FD517AD3298510EA4D8685DBD1D947D79AABFC575CAEA69244 2020
111 F6AD9A9D94833D0CD4071DC885AB28680AA5CA22FEFDF0B7B96ED89FB20B3B7D 2006
112 F6AD9A9D94833D0CD4071DC885AB28680AA5CA22FEFDF0B7B96ED89FB20B3B7D 2015
113 F962BCF164905BDF98A950D0FEADBCC87644CDDCB771D75087C92A430DB8903B 2005
114 F962BCF164905BDF98A950D0FEADBCC87644CDDCB771D75087C92A430DB8903B 2013
115 F98E338A63C4C981F45BBEAD8F83E8300B53167DA6769FCA43329E53C5B3BD98 2005
116 FDFDD20EAB3F4831B4C00505FCB2FF699EA9EB50383F165F7A0CF1AB66D201D1 2007
117 FDFDD20EAB3F4831B4C00505FCB2FF699EA9EB50383F165F7A0CF1AB66D201D1 2008
118 FE7FA26269B82E8538308FB70947B77B3304BFA4122FA569C0A8DF32C1D0A4A6 2007
119 FE7FA26269B82E8538308FB70947B77B3304BFA4122FA569C0A8DF32C1D0A4A6 2015
120 FFE837A538A9166CC4089E844F651277391B496479F4691CE27BF1000C49223B 2006
121 FFE837A538A9166CC4089E844F651277391B496479F4691CE27BF1000C49223B 2014
    PrimarySENtype SENlevel
1   OTH            No SEN
2   NA             No SEN
3   OTH            No SEN
4   NA             No SEN
5   SPLD           No SEN
6   NA             No SEN
7   OTH            No SEN
8   NA             No SEN
9   SPLD           No SEN
10  NA             No SEN
11  SPLD           No SEN
12  NA             No SEN
13  SEMH           No SEN
14  NA             No SEN
15  MLD            No SEN
16  NA             No SEN
17  SEMH           No SEN
18  NA             No SEN
19  SPLD           No SEN
20  NA             No SEN
21  OTH            No SEN
22  NA             No SEN
23  OTH            No SEN
24  MLD            No SEN
25  OTH            No SEN
26  NA             No SEN
27  SPLD           No SEN
28  NA             No SEN
29  OTH            No SEN
30  NA             No SEN
⋮   ⋮              ⋮
92  OTH            No SEN
93  NA             No SEN
94  OTH            No SEN
95  NA             No SEN
96  SEMH           No SEN
97  NA             No SEN
98  SEMH           No SEN
99  NA             No SEN
100 ASD            No SEN
101 NA             No SEN
102 SEMH           No SEN
103 NA             No SEN
104 MLD            No SEN
105 NA             No SEN
106 SEMH           No SEN
107 NA             No SEN
108 SEMH           No SEN
109 NA             No SEN
110 ASD            No SEN
111 NA             No SEN
112 SPLD           No SEN
113 NA             No SEN
114 SPLD           No SEN
115 OTH            No SEN
116 NA             No SEN
117 SLCN           No SEN
118 NA             No SEN
119 SPLD           No SEN
120 NA             No SEN
121 SEMH           No SEN

In [603]:
sen_final <- sen_level_desc |>
    arrange(desc(Year)) |>            
    group_by(person_id) |>            
    filter(row_number() == 1) |>      
    ungroup()

In [604]:
sen_final |>
    group_by(PrimarySENtype) |>
    tally()

   PrimarySENtype n
1  ASD              230
2  HI               128
3  MLD             1540
4  MSI                3
5  NSA               54
6  OTH              204
7  PD               150
8  PMLD              27
9  SEMH            1128
10 SLCN             405
11 SLD              100
12 SPLD             441
13 VI                74
14 NA             12740

In [606]:
head(sen_final)

  person_id                                                        Year
1 0BAA7959F866DC200B0DE7C16B5B16DD63D6D6BA086D46BA9D26025AC7FB1FB6 2020
2 18A1DBCA368AFAADA2DAC40BD35DE4E1756E5C5905C643A9DFD8590ED65BC980 2020
3 18BDC8758A1C2629E1B3FE7677D649961D106A4E3C5371B14B2EE6FBC12D6162 2020
4 191B614E755130087F1A4C6F61D7CA413FC57CDE42DE350168AF9F21079A5A3D 2020
5 1E8EDACA982683915764BFB3DA811D133E1AD9879F0512C019E4307EFF8E2D13 2020
6 248B0C2E0DD811AC20D8D8940381A477C3041C6B299278C2F7C44AB3E3E098A0 2020
  PrimarySENtype SENlevel
1 OTH            SEN support
2 HI             SEN support
3 VI             SEN support
4 VI             SEN support
5 SEMH           SEN support
6 OTH            SEN support

In [621]:
sen_final <- sen_final |>
    rename(SENtype = PrimarySENtype) |>
    select(-Year)

In [622]:
sen_final |>
    nrow()

[1] 17224

In [623]:
sen_final |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 17224

#### merge SEN into main data

In [174]:
# save as csv
write.csv(sen_final, "data/sen_final.csv", row.names = FALSE)

In [257]:
person_home_fsm_sen <- sen_final |> 
    left_join(person_home_fsm, by = join_by(person_id))

In [258]:
person_home_fsm_sen

      person_id
1     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
3     0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D
4     0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7
5     00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66
6     0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D
7     0018E26A40A6299391164D4918658B0B1248367C762DCE6D2FDF1AE131A9138C
8     0019031CD62586D59268772800516ED50CDF1EF7DE46488542BB031850F6E68A
9     001B7CEB7B4CC529920A0B9F5B83D1AC0019E5DC44B3FBB3CEF665C331C0C3B6
10    001E539C263734CC355646811C93CF85B0C587D2EBA8B0D79290FDE8A75D6267
11    001E5C1FFA964716BF5E84562BC0B5D64F7742B1E8126718A5C0157D485F215D
12    001F566795F57F5D8DD92430D868A38B757699844E3E09569B33253527012932
13    001FFD3AA96B7E4FC5BB9A2F7502CD45BFCC35882335F1C34F78DD9AE5667225
14    00222373A6082CDBF94DA04F23E7EB4C8775BEE122FE9C29FBF521900A498EDF
15    002AB68E0EC9459837DD6159160BF8C592504B5F0EE3160A22051398D20C3FFC
16    002E041C5100C46E33B8A0C0220BDE85A79111C5D0E26742F6278C059930FAF6
17    002EF3F17C7981C3D6FD842C559E9AA0626E06B3940B670DDA2B71F7070ADF7D
18    003132A725233755576CF96E5AA2B3DF606A618754D4BDDFCDD5483849E7B946
19    00341B29C42EC823E9D06B625E751614D66794F1096E2F045DDE51DB64C9C623
20    0037AB0369C14AD5CA0340E2DFDAE2FFF22062A44A7889743C152A8163C08500
21    003D2F5BDBC025915EE2AA9CCB96F54F72F003BF7DC6939849ADD6CCD1048ABC
22    0048AA244E75570B74E82BDC60D09008D5E728E78E60FB96AA0E762DBD0E818E
23    004AC6875C0259256CBCBC00373E9D09131E7D064B6089B9EB26F821F8297775
24    004C012DC8B27D82CC173C9590867A88C8B60E6F4C1EAE8AF73D53403DDD94B5
25    004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
26    005087BCA7BEC31B79A3CA446453131C51CD1DC3296FE71B509E46AA984FFAE3
27    0052FF7683A04EBA481AFA53811E1707DBAB62007649EA0C4CE89C8498C06C97
28    0054192801954D860BB235F844AD1CB8A99956B2CF3D4E20F83C650DD6279B58
29    0059AC822384B93661D2AB87E93EA6AB0847122FA139A080070E86A2F6A1910E
30    005A3BB3D150E6AFDC0C4DDCEE6DB850E746A6E2F7760B727CF97B659BC2F483
⋮     ⋮
17195 FF77AAB58760E4616819BF69FA7A7D0466EC940FC1B666F5D8FC15261B05FDA7
17196 FF785EF44C283B9E43E7F206B8848D7C550C36E7E8E5DA0A2B6267CABC0AE447
17197 FF7AC7331F6B988DCFBCFA5C55F7984D5BA33735D4DDB4671F30E37176A7B40D
17198 FF7B98BFE21CD2600469C9D7B3C040C06C1AAAB58F51EE3BE5A0E0CA94470300
17199 FF7B9B8977DE09E00DDE57866479BEED54F7BC5730E38C61A15A220CAF2C507B
17200 FF85D28F3D4272EF3EDA67E52BC94BB3A529BD2CD31D32EF21FB8157396EF57D
17201 FF85FB47EF271836ECDF7555602263FC0E52F8A84F39868EE7B66E30E47DF618
17202 FF8C66C8699FEF1708ABC2DADF11D78283107FADB514F81D4219017A8D26E2DE
17203 FF9024B3D2775BB5CC65F8872CB1A8BECAD9A7E25FBB3C3DF7D46A8A1BE31AC1
17204 FF94BC38B3E8FE01672532C523A4C00ABB2F9C7B3CDFF6C78F2DA080B544B09A
17205 FF94D3F7FDB40C124787D0EBA0CD7660187135442D800F18C11487D380F55663
17206 FF9B2F9502DAFBC1EFB04109BEFF47C64A04801619DE844A3DAD073DD45D99D1
17207 FFAA13CCE7B35BA3D3A737EF1A13BCE2289A94F9778EC0C9F18CD77F1B93C979
17208 FFACDC831FAAA09353CAB36C5828F34E508AC8BFED1B4B07999BAF198CAC4EEA
17209 FFBCE0C32A37E3663F1C5159ECFC6F08CD5722E938464A58634F3263003F1D9F
17210 FFC0379FDA559C1337454C579FF36F9AE82E62D16B3223D009C57DEC3731754C
17211 FFC7129859DD885141E316248A0EB23059DB0F0DB98242C34C67F06FBBAB8041
17212 FFC96F346EC6829E7A31F60109FD729DE208D180104B50FC8B1BFAD552D6C8FC
17213 FFD30596592DA2C82B86241FBA35E56C7384E7EF8219DB076458B4F9ACDED786
17214 FFD391941F3AA9CB910FFFACF24CC2CEAD0BC63EED146E9C21B2C71BA77B084A
17215 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951
17216 FFE1AA7D705C959745A85B91C6D3F3D22A57B8E50092E9EC25046F6986F77D96
17217 FFE837A538A9166CC4089E844F651277391B496479F4691CE27BF1000C49223B
17218 FFEA068077E4464D059236951F07D7DF96542C2197AAFAC3E20C036BACB9825C
17219 FFEF2AA9E8BD72D6A0E7CE50F067E4247E12738F53AE726CD94A4D9CB588C702
17220 FFEFD5577D0112E9304118DB7851CF61BEE4DD3D3184EEA756C076317925508F
17221 FFFA6705A275195BFE8A443AF0BD2AA86B1AA0481D330D8665813206EB8DAD43
17222 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77
17223 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
17224 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
      ever_SEN_support first_SEN_support_year SEN_support_need ever_EHC_plan
1      TRUE            2016                   ASD              FALSE
2      TRUE            2007                   MLD              FALSE
3      TRUE            2005                   SLCN, MLD         TRUE
4      TRUE            2014                   MLD              FALSE
5     FALSE              NA                   NA               FALSE
6      TRUE            2017                                    FALSE
7      TRUE            2008                   PD               FALSE
8      TRUE            2015                   SEMH             FALSE
9     FALSE              NA                   NA               FALSE
10     TRUE            2013                                    FALSE
11    FALSE              NA                   NA               FALSE
12    FALSE              NA                   NA               FALSE
13     TRUE            2006                   MLD              FALSE
14     TRUE            2007                   MLD              FALSE
15    FALSE              NA                   NA               FALSE
16    FALSE              NA                   NA               FALSE
17     TRUE            2010                   MLD              FALSE
18    FALSE              NA                   NA               FALSE
19    FALSE              NA                   NA               FALSE
20     TRUE            2007                                    FALSE
21    FALSE              NA                   NA               FALSE
22    FALSE              NA                   NA               FALSE
23    FALSE              NA                   NA               FALSE
24     TRUE            2008                                    FALSE
25     TRUE            2010                   SEMH             FALSE
26    FALSE              NA                   NA               FALSE
27    FALSE              NA                   NA               FALSE
28     TRUE            2007                   SPLD, SLCN       FALSE
29     TRUE            2017                                    FALSE
30    FALSE              NA                   NA               FALSE
⋮     ⋮                ⋮                      ⋮                ⋮
17195  TRUE            2007                   SLCN              TRUE
17196 FALSE              NA                   NA               FALSE
17197 FALSE              NA                   NA               FALSE
17198  TRUE            2006                   ASD               TRUE
17199 FALSE              NA                   NA               FALSE
17200  TRUE            2007                                    FALSE
17201  TRUE            2010                   MLD              FALSE
17202 FALSE              NA                   NA               FALSE
17203  TRUE            2007                   SEMH              TRUE
17204 FALSE              NA                   NA               FALSE
17205 FALSE              NA                   NA               FALSE
17206 FALSE              NA                   NA               FALSE
17207 FALSE              NA                   NA               FALSE
17208 FALSE              NA                   NA               FALSE
17209 FALSE              NA                   NA               FALSE
17210 FALSE              NA                   NA               FALSE
17211 FALSE              NA                   NA               FALSE
17212 FALSE              NA                   NA               FALSE
17213  TRUE            2005                   MLD              FALSE
17214  TRUE            2018                                    FALSE
17215  TRUE            2006                   SEMH, ASD         TRUE
17216  TRUE            2012                   SEMH             FALSE
17217  TRUE            2014                   SEMH             FALSE
17218 FALSE              NA                   NA               FALSE
17219 FALSE              NA                   NA               FALSE
17220  TRUE            2008                   MLD              FALSE
17221 FALSE              NA                   NA               FALSE
17222  TRUE            2013                                    FALSE
17223 FALSE              NA                   NA               FALSE
17224  TRUE            2009                                    FALSE
      first_EHC_plan_year EHC_plan_need no_SEN birth_date gender
1       NA                NA            FALSE  2001-05-15 M
2       NA                NA            FALSE  2001-01-15 F
3     2012                MLD           FALSE  2001-11-15 M
4       NA                NA            FALSE  2002-05-15 M
5       NA                NA             TRUE  2000-11-15 M
6       NA                NA            FALSE  2001-04-15 F
7       NA                NA            FALSE  2002-07-15 M
8       NA                NA            FALSE  2001-12-15 F
9       NA                NA             TRUE  2001-05-15 M
10      NA                NA            FALSE  2000-10-15 M
11      NA                NA             TRUE  2002-04-15 M
12      NA                NA             TRUE  2002-06-15 M
13      NA                NA            FALSE  2002-06-15 F
14      NA                NA            FALSE  2000-11-15 F
15      NA                NA             TRUE  2002-08-15 F
16      NA                NA             TRUE  2000-12-15 M
17      NA                NA            FALSE  2002-05-15 F
18      NA                NA             TRUE  2001-07-15 M
19      NA                NA             TRUE  2002-03-15 F
20      NA                NA            FALSE  2000-09-15 M
21      NA                NA             TRUE  2001-05-15 M
22      NA                NA             TRUE  2001-12-15 F
23      NA                NA             TRUE  2002-01-15 M
24      NA                NA            FALSE  2002-04-15 F
25      NA                NA            FALSE  2001-01-15 F
26      NA                NA             TRUE  2001-04-15 F
27      NA                NA             TRUE  2002-07-15 F
28      NA                NA            FALSE  2000-11-15 F
29      NA                NA            FALSE  2001-04-15 F
30      NA                NA             TRUE  2002-04-15 M
⋮     ⋮                   ⋮             ⋮      ⋮          ⋮
17195 2018                              FALSE  2002-04-15 F
17196   NA                NA             TRUE  2001-07-15 M
17197   NA                NA             TRUE  2001-07-15 M
17198 2009                ASD           FALSE  2001-08-15 M
17199   NA                NA             TRUE  2001-06-15 M
17200   NA                NA            FALSE  2001-03-15 M
17201   NA                NA            FALSE  2002-06-15 M
17202   NA                NA             TRUE  2001-01-15 F
17203 2014                SEMH          FALSE  2002-08-15 M
17204   NA                NA             TRUE  2001-05-15 F
17205   NA                NA             TRUE  2002-05-15 F
17206   NA                NA             TRUE  2001-02-15 F
17207   NA                NA             TRUE  2001-10-15 F
17208   NA                NA             TRUE  2001-03-15 M
17209   NA                NA             TRUE  2001-10-15 F
17210   NA                NA             TRUE  2001-09-15 M
17211   NA                NA             TRUE  2002-07-15 F
17212   NA                NA             TRUE  2002-05-15 M
17213   NA                NA            FALSE  2001-03-15 F
17214   NA                NA            FALSE  2002-08-15 M
17215 2017                              FALSE  2000-09-15 M
17216   NA                NA            FALSE  2001-02-15 F
17217   NA                NA            FALSE  2001-02-15 M
17218   NA                NA             TRUE  2001-10-15 M
17219   NA                NA             TRUE  2001-08-15 M
17220   NA                NA            FALSE  2001-01-15 F
17221   NA                NA             TRUE  2002-07-15 F
17222   NA                NA            FALSE  2002-05-15 M
17223   NA                NA             TRUE  2002-01-15 F
17224   NA                NA            FALSE  2001-07-15 M
      CombinedEthnicity cohort  DistCurrSch DistNearSch IDACIScore_Home
1     White British     2000/01 0.66        0.66        0.410
2     White British     2000/01 3.50        0.62        0.397
3     White British     2001/02 7.01        0.00        0.125
4     Other             2001/02 0.57        0.57        0.405
5     South Asian       2000/01 1.69        0.44        0.521
6     White British     2000/01 1.12        0.62        0.234
7     South Asian       2001/02 0.15        0.15        0.277
8     Other             2001/02 0.57        0.57        0.487
9     White British     2000/01 1.56        1.56        0.034
10    White British     2000/01 1.79        1.56        0.259
11    White British     2001/02 3.60        3.60        0.067
12    White British     2001/02 0.29        0.29        0.121
13    South Asian       2001/02   NA          NA           NA
14    South Asian       2000/01 2.52        0.61        0.245
15    South Asian       2001/02 7.57        0.32        0.132
16    South Asian       2000/01 1.60        0.21        0.315
17    White British     2001/02 0.76        0.51        0.500
18    White British     2000/01 0.33        0.33        0.270
19    White British     2001/02 0.91        0.26        0.193
20    White British     2000/01 1.04        1.04        0.186
21    Other             2000/01 1.81        0.98        0.106
22    White British     2001/02 2.14        2.14        0.080
23    White British     2001/02 0.50        0.50        0.042
24    South Asian       2001/02 1.60        0.29        0.383
25    White British     2000/01 1.81        0.30        0.369
26    White British     2000/01   NA          NA           NA
27    White British     2001/02 2.14        2.14        0.068
28    South Asian       2000/01 1.08        0.78        0.411
29    White British     2000/01 0.72        0.72        0.178
30    South Asian       2001/02 0.84        0.20        0.221
⋮     ⋮                 ⋮       ⋮           ⋮           ⋮
17195 White British     2001/02 0.62        0.62        0.30200
17196 South Asian       2000/01 1.81        0.98        0.16500
17197 White British     2000/01 0.18        0.18        0.02300
17198 White British     2000/01 2.73        1.78        0.13600
17199 White British     2000/01 2.04        1.99        0.04100
17200 South Asian       2000/01 0.98        0.60        0.25300
17201 White British     2001/02 2.82        1.09        0.11900
17202 White British     2000/01 0.30        0.30        0.13700
17203 White British     2001/02 6.71        0.66        0.08000
17204 White British     2000/01 1.93        0.97        0.11900
17205 Other             2001/02 0.73        0.73        0.13700
17206 White British     2000/01 0.64        0.64        0.06700
17207 Other             2001/02 1.04        0.46        0.25100
17208 Other             2000/01 1.80        0.81        0.03000
17209 South Asian       2001/02 3.29        0.36        0.26200
17210 South Asian       2001/02 1.01        0.68        0.25300
17211 South Asian       2001/02 0.91        0.80        0.21500
17212 South Asian       2001/02 1.08        0.39        0.34500
17213 Other             2000/01 0.86        0.41        0.23600
17214 White British     2001/02 0.11        0.11        0.32600
17215 White British     2000/01 0.39        0.39        0.06349
17216 White British     2000/01 2.17        0.40        0.22600
17217 White British     2000/01 7.97        2.25        0.04200
17218 White British     2001/02 0.69        0.69        0.31900
17219 South Asian       2000/01 1.21        0.52        0.17700
17220 White British     2000/01 0.33        0.33        0.52000
17221 White British     2001/02 0.98        0.98        0.18800
17222 White British     2001/02 1.23        1.23        0.06200
17223 White British     2001/02 0.19        0.19        0.25800
17224 White British     2000/01 3.00        0.24        0.23300
      LSOA11_Home EAL ever_fsm
1     E01010635    0   0
2     E01010749    0   0
3     E01002563    0   1
4     E01010724    1   0
5     E01010610    1   0
6     E01010815    0   0
7     E01033693    1   1
8     E01010663    1   1
9     E01010575    0   0
10    E01010704    0   0
11    E01010648    0   0
12    E01010598    0   0
13    NA          NA   0
14    E01010662    1   0
15    E01010729    0   0
16    E01010617    0   1
17    E01010800    0   1
18    E01010717    0   1
19    E01010629    0   1
20    E01010789    0   0
21    E01001313    1  NA
22    E01027560    0   1
23    E01010695    0   0
24    E01010623    1   1
25    E01010718    0   1
26    NA          NA   0
27    E01010638    0   0
28    E01010826    1   1
29    E01010921    0   0
30    E01010737    1   1
⋮     ⋮           ⋮   ⋮
17195 E01010864   0   1
17196 E01010746   1   0
17197 E01010692   0   0
17198 E01010641   0   0
17199 E01027586   0   0
17200 E01010809   1   0
17201 E01033696   0   1
17202 E01011396   0   1
17203 E01010795   0   0
17204 E01010787   0   0
17205 E01010699   0   0
17206 E01027584   0   0
17207 E01010836   1   0
17208 E01010596   1   1
17209 E01010627   1   1
17210 E01010809   1   0
17211 E01010665   1   0
17212 E01010611   1   1
17213 E01010743   1   1
17214 E01010605   0   1
17215 E01027583   0   0
17216 E01007591   0   1
17217 E01027567   0   0
17218 E01010680   0   0
17219 E01010805   0   0
17220 E01010868   0   1
17221 E01010866   0   0
17222 E01010645   0   0
17223 E01010846   0   1
17224 E01010852   0   0

In [259]:
# save as csv
write.csv(person_home_fsm_sen, "data/person_home_fsm_sen.csv", row.names = FALSE)