In [1]:
library(tidyverse)
library(dbplyr)
library(bigrquery)
library(lubridate)

bq_auth()

project_id = "yhcr-prd-bradfor-bia-core"

# create connection to database
con <- DBI::dbConnect(bigrquery::bigquery(), 
                      project = project_id)

print(paste0("Connected to : ", project_id))

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘dbplyr’


The following objects are masked from ‘package:dplyr’:

    ident, sql

[1] "Connected to : yhcr-prd-bradfor-bia-core"

# Read in person cohort csv

In [2]:
person <- read.csv('data/additional_person_cohorts.csv', header = TRUE)

In [7]:
head(person)

  person_id                                                        birth_date
1 EE91E3C77F2B7CB44F1F601317E2DE5EE76ABB0941F24D4714026B3E30FC313C 1998-09-15
2 C5553DE427E9B8F60E9B5D1E83391E1B660F415A3924B630742D52A0517F5219 1998-09-15
3 AC8CB4071E24E606BFFECC380A9EA11546158370916C4D8D954FA76D63FA81AE 1998-09-15
4 E4E84D0DEB6692712A8E875B701E097EB61235069C56626900C0951E9B112B6D 1998-09-15
5 64FA4602D88C275E27FDBD17EA4678E378D7B297D91C2CDB914150ED0CBF3785 1998-09-15
6 F516562D5CFDDC6CD66FB8EA18399D11BB0E2E042F569D918285FF96C3377338 1998-09-15
  gender CombinedEthnicity cohort
1 M      South Asian       1998/99
2 M      White British     1998/99
3 M      White British     1998/99
4 M      South Asian       1998/99
5 M      White British     1998/99
6 M      White British     1998/99

In [8]:
person |>
nrow()

[1] 23385

In [3]:
person_ids <- read.csv('data/additional_person_ids.csv', header = TRUE)

In [10]:
head(person_ids)

  person_id                                                        NCCIS_ACADYR
1 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2016/2017
2 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 2015/2016
3 000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909 2015/2016
4 00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC 2016/2017
5 0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D 2016/2017
6 0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D 2016/2017

In [11]:
person_ids |>
nrow()

[1] 18999

In [12]:
# Check if all person_ids in person_id are in person
all(person_ids$person_id %in% person$person_id)

[1] TRUE

In [13]:
# filter person to only matching IDs
person_filtered <- person |>
    filter(person_id %in% person_ids$person_id)

In [14]:
person_filtered |>
nrow()

[1] 17538

In [15]:
all(person_ids$person_id %in% person_filtered$person_id)

[1] TRUE

# Siblings / home indicators

In [16]:
school_census_data = "CB_2489.cb_StudentAdditionalInfoFromCensus"

In [17]:
home_table <- tbl(con, school_census_data) |>
    select(person_id, SourceTable, DistCurrSch, Language, IDACIScore_Home, LSOA11_Home, InCare) |>
    filter(!is.na(person_id))

In [188]:
# SGA means based on shared address (vs. on address and surname)
# BirthOrder_SGA 1 is the oldest

In [18]:
home_table

# Source:   SQL [?? x 7]
# Database: BigQueryConnection
   person_id SourceTable DistCurrSch Language IDACIScore_Home LSOA11_Home InCare
   <chr>     <chr>             <dbl> <chr>              <dbl> <chr>       <chr>
 1 1F8E5FB8… Spring_Cen…        0.48 KUR                   NA E01010625   NA
 2 677579B6… Spring_Cen…        0.48 RMN                   NA E01010620   NA
 3 48384998… Spring_Cen…        1.74 ARA                   NA E01010840   NA
 4 53AF9BA8… Spring_Cen…        2.06 CZE                   NA E01013567   NA
 5 AEFA5D1B… Spring_Cen…        0.08 PRSD                  NA E01010872   NA
 6 CA7DE3B3… Spring_Cen…        1.45 ARAS                  NA E01010723   NA
 7 A869AB84… Spring_Cen…        0.22 ENG                   NA E01033258   NA
 8 A04AE770… Spring_Cen…        1.96 ENG                   NA E01010845   NA
 9 1E6FB869… Spring_Cen…        0.19 ENG                   NA E01010717   NA
10 9C16DB10… Spring_Cen…        0.36 ENG                   NA E01010788   NA
# ℹ more rows

In [19]:
home_table_df <- home_table |>
    collect()

In [20]:
home_table_df |>
    nrow()

[1] 6656974

In [21]:
home_table_df |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 302369

In [22]:
home_table_filtered <- home_table_df |>
    filter(person_id %in% person_ids$person_id)

In [23]:
home_table_filtered |>
    nrow()

[1] 546604

In [24]:
home_table_filtered |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 17403

In [25]:
# extract year from source table
home_table_filtered$Year <- substr(home_table_filtered$SourceTable, nchar(home_table_filtered$SourceTable) - 3, nchar(home_table_filtered$SourceTable))

In [26]:
head(home_table_filtered)

  person_id
1 2FA132D5DC56E77DE5E30728AA576966E7F2008CB3F96E1BA9F8754FD5F8DEC3
2 391B645B52F18FFE649DD81418E83E190381418622EDD73A2831C9BEE36DC132
3 164E53437CFA00EF9777758F6F076C95830196AAEDBCF99D8A9418ED78112FB5
4 0BE8A6BB7BC4E2EF84D250DBB3D085F543206E0397395BFED5B6FA9FD2455DFA
5 018B1258C2F1AEE4098F69728BCD61326D343AC119B826BE21430E8D7DAD2857
6 509F6B8CF341FB222E705C40C234F9AE8011298F6BC699B32A9E99D59A8F9D14
  SourceTable        DistCurrSch Language IDACIScore_Home LSOA11_Home InCare
1 PLASC_2004         0.13        NA       0.37225         NA          0
2 PLASC_2004         0.14        NA       0.19546         NA          0
3 Spring_Census_2007 0.26        ENG      0.09306         NA          0
4 Spring_Census_2007 0.31        SPA      0.47297         NA          0
5 Spring_Census_2012 0.84        ENG      0.15428         NA          NA
6 Autumn_Census_2008   NA        ENG      0.42181         NA          NA
  Year
1 2004
2 2004
3 2007
4 2007
5 2012
6 2008

In [27]:
# drop source table col and then merge / remove duplicate rows
home_table_filtered <- home_table_filtered |>
    select(-SourceTable)

In [28]:
home_table_filtered <- home_table_filtered |>
    distinct()

In [29]:
home_table_filtered |>
    nrow()

[1] 457722

In [30]:
home_table_filtered |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 17403

#### drop cols

In [33]:
head(home_table_filtered)

  person_id                                                        DistCurrSch
1 2FA132D5DC56E77DE5E30728AA576966E7F2008CB3F96E1BA9F8754FD5F8DEC3 0.13
2 391B645B52F18FFE649DD81418E83E190381418622EDD73A2831C9BEE36DC132 0.14
3 164E53437CFA00EF9777758F6F076C95830196AAEDBCF99D8A9418ED78112FB5 0.26
4 0BE8A6BB7BC4E2EF84D250DBB3D085F543206E0397395BFED5B6FA9FD2455DFA 0.31
5 018B1258C2F1AEE4098F69728BCD61326D343AC119B826BE21430E8D7DAD2857 0.84
6 509F6B8CF341FB222E705C40C234F9AE8011298F6BC699B32A9E99D59A8F9D14   NA
  Language IDACIScore_Home LSOA11_Home Year
1 NA       0.37225         NA          2004
2 NA       0.19546         NA          2004
3 ENG      0.09306         NA          2007
4 SPA      0.47297         NA          2007
5 ENG      0.15428         NA          2012
6 ENG      0.42181         NA          2008

In [32]:
home_table_filtered <- home_table_filtered |>
    select(-InCare)

In [34]:
# add in cohort identifier so that can drop data from primary school ranges
home_table_merge <- home_table_filtered |>
  left_join(person_filtered |> select(person_id, cohort), by = "person_id")

In [35]:
home_table_merge |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 17403

In [37]:
head(home_table_merge)

  person_id                                                        DistCurrSch
1 2FA132D5DC56E77DE5E30728AA576966E7F2008CB3F96E1BA9F8754FD5F8DEC3 0.13
2 391B645B52F18FFE649DD81418E83E190381418622EDD73A2831C9BEE36DC132 0.14
3 164E53437CFA00EF9777758F6F076C95830196AAEDBCF99D8A9418ED78112FB5 0.26
4 0BE8A6BB7BC4E2EF84D250DBB3D085F543206E0397395BFED5B6FA9FD2455DFA 0.31
5 018B1258C2F1AEE4098F69728BCD61326D343AC119B826BE21430E8D7DAD2857 0.84
6 509F6B8CF341FB222E705C40C234F9AE8011298F6BC699B32A9E99D59A8F9D14   NA
  Language IDACIScore_Home LSOA11_Home Year cohort
1 NA       0.37225         NA          2004 1998/99
2 NA       0.19546         NA          2004 1998/99
3 ENG      0.09306         NA          2007 1998/99
4 SPA      0.47297         NA          2007 1998/99
5 ENG      0.15428         NA          2012 1999/00
6 ENG      0.42181         NA          2008 1998/99

In [39]:
home_table_merge <- home_table_merge |> 
    filter(Year %in% c('2010', '2011', '2012','2013','2014','2015'))

In [40]:
home_table_merge |> distinct(Year) |> pull(Year)

[1] "2012" "2013" "2014" "2010" "2015" "2011"

In [41]:
# where cohort 2001/2 drop 2013 year records
home_table_merge <- home_table_merge |> 
    filter(!(cohort == '1999/00' & Year == '2010'))

In [42]:
# where cohort 2000/1 drop 2018 year records
home_table_merge <- home_table_merge |> 
    filter(!(cohort == '1998/99' & Year == '2015'))

In [43]:
home_table_merge |>
    nrow()

[1] 209168

In [44]:
home_table_merge |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 17208

In [45]:
# drop rows per year with NAs
home_table_merge <- home_table_merge |>
    arrange(desc(Year)) |>
    group_by(person_id, Year) |>
    summarise(across(everything(), ~ ifelse(all(is.na(.)), NA, na.omit(.)[1])), .groups = "drop")

In [46]:
home_table_merge |>
    nrow()

[1] 83043

In [47]:
home_table_merge |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 17208

In [221]:
home_table_merge |>
    filter(person_id == '0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D')

  person_id                                                        Year
1 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2014
2 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2015
3 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2016
4 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2017
5 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2018
  DistCurrSch DistNearSch Language IDACIScore_Home LSOA11_Home cohort
1 1.59        0.81        ENG      0.20557         E01002616   2001/02
2 1.59        0.48        ENG      0.20557         E01002616   2001/02
3 1.59        0.48        ENG           NA         E01002616   2001/02
4 7.01        0.00        ENG      0.12500         E01002563   2001/02
5 7.01        0.00        ENG           NA         E01002563   2001/02

In [48]:
# group by all cols except year, and keep first row of duplicates
home_table_merge <- home_table_merge |>
    arrange(desc(Year)) |>
    group_by(across(-Year)) |>
    filter(row_number() == 1) |>
    ungroup()

In [49]:
home_table_merge |>
    nrow()

[1] 64037

In [225]:
home_table_merge |>
    filter(person_id == '0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D')

  person_id                                                        Year
1 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2018
2 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2017
3 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2016
4 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2015
5 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2014
  DistCurrSch DistNearSch Language IDACIScore_Home LSOA11_Home cohort
1 7.01        0.00        ENG           NA         E01002563   2001/02
2 7.01        0.00        ENG      0.12500         E01002563   2001/02
3 1.59        0.48        ENG           NA         E01002616   2001/02
4 1.59        0.48        ENG      0.20557         E01002616   2001/02
5 1.59        0.81        ENG      0.20557         E01002616   2001/02

In [50]:
# repeat merge rows where there are NA values keep first non NA (latest date prioritised)
home_table_merge <- home_table_merge |>
    arrange(desc(Year)) |>
    group_by(person_id) |>
    summarise(across(everything(), ~ ifelse(all(is.na(.)), NA, na.omit(.)[1])), .groups = "drop")

In [51]:
head(home_table_merge)

  person_id                                                        Year
1 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2015
2 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 2014
3 000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909 2014
4 00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC 2015
5 0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D 2015
6 00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7 2015
  DistCurrSch Language IDACIScore_Home LSOA11_Home cohort
1 2.45        ENG      0.04778         E01027555   1999/00
2 4.71        ENG      0.35519         E01010703   1998/99
3 0.33        ENG      0.37575         E01010742   1998/99
4 1.78        ENG      0.07161         E01010641   1999/00
5 0.76        ENG      0.44704         E01010655   1999/00
6 1.29        ENG      0.41032         E01010626   1999/00

In [229]:
home_table_merge |>
    filter(person_id == '0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D')

  person_id                                                        Year
1 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2018
  DistCurrSch DistNearSch Language IDACIScore_Home LSOA11_Home cohort
1 7.01        0           ENG      0.125           E01002563   2001/02

In [52]:
home_table_merge |> nrow()

[1] 17208

In [53]:
home_table_merge |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 17208

#### EAL

In [54]:
home_table_merge <- home_table_merge |>
    mutate(
    EAL = case_when(
      Language == "ENG" ~ 0,
      is.na(Language) ~ NA,
      TRUE ~ 1 
    )
  )

In [55]:
home_table_merge <- home_table_merge |>
    select(-c(Language, Year))

In [56]:
head(home_table_merge)

  person_id                                                        DistCurrSch
1 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2.45
2 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 4.71
3 000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909 0.33
4 00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC 1.78
5 0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D 0.76
6 00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7 1.29
  IDACIScore_Home LSOA11_Home cohort  EAL
1 0.04778         E01027555   1999/00 0
2 0.35519         E01010703   1998/99 0
3 0.37575         E01010742   1998/99 0
4 0.07161         E01010641   1999/00 0
5 0.44704         E01010655   1999/00 0
6 0.41032         E01010626   1999/00 0

## merge person and home

In [57]:
home_table_merge <- home_table_merge |>
    select(-cohort)

In [58]:
person_home <- person_filtered |> 
    left_join(home_table_merge, by = join_by(person_id))

In [59]:
head(person_home)

  person_id                                                        birth_date
1 EE91E3C77F2B7CB44F1F601317E2DE5EE76ABB0941F24D4714026B3E30FC313C 1998-09-15
2 C5553DE427E9B8F60E9B5D1E83391E1B660F415A3924B630742D52A0517F5219 1998-09-15
3 AC8CB4071E24E606BFFECC380A9EA11546158370916C4D8D954FA76D63FA81AE 1998-09-15
4 E4E84D0DEB6692712A8E875B701E097EB61235069C56626900C0951E9B112B6D 1998-09-15
5 64FA4602D88C275E27FDBD17EA4678E378D7B297D91C2CDB914150ED0CBF3785 1998-09-15
6 F516562D5CFDDC6CD66FB8EA18399D11BB0E2E042F569D918285FF96C3377338 1998-09-15
  gender CombinedEthnicity cohort  DistCurrSch IDACIScore_Home LSOA11_Home EAL
1 M      South Asian       1998/99 0.28        0.39633         E01010830   1
2 M      White British     1998/99 0.66        0.32669         E01012102   0
3 M      White British     1998/99 0.86        0.33826         E01010720   0
4 M      South Asian       1998/99 0.28        0.58239         E01009366   1
5 M      White British     1998/99 3.42        0.04938         E01010648   0
6 M      White British     1998/99 1.24        0.16338         E01023472   0

In [60]:
# save as csv
write.csv(person_home, "data/additional_person_home.csv", row.names = FALSE)

# Disability

In [61]:
student_data = "CB_2489.cb_Student"

student_table <- tbl(con, student_data) |> 
    select(person_id, Gender, Disability) |>
    filter(!is.na(person_id)) |>
    filter(!is.na(Disability))

In [62]:
student_table

# Source:   SQL [?? x 3]
# Database: BigQueryConnection
   person_id                                                   Gender Disability
   <chr>                                                       <chr>  <chr>
 1 1BB207623557A2E675505C4CA5237B7AB9EB8EA3B3D17E70CD93A68926… F      NCOL
 2 26E90FE4263275E646264F68FA34C104CD1AEE6BF45CF0D7F256E117A4… F      NCOL
 3 10BC24A12C475E751290F1DD6CE0129AE5627F2676F2E7041EC4D69026… F      NCOL
 4 EF5BDEACB889527A7BC6F6F29DC7A3CB88F77A7AF5A12E8B6DE9F88F73… F      NCOL
 5 F7FDCCAFC13BA5A4F2FC7E407D12F14C1ACE57A0DB38874412D284C4C1… M      NCOL
 6 D2630283F9C4DFDB64DA4509C55BA1ACC3E62B0D50FFD12CB01721F495… M      NCOL
 7 943242326C63FCA6AAF153271971640F2CDC932543D81CB0A3E3022D93… M      NCOL
 8 EA6F60F9824E3D26D76A78F9EC54279A433AE4390DB2953CCAB34F0300… M      NCOL
 9 24BCE3FCC408EFDB17B492DE055E5E7E7DB013199B3768B60257B4375D… M      NCOL
10 F27B849A12EB97ECE880026DB0E694F30594669BA0870B3DA7088A3B91… M      NCOL
# ℹ more rows

In [63]:
student_df <- collect(student_table)

In [64]:
# filter person to only matching IDs
student_filtered <- student_df |>
    filter(person_id %in% person_ids$person_id)

In [65]:
head(student_filtered)

  person_id                                                        Gender
1 F7FDCCAFC13BA5A4F2FC7E407D12F14C1ACE57A0DB38874412D284C4C1652A65 M
2 E6D87B4F9F70813E09245E9B6A57989B610A678A88F2B9CECDB4616F3B1E1E98 M
3 8CD319109B189BEDAA8347C66D11C90071C6F45324532E2BB5FA981456E67427 M
4 30A1CEE32BBDBD1F6A973E913F42F6E35B85C3B52CAA06D68EEDA313338E79EF M
5 734096AF44FCFC666AA00CFB48B3E16A7BF1F98F8EEC2882D67381F23C20B90B M
6 91482AA2D9D0C6EE53A77B22768E757E4D64533EAFFA2812E2E824A1D1699C4A M
  Disability
1 NCOL
2 NCOL
3 NCOL
4 NCOL
5 NCOL
6 NCOL

In [66]:
student_filtered |> 
  distinct(Disability) |> 
  pull(Disability)

 [1] "NCOL" "NONE" "OTH"  "MED"  "LD"   "INC"  "MOB"  "BEH"  "VIS"  "HEAR"
[11] "COMM" "EAT"  "PC"   "AUT"  "HAND" "CON"

In [67]:
student_table <- student_filtered |> 
  mutate(
    SEN = case_when(
      Disability %in% c('NCOL', "", NA) ~ NA_character_,
      TRUE ~ Disability  # Handle any other unexpected cases
    )
  )

In [68]:
head(student_table)

  person_id                                                        Gender
1 F7FDCCAFC13BA5A4F2FC7E407D12F14C1ACE57A0DB38874412D284C4C1652A65 M
2 E6D87B4F9F70813E09245E9B6A57989B610A678A88F2B9CECDB4616F3B1E1E98 M
3 8CD319109B189BEDAA8347C66D11C90071C6F45324532E2BB5FA981456E67427 M
4 30A1CEE32BBDBD1F6A973E913F42F6E35B85C3B52CAA06D68EEDA313338E79EF M
5 734096AF44FCFC666AA00CFB48B3E16A7BF1F98F8EEC2882D67381F23C20B90B M
6 91482AA2D9D0C6EE53A77B22768E757E4D64533EAFFA2812E2E824A1D1699C4A M
  Disability SEN
1 NCOL       NA
2 NCOL       NA
3 NCOL       NA
4 NCOL       NA
5 NCOL       NA
6 NCOL       NA

In [69]:
student_table |>
    group_by(SEN) |>
    tally() |>
    arrange(desc(n))

   SEN  n
1  NA   15623
2  NONE   502
3  LD     157
4  OTH    155
5  BEH     49
6  COMM    25
7  AUT     10
8  HEAR     9
9  MOB      9
10 VIS      8
11 MED      6
12 EAT      5
13 HAND     3
14 INC      3
15 CON      2
16 PC       2

## SEN

In [62]:
sen_data = "CB_2489.cb_StudentEntitlementFromCensus"

sen_table <- tbl(con, sen_data) |> 
    select(person_id, SourceTable, EVERFSM_ALL, SENprovision, SENprovisionMajor, PrimarySENtype) |>
    filter(!is.na(person_id))

In [7]:
head(sen_table)

# Source:   SQL [6 x 5]
# Database: BigQueryConnection
  person_id             SourceTable EVERFSM_ALL SENprovisionMajor PrimarySENtype
  <chr>                 <chr>             <dbl> <chr>             <chr>
1 B1D77C27358C0FAEEEFE… PLASC_2002           NA NA                NA
2 B0F6576C4FD111B8FC7E… PLASC_2002           NA NA                NA
3 743AE9CEC04DB16EFABD… PLASC_2002           NA NA                NA
4 F8997374AD18D48539CC… PLASC_2002           NA NA                NA
5 F55EE5CB232507DD90FD… PLASC_2002           NA NA                NA
6 85F82007BB545B6BA136… PLASC_2002           NA NA                NA

In [8]:
sen_table |> 
  distinct(SourceTable) |> 
  pull(SourceTable)

 [1] "PLASC_2003"          "PLASC_2004"          "Autumn_Census_2008"
 [4] "Autumn_Census_2011"  "Autumn_Census_2015"  "SUMMER_Census_2006"
 [7] "Spring_Census_2007"  "Spring_Census_2008"  "Spring_Census_2010"
[10] "Spring_Census_2011"  "Spring_Census_2012"  "Spring_Census_2013"
[13] "Spring_Census_2014"  "Summer_Census_2007"  "Summer_Census_2009"
[16] "Summer_Census_2011"  "Summer_Census_2014"  "Autumn_Census_2016"
[19] "Autumn_Census_2017"  "Autumn_Census_2022"  "Spring_Census_2019"
[22] "Spring_Census_2020"  "Spring_Census_2021"  "Spring_Census_2022"
[25] "Summer_Census_2018"  "Summer_Census_2019"  "Summer_Census_2021"
[28] "Summer_Census_2022"  "PLASC_2002"          "PLASC_2005"
[31] "Autumn_Census_2007"  "Autumn_Census_2009"  "Autumn_Census_2010"
[34] "Autumn_Census_2012"  "Autumn_Census_2013"  "Autumn_Census_2014"
[37] "Spring_Census_2006"  "Spring_Census_2009"  "Spring_Census_2015"
[40] "Summer_Census_2008"  "Summer_Census_2010"  "Summer_Census_2012"
[43] "Summer_Census_2013"  "Summer_Census_2015"  "Autumn_Census_2018"
[46] "Autumn_Census_2019"  "Autumn_Census_2020"  "Autumn_Census_2021"
[49] "Spring_Census_2016"  "Summer_Census_2016"  "Summer_Census_20017"

Pupil Level Annual School Census (PLASC)

In [63]:
sen_df <- collect(sen_table)

In [64]:
# filter to person_ids
sen_filtered <- sen_df |>
    filter(person_id %in% person_ids$person_id)

In [65]:
# edit label for Summer_Census_20017
sen_filtered <- sen_filtered |>
    mutate(SourceTable = case_when(
        SourceTable == 'Summer_Census_20017' ~ 'Summer_Census_2017',
        TRUE ~ SourceTable)
           )

In [66]:
# extract year from source table
sen_filtered$Year <- substr(sen_filtered$SourceTable, nchar(sen_filtered$SourceTable) - 3, nchar(sen_filtered$SourceTable))

In [13]:
head(sen_filtered)

  person_id                                                        SourceTable
1 330522675B341B5E7544DD15159765054E653C9A671D282531DD9657FD1493F4 PLASC_2002
2 BB6DCF7E9E10A7D0A39C306A6A6E608A2D5281F97B606FF116251B33ADDF78FF PLASC_2002
3 9D198D6F6864728BDCDC936C82D20DC4C502630F92BF1FC5280A280BC336BBB9 PLASC_2002
4 F95D040681FD17D9CD3A9C5F58EB6A2EF923CB48F464CA3E70E5589705AAE398 PLASC_2002
5 8E57CD24611AC0B35F501586B83737B29FB1BC875EE2E44A8BA0E1E133160E50 PLASC_2003
6 B6DBA3DB9F059985A626C27527A3206BF277AA4261089F171F302C84FAAF20E3 PLASC_2004
  EVERFSM_ALL SENprovisionMajor PrimarySENtype Year
1 NA          NA                NA             2002
2 NA          NA                NA             2002
3 NA          NA                NA             2002
4 NA          NA                NA             2002
5 NA          NA                NA             2003
6 NA          NA                NA             2004

In [14]:
sen_filtered |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 17403

#### extract only FSM col

In [15]:
fsm <- sen_filtered |>
    select(person_id, Year, EVERFSM_ALL)

In [16]:
fsm_filtered <- fsm |>
    filter(!is.na(EVERFSM_ALL))

In [17]:
fsm_filtered |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 17285

In [18]:
# keep latest year only
fsm_filtered <- fsm_filtered |>
      arrange(person_id, desc(Year)) |>
      distinct(person_id, .keep_all = TRUE)

In [19]:
fsm_filtered|>
    nrow()

[1] 17285

In [20]:
fsm_filtered |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 17285

In [21]:
fsm_filtered |>
    group_by(EVERFSM_ALL) |>
    tally()

  EVERFSM_ALL n
1 0           9936
2 1           7349

#### merge in FSM col to main data

In [22]:
fsm_filtered <- fsm_filtered |>
    select(person_id, EVERFSM_ALL) |>
    rename(ever_fsm = EVERFSM_ALL)

In [23]:
person_home <- read.csv("data/additional_person_home.csv", header = TRUE)

In [24]:
person_home_fsm <- person_home |> 
    left_join(fsm_filtered, by = join_by(person_id))

In [25]:
head(person_home_fsm)

  person_id                                                        birth_date
1 EE91E3C77F2B7CB44F1F601317E2DE5EE76ABB0941F24D4714026B3E30FC313C 1998-09-15
2 C5553DE427E9B8F60E9B5D1E83391E1B660F415A3924B630742D52A0517F5219 1998-09-15
3 AC8CB4071E24E606BFFECC380A9EA11546158370916C4D8D954FA76D63FA81AE 1998-09-15
4 E4E84D0DEB6692712A8E875B701E097EB61235069C56626900C0951E9B112B6D 1998-09-15
5 64FA4602D88C275E27FDBD17EA4678E378D7B297D91C2CDB914150ED0CBF3785 1998-09-15
6 F516562D5CFDDC6CD66FB8EA18399D11BB0E2E042F569D918285FF96C3377338 1998-09-15
  gender CombinedEthnicity cohort  DistCurrSch IDACIScore_Home LSOA11_Home EAL
1 M      South Asian       1998/99 0.28        0.39633         E01010830   1
2 M      White British     1998/99 0.66        0.32669         E01012102   0
3 M      White British     1998/99 0.86        0.33826         E01010720   0
4 M      South Asian       1998/99 0.28        0.58239         E01009366   1
5 M      White British     1998/99 3.42        0.04938         E01010648   0
6 M      White British     1998/99 1.24        0.16338         E01023472   0
  ever_fsm
1 1
2 1
3 1
4 1
5 0
6 0

#### SEN cols

In [67]:
sen_filtered <- sen_filtered |>
    select(-c(EVERFSM_ALL)) |>
    arrange(person_id, desc(Year))

In [27]:
head(sen_filtered)

  person_id
1 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
2 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
3 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
4 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
5 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
6 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
  SourceTable        SENprovisionMajor PrimarySENtype Year
1 Autumn_Census_2018 1_NON             NA             2018
2 Summer_Census_2018 1_NON             NA             2018
3 Summer_Census_2017 1_NON             NA             2017
4 Autumn_Census_2017 1_NON             NA             2017
5 Autumn_Census_2016 1_NON             NA             2016
6 Spring_Census_2016 1_NON             NA             2016

In [28]:
sen_filtered |>
    distinct(Year) |> 
    pull(Year)

 [1] "2018" "2017" "2016" "2015" "2014" "2013" "2012" "2011" "2010" "2009"
[11] "2008" "2007" "2006" "2005" "2004" "2003" "2019" "2002" "2020"

In [68]:
sen_filtered_year <- sen_filtered |>
    filter(Year %in% c('2020','2019','2018','2017','2016','2015','2014','2013','2012','2011','2010','2009','2008','2007','2006','2005'))

In [30]:
sen_filtered_year |>
    nrow()

[1] 515260

In [31]:
sen_filtered_year |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 17392

In [46]:
sen_2020 <- sen_filtered_year |>
    filter(Year == '2005') |>
    filter(SENprovisionMajor != '1_NON')

In [47]:
all_2020 <- sen_filtered_year |>
    filter(Year == '2005')

In [48]:
no2020 <- sen_filtered_year |>
    filter(Year != '2005')

In [49]:
# check for any ids in 2020 but not in previous years - if 0 then can drop 2020 (post graduation)
sen_2020_only <- anti_join(sen_2020, no2020, by = "person_id")
sen_2020_only

     person_id SourceTable SENprovisionMajor PrimarySENtype Year

In [50]:
all_2020_only <- anti_join(all_2020, no2020, by = "person_id")
all_2020_only

  person_id                                                        SourceTable
1 601F0BB7480893CC5749F92DA5171829DF2D0AD6AF8FA28A3AE85BCBECFA8AEA PLASC_2005
2 740F81CFCFBB9A1610D7E64432E4D6358DF2F0BA12E8234A2056EA04392EFEEC PLASC_2005
3 AF04D6D1E088B6C8B9B7119D1234D5642C1741E220F8AD24FF07E45CB3318D2F PLASC_2005
4 B65FE3AC1F6360BE6BB988875A2CE44D1627E547EE7C359FDFBF525FF10773F7 PLASC_2005
5 C280FEE80D213F9A65F7446524D6727CC0F108CED1F59D8612A14E6A68BD7B2D PLASC_2005
  SENprovisionMajor PrimarySENtype Year
1 NA                VI             2005
2 NA                SPLD           2005
3 NA                NA             2005
4 NA                SLCN           2005
5 NA                NA             2005

In [69]:
sen_filtered_year <- sen_filtered_year |>
    filter(Year %in% c('2018','2017','2016','2015','2014','2013','2012','2011','2010','2009','2008','2007','2006','2005'))

In [111]:
# only keep the 2020 row for one person with data only in 2020 which is no sen anyway (rather than having unknown for this id)
#sen_filtered_year <- rbind(sen_filtered_year,all_2020_only)

In [52]:
sen_filtered_year |>
    nrow()

[1] 514190

In [70]:
sen_filtered_year |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 17392

In [489]:
#missing_ids <- anti_join(person_ids, sen_filtered_year, by = "person_id") %>%
#  select(person_id) %>%
#  distinct()

In [490]:
#sen_filtered |>
#    filter(person_id %in% missing_ids$person_id) |>
#    distinct(Year) |>
#    pull(Year)

In [491]:
#sen_filtered |>
#    filter(person_id %in% missing_ids$person_id) |>
#    filter(Year =='2005') |>
#    summarise(count = n_distinct(person_id))

In [492]:
#sen_filtered |>
#    filter(person_id %in% missing_ids$person_id) |>
#    filter(Year =='2005')

In [114]:
sen_filtered |>
    filter(person_id =='D2C1319A064B0552A68F440AE60726DB822B2FFFF28F22B134C3EE9937A8A848')

   person_id                                                        SENStage
1  D2C1319A064B0552A68F440AE60726DB822B2FFFF28F22B134C3EE9937A8A848 NA
2  D2C1319A064B0552A68F440AE60726DB822B2FFFF28F22B134C3EE9937A8A848 NA
3  D2C1319A064B0552A68F440AE60726DB822B2FFFF28F22B134C3EE9937A8A848 NA
4  D2C1319A064B0552A68F440AE60726DB822B2FFFF28F22B134C3EE9937A8A848 NA
5  D2C1319A064B0552A68F440AE60726DB822B2FFFF28F22B134C3EE9937A8A848 NA
6  D2C1319A064B0552A68F440AE60726DB822B2FFFF28F22B134C3EE9937A8A848 NA
7  D2C1319A064B0552A68F440AE60726DB822B2FFFF28F22B134C3EE9937A8A848 NA
8  D2C1319A064B0552A68F440AE60726DB822B2FFFF28F22B134C3EE9937A8A848 NA
9  D2C1319A064B0552A68F440AE60726DB822B2FFFF28F22B134C3EE9937A8A848 NA
10 D2C1319A064B0552A68F440AE60726DB822B2FFFF28F22B134C3EE9937A8A848 NA
   SENprovision SENprovisionMajor PrimarySENtype Year
1  P            2_SNS             NA             2011
2  P            2_SNS             SLCN           2011
3  N            1_NON             NA             2010
4  P            2_SNS             SPLD           2010
5  P            2_SNS             NA             2010
6  P            NA                NA             2009
7  N            1_NON             NA             2009
8  P            NA                MLD            2008
9  P            NA                NA             2008
10 N            NA                NA             2008

In [71]:
# leave year arrange as asc so that first instance of new status remains 
sen_cut <- sen_filtered_year |>
    arrange(Year) |>
    group_by(person_id, Year) |>
    summarise(across(everything(), ~ ifelse(all(is.na(.)), NA, na.omit(.)[1])), .groups = "drop")

In [72]:
sen_cut |>
    nrow()

[1] 202762

In [73]:
sen_cut |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 17392

#### clean SEN cols

In [74]:
sen_cut |> 
    nrow()

[1] 202762

In [75]:
sen_clean <- sen_cut

In [76]:
sen_clean |>
    group_by(SENprovision) |>
    tally() |>
    arrange(desc(n))

  SENprovision n
1 N            159097
2 A             24676
3 P             11440
4 S              4175
5 K              2980
6 E               394

In [77]:
sen_clean <- sen_clean |>
    mutate(SENprovisionNEW = case_when(
        SENprovision %in% c('N') ~ 'No SEN',
        SENprovision %in% c('A','P','K') ~ 'SEN support',
        SENprovision %in% c('S','E') ~ 'EHC plan',
        TRUE ~ NA
            )
         )

In [78]:
head(sen_clean)

  person_id                                                        Year
1 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2005
2 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2006
3 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2007
4 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2008
5 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2009
6 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2010
  SourceTable        SENprovision SENprovisionMajor PrimarySENtype
1 PLASC_2005         N            NA                NA
2 Spring_Census_2006 N            NA                NA
3 Summer_Census_2007 N            NA                NA
4 Spring_Census_2008 N            NA                NA
5 Spring_Census_2009 N            1_NON             NA
6 Summer_Census_2010 N            1_NON             NA
  SENprovisionNEW
1 No SEN
2 No SEN
3 No SEN
4 No SEN
5 No SEN
6 No SEN

In [79]:
sen_clean |>
    group_by(SENprovisionMajor) |>
    tally()

  SENprovisionMajor n
1 1_NON             108128
2 2_SNS              27545
3 3_SS                3646
4 NA                 63443

In [80]:
sen_clean <- sen_clean |>
    select(-SENprovision) |>
    mutate(SENmajorNEW = case_when(
        SENprovisionMajor == '1_NON' ~ 'No SEN',
        SENprovisionMajor == '2_SNS' ~ 'SEN support',
        SENprovisionMajor == '3_SS' ~ 'EHC plan',
        TRUE ~ NA
            )
         )

In [81]:
head(sen_clean)

  person_id                                                        Year
1 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2005
2 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2006
3 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2007
4 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2008
5 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2009
6 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2010
  SourceTable        SENprovisionMajor PrimarySENtype SENprovisionNEW
1 PLASC_2005         NA                NA             No SEN
2 Spring_Census_2006 NA                NA             No SEN
3 Summer_Census_2007 NA                NA             No SEN
4 Spring_Census_2008 NA                NA             No SEN
5 Spring_Census_2009 1_NON             NA             No SEN
6 Summer_Census_2010 1_NON             NA             No SEN
  SENmajorNEW
1 NA
2 NA
3 NA
4 NA
5 No SEN
6 No SEN

In [82]:
# check where two new cols dont match
sen_clean |>
    filter(SENprovisionNEW != SENmajorNEW & !is.na(SENprovisionNEW) & !is.na(SENmajorNEW))

    person_id                                                        Year
1   0037E941FE88C2503AF508B5306803DB1693F3200533648162692820D1EA221D 2009
2   00DF0E4C51A21FCBAB2877360CF6663CE4D6A38CDEF3079601A319F3B250AEC6 2009
3   0122DBAEF5317FC0247DB65A54E5AF7ECE614F9651BAF9A1C2948D0E84FAC7D5 2009
4   01846FB39CA12D92AC66CEA2227079A681F9093AFB2925A7B7578AB5B44245A3 2009
5   0377438AD33436A7D103C1FBE4E1FDBF06466C75946C3E5227494FCA5D75A28E 2009
6   03D7BD9ED69833F2058E65F946BEFC23B595C608B3D3CCE833ECAA4D89136DB9 2009
7   040C0FFF4ADA6DFFC51317E106CEA7DC7CE97C71B0E0DCC837D5C57BC079875E 2009
8   04B8154970F2C510741B4D0B1E2DA92E745CE931E114BB151A670FF04CBABACF 2009
9   056F5A1A5ECE89A2FA652093AFADA7C163CE1F6574469191F1940804EC11A171 2009
10  06172BA1965B42C1AD0AAAFAA7141E21A45688AC67F78FF124DB69D73125F1F2 2009
11  069802A46D6D717092FA83889D380FF9949DD12E595A06D1C069D0262837D4A9 2009
12  09F020DE7DB1E76311C02DC7C75251F9C467B35B2C7E6525D8BD73155C035CD6 2009
13  0A4127FD6E81FBFF3A9C32E5CADF04539797DD6E06271240A92FD278CA260B7E 2009
14  0B46FFB6E534E626C851399A4413C15429900ECBF72C471AF7ECAC2295B853C3 2009
15  0B6321E80BAC6CA9519477EBB2E41E1B465FFE1010436B84AD42EF6D5D50341C 2009
16  0B6F89848E100492E359C0AADC0BC18484650B46D0027D325AA7C0712B2BE8D4 2009
17  0BAAEBE8BDE6E0DD5BE0B162B88865E74AB9976B5420F82A6838C37294DEEF3D 2009
18  0D2675541C41A0DE74636BF15F1368A3D994BB655F47CB6C4A10A6EF68D84FAE 2009
19  0DF8990A4ED627C829D907CDB60A0B08A24F0081D3A3CF3A4AD37EC7DCA259E0 2009
20  0F1C170DFD77A8DD6701C4D46F64DF52233F20FB5D0B516D5375E5F9AC1E3BA6 2009
21  107EE3CB6D7255FF9F9D4D6E9C12EE732520FF5A41B374B8DEB8384F7CC09B6B 2009
22  1176A5EA9B48BA9D3AA3B1C048A0CD9E8C80130C6975B6ABD3949F281E25003C 2009
23  12E5A555072F27D0693C9A84003EB075DA83F200984D9B8C5D6B17ED497C84D2 2009
24  133549E59829893227543FEE0BFA061D67C63FD639219583192AD728E4DD9C9F 2009
25  14684442DBAFE42443AC7C7225AD915771EFCA52582FD460AA583A2C476710FA 2009
26  14D540F43106E16E00D6E3271D3F67D307FDC8BDCB9D49A77F5F134E6C91F2E9 2009
27  171A9CCA522DF1F7DFF5CF0F2FC930C46FEB7341F21E738F38405F217C755D8F 2009
28  1854BD4B477C2EF98F02ED64192EF76750690307915BC78EC014848B6BBBF75F 2009
29  19FF963B9B88AB525D81DBAD04FADB566A41DCF2126372D5671F7C3A1E0816D5 2009
30  1A2F1FDCDF85A15B5EA7791D22E71C1329246BD1697429C6693F9A6B318E152D 2009
⋮   ⋮                                                                ⋮
291 E57E67229ABECA11DB3FEF69897032CC406E10A53787EF9B9D70370FD871EA8A 2009
292 E6DD95B4E337FD605D64CB4E24A754AB23C991F9CF157ECB8DD909BCF1750794 2009
293 E78F6082BA5A496AC6176EA31EA9155ED215879ECE5514874CAD53FF40822484 2009
294 E7F560DD7CEA92E8619C518A6E3F3711BF4633081986A1CD742E9A7AD13EBE7E 2009
295 E7FF84DC196A21D3FC72A55298D28811A22A46D1088F08C08AC31E9769465113 2009
296 E8FA3252413F57D4E4CF87C47D283462F7A2FD391DF2CA5C5932B31E98E7AF32 2009
297 EB749CD0AD24493828DD86A7059C0D432301DBFF95E95E0AD5C25E25F559B66F 2009
298 ECFF6CD5D9B3D7F951A9A8B31C596A5BFC70F62BB3F2E0F806BE07A9C96F5BC6 2009
299 EFCB02FAFED077548498ACE420821A27CF7858E2A66C2CB73AAEC4A301C6D30E 2009
300 F040C081613707AEA329E5D3284DC82795402A7F6DEC15CD71098C93C9FE6732 2009
301 F0CB9F90DEFF5D06748F0DAFE0AE3910E4652CF04453FB285A01AD9E7AEBAB86 2009
302 F2E81AD9A3E591145D04529B552DFA5A28AD67F91CC4FE16EB0162406B4CAA4F 2009
303 F555DB92885023D26620B64D1F0CA8E5BB70EC48AEC7A2FE963D90FB7C885352 2009
304 F5E514E03F738349866D17570548EC439299E0E0FD381CC5FBDDA6B3E3268BEB 2009
305 F652FD49DA8B7F8B21F52A523C054200053974F717F5D4E01C99A789A80E2DA8 2009
306 F6A748561C5F0C68DEE7A6B9F8AED5E28B516EC1228D3BE3522E2859D5B0C9BF 2009
307 F7C5FB6F3CD6D7575E4A6B11AE314C8DC3F9C005A8346A7A29CFCBE5F883485C 2009
308 F8107A156FFCE8C9524F6FE2C07B93CA37E2093788E66A084CA451B817523BAB 2009
309 F81CF5A4ECFA333FF0C9F81B7D08CD92FE0E58DC38DB2FF0AC4D32CEC8B2792B 2009
310 F8AD4CA912E221A33610395C1C7440B1F7DEEF2F8DCDAC6581651D1994099DE5 2009
311 F8B97424D17E7502D78DEFF07F6C325217A64CDEBA23F27A89DCF9AD688E71E8 2009
312 F92235234C6109E2FBD1B36B1A87BE3F14AB484998E8DB83BC43F73F038259E1 2009
313 F926824AFA55098F81C6A6D7F2233B03AD82F0BE87134E7F36B22D36236FEC32 2009
314 F93E56DF68739273FB9FB59EADEEA8B5BB533AF00D8CEF6787B43292B6C37CBF 2009
315 FA99ACEDB9B2FE30458899E02EA31D06589D14768E71B770AB334C05AEEFC589 2009
316 FB953D4E32C10AEA6239D21F4E48DB9418412249DE99EF857A7E4DBD938D2847 2009
317 FD8F64DE3EC5904707F30AF37A26C0DC6094B90874D70CB722E829F81C940460 2009
318 FE35B04FBDEEF57519BF242A504D7836EAFC1D81C8A57227767DAD281F132938 2009
319 FEAD8028A454E85E0649CBA449D7000A0E8EFA2B3D55C56809004F9BFFB38643 2009
320 FFBD6A3EECCC20370CAC11CC736BF0A4EC2CA96494106C8C26B3B565003833A7 2009
    SourceTable        SENprovisionMajor PrimarySENtype SENprovisionNEW
1   Autumn_Census_2009 1_NON             NA             SEN support
2   Autumn_Census_2009 2_SNS             NA             No SEN
3   Autumn_Census_2009 1_NON             NA             SEN support
4   Autumn_Census_2009 1_NON             NA             SEN support
5   Autumn_Census_2009 2_SNS             NA             No SEN
6   Autumn_Census_2009 1_NON             NA             SEN support
7   Autumn_Census_2009 1_NON             NA             SEN support
8   Autumn_Census_2009 1_NON             NA             SEN support
9   Autumn_Census_2009 2_SNS             NA             No SEN
10  Autumn_Census_2009 2_SNS             NA             No SEN
11  Autumn_Census_2009 2_SNS             NA             No SEN
12  Autumn_Census_2009 1_NON             NA             SEN support
13  Autumn_Census_2009 2_SNS             NA             No SEN
14  Autumn_Census_2009 2_SNS             NA             No SEN
15  Autumn_Census_2009 2_SNS             NA             No SEN
16  Autumn_Census_2009 2_SNS             NA             No SEN
17  Autumn_Census_2009 1_NON             NA             SEN support
18  Autumn_Census_2009 1_NON             NA             SEN support
19  Autumn_Census_2009 2_SNS             NA             No SEN
20  Autumn_Census_2009 2_SNS             NA             No SEN
21  Autumn_Census_2009 2_SNS             NA             No SEN
22  Autumn_Census_2009 2_SNS             MLD            No SEN
23  Autumn_Census_2009 2_SNS             NA             No SEN
24  Autumn_Census_2009 1_NON             NA             SEN support
25  Autumn_Census_2009 2_SNS             NA             No SEN
26  Autumn_Census_2009 2_SNS             NA             No SEN
27  Autumn_Census_2009 2_SNS             NA             No SEN
28  Autumn_Census_2009 2_SNS             NA             No SEN
29  Autumn_Census_2009 1_NON             NA             SEN support
30  Autumn_Census_2009 1_NON             NA             SEN support
⋮   ⋮                  ⋮                 ⋮              ⋮
291 Autumn_Census_2009 1_NON             NA             SEN support
292 Autumn_Census_2009 2_SNS             NA             No SEN
293 Autumn_Census_2009 1_NON             NA             SEN support
294 Autumn_Census_2009 1_NON             NA             SEN support
295 Autumn_Census_2009 2_SNS             NA             No SEN
296 Autumn_Census_2009 1_NON             NA             SEN support
297 Autumn_Census_2009 2_SNS             NA             No SEN
298 Autumn_Census_2009 2_SNS             NA             No SEN
299 Autumn_Census_2009 2_SNS             NA             No SEN
300 Autumn_Census_2009 2_SNS             NA             No SEN
301 Autumn_Census_2009 2_SNS             BESD           No SEN
302 Autumn_Census_2009 2_SNS             NA             No SEN
303 Autumn_Census_2009 2_SNS             NA             No SEN
304 Autumn_Census_2009 2_SNS             NA             No SEN
305 Autumn_Census_2009 1_NON             NA             SEN support
306 Autumn_Census_2009 1_NON             NA             SEN support
307 Autumn_Census_2009 1_NON             NA             SEN support
308 Autumn_Census_2009 1_NON             NA             SEN support
309 Autumn_Census_2009 2_SNS             NA             No SEN
310 Autumn_Census_2009 2_SNS             NA             No SEN
311 Autumn_Census_2009 1_NON             NA             SEN support
312 Autumn_Census_2009 2_SNS             NA             No SEN
313 Autumn_Census_2009 2_SNS             NA             No SEN
314 Autumn_Census_2009 2_SNS             NA             No SEN
315 Autumn_Census_2009 1_NON             NA             SEN support
316 Autumn_Census_2009 2_SNS             BESD           No SEN
317 Autumn_Census_2009 2_SNS             NA             No SEN
318 Autumn_Census_2009 2_SNS             NA             No SEN
319 Autumn_Census_2009 2_SNS             NA             No SEN
320 Autumn_Census_2009 2_SNS             NA             No SEN
    SENmajorNEW
1   No SEN
2   SEN support
3   No SEN
4   No SEN
5   SEN support
6   No SEN
7   No SEN
8   No SEN
9   SEN support
10  SEN support
11  SEN support
12  No SEN
13  SEN support
14  SEN support
15  SEN support
16  SEN support
17  No SEN
18  No SEN
19  SEN support
20  SEN support
21  SEN support
22  SEN support
23  SEN support
24  No SEN
25  SEN support
26  SEN support
27  SEN support
28  SEN support
29  No SEN
30  No SEN
⋮   ⋮
291 No SEN
292 SEN support
293 No SEN
294 No SEN
295 SEN support
296 No SEN
297 SEN support
298 SEN support
299 SEN support
300 SEN support
301 SEN support
302 SEN support
303 SEN support
304 SEN support
305 No SEN
306 No SEN
307 No SEN
308 No SEN
309 SEN support
310 SEN support
311 No SEN
312 SEN support
313 SEN support
314 SEN support
315 No SEN
316 SEN support
317 SEN support
318 SEN support
319 SEN support
320 SEN support

In [83]:
# merge values across two new cols
# where one of the new cols is no sen and the other is sen, keep sen
sen_clean <- sen_clean |>
    mutate(SENlevel = case_when(
        SENprovisionNEW == SENmajorNEW ~ SENprovisionNEW,  # both are the same
        is.na(SENprovisionNEW) & !is.na(SENmajorNEW) ~ SENmajorNEW,  # drop NA
        !is.na(SENprovisionNEW) & is.na(SENmajorNEW) ~ SENprovisionNEW,  # drop NA
        SENprovisionNEW == "No SEN" & SENmajorNEW == "SEN support" ~ SENmajorNEW,  # SEN support over No SEN
        SENprovisionNEW == "SEN support" & SENmajorNEW == "No SEN" ~ SENprovisionNEW,  # SEN support over No SEN
        SENprovisionNEW == "SEN support" & SENmajorNEW == "EHC plan" ~ SENmajorNEW,  # EHC plan over SEN support 
        SENprovisionNEW == "EHC plan" & SENmajorNEW == "SEN support" ~ SENprovisionNEW,  # EHC plan over SEN support 
        SENprovisionNEW == "No SEN" & SENmajorNEW == "EHC plan" ~ SENmajorNEW,  # EHC plan over SEN support 
        TRUE ~ NA
  ))

In [84]:
# check where two new cols dont match incase of EHCP col not matching
sen_clean |>
    filter(is.na(SENlevel))

     person_id Year SourceTable SENprovisionMajor PrimarySENtype
     SENprovisionNEW SENmajorNEW SENlevel

In [85]:
sen_clean <- sen_clean |>
    select(-SENprovisionMajor)

In [86]:
head(sen_clean)

  person_id                                                        Year
1 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2005
2 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2006
3 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2007
4 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2008
5 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2009
6 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2010
  SourceTable        PrimarySENtype SENprovisionNEW SENmajorNEW SENlevel
1 PLASC_2005         NA             No SEN          NA          No SEN
2 Spring_Census_2006 NA             No SEN          NA          No SEN
3 Summer_Census_2007 NA             No SEN          NA          No SEN
4 Spring_Census_2008 NA             No SEN          NA          No SEN
5 Spring_Census_2009 NA             No SEN          No SEN      No SEN
6 Summer_Census_2010 NA             No SEN          No SEN      No SEN

In [87]:
sen_clean <- sen_clean |>
    select(-c(SENprovisionNEW,SENmajorNEW))

In [89]:
sen_clean <- sen_clean |>
    select(-SourceTable)

In [90]:
# copy previous value where sen level is the same but type is NA
sen_clean <- sen_clean |>
    arrange(person_id, Year) |>  
    group_by(person_id) |>
    mutate(PrimarySENtype = case_when(
          # if NA and SENlevel is same, and prev not NA take prev value
          is.na(PrimarySENtype) & lag(SENlevel) == SENlevel & !is.na(lag(PrimarySENtype)) ~ lag(PrimarySENtype),  
          TRUE ~ PrimarySENtype  # Keep original value otherwise
        )) |>
    #fill(PrimarySENtype, .direction = "down") |>
    ungroup()

In [91]:
# repeat
sen_clean <- sen_clean |>
    arrange(person_id, Year) |>  
    group_by(person_id) |>
    mutate(PrimarySENtype = case_when(
          # if NA and SENlevel is same, and prev not NA take prev value
          is.na(PrimarySENtype) & lag(SENlevel) == SENlevel & !is.na(lag(PrimarySENtype)) ~ lag(PrimarySENtype),  
          TRUE ~ PrimarySENtype  # Keep original value otherwise
        )) |>
    #fill(PrimarySENtype, .direction = "down") |>
    ungroup()

What are the implications of having an SEN but it only being identified / support being put in place when in year 11???

In [92]:
sen_clean |>
    filter(SENlevel != 'No SEN')

      person_id                                                        Year
1     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 2009
2     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 2010
3     0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D 2008
4     00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7 2007
5     00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7 2008
6     00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7 2009
7     00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7 2010
8     00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7 2011
9     001F42538A9E6E496F13CD05B5E9FE91EB3B20F0CEBECA1B76CC5E7151B7A0D4 2011
10    001F42538A9E6E496F13CD05B5E9FE91EB3B20F0CEBECA1B76CC5E7151B7A0D4 2012
11    001F42538A9E6E496F13CD05B5E9FE91EB3B20F0CEBECA1B76CC5E7151B7A0D4 2013
12    001F42538A9E6E496F13CD05B5E9FE91EB3B20F0CEBECA1B76CC5E7151B7A0D4 2014
13    00211975518FD5336E43850D59B5F5DDA7CD98B212760111CB40528BDECF3B1B 2008
14    00211975518FD5336E43850D59B5F5DDA7CD98B212760111CB40528BDECF3B1B 2010
15    00211975518FD5336E43850D59B5F5DDA7CD98B212760111CB40528BDECF3B1B 2011
16    00211975518FD5336E43850D59B5F5DDA7CD98B212760111CB40528BDECF3B1B 2012
17    00211975518FD5336E43850D59B5F5DDA7CD98B212760111CB40528BDECF3B1B 2014
18    00211975518FD5336E43850D59B5F5DDA7CD98B212760111CB40528BDECF3B1B 2015
19    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2006
20    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2007
21    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2008
22    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2009
23    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2010
24    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2011
25    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2012
26    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2013
27    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2014
28    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2015
29    00269FAEA8B5167F1239AA166C20B7673380CCB3E5F3E2F1F6FAA6034A11CE88 2009
30    00269FAEA8B5167F1239AA166C20B7673380CCB3E5F3E2F1F6FAA6034A11CE88 2010
⋮     ⋮                                                                ⋮
43844 FFE8D30492571D5641B63115FFED00DE60D39E160D78483EC4E2BCE0A442F884 2006
43845 FFE8D30492571D5641B63115FFED00DE60D39E160D78483EC4E2BCE0A442F884 2007
43846 FFE8D30492571D5641B63115FFED00DE60D39E160D78483EC4E2BCE0A442F884 2008
43847 FFE8D30492571D5641B63115FFED00DE60D39E160D78483EC4E2BCE0A442F884 2009
43848 FFE8D30492571D5641B63115FFED00DE60D39E160D78483EC4E2BCE0A442F884 2010
43849 FFE8D30492571D5641B63115FFED00DE60D39E160D78483EC4E2BCE0A442F884 2011
43850 FFE8D30492571D5641B63115FFED00DE60D39E160D78483EC4E2BCE0A442F884 2012
43851 FFE8D30492571D5641B63115FFED00DE60D39E160D78483EC4E2BCE0A442F884 2013
43852 FFE8D30492571D5641B63115FFED00DE60D39E160D78483EC4E2BCE0A442F884 2014
43853 FFE8D30492571D5641B63115FFED00DE60D39E160D78483EC4E2BCE0A442F884 2015
43854 FFEBA230449490BA4B1BCEB1A68C790B1D85708DE8C6EAB8CD170D3E52F12775 2005
43855 FFEBA230449490BA4B1BCEB1A68C790B1D85708DE8C6EAB8CD170D3E52F12775 2006
43856 FFEBA2A7088A41ADEF06DE231C6F48B615D19A0CA2D2FC917F432A964C9B2EA3 2006
43857 FFEBA2A7088A41ADEF06DE231C6F48B615D19A0CA2D2FC917F432A964C9B2EA3 2007
43858 FFEBA2A7088A41ADEF06DE231C6F48B615D19A0CA2D2FC917F432A964C9B2EA3 2008
43859 FFEBA2A7088A41ADEF06DE231C6F48B615D19A0CA2D2FC917F432A964C9B2EA3 2009
43860 FFEBA2A7088A41ADEF06DE231C6F48B615D19A0CA2D2FC917F432A964C9B2EA3 2010
43861 FFEBA2A7088A41ADEF06DE231C6F48B615D19A0CA2D2FC917F432A964C9B2EA3 2011
43862 FFEBA2A7088A41ADEF06DE231C6F48B615D19A0CA2D2FC917F432A964C9B2EA3 2012
43863 FFEBA2A7088A41ADEF06DE231C6F48B615D19A0CA2D2FC917F432A964C9B2EA3 2013
43864 FFEBA2A7088A41ADEF06DE231C6F48B615D19A0CA2D2FC917F432A964C9B2EA3 2014
43865 FFEBA2A7088A41ADEF06DE231C6F48B615D19A0CA2D2FC917F432A964C9B2EA3 2015
43866 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC 2006
43867 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC 2012
43868 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC 2013
43869 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC 2014
43870 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB 2008
43871 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB 2009
43872 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB 2011
43873 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB 2012
      PrimarySENtype SENlevel
1     NA             SEN support
2     NA             SEN support
3     NA             SEN support
4     NA             SEN support
5     NA             SEN support
6     NA             SEN support
7     NA             SEN support
8     NA             SEN support
9     NA             SEN support
10    NA             SEN support
11    NA             SEN support
12    NA             SEN support
13    NA             SEN support
14    SPLD           SEN support
15    BESD           SEN support
16    BESD           SEN support
17    BESD           EHC plan
18    SEMH           EHC plan
19    NA             SEN support
20    NA             SEN support
21    NA             SEN support
22    NA             SEN support
23    NA             SEN support
24    NA             SEN support
25    NA             SEN support
26    NA             SEN support
27    NA             SEN support
28    NA             SEN support
29    NA             SEN support
30    NA             SEN support
⋮     ⋮              ⋮
43844 BESD           EHC plan
43845 SPLD           EHC plan
43846 SPLD           EHC plan
43847 SPLD           EHC plan
43848 SPLD           EHC plan
43849 MLD            EHC plan
43850 MLD            EHC plan
43851 MLD            EHC plan
43852 MLD            EHC plan
43853 MLD            EHC plan
43854 OTH            SEN support
43855 OTH            SEN support
43856 MLD            SEN support
43857 MLD            SEN support
43858 MLD            SEN support
43859 NA             SEN support
43860 SPLD           SEN support
43861 SPLD           SEN support
43862 SPLD           SEN support
43863 SPLD           SEN support
43864 SPLD           SEN support
43865 SPLD           SEN support
43866 MLD            SEN support
43867 NA             SEN support
43868 NA             SEN support
43869 NA             SEN support
43870 NA             SEN support
43871 NA             SEN support
43872 NA             SEN support
43873 NA             SEN support

In [93]:
sen_clean <- sen_clean |>
    mutate(PrimarySENtype = case_when(
        PrimarySENtype == 'BESD' ~ 'SEMH',
        TRUE ~ PrimarySENtype)
           )

In [ ]:
sen_clean <- sen_clean |>

#### join cohort id

In [94]:
sen_clean_cohort <- sen_clean |>
    left_join(person_ids, by = join_by(person_id))

Warning message in left_join(sen_clean, person_ids, by = join_by(person_id)):
“Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 53 of `x` matches multiple rows in `y`.
ℹ Row 1 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.”

In [95]:
sen_clean_cohort

       person_id                                                        Year
1      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2005
2      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2006
3      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2007
4      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2008
5      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2009
6      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2010
7      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2011
8      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2012
9      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2013
10     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2014
11     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2015
12     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2016
13     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2017
14     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2018
15     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 2005
16     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 2006
17     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 2007
18     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 2008
19     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 2009
20     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 2010
21     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 2011
22     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 2012
23     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 2013
24     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 2014
25     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 2015
26     000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909 2005
27     000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909 2006
28     000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909 2007
29     000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909 2008
30     000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909 2009
⋮      ⋮                                                                ⋮
218290 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB 2014
218291 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB 2015
218292 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB 2016
218293 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008 2005
218294 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008 2006
218295 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008 2007
218296 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008 2008
218297 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008 2009
218298 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008 2010
218299 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008 2011
218300 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008 2012
218301 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008 2013
218302 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008 2014
218303 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008 2015
218304 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008 2016
218305 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008 2017
218306 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008 2018
218307 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA 2005
218308 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA 2006
218309 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA 2007
218310 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA 2008
218311 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA 2009
218312 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA 2010
218313 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA 2011
218314 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA 2012
218315 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA 2013
218316 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA 2014
218317 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA 2015
218318 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA 2016
218319 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA 2017
       PrimarySENtype SENlevel    NCCIS_ACADYR
1      NA             No SEN      2016/2017
2      NA             No SEN      2016/2017
3      NA             No SEN      2016/2017
4      NA             No SEN      2016/2017
5      NA             No SEN      2016/2017
6      NA             No SEN      2016/2017
7      NA             No SEN      2016/2017
8      NA             No SEN      2016/2017
9      NA             No SEN      2016/2017
10     NA             No SEN      2016/2017
11     NA             No SEN      2016/2017
12     NA             No SEN      2016/2017
13     NA             No SEN      2016/2017
14     NA             No SEN      2016/2017
15     NA             No SEN      2015/2016
16     NA             No SEN      2015/2016
17     NA             No SEN      2015/2016
18     NA             No SEN      2015/2016
19     NA             SEN support 2015/2016
20     NA             SEN support 2015/2016
21     NA             No SEN      2015/2016
22     NA             No SEN      2015/2016
23     NA             No SEN      2015/2016
24     NA             No SEN      2015/2016
25     NA             No SEN      2015/2016
26     NA             No SEN      2015/2016
27     NA             No SEN      2015/2016
28     NA             No SEN      2015/2016
29     NA             No SEN      2015/2016
30     NA             No SEN      2015/2016
⋮      ⋮              ⋮           ⋮
218290 NA             No SEN      2016/2017
218291 NA             No SEN      2016/2017
218292 NA             No SEN      2016/2017
218293 NA             No SEN      2016/2017
218294 NA             No SEN      2016/2017
218295 NA             No SEN      2016/2017
218296 NA             No SEN      2016/2017
218297 NA             No SEN      2016/2017
218298 NA             No SEN      2016/2017
218299 NA             No SEN      2016/2017
218300 NA             No SEN      2016/2017
218301 NA             No SEN      2016/2017
218302 NA             No SEN      2016/2017
218303 NA             No SEN      2016/2017
218304 NA             No SEN      2016/2017
218305 NA             No SEN      2016/2017
218306 NA             No SEN      2016/2017
218307 NA             No SEN      2015/2016
218308 NA             No SEN      2015/2016
218309 NA             No SEN      2015/2016
218310 NA             No SEN      2015/2016
218311 NA             No SEN      2015/2016
218312 NA             No SEN      2015/2016
218313 NA             No SEN      2015/2016
218314 NA             No SEN      2015/2016
218315 NA             No SEN      2015/2016
218316 NA             No SEN      2015/2016
218317 NA             No SEN      2015/2016
218318 NA             No SEN      2015/2016
218319 NA             No SEN      2015/2016

#### check missing sen type against extras from exclusion tables

In [96]:
sen <- read.csv('data/additional_sen_extras.csv', header = TRUE)

In [97]:
head(sen)

  person_id
1 13A5184415FCC22BFF3F2EFFD8D3B69FAB1949AFB346B8A15B449CBED2CDB473
2 02304796B373267AE442202D65322A36B8844DD043A88734014D6434DD7D1F12
3 04584E57ADBD062B2BA9DB9076CF692E45F5767837BD87EEE4FED6DB521BB84B
4 66927CC16F370C097C232D8581FB0E92E89F688DE966B50CD1A128B631F9DB6A
5 778E21A7061D57C78E5986180FAE5D061F1F8B2B69F1925CDD0FCDC4B424AEF1
6 7D46116A75B15250162ECE83B71941167D4FFAE82D39C508681D25F69C50BF32
  PrimarySENtype
1 BESD
2 BESD
3 OTH
4 MLD
5 BESD
6 BESD

In [98]:
missing_type <- sen_clean_cohort |>
    filter(SENlevel != 'No SEN' & is.na(PrimarySENtype))

In [99]:
missing_type

      person_id                                                        Year
1     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 2009
2     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 2010
3     0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D 2008
4     0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D 2008
5     00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7 2007
6     00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7 2008
7     00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7 2009
8     00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7 2010
9     00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7 2011
10    001F42538A9E6E496F13CD05B5E9FE91EB3B20F0CEBECA1B76CC5E7151B7A0D4 2011
11    001F42538A9E6E496F13CD05B5E9FE91EB3B20F0CEBECA1B76CC5E7151B7A0D4 2012
12    001F42538A9E6E496F13CD05B5E9FE91EB3B20F0CEBECA1B76CC5E7151B7A0D4 2013
13    001F42538A9E6E496F13CD05B5E9FE91EB3B20F0CEBECA1B76CC5E7151B7A0D4 2014
14    00211975518FD5336E43850D59B5F5DDA7CD98B212760111CB40528BDECF3B1B 2008
15    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2006
16    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2006
17    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2007
18    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2007
19    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2008
20    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2008
21    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2009
22    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2009
23    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2010
24    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2010
25    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2011
26    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2011
27    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2012
28    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2012
29    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2013
30    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9 2013
⋮     ⋮                                                                ⋮
21021 FF87772E341BABD802077555E62FB0C28F67C988A30868E6E9F2DA6D557D7DF1 2008
21022 FF87772E341BABD802077555E62FB0C28F67C988A30868E6E9F2DA6D557D7DF1 2009
21023 FF8E8AF167DFF1BAF1D811D242FA37AF571E9F0D9A71C329110B911ED5BD0577 2007
21024 FF8E8AF167DFF1BAF1D811D242FA37AF571E9F0D9A71C329110B911ED5BD0577 2008
21025 FF8E8AF167DFF1BAF1D811D242FA37AF571E9F0D9A71C329110B911ED5BD0577 2009
21026 FF8E8AF167DFF1BAF1D811D242FA37AF571E9F0D9A71C329110B911ED5BD0577 2010
21027 FFB4377E08770663A747BC594EB9DAB119751856BE2BFD42B18070EDC7F58420 2007
21028 FFB4377E08770663A747BC594EB9DAB119751856BE2BFD42B18070EDC7F58420 2008
21029 FFBD6A3EECCC20370CAC11CC736BF0A4EC2CA96494106C8C26B3B565003833A7 2009
21030 FFBF093B81AF4B734782FF9C927D3A86B9581F52D2E18D059CC2DDBA97110CDA 2007
21031 FFBF093B81AF4B734782FF9C927D3A86B9581F52D2E18D059CC2DDBA97110CDA 2008
21032 FFBF093B81AF4B734782FF9C927D3A86B9581F52D2E18D059CC2DDBA97110CDA 2009
21033 FFBF093B81AF4B734782FF9C927D3A86B9581F52D2E18D059CC2DDBA97110CDA 2010
21034 FFBF093B81AF4B734782FF9C927D3A86B9581F52D2E18D059CC2DDBA97110CDA 2011
21035 FFBF093B81AF4B734782FF9C927D3A86B9581F52D2E18D059CC2DDBA97110CDA 2012
21036 FFC53382EFC80944BF643197EFC665798C754FA8E41038787A7E7B316B99A75B 2006
21037 FFC53382EFC80944BF643197EFC665798C754FA8E41038787A7E7B316B99A75B 2007
21038 FFC53382EFC80944BF643197EFC665798C754FA8E41038787A7E7B316B99A75B 2008
21039 FFC53382EFC80944BF643197EFC665798C754FA8E41038787A7E7B316B99A75B 2009
21040 FFC53382EFC80944BF643197EFC665798C754FA8E41038787A7E7B316B99A75B 2010
21041 FFC53382EFC80944BF643197EFC665798C754FA8E41038787A7E7B316B99A75B 2011
21042 FFC53382EFC80944BF643197EFC665798C754FA8E41038787A7E7B316B99A75B 2012
21043 FFEBA2A7088A41ADEF06DE231C6F48B615D19A0CA2D2FC917F432A964C9B2EA3 2009
21044 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC 2012
21045 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC 2013
21046 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC 2014
21047 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB 2008
21048 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB 2009
21049 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB 2011
21050 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB 2012
      PrimarySENtype SENlevel    NCCIS_ACADYR
1     NA             SEN support 2015/2016
2     NA             SEN support 2015/2016
3     NA             SEN support 2016/2017
4     NA             SEN support 2016/2017
5     NA             SEN support 2016/2017
6     NA             SEN support 2016/2017
7     NA             SEN support 2016/2017
8     NA             SEN support 2016/2017
9     NA             SEN support 2016/2017
10    NA             SEN support 2015/2016
11    NA             SEN support 2015/2016
12    NA             SEN support 2015/2016
13    NA             SEN support 2015/2016
14    NA             SEN support 2015/2016
15    NA             SEN support 2015/2016
16    NA             SEN support 2015/2016
17    NA             SEN support 2015/2016
18    NA             SEN support 2015/2016
19    NA             SEN support 2015/2016
20    NA             SEN support 2015/2016
21    NA             SEN support 2015/2016
22    NA             SEN support 2015/2016
23    NA             SEN support 2015/2016
24    NA             SEN support 2015/2016
25    NA             SEN support 2015/2016
26    NA             SEN support 2015/2016
27    NA             SEN support 2015/2016
28    NA             SEN support 2015/2016
29    NA             SEN support 2015/2016
30    NA             SEN support 2015/2016
⋮     ⋮              ⋮           ⋮
21021 NA             SEN support 2015/2016
21022 NA             SEN support 2015/2016
21023 NA             SEN support 2016/2017
21024 NA             SEN support 2016/2017
21025 NA             SEN support 2016/2017
21026 NA             SEN support 2016/2017
21027 NA             SEN support 2015/2016
21028 NA             SEN support 2015/2016
21029 NA             SEN support 2015/2016
21030 NA             SEN support 2015/2016
21031 NA             SEN support 2015/2016
21032 NA             SEN support 2015/2016
21033 NA             SEN support 2015/2016
21034 NA             SEN support 2015/2016
21035 NA             SEN support 2015/2016
21036 NA             SEN support 2016/2017
21037 NA             SEN support 2016/2017
21038 NA             SEN support 2016/2017
21039 NA             SEN support 2016/2017
21040 NA             SEN support 2016/2017
21041 NA             SEN support 2016/2017
21042 NA             SEN support 2016/2017
21043 NA             SEN support 2015/2016
21044 NA             SEN support 2016/2017
21045 NA             SEN support 2016/2017
21046 NA             SEN support 2016/2017
21047 NA             SEN support 2016/2017
21048 NA             SEN support 2016/2017
21049 NA             SEN support 2016/2017
21050 NA             SEN support 2016/2017

In [100]:
# Check if all person_ids in person_id are in person
any(sen$person_id %in% missing_type$person_id)

[1] TRUE

In [101]:
sum(sen$person_id %in% missing_type$person_id)

[1] 805

In [102]:
sen <- sen |>
    mutate(PrimarySENtype = case_when(
        PrimarySENtype == 'BESD' ~ 'SEMH',
        TRUE ~ PrimarySENtype)
           )

#### compute 'ever' values

In [103]:
sen_clean_cohort <- sen_clean_cohort |> 
  mutate(Year = as.integer(Year))  # Convert Year to integer

In [104]:
sen_final <- sen_clean_cohort |> 
  group_by(person_id) |> 
  summarize(
    ever_SEN_support = any(SENlevel == "SEN support"),
    first_SEN_support_year = ifelse(ever_SEN_support, min(Year[SENlevel == "SEN support"], na.rm = TRUE), NA),
    SEN_support_need = ifelse(ever_SEN_support, paste(na.omit(unique(PrimarySENtype[SENlevel == "SEN support"])), collapse = ", "), NA),

    ever_EHC_plan = any(SENlevel == "EHC plan"),
    first_EHC_plan_year = ifelse(ever_EHC_plan, min(Year[SENlevel == "EHC plan"], na.rm = TRUE), NA),
    EHC_plan_need = ifelse(ever_EHC_plan, paste(na.omit(unique(PrimarySENtype[SENlevel == "EHC plan"])), collapse = ", "), NA),

    no_SEN = all(SENlevel == "No SEN")
  )

In [105]:
sen_final

      person_id
1     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
2     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
3     000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909
4     00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC
5     0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
6     00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7
7     001F42538A9E6E496F13CD05B5E9FE91EB3B20F0CEBECA1B76CC5E7151B7A0D4
8     00211975518FD5336E43850D59B5F5DDA7CD98B212760111CB40528BDECF3B1B
9     00237E9C21696BB29409630166F2D9CCEC24B83FB120AEDD878DDD54C6516B3D
10    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9
11    0025102C0D8E8C5F27454E3715E982A43E1431991E85562E55BCB19D9D1BD7D3
12    0025514088C52FB45B7439689844A1FEA2FB8B2753994F432CC7DDC68036BD59
13    00269FAEA8B5167F1239AA166C20B7673380CCB3E5F3E2F1F6FAA6034A11CE88
14    0026BFA5D5426F421200AB505AAD52956621DCC253241A6647302BCE4764547D
15    002D3DB2625339C740EB129CCC925A9D90E4F5AA05561B81FE166EDF990B8F65
16    002E7A9E65A6A184952E4F1811844FCFCCE758FAE60986A1F9B9C9892FD0895D
17    003196BCDC325A98F118130F185DF8FDDE1B8E1E4882719DAE198B2908F03A5B
18    0032202712FAB3A372409235FFE3C0486E36F9B2FB9C9C9851B4ACAB9A3330F0
19    0037E941FE88C2503AF508B5306803DB1693F3200533648162692820D1EA221D
20    0043C7C252748432DF62E306CCC2DFF568A52DC78D4021140E3C4676C9D65A7E
21    00450DFB52E0DDD50F5800AD149075B29E4A1454F36B9ACF2E106CF44B9BED55
22    0045ADA48CA299BC4445318E8D951610DCB89A829665CFC821E92340F0F8B30D
23    0046475B3089CF6E67A50BBAB6ACC4D6C7FA957BEE68B7F8365239D87857F197
24    0046A4A849F346DFC497329C2BEE0509FAC101F8F4683542D6B453D1C10156BE
25    004AA9D5C19D6B421D63DF6E9FB8BA6C671707143EF6FD6794AC73DE319156B0
26    004CD18444BDD86E6C7F4BE1EE806175325E95085AEBC68E7CAA36A747BD2824
27    004D0B5FF90E252B2912022950FEC4929A1ACB81BA61A626F3093B3B496C93CA
28    004D2E4310F936F43F4D73B1BD31894B7273A1E30C1A028DAAC81939B9572966
29    004FE0E78454FE677A07F1AD8D1226F61C6534E08B44EE01DC6C518FE2200DEA
30    0050C79DAB376114E567D08BE22EA699565E600DFC9F3BD68705700FA49DE62C
⋮     ⋮
17363 FF7EFC3006B327BC644769B23FF20D6E4AFBD5EAE86EE2110BB9B3E1E7317740
17364 FF87772E341BABD802077555E62FB0C28F67C988A30868E6E9F2DA6D557D7DF1
17365 FF8A2758AC947462FBCFD2DCD8024A4EDC6A7C6B63C5E87AB1ABA8D7CF3DCCF0
17366 FF8DEC4753882445FD9D524D7235E53252C52529C3B00C22A96D7C693BEEAC4C
17367 FF8E8AF167DFF1BAF1D811D242FA37AF571E9F0D9A71C329110B911ED5BD0577
17368 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
17369 FF9EA711F52DA4D4DF1670062FB8E2C0AEB31E8FC6EB0797CC1A29644957872C
17370 FFAB3C449F625A8B0527299C27FB85E818A99752883B172742E224652383116F
17371 FFB4377E08770663A747BC594EB9DAB119751856BE2BFD42B18070EDC7F58420
17372 FFB5122C6D8418A48E6FB924782900EF5E4605E4ECFD42FFB6C3119515E32C2F
17373 FFB5635E90C51B5347572A1D06AD63844EBA1C885834A3FB3F09AE4CB361A019
17374 FFB9583A0820E84F60A840CDB2D2E143E87A2BE0091320FEBFD0FC7A5C9A7C5B
17375 FFBC13351F5A42EBF9E6A394DD518A4EF6363B0BBAEE35D691F457292C455ED8
17376 FFBD6A3EECCC20370CAC11CC736BF0A4EC2CA96494106C8C26B3B565003833A7
17377 FFBF093B81AF4B734782FF9C927D3A86B9581F52D2E18D059CC2DDBA97110CDA
17378 FFC07EC8DFA7528E9E1C34B30490DC24EDC687B160DC3F750BB70DB3C45CA343
17379 FFC53382EFC80944BF643197EFC665798C754FA8E41038787A7E7B316B99A75B
17380 FFDE0350353E1B484F83298958E0F735D428D6B50E78471B87509497F4406002
17381 FFE133B080FD044D5E6FDC0E74D7303B3D41419692A96B3E116D180FE9EB2F06
17382 FFE244494ADA5394035640D578E70F7D57EBA5F67793F328CEF11B0B124491E2
17383 FFE326BEEDD9B7453AA81BB7251D3F724AB1351CD2D45090955FC0B1EC4377EF
17384 FFE326E526FAA00EF542D85A2BEBF681FB29C82A21EDA118DCD93D32035A203B
17385 FFE8D30492571D5641B63115FFED00DE60D39E160D78483EC4E2BCE0A442F884
17386 FFEBA230449490BA4B1BCEB1A68C790B1D85708DE8C6EAB8CD170D3E52F12775
17387 FFEBA2A7088A41ADEF06DE231C6F48B615D19A0CA2D2FC917F432A964C9B2EA3
17388 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
17389 FFEF385FC541F397C34ACF193D6936D6BB045655B8781D7CFF18D632AAE9ED10
17390 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB
17391 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
17392 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
      ever_SEN_support first_SEN_support_year SEN_support_need ever_EHC_plan
1     FALSE              NA                   NA               FALSE
2      TRUE            2009                                    FALSE
3     FALSE              NA                   NA               FALSE
4     FALSE              NA                   NA               FALSE
5      TRUE            2008                                    FALSE
6      TRUE            2007                                    FALSE
7      TRUE            2011                                    FALSE
8      TRUE            2008                   SPLD, SEMH        TRUE
9     FALSE              NA                   NA               FALSE
10     TRUE            2006                                    FALSE
11    FALSE              NA                   NA               FALSE
12    FALSE              NA                   NA               FALSE
13     TRUE            2009                   MLD              FALSE
14    FALSE              NA                   NA               FALSE
15    FALSE              NA                   NA               FALSE
16    FALSE              NA                   NA               FALSE
17     TRUE            2007                                    FALSE
18    FALSE              NA                   NA               FALSE
19     TRUE            2009                                    FALSE
20    FALSE              NA                   NA               FALSE
21    FALSE              NA                   NA               FALSE
22     TRUE            2006                   SEMH              TRUE
23     TRUE            2012                                    FALSE
24    FALSE              NA                   NA               FALSE
25     TRUE            2010                                    FALSE
26    FALSE              NA                   NA               FALSE
27    FALSE              NA                   NA               FALSE
28    FALSE              NA                   NA               FALSE
29     TRUE            2007                   OTH, VI          FALSE
30     TRUE            2005                   SLCN, OTH        FALSE
⋮     ⋮                ⋮                      ⋮                ⋮
17363  TRUE            2009                                    FALSE
17364  TRUE            2007                                    FALSE
17365 FALSE              NA                   NA               FALSE
17366 FALSE              NA                   NA               FALSE
17367  TRUE            2007                                    FALSE
17368 FALSE              NA                   NA               FALSE
17369 FALSE              NA                   NA               FALSE
17370 FALSE              NA                   NA               FALSE
17371  TRUE            2007                   SEMH             FALSE
17372 FALSE              NA                   NA               FALSE
17373  TRUE            2005                   MLD              FALSE
17374 FALSE              NA                   NA               FALSE
17375  TRUE            2016                   MLD              FALSE
17376  TRUE            2006                   MLD              FALSE
17377  TRUE            2005                   MLD              FALSE
17378 FALSE              NA                   NA               FALSE
17379  TRUE            2006                                    FALSE
17380  TRUE            2006                   OTH              FALSE
17381 FALSE              NA                   NA               FALSE
17382  TRUE            2006                   MLD              FALSE
17383 FALSE              NA                   NA               FALSE
17384  TRUE            2005                   SLD              FALSE
17385  TRUE            2005                   SEMH              TRUE
17386  TRUE            2005                   OTH              FALSE
17387  TRUE            2006                   MLD, SPLD        FALSE
17388  TRUE            2006                   MLD              FALSE
17389 FALSE              NA                   NA               FALSE
17390  TRUE            2008                                    FALSE
17391 FALSE              NA                   NA               FALSE
17392 FALSE              NA                   NA               FALSE
      first_EHC_plan_year EHC_plan_need   no_SEN
1       NA                NA               TRUE
2       NA                NA              FALSE
3       NA                NA               TRUE
4       NA                NA               TRUE
5       NA                NA              FALSE
6       NA                NA              FALSE
7       NA                NA              FALSE
8     2014                SEMH            FALSE
9       NA                NA               TRUE
10      NA                NA              FALSE
11      NA                NA               TRUE
12      NA                NA               TRUE
13      NA                NA              FALSE
14      NA                NA               TRUE
15      NA                NA               TRUE
16      NA                NA               TRUE
17      NA                NA              FALSE
18      NA                NA               TRUE
19      NA                NA              FALSE
20      NA                NA               TRUE
21      NA                NA               TRUE
22    2011                SEMH            FALSE
23      NA                NA              FALSE
24      NA                NA               TRUE
25      NA                NA              FALSE
26      NA                NA               TRUE
27      NA                NA               TRUE
28      NA                NA               TRUE
29      NA                NA              FALSE
30      NA                NA              FALSE
⋮     ⋮                   ⋮               ⋮
17363   NA                NA              FALSE
17364   NA                NA              FALSE
17365   NA                NA               TRUE
17366   NA                NA               TRUE
17367   NA                NA              FALSE
17368   NA                NA               TRUE
17369   NA                NA               TRUE
17370   NA                NA               TRUE
17371   NA                NA              FALSE
17372   NA                NA               TRUE
17373   NA                NA              FALSE
17374   NA                NA               TRUE
17375   NA                NA              FALSE
17376   NA                NA              FALSE
17377   NA                NA              FALSE
17378   NA                NA               TRUE
17379   NA                NA              FALSE
17380   NA                NA              FALSE
17381   NA                NA               TRUE
17382   NA                NA              FALSE
17383   NA                NA               TRUE
17384   NA                NA              FALSE
17385 2006                SEMH, SPLD, MLD FALSE
17386   NA                NA              FALSE
17387   NA                NA              FALSE
17388   NA                NA              FALSE
17389   NA                NA               TRUE
17390   NA                NA              FALSE
17391   NA                NA               TRUE
17392   NA                NA               TRUE

In [106]:
sen_final |> nrow()

[1] 17392

#### ARCHIVE filter to one record pp with year as first record of SEN need

In [58]:
# group by all cols except year, and keep first row of duplicates
sen_merge <- sen_clean |>
    arrange(desc(Year)) |>
    group_by(across(-Year)) |>
    filter(row_number() == 1) |>
    ungroup() |>
    arrange(person_id)

In [59]:
sen_merge |>
    filter(person_id == 'D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E')

  person_id                                                        Year
1 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E 2020
2 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E 2017
3 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E 2014
  PrimarySENtype SENlevel
1 NA             No SEN
2 SPLD           SEN support
3 NA             SEN support

In [60]:
sen_merge |>
arrange(person_id, desc(Year))

      person_id                                                        Year
1     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2017
2     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2015
3     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2017
4     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2006
5     0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2018
6     0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2017
7     0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2011
8     0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2008
9     0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2005
10    0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2018
11    0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2017
12    0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2013
13    00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66 2019
14    0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D 2017
15    0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D 2016
16    0018E26A40A6299391164D4918658B0B1248367C762DCE6D2FDF1AE131A9138C 2019
17    0018E26A40A6299391164D4918658B0B1248367C762DCE6D2FDF1AE131A9138C 2018
18    0018E26A40A6299391164D4918658B0B1248367C762DCE6D2FDF1AE131A9138C 2007
19    0019031CD62586D59268772800516ED50CDF1EF7DE46488542BB031850F6E68A 2018
20    0019031CD62586D59268772800516ED50CDF1EF7DE46488542BB031850F6E68A 2017
21    0019031CD62586D59268772800516ED50CDF1EF7DE46488542BB031850F6E68A 2014
22    001B7CEB7B4CC529920A0B9F5B83D1AC0019E5DC44B3FBB3CEF665C331C0C3B6 2018
23    001E539C263734CC355646811C93CF85B0C587D2EBA8B0D79290FDE8A75D6267 2017
24    001E539C263734CC355646811C93CF85B0C587D2EBA8B0D79290FDE8A75D6267 2013
25    001E5C1FFA964716BF5E84562BC0B5D64F7742B1E8126718A5C0157D485F215D 2020
26    001F566795F57F5D8DD92430D868A38B757699844E3E09569B33253527012932 2020
27    001FFD3AA96B7E4FC5BB9A2F7502CD45BFCC35882335F1C34F78DD9AE5667225 2020
28    001FFD3AA96B7E4FC5BB9A2F7502CD45BFCC35882335F1C34F78DD9AE5667225 2006
29    00222373A6082CDBF94DA04F23E7EB4C8775BEE122FE9C29FBF521900A498EDF 2017
30    00222373A6082CDBF94DA04F23E7EB4C8775BEE122FE9C29FBF521900A498EDF 2007
⋮     ⋮                                                                ⋮
30500 FFACDC831FAAA09353CAB36C5828F34E508AC8BFED1B4B07999BAF198CAC4EEA 2019
30501 FFBCE0C32A37E3663F1C5159ECFC6F08CD5722E938464A58634F3263003F1D9F 2020
30502 FFC0379FDA559C1337454C579FF36F9AE82E62D16B3223D009C57DEC3731754C 2020
30503 FFC7129859DD885141E316248A0EB23059DB0F0DB98242C34C67F06FBBAB8041 2020
30504 FFC96F346EC6829E7A31F60109FD729DE208D180104B50FC8B1BFAD552D6C8FC 2018
30505 FFD30596592DA2C82B86241FBA35E56C7384E7EF8219DB076458B4F9ACDED786 2017
30506 FFD30596592DA2C82B86241FBA35E56C7384E7EF8219DB076458B4F9ACDED786 2016
30507 FFD30596592DA2C82B86241FBA35E56C7384E7EF8219DB076458B4F9ACDED786 2009
30508 FFD391941F3AA9CB910FFFACF24CC2CEAD0BC63EED146E9C21B2C71BA77B084A 2018
30509 FFD391941F3AA9CB910FFFACF24CC2CEAD0BC63EED146E9C21B2C71BA77B084A 2017
30510 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2018
30511 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2016
30512 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2014
30513 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2011
30514 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951 2008
30515 FFE1AA7D705C959745A85B91C6D3F3D22A57B8E50092E9EC25046F6986F77D96 2017
30516 FFE1AA7D705C959745A85B91C6D3F3D22A57B8E50092E9EC25046F6986F77D96 2014
30517 FFE1AA7D705C959745A85B91C6D3F3D22A57B8E50092E9EC25046F6986F77D96 2011
30518 FFE837A538A9166CC4089E844F651277391B496479F4691CE27BF1000C49223B 2017
30519 FFE837A538A9166CC4089E844F651277391B496479F4691CE27BF1000C49223B 2014
30520 FFEA068077E4464D059236951F07D7DF96542C2197AAFAC3E20C036BACB9825C 2020
30521 FFEF2AA9E8BD72D6A0E7CE50F067E4247E12738F53AE726CD94A4D9CB588C702 2018
30522 FFEFD5577D0112E9304118DB7851CF61BEE4DD3D3184EEA756C076317925508F 2017
30523 FFEFD5577D0112E9304118DB7851CF61BEE4DD3D3184EEA756C076317925508F 2009
30524 FFFA6705A275195BFE8A443AF0BD2AA86B1AA0481D330D8665813206EB8DAD43 2020
30525 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77 2020
30526 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77 2013
30527 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 2018
30528 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2017
30529 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 2010
      PrimarySENtype SENlevel
1     ASD            SEN support
2     NA             No SEN
3     MLD            SEN support
4     NA             No SEN
5     NA             EHC plan
6     MLD            EHC plan
7     MLD            SEN support
8     NA             No SEN
9     SLCN           SEN support
10    NA             SEN support
11    MLD            SEN support
12    NA             No SEN
13    NA             No SEN
14    NA             SEN support
15    NA             No SEN
16    PD             SEN support
17    NA             SEN support
18    NA             No SEN
19    NA             SEN support
20    SEMH           SEN support
21    NA             No SEN
22    NA             No SEN
23    NA             No SEN
24    NA             SEN support
25    NA             No SEN
26    NA             No SEN
27    NA             No SEN
28    MLD            SEN support
29    MLD            SEN support
30    NA             SEN support
⋮     ⋮              ⋮
30500 NA             No SEN
30501 NA             No SEN
30502 NA             No SEN
30503 NA             No SEN
30504 NA             No SEN
30505 NA             SEN support
30506 NA             No SEN
30507 MLD            SEN support
30508 NA             SEN support
30509 NA             No SEN
30510 NA             EHC plan
30511 ASD            SEN support
30512 BESD           SEN support
30513 NA             SEN support
30514 NA             No SEN
30515 SEMH           SEN support
30516 NA             SEN support
30517 NA             No SEN
30518 NA             No SEN
30519 BESD           SEN support
30520 NA             No SEN
30521 NA             No SEN
30522 NA             No SEN
30523 MLD            SEN support
30524 NA             No SEN
30525 NA             No SEN
30526 NA             SEN support
30527 NA             No SEN
30528 NA             No SEN
30529 NA             SEN support

In [575]:
# copy previous value where sen level is NA but type not NA
sen_level_clean <- sen_merge |>
    arrange(person_id, Year) |>  
    group_by(person_id) |>
    mutate(SENlevel = case_when(
          # if NA and prev SENlevel is SEN support, and type not NA 
          SENlevel == 'No SEN' & lag(SENlevel) == 'SEN support' & !is.na(PrimarySENtype) ~ 'SEN support',  
          SENlevel == 'No SEN' & lag(SENlevel) == 'EHC plan' & !is.na(PrimarySENtype) ~ 'EHC plan',
          TRUE ~ SENlevel  # Keep original value otherwise
        )) |>
    ungroup()

In [576]:
sen_level_clean |>
    filter(person_id == 'D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E')

  person_id                                                        Year
1 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E 2007
2 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E 2008
3 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E 2010
4 D7759C6DE1092426F3CAD1789805C59D6DB27F497B8C8C7038E2E1A4985FC11E 2013
  PrimarySENtype SENlevel
1 NA             No SEN
2 NA             SEN support
3 SPLD           SEN support
4 SPLD           SEN support

In [585]:
# repeat but for desc year
sen_level_desc <- sen_level_clean |>
    arrange(person_id, desc(Year)) |>  
    group_by(person_id) |>
    mutate(SENlevel = case_when(
          # if NA and prev SENlevel is SEN support, and type not NA 
          SENlevel == 'No SEN' & lag(SENlevel) == 'SEN support' & !is.na(PrimarySENtype) ~ 'SEN support',  
          SENlevel == 'No SEN' & lag(SENlevel) == 'EHC plan' & !is.na(PrimarySENtype) ~ 'EHC plan',
          TRUE ~ SENlevel  # Keep original value otherwise
        )) |>
    ungroup()

In [591]:
# repeat to catch gaps
sen_level_desc <- sen_level_desc |>
    arrange(person_id, Year) |>  
    group_by(person_id) |>
    mutate(SENlevel = case_when(
          # if NA and prev SENlevel is SEN support, and type not NA 
          SENlevel == 'No SEN' & lag(SENlevel) == 'SEN support' & !is.na(PrimarySENtype) ~ 'SEN support',  
          SENlevel == 'No SEN' & lag(SENlevel) == 'EHC plan' & !is.na(PrimarySENtype) ~ 'EHC plan',
          TRUE ~ SENlevel  # Keep original value otherwise
        )) |>
    ungroup()

In [594]:
sen_level_desc |>
    filter(person_id == 'D4D7BBA8B62A4CEB3450B49A97320FCD1E420F8D489BBA9AF698C2124BC88147')

  person_id                                                        Year
1 D4D7BBA8B62A4CEB3450B49A97320FCD1E420F8D489BBA9AF698C2124BC88147 2006
2 D4D7BBA8B62A4CEB3450B49A97320FCD1E420F8D489BBA9AF698C2124BC88147 2008
3 D4D7BBA8B62A4CEB3450B49A97320FCD1E420F8D489BBA9AF698C2124BC88147 2013
4 D4D7BBA8B62A4CEB3450B49A97320FCD1E420F8D489BBA9AF698C2124BC88147 2016
  PrimarySENtype SENlevel
1 NA             No SEN
2 SEMH           SEN support
3 SEMH           SEN support
4 SEMH           SEN support

In [595]:
missing_senlevel <- sen_level_desc |>
    filter(SENlevel == 'No SEN' & !is.na(PrimarySENtype))

In [596]:
missing_senlevel |>
    summarize(n_distinct(person_id))

  n_distinct(person_id)
1 64

In [598]:
sen_level_desc |>
    filter(person_id %in% missing_senlevel$person_id) |>
    distinct(SENlevel)

  SENlevel
1 No SEN

In [599]:
sen_level_desc |>
    filter(person_id %in% missing_senlevel$person_id) |>
    arrange(person_id, Year)

    person_id                                                        Year
1   05BECC2FA9168CC3CC4A8669F2B6BEF1235BB7A7386DDA71141D0444C1A34D87 2005
2   0607C1DA04A1A88F14F80F5DB04C9112B950A68544F2F21E241F94F3AC7D6E78 2006
3   0607C1DA04A1A88F14F80F5DB04C9112B950A68544F2F21E241F94F3AC7D6E78 2015
4   137AAFFB957B50C9C3509763EEE31B4AD73661BB93279CBBCCFB377BDE975C8D 2006
5   137AAFFB957B50C9C3509763EEE31B4AD73661BB93279CBBCCFB377BDE975C8D 2015
6   1E2DDA056F48950C6617E5D8209A6CB6E5583CD02031694903C9E11461C1B70B 2006
7   1E2DDA056F48950C6617E5D8209A6CB6E5583CD02031694903C9E11461C1B70B 2015
8   20E40E9631F550A80DC84266D8EA9118EE12F0C0498AEF95D4ED1DAC9A5124ED 2006
9   20E40E9631F550A80DC84266D8EA9118EE12F0C0498AEF95D4ED1DAC9A5124ED 2015
10  21D5645242C07A3BA957B9BB0D4FCA5919A131A16F8B0D738BE93C986D91BE19 2005
11  21D5645242C07A3BA957B9BB0D4FCA5919A131A16F8B0D738BE93C986D91BE19 2016
12  25F20084CCDCC4C36969A2B69319897EFD35547672A1BB15A74E2696CA91CB25 2011
13  25F20084CCDCC4C36969A2B69319897EFD35547672A1BB15A74E2696CA91CB25 2015
14  267E4A245B7E7853BBFE3B71279DF24E7EC5C3BA53D33D5EE67055AC6E202341 2005
15  267E4A245B7E7853BBFE3B71279DF24E7EC5C3BA53D33D5EE67055AC6E202341 2011
16  2D3529D793F5D5FE48E4D46340B0CDA08163402C37512A1D03CFBD04F5A74069 2006
17  2D3529D793F5D5FE48E4D46340B0CDA08163402C37512A1D03CFBD04F5A74069 2013
18  2D714368F0D540D3478EED42CC13DC75B3988A104484E4A29C0906E8F149CDB6 2006
19  2D714368F0D540D3478EED42CC13DC75B3988A104484E4A29C0906E8F149CDB6 2020
20  308CF0AD7F040CF19307CE47DA196814651BDDFB85B61DCDDC55646AA7D7EA3F 2016
21  308CF0AD7F040CF19307CE47DA196814651BDDFB85B61DCDDC55646AA7D7EA3F 2020
22  315A97DA7FBCC9BA54B558B8F941F6998766F57A2B7B1879F97F51D9E7A81FAF 2006
23  315A97DA7FBCC9BA54B558B8F941F6998766F57A2B7B1879F97F51D9E7A81FAF 2015
24  329713B0F69A6C27FC40A56E3541B55D5C0B602EA3DB11C5086033CE15DC765E 2016
25  341F2B5CDE9327ADDA42B452ED60EBE3320AE0B624013C59FAAE6D0B47979459 2005
26  37A5FC349F5078BA1A93905D6295C39C98CF573BED89CA3EAAFA5BCA1598117A 2006
27  37A5FC349F5078BA1A93905D6295C39C98CF573BED89CA3EAAFA5BCA1598117A 2015
28  3DFB204D7C85040E07790642ADA942B9FDF8DD6DF02950FF43387E9B3D5E7E9C 2006
29  3DFB204D7C85040E07790642ADA942B9FDF8DD6DF02950FF43387E9B3D5E7E9C 2013
30  4161459C0AA4D9B12A0068D59E8E1D30CD34833BF599E788E91967EADCCE88C1 2006
⋮   ⋮                                                                ⋮
92  CBF57090D7BE517787C6D0DC11A768A42BC9EB9FE0D1286AFBFD08C5C799F0AA 2005
93  D361AD6405F7B3035A1AB7131C0487841F609B867EB8BFDBEC924DE01C0C497B 2006
94  D361AD6405F7B3035A1AB7131C0487841F609B867EB8BFDBEC924DE01C0C497B 2012
95  D5A60DAAA3112F1E82AD2001F9E5026FA7A04EAD8ADAD19CC4C63AFBAD6B4B80 2006
96  D5A60DAAA3112F1E82AD2001F9E5026FA7A04EAD8ADAD19CC4C63AFBAD6B4B80 2007
97  D62EEA35AC8962663BC4A21CE585418D10526DF30C00D600875F983BBB6D5474 2006
98  D62EEA35AC8962663BC4A21CE585418D10526DF30C00D600875F983BBB6D5474 2014
99  D6B25EFED1431714C98FF5F5589024B572764254347F00B836A7BB594A83A3B7 2007
100 D6B25EFED1431714C98FF5F5589024B572764254347F00B836A7BB594A83A3B7 2020
101 D8758BE9A3FFD63DA723ED5D42819CD01EDFEFC30D5987E8D5A123AD7B4473A8 2013
102 D8758BE9A3FFD63DA723ED5D42819CD01EDFEFC30D5987E8D5A123AD7B4473A8 2015
103 DD60886DDF05972D479065F98B085EFBD8E30A532DBEB78219DBE41D2DFF4CC9 2007
104 DD60886DDF05972D479065F98B085EFBD8E30A532DBEB78219DBE41D2DFF4CC9 2010
105 E0876FCA4B343D1F2BD2844B5057949E021E14DA27CD8EB86BE0FE40ABB922A0 2005
106 E0876FCA4B343D1F2BD2844B5057949E021E14DA27CD8EB86BE0FE40ABB922A0 2015
107 E822DF2372856FD8EC9B701F87E7915A9374166C34280BC70E46A9C4A3B78593 2006
108 E822DF2372856FD8EC9B701F87E7915A9374166C34280BC70E46A9C4A3B78593 2016
109 E95448F90589E3FD517AD3298510EA4D8685DBD1D947D79AABFC575CAEA69244 2007
110 E95448F90589E3FD517AD3298510EA4D8685DBD1D947D79AABFC575CAEA69244 2020
111 F6AD9A9D94833D0CD4071DC885AB28680AA5CA22FEFDF0B7B96ED89FB20B3B7D 2006
112 F6AD9A9D94833D0CD4071DC885AB28680AA5CA22FEFDF0B7B96ED89FB20B3B7D 2015
113 F962BCF164905BDF98A950D0FEADBCC87644CDDCB771D75087C92A430DB8903B 2005
114 F962BCF164905BDF98A950D0FEADBCC87644CDDCB771D75087C92A430DB8903B 2013
115 F98E338A63C4C981F45BBEAD8F83E8300B53167DA6769FCA43329E53C5B3BD98 2005
116 FDFDD20EAB3F4831B4C00505FCB2FF699EA9EB50383F165F7A0CF1AB66D201D1 2007
117 FDFDD20EAB3F4831B4C00505FCB2FF699EA9EB50383F165F7A0CF1AB66D201D1 2008
118 FE7FA26269B82E8538308FB70947B77B3304BFA4122FA569C0A8DF32C1D0A4A6 2007
119 FE7FA26269B82E8538308FB70947B77B3304BFA4122FA569C0A8DF32C1D0A4A6 2015
120 FFE837A538A9166CC4089E844F651277391B496479F4691CE27BF1000C49223B 2006
121 FFE837A538A9166CC4089E844F651277391B496479F4691CE27BF1000C49223B 2014
    PrimarySENtype SENlevel
1   OTH            No SEN
2   NA             No SEN
3   OTH            No SEN
4   NA             No SEN
5   SPLD           No SEN
6   NA             No SEN
7   OTH            No SEN
8   NA             No SEN
9   SPLD           No SEN
10  NA             No SEN
11  SPLD           No SEN
12  NA             No SEN
13  SEMH           No SEN
14  NA             No SEN
15  MLD            No SEN
16  NA             No SEN
17  SEMH           No SEN
18  NA             No SEN
19  SPLD           No SEN
20  NA             No SEN
21  OTH            No SEN
22  NA             No SEN
23  OTH            No SEN
24  MLD            No SEN
25  OTH            No SEN
26  NA             No SEN
27  SPLD           No SEN
28  NA             No SEN
29  OTH            No SEN
30  NA             No SEN
⋮   ⋮              ⋮
92  OTH            No SEN
93  NA             No SEN
94  OTH            No SEN
95  NA             No SEN
96  SEMH           No SEN
97  NA             No SEN
98  SEMH           No SEN
99  NA             No SEN
100 ASD            No SEN
101 NA             No SEN
102 SEMH           No SEN
103 NA             No SEN
104 MLD            No SEN
105 NA             No SEN
106 SEMH           No SEN
107 NA             No SEN
108 SEMH           No SEN
109 NA             No SEN
110 ASD            No SEN
111 NA             No SEN
112 SPLD           No SEN
113 NA             No SEN
114 SPLD           No SEN
115 OTH            No SEN
116 NA             No SEN
117 SLCN           No SEN
118 NA             No SEN
119 SPLD           No SEN
120 NA             No SEN
121 SEMH           No SEN

In [603]:
sen_final <- sen_level_desc |>
    arrange(desc(Year)) |>            
    group_by(person_id) |>            
    filter(row_number() == 1) |>      
    ungroup()

In [604]:
sen_final |>
    group_by(PrimarySENtype) |>
    tally()

   PrimarySENtype n
1  ASD              230
2  HI               128
3  MLD             1540
4  MSI                3
5  NSA               54
6  OTH              204
7  PD               150
8  PMLD              27
9  SEMH            1128
10 SLCN             405
11 SLD              100
12 SPLD             441
13 VI                74
14 NA             12740

In [606]:
head(sen_final)

  person_id                                                        Year
1 0BAA7959F866DC200B0DE7C16B5B16DD63D6D6BA086D46BA9D26025AC7FB1FB6 2020
2 18A1DBCA368AFAADA2DAC40BD35DE4E1756E5C5905C643A9DFD8590ED65BC980 2020
3 18BDC8758A1C2629E1B3FE7677D649961D106A4E3C5371B14B2EE6FBC12D6162 2020
4 191B614E755130087F1A4C6F61D7CA413FC57CDE42DE350168AF9F21079A5A3D 2020
5 1E8EDACA982683915764BFB3DA811D133E1AD9879F0512C019E4307EFF8E2D13 2020
6 248B0C2E0DD811AC20D8D8940381A477C3041C6B299278C2F7C44AB3E3E098A0 2020
  PrimarySENtype SENlevel
1 OTH            SEN support
2 HI             SEN support
3 VI             SEN support
4 VI             SEN support
5 SEMH           SEN support
6 OTH            SEN support

In [621]:
sen_final <- sen_final |>
    rename(SENtype = PrimarySENtype) |>
    select(-Year)

In [622]:
sen_final |>
    nrow()

[1] 17224

In [623]:
sen_final |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 17224

#### merge SEN into main data

In [107]:
# save as csv
write.csv(sen_final, "data/additional_sen_final.csv", row.names = FALSE)

In [108]:
person_home_fsm_sen <- sen_final |> 
    left_join(person_home_fsm, by = join_by(person_id))

In [109]:
person_home_fsm_sen

      person_id
1     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
2     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
3     000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909
4     00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC
5     0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
6     00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7
7     001F42538A9E6E496F13CD05B5E9FE91EB3B20F0CEBECA1B76CC5E7151B7A0D4
8     00211975518FD5336E43850D59B5F5DDA7CD98B212760111CB40528BDECF3B1B
9     00237E9C21696BB29409630166F2D9CCEC24B83FB120AEDD878DDD54C6516B3D
10    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9
11    0025102C0D8E8C5F27454E3715E982A43E1431991E85562E55BCB19D9D1BD7D3
12    0025514088C52FB45B7439689844A1FEA2FB8B2753994F432CC7DDC68036BD59
13    00269FAEA8B5167F1239AA166C20B7673380CCB3E5F3E2F1F6FAA6034A11CE88
14    0026BFA5D5426F421200AB505AAD52956621DCC253241A6647302BCE4764547D
15    002D3DB2625339C740EB129CCC925A9D90E4F5AA05561B81FE166EDF990B8F65
16    002E7A9E65A6A184952E4F1811844FCFCCE758FAE60986A1F9B9C9892FD0895D
17    003196BCDC325A98F118130F185DF8FDDE1B8E1E4882719DAE198B2908F03A5B
18    0032202712FAB3A372409235FFE3C0486E36F9B2FB9C9C9851B4ACAB9A3330F0
19    0037E941FE88C2503AF508B5306803DB1693F3200533648162692820D1EA221D
20    0043C7C252748432DF62E306CCC2DFF568A52DC78D4021140E3C4676C9D65A7E
21    00450DFB52E0DDD50F5800AD149075B29E4A1454F36B9ACF2E106CF44B9BED55
22    0045ADA48CA299BC4445318E8D951610DCB89A829665CFC821E92340F0F8B30D
23    0046475B3089CF6E67A50BBAB6ACC4D6C7FA957BEE68B7F8365239D87857F197
24    0046A4A849F346DFC497329C2BEE0509FAC101F8F4683542D6B453D1C10156BE
25    004AA9D5C19D6B421D63DF6E9FB8BA6C671707143EF6FD6794AC73DE319156B0
26    004CD18444BDD86E6C7F4BE1EE806175325E95085AEBC68E7CAA36A747BD2824
27    004D0B5FF90E252B2912022950FEC4929A1ACB81BA61A626F3093B3B496C93CA
28    004D2E4310F936F43F4D73B1BD31894B7273A1E30C1A028DAAC81939B9572966
29    004FE0E78454FE677A07F1AD8D1226F61C6534E08B44EE01DC6C518FE2200DEA
30    0050C79DAB376114E567D08BE22EA699565E600DFC9F3BD68705700FA49DE62C
⋮     ⋮
17363 FF7EFC3006B327BC644769B23FF20D6E4AFBD5EAE86EE2110BB9B3E1E7317740
17364 FF87772E341BABD802077555E62FB0C28F67C988A30868E6E9F2DA6D557D7DF1
17365 FF8A2758AC947462FBCFD2DCD8024A4EDC6A7C6B63C5E87AB1ABA8D7CF3DCCF0
17366 FF8DEC4753882445FD9D524D7235E53252C52529C3B00C22A96D7C693BEEAC4C
17367 FF8E8AF167DFF1BAF1D811D242FA37AF571E9F0D9A71C329110B911ED5BD0577
17368 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
17369 FF9EA711F52DA4D4DF1670062FB8E2C0AEB31E8FC6EB0797CC1A29644957872C
17370 FFAB3C449F625A8B0527299C27FB85E818A99752883B172742E224652383116F
17371 FFB4377E08770663A747BC594EB9DAB119751856BE2BFD42B18070EDC7F58420
17372 FFB5122C6D8418A48E6FB924782900EF5E4605E4ECFD42FFB6C3119515E32C2F
17373 FFB5635E90C51B5347572A1D06AD63844EBA1C885834A3FB3F09AE4CB361A019
17374 FFB9583A0820E84F60A840CDB2D2E143E87A2BE0091320FEBFD0FC7A5C9A7C5B
17375 FFBC13351F5A42EBF9E6A394DD518A4EF6363B0BBAEE35D691F457292C455ED8
17376 FFBD6A3EECCC20370CAC11CC736BF0A4EC2CA96494106C8C26B3B565003833A7
17377 FFBF093B81AF4B734782FF9C927D3A86B9581F52D2E18D059CC2DDBA97110CDA
17378 FFC07EC8DFA7528E9E1C34B30490DC24EDC687B160DC3F750BB70DB3C45CA343
17379 FFC53382EFC80944BF643197EFC665798C754FA8E41038787A7E7B316B99A75B
17380 FFDE0350353E1B484F83298958E0F735D428D6B50E78471B87509497F4406002
17381 FFE133B080FD044D5E6FDC0E74D7303B3D41419692A96B3E116D180FE9EB2F06
17382 FFE244494ADA5394035640D578E70F7D57EBA5F67793F328CEF11B0B124491E2
17383 FFE326BEEDD9B7453AA81BB7251D3F724AB1351CD2D45090955FC0B1EC4377EF
17384 FFE326E526FAA00EF542D85A2BEBF681FB29C82A21EDA118DCD93D32035A203B
17385 FFE8D30492571D5641B63115FFED00DE60D39E160D78483EC4E2BCE0A442F884
17386 FFEBA230449490BA4B1BCEB1A68C790B1D85708DE8C6EAB8CD170D3E52F12775
17387 FFEBA2A7088A41ADEF06DE231C6F48B615D19A0CA2D2FC917F432A964C9B2EA3
17388 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
17389 FFEF385FC541F397C34ACF193D6936D6BB045655B8781D7CFF18D632AAE9ED10
17390 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB
17391 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
17392 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
      ever_SEN_support first_SEN_support_year SEN_support_need ever_EHC_plan
1     FALSE              NA                   NA               FALSE
2      TRUE            2009                                    FALSE
3     FALSE              NA                   NA               FALSE
4     FALSE              NA                   NA               FALSE
5      TRUE            2008                                    FALSE
6      TRUE            2007                                    FALSE
7      TRUE            2011                                    FALSE
8      TRUE            2008                   SPLD, SEMH        TRUE
9     FALSE              NA                   NA               FALSE
10     TRUE            2006                                    FALSE
11    FALSE              NA                   NA               FALSE
12    FALSE              NA                   NA               FALSE
13     TRUE            2009                   MLD              FALSE
14    FALSE              NA                   NA               FALSE
15    FALSE              NA                   NA               FALSE
16    FALSE              NA                   NA               FALSE
17     TRUE            2007                                    FALSE
18    FALSE              NA                   NA               FALSE
19     TRUE            2009                                    FALSE
20    FALSE              NA                   NA               FALSE
21    FALSE              NA                   NA               FALSE
22     TRUE            2006                   SEMH              TRUE
23     TRUE            2012                                    FALSE
24    FALSE              NA                   NA               FALSE
25     TRUE            2010                                    FALSE
26    FALSE              NA                   NA               FALSE
27    FALSE              NA                   NA               FALSE
28    FALSE              NA                   NA               FALSE
29     TRUE            2007                   OTH, VI          FALSE
30     TRUE            2005                   SLCN, OTH        FALSE
⋮     ⋮                ⋮                      ⋮                ⋮
17363  TRUE            2009                                    FALSE
17364  TRUE            2007                                    FALSE
17365 FALSE              NA                   NA               FALSE
17366 FALSE              NA                   NA               FALSE
17367  TRUE            2007                                    FALSE
17368 FALSE              NA                   NA               FALSE
17369 FALSE              NA                   NA               FALSE
17370 FALSE              NA                   NA               FALSE
17371  TRUE            2007                   SEMH             FALSE
17372 FALSE              NA                   NA               FALSE
17373  TRUE            2005                   MLD              FALSE
17374 FALSE              NA                   NA               FALSE
17375  TRUE            2016                   MLD              FALSE
17376  TRUE            2006                   MLD              FALSE
17377  TRUE            2005                   MLD              FALSE
17378 FALSE              NA                   NA               FALSE
17379  TRUE            2006                                    FALSE
17380  TRUE            2006                   OTH              FALSE
17381 FALSE              NA                   NA               FALSE
17382  TRUE            2006                   MLD              FALSE
17383 FALSE              NA                   NA               FALSE
17384  TRUE            2005                   SLD              FALSE
17385  TRUE            2005                   SEMH              TRUE
17386  TRUE            2005                   OTH              FALSE
17387  TRUE            2006                   MLD, SPLD        FALSE
17388  TRUE            2006                   MLD              FALSE
17389 FALSE              NA                   NA               FALSE
17390  TRUE            2008                                    FALSE
17391 FALSE              NA                   NA               FALSE
17392 FALSE              NA                   NA               FALSE
      first_EHC_plan_year EHC_plan_need   no_SEN birth_date gender
1       NA                NA               TRUE  1999-09-15 F
2       NA                NA              FALSE  1999-08-15 F
3       NA                NA               TRUE  1998-11-15 M
4       NA                NA               TRUE  2000-05-15 M
5       NA                NA              FALSE  2000-08-15 F
6       NA                NA              FALSE  1999-09-15 M
7       NA                NA              FALSE  1999-01-15 F
8     2014                SEMH            FALSE  1998-10-15 M
9       NA                NA               TRUE  1999-03-15 M
10      NA                NA              FALSE  1999-07-15 F
11      NA                NA               TRUE  1999-06-15 M
12      NA                NA               TRUE  2000-04-15 M
13      NA                NA              FALSE  2000-01-15 M
14      NA                NA               TRUE  1998-09-15 F
15      NA                NA               TRUE  1999-08-15 F
16      NA                NA               TRUE  1999-05-15 F
17      NA                NA              FALSE  1998-09-15 M
18      NA                NA               TRUE  1999-08-15 M
19      NA                NA              FALSE  2000-06-15 F
20      NA                NA               TRUE  1998-12-15 F
21      NA                NA               TRUE  1999-07-15 M
22    2011                SEMH            FALSE  1999-07-15 M
23      NA                NA              FALSE  1999-11-15 M
24      NA                NA               TRUE  2000-01-15 F
25      NA                NA              FALSE  2000-03-15 F
26      NA                NA               TRUE  1999-11-15 M
27      NA                NA               TRUE  2000-08-15 F
28      NA                NA               TRUE  2000-08-15 F
29      NA                NA              FALSE  1999-06-15 F
30      NA                NA              FALSE  1999-06-15 M
⋮     ⋮                   ⋮               ⋮      ⋮          ⋮
17363   NA                NA              FALSE  1999-05-15 M
17364   NA                NA              FALSE  1998-11-15 F
17365   NA                NA               TRUE  1999-03-15 M
17366   NA                NA               TRUE  2000-01-15 F
17367   NA                NA              FALSE  2000-02-15 F
17368   NA                NA               TRUE  1999-10-15 F
17369   NA                NA               TRUE  1998-11-15 F
17370   NA                NA               TRUE  1999-06-15 F
17371   NA                NA              FALSE  1999-05-15 F
17372   NA                NA               TRUE  1999-01-15 F
17373   NA                NA              FALSE  1999-04-15 M
17374   NA                NA               TRUE  1999-01-15 F
17375   NA                NA              FALSE  1999-08-15 M
17376   NA                NA              FALSE  1998-12-15 F
17377   NA                NA              FALSE  1999-04-15 M
17378   NA                NA               TRUE  1999-05-15 M
17379   NA                NA              FALSE  2000-05-15 M
17380   NA                NA              FALSE  2000-06-15 F
17381   NA                NA               TRUE  1999-07-15 F
17382   NA                NA              FALSE  1999-02-15 F
17383   NA                NA               TRUE  1999-12-15 M
17384   NA                NA              FALSE  2000-05-15 F
17385 2006                SEMH, SPLD, MLD FALSE  1999-02-15 M
17386   NA                NA              FALSE  2000-05-15 F
17387   NA                NA              FALSE  1999-05-15 F
17388   NA                NA              FALSE  1999-11-15 M
17389   NA                NA               TRUE  1999-07-15 M
17390   NA                NA              FALSE  2000-03-15 M
17391   NA                NA               TRUE  2000-02-15 M
17392   NA                NA               TRUE  1999-07-15 F
      CombinedEthnicity cohort  DistCurrSch IDACIScore_Home LSOA11_Home EAL
1     White British     1999/00  2.45       0.04778         E01027555   0
2     White British     1998/99  4.71       0.35519         E01010703   0
3     South Asian       1998/99  0.33       0.37575         E01010742   0
4     White British     1999/00  1.78       0.07161         E01010641   0
5     White British     1999/00  0.76       0.44704         E01010655   0
6     South Asian       1999/00  1.29       0.41032         E01010626   0
7     South Asian       1998/99  1.37       0.06820         E01010568   0
8     White British     1998/99  4.27       0.13373         E01010752   0
9     White British     1998/99  0.10       0.03718         E01027577   0
10    Other             1998/99  2.74       0.56999         E01010625   1
11    White British     1998/99  0.47       0.26645         E01011330   0
12    South Asian       1999/00  1.13       0.57886         E01010710   1
13    Other             1999/00  1.23       0.53049         E01011792   0
14    White British     1998/99  0.61       0.03136         E01010579   0
15    South Asian       1998/99  0.61       0.47585         E01010663   1
16    White British     1998/99  6.72       0.03763         E01019350   0
17    White British     1998/99  1.05       0.12008         E01015222   0
18    Other             1998/99  0.35       0.13249         E01011541   0
19    South Asian       1999/00  0.68       0.35972         E01010738   0
20    White British     1998/99  1.48       0.05565         E01010764   0
21    White British     1998/99  0.53       0.37534         E01010734   0
22    White British     1998/99  4.99       0.10599         E01010795   0
23    South Asian       1999/00  2.06       0.35631         E01010793   1
24    White British     1999/00  1.29       0.08819         E01010706   0
25    White British     1999/00  1.25       0.05929         E01010790   0
26    White British     1999/00  3.18       0.30338         E01010967   0
27    White British     1999/00  0.62       0.33347         E01010802   0
28    South Asian       1999/00 12.70       0.00000         E01010772   0
29    South Asian       1998/99  1.91       0.37822         E01010613   1
30    White British     1998/99  0.77       0.01367         E01010580   0
⋮     ⋮                 ⋮       ⋮           ⋮               ⋮           ⋮
17363 South Asian       1998/99 2.33        0.35687         E01010665   1
17364 South Asian       1998/99 5.25        0.51416         E01016415   1
17365 White British     1998/99 0.54        0.13269         E01010603   0
17366 White British     1999/00 0.83        0.19848         E01010591   0
17367 South Asian       1999/00 0.62        0.17657         E01002609   1
17368 White British     1999/00 2.02        0.60213         E01011473   0
17369 White British     1998/99 2.47        0.09950         E01010750   0
17370 White British     1998/99 0.75        0.06837         E01010694   0
17371 White British     1998/99 3.13        0.09103         E01010816   0
17372 White British     1998/99 1.09        0.33826         E01010720   0
17373 South Asian       1998/99 1.03        0.31593         E01010835   0
17374 South Asian       1998/99 3.05        0.49557         E01010842   1
17375 Other             1998/99 1.99        0.37534         E01010734   1
17376 South Asian       1998/99 0.25        0.50226         E01010607   1
17377 South Asian       1998/99 0.37        0.42337         E01010719   0
17378 South Asian       1998/99 0.71        0.30280         E01015665   1
17379 White British     1999/00 2.62        0.08347         E01027560   0
17380 Other             1999/00 3.78        0.36170         E01010702   0
17381 Other             1998/99 0.39        0.33947         E01010731   0
17382 White British     1998/99 0.40        0.40603         E01010614   0
17383 White British     1999/00 1.20        0.23951         E01010827   0
17384 White British     1999/00 0.22        0.23702         E01022024   0
17385 White British     1998/99 4.40        0.08392         E01010754   0
17386 White British     1999/00 3.18        0.06716         E01010775   0
17387 White British     1998/99 7.77        0.15154         E01027834   0
17388 South Asian       1999/00 0.87        0.00000         E01010947   0
17389 White British     1998/99 1.27        0.02560         E01010758   0
17390 Other             1999/00 1.35        0.34551         E01026960   1
17391 White British     1999/00 0.35        0.06354         E01027585   0
17392 White British     1998/99 5.57        0.09103         E01010816   0
      ever_fsm
1     0
2     0
3     0
4     0
5     1
6     1
7     1
8     1
9     0
10    1
11    1
12    1
13    1
14    0
15    1
16    1
17    1
18    0
19    0
20    0
21    1
22    1
23    0
24    0
25    0
26    0
27    1
28    0
29    0
30    0
⋮     ⋮
17363 0
17364 0
17365 0
17366 0
17367 0
17368 1
17369 0
17370 0
17371 1
17372 1
17373 0
17374 1
17375 1
17376 1
17377 0
17378 0
17379 0
17380 0
17381 0
17382 0
17383 1
17384 1
17385 1
17386 1
17387 0
17388 1
17389 0
17390 1
17391 0
17392 0

In [110]:
# save as csv
write.csv(person_home_fsm_sen, "data/additional_person_home_fsm_sen.csv", row.names = FALSE)