In [1]:
library(tidyverse)
library(dbplyr)
library(bigrquery)
library(lubridate)

bq_auth()

project_id = "yhcr-prd-bradfor-bia-core"

# create connection to database
con <- DBI::dbConnect(bigrquery::bigquery(), 
                      project = project_id)

print(paste0("Connected to : ", project_id))

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘dbplyr’


The following objects are masked from ‘package:dplyr’:

    ident, sql

[1] "Connected to : yhcr-prd-bradfor-bia-core"

In [2]:
dest_data = "CB_2489.cb_NCCIS_2011_to_2019"

dest_table <- tbl(con, dest_data) |>
    select(person_id, NCCIS_ACADYR, NCCIS_MonthNo, NCCIS_Year_11_Intended_Destination, NCCIS_Current_Activity_Code, 
           NCCIS_Current_Activity_Start_Date, NCCIS_NEET_Start_Date, NCCIS_Lead_LEA_Code) |> 
    # convert to df
    collect()

In [3]:
head(dest_table)

  person_id                                                        NCCIS_ACADYR
1 749832F625AF33E7069CC7445D5E7C0C5210D8EF0BA4D3DB806ACF5EC905799E 2010/2011
2 EBE4BDB714011EC4573C41C3FC3EAFA79F91A10ECF37A79E1E4E304351B25630 2010/2011
3 63D417352B7A9B345D6B76757420122583FF334EBC2F2874E3EA62029A2A06CC 2010/2011
4 7324E1EF21451B1FE7732FEDB155B7CC0EE54052788F49D1027BF6B53A44FC91 2010/2011
5 9CE5E3220A4154A9BD65B3BB02E15C21FF6D240B47724845E4A8F2C3F8B5EE29 2010/2011
6 A7A2D6E75DC2B62F1282690150E032A671FAF9458BC14FBC4FC4C32FEF936B4B 2012/2013
  NCCIS_MonthNo NCCIS_Year_11_Intended_Destination NCCIS_Current_Activity_Code
1 12            NA                                 830
2  3            NA                                 820
3  2            NA                                 820
4  9            NA                                 820
5  4            130                                320
6  5            NA                                 810
  NCCIS_Current_Activity_Start_Date NCCIS_NEET_Start_Date NCCIS_Lead_LEA_Code
1 2007-08-30                        NA                    380
2 2008-08-06                        NA                    888
3 2008-02-19                        NA                    380
4 2008-05-13                        NA                    380
5 2008-09-01                        NA                    383
6 2008-09-15                        NA                    879

In [4]:
unique(dest_table$NCCIS_ACADYR)

[1] "2010/2011" "2012/2013" "2011/2012" "2014/2015" "2013/2014" "2015/2016"
[7] "2016/2017" "2017/2018" "2018/2019"

In [11]:
dest_15_19 <- dest_table |>
    filter(NCCIS_ACADYR %in% c('2015/2016','2016/2017','2017/2018','2018/2019'))

In [7]:
dest_data_17_21 = "CB_2489.cb_NCCIS_2017_to_2021"

dest_table_17_21 <- tbl(con, dest_data_17_21) |>
    select(person_id, NCCIS_ACADYR, NCCIS_MonthNo, NCCIS_Year_11_Intended_Destination, NCCIS_Current_Activity_Code, 
           NCCIS_Current_Activity_Start_Date, NCCIS_NEET_Start_Date, NCCIS_Lead_LEA_Code) |> 
    # convert to df
    collect()

In [8]:
head(dest_table_17_21)

  person_id                                                        NCCIS_ACADYR
1 NA                                                               2020/2021
2 D7CA98F8593422C2876539F75068B17F69CE4B2A5C777D3BDCE3D3D317A8F305 2016/2017
3 0EEC5BC24C4E35AF968D313FC831462BBAF3F7BCD36E8AA89AEF47EDA1AA9C0F 2016/2017
4 1F7B068D8DE8C9860DAFB315A6C4A1BD86F681F931B39B698119D54F2EA02FFC 2020/2021
5 9F254BBC32219DCDC43637188069FCDDD92A3BA521874552E471E9DAB9782DD9 2017/2018
6 4B9682E08E82FBA1AD74322CDD58A793244E5E19058B37044177BFD21D832FD9 2017/2018
  NCCIS_MonthNo NCCIS_Year_11_Intended_Destination NCCIS_Current_Activity_Code
1  4            NA                                 820
2  4            511                                820
3  6            NA                                 810
4  6            NA                                 810
5  9            NA                                 820
6 10            NA                                 820
  NCCIS_Current_Activity_Start_Date NCCIS_NEET_Start_Date NCCIS_Lead_LEA_Code
1 2014-02-20                        NA                    888
2 2014-11-11                        NA                    815
3 2015-01-14                        NA                    384
4 2015-01-15                        NA                    888
5 2015-02-23                        NA                    872
6 2015-06-01                        NA                    909

In [9]:
dest_table_17_21 <- dest_table_17_21 |>
    filter(!is.na(person_id))

In [10]:
unique(dest_table_17_21$NCCIS_ACADYR)

[1] "2016/2017" "2020/2021" "2017/2018" "2018/2019" "2019/2020"

In [12]:
dest_16_20 <- dest_table_17_21 |>
    filter(NCCIS_ACADYR %in% c('2016/2017','2017/2018','2018/2019','2019/2020'))

#### Bind dataframes, avoiding duplicates

In [13]:
destinations <- bind_rows(dest_15_19, dest_16_20) |> 
  distinct()

In [14]:
destinations |> 
  summarise(num_unique = n_distinct(person_id))

  num_unique
1 72639

## Filter destinations to target cohort

In [17]:
person_0002 <- read.csv("data/person_cohorts.csv", header = TRUE)

In [18]:
head(person_0002)

  person_id                                                        birth_date
1 D27CE553B8DA52E66BCBA43420F6F53DAEBF9FE2864361849339028B6B002695 2000-09-15
2 9F33F6D292805042AF92186788B71C7302C7E976F6C148C34FDE62B157C03928 2000-09-15
3 C38AD0B73560547A95C529E42A9CF6E1E06282163BB419DC2C1451422CD20CE0 2000-09-15
4 03A81FF3A58E65546A42780919E74680BF016F6D3E8FE1FA64FFD9B9E436B795 2000-09-15
5 8C9979BE485657CDE5AC92361D6E454DC61C1396BCC38F77933217649F802EFF 2000-09-15
6 00ED2E8CBC0AE48B370DBB70FB9440A00BD65113392DE33A5E14380D5C306075 2000-09-15
  gender CombinedEthnicity cohort
1 F      South Asian       2000/01
2 F      South Asian       2000/01
3 F      South Asian       2000/01
4 F      NA                2000/01
5 F      White British     2000/01
6 F      White British     2000/01

In [19]:
person_9800 = read.csv("data/additional_person_cohorts.csv", header = TRUE)

In [20]:
head(person_9800)

  person_id                                                        birth_date
1 EE91E3C77F2B7CB44F1F601317E2DE5EE76ABB0941F24D4714026B3E30FC313C 1998-09-15
2 C5553DE427E9B8F60E9B5D1E83391E1B660F415A3924B630742D52A0517F5219 1998-09-15
3 AC8CB4071E24E606BFFECC380A9EA11546158370916C4D8D954FA76D63FA81AE 1998-09-15
4 E4E84D0DEB6692712A8E875B701E097EB61235069C56626900C0951E9B112B6D 1998-09-15
5 64FA4602D88C275E27FDBD17EA4678E378D7B297D91C2CDB914150ED0CBF3785 1998-09-15
6 F516562D5CFDDC6CD66FB8EA18399D11BB0E2E042F569D918285FF96C3377338 1998-09-15
  gender CombinedEthnicity cohort
1 M      South Asian       1998/99
2 M      White British     1998/99
3 M      White British     1998/99
4 M      South Asian       1998/99
5 M      White British     1998/99
6 M      White British     1998/99

In [21]:
person <- bind_rows(person_9800, person_0002) |> 
  distinct()

In [22]:
person |> 
  summarise(num_unique = n_distinct(person_id))

  num_unique
1 45486

In [64]:
write.csv(person, "data/person_cohorts_max.csv", row.names = FALSE)

In [23]:
destinations_filtered <- destinations |>
    # filter destinations to target person ids
    semi_join(person, by = "person_id") |>
    # then left join dfs
    left_join(person |> select(person_id, cohort), by = "person_id")

In [24]:
NEET_activity <- destinations_filtered |>
    filter(NCCIS_Current_Activity_Code %in% c('540','610','615','616','619','620','630','640','650','660','670','680','710','810','820','830'))

# ,'710','810','820','830'

In [25]:
NEET_activity  |>
 group_by(cohort) |>
 tally()

  cohort  n
1 1998/99 25372
2 1999/00 25807
3 2000/01 25699
4 2001/02 26102

In [26]:
NEET_activity |> 
  group_by(cohort) |>
  summarise(num_unique = n_distinct(person_id))

  cohort  num_unique
1 1998/99 6544
2 1999/00 6337
3 2000/01 6401
4 2001/02 6344

## Tidy destinations and activity

In [27]:
destinations_clean <- destinations_filtered |>
    mutate(Intended_destination = 
        case_when(
            NCCIS_Year_11_Intended_Destination %in% c('111','121','211','311') ~ 'EET',
            NCCIS_Year_11_Intended_Destination %in% c('411','511') ~ 'NEET',
            TRUE ~ NA
            )
        )

In [28]:
destinations_clean |>
    group_by(Intended_destination) |>
    tally()

  Intended_destination n
1 EET                   61429
2 NEET                   1350
3 NA                   777808

In [29]:
destinations_clean <- destinations_clean |>
    mutate(Current_activity = 
           case_when(
               NCCIS_Current_Activity_Code %in% c('210','220','230','240','250','260','270','280','290') ~ 'Education',
               NCCIS_Current_Activity_Code %in% c('310','320','330','340','350','360','380','381','550') ~ 'Employment',
               NCCIS_Current_Activity_Code %in% c('410','430','440','450','460') ~ 'Training',
               NCCIS_Current_Activity_Code %in% c('530','540','610','615','616','619','620','630','640','650','660','670','680','710') ~ 'NEET',
               NCCIS_Current_Activity_Code %in% c('810','820') ~ NA,
               NCCIS_Current_Activity_Code == '830' ~ 'Refused',
               TRUE ~ NA
               )
           )

In [30]:
destinations_clean |>
    group_by(Current_activity) |>
    tally()

  Current_activity n
1 Education        639506
2 Employment        75156
3 NEET              27659
4 Refused            1220
5 Training          22483
6 NA                74563

In [31]:
destinations_clean <- destinations_clean |>
    mutate(NEET_detail = 
           case_when(
               NCCIS_Current_Activity_Code == '530' ~ 'Re-engagement',
               NCCIS_Current_Activity_Code == '540' ~ 'Working: no reward',
               NCCIS_Current_Activity_Code == '610' ~ 'Not ready',
               NCCIS_Current_Activity_Code == '615' ~ 'Start date agreed',
               NCCIS_Current_Activity_Code == '616' ~ 'Start date agreed',
               NCCIS_Current_Activity_Code == '619' ~ 'Seeking EET',
               NCCIS_Current_Activity_Code == '620' ~ 'Carer',
               NCCIS_Current_Activity_Code == '630' ~ 'Teen parent',
               NCCIS_Current_Activity_Code == '640' ~ 'Illness',
               NCCIS_Current_Activity_Code == '650' ~ 'Pregnancy',
               NCCIS_Current_Activity_Code == '660' ~ 'Religious grounds',
               NCCIS_Current_Activity_Code == '670' ~ 'Economically inactive',
               NCCIS_Current_Activity_Code == '680' ~ 'Other',
               NCCIS_Current_Activity_Code == '710' ~ 'Custody',
               TRUE ~ NA
               )
           )

In [32]:
destinations_clean |>
    group_by(NEET_detail) |>
    tally()

   NEET_detail           n
1  Carer                    401
2  Custody                  183
3  Economically inactive    210
4  Illness                 2668
5  Not ready               1610
6  Other                    860
7  Pregnancy               1004
8  Re-engagement            454
9  Religious grounds          7
10 Seeking EET            16531
11 Start date agreed       1316
12 Teen parent             2264
13 Working: no reward       151
14 NA                    812928

In [33]:
head(destinations_clean)

  person_id                                                        NCCIS_ACADYR
1 C9DBADB7031E637DF29DB08FF5ADAE4537683FD0299F314DAA1202D5E4EAA617 2015/2016
2 174CC1E6BD3BE665ABFDCAF441CC5AEC5464AD42C33E874A1ED4B1C1BDF6246E 2015/2016
3 0C554C9C2572686990D2418E0724CD5CCF9874B9CE92E0C251E7501C6504754D 2015/2016
4 12FB003A53BF00E70DD05011BED09201A9E1BF9A2A22492047448D5D5F459AA3 2015/2016
5 AF8AECA2B925A6C0C37C5B5A5421FA0E33421708126A0C567FA89DF0A2F8233B 2015/2016
6 3B525035E2F6C5D41CB726E87ECF35982E71C45C84CF974EA50E9A05AB9F048D 2015/2016
  NCCIS_MonthNo NCCIS_Year_11_Intended_Destination NCCIS_Current_Activity_Code
1  9            NA                                 310
2  3            NA                                 310
3 10            NA                                 310
4  9            NA                                 810
5  9            NA                                 810
6 11            NA                                 410
  NCCIS_Current_Activity_Start_Date NCCIS_NEET_Start_Date NCCIS_Lead_LEA_Code
1 2015-07-28                        NA                    382
2 2015-08-20                        NA                    380
3 2015-08-21                        NA                    353
4 2015-09-01                        NA                    938
5 2015-09-01                        NA                    211
6 2015-09-02                        NA                    380
  cohort  Intended_destination Current_activity NEET_detail
1 1998/99 NA                   Employment       NA
2 1998/99 NA                   Employment       NA
3 1998/99 NA                   Employment       NA
4 1998/99 NA                   NA               NA
5 1998/99 NA                   NA               NA
6 1998/99 NA                   Training         NA

In [34]:
destinations_clean <- destinations_clean |>
    select(-c(NCCIS_Year_11_Intended_Destination, NCCIS_Current_Activity_Code, NCCIS_Current_Activity_Start_Date, NCCIS_NEET_Start_Date, NCCIS_Lead_LEA_Code, cohort))

In [35]:
head(destinations_clean)

  person_id                                                        NCCIS_ACADYR
1 C9DBADB7031E637DF29DB08FF5ADAE4537683FD0299F314DAA1202D5E4EAA617 2015/2016
2 174CC1E6BD3BE665ABFDCAF441CC5AEC5464AD42C33E874A1ED4B1C1BDF6246E 2015/2016
3 0C554C9C2572686990D2418E0724CD5CCF9874B9CE92E0C251E7501C6504754D 2015/2016
4 12FB003A53BF00E70DD05011BED09201A9E1BF9A2A22492047448D5D5F459AA3 2015/2016
5 AF8AECA2B925A6C0C37C5B5A5421FA0E33421708126A0C567FA89DF0A2F8233B 2015/2016
6 3B525035E2F6C5D41CB726E87ECF35982E71C45C84CF974EA50E9A05AB9F048D 2015/2016
  NCCIS_MonthNo Intended_destination Current_activity NEET_detail
1  9            NA                   Employment       NA
2  3            NA                   Employment       NA
3 10            NA                   Employment       NA
4  9            NA                   NA               NA
5  9            NA                   NA               NA
6 11            NA                   Training         NA

## Destinations single record

In [39]:
destinations_clean |>
  group_by(person_id, NCCIS_ACADYR, NCCIS_MonthNo) |> 
  filter(n() > 1) |> 
  summarise(count = n(), .groups = "drop") |> 
  summarise(num_persons_with_duplicates = n_distinct(person_id))

  num_persons_with_duplicates
1 1179

In [40]:
destinations_clean <- destinations_clean |>
  arrange(person_id, NCCIS_ACADYR, NCCIS_MonthNo, Current_activity)

In [41]:
destinations_clean |>
  group_by(person_id, NCCIS_ACADYR, NCCIS_MonthNo) |> 
  filter(n() > 1)

      person_id
1     00A6CFE5C25E69EC51F67C74E4F40F8AECFE43014AD77CBCB2ADA9ECBBB96BA6
2     00A6CFE5C25E69EC51F67C74E4F40F8AECFE43014AD77CBCB2ADA9ECBBB96BA6
3     00A6CFE5C25E69EC51F67C74E4F40F8AECFE43014AD77CBCB2ADA9ECBBB96BA6
4     00A6CFE5C25E69EC51F67C74E4F40F8AECFE43014AD77CBCB2ADA9ECBBB96BA6
5     00A6CFE5C25E69EC51F67C74E4F40F8AECFE43014AD77CBCB2ADA9ECBBB96BA6
6     00A6CFE5C25E69EC51F67C74E4F40F8AECFE43014AD77CBCB2ADA9ECBBB96BA6
7     00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
8     00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
9     00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
10    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
11    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
12    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
13    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
14    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
15    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
16    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
17    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
18    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
19    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
20    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
21    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
22    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
23    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
24    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
25    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
26    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
27    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
28    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
29    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
30    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
⋮     ⋮
20977 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20978 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20979 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20980 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20981 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20982 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20983 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20984 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20985 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20986 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20987 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20988 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20989 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20990 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20991 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20992 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20993 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20994 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20995 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20996 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20997 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20998 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20999 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
21000 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
21001 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
21002 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
21003 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
21004 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
21005 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
21006 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
      NCCIS_ACADYR NCCIS_MonthNo Intended_destination Current_activity
1     2018/2019    10            EET                  Education
2     2018/2019    10            NA                   NA
3     2018/2019    11            EET                  Education
4     2018/2019    11            NA                   NA
5     2018/2019    12            NA                   Education
6     2018/2019    12            NA                   NA
7     2016/2017     1            NA                   Education
8     2016/2017     1            NA                   Education
9     2016/2017     2            NA                   Education
10    2016/2017     2            NA                   Education
11    2016/2017     3            NA                   Education
12    2016/2017     3            NA                   Education
13    2016/2017     4            NA                   Education
14    2016/2017     4            NA                   Education
15    2016/2017     5            NA                   Education
16    2016/2017     5            NA                   Education
17    2016/2017     6            NA                   Education
18    2016/2017     6            NA                   Education
19    2016/2017     7            NA                   Education
20    2016/2017     7            NA                   Education
21    2016/2017     8            NA                   Education
22    2016/2017     8            NA                   Education
23    2016/2017    10            NA                   Education
24    2016/2017    10            NA                   Education
25    2016/2017    11            NA                   Education
26    2016/2017    11            NA                   Education
27    2016/2017    12            NA                   Education
28    2016/2017    12            NA                   Education
29    2017/2018     1            NA                   Education
30    2017/2018     1            NA                   Education
⋮     ⋮            ⋮             ⋮                    ⋮
20977 2016/2017     6            NA                   Education
20978 2016/2017     6            NA                   Education
20979 2016/2017     7            NA                   Education
20980 2016/2017     7            NA                   Education
20981 2016/2017     8            NA                   Education
20982 2016/2017     8            NA                   Education
20983 2017/2018     1            NA                   Education
20984 2017/2018     1            NA                   Education
20985 2017/2018     2            NA                   Education
20986 2017/2018     2            NA                   Education
20987 2017/2018     3            NA                   Education
20988 2017/2018     3            NA                   Education
20989 2017/2018     4            NA                   Education
20990 2017/2018     4            NA                   Education
20991 2017/2018     5            NA                   Education
20992 2017/2018     5            NA                   Education
20993 2017/2018     6            NA                   Education
20994 2017/2018     6            NA                   Education
20995 2017/2018     7            NA                   Education
20996 2017/2018     7            NA                   Education
20997 2017/2018     8            NA                   Education
20998 2017/2018     8            NA                   Education
20999 2017/2018     9            NA                   Education
21000 2017/2018     9            NA                   Education
21001 2017/2018    10            NA                   Education
21002 2017/2018    10            NA                   Education
21003 2017/2018    11            NA                   Education
21004 2017/2018    11            NA                   Education
21005 2017/2018    12            NA                   Education
21006 2017/2018    12            NA                   Education
      NEET_detail
1     NA
2     NA
3     NA
4     NA
5     NA
6     NA
7     NA
8     NA
9     NA
10    NA
11    NA
12    NA
13    NA
14    NA
15    NA
16    NA
17    NA
18    NA
19    NA
20    NA
21    NA
22    NA
23    NA
24    NA
25    NA
26    NA
27    NA
28    NA
29    NA
30    NA
⋮     ⋮
20977 NA
20978 NA
20979 NA
20980 NA
20981 NA
20982 NA
20983 NA
20984 NA
20985 NA
20986 NA
20987 NA
20988 NA
20989 NA
20990 NA
20991 NA
20992 NA
20993 NA
20994 NA
20995 NA
20996 NA
20997 NA
20998 NA
20999 NA
21000 NA
21001 NA
21002 NA
21003 NA
21004 NA
21005 NA
21006 NA

#### split intended destinations and currect activity before removing 'not known' duplicates

In [42]:
dest_split <- destinations_clean |>
    select(-c(Current_activity, NEET_detail))

In [43]:
dest_split <- dest_split |>
  arrange(person_id, Intended_destination)

In [44]:
dest_split |>
  group_by(person_id) |> 
  filter(n() > 1)

       person_id
1      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
3      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
4      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
5      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
6      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
7      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
8      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
9      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
10     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
11     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
12     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
13     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
14     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
15     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
16     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
17     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
18     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
19     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
20     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
21     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
22     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
23     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
24     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
25     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
26     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
27     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
28     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
29     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
30     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
⋮      ⋮
840473 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
840474 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
840475 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
840476 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
840477 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
840478 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
840479 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
840480 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
840481 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
840482 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
840483 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
840484 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
840485 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
840486 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
840487 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
840488 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
840489 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
840490 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
840491 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
840492 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
840493 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
840494 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
840495 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
840496 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
840497 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
840498 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
840499 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
840500 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
840501 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
840502 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
       NCCIS_ACADYR NCCIS_MonthNo Intended_destination
1      2017/2018     1            NA
2      2017/2018     2            NA
3      2017/2018     3            NA
4      2017/2018     4            NA
5      2017/2018     5            NA
6      2017/2018     6            NA
7      2017/2018     7            NA
8      2017/2018     8            NA
9      2017/2018     9            NA
10     2017/2018    10            NA
11     2017/2018    11            NA
12     2017/2018    12            NA
13     2018/2019     1            NA
14     2018/2019     2            NA
15     2018/2019     3            NA
16     2018/2019     4            NA
17     2018/2019     5            NA
18     2018/2019     6            NA
19     2018/2019     7            NA
20     2018/2019     8            NA
21     2018/2019     9            NA
22     2018/2019    10            NA
23     2018/2019    11            NA
24     2018/2019    12            NA
25     2016/2017     1            EET
26     2016/2017     2            EET
27     2016/2017     3            EET
28     2016/2017     4            EET
29     2016/2017     5            EET
30     2016/2017     6            EET
⋮      ⋮            ⋮             ⋮
840473 2018/2019     7            NA
840474 2018/2019     8            NA
840475 2018/2019     9            NA
840476 2018/2019    10            NA
840477 2018/2019    11            NA
840478 2018/2019    12            NA
840479 2015/2016     1            NA
840480 2015/2016     2            NA
840481 2015/2016     3            NA
840482 2015/2016     4            NA
840483 2015/2016     5            NA
840484 2015/2016     6            NA
840485 2015/2016     7            NA
840486 2015/2016     8            NA
840487 2015/2016     9            NA
840488 2015/2016    10            NA
840489 2015/2016    11            NA
840490 2015/2016    12            NA
840491 2016/2017     1            NA
840492 2016/2017     2            NA
840493 2016/2017     3            NA
840494 2016/2017     4            NA
840495 2016/2017     5            NA
840496 2016/2017     6            NA
840497 2016/2017     7            NA
840498 2016/2017     8            NA
840499 2016/2017     9            NA
840500 2016/2017    10            NA
840501 2016/2017    11            NA
840502 2016/2017    12            NA

In [45]:
# order of priority: EET, NEET, NA
dest_split_clean <- dest_split |>
    group_by(person_id) |> 
    distinct(person_id, .keep_all = TRUE) |>
    select(c(person_id,Intended_destination))

In [46]:
dest_split_clean |>
    group_by(person_id) |> 
      filter(n() > 1) |> 
      summarise(count = n(), .groups = "drop") |> 
      summarise(num_persons_with_duplicates = n_distinct(person_id))

  num_persons_with_duplicates
1 0

In [47]:
head(dest_split_clean)

  person_id
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
3 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
4 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D
5 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
6 000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909
  Intended_destination
1 NA
2 EET
3 NA
4 NA
5 NA
6 NA

In [48]:
activ_split <- destinations_clean |>
    select(-Intended_destination)

In [49]:
# automatic order of priority: Edu, Emp, NEET, Refused, Train, NA
activ_split <- activ_split |>
    mutate(Current_activity = factor(Current_activity, levels = c("Education", "Employment", "Training", "NEET", "Refused", NA ))) |>
    arrange(person_id, NCCIS_ACADYR, NCCIS_MonthNo, Current_activity)

In [50]:
activ_split |>
  group_by(person_id, NCCIS_ACADYR, NCCIS_MonthNo) |> 
  filter(n() > 1)

      person_id
1     00A6CFE5C25E69EC51F67C74E4F40F8AECFE43014AD77CBCB2ADA9ECBBB96BA6
2     00A6CFE5C25E69EC51F67C74E4F40F8AECFE43014AD77CBCB2ADA9ECBBB96BA6
3     00A6CFE5C25E69EC51F67C74E4F40F8AECFE43014AD77CBCB2ADA9ECBBB96BA6
4     00A6CFE5C25E69EC51F67C74E4F40F8AECFE43014AD77CBCB2ADA9ECBBB96BA6
5     00A6CFE5C25E69EC51F67C74E4F40F8AECFE43014AD77CBCB2ADA9ECBBB96BA6
6     00A6CFE5C25E69EC51F67C74E4F40F8AECFE43014AD77CBCB2ADA9ECBBB96BA6
7     00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
8     00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
9     00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
10    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
11    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
12    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
13    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
14    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
15    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
16    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
17    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
18    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
19    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
20    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
21    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
22    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
23    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
24    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
25    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
26    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
27    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
28    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
29    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
30    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
⋮     ⋮
20977 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20978 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20979 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20980 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20981 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20982 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20983 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20984 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20985 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20986 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20987 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20988 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20989 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20990 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20991 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20992 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20993 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20994 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20995 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20996 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20997 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20998 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
20999 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
21000 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
21001 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
21002 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
21003 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
21004 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
21005 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
21006 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
      NCCIS_ACADYR NCCIS_MonthNo Current_activity NEET_detail
1     2018/2019    10            Education        NA
2     2018/2019    10            NA               NA
3     2018/2019    11            Education        NA
4     2018/2019    11            NA               NA
5     2018/2019    12            Education        NA
6     2018/2019    12            NA               NA
7     2016/2017     1            Education        NA
8     2016/2017     1            Education        NA
9     2016/2017     2            Education        NA
10    2016/2017     2            Education        NA
11    2016/2017     3            Education        NA
12    2016/2017     3            Education        NA
13    2016/2017     4            Education        NA
14    2016/2017     4            Education        NA
15    2016/2017     5            Education        NA
16    2016/2017     5            Education        NA
17    2016/2017     6            Education        NA
18    2016/2017     6            Education        NA
19    2016/2017     7            Education        NA
20    2016/2017     7            Education        NA
21    2016/2017     8            Education        NA
22    2016/2017     8            Education        NA
23    2016/2017    10            Education        NA
24    2016/2017    10            Education        NA
25    2016/2017    11            Education        NA
26    2016/2017    11            Education        NA
27    2016/2017    12            Education        NA
28    2016/2017    12            Education        NA
29    2017/2018     1            Education        NA
30    2017/2018     1            Education        NA
⋮     ⋮            ⋮             ⋮                ⋮
20977 2016/2017     6            Education        NA
20978 2016/2017     6            Education        NA
20979 2016/2017     7            Education        NA
20980 2016/2017     7            Education        NA
20981 2016/2017     8            Education        NA
20982 2016/2017     8            Education        NA
20983 2017/2018     1            Education        NA
20984 2017/2018     1            Education        NA
20985 2017/2018     2            Education        NA
20986 2017/2018     2            Education        NA
20987 2017/2018     3            Education        NA
20988 2017/2018     3            Education        NA
20989 2017/2018     4            Education        NA
20990 2017/2018     4            Education        NA
20991 2017/2018     5            Education        NA
20992 2017/2018     5            Education        NA
20993 2017/2018     6            Education        NA
20994 2017/2018     6            Education        NA
20995 2017/2018     7            Education        NA
20996 2017/2018     7            Education        NA
20997 2017/2018     8            Education        NA
20998 2017/2018     8            Education        NA
20999 2017/2018     9            Education        NA
21000 2017/2018     9            Education        NA
21001 2017/2018    10            Education        NA
21002 2017/2018    10            Education        NA
21003 2017/2018    11            Education        NA
21004 2017/2018    11            Education        NA
21005 2017/2018    12            Education        NA
21006 2017/2018    12            Education        NA

In [51]:
# manual order of priority
activ_split_clean <- activ_split |>
    group_by(person_id, NCCIS_ACADYR, NCCIS_MonthNo) |> 
    distinct(person_id, NCCIS_ACADYR, NCCIS_MonthNo, .keep_all = TRUE)

In [52]:
activ_split_clean |>
    group_by(person_id, NCCIS_ACADYR, NCCIS_MonthNo) |> 
      filter(n() > 1) |> 
      summarise(count = n(), .groups = "drop") |> 
      summarise(num_persons_with_duplicates = n_distinct(person_id))

  num_persons_with_duplicates
1 0

In [53]:
activ_split_clean

       person_id
1      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
3      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
4      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
5      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
6      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
7      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
8      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
9      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
10     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
11     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
12     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
13     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
14     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
15     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
16     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
17     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
18     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
19     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
20     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
21     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
22     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
23     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
24     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
25     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
26     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
27     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
28     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
29     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
30     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
⋮      ⋮
829983 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
829984 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
829985 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
829986 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
829987 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
829988 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
829989 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
829990 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
829991 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
829992 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
829993 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
829994 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
829995 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
829996 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
829997 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
829998 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
829999 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830000 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830001 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830002 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830003 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830004 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830005 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830006 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830007 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830008 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830009 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830010 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830011 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830012 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
       NCCIS_ACADYR NCCIS_MonthNo Current_activity NEET_detail
1      2017/2018     1            Education        NA
2      2017/2018     2            Education        NA
3      2017/2018     3            Education        NA
4      2017/2018     4            Education        NA
5      2017/2018     5            Education        NA
6      2017/2018     6            Education        NA
7      2017/2018     7            Education        NA
8      2017/2018     8            Education        NA
9      2017/2018     9            Education        NA
10     2017/2018    10            Education        NA
11     2017/2018    11            Education        NA
12     2017/2018    12            Education        NA
13     2018/2019     1            Employment       NA
14     2018/2019     2            Employment       NA
15     2018/2019     3            Employment       NA
16     2018/2019     4            Employment       NA
17     2018/2019     5            Employment       NA
18     2018/2019     6            Employment       NA
19     2018/2019     7            Employment       NA
20     2018/2019     8            Employment       NA
21     2018/2019     9            NA               NA
22     2018/2019    10            NA               NA
23     2018/2019    11            Employment       NA
24     2018/2019    12            Employment       NA
25     2016/2017     1            Education        NA
26     2016/2017     2            Education        NA
27     2016/2017     3            Education        NA
28     2016/2017     4            Education        NA
29     2016/2017     5            Education        NA
30     2016/2017     6            Education        NA
⋮      ⋮            ⋮             ⋮                ⋮
829983 2018/2019     7            Employment       NA
829984 2018/2019     8            Employment       NA
829985 2018/2019     9            Education        NA
829986 2018/2019    10            Employment       NA
829987 2018/2019    11            Employment       NA
829988 2018/2019    12            Employment       NA
829989 2015/2016     1            Education        NA
829990 2015/2016     2            Education        NA
829991 2015/2016     3            Education        NA
829992 2015/2016     4            Education        NA
829993 2015/2016     5            Education        NA
829994 2015/2016     6            Education        NA
829995 2015/2016     7            Education        NA
829996 2015/2016     8            NA               NA
829997 2015/2016     9            NA               NA
829998 2015/2016    10            Education        NA
829999 2015/2016    11            Education        NA
830000 2015/2016    12            Education        NA
830001 2016/2017     1            Education        NA
830002 2016/2017     2            Education        NA
830003 2016/2017     3            Education        NA
830004 2016/2017     4            Education        NA
830005 2016/2017     5            Education        NA
830006 2016/2017     6            Education        NA
830007 2016/2017     7            Education        NA
830008 2016/2017     8            NA               NA
830009 2016/2017     9            Education        NA
830010 2016/2017    10            Education        NA
830011 2016/2017    11            Education        NA
830012 2016/2017    12            Education        NA

#### Re-join and pivot wide

In [54]:
dest_joined <- activ_split_clean |>
    left_join(dest_split_clean, by = join_by(person_id)) |>
    select(c(person_id,NCCIS_ACADYR,Intended_destination,NCCIS_MonthNo,Current_activity,NEET_detail))

In [55]:
dest_joined |>
    group_by(person_id, NCCIS_ACADYR, NCCIS_MonthNo) |> 
      filter(n() > 1) |> 
      summarise(count = n(), .groups = "drop") |> 
      summarise(num_persons_with_duplicates = n_distinct(person_id))

  num_persons_with_duplicates
1 0

In [56]:
dest_joined |>
    group_by(person_id, NCCIS_ACADYR, NCCIS_MonthNo) |> 
      filter(n() > 1)

     person_id NCCIS_ACADYR Intended_destination NCCIS_MonthNo Current_activity
     NEET_detail

In [57]:
dest_joined

       person_id
1      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
3      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
4      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
5      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
6      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
7      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
8      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
9      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
10     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
11     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
12     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
13     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
14     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
15     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
16     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
17     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
18     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
19     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
20     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
21     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
22     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
23     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
24     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
25     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
26     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
27     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
28     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
29     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
30     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
⋮      ⋮
829983 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
829984 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
829985 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
829986 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
829987 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
829988 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
829989 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
829990 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
829991 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
829992 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
829993 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
829994 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
829995 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
829996 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
829997 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
829998 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
829999 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830000 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830001 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830002 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830003 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830004 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830005 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830006 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830007 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830008 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830009 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830010 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830011 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
830012 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
       NCCIS_ACADYR Intended_destination NCCIS_MonthNo Current_activity
1      2017/2018    NA                    1            Education
2      2017/2018    NA                    2            Education
3      2017/2018    NA                    3            Education
4      2017/2018    NA                    4            Education
5      2017/2018    NA                    5            Education
6      2017/2018    NA                    6            Education
7      2017/2018    NA                    7            Education
8      2017/2018    NA                    8            Education
9      2017/2018    NA                    9            Education
10     2017/2018    NA                   10            Education
11     2017/2018    NA                   11            Education
12     2017/2018    NA                   12            Education
13     2018/2019    NA                    1            Employment
14     2018/2019    NA                    2            Employment
15     2018/2019    NA                    3            Employment
16     2018/2019    NA                    4            Employment
17     2018/2019    NA                    5            Employment
18     2018/2019    NA                    6            Employment
19     2018/2019    NA                    7            Employment
20     2018/2019    NA                    8            Employment
21     2018/2019    NA                    9            NA
22     2018/2019    NA                   10            NA
23     2018/2019    NA                   11            Employment
24     2018/2019    NA                   12            Employment
25     2016/2017    EET                   1            Education
26     2016/2017    EET                   2            Education
27     2016/2017    EET                   3            Education
28     2016/2017    EET                   4            Education
29     2016/2017    EET                   5            Education
30     2016/2017    EET                   6            Education
⋮      ⋮            ⋮                    ⋮             ⋮
829983 2018/2019    NA                    7            Employment
829984 2018/2019    NA                    8            Employment
829985 2018/2019    NA                    9            Education
829986 2018/2019    NA                   10            Employment
829987 2018/2019    NA                   11            Employment
829988 2018/2019    NA                   12            Employment
829989 2015/2016    NA                    1            Education
829990 2015/2016    NA                    2            Education
829991 2015/2016    NA                    3            Education
829992 2015/2016    NA                    4            Education
829993 2015/2016    NA                    5            Education
829994 2015/2016    NA                    6            Education
829995 2015/2016    NA                    7            Education
829996 2015/2016    NA                    8            NA
829997 2015/2016    NA                    9            NA
829998 2015/2016    NA                   10            Education
829999 2015/2016    NA                   11            Education
830000 2015/2016    NA                   12            Education
830001 2016/2017    NA                    1            Education
830002 2016/2017    NA                    2            Education
830003 2016/2017    NA                    3            Education
830004 2016/2017    NA                    4            Education
830005 2016/2017    NA                    5            Education
830006 2016/2017    NA                    6            Education
830007 2016/2017    NA                    7            Education
830008 2016/2017    NA                    8            NA
830009 2016/2017    NA                    9            Education
830010 2016/2017    NA                   10            Education
830011 2016/2017    NA                   11            Education
830012 2016/2017    NA                   12            Education
       NEET_detail
1      NA
2      NA
3      NA
4      NA
5      NA
6      NA
7      NA
8      NA
9      NA
10     NA
11     NA
12     NA
13     NA
14     NA
15     NA
16     NA
17     NA
18     NA
19     NA
20     NA
21     NA
22     NA
23     NA
24     NA
25     NA
26     NA
27     NA
28     NA
29     NA
30     NA
⋮      ⋮
829983 NA
829984 NA
829985 NA
829986 NA
829987 NA
829988 NA
829989 NA
829990 NA
829991 NA
829992 NA
829993 NA
829994 NA
829995 NA
829996 NA
829997 NA
829998 NA
829999 NA
830000 NA
830001 NA
830002 NA
830003 NA
830004 NA
830005 NA
830006 NA
830007 NA
830008 NA
830009 NA
830010 NA
830011 NA
830012 NA

In [58]:
dest_joined |>
    group_by(Current_activity) |>
    tally()

  Current_activity n
1 Education        634596
2 Employment        74012
3 Training          22271
4 NEET              26884
5 Refused            1155
6 NA                71094

In [59]:
destinations_wide <- dest_joined |>
    select(-(NEET_detail)) |>
    pivot_wider(
        names_from = NCCIS_MonthNo,
        values_from = Current_activity,
        values_fill = NA
        ) |>
    select(c(person_id,NCCIS_ACADYR,Intended_destination,'9','10','11','12','1','2','3','4','5','6','7','8'))

In [60]:
# Save as CSV

In [61]:
write.csv(destinations_wide, "data/destinations_wide_max.csv", row.names = FALSE)

In [62]:
dest_joined_detail <- dest_joined |>
    mutate(Current_activity = case_when(
        Current_activity == "NEET" & !is.na(NEET_detail) ~ paste0("NEET: ", NEET_detail),
        TRUE ~ Current_activity
  ))

In [91]:
destinations_wide_detail <- dest_joined_detail |>
    select(-(NEET_detail)) |>
    mutate(year_month = paste(NCCIS_ACADYR, NCCIS_MonthNo, sep = ': '))|>
    ungroup() |> 
    select(-c(NCCIS_ACADYR, NCCIS_MonthNo))

In [93]:
head(destinations_wide_detail)

  person_id
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
3 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
4 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
5 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
6 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
  Intended_destination Current_activity year_month
1 NA                   Education        2017/2018: 1
2 NA                   Education        2017/2018: 2
3 NA                   Education        2017/2018: 3
4 NA                   Education        2017/2018: 4
5 NA                   Education        2017/2018: 5
6 NA                   Education        2017/2018: 6

In [94]:
destinations_wide_detail <- destinations_wide_detail |>
    pivot_wider(
        names_from = year_month,
        values_from = Current_activity,
        values_fill = NA
        )
    #select(c(person_id,NCCIS_ACADYR,Intended_destination,'9','10','11','12','1','2','3','4','5','6','7','8'))

In [95]:
destinations_wide_detail

      person_id
1     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
3     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
4     0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D
5     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
6     000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909
7     0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7
8     00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC
9     00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66
10    0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D
11    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
12    00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7
13    0018E26A40A6299391164D4918658B0B1248367C762DCE6D2FDF1AE131A9138C
14    0019031CD62586D59268772800516ED50CDF1EF7DE46488542BB031850F6E68A
15    001B7CEB7B4CC529920A0B9F5B83D1AC0019E5DC44B3FBB3CEF665C331C0C3B6
16    001E539C263734CC355646811C93CF85B0C587D2EBA8B0D79290FDE8A75D6267
17    001E5C1FFA964716BF5E84562BC0B5D64F7742B1E8126718A5C0157D485F215D
18    001F42538A9E6E496F13CD05B5E9FE91EB3B20F0CEBECA1B76CC5E7151B7A0D4
19    001F566795F57F5D8DD92430D868A38B757699844E3E09569B33253527012932
20    001FFD3AA96B7E4FC5BB9A2F7502CD45BFCC35882335F1C34F78DD9AE5667225
21    00211975518FD5336E43850D59B5F5DDA7CD98B212760111CB40528BDECF3B1B
22    00222373A6082CDBF94DA04F23E7EB4C8775BEE122FE9C29FBF521900A498EDF
23    00237E9C21696BB29409630166F2D9CCEC24B83FB120AEDD878DDD54C6516B3D
24    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9
25    0025102C0D8E8C5F27454E3715E982A43E1431991E85562E55BCB19D9D1BD7D3
26    0025514088C52FB45B7439689844A1FEA2FB8B2753994F432CC7DDC68036BD59
27    00269FAEA8B5167F1239AA166C20B7673380CCB3E5F3E2F1F6FAA6034A11CE88
28    0026BFA5D5426F421200AB505AAD52956621DCC253241A6647302BCE4764547D
29    002AB68E0EC9459837DD6159160BF8C592504B5F0EE3160A22051398D20C3FFC
30    002D3DB2625339C740EB129CCC925A9D90E4F5AA05561B81FE166EDF990B8F65
⋮     ⋮
35653 FFC53382EFC80944BF643197EFC665798C754FA8E41038787A7E7B316B99A75B
35654 FFC7129859DD885141E316248A0EB23059DB0F0DB98242C34C67F06FBBAB8041
35655 FFC96F346EC6829E7A31F60109FD729DE208D180104B50FC8B1BFAD552D6C8FC
35656 FFD30596592DA2C82B86241FBA35E56C7384E7EF8219DB076458B4F9ACDED786
35657 FFD391941F3AA9CB910FFFACF24CC2CEAD0BC63EED146E9C21B2C71BA77B084A
35658 FFD5BA3FE061A462810CE5612E0D8F23A80A5C345BA1A4FB19FF145FA7BC37D3
35659 FFD8D921E0BB4710DE68BAE031E6C1A78203B96770F1FDE2CA983B7EEE34EF7B
35660 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951
35661 FFDE0350353E1B484F83298958E0F735D428D6B50E78471B87509497F4406002
35662 FFE133B080FD044D5E6FDC0E74D7303B3D41419692A96B3E116D180FE9EB2F06
35663 FFE1AA7D705C959745A85B91C6D3F3D22A57B8E50092E9EC25046F6986F77D96
35664 FFE244494ADA5394035640D578E70F7D57EBA5F67793F328CEF11B0B124491E2
35665 FFE326BEEDD9B7453AA81BB7251D3F724AB1351CD2D45090955FC0B1EC4377EF
35666 FFE326E526FAA00EF542D85A2BEBF681FB29C82A21EDA118DCD93D32035A203B
35667 FFE837A538A9166CC4089E844F651277391B496479F4691CE27BF1000C49223B
35668 FFE8D30492571D5641B63115FFED00DE60D39E160D78483EC4E2BCE0A442F884
35669 FFEA068077E4464D059236951F07D7DF96542C2197AAFAC3E20C036BACB9825C
35670 FFEBA230449490BA4B1BCEB1A68C790B1D85708DE8C6EAB8CD170D3E52F12775
35671 FFEBA2A7088A41ADEF06DE231C6F48B615D19A0CA2D2FC917F432A964C9B2EA3
35672 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
35673 FFEF2AA9E8BD72D6A0E7CE50F067E4247E12738F53AE726CD94A4D9CB588C702
35674 FFEF385FC541F397C34ACF193D6936D6BB045655B8781D7CFF18D632AAE9ED10
35675 FFEFD5577D0112E9304118DB7851CF61BEE4DD3D3184EEA756C076317925508F
35676 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB
35677 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
35678 FFFA6705A275195BFE8A443AF0BD2AA86B1AA0481D330D8665813206EB8DAD43
35679 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77
35680 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
35681 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
35682 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
      Intended_destination 2017/2018: 1      2017/2018: 2      2017/2018: 3
1     NA                   Education         Education         Education
2     EET                  Education         Education         Education
3     NA                   Education         Education         Education
4     NA                   NA                NA                NA
5     NA                   NA                NA                NA
6     NA                   NA                NA                NA
7     NA                   NA                NA                NA
8     NA                   Education         Education         Education
9     NA                   Education         Education         Education
10    NA                   Education         Education         Education
11    NA                   Education         NEET: Seeking EET Training
12    NA                   Education         Education         Education
13    NA                   NA                NA                NA
14    NA                   NA                NA                NA
15    NA                   Education         Education         Education
16    NA                   Education         Education         Education
17    NA                   NA                NA                NA
18    NA                   NA                NA                NA
19    NA                   NA                NA                NA
20    NA                   NA                NA                NA
21    NA                   NA                NA                NA
22    NA                   Education         Education         Education
23    EET                  NA                NA                NA
24    NA                   NA                NA                NA
25    NA                   NA                NA                NA
26    NA                   Training          Training          Training
27    NA                   Education         Education         Education
28    NA                   NA                NA                NA
29    NA                   NA                NA                NA
30    NA                   NA                NA                NA
⋮     ⋮                    ⋮                 ⋮                 ⋮
35653 EET                  Education         Education         Education
35654 NA                   NA                NA                NA
35655 NA                   NA                NA                NA
35656 NA                   Training          Training          Training
35657 NA                   NA                NA                NA
35658 NA                   NA                NA                NA
35659 NA                   Education         Education         Education
35660 EET                  Education         Education         Education
35661 NA                   Education         Education         Education
35662 NA                   NA                NA                NA
35663 NA                   NEET: Seeking EET Training          Training
35664 NA                   NA                NA                NA
35665 NA                   Education         Education         Employment
35666 EET                  Education         Education         Education
35667 EET                  Employment        Employment        Employment
35668 NA                   NA                NA                NA
35669 NA                   NA                NA                NA
35670 NA                   Education         Education         Education
35671 EET                  NA                NA                NA
35672 NA                   Education         Education         Education
35673 NA                   Education         Education         Education
35674 NA                   NA                NA                NA
35675 NA                   Education         Education         Education
35676 NA                   NA                NA                NA
35677 EET                  Education         Education         Education
35678 NA                   NA                NA                NA
35679 NA                   NA                NA                NA
35680 NA                   NA                NA                NA
35681 NA                   Education         Education         Education
35682 NA                   NA                NA                NA
      2017/2018: 4 2017/2018: 5 2017/2018: 6 2017/2018: 7 2017/2018: 8      ⋯
1     Education    Education    Education    Education    Education         ⋯
2     Education    Education    Education    Education    Education         ⋯
3     Education    Education    Education    Education    Education         ⋯
4     NA           NA           NA           NA           NA                ⋯
5     NA           NA           NA           NA           NA                ⋯
6     NA           NA           NA           NA           NA                ⋯
7     NA           NA           NA           NA           NA                ⋯
8     Education    Education    Education    Education    Education         ⋯
9     Education    Education    Education    Education    NA                ⋯
10    Education    Education    Education    Education    Education         ⋯
11    Training     Training     NA           NA           Employment        ⋯
12    Education    Education    Education    Education    Education         ⋯
13    NA           NA           NA           NA           NA                ⋯
14    NA           NA           NA           NA           NA                ⋯
15    Education    Education    Education    Education    NA                ⋯
16    Education    Education    Education    Education    Education         ⋯
17    NA           NA           NA           NA           NA                ⋯
18    NA           NA           NA           NA           NA                ⋯
19    NA           NA           NA           NA           NA                ⋯
20    NA           NA           NA           NA           NA                ⋯
21    NA           NA           NA           NA           NA                ⋯
22    Education    Education    Education    Education    Education         ⋯
23    NA           NA           NA           NA           NA                ⋯
24    NA           NA           NA           NA           NA                ⋯
25    NA           NA           NA           NA           NA                ⋯
26    Training     Training     Training     Training     Training          ⋯
27    Education    Education    Education    Education    Education         ⋯
28    NA           NA           NA           NA           NA                ⋯
29    NA           NA           NA           NA           NA                ⋯
30    NA           NA           NA           NA           NA                ⋯
⋮     ⋮            ⋮            ⋮            ⋮            ⋮                 ⋱
35653 Education    Education    Education    Education    Education         ⋯
35654 NA           NA           NA           NA           NA                ⋯
35655 NA           NA           NA           NA           NA                ⋯
35656 Training     Training     Training     Training     NEET: Seeking EET ⋯
35657 NA           NA           NA           NA           NA                ⋯
35658 NA           NA           NA           NA           NA                ⋯
35659 Education    Education    Education    Education    Education         ⋯
35660 Education    Education    Education    Education    Education         ⋯
35661 Education    Education    Education    Education    Education         ⋯
35662 NA           NA           NA           NA           NA                ⋯
35663 Training     Training     NA           NA           NA                ⋯
35664 NA           NA           NA           NA           NA                ⋯
35665 Employment   Employment   Employment   Employment   Employment        ⋯
35666 Education    Education    Education    Education    Education         ⋯
35667 Employment   Employment   Employment   Employment   Employment        ⋯
35668 NA           NA           NA           NA           NA                ⋯
35669 NA           NA           NA           NA           NA                ⋯
35670 Education    Education    Education    Education    Education         ⋯
35671 NA           NA           NA           NA           NA                ⋯
35672 Education    Education    Education    Education    Education         ⋯
35673 Education    Education    Education    Education    NA                ⋯
35674 NA           NA           NA           NA           NA                ⋯
35675 Education    Education    Education    Education    Education         ⋯
35676 NA           NA           NA           NA           NA                ⋯
35677 Education    Education    Education    Education    Education         ⋯
35678 NA           NA           NA           NA           NA                ⋯
35679 NA           NA           NA           NA           NA                ⋯
35680 NA           NA           NA           NA           NA                ⋯
35681 Education    Education    Education    Education    Education         ⋯
35682 NA           NA           NA           NA           NA                ⋯
      2015/2016: 5      2015/2016: 6      2015/2016: 7      2015/2016: 8
1     NA                NA                NA                NA
2     NA                NA                NA                NA
3     NA                NA                NA                NA
4     NA                NA                NA                NA
5     Employment        Employment        Employment        Employment
6     Education         Education         NA                NA
7     NA                NA                NA                NA
8     NA                NA                NA                NA
9     NA                NA                NA                NA
10    NA                NA                NA                NA
11    NA                NA                NA                NA
12    NA                NA                NA                NA
13    NA                NA                NA                NA
14    NA                NA                NA                NA
15    NA                NA                NA                NA
16    NA                NA                NA                NA
17    NA                NA                NA                NA
18    NA                Education         NA                NA
19    NA                NA                NA                NA
20    NA                NA                NA                NA
21    Employment        Employment        Employment        Employment
22    NA                NA                NA                NA
23    NA                NA                Education         Education
24    NEET: Seeking EET NEET: Seeking EET NEET: Seeking EET NEET: Seeking EET
25    Education         Education         Education         Education
26    NA                NA                NA                NA
27    NA                NA                NA                NA
28    Education         Education         Education         Education
29    NA                NA                NA                NA
30    Education         Education         Education         NA
⋮     ⋮                 ⋮                 ⋮                 ⋮
35653 NA                NA                NA                NA
35654 NA                NA                NA                NA
35655 NA                NA                NA                NA
35656 NA                NA                NA                NA
35657 NA                NA                NA                NA
35658 NA                NA                NA                NA
35659 NA                NA                NA                NA
35660 NA                NA                NA                NA
35661 NA                NA                NA                NA
35662 Education         Education         NA                NA
35663 NA                NA                NA                NA
35664 Education         Education         Education         NA
35665 NA                NA                NA                NA
35666 NA                NA                NA                NA
35667 NA                NA                NA                NA
35668 Education         Education         Education         Education
35669 NA                NA                NA                NA
35670 NA                NA                NA                NA
35671 Education         Education         Education         NA
35672 NA                NA                NA                NA
35673 NA                NA                NA                NA
35674 NA                NA                Education         NA
35675 NA                NA                NA                NA
35676 NA                NA                NA                NA
35677 NA                NA                NA                NA
35678 NA                NA                NA                NA
35679 NA                NA                NA                NA
35680 NA                NA                NA                NA
35681 NA                NA                NA                NA
35682 Education         Education         Education         NA
      2015/2016: 9 2015/2016: 10 2015/2016: 11     2015/2016: 12
1     NA           NA            NA                NA
2     NA           NA            NA                NA
3     NA           NA            NA                NA
4     NA           NA            NA                NA
5     Education    Education     Education         NA
6     NA           Education     Education         Education
7     NA           NA            NA                NA
8     NA           NA            NA                NA
9     NA           NA            NA                NA
10    NA           NA            NA                NA
11    NA           NA            NA                NA
12    NA           NA            NA                NA
13    NA           NA            NA                NA
14    NA           NA            NA                NA
15    NA           NA            NA                NA
16    NA           NA            NA                NA
17    NA           NA            NA                NA
18    NA           Education     NA                NA
19    NA           NA            NA                NA
20    NA           NA            NA                NA
21    NA           Employment    Employment        Employment
22    NA           NA            NA                NA
23    NA           NA            NA                NA
24    Education    Education     NEET: Seeking EET NEET: Seeking EET
25    Education    Education     Education         Education
26    NA           NA            NA                NA
27    NA           NA            NA                NA
28    NA           Education     Education         Education
29    NA           NA            NA                NA
30    NA           Education     Education         Education
⋮     ⋮            ⋮             ⋮                 ⋮
35653 NA           NA            NA                NA
35654 NA           NA            NA                NA
35655 NA           NA            NA                NA
35656 NA           NA            NA                NA
35657 NA           NA            NA                NA
35658 NA           NA            NA                NA
35659 NA           NA            NA                NA
35660 NA           NA            NA                NA
35661 NA           NA            NA                NA
35662 NA           NA            Education         Education
35663 NA           NA            NA                NA
35664 Education    Education     Education         Education
35665 NA           NA            NA                NA
35666 NA           NA            NA                NA

In [96]:
colnames(destinations_wide_detail)

 [1] "person_id"            "Intended_destination" "2017/2018: 1"
 [4] "2017/2018: 2"         "2017/2018: 3"         "2017/2018: 4"
 [7] "2017/2018: 5"         "2017/2018: 6"         "2017/2018: 7"
[10] "2017/2018: 8"         "2017/2018: 9"         "2017/2018: 10"
[13] "2017/2018: 11"        "2017/2018: 12"        "2018/2019: 1"
[16] "2018/2019: 2"         "2018/2019: 3"         "2018/2019: 4"
[19] "2018/2019: 5"         "2018/2019: 6"         "2018/2019: 7"
[22] "2018/2019: 8"         "2018/2019: 9"         "2018/2019: 10"
[25] "2018/2019: 11"        "2018/2019: 12"        "2016/2017: 1"
[28] "2016/2017: 2"         "2016/2017: 3"         "2016/2017: 4"
[31] "2016/2017: 5"         "2016/2017: 6"         "2016/2017: 7"
[34] "2016/2017: 8"         "2016/2017: 9"         "2016/2017: 10"
[37] "2016/2017: 11"        "2016/2017: 12"        "2019/2020: 1"
[40] "2019/2020: 2"         "2019/2020: 3"         "2019/2020: 4"
[43] "2019/2020: 5"         "2019/2020: 6"         "2019/2020: 7"
[46] "2019/2020: 8"         "2019/2020: 9"         "2019/2020: 10"
[49] "2019/2020: 11"        "2019/2020: 12"        "2015/2016: 2"
[52] "2015/2016: 3"         "2015/2016: 5"         "2015/2016: 6"
[55] "2015/2016: 7"         "2015/2016: 8"         "2015/2016: 9"
[58] "2015/2016: 10"        "2015/2016: 11"        "2015/2016: 12"
[61] "2015/2016: 1"         "2015/2016: 4"

In [112]:
destinations_wide_detail_final <- destinations_wide_detail |>
    select('person_id',
            'Intended_destination',

            '2015/2016: 9',
            '2015/2016: 10',
            '2015/2016: 11',
            '2015/2016: 12',
            '2015/2016: 1',
            '2015/2016: 2',
            '2015/2016: 3',
            '2015/2016: 4',
            '2015/2016: 5',
            '2015/2016: 6',
            '2015/2016: 7',
            '2015/2016: 8',

            '2016/2017: 9',
            '2016/2017: 10',
            '2016/2017: 11',
            '2016/2017: 12',
            '2016/2017: 1',
            '2016/2017: 2',
            '2016/2017: 3',
            '2016/2017: 4',
            '2016/2017: 5',
            '2016/2017: 6',
            '2016/2017: 7',
            '2016/2017: 8',

            '2017/2018: 9',
            '2017/2018: 10',
            '2017/2018: 11',
            '2017/2018: 12',
            '2017/2018: 1',
            '2017/2018: 2',
            '2017/2018: 3',
            '2017/2018: 4',
            '2017/2018: 5',
            '2017/2018: 6',
            '2017/2018: 7',
            '2017/2018: 8',

            '2018/2019: 9',
            '2018/2019: 10',
            '2018/2019: 11',
            '2018/2019: 12',
            '2018/2019: 1',
            '2018/2019: 2',
            '2018/2019: 3',
            '2018/2019: 4',
            '2018/2019: 5',
            '2018/2019: 6',
            '2018/2019: 7',
            '2018/2019: 8',

            '2019/2020: 9',
            '2019/2020: 10',
            '2019/2020: 11',
            '2019/2020: 12',
            '2019/2020: 1',
            '2019/2020: 2',
            '2019/2020: 3',
            '2019/2020: 4',
            '2019/2020: 5',
            '2019/2020: 6',
            '2019/2020: 7',
            '2019/2020: 8')

In [113]:
head(destinations_wide_detail_final)

  person_id
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
3 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
4 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D
5 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
6 000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909
  Intended_destination 2015/2016: 9 2015/2016: 10 2015/2016: 11 2015/2016: 12
1 NA                   NA           NA            NA            NA
2 EET                  NA           NA            NA            NA
3 NA                   NA           NA            NA            NA
4 NA                   NA           NA            NA            NA
5 NA                   Education    Education     Education     NA
6 NA                   NA           Education     Education     Education
  2015/2016: 1 2015/2016: 2 2015/2016: 3 2015/2016: 4 ⋯ 2019/2020: 11
1 NA           NA           NA           NA           ⋯ NA
2 NA           NA           NA           NA           ⋯ NA
3 NA           NA           NA           NA           ⋯ NA
4 NA           NA           NA           NA           ⋯ NEET: Seeking EET
5 NA           Employment   Employment   NA           ⋯ NA
6 NA           Education    Education    NA           ⋯ NA
  2019/2020: 12     2019/2020: 1      2019/2020: 2      2019/2020: 3
1 NA                NA                NA                NA
2 NA                NA                NA                NA
3 NA                NA                NA                NA
4 NEET: Seeking EET NEET: Seeking EET NEET: Seeking EET NEET: Seeking EET
5 NA                NA                NA                NA
6 NA                NA                NA                NA
  2019/2020: 4      2019/2020: 5      2019/2020: 6      2019/2020: 7
1 NA                NA                NA                NA
2 NA                NA                NA                NA
3 NA                NA                NA                NA
4 NEET: Seeking EET NEET: Seeking EET NEET: Seeking EET NEET: Seeking EET
5 NA                NA                NA                NA
6 NA                NA                NA                NA
  2019/2020: 8
1 NA
2 NA
3 NA
4 NEET: Seeking EET
5 NA
6 NA

#### save destinations with NEET detail as csv

In [99]:
write.csv(destinations_wide_detail_final, "data/destinations_wide_detail_max.csv", row.names = FALSE)

#### Align destination activity 2 years

In [101]:
person_cohorts <- person |>
    select(c(person_id, cohort))

In [103]:
head(person_cohorts)

  person_id                                                        cohort
1 EE91E3C77F2B7CB44F1F601317E2DE5EE76ABB0941F24D4714026B3E30FC313C 1998/99
2 C5553DE427E9B8F60E9B5D1E83391E1B660F415A3924B630742D52A0517F5219 1998/99
3 AC8CB4071E24E606BFFECC380A9EA11546158370916C4D8D954FA76D63FA81AE 1998/99
4 E4E84D0DEB6692712A8E875B701E097EB61235069C56626900C0951E9B112B6D 1998/99
5 64FA4602D88C275E27FDBD17EA4678E378D7B297D91C2CDB914150ED0CBF3785 1998/99
6 F516562D5CFDDC6CD66FB8EA18399D11BB0E2E042F569D918285FF96C3377338 1998/99

In [114]:
destinations_cohorts <- destinations_wide_detail_final |>
    left_join(person_cohorts , by = "person_id")

In [115]:
head(destinations_cohorts)

  person_id
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
3 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
4 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D
5 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
6 000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909
  Intended_destination 2015/2016: 9 2015/2016: 10 2015/2016: 11 2015/2016: 12
1 NA                   NA           NA            NA            NA
2 EET                  NA           NA            NA            NA
3 NA                   NA           NA            NA            NA
4 NA                   NA           NA            NA            NA
5 NA                   Education    Education     Education     NA
6 NA                   NA           Education     Education     Education
  2015/2016: 1 2015/2016: 2 2015/2016: 3 2015/2016: 4 ⋯ 2019/2020: 12
1 NA           NA           NA           NA           ⋯ NA
2 NA           NA           NA           NA           ⋯ NA
3 NA           NA           NA           NA           ⋯ NA
4 NA           NA           NA           NA           ⋯ NEET: Seeking EET
5 NA           Employment   Employment   NA           ⋯ NA
6 NA           Education    Education    NA           ⋯ NA
  2019/2020: 1      2019/2020: 2      2019/2020: 3      2019/2020: 4
1 NA                NA                NA                NA
2 NA                NA                NA                NA
3 NA                NA                NA                NA
4 NEET: Seeking EET NEET: Seeking EET NEET: Seeking EET NEET: Seeking EET
5 NA                NA                NA                NA
6 NA                NA                NA                NA
  2019/2020: 5      2019/2020: 6      2019/2020: 7      2019/2020: 8
1 NA                NA                NA                NA
2 NA                NA                NA                NA
3 NA                NA                NA                NA
4 NEET: Seeking EET NEET: Seeking EET NEET: Seeking EET NEET: Seeking EET
5 NA                NA                NA                NA
6 NA                NA                NA                NA
  cohort
1 2000/01
2 1999/00
3 2000/01
4 2001/02
5 1998/99
6 1998/99

In [116]:
destinations_cohort_9899 <- destinations_cohorts |>
    filter(cohort == '1998/99')

In [117]:
destinations_cohort_9900 <- destinations_cohorts |>
    filter(cohort == '1999/00')

In [118]:
destinations_cohort_0001 <- destinations_cohorts |>
    filter(cohort == '2000/01')

In [119]:
destinations_cohort_0102 <- destinations_cohorts |>
    filter(cohort == '2001/02')

In [129]:
destinations_cohort_9899_2years <- destinations_cohort_9899 |>
    select('cohort',
            'person_id',
            'Intended_destination',

            '2015/2016: 9',
            '2015/2016: 10',
            '2015/2016: 11',
            '2015/2016: 12',
            '2015/2016: 1',
            '2015/2016: 2',
            '2015/2016: 3',
            '2015/2016: 4',
            '2015/2016: 5',
            '2015/2016: 6',
            '2015/2016: 7',
            '2015/2016: 8',

            '2016/2017: 9',
            '2016/2017: 10',
            '2016/2017: 11',
            '2016/2017: 12',
            '2016/2017: 1',
            '2016/2017: 2',
            '2016/2017: 3',
            '2016/2017: 4',
            '2016/2017: 5',
            '2016/2017: 6',
            '2016/2017: 7',
            '2016/2017: 8')

In [130]:
destinations_cohort_9900_2years <- destinations_cohort_9900 |>
    select('cohort',
            'person_id',
            'Intended_destination',

            '2016/2017: 9',
            '2016/2017: 10',
            '2016/2017: 11',
            '2016/2017: 12',
            '2016/2017: 1',
            '2016/2017: 2',
            '2016/2017: 3',
            '2016/2017: 4',
            '2016/2017: 5',
            '2016/2017: 6',
            '2016/2017: 7',
            '2016/2017: 8',
           
           '2017/2018: 9',
            '2017/2018: 10',
            '2017/2018: 11',
            '2017/2018: 12',
            '2017/2018: 1',
            '2017/2018: 2',
            '2017/2018: 3',
            '2017/2018: 4',
            '2017/2018: 5',
            '2017/2018: 6',
            '2017/2018: 7',
            '2017/2018: 8'
          )

In [131]:
destinations_cohort_0001_2years <- destinations_cohort_0001 |>
    select('cohort',
            'person_id',
            'Intended_destination',
           
           '2017/2018: 9',
            '2017/2018: 10',
            '2017/2018: 11',
            '2017/2018: 12',
            '2017/2018: 1',
            '2017/2018: 2',
            '2017/2018: 3',
            '2017/2018: 4',
            '2017/2018: 5',
            '2017/2018: 6',
            '2017/2018: 7',
            '2017/2018: 8',
           
           '2018/2019: 9',
            '2018/2019: 10',
            '2018/2019: 11',
            '2018/2019: 12',
            '2018/2019: 1',
            '2018/2019: 2',
            '2018/2019: 3',
            '2018/2019: 4',
            '2018/2019: 5',
            '2018/2019: 6',
            '2018/2019: 7',
            '2018/2019: 8'
          )

In [132]:
destinations_cohort_0102_2years <- destinations_cohort_0102 |>
    select('cohort',
            'person_id',
            'Intended_destination',
           
           '2018/2019: 9',
            '2018/2019: 10',
            '2018/2019: 11',
            '2018/2019: 12',
            '2018/2019: 1',
            '2018/2019: 2',
            '2018/2019: 3',
            '2018/2019: 4',
            '2018/2019: 5',
            '2018/2019: 6',
            '2018/2019: 7',
            '2018/2019: 8',
           
           '2019/2020: 9',
            '2019/2020: 10',
            '2019/2020: 11',
            '2019/2020: 12',
            '2019/2020: 1',
            '2019/2020: 2',
            '2019/2020: 3',
            '2019/2020: 4',
            '2019/2020: 5',
            '2019/2020: 6',
            '2019/2020: 7',
            '2019/2020: 8'
          )

In [133]:
new_names <- c("Year1Month1", "Year1Month2", "Year1Month3",
              "Year1Month4", "Year1Month5", "Year1Month6",
              "Year1Month7", "Year1Month8", "Year1Month9",
              "Year1Month10", "Year1Month11", "Year1Month12",
              "Year2Month1", "Year2Month2", "Year2Month3",
              "Year2Month4", "Year2Month5", "Year2Month6",
              "Year2Month7", "Year2Month8", "Year2Month9",
              "Year2Month10", "Year2Month11", "Year2Month12")

In [134]:
colnames(destinations_cohort_9899_2years)[4:27] <- new_names
colnames(destinations_cohort_9900_2years)[4:27] <- new_names
colnames(destinations_cohort_0001_2years)[4:27] <- new_names
colnames(destinations_cohort_0102_2years)[4:27] <- new_names

In [135]:
head(destinations_cohort_0102_2years)

  cohort  person_id
1 2001/02 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D
2 2001/02 0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7
3 2001/02 0018E26A40A6299391164D4918658B0B1248367C762DCE6D2FDF1AE131A9138C
4 2001/02 0019031CD62586D59268772800516ED50CDF1EF7DE46488542BB031850F6E68A
5 2001/02 001E5C1FFA964716BF5E84562BC0B5D64F7742B1E8126718A5C0157D485F215D
6 2001/02 001F566795F57F5D8DD92430D868A38B757699844E3E09569B33253527012932
  Intended_destination Year1Month1 Year1Month2 Year1Month3 Year1Month4
1 NA                   Education   Education   Education   Education
2 NA                   Education   Education   Education   Education
3 NA                   NA          Education   Education   Education
4 NA                   NA          Education   Education   Education
5 NA                   NA          Education   Education   Education
6 NA                   NA          Education   Education   Education
  Year1Month5 Year1Month6 Year1Month7     ⋯ Year2Month3       Year2Month4
1 Education   Education   NEET: Not ready ⋯ NEET: Seeking EET NEET: Seeking EET
2 Education   Education   Education       ⋯ Education         Education
3 Education   Education   Education       ⋯ Education         Education
4 Education   Education   Education       ⋯ Employment        Employment
5 Education   Education   Education       ⋯ Education         Education
6 Education   Education   Education       ⋯ Education         Education
  Year2Month5       Year2Month6       Year2Month7       Year2Month8
1 NEET: Seeking EET NEET: Seeking EET NEET: Seeking EET NEET: Seeking EET
2 Education         Education         Education         Education
3 Education         Education         Education         Education
4 Employment        Employment        Employment        Employment
5 Education         Education         Education         Education
6 Education         Education         Education         Education
  Year2Month9       Year2Month10      Year2Month11      Year2Month12
1 NEET: Seeking EET NEET: Seeking EET NEET: Seeking EET NEET: Seeking EET
2 Education         Education         Education         Education
3 Education         Education         Education         Education
4 Employment        Employment        Employment        Employment
5 Education         Education         Education         NA
6 Education         Education         Education         NA

In [136]:
destinations_cohorts_aligned <- rbind(destinations_cohort_9899_2years,
                                      destinations_cohort_9900_2years,
                                      destinations_cohort_0001_2years,
                                      destinations_cohort_0102_2years)

In [137]:
destinations_cohorts_aligned

      cohort  person_id
1     1998/99 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
2     1998/99 000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909
3     1998/99 001F42538A9E6E496F13CD05B5E9FE91EB3B20F0CEBECA1B76CC5E7151B7A0D4
4     1998/99 00211975518FD5336E43850D59B5F5DDA7CD98B212760111CB40528BDECF3B1B
5     1998/99 00237E9C21696BB29409630166F2D9CCEC24B83FB120AEDD878DDD54C6516B3D
6     1998/99 00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9
7     1998/99 0025102C0D8E8C5F27454E3715E982A43E1431991E85562E55BCB19D9D1BD7D3
8     1998/99 0026BFA5D5426F421200AB505AAD52956621DCC253241A6647302BCE4764547D
9     1998/99 002D3DB2625339C740EB129CCC925A9D90E4F5AA05561B81FE166EDF990B8F65
10    1998/99 002E7A9E65A6A184952E4F1811844FCFCCE758FAE60986A1F9B9C9892FD0895D
11    1998/99 003196BCDC325A98F118130F185DF8FDDE1B8E1E4882719DAE198B2908F03A5B
12    1998/99 0032202712FAB3A372409235FFE3C0486E36F9B2FB9C9C9851B4ACAB9A3330F0
13    1998/99 0043C7C252748432DF62E306CCC2DFF568A52DC78D4021140E3C4676C9D65A7E
14    1998/99 00450DFB52E0DDD50F5800AD149075B29E4A1454F36B9ACF2E106CF44B9BED55
15    1998/99 0045ADA48CA299BC4445318E8D951610DCB89A829665CFC821E92340F0F8B30D
16    1998/99 004FE0E78454FE677A07F1AD8D1226F61C6534E08B44EE01DC6C518FE2200DEA
17    1998/99 0050C79DAB376114E567D08BE22EA699565E600DFC9F3BD68705700FA49DE62C
18    1998/99 005F5FB87F7E1CE08012E08C6B8887E641C2597A119A5E71101F2D07D6BD1499
19    1998/99 006138BE2285A21040A8422B8BBCB90D56DDCB7ECB6623258AFAD0375F4E118A
20    1998/99 0064BF51F495220745AC025A50818B596BDDA2EDFECCF43CD076BB4F895B0E44
21    1998/99 00711A691CFC443674F7DFB014681E1F0C55DC8B9ED0E04E335A7A1B8FDF4F32
22    1998/99 00728E3D3C7714176088844EC230ED81D79E9093AE0742526C9EAF244DD42CFA
23    1998/99 007570ED5702694AEE71FBCA3ED93584AD7C19E06FE4CB64203ED8BE71B024EA
24    1998/99 0075A60FD7FBBCE1BB568F22433CF8A0CA476B94DE83350BFA3F3BDA07371037
25    1998/99 007AA0CA0759384F9FDE693D320070748A8AF12C75E32621E3CF0620E465A0FD
26    1998/99 007D0119A91376D27F773060F5E9C327CC61639E1F8F69E01FB48B14BCAE92AF
27    1998/99 0080DCC449A400C7BEB4A8FD7FBC453381B036E15F3F039EADAE9A1E4550767F
28    1998/99 009354452C32CB442E4EEE6DF777F1EA4756148684FD6E3F75EA15F5F0E28081
29    1998/99 0093549A2B3FB44847A7880014804DB333707601AE77A4AF949EE71E538194D6
30    1998/99 00A18746DA51B08EB5EE9ABA407D9C3F8E3C82B72E5E87B371C03A591F4591F5
⋮     ⋮       ⋮
35653 2001/02 FEFEE4203EF2177115F364C173E81DFB7ED86879326EECBBF4813E38F7F9BC8A
35654 2001/02 FF03BF1E2A039BA8F118AAEAFD1C757D3138A5551B470C270153829139565DD2
35655 2001/02 FF0C3CB098A1EFF36CC03C8C36B23D0C8D1AB0747753ACE9EC6065CD482408B8
35656 2001/02 FF10DCDDB38F2AD2DC8767DFC62670F389828158BCEC5C1E7D793E4614AD1445
35657 2001/02 FF11DE64C6C96030A4E276362D2DF6E4695045FFFC78543F75B7FD9CAA0E95E4
35658 2001/02 FF15B543AF51E53917F1E8ECBFED9707195B3316312F04E02B9438BB7BBED9FA
35659 2001/02 FF166F1349783175407313E35C3E20105BB7BFACC3680798961FE9C9B8E41FA7
35660 2001/02 FF1C8BA4C2D9C4E2DB2B64F092A16C70846232BDF5D18827114B1F40D1A4CEA3
35661 2001/02 FF35E0916282ECC5BFC997AB1F6866B5289FA0C95838F318AAD4EFCF4A04D87F
35662 2001/02 FF3752BEEFF14D8C9F4DAF38DD5806E47CFD4A1F51CADCA375E885EE3D6CF5E2
35663 2001/02 FF40E206271C27C81CBC640537EBD223DA63168EFE943D7A0352F840B8BC79BC
35664 2001/02 FF40EFF70112B4162DB955BC8B70FF0763F2A509B0D8C67F5B3CC39E60EFDFCB
35665 2001/02 FF492AB1F9A7DFDFA90FAA075071B978780CFFDD64435E5CC205803A33A48BB3
35666 2001/02 FF5A6E829A11E32FE9B98382A4A4EDA7AFC7D45C48A181666899DC62A282D688
35667 2001/02 FF61F463A80412127350F171EAFFCA827D736DCF065D99769CC0E6AD72DBAD47
35668 2001/02 FF63250D160E943CD3B77C5060A163DF69CE5AB3E0F3FA317DFA8B524079E6AE
35669 2001/02 FF77AAB58760E4616819BF69FA7A7D0466EC940FC1B666F5D8FC15261B05FDA7
35670 2001/02 FF85FB47EF271836ECDF7555602263FC0E52F8A84F39868EE7B66E30E47DF618
35671 2001/02 FF9024B3D2775BB5CC65F8872CB1A8BECAD9A7E25FBB3C3DF7D46A8A1BE31AC1
35672 2001/02 FF94D3F7FDB40C124787D0EBA0CD7660187135442D800F18C11487D380F55663
35673 2001/02 FFAA13CCE7B35BA3D3A737EF1A13BCE2289A94F9778EC0C9F18CD77F1B93C979
35674 2001/02 FFBCE0C32A37E3663F1C5159ECFC6F08CD5722E938464A58634F3263003F1D9F
35675 2001/02 FFC0379FDA559C1337454C579FF36F9AE82E62D16B3223D009C57DEC3731754C
35676 2001/02 FFC7129859DD885141E316248A0EB23059DB0F0DB98242C34C67F06FBBAB8041
35677 2001/02 FFC96F346EC6829E7A31F60109FD729DE208D180104B50FC8B1BFAD552D6C8FC
35678 2001/02 FFD391941F3AA9CB910FFFACF24CC2CEAD0BC63EED146E9C21B2C71BA77B084A
35679 2001/02 FFEA068077E4464D059236951F07D7DF96542C2197AAFAC3E20C036BACB9825C
35680 2001/02 FFFA6705A275195BFE8A443AF0BD2AA86B1AA0481D330D8665813206EB8DAD43
35681 2001/02 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77
35682 2001/02 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
      Intended_destination Year1Month1       Year1Month2
1     NA                   Education         Education
2     NA                   NA                Education
3     NA                   NA                Education
4     NA                   NA                Employment
5     EET                  NA                NA
6     NA                   Education         Education
7     NA                   Education         Education
8     NA                   NA                Education
9     NA                   NA                Education
10    NA                   NA                NA
11    EET                  Education         Education
12    NA                   Education         Education
13    NA                   Education         Education
14    NA                   NA                Education
15    NA                   NEET: Seeking EET NEET: Seeking EET
16    NA                   Education         Education
17    NA                   NA                NA
18    NA                   Education         Education
19    NA                   Education         Education
20    EET                  Education         NA
21    NA                   NA                Education
22    NA                   Education         Education
23    NA                   Education         NA
24    NA                   NA                Education
25    NA                   NA                Education
26    EET                  NA                NA
27    EET                  Education         Education
28    NA                   Education         Education
29    NA                   Employment        Employment
30    NA                   NA                Employment
⋮     ⋮                    ⋮                 ⋮
35653 NA                   Education         Education
35654 NA                   Education         Education
35655 NA                   Employment        Employment
35656 NA                   Education         Education
35657 NA                   Education         Education
35658 EET                  NA                NA
35659 NA                   Education         NEET: Seeking EET
35660 NA                   NA                NA
35661 NA                   Education         Education
35662 NA                   NA                NA
35663 NA                   NEET: Seeking EET NEET: Seeking EET
35664 NEET                 Education         Education
35665 NA                   Education         Education
35666 NA                   NA                Education
35667 NA                   Education         Education
35668 NA                   Education         Education
35669 NA                   Education         Education
35670 NA                   Education         Education
35671 NA                   Education         Education
35672 NA                   NA                Education
35673 NA                   NA                Education
35674 NA                   Education         Education
35675 NA                   NA                Education
35676 NA                   Education         Education
35677 NA                   Education         Education
35678 NA                   NA                Education
35679 NA                   Education         Education
35680 NA                   NA                Education
35681 NA                   NA                Education
35682 NA                   NA                Education
      Year1Month3       Year1Month4       Year1Month5       Year1Month6
1     Education         NA                NA                Employment
2     Education         Education         NA                Education
3     NA                NA                Education         NA
4     Employment        Employment        Employment        Employment
5     NA                NA                NA                NA
6     NEET: Seeking EET NEET: Seeking EET NEET: Seeking EET NEET: Seeking EET
7     Education         Education         Education         Education
8     Education         Education         Education         Education
9     Education         Education         Education         Education
10    NA                NA                NA                NA
11    Education         Education         Education         Education
12    Education         Education         Education         Education
13    Education         NA                Education         Education
14    Education         NA                Education         Education
15    Training          Training          Training          NEET: Seeking EET
16    Education         Education         Education         Education
17    Education         Education         Education         Education
18    Education         Education         Education         Education
19    Education         Education         Education         Education
20    Education         Education         Education         NA
21    Education         NA                Education         NA
22    Education         Education         Education         Education
23    Education         Education         Education         Education
24    Education         Education         Education         Education
25    Education         Education         Education         Education
26    Education         Education         Education         Education
27    Education         Education         Education         Education
28    NA                Education         NA                Education
29    NA                Employment        NA                Employment
30    Employment        Employment        Employment        Employment
⋮     ⋮                 ⋮                 ⋮                 ⋮
35653 Education         Education         Education         Education
35654 Education         Education         Education         Education
35655 Employment        Employment        Employment        Employment
35656 Education         Education         Education         Education
35657 Education         Education         Education         Education
35658 Employment        Employment        Employment        Employment
35659 NEET: Seeking EET NEET: Seeking EET NEET: Seeking EET NEET: Seeking EET
35660 Education         Education         Education         Education
35661 Education         Education         Education         Education
35662 NA                Education         Education         Education
35663 NEET: Seeking EET NEET: Seeking EET NEET: Seeking EET NEET: Seeking EET
35664 Education         Education         Education         NA
35665 Education         Education         Education         Education
35666 Education         Education         Education         Education
35667 Education         Education         Education         Education
35668 Education         Education         Education         Education
35669 Education         Education         Education         Education
35670 Education         Education         Education         Education
35671 Education         Education         Education         Education
35672 Education         Education         Education         Education
35673 Education         Education         Education         Education
35674 Education         Education         Education         Education
35675 Education         Education         Education         Education
35676 Education         Education         Education         Education
35677 Education         Education         Education         Education
35678 Education         Education         Education         Education
35679 Education         Education         Education         Education
35680 Education         Education         Education         Education
35681 Education         Education         Education         Education
35682 Education         Education         Education         Education
      Year1Month7       ⋯ Year2Month3 Year2Month4 Year2Month5 Year2Month6
1     Employment        ⋯ Employment  Employment  Employment  Employment
2     Education         ⋯ Education   Education   Education   Education
3     Education         ⋯ Education   Education   Education   Education
4     Employment        ⋯ Employment  Employment  Employment  Employment
5     Education         ⋯ Education   Education   Education   Education
6     NEET: Seeking EET ⋯ Employment  Employment  Employment  Employment
7     Education         ⋯ Education   Education   Education   Education
8     Education         ⋯ Education   Education   Education   Education
9     Education         ⋯ Education   Education   Education   Education
10    NA                ⋯ Employment  Employment  Employment  Employment
11    Education         ⋯ Education   Education   Education   Education
12    Education         ⋯ Education   Education   Education   Education
13    NA                ⋯ Education   Education   Education   Education
14    Education         ⋯ Education   Education   Education   Education
15    NEET: Seeking EET ⋯ Training    Training    Training    NA
16    Education         ⋯ Education   Education   Education   Education
17    Education         ⋯ Education   Education   Education   Education
18    Education         ⋯ Education   Education   Education   Education
19    Education         ⋯ Education   Education   Education   Education
20    Education         ⋯ Education   Education   Education   Education
21    NA                ⋯ Education   Education   Education   Education
22    Education         ⋯ Education   Education   Education   Education
23    NEET: Seeking EET ⋯ Employment  Employment  Education   Education
24    Education         ⋯ Education   Education   Education   Education
25    Education         ⋯ Employment  Employment  Employment  Employment
26    Education         ⋯ Education   Education   Education   Education
27    Education         ⋯ Education   Education   Education   Education
28    Education         ⋯ Education   Education   Education   Education
29    Employment        ⋯ Employment  Employment  Employment  Employment
30    Employment        ⋯ Employment  Employment  Employment  Employment
⋮     ⋮                 ⋱ ⋮           ⋮           ⋮           ⋮
35653 Education         ⋯ Education   Education   Education   Education
35654 Education         ⋯ Education   Education   Education   Education
35655 Employment        ⋯ Employment  Employment  Employment  Employment
35656 Education         ⋯ Education   Education   Education   Education
35657 Education         ⋯ Education   Education   Education   Education
35658 Employment        ⋯ Employment  Employment  Employment  Employment
35659 NEET: Seeking EET ⋯ Education   Education   Education   Education
35660 Education         ⋯ Education   Education   Education   Education
35661 Education         ⋯ Education   Education   Education   Education
35662 Education         ⋯ Education   Education   Education   Education
35663 NEET: Seeking EET ⋯ Refused     Refused     Refused     Refused
35664 NA                ⋯ Employment  Employment  Employment  Employment
35665 Education         ⋯ Education   Education   Education   Education
35666 Education         ⋯ Education   Education   Education   Education
35667 Education         ⋯ Education   Education   Education   Education
35668 Education         ⋯ Education   Education   Education   Education
35669 Education         ⋯ Education   Education   Education   Education
35670 Education         ⋯ Education   Education   Education   Education
35671 Education         ⋯ Education   Education   Education   Education
35672 Education         ⋯ Education   Education   Education   Education
35673 Education         ⋯ Education   Education   Education   Education
35674 Education         ⋯ Education   Education   Education   Education
35675 Education         ⋯ Education   Education   Education   Education
35676 Education         ⋯ Education   Education   Education   Education
35677 Education         ⋯ Employment  Employment  Employment  Employment
35678 Education         ⋯ Education   Education   Education   Education
35679 Education         ⋯ Education   Education   Education   Education
35680 Education         ⋯ Education   Education   Education   Education
35681 Education         ⋯ Education   Education   Education   Education
35682 Education         ⋯ Education   Education   Education   Education
      Year2Month7       Year2Month8       Year2Month9       Year2Month10
1     Employment        Employment        Employment        Employment
2     Education         Education         Education         Education
3     Education         Education         Education         Education
4     Employment        Employment        Employment        Employment
5     Education         Education         Education         Education
6     Employment        Employment        Employment        Employment
7     Education         Education         Education         Education
8     Education         Education         Education         Education
9     Education         Education         Education         Education
10    Employment        Employment        Employment        Employment
11    Education         Education         Education         Education
12    Education         Education         Education         Education
13    Education         Education         Education         Education
14    Education         Education         Education         Education
15    NEET: Seeking EET NEET: Seeking EET NEET: Seeking EET NEET: Seeking EET
16    Education         Education         Education         Education
17    Education         Education         Education         Education
18    Education         Education         Education         Education
19    Education         Education         Education         Education
20    Education         Education         Education         Education
21    Education         Education         Education         Education
22    Education         Education         Education         Education
23    Education         Education         Education         Education
24    Education         Education         Education         Education
25    Employment        Employment        Employment        Employment
26    Education         Education         Education         Education
27    Education         Education         Education         Education
28    Education         Education         Education         Education
29    Employment        Employment        NEET: Seeking EET NEET: Seeking EET
30    Employment        Employment        Employment        Employment
⋮     ⋮                 ⋮                 ⋮                 ⋮
35653 Education         Education         Education         Education
35654 Education         Education         Education         Education
35655 Employment        Employment        Employment        Employment
35656 Education         Education         Education         Education
35657 Education         Education         Education         Education
35658 Employment        Employment        Employment        Employment
35659 Education         Education         Education         Education
35660 Education         Education         Education         Education
35661 Education         Education         Education         Education
35662 Education         Education         Education         Education
35663 Refused           Refused           Refused           Refused

#### save destinations with NEET detail and aligned months as csv

In [138]:
write.csv(destinations_cohorts_aligned, "data/destinations_4cohorts_aligned.csv", row.names = FALSE)