In [1]:
library(tidyverse)
library(dbplyr)
library(bigrquery)
library(lubridate)

bq_auth()

project_id = "yhcr-prd-bradfor-bia-core"

# create connection to database
con <- DBI::dbConnect(bigrquery::bigquery(), 
                      project = project_id)

print(paste0("Connected to : ", project_id))

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘dbplyr’


The following objects are masked from ‘package:dplyr’:

    ident, sql

[1] "Connected to : yhcr-prd-bradfor-bia-core"

In [2]:
person_ids <- read.csv('data/additional_person_ids.csv', header = TRUE)

In [3]:
exclusion_data = "CB_2489.cb_ExclusionStudentsDetails"

exclusion_table <- tbl(con, exclusion_data) |>
    select(person_id,Year,NumberOfEnrolments,TotalFixedExclusions,TotalFixedSessions,PermanentExclusionCount,PrimarySENtype)

In [4]:
exclusion_df <- collect(exclusion_table)

# Extract SEN type to compare with missing

In [5]:
exclusion_df |> distinct(PrimarySENtype) |> pull(PrimarySENtype)

 [1] NA     " "    "BESD" "OTH"  "MLD"  "HI"   "SPLD" "SLCN" "PMLD" "ASD"
[11] "PD"   "SLD"  "SEMH" "NSA"  "VI"   "MSI"

In [6]:
sen <- exclusion_df |>
    select(person_id, PrimarySENtype) |>
    filter(PrimarySENtype %in% c('BESD','OTH','MLD','HI','SPLD','SLCN','PMLD','ASD','PD','SLD','SEMH','NSA','VI','MSI'))

In [7]:
sen |> nrow()

[1] 10927

## Save csv

In [8]:
# save as csv
write.csv(sen, "data/additional_sen_extras.csv", row.names = FALSE)

# Exclusions

In [9]:
exclusion_df |> arrange(Year) |> distinct(Year) |> pull(Year)

 [1] "2002" "2003" "2004" "2005" "2006" "2007" "2008" "2009" "2010" "2011"
[11] "2012" "2013" "2014" "2015" "2016" "2017" "2018" "2019" "2020" "2021"

In [10]:
exclusion_df |> arrange(NumberOfEnrolments) |> distinct(NumberOfEnrolments) |> pull(NumberOfEnrolments)

[1]  1  2  3  4 NA

In [11]:
exclusions_filtered <- exclusion_df |>
    filter(person_id %in% person_ids$person_id) |>
    select(-PrimarySENtype)

In [12]:
exclusions_filtered |> nrow()

[1] 4924

In [13]:
exclusions_filtered |> arrange(Year) |> distinct(Year) |> pull(Year)

 [1] "2007" "2008" "2009" "2010" "2011" "2012" "2013" "2014" "2015" "2016"
[11] "2017" "2018" "2019"

In [14]:
exclusions_filtered_cohort <- exclusions_filtered |>
    left_join(person_ids, by = join_by(person_id))

Warning message in left_join(exclusions_filtered, person_ids, by = join_by(person_id)):
“Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 4 of `x` matches multiple rows in `y`.
ℹ Row 8487 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.”

In [15]:
head(exclusions_filtered_cohort)

  person_id                                                        Year
1 F442350586B4F3CD0E0B5ADA701CE357664BDBD476679130440815D410CC0E61 2007
2 FE7E0341560512618F68DB203ADB29FDF291C26185D50CB9A291C1CC4737FADD 2007
3 DC4E7FC6B02A9C3E0D51398F4BB41B31ACD647847052DF06AC3710DE628DAE7B 2007
4 1BFF9F036C8DD0C66E5330B88F6B5A2A7A7105809E2A94BFD6AF7B3A81F60399 2007
5 1BFF9F036C8DD0C66E5330B88F6B5A2A7A7105809E2A94BFD6AF7B3A81F60399 2007
6 2B61287808231C720C63753E882478D403B0E4F4A569D68AEFF37830BCCDEE60 2007
  NumberOfEnrolments TotalFixedExclusions TotalFixedSessions
1 1                   3                   48
2 1                   4                   25
3 1                   3                   25
4 1                  10                   43
5 1                  10                   43
6 1                   7                   38
  PermanentExclusionCount NCCIS_ACADYR
1 NA                      2015/2016
2 NA                      2016/2017
3 NA                      2016/2017
4 NA                      2015/2016
5 NA                      2015/2016
6 NA                      2015/2016

## Select dates by cohort

In [16]:
cohort_1 <- exclusions_filtered_cohort |> filter(NCCIS_ACADYR == '2015/2016')

In [17]:
cohort_1 |> arrange(Year) |> distinct(Year) |> pull(Year)

 [1] "2007" "2008" "2009" "2010" "2011" "2012" "2013" "2014" "2015" "2016"
[11] "2017" "2018"

In [18]:
cohort_1 <- cohort_1 |>
    filter(Year %in% c('2010','2011','2012','2013','2014','2015'))

In [19]:
cohort_2 <- exclusions_filtered_cohort |> filter(NCCIS_ACADYR == '2016/2017')

In [20]:
cohort_2 |> arrange(Year) |> distinct(Year) |> pull(Year)

 [1] "2007" "2008" "2009" "2010" "2011" "2012" "2013" "2014" "2015" "2016"
[11] "2017" "2018" "2019"

In [21]:
cohort_2 <- cohort_2 |>
    filter(Year %in% c('2011','2012','2013','2014','2015','2016'))

In [22]:
cohort_2 |> arrange(person_id, Year)

     person_id                                                        Year
1    0025514088C52FB45B7439689844A1FEA2FB8B2753994F432CC7DDC68036BD59 2016
2    004D0B5FF90E252B2912022950FEC4929A1ACB81BA61A626F3093B3B496C93CA 2014
3    00AAB0713CDD0D6705388B5DAED9E7AC7AA19E168DF615318DD6ED3DC4EE4CA1 2014
4    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916 2012
5    00D0DCE31E1E532A9AD051B9A03E286EE87258F21A7AC2C7EC65C9A2F2C3D6BB 2015
6    00D0DCE31E1E532A9AD051B9A03E286EE87258F21A7AC2C7EC65C9A2F2C3D6BB 2016
7    018B1258C2F1AEE4098F69728BCD61326D343AC119B826BE21430E8D7DAD2857 2015
8    01D5BB808C605F3206FF17738BC4011F459A59BBA3DD18AB15D8364CD1B383EF 2014
9    01D5BB808C605F3206FF17738BC4011F459A59BBA3DD18AB15D8364CD1B383EF 2014
10   01D5BB808C605F3206FF17738BC4011F459A59BBA3DD18AB15D8364CD1B383EF 2015
11   01D5BB808C605F3206FF17738BC4011F459A59BBA3DD18AB15D8364CD1B383EF 2015
12   02340F3F5D13AB36293E7F6DF375CE9AAE460153C9B2F3682ABF23C881A11830 2011
13   02340F3F5D13AB36293E7F6DF375CE9AAE460153C9B2F3682ABF23C881A11830 2012
14   02340F3F5D13AB36293E7F6DF375CE9AAE460153C9B2F3682ABF23C881A11830 2013
15   02340F3F5D13AB36293E7F6DF375CE9AAE460153C9B2F3682ABF23C881A11830 2015
16   025B83C54F43BCBF9D843EB4277A89CBBA219A4370F17F7C855801AC1BF64902 2015
17   025B83C54F43BCBF9D843EB4277A89CBBA219A4370F17F7C855801AC1BF64902 2016
18   02681DD9E411D27F4B0B58E1F0CB8D6D85EED6C7868C8A31E2CFF5CDCD23C55B 2014
19   026BCB91C7B0996FEE1C7525B3B05E2100731DAD4C94CA0B1D7D9DB94C124414 2016
20   030DFF63ED83821DFE6AC65EB515B33F75C2E75D63DEC18B85C5EE94D89CB591 2012
21   030DFF63ED83821DFE6AC65EB515B33F75C2E75D63DEC18B85C5EE94D89CB591 2013
22   030DFF63ED83821DFE6AC65EB515B33F75C2E75D63DEC18B85C5EE94D89CB591 2014
23   030DFF63ED83821DFE6AC65EB515B33F75C2E75D63DEC18B85C5EE94D89CB591 2016
24   0383BAC74CDF01BD05413B510B2961DF66D212EAF8EFBD4705FA540B501451F1 2015
25   0383BAC74CDF01BD05413B510B2961DF66D212EAF8EFBD4705FA540B501451F1 2015
26   0390C9B3C796AF612692B57F080BCA4BF82FAEDD564619E748B32D68BE00190A 2015
27   0390C9B3C796AF612692B57F080BCA4BF82FAEDD564619E748B32D68BE00190A 2015
28   0390C9B3C796AF612692B57F080BCA4BF82FAEDD564619E748B32D68BE00190A 2015
29   0390C9B3C796AF612692B57F080BCA4BF82FAEDD564619E748B32D68BE00190A 2015
30   03C67308298F1CB39B63B21FE0EA24C3AB3DD9B4062968764C5A183CB9AF3C82 2011
⋮    ⋮                                                                ⋮
2919 FCF1D06591FBC5EF9E61BFC87A71F7AB5F378B62AB231B3EFFC9C04D023225A7 2013
2920 FD0E12F4DA370C65B5D77E19151A4B66763ABB02C0D5E9232B08C7B2AB7A7C8A 2013
2921 FD0E12F4DA370C65B5D77E19151A4B66763ABB02C0D5E9232B08C7B2AB7A7C8A 2014
2922 FD1487AEA6899D31D91ED4094F9BD21A8EEA8CE9C24D38216453DAF9E31D85E1 2013
2923 FD1487AEA6899D31D91ED4094F9BD21A8EEA8CE9C24D38216453DAF9E31D85E1 2014
2924 FD3A8956FC7ECC4E7956E8927C26118F6A431E8E944FFC40E1D4550343B21A4A 2015
2925 FD407133CF480DF8165DAADF7A6FEBFA310B3DA05C49D9F5F3E4E0C19913A076 2012
2926 FD4240180C502A6B29ABA286EA89EDC6DD1A9DAA583173AFFF592E3BA56A571C 2014
2927 FD4240180C502A6B29ABA286EA89EDC6DD1A9DAA583173AFFF592E3BA56A571C 2015
2928 FD4240180C502A6B29ABA286EA89EDC6DD1A9DAA583173AFFF592E3BA56A571C 2016
2929 FD46472E92CC6B39280F07427630DAFF4E7122E6D46657DBF0ACFEBF968603C8 2015
2930 FD77800BE3F7B8710C90D14B8B8CBA2D442B6C0B9FEFA853E612C81103F91176 2015
2931 FDA13B650DEC9DBA53E143F38E036F0CAA9FE20D3F9D1511642ADE777DC5C52C 2015
2932 FDAE35F69314F50F951255B3142E0C7A2B2B8F30A8BAA46397233059E4F76E70 2015
2933 FDAE35F69314F50F951255B3142E0C7A2B2B8F30A8BAA46397233059E4F76E70 2016
2934 FE00D687F9774C9041EF0556DA93F28938BB313FA05AC7FD28C894CD3FB05B2B 2014
2935 FE7E0341560512618F68DB203ADB29FDF291C26185D50CB9A291C1CC4737FADD 2012
2936 FE7E0341560512618F68DB203ADB29FDF291C26185D50CB9A291C1CC4737FADD 2013
2937 FE7E0341560512618F68DB203ADB29FDF291C26185D50CB9A291C1CC4737FADD 2015
2938 FE9CD3A881062D28A3CCCDBF9C58A31CDB882FFD8D32C53EF0E257EC16AE943D 2011
2939 FE9CD3A881062D28A3CCCDBF9C58A31CDB882FFD8D32C53EF0E257EC16AE943D 2012
2940 FE9CD3A881062D28A3CCCDBF9C58A31CDB882FFD8D32C53EF0E257EC16AE943D 2014
2941 FF0E4F96548A1554A48EEB6E692699D9D511D2152C8E21BBDD82E26A97967B4A 2015
2942 FF4C2AE50FAACEE194CF4F6FE7C8204D070615E157145637C54FCCDFED7C0A2B 2013
2943 FF4C2AE50FAACEE194CF4F6FE7C8204D070615E157145637C54FCCDFED7C0A2B 2014
2944 FF4C2AE50FAACEE194CF4F6FE7C8204D070615E157145637C54FCCDFED7C0A2B 2016
2945 FF6DAD51E8AE31D80E60BA375F99DCD8D602AB6CD8E379E4F9174627F91905C9 2011
2946 FF6DAD51E8AE31D80E60BA375F99DCD8D602AB6CD8E379E4F9174627F91905C9 2016
2947 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB 2013
2948 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB 2014
     NumberOfEnrolments TotalFixedExclusions TotalFixedSessions
1    1                  1                    10
2    1                  1                     6
3    1                  1                     4
4    1                  1                     2
5    1                  2                     6
6    1                  4                     7
7    1                  1                    24
8    1                  2                     6
9    1                  2                     6
10   1                  2                     2
11   1                  2                     2
12   1                  2                    12
13   1                  2                     6
14   1                  2                     8
15   2                  4                    19
16   1                  1                     6
17   1                  2                    10
18   1                  1                     4
19   1                  1                     5
20   1                  1                     2
21   1                  1                     4
22   1                  1                     8
23   1                  1                     4
24   1                  1                     4
25   1                  1                     4
26   1                  1                    10
27   1                  1                    10
28   1                  1                    10
29   1                  1                    10
30   1                  0                     0
⋮    ⋮                  ⋮                    ⋮
2919 1                  0                     0
2920 1                  6                    34
2921 1                  1                    10
2922 1                  1                     4
2923 1                  1                     2
2924 1                  1                    10
2925 1                  1                     2
2926 1                  2                     4
2927 1                  7                    22
2928 1                  1                     4
2929 1                  1                     4
2930 1                  1                     6
2931 1                  2                    20
2932 1                  1                     2
2933 1                  3                    26
2934 1                  1                     4
2935 1                  1                     2
2936 1                  1                     4
2937 1                  3                    12
2938 1                  0                     0
2939 1                  1                     2
2940 1                  1                     6
2941 1                  1                     4
2942 1                  1                     2
2943 1                  1                     3
2944 1                  2                     4
2945 1                  1                     1
2946 1                  1                    10
2947 1                  1                     1
2948 1                  1                     2
     PermanentExclusionCount NCCIS_ACADYR
1    0                       2016/2017
2    0                       2016/2017
3    0                       2016/2017
4    0                       2016/2017
5    0                       2016/2017
6    0                       2016/2017
7    0                       2016/2017
8    0                       2016/2017
9    0                       2016/2017
10   0                       2016/2017
11   0                       2016/2017
12   0                       2016/2017
13   0                       2016/2017
14   0                       2016/2017
15   0                       2016/2017
16   0                       2016/2017
17   0                       2016/2017
18   0                       2016/2017
19   0                       2016/2017
20   0                       2016/2017
21   0                       2016/2017
22   0                       2016/2017
23   0                       2016/2017
24   0                       2016/2017
25   0                       2016/2017
26   0                       2016/2017
27   0                       2016/2017
28   0                       2016/2017
29   0                       2016/2017
30   0                       2016/2017
⋮    ⋮                       ⋮
2919 1                       2016/2017
2920 0                       2016/2017
2921 0                       2016/2017
2922 0                       2016/2017
2923 0                       2016/2017
2924 0                       2016/2017
2925 0                       2016/2017
2926 0                       2016/2017
2927 0                       2016/2017
2928 0                       2016/2017
2929 0                       2016/2017
2930 0                       2016/2017
2931 0                       2016/2017
2932 0                       2016/2017
2933 0                       2016/2017
2934 0                       2016/2017
2935 0                       2016/2017
2936 0                       2016/2017
2937 0                       2016/2017
2938 0                       2016/2017
2939 0                       2016/2017
2940 0                       2016/2017
2941 0                       2016/2017
2942 0                       2016/2017
2943 0                       2016/2017
2944 0                       2016/2017
2945 0                       2016/2017
2946 0                       2016/2017
2947 0                       2016/2017
2948 0                       2016/2017

## Rejoin cohorts and tally exclusions

In [23]:
all_exclusions <- rbind(cohort_1,cohort_2)

In [24]:
exclusions_alltime <- all_exclusions |> 
    group_by(person_id) %>%
      summarise(
        Suspensions = sum(TotalFixedExclusions, na.rm = TRUE),
        SuspensionSessions = sum(TotalFixedSessions, na.rm = TRUE),
        Exclusions = sum(PermanentExclusionCount, na.rm = TRUE),
        .groups = "drop"
      )

In [25]:
exclusions_alltime

     person_id
1    00211975518FD5336E43850D59B5F5DDA7CD98B212760111CB40528BDECF3B1B
2    0025514088C52FB45B7439689844A1FEA2FB8B2753994F432CC7DDC68036BD59
3    0045ADA48CA299BC4445318E8D951610DCB89A829665CFC821E92340F0F8B30D
4    004D0B5FF90E252B2912022950FEC4929A1ACB81BA61A626F3093B3B496C93CA
5    007570ED5702694AEE71FBCA3ED93584AD7C19E06FE4CB64203ED8BE71B024EA
6    009354452C32CB442E4EEE6DF777F1EA4756148684FD6E3F75EA15F5F0E28081
7    0093549A2B3FB44847A7880014804DB333707601AE77A4AF949EE71E538194D6
8    00AAB0713CDD0D6705388B5DAED9E7AC7AA19E168DF615318DD6ED3DC4EE4CA1
9    00C823B541B2D9EAA0C42DE865BD315331166CFCBCC6334744ADB31E5F72D916
10   00D0DCE31E1E532A9AD051B9A03E286EE87258F21A7AC2C7EC65C9A2F2C3D6BB
11   00DF0E4C51A21FCBAB2877360CF6663CE4D6A38CDEF3079601A319F3B250AEC6
12   00EC5B7FD1F69BF7968F5FC7F130B1E8057AC19E67EBC5E3039C4233E7D8657E
13   00FB7FF2287CBC46BE16FD0A09A15C0190BAB50647F84B02A51D51B02ED64642
14   013ED8E2B5AE328F92F3A73C615835F8D6048E2EDCA9EFC06636553597110066
15   017BD83D33E24C2CE047BFB67D7D010694F10CAF3E02B4360C88D4EE29E119FD
16   01846FB39CA12D92AC66CEA2227079A681F9093AFB2925A7B7578AB5B44245A3
17   018B1258C2F1AEE4098F69728BCD61326D343AC119B826BE21430E8D7DAD2857
18   019D68532F311169EE28E839E1F63FF348DB5C1B69B919075A8DAB00E6B13429
19   01C363EB312C40E14CCC43F4B63CF67CA4967BEF853AAA9F26959C9E7BB79919
20   01D4C5437E5A02C67E1473FEF63139486A1A85EA656181F6B68633068E174AEB
21   01D5BB808C605F3206FF17738BC4011F459A59BBA3DD18AB15D8364CD1B383EF
22   01FB1E084AF5A275C95EED2C139E48693D91BF93764961162A7EC08B08E71731
23   020A1C1FFF5B937C8888727C70A21ED9A6219660730ABA1BA6454F13B0800329
24   021A70EB6CE9E67A03F9E2295D120DFE1CC467951BDCC0334CDA7887FFBF33D5
25   02340F3F5D13AB36293E7F6DF375CE9AAE460153C9B2F3682ABF23C881A11830
26   025B83C54F43BCBF9D843EB4277A89CBBA219A4370F17F7C855801AC1BF64902
27   02681DD9E411D27F4B0B58E1F0CB8D6D85EED6C7868C8A31E2CFF5CDCD23C55B
28   026B6B2033B19490737973CBA64CB37CD5FBBBADED91AFFE08715C696B149BA3
29   026BCB91C7B0996FEE1C7525B3B05E2100731DAD4C94CA0B1D7D9DB94C124414
30   02FA725483693A9C5CBD699199A586D5C6BFC58344E37E8EAB7E327AA259FB10
⋮    ⋮
2625 FD3E5173238899FD57D04725107CC5E1F2DAA03B4BCEAB485676DEA433BF1228
2626 FD407133CF480DF8165DAADF7A6FEBFA310B3DA05C49D9F5F3E4E0C19913A076
2627 FD4240180C502A6B29ABA286EA89EDC6DD1A9DAA583173AFFF592E3BA56A571C
2628 FD46472E92CC6B39280F07427630DAFF4E7122E6D46657DBF0ACFEBF968603C8
2629 FD4E529F62826215CF6C0B6D9F99F32B24A10CE1DD2C412A33975DA4DFF04C07
2630 FD71E1FAC0B6E109416C3E52C40DC016538F74C1200512DDBC6627175D2D2489
2631 FD77800BE3F7B8710C90D14B8B8CBA2D442B6C0B9FEFA853E612C81103F91176
2632 FD964A1289AC7B6DAFA34D5EA64857D6C2BF3B0C8153F20C40208119A4384901
2633 FD9CBFB8278D5B01B9E8C2AF41740D74B20CA78F13593DD90AEC87453B1A7992
2634 FDA13B650DEC9DBA53E143F38E036F0CAA9FE20D3F9D1511642ADE777DC5C52C
2635 FDAE35F69314F50F951255B3142E0C7A2B2B8F30A8BAA46397233059E4F76E70
2636 FDD9C062BDEEB81DDBBEC46A08F00140D5EE272A3C0570E0B80B5A8AB3652712
2637 FDE0ED1B1BFB7DBB60DDF325804D8B28D458FCB131B452663C1B53BAB9352A51
2638 FE00D687F9774C9041EF0556DA93F28938BB313FA05AC7FD28C894CD3FB05B2B
2639 FE1CF56E5C388698F0F38B1108358A7D3CAA29632D5584A09A7A0232EE6DD6D8
2640 FE5386B1876DF6DDB25DE2BF9246B8263D80B9CC125E1DF54F885350EA454452
2641 FE5841218611C59801AB89241D64D5B0160D7D104D8898584076A4074E13E46D
2642 FE7E0341560512618F68DB203ADB29FDF291C26185D50CB9A291C1CC4737FADD
2643 FE865826CF1F521140082014FCC19CD99A8192B1EA848DC1D7AD997D522DDE16
2644 FE8D0D3BC374DB46231FB4C72D82A69D2152D9457B44935998847336C906E72E
2645 FE9A2EB7F690A4A6CDE88DAD0C233157455328F0541F6CB11C7645A1A2B83560
2646 FE9CD3A881062D28A3CCCDBF9C58A31CDB882FFD8D32C53EF0E257EC16AE943D
2647 FECB03F3615901E7AE0D2AA6BD9DE76F4D99AD1FFB9F4E3ECEB52CACB3B8726D
2648 FEFDC528D14429D65FC779FFF3FBCF7721A1B70814BF8B113FDDDCD779FBE4DF
2649 FF0E4F96548A1554A48EEB6E692699D9D511D2152C8E21BBDD82E26A97967B4A
2650 FF4C2AE50FAACEE194CF4F6FE7C8204D070615E157145637C54FCCDFED7C0A2B
2651 FF6DAD51E8AE31D80E60BA375F99DCD8D602AB6CD8E379E4F9174627F91905C9
2652 FF7EFC3006B327BC644769B23FF20D6E4AFBD5EAE86EE2110BB9B3E1E7317740
2653 FFB5122C6D8418A48E6FB924782900EF5E4605E4ECFD42FFB6C3119515E32C2F
2654 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB
     Suspensions SuspensionSessions Exclusions
1     5          30                 0
2     1          10                 0
3     6          14                 0
4     1           6                 0
5    20          74                 0
6     5          38                 0
7     7          13                 0
8     1           4                 0
9     1           2                 0
10    6          13                 0
11    3          16                 0
12    2           8                 0
13    1           6                 0
14    1           2                 0
15    6          34                 0
16    2          20                 1
17    1          24                 0
18    1           2                 0
19    1          30                 0
20    8          72                 0
21    8          16                 0
22    2          40                 0
23    3           5                 0
24    2           8                 0
25   10          45                 0
26    3          16                 0
27    1           4                 0
28    2           4                 0
29    1           5                 0
30    1           2                 0
⋮    ⋮           ⋮                  ⋮
2625  2           12                0
2626  1            2                0
2627 10           30                0
2628  1            4                0
2629  1            2                0
2630 20          100                0
2631  1            6                0
2632  1            4                0
2633  8           21                0
2634  2           20                0
2635  4           28                0
2636 10           30                0
2637  1            2                0
2638  1            4                0
2639  2            3                0
2640  8           42                0
2641  2           24                0
2642  5           18                0
2643 14           70                0
2644  1            2                0
2645  5           28                1
2646  2            8                0
2647  6           78                0
2648  6           20                0
2649  1            4                0
2650  4            9                0
2651  2           11                0
2652  2            6                0
2653  1            6                0
2654  2            3                0

## Save csv

In [26]:
# save as csv
write.csv(exclusions_alltime, "data/additional_exclusions.csv", row.names = FALSE)