In [1]:
library(tidyverse)
library(dbplyr)
library(bigrquery)
library(lubridate)

bq_auth()

project_id = "yhcr-prd-bradfor-bia-core"

# create connection to database
con <- DBI::dbConnect(bigrquery::bigquery(), 
                      project = project_id)

print(paste0("Connected to : ", project_id))

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘dbplyr’


The following objects are masked from ‘package:dplyr’:

    ident, sql

[1] "Connected to : yhcr-prd-bradfor-bia-core"

In [2]:
person_ids <- read.csv('data/person_ids.csv', header = TRUE)

In [4]:
exclusion_data = "CB_2489.cb_ExclusionStudentsDetails"

exclusion_table <- tbl(con, exclusion_data) |>
    select(person_id,Year,NumberOfEnrolments,TotalFixedExclusions,TotalFixedSessions,PermanentExclusionCount,PrimarySENtype)

In [6]:
exclusion_df <- collect(exclusion_table)

# Extract SEN type to compare with missing

In [15]:
exclusion_df |> distinct(PrimarySENtype) |> pull(PrimarySENtype)

 [1] NA     " "    "BESD" "OTH"  "MLD"  "HI"   "SPLD" "SLCN" "PMLD" "ASD"
[11] "PD"   "SLD"  "SEMH" "NSA"  "VI"   "MSI"

In [38]:
sen <- exclusion_df |>
    select(person_id, PrimarySENtype) |>
    filter(PrimarySENtype %in% c('BESD','OTH','MLD','HI','SPLD','SLCN','PMLD','ASD','PD','SLD','SEMH','NSA','VI','MSI'))

In [39]:
sen |> nrow()

[1] 10927

## Save csv

In [40]:
# save as csv
write.csv(sen, "data/sen_extras.csv", row.names = FALSE)

# Exclusions

In [8]:
exclusion_df |> arrange(Year) |> distinct(Year) |> pull(Year)

 [1] "2002" "2003" "2004" "2005" "2006" "2007" "2008" "2009" "2010" "2011"
[11] "2012" "2013" "2014" "2015" "2016" "2017" "2018" "2019" "2020" "2021"

In [9]:
exclusion_df |> arrange(NumberOfEnrolments) |> distinct(NumberOfEnrolments) |> pull(NumberOfEnrolments)

[1]  1  2  3  4 NA

In [17]:
exclusions_filtered <- exclusion_df |>
    filter(person_id %in% person_ids$person_id) |>
    select(-PrimarySENtype)

In [18]:
exclusions_filtered |> nrow()

[1] 5037

In [19]:
exclusions_filtered |> arrange(Year) |> distinct(Year) |> pull(Year)

 [1] "2007" "2008" "2009" "2010" "2011" "2012" "2013" "2014" "2015" "2016"
[11] "2017" "2018" "2019" "2020"

In [20]:
exclusions_filtered_cohort <- exclusions_filtered |>
    left_join(person_ids, by = join_by(person_id))

In [22]:
head(exclusions_filtered_cohort)

  person_id                                                        Year
1 6FB5E22CD8825E788A477B4CCEEBAC0B4A50D56141F9322659699841DCC1E97C 2007
2 B353E64ABC7B6CEE2C89B379F6E1FE1B7C11957CD8A50E95BC2F2BFA858CF444 2007
3 AC5A4C888ECAE0D44D1208E14F61E95B3BC90FB52AA09FD6C246773C77A43E26 2017
4 8C35711901E2F60373EF9AC887E97C95765384613B3F440D8D190C7F2205417C 2017
5 26EC80FD819A62ED03E3A9B47BB5F3F72807675A7B8079A1A392629CBD033260 2017
6 B6526B45A48C10CE38A88A086DB9B3A340C7D2E8DFB72759522CF4575BC19191 2017
  NumberOfEnrolments TotalFixedExclusions TotalFixedSessions
1 1                  15                   41
2 1                  11                   59
3 1                  14                   31
4 1                   3                   40
5 1                   2                   32
6 1                   3                   36
  PermanentExclusionCount NCCIS_ACADYR
1 NA                      2017/2018
2 NA                      2018/2019
3  0                      2017/2018
4  0                      2017/2018
5  0                      2018/2019
6  0                      2018/2019

## Select dates by cohort

In [23]:
cohort_1 <- exclusions_filtered_cohort |> filter(NCCIS_ACADYR == '2017/2018')

In [25]:
cohort_1 |> arrange(Year) |> distinct(Year) |> pull(Year)

 [1] "2007" "2008" "2009" "2010" "2011" "2012" "2013" "2014" "2015" "2016"
[11] "2017" "2018" "2019"

In [27]:
cohort_1 <- cohort_1 |>
    filter(Year %in% c('2012','2013','2014','2015','2016','2017'))

In [24]:
cohort_2 <- exclusions_filtered_cohort |> filter(NCCIS_ACADYR == '2018/2019')

In [26]:
cohort_2 |> arrange(Year) |> distinct(Year) |> pull(Year)

 [1] "2007" "2008" "2009" "2010" "2011" "2012" "2013" "2014" "2015" "2016"
[11] "2017" "2018" "2019" "2020"

In [28]:
cohort_2 <- cohort_2 |>
    filter(Year %in% c('2013','2014','2015','2016','2017','2018'))

In [29]:
cohort_2 |> arrange(person_id, Year)

     person_id                                                        Year
1    0019031CD62586D59268772800516ED50CDF1EF7DE46488542BB031850F6E68A 2017
2    002EF3F17C7981C3D6FD842C559E9AA0626E06B3940B670DDA2B71F7070ADF7D 2017
3    002EF3F17C7981C3D6FD842C559E9AA0626E06B3940B670DDA2B71F7070ADF7D 2018
4    00AB4C4DE30808A1DD989DA7B5CE1495F536A534AD3347BB148C1A90D900EE87 2013
5    00AB4C4DE30808A1DD989DA7B5CE1495F536A534AD3347BB148C1A90D900EE87 2014
6    00AB4C4DE30808A1DD989DA7B5CE1495F536A534AD3347BB148C1A90D900EE87 2015
7    00AB4C4DE30808A1DD989DA7B5CE1495F536A534AD3347BB148C1A90D900EE87 2016
8    00AB4C4DE30808A1DD989DA7B5CE1495F536A534AD3347BB148C1A90D900EE87 2017
9    00DE1C30EB1A1AA2CE3FB40A6E8F2CD3C88180EE30C0AE6DEB98D3F0D1BD812C 2016
10   00EDA7B3E285D5F32B567A3FA30BB271560D3D211B046F1F803BF5C7E2DB1918 2017
11   013DEF439FBB5DB5FAB8CA66A79222C46E828A7FBC647474C2F3FDCA63108D0D 2016
12   019B9E9E364E3013EC40B186620F945E943DF2541ABD82695AEDF5AA8A42C862 2015
13   01DD211111ECE9C51A992B85C0E53F8F3A604974F18AD8B5C0C2A2071C05D8DC 2017
14   01DD211111ECE9C51A992B85C0E53F8F3A604974F18AD8B5C0C2A2071C05D8DC 2018
15   0219806BE528EDA4A2797134B2D5936DBD07147BD7D3442FA638B2E3AF315E34 2017
16   023528A1945A4B6190B87F594F7D67992193A8F16A5446237AB29647F92C2FAB 2016
17   0239CB13E86E69A92111DA56243394D513190F44FCA0BC9F32EDB644681F206E 2017
18   0239CB13E86E69A92111DA56243394D513190F44FCA0BC9F32EDB644681F206E 2018
19   0266EDB5E3DF43D6ACBEFDDA888243CC592BB10E77976084DE93E4002ABF1C8A 2015
20   02730C6C708D9E73A3BB56D4A385FBE42C7888416ED66398ED633DAF11D9C9B2 2017
21   027F18C104F1239F36B307F0700F9D12382000C41C2F9C7474B90CCDA8A29E23 2017
22   028ADF10AA495F18F83957D37B592B2467A48926B291BF23467987FFD14D1815 2018
23   02BD3533E91FB4DFF1F325E5D4175A18543AB05F015AC965350E10109D676725 2017
24   02EDA5E640AB7DF73DB32FE649FC324343198C130035103E225F212175129C1E 2016
25   03087BBC6154E70A12E5CF709D596F1C32F77AF9A035D9D8F1CF3CAA7B3D0813 2016
26   032EF98AE628F7D1B75E33749CFC0BC5EB0A56EB3F1264DE328931023664EA74 2014
27   032EF98AE628F7D1B75E33749CFC0BC5EB0A56EB3F1264DE328931023664EA74 2015
28   032EF98AE628F7D1B75E33749CFC0BC5EB0A56EB3F1264DE328931023664EA74 2017
29   032EF98AE628F7D1B75E33749CFC0BC5EB0A56EB3F1264DE328931023664EA74 2018
30   035BC8D747E87A7E8B6193B4023B70429A0DA0A89E2CABAB5A30BBD930968AD1 2016
⋮    ⋮                                                                ⋮
2396 FDBE0448D4959DB5165A9BB71940DA7AD6671E211F87870ACF8D6F72A6BA7A07 2018
2397 FDD22A2964C396D337C457A69BC39ED4821D6D6CA9D817631E1D8D39FE7BEE91 2018
2398 FDF921AEF2AEAE17151EA8C15D152F64D54CB8A824ECDBC7CB56D4351C734420 2016
2399 FDF921AEF2AEAE17151EA8C15D152F64D54CB8A824ECDBC7CB56D4351C734420 2017
2400 FE12AB2DA7E245EFD4582948A8EA955E0A490948E4C01B6EE84EF6833F4F5BEC 2015
2401 FE50A73DF023BDF7E77B4E32809DB19F3D5E447FC9CF35493C08ED30C59F8BE3 2015
2402 FE50A73DF023BDF7E77B4E32809DB19F3D5E447FC9CF35493C08ED30C59F8BE3 2018
2403 FE5E8C6E297BC61CE951A2A4CD0CE3C884DAC2F02FDE2C58ED5CCE45B97F6AEB 2013
2404 FE5E8C6E297BC61CE951A2A4CD0CE3C884DAC2F02FDE2C58ED5CCE45B97F6AEB 2014
2405 FE5E8C6E297BC61CE951A2A4CD0CE3C884DAC2F02FDE2C58ED5CCE45B97F6AEB 2015
2406 FE5E8C6E297BC61CE951A2A4CD0CE3C884DAC2F02FDE2C58ED5CCE45B97F6AEB 2018
2407 FE68794865B2A4C26FEB820A1FC64CBD16FBB513726F675F8059CC856169904D 2016
2408 FE68794865B2A4C26FEB820A1FC64CBD16FBB513726F675F8059CC856169904D 2017
2409 FE6AC7DC3C4A3629D2046E7C5A6248DD3DCD7CE473EDD536A65289640391D61E 2018
2410 FE8201470B14FDA2535F4F5AF15A6A60425A7656FD6885F86C2B414154B51533 2015
2411 FE8201470B14FDA2535F4F5AF15A6A60425A7656FD6885F86C2B414154B51533 2016
2412 FE8201470B14FDA2535F4F5AF15A6A60425A7656FD6885F86C2B414154B51533 2017
2413 FEDAA33BAA4366BE636675D32D81E0750C59FA477A53A85B7916FDE7A92FB56C 2015
2414 FEDAA33BAA4366BE636675D32D81E0750C59FA477A53A85B7916FDE7A92FB56C 2018
2415 FF10DCDDB38F2AD2DC8767DFC62670F389828158BCEC5C1E7D793E4614AD1445 2017
2416 FF10DCDDB38F2AD2DC8767DFC62670F389828158BCEC5C1E7D793E4614AD1445 2018
2417 FF40E206271C27C81CBC640537EBD223DA63168EFE943D7A0352F840B8BC79BC 2016
2418 FF40E206271C27C81CBC640537EBD223DA63168EFE943D7A0352F840B8BC79BC 2017
2419 FF40E206271C27C81CBC640537EBD223DA63168EFE943D7A0352F840B8BC79BC 2018
2420 FF40EFF70112B4162DB955BC8B70FF0763F2A509B0D8C67F5B3CC39E60EFDFCB 2018
2421 FF5A6E829A11E32FE9B98382A4A4EDA7AFC7D45C48A181666899DC62A282D688 2013
2422 FF63250D160E943CD3B77C5060A163DF69CE5AB3E0F3FA317DFA8B524079E6AE 2018
2423 FF77AAB58760E4616819BF69FA7A7D0466EC940FC1B666F5D8FC15261B05FDA7 2017
2424 FF85FB47EF271836ECDF7555602263FC0E52F8A84F39868EE7B66E30E47DF618 2014
2425 FFC96F346EC6829E7A31F60109FD729DE208D180104B50FC8B1BFAD552D6C8FC 2017
     NumberOfEnrolments TotalFixedExclusions TotalFixedSessions
1    1                   4                   21
2    1                   2                   12
3    1                   1                    2
4    1                   5                   10
5    1                  13                   35
6    1                   1                    6
7    1                   6                   90
8    1                   1                    2
9    1                   1                    1
10   1                   2                   13
11   1                   1                    2
12   1                   1                    2
13   1                   1                    1
14   1                   3                    7
15   1                   1                    4
16   1                   1                   10
17   1                   2                    3
18   1                   2                    5
19   1                   1                    4
20   1                   1                    6
21   1                   1                    2
22   1                   1                    1
23   1                   1                    4
24   1                   1                    4
25   1                   2                    4
26   1                   3                   22
27   1                   5                   14
28   1                   1                   10
29   1                   1                    6
30   1                   1                    4
⋮    ⋮                  ⋮                    ⋮
2396 1                  2                     7
2397 1                  1                     4
2398 1                  1                     6
2399 1                  1                     4
2400 1                  1                    10
2401 1                  1                     1
2402 1                  1                     3
2403 2                  4                    12
2404 1                  4                    24
2405 1                  2                     4
2406 1                  4                    14
2407 1                  2                     6
2408 1                  2                    11
2409 1                  1                     6
2410 1                  2                    18
2411 1                  2                    16
2412 2                  4                    40
2413 1                  1                     6
2414 1                  1                     2
2415 1                  1                     1
2416 1                  1                     2
2417 1                  1                     6
2418 1                  2                    12
2419 1                  4                    14
2420 1                  3                     7
2421 1                  1                    10
2422 1                  1                    10
2423 1                  3                     4
2424 1                  1                     1
2425 1                  1                    10
     PermanentExclusionCount NCCIS_ACADYR
1    0                       2018/2019
2    0                       2018/2019
3    0                       2018/2019
4    0                       2018/2019
5    0                       2018/2019
6    0                       2018/2019
7    0                       2018/2019
8    0                       2018/2019
9    0                       2018/2019
10   0                       2018/2019
11   0                       2018/2019
12   0                       2018/2019
13   0                       2018/2019
14   0                       2018/2019
15   0                       2018/2019
16   0                       2018/2019
17   0                       2018/2019
18   0                       2018/2019
19   0                       2018/2019
20   0                       2018/2019
21   0                       2018/2019
22   0                       2018/2019
23   0                       2018/2019
24   0                       2018/2019
25   0                       2018/2019
26   0                       2018/2019
27   0                       2018/2019
28   0                       2018/2019
29   0                       2018/2019
30   0                       2018/2019
⋮    ⋮                       ⋮
2396 0                       2018/2019
2397 0                       2018/2019
2398 0                       2018/2019
2399 0                       2018/2019
2400 0                       2018/2019
2401 0                       2018/2019
2402 0                       2018/2019
2403 0                       2018/2019
2404 0                       2018/2019
2405 0                       2018/2019
2406 0                       2018/2019
2407 0                       2018/2019
2408 0                       2018/2019
2409 0                       2018/2019
2410 0                       2018/2019
2411 0                       2018/2019
2412 0                       2018/2019
2413 0                       2018/2019
2414 0                       2018/2019
2415 0                       2018/2019
2416 0                       2018/2019
2417 0                       2018/2019
2418 0                       2018/2019
2419 0                       2018/2019
2420 0                       2018/2019
2421 0                       2018/2019
2422 0                       2018/2019
2423 0                       2018/2019
2424 0                       2018/2019
2425 0                       2018/2019

## Rejoin cohorts and tally exclusions

In [30]:
all_exclusions <- rbind(cohort_1,cohort_2)

In [31]:
exclusions_alltime <- all_exclusions |> 
    group_by(person_id) %>%
      summarise(
        Suspensions = sum(TotalFixedExclusions, na.rm = TRUE),
        SuspensionSessions = sum(TotalFixedSessions, na.rm = TRUE),
        Exclusions = sum(PermanentExclusionCount, na.rm = TRUE),
        .groups = "drop"
      )

In [32]:
exclusions_alltime

     person_id
1    00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
2    0019031CD62586D59268772800516ED50CDF1EF7DE46488542BB031850F6E68A
3    002EF3F17C7981C3D6FD842C559E9AA0626E06B3940B670DDA2B71F7070ADF7D
4    004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
5    006E9437536191621258B883B68946C2B0D85A0161B4CC2FE397CDE1FC1034FA
6    00984270C3D5F57B15FBB33EE849BA97F72C4F732D031E981D2C43395F4E5098
7    00A0BB9E50F2E2C8181D0DACFEFF0F3136172F3133377432BB753099B678A32D
8    00AB4C4DE30808A1DD989DA7B5CE1495F536A534AD3347BB148C1A90D900EE87
9    00DE1C30EB1A1AA2CE3FB40A6E8F2CD3C88180EE30C0AE6DEB98D3F0D1BD812C
10   00EDA7B3E285D5F32B567A3FA30BB271560D3D211B046F1F803BF5C7E2DB1918
11   012AA581D9CBABA3F2F2457850292856E2FF5B7A7BAD9C82E32034AD637CACDA
12   013DEF439FBB5DB5FAB8CA66A79222C46E828A7FBC647474C2F3FDCA63108D0D
13   015E2F42836BD125E19F4B3E4EA0F2C7D07A43507B1A4343645D77BBB031B003
14   01756F0451ED263A99473FB8CEF8ADFAB896BF1F513208DDD0FCAFF189C6D144
15   017AA9CBE090DF46D824482BB63267EDF494C0D84BE1C2BC263D2A4300750CD6
16   019B9E9E364E3013EC40B186620F945E943DF2541ABD82695AEDF5AA8A42C862
17   01A8189C9E1CE769FF6CD24937079F733400CD3120A898A88D4707FA341D1F3F
18   01C618F6B0C1218EC310864FA23417B95B6B243D391044799EC1FFCD85796F9F
19   01DD211111ECE9C51A992B85C0E53F8F3A604974F18AD8B5C0C2A2071C05D8DC
20   020F1C3CBCBA82F471211F1C683B7ABE70CF0476AABADCC69E982AFF59D555B2
21   0217C037685F3F415E91663B488450FA24BDCC6349CC7D6DC7DC4B4A653E7BBE
22   0219806BE528EDA4A2797134B2D5936DBD07147BD7D3442FA638B2E3AF315E34
23   023528A1945A4B6190B87F594F7D67992193A8F16A5446237AB29647F92C2FAB
24   0239CB13E86E69A92111DA56243394D513190F44FCA0BC9F32EDB644681F206E
25   0266EDB5E3DF43D6ACBEFDDA888243CC592BB10E77976084DE93E4002ABF1C8A
26   02730C6C708D9E73A3BB56D4A385FBE42C7888416ED66398ED633DAF11D9C9B2
27   027F18C104F1239F36B307F0700F9D12382000C41C2F9C7474B90CCDA8A29E23
28   028ADF10AA495F18F83957D37B592B2467A48926B291BF23467987FFD14D1815
29   02B5B0228699365E94953BB6A249D6440EAEE5EDD57C056DAB2C999DA262B8E1
30   02BD3533E91FB4DFF1F325E5D4175A18543AB05F015AC965350E10109D676725
⋮    ⋮
2763 FDD22A2964C396D337C457A69BC39ED4821D6D6CA9D817631E1D8D39FE7BEE91
2764 FDF05AC938601CAE46CDE5FAA9DA6088B4ACDF5D7940AF8BA674D67CCBFA829B
2765 FDF921AEF2AEAE17151EA8C15D152F64D54CB8A824ECDBC7CB56D4351C734420
2766 FE0B0E1715FEC0A05ACDC10E01C64CD9C33CDE60F5197C6B7899F2DFCE590E22
2767 FE12AB2DA7E245EFD4582948A8EA955E0A490948E4C01B6EE84EF6833F4F5BEC
2768 FE3895C54AD1AFAF3487E0DC4AE5D797D949AD1A6BFD767C2A250826F71E8299
2769 FE47AC5ADFDA6F21251363CDE72F3C1305D84EF33FDB0814F25C82B9FAFA64A6
2770 FE50A73DF023BDF7E77B4E32809DB19F3D5E447FC9CF35493C08ED30C59F8BE3
2771 FE5A0494239487D87B120AC5C4A84EA18702EFCE46F18C31242D54DADB719158
2772 FE5E8C6E297BC61CE951A2A4CD0CE3C884DAC2F02FDE2C58ED5CCE45B97F6AEB
2773 FE605A5D1056CBEDB3FCC0A4DBD12413C6FE72F6678273D37D6A5C132502AA7B
2774 FE68794865B2A4C26FEB820A1FC64CBD16FBB513726F675F8059CC856169904D
2775 FE6AC7DC3C4A3629D2046E7C5A6248DD3DCD7CE473EDD536A65289640391D61E
2776 FE7C31E8F10EC910BF2CBCD22674407EA777DF183E6E06AAD7FDE353ABFCA589
2777 FE8201470B14FDA2535F4F5AF15A6A60425A7656FD6885F86C2B414154B51533
2778 FEA4D3C284E413C68FA036CE02B6CF030FC7A2B0DF0CB5A2A60E47E83BBA4624
2779 FEBF37D66CE5EE7404F5DDEFEB7A70DFACA3FBF806F9440B856A364E84DD77A1
2780 FEDAA33BAA4366BE636675D32D81E0750C59FA477A53A85B7916FDE7A92FB56C
2781 FF046FADC901878336120CDC808226A223546B7979E5E7142A594C76024CCA4B
2782 FF10DCDDB38F2AD2DC8767DFC62670F389828158BCEC5C1E7D793E4614AD1445
2783 FF40E206271C27C81CBC640537EBD223DA63168EFE943D7A0352F840B8BC79BC
2784 FF40EFF70112B4162DB955BC8B70FF0763F2A509B0D8C67F5B3CC39E60EFDFCB
2785 FF4162FA747804428CACD396BE5D65D5F2A82B6C1D7217EF1563DCA7F60EACFD
2786 FF5A6E829A11E32FE9B98382A4A4EDA7AFC7D45C48A181666899DC62A282D688
2787 FF63250D160E943CD3B77C5060A163DF69CE5AB3E0F3FA317DFA8B524079E6AE
2788 FF77AAB58760E4616819BF69FA7A7D0466EC940FC1B666F5D8FC15261B05FDA7
2789 FF85FB47EF271836ECDF7555602263FC0E52F8A84F39868EE7B66E30E47DF618
2790 FFC96F346EC6829E7A31F60109FD729DE208D180104B50FC8B1BFAD552D6C8FC
2791 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951
2792 FFE1AA7D705C959745A85B91C6D3F3D22A57B8E50092E9EC25046F6986F77D96
     Suspensions SuspensionSessions Exclusions
1     1            2                0
2     4           21                0
3     3           14                0
4     8           36                0
5     1            2                0
6     1           20                0
7     1            2                0
8    26          143                0
9     1            1                0
10    2           13                0
11    1            6                0
12    1            2                0
13    6           19                0
14    1            2                0
15    1            4                0
16    1            2                0
17    2           12                0
18    1            2                0
19    4            8                0
20    2            4                0
21    3            5                0
22    1            4                0
23    1           10                0
24    4            8                0
25    1            4                0
26    1            6                0
27    1            2                0
28    1            1                0
29    1           10                0
30    1            4                0
⋮    ⋮           ⋮                  ⋮
2763  1           4                 0
2764  3           8                 0
2765  2          10                 0
2766  1           2                 0
2767  1          10                 0
2768  1           6                 0
2769  3          10                 0
2770  2           4                 0
2771  7          29                 0
2772 14          54                 0
2773  1          20                 0
2774  4          17                 0
2775  1           6                 0
2776  5          22                 0
2777  8          74                 0
2778  1          10                 0
2779  3          10                 0
2780  2           8                 0
2781  1          10                 0
2782  2           3                 0
2783  7          32                 0
2784  3           7                 0
2785  1           2                 0
2786  1          10                 0
2787  1          10                 0
2788  3           4                 0
2789  1           1                 0
2790  1          10                 0
2791  1           2                 0
2792  6          12                 0

## Save csv

In [33]:
# save as csv
write.csv(exclusions_alltime, "data/exclusions.csv", row.names = FALSE)