In [1]:
library(tidyverse)
library(dbplyr)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘dbplyr’


The following objects are masked from ‘package:dplyr’:

    ident, sql

In [2]:
raw_data <- read.csv("data/full_data.csv", header = TRUE)

In [3]:
head(raw_data)

  cohort  person_id
1 2000/01 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2 2000/01 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
3 2001/02 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D
4 2001/02 0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7
5 2000/01 00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66
6 2000/01 0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D
  DOB        Gender Ethnicity     EAL ever_FSM ever_CIN DistCurrSch DistNearSch
1 2001-05-15 M      White British 0   0        FALSE    0.66        0.66
2 2001-01-15 F      White British 0   0         TRUE    3.50        0.62
3 2001-11-15 M      White British 0   1         TRUE    7.01        0.00
4 2002-05-15 M      Other         1   0        FALSE    0.57        0.57
5 2000-11-15 M      South Asian   1   0        FALSE    1.69        0.44
6 2001-04-15 F      White British 0   0        FALSE    1.12        0.62
  ⋯ Y2015.2016_Term1 Y2015.2016_Term2 Y2015.2016_Term3 Y2016.2017_Term1
1 ⋯ 107442           107442           107442           143114
2 ⋯ 140569           140569           140569           140569
3 ⋯ 136529           136529           136529           136529
4 ⋯ 107441           107441           107441           143112
5 ⋯ 108087           108087           108087           108087
6 ⋯ 107366           107366           107366           142761
  Y2016.2017_Term2 Y2016.2017_Term3 Y2017.2018_Term1 Y2017.2018_Term2
1 143114           143114               NA               NA
2 140569           140569               NA               NA
3 136529           136529           136529           136529
4 143112           143112           143112           143112
5 108087           108087               NA               NA
6 142761           142761               NA               NA
  Y2017.2018_Term3 ever_AP
1     NA           FALSE
2     NA           FALSE
3 136529           FALSE
4 143112           FALSE
5     NA           FALSE
6     NA           FALSE

# Split cohorts, rename to Year7-11 and rejoin

In [4]:
cohort1 <- raw_data |>
    filter(cohort == '2000/01') |>
    select(-c(Y2017.2018_Term1, Y2017.2018_Term2, Y2017.2018_Term3)) |>
    rename(
        Year7_Term1 = Y2012.2013_Term1,
        Year7_Term2 = Y2012.2013_Term2,
        Year7_Term3 = Y2012.2013_Term3,
        Year8_Term1 = Y2013.2014_Term1,
        Year8_Term2 = Y2013.2014_Term2,
        Year8_Term3 = Y2013.2014_Term3,
        Year9_Term1 = Y2014.2015_Term1,
        Year9_Term2 = Y2014.2015_Term2,
        Year9_Term3 = Y2014.2015_Term3,
        Year10_Term1 = Y2015.2016_Term1,
        Year10_Term2 = Y2015.2016_Term2,
        Year10_Term3 = Y2015.2016_Term3,
        Year11_Term1 = Y2016.2017_Term1,
        Year11_Term2 = Y2016.2017_Term2,
        Year11_Term3 = Y2016.2017_Term3
        )

In [5]:
head(cohort1)

  cohort  person_id
1 2000/01 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2 2000/01 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
3 2000/01 00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66
4 2000/01 0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D
5 2000/01 001B7CEB7B4CC529920A0B9F5B83D1AC0019E5DC44B3FBB3CEF665C331C0C3B6
6 2000/01 001E539C263734CC355646811C93CF85B0C587D2EBA8B0D79290FDE8A75D6267
  DOB        Gender Ethnicity     EAL ever_FSM ever_CIN DistCurrSch DistNearSch
1 2001-05-15 M      White British 0   0        FALSE    0.66        0.66
2 2001-01-15 F      White British 0   0         TRUE    3.50        0.62
3 2000-11-15 M      South Asian   1   0        FALSE    1.69        0.44
4 2001-04-15 F      White British 0   0        FALSE    1.12        0.62
5 2001-05-15 M      White British 0   0        FALSE    1.56        1.56
6 2000-10-15 M      White British 0   0        FALSE    1.79        1.56
  ⋯ Year9_Term1 Year9_Term2 Year9_Term3 Year10_Term1 Year10_Term2 Year10_Term3
1 ⋯ 107442      107442      107442      107442       107442       107442
2 ⋯ 140569      140569      140569      140569       140569       140569
3 ⋯ 108087      108087      108087      108087       108087       108087
4 ⋯ 107366      107366      107366      107366       107366       107366
5 ⋯ 107395      107395      107395      107395       107395       107395
6 ⋯ 107439      107439      107439      107439       107439       107439
  Year11_Term1 Year11_Term2 Year11_Term3 ever_AP
1 143114       143114       143114       FALSE
2 140569       140569       140569       FALSE
3 108087       108087       108087       FALSE
4 142761       142761       142761       FALSE
5 107395       107395       107395       FALSE
6 107439       107439       107439       FALSE

In [6]:
cohort2 <- raw_data |>
    filter(cohort == '2001/02') |>
    select(-c(Y2012.2013_Term1, Y2012.2013_Term2, Y2012.2013_Term3)) |>
    rename(
        Year7_Term1 = Y2013.2014_Term1,
        Year7_Term2 = Y2013.2014_Term2,
        Year7_Term3 = Y2013.2014_Term3,
        Year8_Term1 = Y2014.2015_Term1,
        Year8_Term2 = Y2014.2015_Term2,
        Year8_Term3 = Y2014.2015_Term3,
        Year9_Term1 = Y2015.2016_Term1,
        Year9_Term2 = Y2015.2016_Term2,
        Year9_Term3 = Y2015.2016_Term3,
        Year10_Term1 = Y2016.2017_Term1,
        Year10_Term2 = Y2016.2017_Term2,
        Year10_Term3 = Y2016.2017_Term3,
        Year11_Term1 = Y2017.2018_Term1,
        Year11_Term2 = Y2017.2018_Term2,
        Year11_Term3 = Y2017.2018_Term3
        )

In [7]:
head(cohort2)

  cohort  person_id
1 2001/02 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D
2 2001/02 0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7
3 2001/02 0018E26A40A6299391164D4918658B0B1248367C762DCE6D2FDF1AE131A9138C
4 2001/02 0019031CD62586D59268772800516ED50CDF1EF7DE46488542BB031850F6E68A
5 2001/02 001E5C1FFA964716BF5E84562BC0B5D64F7742B1E8126718A5C0157D485F215D
6 2001/02 001F566795F57F5D8DD92430D868A38B757699844E3E09569B33253527012932
  DOB        Gender Ethnicity     EAL ever_FSM ever_CIN DistCurrSch DistNearSch
1 2001-11-15 M      White British 0   1         TRUE    7.01        0.00
2 2002-05-15 M      Other         1   0        FALSE    0.57        0.57
3 2002-07-15 M      South Asian   1   1        FALSE    0.15        0.15
4 2001-12-15 F      Other         1   1         TRUE    0.57        0.57
5 2002-04-15 M      White British 0   0        FALSE    3.60        3.60
6 2002-06-15 M      White British 0   0        FALSE    0.29        0.29
  ⋯ Year9_Term1 Year9_Term2 Year9_Term3 Year10_Term1 Year10_Term2 Year10_Term3
1 ⋯ 136529      136529      136529      136529       136529       136529
2 ⋯ 107441      107441      107441      143112       143112       143112
3 ⋯ 139474      139474      139474      139474       139474       139474
4 ⋯ 139982      139982      139982      139982       139982       139982
5 ⋯ 136905      136905      136905      136905       136905       136905
6 ⋯ 107440      107440      107440      107440       107440       107440
  Year11_Term1 Year11_Term2 Year11_Term3 ever_AP
1 136529       136529       136529       FALSE
2 143112       143112       143112       FALSE
3 139474       139474       139474       FALSE
4 139982       139982       139982       FALSE
5 136905       136905       136905       FALSE
6 107440       107440       107440       FALSE

In [8]:
data <- rbind(cohort1,cohort2)

In [9]:
data

      cohort  person_id
1     2000/01 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2     2000/01 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
3     2000/01 00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66
4     2000/01 0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D
5     2000/01 001B7CEB7B4CC529920A0B9F5B83D1AC0019E5DC44B3FBB3CEF665C331C0C3B6
6     2000/01 001E539C263734CC355646811C93CF85B0C587D2EBA8B0D79290FDE8A75D6267
7     2000/01 00222373A6082CDBF94DA04F23E7EB4C8775BEE122FE9C29FBF521900A498EDF
8     2000/01 002E041C5100C46E33B8A0C0220BDE85A79111C5D0E26742F6278C059930FAF6
9     2000/01 003132A725233755576CF96E5AA2B3DF606A618754D4BDDFCDD5483849E7B946
10    2000/01 0037AB0369C14AD5CA0340E2DFDAE2FFF22062A44A7889743C152A8163C08500
11    2000/01 003D2F5BDBC025915EE2AA9CCB96F54F72F003BF7DC6939849ADD6CCD1048ABC
12    2000/01 004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
13    2000/01 005087BCA7BEC31B79A3CA446453131C51CD1DC3296FE71B509E46AA984FFAE3
14    2000/01 0054192801954D860BB235F844AD1CB8A99956B2CF3D4E20F83C650DD6279B58
15    2000/01 0059AC822384B93661D2AB87E93EA6AB0847122FA139A080070E86A2F6A1910E
16    2000/01 005F4B5837E7E247A9A2A7A1F750EAF2B7E33ADD839287A9A654E5DEEE3657FB
17    2000/01 00650796D5BA76B502DD9A678C2B073B9C5F8F3ECC632A169825DA5EBDE0157F
18    2000/01 00658204F81C7F5F3D2809EC70DAFF7A6257E36E3773C7E1B757860069B2814E
19    2000/01 006E0488743F715599D4A1482A181A502F0951B7E75A5938B16F6654CD21F478
20    2000/01 006E3883AF0261A8C303A137715C7DD62949D75FFD52F75536E0B79CECCC90E0
21    2000/01 006E9437536191621258B883B68946C2B0D85A0161B4CC2FE397CDE1FC1034FA
22    2000/01 0071A44F79A6377921D0EFCB10710FD457794982D10B9E23BA524A609195712A
23    2000/01 00748B650176730AAF7158DCC2B2B974C8EB08D2BE8195BBD107F3B670619625
24    2000/01 007688F524D055BB6356EC8D2161248522BB499E6B146E91078F67F188ECD2C1
25    2000/01 0086479B32394EF4A752A53E24AC300B0579C1036E0256EC19C4E64FD02AE068
26    2000/01 008BBE3A231ACCDB36E882A8A9165417CE3F92351CB7DAE165A284C2DFBBC9B2
27    2000/01 0090D6AD92BC8EB88E772F5FBBAF7105DB294A19F6857D337505D1290D7D2419
28    2000/01 00928AA3ABFCEC55A9FD4BCC1CDFB582C6EFBDDB8F69E2AA1860BC1BA2461244
29    2000/01 0092DC69D7FF24E57AEAA4DDBA6450BBEB1FE4A15DAD25E3A7DCB714FE23E315
30    2000/01 00984270C3D5F57B15FBB33EE849BA97F72C4F732D031E981D2C43395F4E5098
⋮     ⋮       ⋮
17195 2001/02 FEFEE4203EF2177115F364C173E81DFB7ED86879326EECBBF4813E38F7F9BC8A
17196 2001/02 FF03BF1E2A039BA8F118AAEAFD1C757D3138A5551B470C270153829139565DD2
17197 2001/02 FF0C3CB098A1EFF36CC03C8C36B23D0C8D1AB0747753ACE9EC6065CD482408B8
17198 2001/02 FF10DCDDB38F2AD2DC8767DFC62670F389828158BCEC5C1E7D793E4614AD1445
17199 2001/02 FF11DE64C6C96030A4E276362D2DF6E4695045FFFC78543F75B7FD9CAA0E95E4
17200 2001/02 FF15B543AF51E53917F1E8ECBFED9707195B3316312F04E02B9438BB7BBED9FA
17201 2001/02 FF166F1349783175407313E35C3E20105BB7BFACC3680798961FE9C9B8E41FA7
17202 2001/02 FF1C8BA4C2D9C4E2DB2B64F092A16C70846232BDF5D18827114B1F40D1A4CEA3
17203 2001/02 FF35E0916282ECC5BFC997AB1F6866B5289FA0C95838F318AAD4EFCF4A04D87F
17204 2001/02 FF3752BEEFF14D8C9F4DAF38DD5806E47CFD4A1F51CADCA375E885EE3D6CF5E2
17205 2001/02 FF40E206271C27C81CBC640537EBD223DA63168EFE943D7A0352F840B8BC79BC
17206 2001/02 FF40EFF70112B4162DB955BC8B70FF0763F2A509B0D8C67F5B3CC39E60EFDFCB
17207 2001/02 FF492AB1F9A7DFDFA90FAA075071B978780CFFDD64435E5CC205803A33A48BB3
17208 2001/02 FF5A6E829A11E32FE9B98382A4A4EDA7AFC7D45C48A181666899DC62A282D688
17209 2001/02 FF61F463A80412127350F171EAFFCA827D736DCF065D99769CC0E6AD72DBAD47
17210 2001/02 FF63250D160E943CD3B77C5060A163DF69CE5AB3E0F3FA317DFA8B524079E6AE
17211 2001/02 FF77AAB58760E4616819BF69FA7A7D0466EC940FC1B666F5D8FC15261B05FDA7
17212 2001/02 FF85FB47EF271836ECDF7555602263FC0E52F8A84F39868EE7B66E30E47DF618
17213 2001/02 FF9024B3D2775BB5CC65F8872CB1A8BECAD9A7E25FBB3C3DF7D46A8A1BE31AC1
17214 2001/02 FF94D3F7FDB40C124787D0EBA0CD7660187135442D800F18C11487D380F55663
17215 2001/02 FFAA13CCE7B35BA3D3A737EF1A13BCE2289A94F9778EC0C9F18CD77F1B93C979
17216 2001/02 FFBCE0C32A37E3663F1C5159ECFC6F08CD5722E938464A58634F3263003F1D9F
17217 2001/02 FFC0379FDA559C1337454C579FF36F9AE82E62D16B3223D009C57DEC3731754C
17218 2001/02 FFC7129859DD885141E316248A0EB23059DB0F0DB98242C34C67F06FBBAB8041
17219 2001/02 FFC96F346EC6829E7A31F60109FD729DE208D180104B50FC8B1BFAD552D6C8FC
17220 2001/02 FFD391941F3AA9CB910FFFACF24CC2CEAD0BC63EED146E9C21B2C71BA77B084A
17221 2001/02 FFEA068077E4464D059236951F07D7DF96542C2197AAFAC3E20C036BACB9825C
17222 2001/02 FFFA6705A275195BFE8A443AF0BD2AA86B1AA0481D330D8665813206EB8DAD43
17223 2001/02 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77
17224 2001/02 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
      DOB        Gender Ethnicity     EAL ever_FSM ever_CIN DistCurrSch
1     2001-05-15 M      White British  0   0       FALSE    0.66
2     2001-01-15 F      White British  0   0        TRUE    3.50
3     2000-11-15 M      South Asian    1   0       FALSE    1.69
4     2001-04-15 F      White British  0   0       FALSE    1.12
5     2001-05-15 M      White British  0   0       FALSE    1.56
6     2000-10-15 M      White British  0   0       FALSE    1.79
7     2000-11-15 F      South Asian    1   0       FALSE    2.52
8     2000-12-15 M      South Asian    0   1       FALSE    1.60
9     2001-07-15 M      White British  0   1       FALSE    0.33
10    2000-09-15 M      White British  0   0       FALSE    1.04
11    2001-05-15 M      Other          1  NA       FALSE    1.81
12    2001-01-15 F      White British  0   1        TRUE    1.81
13    2001-04-15 F      White British NA   0       FALSE      NA
14    2000-11-15 F      South Asian    1   1        TRUE    1.08
15    2001-04-15 F      White British  0   0       FALSE    0.72
16    2000-09-15 F      White British  0   1       FALSE    2.41
17    2000-11-15 M      South Asian    0   1       FALSE    0.51
18    2001-04-15 M      White British  0   0       FALSE    2.28
19    2000-11-15 M      White British  0   0       FALSE    1.77
20    2001-07-15 M      South Asian    1   0       FALSE    1.27
21    2001-01-15 F      White British  0   1        TRUE    5.36
22    2000-11-15 F      White British  0   0       FALSE    0.29
23    2001-05-15 F      Other          0   1        TRUE    3.96
24    2001-05-15 M      White British  0   0       FALSE    1.93
25    2001-01-15 M      White British  0   1        TRUE    1.58
26    2000-12-15 M      Other          1   0       FALSE    2.65
27    2001-01-15 F      Other          1   1        TRUE    1.90
28    2000-10-15 M      South Asian    0   0       FALSE    2.40
29    2000-10-15 M      South Asian    1   0       FALSE    2.39
30    2001-03-15 M      White British  0   0       FALSE    4.13
⋮     ⋮          ⋮      ⋮             ⋮   ⋮        ⋮        ⋮
17195 2002-06-15 F      South Asian   1   0        FALSE    0.18
17196 2002-01-15 M      South Asian   1   0        FALSE    1.01
17197 2001-12-15 M      White British 0   0         TRUE    2.27
17198 2001-10-15 F      Other         0   1         TRUE    0.40
17199 2002-04-15 F      South Asian   1   0         TRUE    0.78
17200 2002-03-15 M      White British 0   1        FALSE    2.38
17201 2001-09-15 F      South Asian   1   0        FALSE    5.01
17202 2002-08-15 F      White British 0   0        FALSE    1.02
17203 2002-05-15 F      South Asian   1   1         TRUE    0.62
17204 2001-12-15 F      White British 0   1        FALSE    2.26
17205 2002-02-15 M      Other         0   1         TRUE    2.39
17206 2001-09-15 M      White British 0   1         TRUE    0.28
17207 2002-05-15 M      South Asian   0   0        FALSE    3.65
17208 2002-02-15 M      South Asian   1   0        FALSE    2.05
17209 2002-04-15 M      Other         0   0        FALSE    0.70
17210 2002-08-15 F      South Asian   0   0         TRUE    0.39
17211 2002-04-15 F      White British 0   1         TRUE    0.62
17212 2002-06-15 M      White British 0   1        FALSE    2.82
17213 2002-08-15 M      White British 0   0         TRUE    6.71
17214 2002-05-15 F      Other         0   0        FALSE    0.73
17215 2001-10-15 F      Other         1   0        FALSE    1.04
17216 2001-10-15 F      South Asian   1   1        FALSE    3.29
17217 2001-09-15 M      South Asian   1   0        FALSE    1.01
17218 2002-07-15 F      South Asian   1   0        FALSE    0.91
17219 2002-05-15 M      South Asian   1   1        FALSE    1.08
17220 2002-08-15 M      White British 0   1         TRUE    0.11
17221 2001-10-15 M      White British 0   0        FALSE    0.69
17222 2002-07-15 F      White British 0   0        FALSE    0.98
17223 2002-05-15 M      White British 0   0        FALSE    1.23
17224 2002-01-15 F      White British 0   1        FALSE    0.19
      DistNearSch ⋯ Year9_Term1 Year9_Term2 Year9_Term3 Year10_Term1
1     0.66        ⋯ 107442      107442      107442      107442
2     0.62        ⋯ 140569      140569      140569      140569
3     0.44        ⋯ 108087      108087      108087      108087
4     0.62        ⋯ 107366      107366      107366      107366
5     1.56        ⋯ 107395      107395      107395      107395
6     1.56        ⋯ 107439      107439      107439      107439
7     0.61        ⋯ 107391      107391      107391      107391
8     0.21        ⋯ 130909      130909      130909      130909
9     0.33        ⋯ 107441      107441      107441      107441
10    1.04        ⋯ 107395      107395      107395      107395
11    0.98        ⋯     NA          NA          NA          NA
12    0.30        ⋯ 107428      107428      107428      107428
13      NA        ⋯     NA          NA          NA          NA
14    0.78        ⋯ 107413      107413      107413      107413
15    0.72        ⋯ 107562      107562      107562      107562
16    0.41        ⋯ 135935      135935      135935      135935
17    0.51        ⋯ 135881      135881      135881      135881
18    0.35        ⋯ 107395      107395      107395      107395
19    1.77        ⋯ 121716      121716      121716      121716
20    0.50        ⋯ 107361      107361      107361      142031
21    5.36        ⋯ 121689      121689      121689      121689
22    0.29        ⋯ 107440      107440      107440      107440
23    0.58        ⋯ 138087      138087      138087      138087
24    1.93        ⋯ 121690      121690      121690      121690
25    1.58        ⋯     NA          NA          NA          NA
26    0.56        ⋯ 135865      135865      135865      135865
27    0.58        ⋯ 108055      108055      108055      108055
28    0.60        ⋯ 107395      107395      107395      107395
29    0.22        ⋯ 108087      108087      108087      108087
30    0.38        ⋯ 132219      132219      132219      132219
⋮     ⋮           ⋱ ⋮           ⋮           ⋮           ⋮
17195 0.18        ⋯ 107413      107413      107413      107413
17196 0.48        ⋯ 135367      135367      135367      135367
17197 1.52        ⋯ 132217      132217      132217      132217
17198 0.40        ⋯ 107442      107442      107442      143114
17199 0.15        ⋯ 138370      138370      138370      138370
17200 2.38        ⋯ 136736      136736      136736      136736
17201 0.66        ⋯ 138087      138087      138087      138087
17202 1.02        ⋯ 107350      107350      107350      142825
17203 0.62        ⋯ 107442      107442      107442      143114
17204 0.58        ⋯ 107350      107350      107350      142825
17205 0.65        ⋯ 107413      107413      107413      107413
17206 0.28        ⋯ 118082      118082      118082      118082
17207 0.68        ⋯ 136788      136788      136788      136788
17208 0.74        ⋯ 107413      107413      107413      107413
17209 0.70        ⋯ 132219      132219      132219      142590
17210 0.39        ⋯ 135866      135866      135866      105560
17211 0.62        ⋯ 107350      107350      107350      142825
17212 1.09        ⋯ 135865      135865      135865      135865
17213 0.66        ⋯ 137497      137497      137497      137497
17214 0.73        ⋯ 136905      136905      136905      136905
17215 0.46        ⋯ 139982      139982      139982      139982
17216 0.36        ⋯ 137277      137277      137277      137277
17217 0.68        ⋯ 135866      135866      135866      135866
17218 0.80        ⋯ 137277      137277      137277      137277
17219 0.39        ⋯ 135367      135367      135367      135367
17220 0.11        ⋯ 107440      107440      107440      107440
17221 0.69        ⋯ 132219      132219      132219      142590
17222 0.98        ⋯ 135865      135865      135865      135865
17223 1.23        ⋯ 136736      136736      136736      136736
17224 0.19        ⋯ 107350      107350      107350      142825
      Year10_Term2 Year10_Term3 Year11_Term1 Year11_Term2 Year11_Term3 ever_AP
1     107442       107442       143114       143114       143114       FALSE
2     140569       140569       140569       140569       140569       FALSE
3     108087       108087       108087       108087       108087       FALSE
4     107366       107366       142761       142761       142761       FALSE
5     107395       107395       107395       107395       107395       FALSE
6     107439       107439       107439       107439       107439       FALSE
7     107391       107391       143113       143113       143113       FALSE
8     130909       130909       130909       130909       130909       FALSE
9     107441       107441       143112       143112       143112       FALSE
10    107395       107395       107395       107395       107395       FALSE
11        NA           NA       137177       137177       137177       FALSE
12    107428       107428       107428       107428       107428        TRUE
13        NA           NA           NA           NA           NA       FALSE
14    107413       107413       107413       107413       107413       FALSE
15    107562       107562       107562       107562       107562       FALSE
16    135935       135935       135935       135935       135935       FALSE
17    135881       135881       135881       135881       135881       FALSE
18    107395       107395       107395       107395       107395       FALSE
19    121716       121716       121716       121716       121716       FALSE
20    142031       142031       142031       142031       142031       FALSE
21    121689       121689       121689       121689       121689       FALSE
22    107440       107440       107440       107440       107440       FALSE
23    138087       138087       138087       138087       138087       FALSE
24    121690       121690       121690       121690       121690       FALSE
25        NA           NA           NA           NA           NA       FALSE
26    135865       135865       135865       135865       135865       FALSE
27    108055       108055       108055       108055       108055       FALSE
28    107395       107395       107395       107395       107395       FALSE
29    108087       108087       108087       108087       108087       FALSE
30    132219       139975       139975       139975       139975       FALSE
⋮     ⋮            ⋮            ⋮            ⋮            ⋮            ⋮
17195 107413       107413       107413       107413       107413       FALSE
17196 135367       135367       135367       135367       135367       FALSE
17197 132217       132217       132217       132217       132217       FALSE
17198 143114       143114       143114       143114       143114       FALSE
17199 138370       138370       139995       139995       139995       FALSE
17200 136736       136736       136736       136736       136736       FALSE
17201 138087       138087       138087       138087       138087       FALSE
17202 142825       142825       142825       142825       142825       FALSE
17203 143114       143114       143114       143114       143114       FALSE
17204 142825       142825       142825       142825       142825       FALSE
17205 107413       107413       135732       135732       135732        TRUE
17206 118082       118082       118082       118082       118082       FALSE
17207 136788       136788       136788       136788       136788       FALSE
17208 107413       107413       107413       107413       107413       FALSE
17209 142590       142590       142590       142590       142590       FALSE
17210 105560       105560       105560       105560       105560       FALSE
17211 142825       142825       142825       142825       130980        TRUE
17212 135865       135865       145173       145173       145173       FALSE
17213 137497       137497       137497       137497       137497        TRUE
17214 136905       136905       136905       136905       136905       FALSE
17215 139982       139982       139982       139982       139982       FALSE
17216 137277       137277       137277       137277       137277       FALSE
17217 135866       135866       135866       135866       135866       FALSE
17218 137277       137277       137277       137277       137277       FALSE
17219 135367       135367       135367       135367       135367       FALSE
17220 107440       107440       107440       107440       107440       FALSE
17221 142590       142590       142590       142590       142590       FALSE
17222 135865       135865       145173       145173       145173       FALSE
17223 136736       136736       136736       136736       136736       FALSE
17224 142825       142825       142825       142825       142825       FALSE

# Missing data

In [10]:
data |> summarise(across(everything(), ~ sum(is.na(.))))

  cohort person_id DOB Gender Ethnicity EAL ever_FSM ever_CIN DistCurrSch
1 0      0         0   3      42        288 215      0        325
  DistNearSch ⋯ Year9_Term1 Year9_Term2 Year9_Term3 Year10_Term1 Year10_Term2
1 675         ⋯ 656         656         656         636          636
  Year10_Term3 Year11_Term1 Year11_Term2 Year11_Term3 ever_AP
1 636          729          729          729          0

In [11]:
colSums(is.na(data))

                 cohort               person_id                     DOB
                      0                       0                       0
                 Gender               Ethnicity                     EAL
                      3                      42                     288
               ever_FSM                ever_CIN             DistCurrSch
                    215                       0                     325
            DistNearSch             LSOA11_Home                   IDACI
                    675                     293                      79
       ever_SEN_support  first_SEN_support_year        SEN_support_need
                      0                    9798                    9798
          ever_EHC_plan     first_EHC_plan_year           EHC_plan_need
                      0                   16607                   16607
                 no_SEN   AuthorisedAbsenceRate UnauthorisedAbsenceRate
                      0                       0                       0
       TotalAbsenceRate             Suspensions      SuspensionSessions
                      0                       0                       0
             Exclusions             KS4_Entries       KS4_Passes_Level1
                      0                     415                     415
      KS4_Passes_Level2             Destination             Year7_Term1
                    415                       0                    1029
            Year7_Term2             Year7_Term3             Year8_Term1
                   1029                    1029                     802
            Year8_Term2             Year8_Term3             Year9_Term1
                    802                     802                     656
            Year9_Term2             Year9_Term3            Year10_Term1
                    656                     656                     636
           Year10_Term2            Year10_Term3            Year11_Term1
                    636                     636                     729
           Year11_Term2            Year11_Term3                 ever_AP
                    729                     729                       0

263 students with all NAs for school 
- 38 labelled DROP
- 17 risky
- 208 steady eet

415 students with no KS4 data 
- 36 labelled DROP
- 144 risky
- 235 steady eet

- N = 17,224
- drop DROP: n = 16,956
- drop all NAs for school: n = 16,731
- drop NA for KS4 entries: n = 16,390
- drop NA for ever FSM: n = 16,285

In [12]:
data_drop_missing <- data |>
    filter(
        Destination != 'DROP',
        !if_all(c(
                Year7_Term1, Year7_Term2, Year7_Term3,
                Year8_Term1, Year8_Term2, Year8_Term3,
                Year9_Term1, Year9_Term2, Year9_Term3,
                Year10_Term1, Year10_Term2, Year10_Term3,
                Year11_Term1, Year11_Term2, Year11_Term3
                ), is.na),
        !is.na(KS4_Entries)
        )

In [13]:
colSums(is.na(data_drop_missing))

                 cohort               person_id                     DOB
                      0                       0                       0
                 Gender               Ethnicity                     EAL
                      3                      42                       3
               ever_FSM                ever_CIN             DistCurrSch
                    105                       0                      21
            DistNearSch             LSOA11_Home                   IDACI
                    355                       6                       0
       ever_SEN_support  first_SEN_support_year        SEN_support_need
                      0                    9351                    9351
          ever_EHC_plan     first_EHC_plan_year           EHC_plan_need
                      0                   15816                   15816
                 no_SEN   AuthorisedAbsenceRate UnauthorisedAbsenceRate
                      0                       0                       0
       TotalAbsenceRate             Suspensions      SuspensionSessions
                      0                       0                       0
             Exclusions             KS4_Entries       KS4_Passes_Level1
                      0                       0                       0
      KS4_Passes_Level2             Destination             Year7_Term1
                      0                       0                     673
            Year7_Term2             Year7_Term3             Year8_Term1
                    673                     673                     447
            Year8_Term2             Year8_Term3             Year9_Term1
                    447                     447                     298
            Year9_Term2             Year9_Term3            Year10_Term1
                    298                     298                     230
           Year10_Term2            Year10_Term3            Year11_Term1
                    230                     230                     241
           Year11_Term2            Year11_Term3                 ever_AP
                    241                     241                       0

#### Replace svchool NAs with 111111

In [14]:
data_drop_missing <- data_drop_missing |>
    mutate(across(c(Year7_Term1, Year7_Term2, Year7_Term3,
                Year8_Term1, Year8_Term2, Year8_Term3,
                Year9_Term1, Year9_Term2, Year9_Term3,
                Year10_Term1, Year10_Term2, Year10_Term3,
                Year11_Term1, Year11_Term2, Year11_Term3),
                ~ replace_na(., 111111)))

In [15]:
#data_drop_missing <- data_drop_missing |>
#    filter(!is.na(ever_FSM))

In [16]:
head(data_drop_missing)

  cohort  person_id
1 2000/01 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2 2000/01 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
3 2000/01 00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66
4 2000/01 0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D
5 2000/01 001B7CEB7B4CC529920A0B9F5B83D1AC0019E5DC44B3FBB3CEF665C331C0C3B6
6 2000/01 001E539C263734CC355646811C93CF85B0C587D2EBA8B0D79290FDE8A75D6267
  DOB        Gender Ethnicity     EAL ever_FSM ever_CIN DistCurrSch DistNearSch
1 2001-05-15 M      White British 0   0        FALSE    0.66        0.66
2 2001-01-15 F      White British 0   0         TRUE    3.50        0.62
3 2000-11-15 M      South Asian   1   0        FALSE    1.69        0.44
4 2001-04-15 F      White British 0   0        FALSE    1.12        0.62
5 2001-05-15 M      White British 0   0        FALSE    1.56        1.56
6 2000-10-15 M      White British 0   0        FALSE    1.79        1.56
  ⋯ Year9_Term1 Year9_Term2 Year9_Term3 Year10_Term1 Year10_Term2 Year10_Term3
1 ⋯ 107442      107442      107442      107442       107442       107442
2 ⋯ 140569      140569      140569      140569       140569       140569
3 ⋯ 108087      108087      108087      108087       108087       108087
4 ⋯ 107366      107366      107366      107366       107366       107366
5 ⋯ 107395      107395      107395      107395       107395       107395
6 ⋯ 107439      107439      107439      107439       107439       107439
  Year11_Term1 Year11_Term2 Year11_Term3 ever_AP
1 143114       143114       143114       FALSE
2 140569       140569       140569       FALSE
3 108087       108087       108087       FALSE
4 142761       142761       142761       FALSE
5 107395       107395       107395       FALSE
6 107439       107439       107439       FALSE

# Simplified dataset

In [17]:
data_simple <- data_drop_missing |>
    mutate(Highest_SEN_level = case_when (
            no_SEN ~ 'No SEN', 
            ever_SEN_support & !ever_EHC_plan ~ 'SEN Support',
            ever_EHC_plan ~ 'EHC Plan'
        ))

In [18]:
data_simple <- data_simple |>
    select(-c(ever_SEN_support,first_SEN_support_year,SEN_support_need,ever_EHC_plan,first_EHC_plan_year,EHC_plan_need,no_SEN, 
              DistNearSch))

In [19]:
head(data_simple)

  cohort  person_id
1 2000/01 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2 2000/01 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
3 2000/01 00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66
4 2000/01 0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D
5 2000/01 001B7CEB7B4CC529920A0B9F5B83D1AC0019E5DC44B3FBB3CEF665C331C0C3B6
6 2000/01 001E539C263734CC355646811C93CF85B0C587D2EBA8B0D79290FDE8A75D6267
  DOB        Gender Ethnicity     EAL ever_FSM ever_CIN DistCurrSch LSOA11_Home
1 2001-05-15 M      White British 0   0        FALSE    0.66        E01010635
2 2001-01-15 F      White British 0   0         TRUE    3.50        E01010749
3 2000-11-15 M      South Asian   1   0        FALSE    1.69        E01010610
4 2001-04-15 F      White British 0   0        FALSE    1.12        E01010815
5 2001-05-15 M      White British 0   0        FALSE    1.56        E01010575
6 2000-10-15 M      White British 0   0        FALSE    1.79        E01010704
  ⋯ Year9_Term2 Year9_Term3 Year10_Term1 Year10_Term2 Year10_Term3 Year11_Term1
1 ⋯ 107442      107442      107442       107442       107442       143114
2 ⋯ 140569      140569      140569       140569       140569       140569
3 ⋯ 108087      108087      108087       108087       108087       108087
4 ⋯ 107366      107366      107366       107366       107366       142761
5 ⋯ 107395      107395      107395       107395       107395       107395
6 ⋯ 107439      107439      107439       107439       107439       107439
  Year11_Term2 Year11_Term3 ever_AP Highest_SEN_level
1 143114       143114       FALSE   SEN Support
2 140569       140569       FALSE   SEN Support
3 108087       108087       FALSE   No SEN
4 142761       142761       FALSE   SEN Support
5 107395       107395       FALSE   No SEN
6 107439       107439       FALSE   SEN Support

# Save CSVs

In [20]:
# save as csv
write.csv(data, "data/data_EA.csv", row.names = FALSE)

In [21]:
# save as csv
write.csv(data_drop_missing, "data/data_EA_noNA.csv", row.names = FALSE)

In [22]:
# save as csv
write.csv(data_simple, "data/data_simple.csv", row.names = FALSE)