In [1]:
library(tidyverse)
library(dbplyr)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘dbplyr’


The following objects are masked from ‘package:dplyr’:

    ident, sql

In [2]:
raw_data <- read.csv("data/additional_full_data.csv", header = TRUE)

In [3]:
head(raw_data)

  cohort  person_id
1 1999/00 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
2 1998/99 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
3 1998/99 000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909
4 1999/00 00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC
5 1999/00 0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
6 1999/00 00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7
  DOB        Gender Ethnicity     EAL ever_FSM ever_CIN DistCurrSch LSOA11_Home
1 1999-09-15 F      White British 0   0        FALSE    2.45        E01027555
2 1999-08-15 F      White British 0   0        FALSE    4.71        E01010703
3 1998-11-15 M      South Asian   0   0        FALSE    0.33        E01010742
4 2000-05-15 M      White British 0   0        FALSE    1.78        E01010641
5 2000-08-15 F      White British 0   1        FALSE    0.76        E01010655
6 1999-09-15 M      South Asian   0   1         TRUE    1.29        E01010626
  ⋯ Y2014.2015_Term1 Y2014.2015_Term2 Y2014.2015_Term3 Y2015.2016_Term1
1 ⋯ 136664           136664           136664           136664
2 ⋯ 136736           136736           136736               NA
3 ⋯ 130909           130909           130909               NA
4 ⋯ 136736           136736           136736           136736
5 ⋯ 107440           107440           107440           107440
6 ⋯ 108087           108087           108087           108087
  Y2015.2016_Term2 Y2015.2016_Term3 Y2010.2011_Term1 Y2010.2011_Term2
1 136664           136664               NA               NA
2     NA               NA           136736           136736
3     NA               NA           130909           130909
4 136736           136736               NA               NA
5 107440           107440               NA               NA
6 108087           108087               NA               NA
  Y2010.2011_Term3 ever_AP
1     NA           FALSE
2 136736           FALSE
3 130909           FALSE
4     NA           FALSE
5     NA           FALSE
6     NA           FALSE

# Split cohorts, rename to Year7-11 and rejoin

In [4]:
cohort1 <- raw_data |>
    filter(cohort == '1998/99') |>
    select(-c(Y2015.2016_Term1, Y2015.2016_Term2, Y2015.2016_Term3)) |>
    rename(
        Year7_Term1 = Y2010.2011_Term1,
        Year7_Term2 = Y2010.2011_Term2,
        Year7_Term3 = Y2010.2011_Term3,
        Year8_Term1 = Y2011.2012_Term1,
        Year8_Term2 = Y2011.2012_Term2,
        Year8_Term3 = Y2011.2012_Term3,
        Year9_Term1 = Y2012.2013_Term1,
        Year9_Term2 = Y2012.2013_Term2,
        Year9_Term3 = Y2012.2013_Term3,
        Year10_Term1 = Y2013.2014_Term1,
        Year10_Term2 = Y2013.2014_Term2,
        Year10_Term3 = Y2013.2014_Term3,
        Year11_Term1 = Y2014.2015_Term1,
        Year11_Term2 = Y2014.2015_Term2,
        Year11_Term3 = Y2014.2015_Term3
        )

In [5]:
head(cohort1)

  cohort  person_id
1 1998/99 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
2 1998/99 000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909
3 1998/99 001F42538A9E6E496F13CD05B5E9FE91EB3B20F0CEBECA1B76CC5E7151B7A0D4
4 1998/99 00211975518FD5336E43850D59B5F5DDA7CD98B212760111CB40528BDECF3B1B
5 1998/99 00237E9C21696BB29409630166F2D9CCEC24B83FB120AEDD878DDD54C6516B3D
6 1998/99 00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9
  DOB        Gender Ethnicity     EAL ever_FSM ever_CIN DistCurrSch LSOA11_Home
1 1999-08-15 F      White British 0   0        FALSE    4.71        E01010703
2 1998-11-15 M      South Asian   0   0        FALSE    0.33        E01010742
3 1999-01-15 F      South Asian   0   1         TRUE    1.37        E01010568
4 1998-10-15 M      White British 0   1         TRUE    4.27        E01010752
5 1999-03-15 M      White British 0   0        FALSE    0.10        E01027577
6 1999-07-15 F      Other         1   1         TRUE    2.74        E01010625
  ⋯ Year10_Term1 Year10_Term2 Year10_Term3 Year11_Term1 Year11_Term2
1 ⋯ 136736       136736       136736       136736       136736
2 ⋯ 130909       130909       130909       130909       130909
3 ⋯ 107395       107395       107395       107395       107395
4 ⋯ 135732       135732       135732       135732       135732
5 ⋯ 121716       121716       121716       121716       121716
6 ⋯ 107366       107366       107366       107366       107366
  Year11_Term3 Year7_Term1 Year7_Term2 Year7_Term3 ever_AP
1 136736       136736      136736      136736      FALSE
2 130909       130909      130909      130909      FALSE
3 107395       107395      107395      107395      FALSE
4 135732       107391      107391      107391       TRUE
5 121716       121716      121716      121716      FALSE
6 107366       132219      132219      132219      FALSE

In [6]:
cohort2 <- raw_data |>
    filter(cohort == '1999/00') |>
    select(-c(Y2010.2011_Term1, Y2010.2011_Term2, Y2010.2011_Term3)) |>
    rename(
        Year7_Term1 = Y2011.2012_Term1,
        Year7_Term2 = Y2011.2012_Term2,
        Year7_Term3 = Y2011.2012_Term3,
        Year8_Term1 = Y2012.2013_Term1,
        Year8_Term2 = Y2012.2013_Term2,
        Year8_Term3 = Y2012.2013_Term3,
        Year9_Term1 = Y2013.2014_Term1,
        Year9_Term2 = Y2013.2014_Term2,
        Year9_Term3 = Y2013.2014_Term3,
        Year10_Term1 = Y2014.2015_Term1,
        Year10_Term2 = Y2014.2015_Term2,
        Year10_Term3 = Y2014.2015_Term3,
        Year11_Term1 = Y2015.2016_Term1,
        Year11_Term2 = Y2015.2016_Term2,
        Year11_Term3 = Y2015.2016_Term3
        )

In [7]:
head(cohort2)

  cohort  person_id
1 1999/00 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
2 1999/00 00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC
3 1999/00 0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
4 1999/00 00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7
5 1999/00 0025514088C52FB45B7439689844A1FEA2FB8B2753994F432CC7DDC68036BD59
6 1999/00 00269FAEA8B5167F1239AA166C20B7673380CCB3E5F3E2F1F6FAA6034A11CE88
  DOB        Gender Ethnicity     EAL ever_FSM ever_CIN DistCurrSch LSOA11_Home
1 1999-09-15 F      White British 0   0        FALSE    2.45        E01027555
2 2000-05-15 M      White British 0   0        FALSE    1.78        E01010641
3 2000-08-15 F      White British 0   1        FALSE    0.76        E01010655
4 1999-09-15 M      South Asian   0   1         TRUE    1.29        E01010626
5 2000-04-15 M      South Asian   1   1        FALSE    1.13        E01010710
6 2000-01-15 M      Other         0   1        FALSE    1.23        E01011792
  ⋯ Year9_Term1 Year9_Term2 Year9_Term3 Year10_Term1 Year10_Term2 Year10_Term3
1 ⋯ 136664      136664      136664      136664       136664       136664
2 ⋯ 136736      136736      136736      136736       136736       136736
3 ⋯ 107440      107440      107440      107440       107440       107440
4 ⋯ 108087      108087      108087      108087       108087       108087
5 ⋯ 136198      136198      107441      107441       107441       107441
6 ⋯ 137001      137001      137001      137001       137001       137001
  Year11_Term1 Year11_Term2 Year11_Term3 ever_AP
1 136664       136664       136664       FALSE
2 136736       136736       136736       FALSE
3 107440       107440       107440       FALSE
4 108087       108087       108087       FALSE
5 107441       107441       107441       FALSE
6 137001       137001       137001       FALSE

In [8]:
data <- rbind(cohort1,cohort2)

In [9]:
data

      cohort  person_id
1     1998/99 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
2     1998/99 000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909
3     1998/99 001F42538A9E6E496F13CD05B5E9FE91EB3B20F0CEBECA1B76CC5E7151B7A0D4
4     1998/99 00211975518FD5336E43850D59B5F5DDA7CD98B212760111CB40528BDECF3B1B
5     1998/99 00237E9C21696BB29409630166F2D9CCEC24B83FB120AEDD878DDD54C6516B3D
6     1998/99 00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9
7     1998/99 0025102C0D8E8C5F27454E3715E982A43E1431991E85562E55BCB19D9D1BD7D3
8     1998/99 0026BFA5D5426F421200AB505AAD52956621DCC253241A6647302BCE4764547D
9     1998/99 002D3DB2625339C740EB129CCC925A9D90E4F5AA05561B81FE166EDF990B8F65
10    1998/99 002E7A9E65A6A184952E4F1811844FCFCCE758FAE60986A1F9B9C9892FD0895D
11    1998/99 003196BCDC325A98F118130F185DF8FDDE1B8E1E4882719DAE198B2908F03A5B
12    1998/99 0032202712FAB3A372409235FFE3C0486E36F9B2FB9C9C9851B4ACAB9A3330F0
13    1998/99 0043C7C252748432DF62E306CCC2DFF568A52DC78D4021140E3C4676C9D65A7E
14    1998/99 00450DFB52E0DDD50F5800AD149075B29E4A1454F36B9ACF2E106CF44B9BED55
15    1998/99 0045ADA48CA299BC4445318E8D951610DCB89A829665CFC821E92340F0F8B30D
16    1998/99 004FE0E78454FE677A07F1AD8D1226F61C6534E08B44EE01DC6C518FE2200DEA
17    1998/99 0050C79DAB376114E567D08BE22EA699565E600DFC9F3BD68705700FA49DE62C
18    1998/99 005F5FB87F7E1CE08012E08C6B8887E641C2597A119A5E71101F2D07D6BD1499
19    1998/99 006138BE2285A21040A8422B8BBCB90D56DDCB7ECB6623258AFAD0375F4E118A
20    1998/99 0064BF51F495220745AC025A50818B596BDDA2EDFECCF43CD076BB4F895B0E44
21    1998/99 00711A691CFC443674F7DFB014681E1F0C55DC8B9ED0E04E335A7A1B8FDF4F32
22    1998/99 00728E3D3C7714176088844EC230ED81D79E9093AE0742526C9EAF244DD42CFA
23    1998/99 007570ED5702694AEE71FBCA3ED93584AD7C19E06FE4CB64203ED8BE71B024EA
24    1998/99 0075A60FD7FBBCE1BB568F22433CF8A0CA476B94DE83350BFA3F3BDA07371037
25    1998/99 007AA0CA0759384F9FDE693D320070748A8AF12C75E32621E3CF0620E465A0FD
26    1998/99 007D0119A91376D27F773060F5E9C327CC61639E1F8F69E01FB48B14BCAE92AF
27    1998/99 0080DCC449A400C7BEB4A8FD7FBC453381B036E15F3F039EADAE9A1E4550767F
28    1998/99 009354452C32CB442E4EEE6DF777F1EA4756148684FD6E3F75EA15F5F0E28081
29    1998/99 0093549A2B3FB44847A7880014804DB333707601AE77A4AF949EE71E538194D6
30    1998/99 00A18746DA51B08EB5EE9ABA407D9C3F8E3C82B72E5E87B371C03A591F4591F5
⋮     ⋮       ⋮
17363 1999/00 FEA6B639240038A86C1D2DE0927341EE2D5D03BBA5CE917F62BBE38B4B670641
17364 1999/00 FEE0D9C83B8D233E9677B076561353322FC4A5F1B08D6B6AD86B3571D6AB1519
17365 1999/00 FEE6EDDDE3DB37C9B60CDADCBE98F529ACACC6822F46F04511A4A0B30FD14AFC
17366 1999/00 FEEDFFCAE9292727078D848894154DEB56C729761D2C5E73F08030FE152F7FFD
17367 1999/00 FEF5B0FD518EE30E8E31B92DD3E1DB1B1E8BC113206680430981FCF93D486DB2
17368 1999/00 FF06E43391A169D31F73C845378BF90233A6D6B380C2A00654C9B5F2958D8525
17369 1999/00 FF0E4F96548A1554A48EEB6E692699D9D511D2152C8E21BBDD82E26A97967B4A
17370 1999/00 FF106C916228AB739E21565248C82336C3F249E745BDA7A0ECCA52B0E2A85461
17371 1999/00 FF10D765BFC2E253329518ADD46EB52E91880C5E48A39E5E0EC11134AFDBFEEA
17372 1999/00 FF118754E06EC19AFDA6A8F6E5E91412C218678AC03DF587AA72EBDFC4903EFB
17373 1999/00 FF40E148D69ED95AD606C62996CBBB07ADFB248A79985F467D4A0AC2B53173DF
17374 1999/00 FF4BAE45489DDBBE149ECB9F0B513F271B28AE2DFD7AA9B241931D5FCCCD3D8D
17375 1999/00 FF4C2AE50FAACEE194CF4F6FE7C8204D070615E157145637C54FCCDFED7C0A2B
17376 1999/00 FF4D56DEE4EF361C8FAEFF2759AF448620E12FE0F3ACB19E819B7638EAA6EBAD
17377 1999/00 FF55C1F6CEDA62E384073149F5B207B5C77AA090498FCE2BF9CF1993CBD77FFE
17378 1999/00 FF58074DEDB0459A54FE83B3B8EFCE85E4F3AFCC200CEA9E0262D3FD4B81D750
17379 1999/00 FF586160E7D3D71A7BD4A848A874284FD8148278DA5A8FA0FD70820E2C8A490D
17380 1999/00 FF6357B0F9636E8CFFE0E65A3EB7F9A4413DB775E129EF3F498BAB5C701B4558
17381 1999/00 FF6DAD51E8AE31D80E60BA375F99DCD8D602AB6CD8E379E4F9174627F91905C9
17382 1999/00 FF8DEC4753882445FD9D524D7235E53252C52529C3B00C22A96D7C693BEEAC4C
17383 1999/00 FF8E8AF167DFF1BAF1D811D242FA37AF571E9F0D9A71C329110B911ED5BD0577
17384 1999/00 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
17385 1999/00 FFC53382EFC80944BF643197EFC665798C754FA8E41038787A7E7B316B99A75B
17386 1999/00 FFDE0350353E1B484F83298958E0F735D428D6B50E78471B87509497F4406002
17387 1999/00 FFE326BEEDD9B7453AA81BB7251D3F724AB1351CD2D45090955FC0B1EC4377EF
17388 1999/00 FFE326E526FAA00EF542D85A2BEBF681FB29C82A21EDA118DCD93D32035A203B
17389 1999/00 FFEBA230449490BA4B1BCEB1A68C790B1D85708DE8C6EAB8CD170D3E52F12775
17390 1999/00 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
17391 1999/00 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB
17392 1999/00 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
      DOB        Gender Ethnicity     EAL ever_FSM ever_CIN DistCurrSch
1     1999-08-15 F      White British  0   0       FALSE    4.71
2     1998-11-15 M      South Asian    0   0       FALSE    0.33
3     1999-01-15 F      South Asian    0   1        TRUE    1.37
4     1998-10-15 M      White British  0   1        TRUE    4.27
5     1999-03-15 M      White British  0   0       FALSE    0.10
6     1999-07-15 F      Other          1   1        TRUE    2.74
7     1999-06-15 M      White British  0   1       FALSE    0.47
8     1998-09-15 F      White British  0   0       FALSE    0.61
9     1999-08-15 F      South Asian    1   1       FALSE    0.61
10    1999-05-15 F      White British  0   1       FALSE    6.72
11    1998-09-15 M      White British  0   1       FALSE    1.05
12    1999-08-15 M      Other          0   0       FALSE    0.35
13    1998-12-15 F      White British  0   0       FALSE    1.48
14    1999-07-15 M      White British  0   1        TRUE    0.53
15    1999-07-15 M      White British  0   1        TRUE    4.99
16    1999-06-15 F      South Asian    1   0       FALSE    1.91
17    1999-06-15 M      White British  0   0       FALSE    0.77
18    1999-03-15 F      Other          1   1       FALSE    0.55
19    1998-12-15 F      White British NA  NA       FALSE      NA
20    1999-05-15 F      White British  0   1        TRUE    5.98
21    1999-04-15 F      White British  0   0       FALSE    0.71
22    1999-02-15 F      South Asian    1   1       FALSE    5.48
23    1999-06-15 M      White British  0   0       FALSE    2.67
24    1998-11-15 M      South Asian    0   1       FALSE    1.62
25    1998-10-15 F      White British  0   0       FALSE    1.02
26    1998-12-15 F      White British  0   0       FALSE    1.13
27    1998-09-15 M      South Asian    1   1       FALSE    1.14
28    1999-02-15 M      South Asian    1   1       FALSE    0.42
29    1999-01-15 M      White British  0   0        TRUE    0.31
30    1999-05-15 M      White British  0   1       FALSE    3.18
⋮     ⋮          ⋮      ⋮             ⋮   ⋮        ⋮        ⋮
17363 1999-12-15 F      South Asian   1   0        FALSE    0.69
17364 2000-03-15 F      White British 0   0        FALSE    1.20
17365 2000-02-15 F      South Asian   0   1        FALSE    1.39
17366 1999-12-15 M      South Asian   0   0        FALSE    0.33
17367 1999-09-15 F      Other         1   0        FALSE    0.54
17368 1999-10-15 F      White British 0   0        FALSE    2.11
17369 2000-01-15 M      White British 0   1         TRUE    0.25
17370 1999-09-15 F      White British 0   1        FALSE    0.55
17371 2000-04-15 F      White British 0   0        FALSE    0.48
17372 2000-01-15 M      South Asian   0   0        FALSE    0.18
17373 2000-01-15 F      South Asian   1   0        FALSE    0.60
17374 2000-01-15 F      South Asian   0   1        FALSE    1.70
17375 2000-05-15 M      South Asian   1   1         TRUE    1.05
17376 2000-03-15 F      South Asian   1   1        FALSE    2.01
17377 2000-07-15 M      South Asian   1   0        FALSE    0.21
17378 1999-11-15 F      White British 0   1        FALSE    0.91
17379 1999-10-15 M      White British 0   1        FALSE    0.35
17380 1999-12-15 M      White British 0   1        FALSE    9.87
17381 2000-07-15 M      White British 0   1        FALSE    1.57
17382 2000-01-15 F      White British 0   0        FALSE    0.83
17383 2000-02-15 F      South Asian   1   0        FALSE    0.62
17384 1999-10-15 F      White British 0   1         TRUE    2.02
17385 2000-05-15 M      White British 0   0        FALSE    2.62
17386 2000-06-15 F      Other         0   0         TRUE    3.78
17387 1999-12-15 M      White British 0   1         TRUE    1.20
17388 2000-05-15 F      White British 0   1        FALSE    0.22
17389 2000-05-15 F      White British 0   1        FALSE    3.18
17390 1999-11-15 M      South Asian   0   1         TRUE    0.87
17391 2000-03-15 M      Other         1   1        FALSE    1.35
17392 2000-02-15 M      White British 0   0        FALSE    0.35
      LSOA11_Home ⋯ Year10_Term1 Year10_Term2 Year10_Term3 Year11_Term1
1     E01010703   ⋯ 136736       136736       136736       136736
2     E01010742   ⋯ 130909       130909       130909       130909
3     E01010568   ⋯ 107395       107395       107395       107395
4     E01010752   ⋯ 135732       135732       135732       135732
5     E01027577   ⋯ 121716       121716       121716       121716
6     E01010625   ⋯ 107366       107366       107366       107366
7     E01011330   ⋯ 135935       135935       135935       135935
8     E01010579   ⋯ 107439       107439       107439       107439
9     E01010663   ⋯ 139982       139982       139982       139982
10    E01019350   ⋯ 137338       137338       137338       137338
11    E01015222   ⋯ 138863       138863       138863       138863
12    E01011541   ⋯ 136392       136392       136392       136392
13    E01010764   ⋯ 139975       139975       139975       139975
14    E01010734   ⋯ 135367       135367       135367       135367
15    E01010795   ⋯ 138099       138099       138099       131772
16    E01010613   ⋯ 107366       107366       107366       107366
17    E01010580   ⋯ 107439       107439       107439       107439
18    E01010606   ⋯ 107413       107413       107413       107413
19    NA          ⋯     NA           NA           NA           NA
20    E01032492   ⋯ 137764       137764       137764       137764
21    E01010690   ⋯ 132219       132219       132219       132219
22    E01010742   ⋯ 139977       139977       139977       139977
23    E01010587   ⋯ 107439       107439       107439       107439
24    E01010873   ⋯ 107780       107780       107780       107780
25    E01000037   ⋯ 138326       138326       138326       138326
26    E01027574   ⋯ 136664       136664       136664       136664
27    E01015788   ⋯ 136651       136651       136651       136651
28    E01010679   ⋯ 139995       139995       139995       139995
29    E01016839   ⋯ 110532       110532       136170       140106
30    E01010872   ⋯ 130909       130909       130909       130909
⋮     ⋮           ⋱ ⋮            ⋮            ⋮            ⋮
17363 E01010719   ⋯ 136198       136198       136198       136198
17364 E01011095   ⋯ 138706       138706       138706       138706
17365 E01033693   ⋯ 107440       107440       107440       107440
17366 E01010675   ⋯ 140569       140569       140569       140569
17367 NA          ⋯     NA           NA           NA           NA
17368 E01010854   ⋯ 132217       132217       132217       132217
17369 E01010583   ⋯ 139975       139975       139975       139975
17370 E01010613   ⋯ 135367       135367       135367       135367
17371 E01011266   ⋯ 139351       139351       139351       139351
17372 E01011333   ⋯ 135935       135935       135935       135935
17373 E01010626   ⋯ 107413       107413       107413       107413
17374 E01010607   ⋯ 130909       130909       130909       130909
17375 E01028555   ⋯ 139528       139528       139528       139528
17376 E01010792   ⋯ 137576       137576       137576       137576
17377 NA          ⋯     NA           NA           NA           NA
17378 E01027578   ⋯ 141179       141179       141179       141179
17379 E01010717   ⋯ 107441       107441       107441       107441
17380 E01027559   ⋯ 121689       121689       121689       121689
17381 E01010779   ⋯ 107395       107395       107395       107395
17382 E01010591   ⋯ 139975       139975       139975       139975
17383 E01002609   ⋯ 136103       136103       136103       136103
17384 E01011473   ⋯ 108097       108097       108097       108097
17385 E01027560   ⋯ 136736       136736       136736       136736
17386 E01010702   ⋯ 136736       136736       136736       136736
17387 E01010827   ⋯ 107440       107440       107440       107440
17388 E01022024   ⋯ 135957       135957       135957       135957
17389 E01010775   ⋯ 139975       139975       139975       139975
17390 E01010947   ⋯ 137444       137444       137444       137444
17391 E01026960   ⋯ 139060       139060       139060       139060
17392 E01027585   ⋯ 121690       121690       121690       121690
      Year11_Term2 Year11_Term3 Year7_Term1 Year7_Term2 Year7_Term3 ever_AP
1     136736       136736       136736      136736      136736      FALSE
2     130909       130909       130909      130909      130909      FALSE
3     107395       107395       107395      107395      107395      FALSE
4     135732       135732       107391      107391      107391       TRUE
5     121716       121716       121716      121716      121716      FALSE
6     107366       107366       132219      132219      132219      FALSE
7     135935       135935       135935      135935      135935      FALSE
8     107439       107439       107439      107439      107439      FALSE
9     139982       139982       107414      107414      107414      FALSE
10    137338       137338       107768      107768      107768      FALSE
11    138863       138863       113528      113528      113528      FALSE
12    136392       136392       136392      136392      136392      FALSE
13    139975       139975       107386      107386      107386      FALSE
14    135367       135367       135367      135367      135367      FALSE
15    131772       131772       107366      107366      107366       TRUE
16    107366       107366       107366      107366      107366      FALSE
17    107439       107439       107439      107439      107439      FALSE
18    107413       107413       107413      107413      107413      FALSE
19        NA           NA           NA          NA          NA      FALSE
20    137764       137764       108086      108086      108296      FALSE
21    132219       132219       132219      132219      132219      FALSE
22    139977       139977       135231      135231      135231      FALSE
23    107439       107439       107439      107439      107439       TRUE
24    107780       107780       107772      107772      107772      FALSE
25    138326       138326       102351      102351      102351      FALSE
26    136664       136664       136664      136664      136664      FALSE
27    136651       136651       136651      136651      136651      FALSE
28    139995       139995       132216      132216      132216       TRUE
29    140106       110526       110532      110532      110532       TRUE
30    130909       130909       130909      130909      130909      FALSE
⋮     ⋮            ⋮            ⋮           ⋮           ⋮           ⋮
17363 136198       136198       136198      136198      136198      FALSE
17364 138706       138706           NA          NA          NA      FALSE
17365 107440       107440       107440      107440      107440      FALSE
17366 140569       140569       107423      107423      107423      FALSE
17367     NA           NA           NA          NA          NA      FALSE
17368 132217       132217       132217      132217      132217      FALSE
17369 139975       139975       101053      137577      137577      FALSE
17370 135367       135367       135367      135367      135367      FALSE
17371 139351       139351       108094      108094      108094      FALSE
17372 135935       135935       135935      135935      135935      FALSE
17373 107413       107413       107413      107413      107413      FALSE
17374 130909       130909       130909      130909      130909      FALSE
17375 139528       139528       133644      133644      133644      FALSE
17376 137576       137576       137576      137576      137576      FALSE
17377     NA           NA           NA          NA          NA      FALSE
17378 141179       141179       121691      121691      121691      FALSE
17379 107441       107441       107441      107441      107441      FALSE
17380 121689       121689       121686      121686      121686      FALSE
17381 107395       107395       107395      107395      107395      FALSE
17382 139975       139975       107386      107386      107386      FALSE
17383 136103       136103       136103      136103      136103      FALSE
17384 108097       108097       108097      108097      108097      FALSE
17385 136736       136736       136736      136736      136736      FALSE
17386 136736       136736       107275      107275      107275      FALSE
17387 107440       107440       107305      107305      107305      FALSE
17388 135957       135957       135957      135957      135957      FALSE
17389 139975       139975       107386      107386      107386      FALSE
17390 137444       137444       134993      134993      134993      FALSE
17391 139060       139060       107397      107397      107397      FALSE
17392 121690       121690       107562      107562      107562      FALSE

# Missing data

In [10]:
data |> summarise(across(everything(), ~ sum(is.na(.))))

  cohort person_id DOB Gender Ethnicity EAL ever_FSM ever_CIN DistCurrSch
1 0      0         0   1      33        184 107      0        233
  LSOA11_Home ⋯ Year10_Term1 Year10_Term2 Year10_Term3 Year11_Term1
1 411         ⋯ 508          508          508          520
  Year11_Term2 Year11_Term3 Year7_Term1 Year7_Term2 Year7_Term3 ever_AP
1 520          520          1619        1618        1619        0

In [11]:
colSums(is.na(data))

                 cohort               person_id                     DOB
                      0                       0                       0
                 Gender               Ethnicity                     EAL
                      1                      33                     184
               ever_FSM                ever_CIN             DistCurrSch
                    107                       0                     233
            LSOA11_Home                   IDACI        ever_SEN_support
                    411                      34                       0
 first_SEN_support_year        SEN_support_need           ever_EHC_plan
                   9714                    9714                       0
    first_EHC_plan_year           EHC_plan_need                  no_SEN
                  16820                   16820                       0
  AuthorisedAbsenceRate UnauthorisedAbsenceRate        TotalAbsenceRate
                      0                       0                       0
            Suspensions      SuspensionSessions              Exclusions
                      0                       0                       0
            KS4_Entries       KS4_Passes_Level1       KS4_Passes_Level2
                    247                     247                     247
            Destination             Year8_Term1             Year8_Term2
                      0                     973                     974
            Year8_Term3             Year9_Term1             Year9_Term2
                    972                     688                     688
            Year9_Term3            Year10_Term1            Year10_Term2
                    688                     508                     508
           Year10_Term3            Year11_Term1            Year11_Term2
                    508                     520                     520
           Year11_Term3             Year7_Term1             Year7_Term2
                    520                    1619                    1618
            Year7_Term3                 ever_AP
                   1619                       0

263 students with all NAs for school 
- 38 labelled DROP
- 17 risky
- 208 steady eet

415 students with no KS4 data 
- 36 labelled DROP
- 144 risky
- 235 steady eet

- N = 17,224
- drop DROP: n = 16,956
- drop all NAs for school: n = 16,731
- drop NA for KS4 entries: n = 16,390
- drop NA for ever FSM: n = 16,285

In [17]:
data_drop_missing <- data |>
    filter(
        Destination != 'DROP',
        !if_all(c(
                Year7_Term1, Year7_Term2, Year7_Term3,
                Year8_Term1, Year8_Term2, Year8_Term3,
                Year9_Term1, Year9_Term2, Year9_Term3,
                Year10_Term1, Year10_Term2, Year10_Term3,
                Year11_Term1, Year11_Term2, Year11_Term3
                ), is.na),
        !is.na(KS4_Entries)
        )

In [18]:
colSums(is.na(data_drop_missing))

                 cohort               person_id                     DOB
                      0                       0                       0
                 Gender               Ethnicity                     EAL
                      1                      31                      82
               ever_FSM                ever_CIN             DistCurrSch
                     17                       0                     114
            LSOA11_Home                   IDACI        ever_SEN_support
                    137                       0                       0
 first_SEN_support_year        SEN_support_need           ever_EHC_plan
                   8354                    8354                       0
    first_EHC_plan_year           EHC_plan_need                  no_SEN
                  14621                   14621                       0
  AuthorisedAbsenceRate UnauthorisedAbsenceRate        TotalAbsenceRate
                      0                       0                       0
            Suspensions      SuspensionSessions              Exclusions
                      0                       0                       0
            KS4_Entries       KS4_Passes_Level1       KS4_Passes_Level2
                      0                       0                       0
            Destination             Year8_Term1             Year8_Term2
                      0                     611                     611
            Year8_Term3             Year9_Term1             Year9_Term2
                    610                     354                     354
            Year9_Term3            Year10_Term1            Year10_Term2
                    354                     187                     187
           Year10_Term3            Year11_Term1            Year11_Term2
                    187                     172                     172
           Year11_Term3             Year7_Term1             Year7_Term2
                    172                    1121                    1119
            Year7_Term3                 ever_AP
                   1120                       0

#### Replace svchool NAs with 111111

In [19]:
data_drop_missing <- data_drop_missing |>
    mutate(across(c(Year7_Term1, Year7_Term2, Year7_Term3,
                Year8_Term1, Year8_Term2, Year8_Term3,
                Year9_Term1, Year9_Term2, Year9_Term3,
                Year10_Term1, Year10_Term2, Year10_Term3,
                Year11_Term1, Year11_Term2, Year11_Term3),
                ~ replace_na(., 111111)))

In [20]:
#data_drop_missing <- data_drop_missing |>
#    filter(!is.na(ever_FSM))

In [21]:
head(data_drop_missing)

  cohort  person_id
1 1998/99 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
2 1998/99 00211975518FD5336E43850D59B5F5DDA7CD98B212760111CB40528BDECF3B1B
3 1998/99 00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9
4 1998/99 0025102C0D8E8C5F27454E3715E982A43E1431991E85562E55BCB19D9D1BD7D3
5 1998/99 0026BFA5D5426F421200AB505AAD52956621DCC253241A6647302BCE4764547D
6 1998/99 002D3DB2625339C740EB129CCC925A9D90E4F5AA05561B81FE166EDF990B8F65
  DOB        Gender Ethnicity     EAL ever_FSM ever_CIN DistCurrSch LSOA11_Home
1 1999-08-15 F      White British 0   0        FALSE    4.71        E01010703
2 1998-10-15 M      White British 0   1         TRUE    4.27        E01010752
3 1999-07-15 F      Other         1   1         TRUE    2.74        E01010625
4 1999-06-15 M      White British 0   1        FALSE    0.47        E01011330
5 1998-09-15 F      White British 0   0        FALSE    0.61        E01010579
6 1999-08-15 F      South Asian   1   1        FALSE    0.61        E01010663
  ⋯ Year10_Term1 Year10_Term2 Year10_Term3 Year11_Term1 Year11_Term2
1 ⋯ 136736       136736       136736       136736       136736
2 ⋯ 135732       135732       135732       135732       135732
3 ⋯ 107366       107366       107366       107366       107366
4 ⋯ 135935       135935       135935       135935       135935
5 ⋯ 107439       107439       107439       107439       107439
6 ⋯ 139982       139982       139982       139982       139982
  Year11_Term3 Year7_Term1 Year7_Term2 Year7_Term3 ever_AP
1 136736       136736      136736      136736      FALSE
2 135732       107391      107391      107391       TRUE
3 107366       132219      132219      132219      FALSE
4 135935       135935      135935      135935      FALSE
5 107439       107439      107439      107439      FALSE
6 139982       107414      107414      107414      FALSE

# Simplified dataset

In [22]:
data_simple <- data_drop_missing |>
    mutate(Highest_SEN_level = case_when (
            no_SEN ~ 'No SEN', 
            ever_SEN_support & !ever_EHC_plan ~ 'SEN Support',
            ever_EHC_plan ~ 'EHC Plan'
        ))

In [24]:
data_simple <- data_simple |>
    select(-c(ever_SEN_support,first_SEN_support_year,SEN_support_need,ever_EHC_plan,first_EHC_plan_year,EHC_plan_need,no_SEN))

In [25]:
head(data_simple)

  cohort  person_id
1 1998/99 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
2 1998/99 00211975518FD5336E43850D59B5F5DDA7CD98B212760111CB40528BDECF3B1B
3 1998/99 00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9
4 1998/99 0025102C0D8E8C5F27454E3715E982A43E1431991E85562E55BCB19D9D1BD7D3
5 1998/99 0026BFA5D5426F421200AB505AAD52956621DCC253241A6647302BCE4764547D
6 1998/99 002D3DB2625339C740EB129CCC925A9D90E4F5AA05561B81FE166EDF990B8F65
  DOB        Gender Ethnicity     EAL ever_FSM ever_CIN DistCurrSch LSOA11_Home
1 1999-08-15 F      White British 0   0        FALSE    4.71        E01010703
2 1998-10-15 M      White British 0   1         TRUE    4.27        E01010752
3 1999-07-15 F      Other         1   1         TRUE    2.74        E01010625
4 1999-06-15 M      White British 0   1        FALSE    0.47        E01011330
5 1998-09-15 F      White British 0   0        FALSE    0.61        E01010579
6 1999-08-15 F      South Asian   1   1        FALSE    0.61        E01010663
  ⋯ Year10_Term2 Year10_Term3 Year11_Term1 Year11_Term2 Year11_Term3
1 ⋯ 136736       136736       136736       136736       136736
2 ⋯ 135732       135732       135732       135732       135732
3 ⋯ 107366       107366       107366       107366       107366
4 ⋯ 135935       135935       135935       135935       135935
5 ⋯ 107439       107439       107439       107439       107439
6 ⋯ 139982       139982       139982       139982       139982
  Year7_Term1 Year7_Term2 Year7_Term3 ever_AP Highest_SEN_level
1 136736      136736      136736      FALSE   SEN Support
2 107391      107391      107391       TRUE   EHC Plan
3 132219      132219      132219      FALSE   SEN Support
4 135935      135935      135935      FALSE   No SEN
5 107439      107439      107439      FALSE   No SEN
6 107414      107414      107414      FALSE   No SEN

# Save CSVs

In [26]:
# save as csv
write.csv(data, "data/additional_data_EA.csv", row.names = FALSE)

In [27]:
# save as csv
write.csv(data_drop_missing, "data/additional_data_EA_noNA.csv", row.names = FALSE)

In [28]:
# save as csv
write.csv(data_simple, "data/additional_data_simple.csv", row.names = FALSE)