In [1]:
library(tidyverse)
library(dbplyr)
library(bigrquery)
library(lubridate)

bq_auth()

project_id = "yhcr-prd-bradfor-bia-core"

# create connection to database
con <- DBI::dbConnect(bigrquery::bigquery(), 
                      project = project_id)

print(paste0("Connected to : ", project_id))

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘dbplyr’


The following objects are masked from ‘package:dplyr’:

    ident, sql

[1] "Connected to : yhcr-prd-bradfor-bia-core"

In [3]:
person <- read.csv("data/person_cohorts_max.csv", header = TRUE)

# Mental Health Referrals

In [2]:
MHref_data = "CB_2489.tbl_Mental_SRReferralIn"

MHref_table <- tbl(con, MHref_data) |>
    select(person_id, datereferral) |> 
    # convert to df
    collect()

In [4]:
head(person)

  person_id                                                        birth_date
1 EE91E3C77F2B7CB44F1F601317E2DE5EE76ABB0941F24D4714026B3E30FC313C 1998-09-15
2 C5553DE427E9B8F60E9B5D1E83391E1B660F415A3924B630742D52A0517F5219 1998-09-15
3 AC8CB4071E24E606BFFECC380A9EA11546158370916C4D8D954FA76D63FA81AE 1998-09-15
4 E4E84D0DEB6692712A8E875B701E097EB61235069C56626900C0951E9B112B6D 1998-09-15
5 64FA4602D88C275E27FDBD17EA4678E378D7B297D91C2CDB914150ED0CBF3785 1998-09-15
6 F516562D5CFDDC6CD66FB8EA18399D11BB0E2E042F569D918285FF96C3377338 1998-09-15
  gender CombinedEthnicity cohort
1 M      South Asian       1998/99
2 M      White British     1998/99
3 M      White British     1998/99
4 M      South Asian       1998/99
5 M      White British     1998/99
6 M      White British     1998/99

In [5]:
head(MHref_table)

  person_id
1 B63CC2FC864F90AF0CFCEEA3EF103E226EC91062EE704F022BACDEFCE1B93BEB
2 B63CC2FC864F90AF0CFCEEA3EF103E226EC91062EE704F022BACDEFCE1B93BEB
3 65DFC7AF06804B357EB3BA6D7A6205FD7BCF82AAF117E4323505C25F02EAE31B
4 65DFC7AF06804B357EB3BA6D7A6205FD7BCF82AAF117E4323505C25F02EAE31B
5 262B531379C8FABE17F50CA985D32ABA9715E0EDE59B2AC36E8F13ADDFDAD483
6 262B531379C8FABE17F50CA985D32ABA9715E0EDE59B2AC36E8F13ADDFDAD483
  datereferral
1 30 Jan 2018 11:34:11
2 30 Jan 2018 11:34:11
3 20 Mar 2018 10:33:53
4 20 Mar 2018 10:33:53
5 20 Mar 2018 10:57:35
6 20 Mar 2018 10:57:35

In [ ]:
intersect(person$person_id, MHref_table$person_id)

In [7]:
mh_filtered <- MHref_table |>
    # filter destinations to target person ids
    semi_join(person, by = "person_id")

In [9]:
mh_filtered <- mh_filtered |>
    unique()

In [11]:
head(mh_filtered)

  person_id
1 367B454437C575ADEB9D2E5BB831BC344B23F4ED34B6B4E35CF4EA1DF6C18230
2 589529480A34074E589066C15276888E113B3D26D05811BD60ABFA6A62373E6D
3 880D672D5444ABF736A4CFFE02ABAB2054E4486D9D06E9C99A6BAABED73428B7
4 284CBB5A7E06A6F8862C38F09C39FE1C1FCF9CBE203E203E1714752A217A51A1
5 8EE74633BEAAF8B1102C43B0DAFE4387F829574B7F60FCE9C60DEF287911C55C
6 03D7DF202BB46EF8910D372A3E82506445C452139B888BBCA29BFEAC630ED50C
  datereferral
1 30 Nov 2018 15:34:54
2 11 Jun 2019 15:55:25
3 11 Jun 2019 16:01:04
4 11 Sep 2018 16:15:08
5 21 Nov 2018 13:53:45
6 18 Jan 2019 16:54:45

In [13]:
mh_filtered <- mh_filtered |>
    mutate(MHReferral = as.Date(datereferral, format = "%d %b %Y %H:%M:%S"))

In [14]:
mh_filtered

      person_id
1     367B454437C575ADEB9D2E5BB831BC344B23F4ED34B6B4E35CF4EA1DF6C18230
2     589529480A34074E589066C15276888E113B3D26D05811BD60ABFA6A62373E6D
3     880D672D5444ABF736A4CFFE02ABAB2054E4486D9D06E9C99A6BAABED73428B7
4     284CBB5A7E06A6F8862C38F09C39FE1C1FCF9CBE203E203E1714752A217A51A1
5     8EE74633BEAAF8B1102C43B0DAFE4387F829574B7F60FCE9C60DEF287911C55C
6     03D7DF202BB46EF8910D372A3E82506445C452139B888BBCA29BFEAC630ED50C
7     A750B01D5FDBBE5F5A9444EC11B0773438BEEC7A0E24B66BB018DFD0282A133D
8     637193BDB068DD712A04B058165E2876BA9C9D68FC1EEDA978304D46A026D97D
9     B9FDC8506D505035AFBC556C0DF197EC924E34C886E786F862FE65ADC36D3EBF
10    4AEBCCA6D58E086BE8B35C59EC6DE5EB251BA36BC4DBA86008D2FCFB31DC803F
11    6CFF4F6D5DEAFA9717F323D464A1FB52A2BC4DCEAF3776716022474526571069
12    CBA062D79B9F00EC5D4973F09D2ACC1183374C5C3E309945EB55FEB3E108B4E9
13    CBA062D79B9F00EC5D4973F09D2ACC1183374C5C3E309945EB55FEB3E108B4E9
14    79F3EBE9553954EC415F205A58DAA2F6FAE082709053156FB26F0DB7DFF0DE4B
15    CA977039509FDCE8FC07FC9AB1C60BDD83AF6617F8005CF906F15FA3D9576300
16    4A3352E41FB4083417D8D77F89B07FDD7CDEC1A87031899D0F80A1BA2B890CEC
17    62FEA75919FE790C4136B54B00C6BFA3452BB444E06BB98DBE40BD3FA961A1BE
18    356325F1EE1A8A1A5331EA979DF8D1D340E83A126533014A8AD263788D091565
19    C1D1611C7D9A2F5E17F070EDCCBD7A98854EF54E8941596B49D559085AAFBE21
20    E97521F1169D752C3F0C7402E5D8DA7DD64197A8CB7948607D1062D039C7ADD0
21    573E4ED35663DC11F97845A0EEF2754BE0D67FDFB5E885EE8741FEEAA56E9FD0
22    BB2B153EA98D72994F815E54E315001F26E856254E8603C2FAF6018E76915545
23    D72BF3598FC96C566DAF515D0E9FE50E2629E5578E2DE6AD6350808543F7E8A6
24    44EB358BCF84ECBDDB729CCFD1A9025C146E6891A8B6CF438938D8D7A3A16D93
25    71021ACA37CCDD70573723C75DACE661A2834A804B026B143056B65A9C7A4928
26    69F625746E3D4A2F6D9F62E65F10513766AFB27166AEED31FE76BC730795B481
27    CB0B3168CAE0CB3C4868BF297669A8A3BD0941E0E2E6B7568B8B6D713F694A4A
28    BADBE677481E64FA583EE080026799B9CADFF751EAC7C997FBDEAD713189647E
29    926C080A120AB13C90008E2224CBE80C798C939EA506C6EB1B99B6CA6C27EE6C
30    589529480A34074E589066C15276888E113B3D26D05811BD60ABFA6A62373E6D
⋮     ⋮
39283 90A6D8468BEE524EDB1AAE58886612118A345BB3D7D87FC6BC5F03B6C2B838E7
39284 05679C508C033BBECD6E28B1F74C694D4B8C9B3ECB3FA5211E0E93C23BD8E23E
39285 68A980B24B540413860C1E5D89F1968D962E584E97FB0457BFA843B6BE80717B
39286 E968BB5EE775BA4D4FA65416BF21481CF45C19B12B7CD86BA9C483F86F12496B
39287 4EFD41D05405F8D3370275EF1560951CB37E51004D4FB71C916C474080670A7F
39288 581E300A7FCC375BD57418BCF2E06521B2F5DFB7E66834EF03F85F6B0F481D94
39289 7615D63CD298EC670F5B6FCF8E011D46F8914C5AF9A973F9FDAC1D7667738AF1
39290 F0D802B89A9A90DEC9B77924094A529E609E41A05FBF4BD1C680564B82ABC278
39291 82CCD9E68672274A60BEE4CBCCF13088D7A4055D8BD261456184B8F8E077D5A4
39292 DB323DA70EB47683F31630EFCA88C4402DFE95D7F7AF68CB7036B02931B18928
39293 D3866CA1CD2DD89404CFEF6BAE7862C2FE3D6762F185CD784F22582EEE55A985
39294 5D80B7B2E55F2D7E82DFBF887208D65B3C2AAD4BCBCA14BB277D25D80FFBF791
39295 3D0669F0BF9369EDF707E4DE6A694070C6705955793716DAF09F011E77954249
39296 7286412E1FE80960BDB18259DA5C01559CFD6568AE421D9AAF5F00AB40571318
39297 2BB114DD0BDD9DB2AD38C8E7294AE3457FCC5709F78CB432AB307EEC823A7D46
39298 9C86C5094B66A8B0D67291FCDB491CBEE1665CAA776800E619AFD25F81C44E80
39299 8AFEA202C7B0223DA86403D3601651DA16E46E14614CADFF8175D182727A62A7
39300 36CDE072087439016D1A7FD672F29A658B75744261B0EB602D69AAA4BEDAC0EE
39301 6049715198F451FB6833DC29E6D5AED2A05B964CFD7296DE603212C355164991
39302 CFD0754F353B7E2BB5C3560B792671B10BC58C374284B4581BA0F538A15CB44F
39303 A8094F99AC775709AE2752A8A893423706C0EA1C172503D83423EF1A683D2D88
39304 A8EEE7204971C3437C80D43613895462F4D9EA316F7697867D954E7F87BE3325
39305 8203AA9FD71186410D42F95646098D56CF945546A36B04E92AEE2DAD05038965
39306 D32879FDEA021001A7C11408B6D9F1E542EC6F1557CA9B9C770F46DA704EF836
39307 9D7BBB097EAD621D91C14965F614BD4573960C701384581B662362256879AF96
39308 A48AF32F5567E04028FB21E7FECA5D58D3E99A1DF75FB48C4CF0B8486F61DD20
39309 B0C770B2E6F92966ED68FED6F0B554352644AAEC0508B68CB186EA8F752604B5
39310 00211975518FD5336E43850D59B5F5DDA7CD98B212760111CB40528BDECF3B1B
39311 CDD61228BF853E495694952C4F6E4CE4D5A52127FB5D8222C4D6A8CCF2217941
39312 E97521F1169D752C3F0C7402E5D8DA7DD64197A8CB7948607D1062D039C7ADD0
      datereferral         MHReferral
1     30 Nov 2018 15:34:54 2018-11-30
2     11 Jun 2019 15:55:25 2019-06-11
3     11 Jun 2019 16:01:04 2019-06-11
4     11 Sep 2018 16:15:08 2018-09-11
5     21 Nov 2018 13:53:45 2018-11-21
6     18 Jan 2019 16:54:45 2019-01-18
7     28 Oct 2019 14:37:15 2019-10-28
8     30 Oct 2019 13:56:03 2019-10-30
9     04 Dec 2019 15:27:00 2019-12-04
10    23 Dec 2019 09:12:13 2019-12-23
11    21 Dec 2018 12:45:28 2018-12-21
12    11 Jun 2019 10:13:23 2019-06-11
13    12 Jun 2019 13:34:26 2019-06-12
14    04 Jul 2019 14:01:55 2019-07-04
15    14 Aug 2019 16:41:27 2019-08-14
16    14 Aug 2019 16:48:39 2019-08-14
17    30 Aug 2019 09:21:12 2019-08-30
18    25 Oct 2017 11:27:00 2017-10-25
19    07 Nov 2017 08:33:00 2017-11-07
20    16 Nov 2017 14:02:00 2017-11-16
21    24 Nov 2017 10:26:00 2017-11-24
22    24 Nov 2017 10:37:00 2017-11-24
23    29 Nov 2017 10:44:00 2017-11-29
24    08 Jan 2018 08:58:00 2018-01-08
25    08 Jan 2018 09:00:00 2018-01-08
26    08 Jan 2018 09:03:00 2018-01-08
27    08 Jan 2018 09:12:00 2018-01-08
28    08 Jan 2018 09:29:00 2018-01-08
29    22 Jan 2018 10:00:00 2018-01-22
30    05 Mar 2018 11:24:00 2018-03-05
⋮     ⋮                    ⋮
39283 09 Aug 2013 10:09:30 2013-08-09
39284 09 Aug 2013 10:10:27 2013-08-09
39285 09 Aug 2013 10:11:19 2013-08-09
39286 09 Aug 2013 10:12:22 2013-08-09
39287 09 Aug 2013 10:13:30 2013-08-09
39288 09 Aug 2013 10:14:20 2013-08-09
39289 09 Aug 2013 12:08:19 2013-08-09
39290 09 Aug 2013 12:09:10 2013-08-09
39291 09 Aug 2013 12:09:53 2013-08-09
39292 09 Aug 2013 12:14:44 2013-08-09
39293 09 Aug 2013 12:17:04 2013-08-09
39294 09 Aug 2013 12:18:33 2013-08-09
39295 09 Aug 2013 12:19:23 2013-08-09
39296 09 Aug 2013 12:21:11 2013-08-09
39297 09 Aug 2013 12:22:06 2013-08-09
39298 09 Aug 2013 12:22:54 2013-08-09
39299 09 Aug 2013 12:23:44 2013-08-09
39300 09 Aug 2013 12:24:30 2013-08-09
39301 09 Aug 2013 12:26:25 2013-08-09
39302 09 Aug 2013 12:27:33 2013-08-09
39303 09 Aug 2013 12:28:23 2013-08-09
39304 09 Aug 2013 12:29:20 2013-08-09
39305 09 Aug 2013 12:31:10 2013-08-09
39306 09 Aug 2013 12:31:58 2013-08-09
39307 09 Aug 2013 12:32:48 2013-08-09
39308 09 Aug 2013 12:33:43 2013-08-09
39309 09 Aug 2013 12:34:29 2013-08-09
39310 11 Sep 2013 13:24:10 2013-09-11
39311 22 Oct 2013 10:28:15 2013-10-22
39312 13 Nov 2013 11:03:30 2013-11-13

In [20]:
cohort_9899 <- person |>
    filter(cohort == '1998/99')

In [22]:
mh_filtered_9899 <- mh_filtered |>
    semi_join(cohort_9899, by = "person_id") |>
    filter(MHReferral < as.Date("2015-09-01"))

In [116]:
mh_filtered_9899 |>
    arrange(MHReferral)

     person_id
1    1EC171D9C8E9515AF835F585890726E1987E8A4F15A3546BA682A21F163F34E9
2    8CCA4D6C724BACE60A211E9BFF8895BFE6EC2F82C307C4CB7A830FA87E03D7C5
3    E5E013E5BBFDA1F263E1BCDB98A42E8C8368C9CE4A415A181944464CC086E5AD
4    063DADDF0002D93D659DED1DA5565FDBB3775BAD559F8A041F8F7B38EC02CBEB
5    E031AFDFF72CE03410622827DD6988A3A3FC5BC303962D6313E0DBEFD454470A
6    6CFF4F6D5DEAFA9717F323D464A1FB52A2BC4DCEAF3776716022474526571069
7    FB81092AD28CA901FE1E58F0F36F6FE5236B7755132F74E65403AC8C20C761F2
8    DF6B3FF6DB820B472CB54DB871E2DC78C73A33C7D433C113AB87A112AD814B05
9    173837E14BAF55207D72F0E441AD26577205FEE02250ADF16D43703D4B80D07E
10   9BEE0D00BC450FC8E759BE0877C51DCE02B9B62F0C132DFBC52D0D880FFBEAC5
11   4171649E2A854F23E90B5B9D72B576BE77A89C03CED76734DA9E3D649FD6C383
12   11A69234A51B0B3FCB9F2AAB50BA88BEDB4FCF5E14C7619E81298F279410F6CD
13   9FE6065FFEB9F1FDC3F0606C6FCBDE0AE488AA7B792E9B7C95A3BF33CE09E8D0
14   C5D3B27C9939B2D995C1E8FEECC3715EFD95B64E0D186A833EE5872B3891ED3D
15   7197DDFADCC7E35C2EB50C81FD1B6E8A4BDDB05370A23F324C897B8D88E243C2
16   9648BF5C29EAFB5C61548727774EFFEF0C2F038332462FF21DD14944BE0939AE
17   4C68E55F7B2B9C4D38F8360AC63AB942219B817BCFC4D4FC134B04FE05690E93
18   05D9A117BD7E95084C06CF80C1984678FB3AD6E3E96540B822902DB00D3872C8
19   DF9D461867D959520C2A4C7D3FDB17B91582D266292FB34CCE0250964D63DD24
20   EB148DFF6AD3EEA4D6F5181B950B2F29E0A050C5D597C0256715E808722D06D0
21   5F4744FE72DDD1091F78B68E1F267DA67C58BF0F2F3BF3C28E4631D6CC708E19
22   6B93597A1EF4C61EEDF46C130090649F977C89611232F86A4274DD318D410BDE
23   0AB9E37B82DC39BC00DE43BE0A9B567C1508CD374410289887F9181E99D221E3
24   C3A89361CE3C5F75B8C578C8BB4A0CE7B1C3A82C1BE9805D143E85BDA7F577E3
25   97BBCB6D18FBB8A0D51BD5182B9F00AE513B5D5204D889AC995939FBF27F120F
26   784C52C31EE41254051B2246A8CD78BF26091F1DB2B4D5004418400C2921BC7C
27   235F1AF69A5F3A9FDDF7C28DF95C2C0C7D9575E0646EF44200CED175033A5033
28   7F50D9B905EC1E6ED853466DEF579348999D02D1E95875420B639A40D851D6AB
29   15E8CE2E6119AD18CDF46BABC277B1644318E8B5694E51B92A5B16112D3EABD4
30   81E0E1D48E5BF850FEA2A01307638DB8BC8F7995CF7339C0EE17A95218A5B22C
⋮    ⋮
5758 47F26CB711DF1F096B3DBAEA9285ECC94419163CB63F53F1586E614A7A042661
5759 DBB6D6692D58870AFF1926B84ED244304001AC2BEB5E637FE3E1339ACDDB7F63
5760 529F1603E411E078075F54FA87D7F47FD6232DC7A081B7E467254EF43C22D361
5761 0E2F51A1A4C321E3B67DFDB6FF333F479F7C48D7BF9D9A2008132CA7C576F88E
5762 91966C22A032F6A521B562C1C3CFFDE5804CA6AB4E93A99299A2715F345EA88C
5763 E55EC7DAFA4C4777CA15ACCB93B2756AD976C2E44B78C5761A8A7743771922EF
5764 6E648DD48CAE3820E8F36B07F9F29C7BBA5768A92344A5914AB04F091ACD5896
5765 8C982B1BB6180017C950D678FDD5DBD2D3855AD86A4A187D438718B665E0A08E
5766 D5CC742EE9412407E7C1156AC483C844B30F0A804F0F0C261D4FD7281BA952B8
5767 775F5FC6FE217976BA984171FF91307389A1B07BD66BB04D5DF568E6FC2131D1
5768 0A04748F832BC17B46A335413CE144BAB47C64FF07BD65B48C98874C1820BF59
5769 19FF963B9B88AB525D81DBAD04FADB566A41DCF2126372D5671F7C3A1E0816D5
5770 A9D43E5AC5A76D9A973B9A4F96B4AD9D73CAD6B11E8C6804CF57928F1C8C083C
5771 0F0DEEFFDA2768BC5E0B2424FE8626BA98AB478B407B8DA0C15201EF7423B950
5772 21EEBB8C3626DA8A88DA11B30896F0356AB76AD1EE46F84E7DA4265ABF2E9954
5773 8C73CE6347C05CD54D3BB0B2142909737BEDDE10D0EF8BFCB35EABC7BDBA3FE8
5774 727EB6EA43005C348ED909F45E9C78168FCD343B91E99E28F51E4DBEDC114300
5775 8196D7B3A4A043B1E1DD63E4E9892C3726CC268FC9C3923C67A0A28B504DB62F
5776 AF8DAF911EA8453F9A6CD8E766872DC6E5089AA66C78179E623332390F4EC887
5777 0E2F51A1A4C321E3B67DFDB6FF333F479F7C48D7BF9D9A2008132CA7C576F88E
5778 3FB0C7C94BC3E09F601CF105C87540F1AB893E9A6CADC6417A815BE7E328659D
5779 98BA66EA6C3734C8D477E923DCF5B90CC4A06DBDA7BFCD1497855733A419E009
5780 A27ED0A561F5D90B9DC169ED272D761140FAB33BC1A3DAEA18D69E7E0B8FBD76
5781 AF5F6E07B22B1FEC1F64D15E42C2FE07724BC528BA4CF668DF72AD62B7E01F51
5782 9F07D68BC43C602B5D06726000B25B205F037DBE9596D1E38B45988DA8B4AC17
5783 BCCC129DBAD5B4F255D91F267F3656B2893CA4F82C0373F269A4B8C86CEB59EB
5784 1C0B17A331149F5A0DF083223BBBE1D9D225F2C3EE0D3023CD93D38DD3C52430
5785 30B3B45F27B8F4527F6F4F33BF5222F5D9B12D7C2329DBBBB1A432573ACF5C60
5786 4967D4FB90280F34087272A578F1BBC6AEE6A691640FFE4D8FAA5A184DF50A45
5787 D83A2C85B5D6CD5F2C9E0AB9F1E570431880AB6B2E3CEEE489C34C38C03F2BBE
     datereferral         MHReferral
1    30 Jan 2003 00:00:00 2003-01-30
2    16 May 2005 00:00:00 2005-05-16
3    01 Mar 2006 00:00:00 2006-03-01
4    30 Nov 2007 00:00:00 2007-11-30
5    08 Jul 2009 00:00:00 2009-07-08
6    11 Nov 2009 00:00:00 2009-11-11
7    22 Apr 2010 00:00:00 2010-04-22
8    28 Apr 2010 00:00:00 2010-04-28
9    24 Nov 2010 15:56:00 2010-11-24
10   29 Mar 2011 00:00:00 2011-03-29
11   11 Apr 2011 00:00:00 2011-04-11
12   20 Sep 2011 00:00:00 2011-09-20
13   09 Nov 2011 00:00:00 2011-11-09
14   16 Jan 2012 00:00:00 2012-01-16
15   14 Mar 2012 11:59:00 2012-03-14
16   12 Apr 2012 10:13:00 2012-04-12
17   03 May 2012 00:00:00 2012-05-03
18   09 May 2012 00:00:00 2012-05-09
19   28 Jun 2012 14:28:00 2012-06-28
20   03 Jul 2012 14:01:42 2012-07-03
21   15 Oct 2012 00:00:00 2012-10-15
22   24 Oct 2012 12:16:00 2012-10-24
23   15 Nov 2012 11:14:00 2012-11-15
24   03 Dec 2012 00:00:00 2012-12-03
25   20 Dec 2012 16:45:37 2012-12-20
26   13 Feb 2013 00:00:00 2013-02-13
27   15 Feb 2013 14:07:00 2013-02-15
28   05 Apr 2013 10:14:00 2013-04-05
29   23 Apr 2013 14:12:22 2013-04-23
30   23 Apr 2013 14:13:58 2013-04-23
⋮    ⋮                    ⋮
5758 11 Jun 2015 08:33:00 2015-06-11
5759 12 Jun 2015 12:00:00 2015-06-12
5760 17 Jun 2015 12:00:00 2015-06-17
5761 19 Jun 2015 12:07:32 2015-06-19
5762 22 Jun 2015 15:16:00 2015-06-22
5763 23 Jun 2015 11:00:00 2015-06-23
5764 25 Jun 2015 11:58:01 2015-06-25
5765 25 Jun 2015 14:00:46 2015-06-25
5766 02 Jul 2015 09:00:00 2015-07-02
5767 07 Jul 2015 08:33:00 2015-07-07
5768 14 Jul 2015 08:30:00 2015-07-14
5769 16 Jul 2015 10:00:00 2015-07-16
5770 20 Jul 2015 09:00:00 2015-07-20
5771 21 Jul 2015 15:50:58 2015-07-21
5772 28 Jul 2015 08:33:00 2015-07-28
5773 28 Jul 2015 15:00:00 2015-07-28
5774 28 Jul 2015 12:01:54 2015-07-28
5775 28 Jul 2015 16:56:40 2015-07-28
5776 30 Jul 2015 08:33:18 2015-07-30
5777 31 Jul 2015 10:38:50 2015-07-31
5778 06 Aug 2015 08:50:00 2015-08-06
5779 07 Aug 2015 15:54:14 2015-08-07
5780 10 Aug 2015 16:12:01 2015-08-10
5781 10 Aug 2015 11:15:08 2015-08-10
5782 17 Aug 2015 13:20:25 2015-08-17
5783 19 Aug 2015 09:00:00 2015-08-19
5784 19 Aug 2015 11:55:00 2015-08-19
5785 20 Aug 2015 14:50:00 2015-08-20
5786 20 Aug 2015 14:59:00 2015-08-20
5787 26 Aug 2015 08:50:53 2015-08-26

In [25]:
mh_filtered_9899 |>
  count(person_id) |>       
  count(n) |>               
  rename(frequency = n, count = nn)

Storing counts in `nn`, as `n` already present in input
ℹ Use `name = "new_name"` to pick a new name.

  frequency count
1 1         5449
2 2          151
3 3           12

In [30]:
unique(person$cohort)

[1] "1998/99" "1999/00" "2000/01" "2001/02"

In [32]:
cohort_9900 <- person |>
    filter(cohort == '1999/00')

In [34]:
mh_filtered_9900 <- mh_filtered |>
    semi_join(cohort_9900, by = "person_id") |>
    filter(MHReferral < as.Date("2016-09-01"))

In [36]:
mh_filtered_9900 |>
  count(person_id) |>       
  count(n) |>               
  rename(frequency = n, count = nn)

Storing counts in `nn`, as `n` already present in input
ℹ Use `name = "new_name"` to pick a new name.

  frequency count
1 1         5791
2 2          319
3 3           54
4 4           10
5 5            1
6 6            1

In [37]:
mh_filtered_9900 |>
  count(person_id) |>
  filter(n > 4) |>
  arrange(desc(n))

  person_id                                                        n
1 531F491C7677E11BF58DEC4BB5C2791781E2A7F6233446B77FAD9F2E4EAC31D7 6
2 42447B8B8A730AC62487C348B6906A2A13267A68320A608A07786F3296B9C4EB 5

In [38]:
cohort_0001 <- person |>
    filter(cohort == '2000/01')

In [39]:
mh_filtered_0001 <- mh_filtered |>
    semi_join(cohort_0001, by = "person_id") |>
    filter(MHReferral < as.Date("2017-09-01"))

In [40]:
mh_filtered_0001 |>
  count(person_id) |>       
  count(n) |>               
  rename(frequency = n, count = nn)

Storing counts in `nn`, as `n` already present in input
ℹ Use `name = "new_name"` to pick a new name.

  frequency count
1 1         5673
2 2          436
3 3          118
4 4           42
5 5           19
6 6            4
7 8            2

In [41]:
cohort_0102 <- person |>
    filter(cohort == '2001/02')

In [42]:
mh_filtered_0102 <- mh_filtered |>
    semi_join(cohort_0102, by = "person_id") |>
    filter(MHReferral < as.Date("2018-09-01"))

In [43]:
mh_filtered_0102 |>
  count(person_id) |>       
  count(n) |>               
  rename(frequency = n, count = nn)

Storing counts in `nn`, as `n` already present in input
ℹ Use `name = "new_name"` to pick a new name.

  frequency count
1  1        5745
2  2         531
3  3         213
4  4          54
5  5          19
6  6          11
7  8           2
8 10           1

In [45]:
mh_filtered_0102 |>
  count(person_id) |>
  filter(n > 9) |>
  arrange(desc(n))

  person_id                                                        n
1 77C5067B347B3B69B9800CBF7F886ED570ACF607BC22B3D3E3D1FACCBA23F9F1 10

In [47]:
mh_filtered_0102 |>
    filter(person_id == '77C5067B347B3B69B9800CBF7F886ED570ACF607BC22B3D3E3D1FACCBA23F9F1')

   person_id
1  77C5067B347B3B69B9800CBF7F886ED570ACF607BC22B3D3E3D1FACCBA23F9F1
2  77C5067B347B3B69B9800CBF7F886ED570ACF607BC22B3D3E3D1FACCBA23F9F1
3  77C5067B347B3B69B9800CBF7F886ED570ACF607BC22B3D3E3D1FACCBA23F9F1
4  77C5067B347B3B69B9800CBF7F886ED570ACF607BC22B3D3E3D1FACCBA23F9F1
5  77C5067B347B3B69B9800CBF7F886ED570ACF607BC22B3D3E3D1FACCBA23F9F1
6  77C5067B347B3B69B9800CBF7F886ED570ACF607BC22B3D3E3D1FACCBA23F9F1
7  77C5067B347B3B69B9800CBF7F886ED570ACF607BC22B3D3E3D1FACCBA23F9F1
8  77C5067B347B3B69B9800CBF7F886ED570ACF607BC22B3D3E3D1FACCBA23F9F1
9  77C5067B347B3B69B9800CBF7F886ED570ACF607BC22B3D3E3D1FACCBA23F9F1
10 77C5067B347B3B69B9800CBF7F886ED570ACF607BC22B3D3E3D1FACCBA23F9F1
   datereferral         MHReferral
1  18 Jun 2018 15:02:32 2018-06-18
2  20 Dec 2017 11:26:00 2017-12-20
3  06 Aug 2018 08:25:19 2018-08-06
4  07 Jan 2014 10:30:30 2014-01-07
5  27 Jan 2017 10:59:00 2017-01-27
6  01 Jun 2017 09:58:00 2017-06-01
7  03 Feb 2017 14:36:00 2017-02-03
8  21 Mar 2016 09:35:00 2016-03-21
9  01 Jun 2017 10:31:00 2017-06-01
10 19 Jul 2013 15:43:00 2013-07-19

In [51]:
mh_referrals <- rbind(mh_filtered_9899, mh_filtered_9900, mh_filtered_0001, mh_filtered_0102) |>
    select(-datereferral)

In [52]:
head(mh_referrals)

  person_id                                                        MHReferral
1 32454BB17C37F7065B3BCBF64C4D14B327B3D64C7AF28C0314469AFB12781E84 2014-09-10
2 E26E1F2A1F0D213B84FBBAD0A9F715C1FFF85507204FD7C6DC58E42D02FBE714 2014-08-18
3 7F9F55AADAE38F6F1E4B8F02E5051C00B81292EE1B0CA278E0871B72DE70A4AA 2014-08-18
4 5958C58EED04EB09709716F8FBB5ABF8220F0378137F829774ED4B23556BD19A 2014-09-05
5 B1F6E94ECCD2170D1207F595A99611869DB631191BBBFCB312AD2AA0034DF8EA 2014-01-23
6 0E0DEE39B051BEC9E5024AB99475C6E2F50DC4B9B71505AA8BE421293EC1BB24 2014-07-18

In [53]:
write.csv(mh_referrals, "data/mh_referrals.csv", row.names = FALSE)

# Inpatient Ward Admissions

In [54]:
inpatient_data = "CB_2489.tbl_SecondaryCare_ward_stay"

inpatient_table <- tbl(con, inpatient_data) |>
    select(person_id, stay_start_date, length_of_stay) |> 
    # convert to df
    collect()

Auto-refreshing stale OAuth token.

In [57]:
inpatient_filtered <- inpatient_table |>
    # filter destinations to target person ids
    semi_join(person, by = "person_id") |>
    unique()

In [115]:
inpatient_filtered |>
    arrange(stay_start_date)

      person_id
1     F463ADF06E5E74F420FA8B0CC64578C730B48D2A1BD10F22ED50FE938C42E21F
2     92D116B37F94927C3909E3A0DEC93313C6E9DC8AE59A74E3741A4EC31BE423F6
3     5DEB32EF0AC32EE350A65B88F618E29861012B390A6F8001BA406DA44788727B
4     F7925D2EF45550630AC5551706DDD163DDC976AC8F14A2F68506BA3B346C9482
5     F850A74E281BD8976AAC7660FC8012B54C19BA349AC227BBBCE205CE8B2EE470
6     B9BA8CA19EB91125A2D67B96A3AD8C7FAFB3B9400C431D270F1747A5B2CB3021
7     24A9A2DDFB03209798608768B0A03721528D0FF0E2156267BD7C0EED89A2CF92
8     ABC8CFD844B24C7CF61AC7A0ADC1E6120FB060EA6A898DCAABE543D0D08C2A62
9     622B00464CAC4229688514F6DE888BCE8EE2A93E3A74CB233E14E2F712953F10
10    93C9C7B8080DC785358A03AA02A6F16621203AE0F5D46DAA931300E0598E15CF
11    4081F584C42ABED8A522B6D168EE018F56B36C1FB687B7CF3F0ED3AFBA2190A0
12    4D7E7CCDF862ADAE8CF68EA1EFDCD2DF51FA3922CF10F3E547B611FEFF04D0BA
13    3B525035E2F6C5D41CB726E87ECF35982E71C45C84CF974EA50E9A05AB9F048D
14    8D91A1143318985A14E501F4D41CA676DCEA6A52B9F21645FE9262C5484DD713
15    B76A177B0FE3A5EFB1396C8EF5E8E04C8C645F95F7DB191E38ED54363094AA58
16    26667F0783BDFD35E3ADCB15F9A1378B622EB7464BE6A5EAA50203F26C177554
17    E4B2B7865E9DC022D3BD7E725A7A3D6A2B48D0C8CFE427B5BA57EA3D6B39A52A
18    B38B8FA67AB9E90BAFF692608643CBD90DFBEBED10400C09F2FBE16BC0C8E726
19    1625A5EC5A3C4CEC388E1031C1DD98A75B05C2AB8B14C2643B5A6C70878DB23D
20    033E241E6E358BB13B3B68DDA9EEEBC7C7551A6E91C4DDFA9C6FB58A5882F9FB
21    70D7CD50410EEEF2F1293EFFA2D94C9CEADCB87C1E6FACC50D158E4F53BD9C36
22    2681371F9D815B65E1504877012B6839C4EAF501C5C69B5BB2ED9624FE50989A
23    D936B88A7D437383A1D73D9814C01B1BC089509C8F36F91EB2AB7069747FF149
24    B8A4A739A3568C074B4DEA22532CCC93AB5C098CAC11CC961CC55820F12F2F05
25    743ABC3708DA649B45081E9903DD7E0D41A08903FAB5DC64578122193474F76C
26    2E4BA7DD2112816F4725A30A6D4EA2C5489EF99EB9510B0ADE65C8530542366A
27    B9BA8CA19EB91125A2D67B96A3AD8C7FAFB3B9400C431D270F1747A5B2CB3021
28    1522B21A999A08B377CE027119EE356B09819D4CAD205B541E5C5EF1C12178F7
29    4EB363E32EBE3E59C7B7BDFE14372E168C0FB7D18B80E276945A519D3F793BD6
30    C9D183CD90017E210F3E878C213C8B9E79F15D1433E329979615426B7282F527
⋮     ⋮
53143 9AF301056610273D18F7128FC25150DE72D6A4ECB58D8E8CE1F3BC047910391B
53144 104F73CC7B62B584115D0E2C6D54F996CA18118C787C245CD86FAE91CB0EE961
53145 4B438BA0A5066815E1EAF704963104B7F16768D9A5AE7BD26CF233EFE93C7931
53146 24622DBAC79721D51B3107B480E20AB812D3E582C90E01FF0D9AA23DE2F6D7D1
53147 0C563BFD18E15D102E2D2E7BDFED40C4F25C95FDF2FBDFFE4020344435A228B0
53148 BC5F1906BF7AD1324466525F59E95385DE6C38B63A43E958CCD2049C8BBC0EAE
53149 F3586475C95D95F1B31A6027A45819C8355DD87526CD8EFC3B320130A5D4FA0A
53150 2F6437E060393AA9AD1482880DFD7DBB3246319240293BDAD5FCEAD31D3DE24F
53151 E571ED3AAF818AEC754D104184F1E377734328BC32F87F7D5ACC84E46530A64A
53152 6A188F5FAE0B08E3945F8311DD0B93B21279E26E190BA44291F6591B5B1475E1
53153 F9E76B84DFFF602ED35028141E0020CA7A066AB7C73078459D3844ED2F09B7B7
53154 A17CC8FA0BD4CAA038F28C1230B85F907081B88221504847B8C5338F5B3DCA3F
53155 4F2BBA876C3E540907AB5CA79EF33C34DA4F43F9D1B4CDAD587046BE2B8CF3E4
53156 E462E93853858014265D9246E9342836A161979ACB2EEAA8C0758F95F50846A6
53157 275E3C2E3D4418E69B747433E8B8DFD2110A559323280F54E3E29977952950C8
53158 04B4402EF270097A80875183302AE92D893866BC39DFFC269F549342AF5ECC4D
53159 0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D
53160 597E6371C694BB3217FF8CDDECDD727B26A99F7CDE3C1E9CB9C231CC389CCCDC
53161 10CC0F07D1E7CD7F97666E28560904C78D061128E6E622D0AAD366CC3F6D2A7D
53162 78E2E234A55EC983E1FF6E2B032EAFFF27FB18BCFC74918724EAF88BA3EFE234
53163 23D932B87E3E0519A57EA8D9F5126A64930F43D9C1D1FE2DD9604D12C0F66C9D
53164 C5DCA44F6C2491CD11DCFF5EFD29D872C942863AD65363681D7A64B7DB680FC8
53165 DB08B5B4D97D567714590290A593408D720C8CBE65C414560C97F59AFFC2DC77
53166 7ADF0355ED01B36873772F840B16F4D41B74A0DCE4BD112FE32C68D98B8FECF5
53167 45513910413B92CB82112981D535F95A5B9C29D40104F45A9D711A8915261C0F
53168 470D0F0C9F143A2288FF914935988AF7F6AF7E2B99114BAD236A0E2A62BF4F3D
53169 FF4BAE45489DDBBE149ECB9F0B513F271B28AE2DFD7AA9B241931D5FCCCD3D8D
53170 4F2BBA876C3E540907AB5CA79EF33C34DA4F43F9D1B4CDAD587046BE2B8CF3E4
53171 F3586475C95D95F1B31A6027A45819C8355DD87526CD8EFC3B320130A5D4FA0A
53172 2F6437E060393AA9AD1482880DFD7DBB3246319240293BDAD5FCEAD31D3DE24F
      stay_start_date length_of_stay
1     2006-12-29      3
2     2006-12-30      2
3     2006-12-30      2
4     2006-12-31      1
5     2006-12-31      1
6     2007-01-01      2
7     2007-01-01      1
8     2007-01-01      3
9     2007-01-02      2
10    2007-01-02      2
11    2007-01-03      2
12    2007-01-03      2
13    2007-01-03      1
14    2007-01-03      1
15    2007-01-03      1
16    2007-01-03      3
17    2007-01-03      3
18    2007-01-04      2
19    2007-01-04      2
20    2007-01-04      2
21    2007-01-04      1
22    2007-01-04      1
23    2007-01-04      1
24    2007-01-04      1
25    2007-01-05      2
26    2007-01-05      2
27    2007-01-05      2
28    2007-01-05      1
29    2007-01-05      3
30    2007-01-06      2
⋮     ⋮               ⋮
53143 2024-08-12      1
53144 2024-08-12      2
53145 2024-08-12      2
53146 2024-08-12      2
53147 2024-08-12      2
53148 2024-08-12      1
53149 2024-08-12      2
53150 2024-08-12      2
53151 2024-08-13      1
53152 2024-08-13      1
53153 2024-08-13      1
53154 2024-08-13      1
53155 2024-08-13      1
53156 2024-08-13      1
53157 2024-08-13      1
53158 2024-08-13      1
53159 2024-08-13      1
53160 2024-08-13      1
53161 2024-08-13      1
53162 2024-08-13      1
53163 2024-08-13      1
53164 2024-08-13      1
53165 2024-08-13      1
53166 2024-08-13      1
53167 2024-08-13      1
53168 2024-08-13      2
53169 2024-08-13      2
53170 2024-08-13      2
53171 2024-08-13      1
53172 2024-08-13      2

In [117]:
inpatient_filtered_9899 <- inpatient_filtered |>
    semi_join(cohort_9899, by = "person_id") |>
    filter(stay_start_date < as.Date("2015-09-01")) |>
    filter(stay_start_date >= as.Date("2007-09-01"))

In [118]:
inpatient_filtered_9899 |>
  count(person_id) |>       
  count(n) |>               
  rename(frequency = n, count = nn)

Storing counts in `nn`, as `n` already present in input
ℹ Use `name = "new_name"` to pick a new name.

   frequency count
1    1       1073
2    2        321
3    3        145
4    4         37
5    5         30
6    6         12
7    7         11
8    8         10
9    9          1
10  10          2
11  11          5
12  13          2
13  15          1
14  16          1
15  20          1
16  28          1
17  80          1
18 106          1
19 110          1
20 124          1

In [119]:
inpatient_filtered_9900 <- inpatient_filtered |>
    semi_join(cohort_9900, by = "person_id") |>
    filter(stay_start_date < as.Date("2016-09-01")) |>
    filter(stay_start_date >= as.Date("2008-09-01"))

In [120]:
inpatient_filtered_9900 |>
  count(person_id) |>       
  count(n) |>               
  rename(frequency = n, count = nn)

Storing counts in `nn`, as `n` already present in input
ℹ Use `name = "new_name"` to pick a new name.

   frequency count
1    1       1071
2    2        305
3    3        106
4    4         52
5    5         24
6    6          9
7    7          8
8    8         10
9    9          1
10  10          4
11  11          1
12  12          2
13  13          1
14  14          1
15  16          1
16  17          1
17  19          1
18  21          1
19  26          1
20  27          1
21 108          1
22 113          1
23 114          1

In [123]:
inpatient_filtered_0001 <- inpatient_filtered |>
    semi_join(cohort_0001, by = "person_id") |>
    filter(stay_start_date < as.Date("2017-09-01")) |>
    filter(stay_start_date >= as.Date("2009-09-01"))

In [122]:
inpatient_filtered_0001 |>
  count(person_id) |>       
  count(n) |>               
  rename(frequency = n, count = nn)

Storing counts in `nn`, as `n` already present in input
ℹ Use `name = "new_name"` to pick a new name.

   frequency count
1    1       1102
2    2        386
3    3        121
4    4         70
5    5         33
6    6         18
7    7         10
8    8          9
9    9         12
10  10          4
11  12          2
12  13          1
13  18          2
14  19          1
15  20          1
16  21          1
17  36          1
18  46          1
19 117          1

In [124]:
inpatient_filtered_0102 <- inpatient_filtered |>
    semi_join(cohort_0102, by = "person_id") |>
    filter(stay_start_date < as.Date("2018-09-01")) |>
    filter(stay_start_date >= as.Date("2010-09-01"))

In [125]:
inpatient_filtered_0102 |>
  count(person_id) |>       
  count(n) |>               
  rename(frequency = n, count = nn)

Storing counts in `nn`, as `n` already present in input
ℹ Use `name = "new_name"` to pick a new name.

   frequency count
1    1       1022
2    2        308
3    3        138
4    4         47
5    5         34
6    6          7
7    7         10
8    8         11
9    9          3
10  10          3
11  11          1
12  12          3
13  13          6
14  15          1
15  16          1
16  17          1
17  18          1
18  21          1
19  23          1
20  24          1
21  25          1
22  27          1
23  45          1
24  58          1
25 104          1
26 107          1
27 115          1

In [126]:
inpatient_stays <- rbind(inpatient_filtered_9899, inpatient_filtered_9900, inpatient_filtered_0001, inpatient_filtered_0102)

In [127]:
head(inpatient_stays)

  person_id
1 01E2844C0F45245F1345B5AA5E94793B95F67AEE51E4469B1576CE4064799483
2 D5EDDC33A87E4B5FAAE509E44B645A41DAB4DEF3D4B2B11775C39BEF1E3B79D5
3 39C36EAA03BBF80F9A626ECD00FA24D6167311EA3EAA27CEFFE2B37D7817F6CC
4 9D7BBB097EAD621D91C14965F614BD4573960C701384581B662362256879AF96
5 A4324797DBF898025A89D6A94779F59EB3DC6D24607D051A75CDEA5B51B1D3F9
6 1C0DE5273D202D08A0207914E83D87825D98FCEB618F46B2087CAFA032D09191
  stay_start_date length_of_stay
1 2007-09-01      2
2 2007-09-11      2
3 2007-09-18      2
4 2007-09-19      2
5 2007-09-24      2
6 2007-10-01      2

In [128]:
write.csv(inpatient_stays, "data/inpatient_stays.csv", row.names = FALSE)

# A&E Admissions - Cant use, data from 2017 onwards

In [70]:
AE_data = "CB_2489.tbl_SecondaryCare_ae_nautilus"

AE_table <- tbl(con, AE_data) |>
    select(person_id, tbl_SecondaryCare_ae_nautilus_start_date, attendance_category_Description) |> 
    # convert to df
    collect()

Auto-refreshing stale OAuth token.

In [72]:
head(AE_table)

  person_id
1 5AAAC46458805915BE03E39E2EE548428C3427A64D919B30D6F9E42C70C45044
2 5C1E6B4663EE26D02BE833DCAA4C0B8C7F78AFAD286830F58C8D41358C20C3BD
3 AF26FF8CE455CC63945131643FD33864D7B7017FE2E171C89DCEC7D0B24BFCFD
4 D6CDC2BB53B9F7A2F8945C63DF885FDE8549D31C47383F74AD7D6714CAD91F0C
5 EFBD06ECD8259E20EB320817CE841DE33E4E5C71CCE9CC8DDB1A2BD722E99E91
6 8C0B8CB3911D88B9344889562B7A05517AB18D1C418E51B3B957DDD32930EBE2
  tbl_SecondaryCare_ae_nautilus_start_date attendance_category_Description
1 2021-10-10 04:01:00                      First A&E Attendance
2 2021-11-05 05:00:00                      First A&E Attendance
3 2023-04-24 22:51:00                      First A&E Attendance
4 2023-05-14 02:03:00                      First A&E Attendance
5 2024-01-01 03:00:00                      First A&E Attendance
6 2024-02-10 01:21:00                      First A&E Attendance

In [73]:
unique(AE_table$attendance_category_Description)

[1] "First A&E Attendance"             "Follow Up Attendance - Planned"
[3] "Unplanned - F Up Another ED"      "Unplanned - F Up This ED"
[5] "Follow Up Attendance - Unplanned" "DOA"

In [98]:
AE_filtered <- AE_table |>
    # filter destinations to target person ids
    semi_join(person, by = "person_id") |>
    unique()

In [114]:
AE_filtered |>
    arrange(tbl_SecondaryCare_ae_nautilus_start_date)

      person_id
1     936FEBEFFBDBA17B7FFDDE1D655BE365E0E45BB136C5536D760086339B63B543
2     FA8F3FE65CEDDE1CAADBFF0F235E53AECC56EFBDCE6DA24CBDBF88A1F6B35063
3     E27CDB12A315A24D1BDCCC488825B17495CEEB78C19F07059168EC79547FF53E
4     FF0790E5C3F880E4CE48A311A2A9626393FCDD64E64C18D540F90A985C572BB7
5     F23CEA945D0FC641A7565D9670C2B2C24BDE11F4759F5B5DF077262F4796DEE7
6     2BD7879A13633D7966EFAF30285ACD97D7E4F31DC1316581C867A3CABBB00E9D
7     987AC57102409F0AF5A6C3DED3E661AEFF4F19D294AFC4E34385093F1D6AB74D
8     A4197B87D8D37C64E71CDAF4B4BC4D7265DBD544084B365DB22E17B405B68A86
9     12DC2837BFCA3A379F508DA43C508DCC7E7F2F69744543303B87BF84E1048CA3
10    6EC71241920766AF5E69CD64C1EA7D84A3CBB26048EA7696CE21867064A3B735
11    9E7F084C26E8360C4280A2AE41349835635F02B94E5540978252F3F025950A5B
12    E71099CDD86F5681E1D1D3BD5407D2615A05496FFB2D576195008E530F8F49DD
13    740198D969C0A40663C28BB15A145A9953CDA3CB549CDA7F28AA249977042838
14    0FF858039D9299D1E0460A47298205231D52A959935AE1D6518A5CB361144FCD
15    4CAF02F92DBEE660F79772144E77C88CD8367B555DD4BD12010A14E27574BFFC
16    ADA171F70F6705DFB5C4CC4DC1F3D4F777D1EBD39AD6FBB43F874832CFEE3C9A
17    11268124FD7DC7D3F23D2D111EE03C18D2E5E4DA25730AD1972F0B3D6A04AB40
18    7115C0395D2DA8A1E883FECE85F984E17B6E0199FD0F9B725EC0C0F0CFE24303
19    BAE6A88E12E7A32C19DB7C80830D3E3F5553DB8E5475FFD96C2D234A992E4A40
20    658F5ACDB521DF6423CD8D4422126CA82CBF242C57ED871C1E6165780026CA33
21    2EC9022CE298D499CBF998607A3D808A8D6A3E9A9DC5D8FFDA8D32B7BC6332B7
22    0A0123A4852B16EA2065708C02BB87FF32BE66DAB951FAF425E672F0B111EF30
23    9BB7629F24AB5600F26A2755E0B4EDC0817BDAFFFA34A7FE6785108643F5E1D6
24    4CAF02F92DBEE660F79772144E77C88CD8367B555DD4BD12010A14E27574BFFC
25    8D7B5D29B2400F6AA56C6A9FC46E2C7968DDFAC57B742606AC8DE02E7816A808
26    9538601D513EA1AB7A8FDC522D3FB0CBB9D1918820EB364853AA7BCF63B5B498
27    D57F7F1A3EC1B5BDF358B6808265C9D092B1BF512AD33B209F21678B7AE8B750
28    8CF9D0B5C88DEFAEB77185E90D7EE69016235F8F91FE114CF3E7B76B04B5CA68
29    BFADC2763CF976749F17508B0EE6BF04C36279D027DD7882EDC287FD76A72B7A
30    5594D296ACFA000E80E0691DEA51919F05339DEE2CB5ABA207837F791219F746
⋮     ⋮
43694 A2CB831A0752B99A6A4DF4B215BD0CC235AD80FB77783DD1C2CDBBC95FC6049C
43695 E6E350D26C360D47D045938D0460655B4EE5E460B487677CA60393B031389C64
43696 C0165B9C40D37D60D9CAA6139A98AEB508C13176AE80917B3AB27CB5D1D7F421
43697 09C3CD4401B0BC06A92B9B51E680FA96338AAD59028077418F8E9AEF581D8E20
43698 0CA03487441073EBE8940A2E3610BE5B5E89F725684E64461627EC9062C6153E
43699 A5B438A927F9E88FA93B194366FA4762963ED216B42AF90DD661101A5449F0E2
43700 178129250F5BC85404CBDC7E2D1B01EE69BEAD73914EA4D951216E3AB5608654
43701 470D0F0C9F143A2288FF914935988AF7F6AF7E2B99114BAD236A0E2A62BF4F3D
43702 A6B730A8689603C185FC8F636A12789AF56082C308BB454F7AB53F8AC2D3F8F1
43703 0CA03487441073EBE8940A2E3610BE5B5E89F725684E64461627EC9062C6153E
43704 230D403A693A34FEAC0CB1D150B6739234BD116BAC4101E1F99A6827AC932F71
43705 31D783A8BD34A7F7C4DF58C97E5ECB466BE8D8C7927D7BBF56E39AD28501B0E5
43706 F2302F1110FA9D13F15DE441B2712D8292F6D6988FEE732AC62E79077AF18481
43707 9966FEABB1303B23D951B74C56143A3FEC3CF970B4727AFFE9475A077188C946
43708 6D68E5DEB18FB81F9ED6719FFD8C92E0D678B90AA6940D9E51D973C40D677D5A
43709 585BBCBE6C3CC4C1108B9BF83ED937CDF85475331FB3859AB4EC5FFCBC99DC2D
43710 C95825670F4F51FADB6BBCB639BF347BE232D69CF3845BB3CF4955D0405CA31A
43711 51349588214C17FEC8C425F75FE6AA7E68CB33DE6A059A2F59F790CC0862B834
43712 784E6E939973B35B78210C14A8892280D6F6100CC4D9E24F5BF771795AF70687
43713 A29EA29AFC795FD7F60A7B62819BA35F7B627C60EDB00FB3ECD3BFADB2CF23CB
43714 009A51362A2BA4928B6EAB3312662A834ED9A785B6893479B88E7D311D96F5D0
43715 0CA03487441073EBE8940A2E3610BE5B5E89F725684E64461627EC9062C6153E
43716 999C5A32C42DD6A3FD02233FEBEC48BDD0905E30A23283BC514DABFA18AFEF98
43717 39FCFA88EC3FBD290E2E1C5E0B157E3A26353A75D5DE20C1CAD68E6528E55C5B
43718 B1D26F10DF17E360114CD8EC996429831AE2CFA796B01BB476B12404D7D0FF99
43719 DF76A7074D22868B6E3B35F44E3890358440B7FFC1B81BDBCC2B3808BFBEF96A
43720 AFF6CEE0A4191BE9A9BA42F6B4BCAFE706F3A19FB27564A5AC86EC4C168EA732
43721 7944794312813FB6AF754B9BE1C47963ED43869DD64997789ECED52B84D1CF82
43722 CDE857A34561A3BC7860530F50D6353F856510C2FE42830964E31D061C2D9C42
43723 6E27CA29931F309605A7C7275F28AD3E09FE10CF40F6A36276AD33154BED25AE
      tbl_SecondaryCare_ae_nautilus_start_date description          start_date
1     2016-06-11 14:00:00                      First A&E Attendance 2016-06-11
2     2017-01-26 09:03:00                      First A&E Attendance 2017-01-26
3     2017-02-05 14:00:00                      First A&E Attendance 2017-02-05
4     2017-06-23 11:00:00                      First A&E Attendance 2017-06-23
5     2017-06-25 18:00:00                      First A&E Attendance 2017-06-25
6     2017-08-22 23:01:00                      First A&E Attendance 2017-08-22
7     2017-08-23 10:14:00                      First A&E Attendance 2017-08-23
8     2017-08-28 23:01:00                      First A&E Attendance 2017-08-28
9     2017-08-30 08:00:00                      First A&E Attendance 2017-08-30
10    2017-09-18 14:00:00                      First A&E Attendance 2017-09-18
11    2017-09-20 11:00:00                      First A&E Attendance 2017-09-20
12    2017-09-21 09:00:00                      First A&E Attendance 2017-09-21
13    2017-09-22 07:00:00                      First A&E Attendance 2017-09-22
14    2017-09-22 13:00:00                      First A&E Attendance 2017-09-22
15    2017-09-22 17:11:00                      First A&E Attendance 2017-09-22
16    2017-09-22 17:43:00                      First A&E Attendance 2017-09-22
17    2017-09-22 22:52:00                      First A&E Attendance 2017-09-22
18    2017-09-22 23:21:00                      First A&E Attendance 2017-09-22
19    2017-09-23 05:09:00                      First A&E Attendance 2017-09-23
20    2017-09-23 05:51:00                      First A&E Attendance 2017-09-23
21    2017-09-23 07:30:00                      First A&E Attendance 2017-09-23
22    2017-09-23 07:35:00                      First A&E Attendance 2017-09-23
23    2017-09-23 10:29:00                      First A&E Attendance 2017-09-23
24    2017-09-23 11:43:00                      First A&E Attendance 2017-09-23
25    2017-09-23 12:59:00                      First A&E Attendance 2017-09-23
26    2017-09-23 16:07:00                      First A&E Attendance 2017-09-23
27    2017-09-23 16:20:00                      First A&E Attendance 2017-09-23
28    2017-09-23 16:45:00                      First A&E Attendance 2017-09-23
29    2017-09-23 18:35:00                      First A&E Attendance 2017-09-23
30    2017-09-23 19:00:00                      First A&E Attendance 2017-09-23
⋮     ⋮                                        ⋮                    ⋮
43694 2024-08-13 06:06:00                      First A&E Attendance 2024-08-13
43695 2024-08-13 07:42:00                      First A&E Attendance 2024-08-13
43696 2024-08-13 07:50:00                      First A&E Attendance 2024-08-13
43697 2024-08-13 09:07:00                      First A&E Attendance 2024-08-13
43698 2024-08-13 09:13:00                      First A&E Attendance 2024-08-13
43699 2024-08-13 09:29:00                      First A&E Attendance 2024-08-13
43700 2024-08-13 10:53:00                      First A&E Attendance 2024-08-13
43701 2024-08-13 13:32:00                      First A&E Attendance 2024-08-13
43702 2024-08-13 13:35:00                      First A&E Attendance 2024-08-13
43703 2024-08-13 14:32:00                      First A&E Attendance 2024-08-13
43704 2024-08-13 15:26:00                      First A&E Attendance 2024-08-13
43705 2024-08-13 17:35:00                      First A&E Attendance 2024-08-13
43706 2024-08-13 17:49:00                      First A&E Attendance 2024-08-13
43707 2024-08-13 19:27:00                      First A&E Attendance 2024-08-13
43708 2024-08-13 19:57:00                      First A&E Attendance 2024-08-13
43709 2024-08-13 22:05:00                      First A&E Attendance 2024-08-13
43710 2024-08-13 23:32:00                      First A&E Attendance 2024-08-13
43711 2024-08-14 00:45:00                      First A&E Attendance 2024-08-14
43712 2024-08-14 07:27:00                      First A&E Attendance 2024-08-14
43713 2024-08-14 07:59:00                      First A&E Attendance 2024-08-14
43714 2024-08-14 08:12:00                      First A&E Attendance 2024-08-14
43715 2024-08-14 09:34:00                      First A&E Attendance 2024-08-14
43716 2024-08-14 10:09:00                      First A&E Attendance 2024-08-14
43717 2024-08-14 13:12:00                      First A&E Attendance 2024-08-14
43718 2024-08-14 14:04:00                      First A&E Attendance 2024-08-14
43719 2024-08-14 14:06:00                      First A&E Attendance 2024-08-14
43720 2024-08-14 14:54:00                      First A&E Attendance 2024-08-14
43721 2024-08-14 16:22:00                      First A&E Attendance 2024-08-14
43722 2024-08-14 19:09:00                      First A&E Attendance 2024-08-14
43723 2024-08-14 21:45:00                      First A&E Attendance 2024-08-14

In [100]:
unique(AE_filtered$attendance_category_Description)

[1] "First A&E Attendance"             "Follow Up Attendance - Planned"
[3] "Unplanned - F Up Another ED"      "Unplanned - F Up This ED"
[5] "Follow Up Attendance - Unplanned" "DOA"

In [101]:
AE_filtered |>
    filter(attendance_category_Description == 'DOA')

  person_id
1 50233BFE7AA9F24DCBC570C4C244A30508E6AC112E883735CFA39CE992025CB4
  tbl_SecondaryCare_ae_nautilus_start_date attendance_category_Description
1 2018-05-21 12:42:00                      DOA

In [102]:
AE_filtered <- AE_filtered |>
    rename(description = attendance_category_Description) |>
    mutate(start_date = as.Date(tbl_SecondaryCare_ae_nautilus_start_date, format = "%Y-%m-%d %H:%M:%S"))

In [103]:
head(AE_filtered)

  person_id
1 5AAAC46458805915BE03E39E2EE548428C3427A64D919B30D6F9E42C70C45044
2 AF26FF8CE455CC63945131643FD33864D7B7017FE2E171C89DCEC7D0B24BFCFD
3 13E72B651A7665C776107E29C0475E0148ED3BF9023AAAF6B42C42086C5F4C64
4 DF21EE69940BE6CD6ACAF925C723AD695D371F91B0D695B3C86A954E43DF6350
5 526A9DD02760CA6A710A6A95FE76D797889BD3BFBAAEEDE5AD18868689EB4D81
6 02134CA5E4A0C5B3CCBE26153D38614A1A3E87CD16ED88BBCE6A53628D8EA0A5
  tbl_SecondaryCare_ae_nautilus_start_date description          start_date
1 2021-10-10 04:01:00                      First A&E Attendance 2021-10-10
2 2023-04-24 22:51:00                      First A&E Attendance 2023-04-24
3 2023-12-17 03:16:00                      First A&E Attendance 2023-12-17
4 2021-12-06 19:03:00                      First A&E Attendance 2021-12-06
5 2022-11-09 22:49:00                      First A&E Attendance 2022-11-09
6 2024-08-09 16:58:00                      First A&E Attendance 2024-08-09

In [106]:
AE_filtered_9899 <- AE_filtered |>
    semi_join(cohort_9899, by = "person_id")

In [108]:
AE_filtered_9899 |>
    arrange(start_date)

      person_id
1     FA8F3FE65CEDDE1CAADBFF0F235E53AECC56EFBDCE6DA24CBDBF88A1F6B35063
2     2BD7879A13633D7966EFAF30285ACD97D7E4F31DC1316581C867A3CABBB00E9D
3     A4197B87D8D37C64E71CDAF4B4BC4D7265DBD544084B365DB22E17B405B68A86
4     6EC71241920766AF5E69CD64C1EA7D84A3CBB26048EA7696CE21867064A3B735
5     740198D969C0A40663C28BB15A145A9953CDA3CB549CDA7F28AA249977042838
6     11268124FD7DC7D3F23D2D111EE03C18D2E5E4DA25730AD1972F0B3D6A04AB40
7     0FF858039D9299D1E0460A47298205231D52A959935AE1D6518A5CB361144FCD
8     1F792FAB6FAC0DBB1920587C43291EEA35746B7222865048B95C36AC19DE2D8E
9     9538601D513EA1AB7A8FDC522D3FB0CBB9D1918820EB364853AA7BCF63B5B498
10    C5F5BE463C2EBACFDD063DADD086313FA474EC5920DC1B1D64560818C651086B
11    7DCE6870794E605BF93A32839000D2578CB609AA23DCAB8E47738B321D1429D1
12    8CF9D0B5C88DEFAEB77185E90D7EE69016235F8F91FE114CF3E7B76B04B5CA68
13    BAE6A88E12E7A32C19DB7C80830D3E3F5553DB8E5475FFD96C2D234A992E4A40
14    5594D296ACFA000E80E0691DEA51919F05339DEE2CB5ABA207837F791219F746
15    E0DAE54C3F760656BEF18C6C4A28FE3CF47A1CEF5ABF705F4A4305FB89BDFDFF
16    58BD5ECF8AE9E4B14E0404992ED486CE19AC0A2DF851777C839B640A01EA9D99
17    3D15B149F4B5DEA02EAD28304650426FF81E503213A8DCD02A3D1171826E4633
18    126F1F4B6846A3C975A68308D7BB298E12B61849F836483F3672EEFA669666DA
19    3A5EE36F94A7E394DC70D640E91DD6418F805A58F1AE0870A9A78F892BD4CE1C
20    EEEDADDB9970AAC62A283211B12B5484CDAE2A5A89D1017D52F2832F2E5B07EC
21    0D4C08E6BAF125D2A7271DE9822D8AE37679C6A496C198B4275C66CF2DFF3E99
22    06252746E9E76276CA311233865CACD42D0C5D4378C01C543A9A4AD0E7F47543
23    E7B494D94283743E10957C1C81130DC884F0D5AF7F00BEA389D5F41D4AB88C55
24    E1AB19121A9D9C97DC516E2188B2952B7923B9B3E5DCC1A711AA4C62C127B25F
25    0894108CFFDAEEE90193251B01D64D46B2E90B055B3B18440A3F39C54E455F23
26    013B9BA4BD97CDC7AE586437E9E9BB2C0F9C0A199AB5AB5B52F8B12D5E93A9A0
27    922E9634EEE55BD332F3B411416233FC832B038F6571568241BA6846A717F0DE
28    144D58DEE9D7B4D67B440D99419E61CBCBC21FDF3FCBE395E4C7E78964E973B1
29    0C95F0A737E5C8A92124A2DA2C48F17E9D61180632DB38F1124E3F25F6474DA7
30    E0DAE54C3F760656BEF18C6C4A28FE3CF47A1CEF5ABF705F4A4305FB89BDFDFF
⋮     ⋮
10905 D048F05E20B070EC80D300EB22A2CB509FE9DA50DB03130EEC8AC2FF13ACE2BB
10906 4A2B5B6FD7E965DE6E8BDC6BF95B86FB6535333F7C6E343D3C062B079725E682
10907 81DCFB29BC0EA44DCFDDD9FC703363E2C517F2916C4D1E90426C9381DDDA1B57
10908 8AC87291B6E908F3F3BD9CF09542E3C07E9C76C9E976BB91C6681DB02A220FC2
10909 232646FA9AF2B02051001EE44C5ED1C131124F0EC314035FF1484C116EAB67A2
10910 282D6046010A299DB0BEC9498BE89D5EF38042F1B76555190CAB376471C3A60A
10911 31872EE9B07EDA5548C1191F5B6D6905E5E967AE11A75AC8CA38B6E158CE9DF6
10912 4464AD34164105B72DD1B38AF047E3199CE74B2DF4A9AB242C764F11DE957DAE
10913 CF806CC54C2725DCFDDE9DFC50BB108025097D189E6E966ACB13D3D09716D309
10914 C253BD357FAFB41DB169996F5629DFDD5662BCD7733F5B66706C9DED36DB6D27
10915 3183FEF17D68BF430305C8B59673F6DCE9A72E368B7BDB8411D6CA40CCF3D8D2
10916 EEBB1D6988BD8569F4A8F3DEF0C815F5461BC81CA154ABF2DE00083F445E39E9
10917 98758CE0A5152423E99BA75499173735C899D546C3F3E46EEF2B8109817C8C28
10918 29022CC1B0A32A77A94CF83F8561C8F9991E47A2F5992DCB2AEFFC6D62F46AA7
10919 BF597657B5429B487FBCD46D27AB0E9446274C929BC612F574DBE1D9ADF7F29A
10920 6747CB5EE668431AA10E58055ED75D1E59B3C00964CEAB32D2C01A2E4BA04399
10921 4966945467842B3AEAADDEF5891BA30B5A86493968AC91FDF37080AFD383254D
10922 FA890862F1349B274B835667E6C65362BE858B73EE83A014D39B01736B2E6349
10923 BF17D781219EC5ED90C558119C439D80A9C8EC4EA6BAD2100C2572B4C809A771
10924 4B438BA0A5066815E1EAF704963104B7F16768D9A5AE7BD26CF233EFE93C7931
10925 230D403A693A34FEAC0CB1D150B6739234BD116BAC4101E1F99A6827AC932F71
10926 0CA03487441073EBE8940A2E3610BE5B5E89F725684E64461627EC9062C6153E
10927 09C3CD4401B0BC06A92B9B51E680FA96338AAD59028077418F8E9AEF581D8E20
10928 0CA03487441073EBE8940A2E3610BE5B5E89F725684E64461627EC9062C6153E
10929 178129250F5BC85404CBDC7E2D1B01EE69BEAD73914EA4D951216E3AB5608654
10930 0CA03487441073EBE8940A2E3610BE5B5E89F725684E64461627EC9062C6153E
10931 DF76A7074D22868B6E3B35F44E3890358440B7FFC1B81BDBCC2B3808BFBEF96A
10932 B1D26F10DF17E360114CD8EC996429831AE2CFA796B01BB476B12404D7D0FF99
10933 A29EA29AFC795FD7F60A7B62819BA35F7B627C60EDB00FB3ECD3BFADB2CF23CB
10934 999C5A32C42DD6A3FD02233FEBEC48BDD0905E30A23283BC514DABFA18AFEF98
      tbl_SecondaryCare_ae_nautilus_start_date description          start_date
1     2017-01-26 09:03:00                      First A&E Attendance 2017-01-26
2     2017-08-22 23:01:00                      First A&E Attendance 2017-08-22
3     2017-08-28 23:01:00                      First A&E Attendance 2017-08-28
4     2017-09-18 14:00:00                      First A&E Attendance 2017-09-18
5     2017-09-22 07:00:00                      First A&E Attendance 2017-09-22
6     2017-09-22 22:52:00                      First A&E Attendance 2017-09-22
7     2017-09-22 13:00:00                      First A&E Attendance 2017-09-22
8     2017-09-23 22:15:00                      First A&E Attendance 2017-09-23
9     2017-09-23 16:07:00                      First A&E Attendance 2017-09-23
10    2017-09-23 21:01:00                      First A&E Attendance 2017-09-23
11    2017-09-23 23:11:00                      First A&E Attendance 2017-09-23
12    2017-09-23 16:45:00                      First A&E Attendance 2017-09-23
13    2017-09-23 05:09:00                      First A&E Attendance 2017-09-23
14    2017-09-23 19:00:00                      First A&E Attendance 2017-09-23
15    2017-09-24 21:12:00                      First A&E Attendance 2017-09-24
16    2017-09-24 13:57:00                      First A&E Attendance 2017-09-24
17    2017-09-24 23:11:00                      First A&E Attendance 2017-09-24
18    2017-09-24 03:55:00                      First A&E Attendance 2017-09-24
19    2017-09-24 18:00:00                      First A&E Attendance 2017-09-24
20    2017-09-24 08:28:00                      First A&E Attendance 2017-09-24
21    2017-09-24 12:30:00                      First A&E Attendance 2017-09-24
22    2017-09-26 18:11:00                      First A&E Attendance 2017-09-26
23    2017-09-26 12:27:00                      First A&E Attendance 2017-09-26
24    2017-09-26 01:55:00                      First A&E Attendance 2017-09-26
25    2017-09-26 17:00:00                      First A&E Attendance 2017-09-26
26    2017-09-26 17:30:00                      First A&E Attendance 2017-09-26
27    2017-09-27 22:27:00                      First A&E Attendance 2017-09-27
28    2017-09-27 02:58:00                      First A&E Attendance 2017-09-27
29    2017-09-27 11:09:00                      First A&E Attendance 2017-09-27
30    2017-09-27 20:20:00                      First A&E Attendance 2017-09-27
⋮     ⋮                                        ⋮                    ⋮
10905 2024-08-08 22:06:00                      First A&E Attendance 2024-08-08
10906 2024-08-08 10:02:00                      First A&E Attendance 2024-08-08
10907 2024-08-08 14:30:00                      First A&E Attendance 2024-08-08
10908 2024-08-08 21:08:00                      First A&E Attendance 2024-08-08
10909 2024-08-09 07:50:00                      First A&E Attendance 2024-08-09
10910 2024-08-09 12:41:00                      First A&E Attendance 2024-08-09
10911 2024-08-10 14:06:00                      First A&E Attendance 2024-08-10
10912 2024-08-10 18:49:00                      First A&E Attendance 2024-08-10
10913 2024-08-10 14:02:00                      First A&E Attendance 2024-08-10
10914 2024-08-11 06:18:00                      First A&E Attendance 2024-08-11
10915 2024-08-11 11:16:00                      First A&E Attendance 2024-08-11
10916 2024-08-11 09:25:00                      First A&E Attendance 2024-08-11
10917 2024-08-11 22:04:00                      First A&E Attendance 2024-08-11
10918 2024-08-11 21:30:00                      First A&E Attendance 2024-08-11
10919 2024-08-12 18:22:00                      First A&E Attendance 2024-08-12
10920 2024-08-12 12:45:00                      First A&E Attendance 2024-08-12
10921 2024-08-12 14:43:00                      First A&E Attendance 2024-08-12
10922 2024-08-12 09:58:00                      First A&E Attendance 2024-08-12
10923 2024-08-12 11:16:00                      First A&E Attendance 2024-08-12
10924 2024-08-12 11:12:00                      First A&E Attendance 2024-08-12
10925 2024-08-13 15:26:00                      First A&E Attendance 2024-08-13
10926 2024-08-13 14:32:00                      First A&E Attendance 2024-08-13
10927 2024-08-13 09:07:00                      First A&E Attendance 2024-08-13
10928 2024-08-13 09:13:00                      First A&E Attendance 2024-08-13
10929 2024-08-13 10:53:00                      First A&E Attendance 2024-08-13
10930 2024-08-14 09:34:00                      First A&E Attendance 2024-08-14
10931 2024-08-14 14:06:00                      First A&E Attendance 2024-08-14
10932 2024-08-14 14:04:00                      First A&E Attendance 2024-08-14
10933 2024-08-14 07:59:00                      First A&E Attendance 2024-08-14
10934 2024-08-14 10:09:00                      First A&E Attendance 2024-08-14

In [104]:
AE_filtered_9899 <- AE_filtered |>
    semi_join(cohort_9899, by = "person_id") |>
    filter(start_date < as.Date("2015-09-01")) |>
    select(-tbl_SecondaryCare_ae_nautilus_start_date)

In [105]:
AE_filtered_9899 |>
  count(person_id) |>       
  count(n) |>               
  rename(frequency = n, count = nn)

Storing counts in `nn`, as `n` already present in input
ℹ Use `name = "new_name"` to pick a new name.

     frequency count

In [111]:
AE_filtered_9900 <- AE_filtered |>
    semi_join(cohort_9900, by = "person_id")

In [109]:
AE_filtered_9900 <- AE_filtered |>
    semi_join(cohort_9900, by = "person_id") |>
    filter(start_date < as.Date("2016-09-01"))

In [112]:
AE_filtered_9900 |>
    arrange(start_date)

      person_id
1     987AC57102409F0AF5A6C3DED3E661AEFF4F19D294AFC4E34385093F1D6AB74D
2     ADA171F70F6705DFB5C4CC4DC1F3D4F777D1EBD39AD6FBB43F874832CFEE3C9A
3     27A1BFC4DAB6A9753E6D66E746259DBA1BE903D13CA1D8D79334D40284A019A7
4     4BC61F8975ABBD71D532B841CF16265957F5F453C37240D3BA25BB7A92601368
5     3F01C0C4497816A2391716FDA15DA1BC577A4E8B272453BC325459C6819DFED2
6     71C2445B16276AFCBEE2F6D2731F6459CF2D40D55D5941D3B8218DE70A987EDF
7     8703E6AF05916E33A89797A0EC21128D1853D448E29D6C2C2D9D0F298817C275
8     162EBF3A92B1EC9A158AD19C34CC83177C583B6E18A92889B378D88E506EAEEA
9     05A567CB36220A5A84ED3358E7FCDB003D3F1FF93A77A70930E3E2CD951F9E91
10    FA26D450B0171FCDA4F35A5793669546A8F12DBB5CC7A3CBEF3DEF3D24B07CF2
11    4BC61F8975ABBD71D532B841CF16265957F5F453C37240D3BA25BB7A92601368
12    9A07C59C264EE46FF186A907153F30CDDAA56B3C6C6AD243739DFFA711E533B7
13    85F8C845C08F78610FE20F20DC330E23C95DD4B8259A7053EDF238F0C1607545
14    8ED49654DA39F194BC32B537B90C68E234983B64879F5D0651EE4248930B2DE7
15    87CE4B6960468158D7E4C0869066257B5A30F5A185FF06370588B071E911E4DE
16    A22DDF029C9A8AB2E897FD0470185A8A4F5DAC457462BECCFC12823656DE62D7
17    61379A0F93A0C8AD0CE665C8BC7345E33EC459772C86D2C8A95B48CD53DC3407
18    6EF96F919AA2AEAAAAC383303CAB560652DA56338E6EE3BBB243B1748E6C8550
19    AF3D3CB4CBE9A38C83CD3E1C56EB0B110AA30F5679B94BA839366D029F074113
20    F709954001F447D9EEB8AB70B79D5A6C5BBB1F23F74BB42AB2289FFAA5E2D044
21    18552C57DC128E9943FA427891BAAAE1EA0B003BDE5175EDBF5E3650004BD9EC
22    63F06F1CCA1EE9246E1DF5DA8A03844DEFF5C533B82846505D60C3EC0D4F7535
23    242C6FC7AC9054606C73983DEE763A8862923FA1D0EFD6323AF51FA7ABB9A59F
24    F709954001F447D9EEB8AB70B79D5A6C5BBB1F23F74BB42AB2289FFAA5E2D044
25    A5C8E8A871D58D22EC4036E6B6ADE4458F15C3B71F7E6830C8E0B85CB3CE66ED
26    B148D4BACA6BF9B182308A8598FFCA51C18F6962352C0C0457F1FE5878A030E4
27    44121EF770BD71F7F98190BC29136DE8BA300A0D67740360E819A64E52E76702
28    BD9F6DF55306F57727015C6ED3A0EC00B44A64D5127FF92EA08FCC73DD9B95FA
29    8BFAA82BD357C87902EFCDC35320AD4399540F1ECD24AA63F6962F633562FB3C
30    06ABDEA449C4AA6BA763700E211625EBC4B448A63B8132A58FE50964D3202A57
⋮     ⋮
11193 2219B487F10732EB6E49CC40217137FB93E6BAC76EDB772F3987B63F57DDB834
11194 CEE798C87964078C99343ACB3642D34477E314BD0C739B1AA2771F5B3CFBEBD6
11195 6A0E260AF99DE6CCD04F920564BAC27C1BB92F46F41F2894B9AF7CB6C8316462
11196 DA6568BF08CF448F89AEB4DA03E80BC0D7271BCF3B8B3A75688E2CDDEC782419
11197 A5C8E8A871D58D22EC4036E6B6ADE4458F15C3B71F7E6830C8E0B85CB3CE66ED
11198 19C4D0542196F4332202CD6D9930A53303DC9A74052441C687B3A594839B4D7D
11199 35484F6B99B96A2727DB80F086BA67BC7E997FB991AB98EC4537D8E65DAC26D0
11200 254A74B9AAD22DB7225C3C9F5F9A3A2F26216E71EDE9E8AE961016EC6824262F
11201 02134CA5E4A0C5B3CCBE26153D38614A1A3E87CD16ED88BBCE6A53628D8EA0A5
11202 485A3EA8E995D101DAB72EB31F82F8BB10A7BA0E5688ACD43E7CB455B41F62F2
11203 C9B69886B39B10231FE3E7558064CF579981C16F6D9319495FEA6BEE9CAB6E4C
11204 87E9DAF2869BCFAA1786282AA40BCFDE6D4B9FC95BDA1CA84277D94F0E37881D
11205 9CC7D9F1EF8E5014240A67BDDDAB22F1A2D2F67602B3BEA64CEBFC96C2E92672
11206 7CE2E84093E2ED34CF12A17AEE79676961BDB70251C3AB827BF375068C04C092
11207 254A74B9AAD22DB7225C3C9F5F9A3A2F26216E71EDE9E8AE961016EC6824262F
11208 9240F48692DA48115A80B0C2F6F8837674D97BE823EAAE37008375EE355EAB0E
11209 030DFF63ED83821DFE6AC65EB515B33F75C2E75D63DEC18B85C5EE94D89CB591
11210 D210630B8D7923FB094B260D80462FF4CA822362952AD0C9144D50F02AF492F9
11211 EF83A6C4F3B9221FB2255F4F6B7DF942F1386608430103DA80346AE530170064
11212 2BD5833E3484B888874C92DB1F0B85AEF45E46027629D65F34C09C2615BDCC96
11213 24622DBAC79721D51B3107B480E20AB812D3E582C90E01FF0D9AA23DE2F6D7D1
11214 9C0607993DE965CDDD2482A8CFEDA75F72466145F14DD405AD37C97E569D0309
11215 87E9DAF2869BCFAA1786282AA40BCFDE6D4B9FC95BDA1CA84277D94F0E37881D
11216 83E948668F12099D8CE8AA7A1CF70CCBE3B0AED3292A80AEA1CD8EBF358C4713
11217 453FFEAFEDFCD541F09AC96D929004B5F470E693FB872D31756E9A9BB53BE86E
11218 F2302F1110FA9D13F15DE441B2712D8292F6D6988FEE732AC62E79077AF18481
11219 E6E350D26C360D47D045938D0460655B4EE5E460B487677CA60393B031389C64
11220 39FCFA88EC3FBD290E2E1C5E0B157E3A26353A75D5DE20C1CAD68E6528E55C5B
11221 AFF6CEE0A4191BE9A9BA42F6B4BCAFE706F3A19FB27564A5AC86EC4C168EA732
11222 7944794312813FB6AF754B9BE1C47963ED43869DD64997789ECED52B84D1CF82
      tbl_SecondaryCare_ae_nautilus_start_date description
1     2017-08-23 10:14:00                      First A&E Attendance
2     2017-09-22 17:43:00                      First A&E Attendance
3     2017-09-23 19:05:00                      First A&E Attendance
4     2017-09-24 10:00:00                      First A&E Attendance
5     2017-09-24 01:03:00                      First A&E Attendance
6     2017-09-25 22:49:00                      First A&E Attendance
7     2017-09-25 00:44:00                      First A&E Attendance
8     2017-09-25 20:57:00                      First A&E Attendance
9     2017-09-25 14:00:00                      First A&E Attendance
10    2017-09-25 18:45:00                      First A&E Attendance
11    2017-09-25 18:58:00                      First A&E Attendance
12    2017-09-25 20:25:00                      First A&E Attendance
13    2017-09-26 11:00:00                      First A&E Attendance
14    2017-09-26 20:49:00                      First A&E Attendance
15    2017-09-26 15:00:00                      First A&E Attendance
16    2017-09-26 10:14:00                      First A&E Attendance
17    2017-09-26 11:30:00                      First A&E Attendance
18    2017-09-26 10:00:00                      First A&E Attendance
19    2017-09-27 16:00:00                      First A&E Attendance
20    2017-09-27 08:18:00                      First A&E Attendance
21    2017-09-27 02:39:00                      First A&E Attendance
22    2017-09-27 10:49:00                      First A&E Attendance
23    2017-09-27 22:39:00                      First A&E Attendance
24    2017-09-28 12:56:00                      First A&E Attendance
25    2017-09-28 21:10:00                      First A&E Attendance
26    2017-09-28 13:00:00                      First A&E Attendance
27    2017-09-29 09:00:00                      First A&E Attendance
28    2017-09-29 19:00:00                      First A&E Attendance
29    2017-09-30 15:51:00                      First A&E Attendance
30    2017-09-30 01:01:00                      First A&E Attendance
⋮     ⋮                                        ⋮
11193 2024-08-07 03:36:00                      First A&E Attendance
11194 2024-08-07 11:02:00                      First A&E Attendance
11195 2024-08-07 11:23:00                      First A&E Attendance
11196 2024-08-07 15:09:00                      First A&E Attendance
11197 2024-08-07 12:37:00                      First A&E Attendance
11198 2024-08-07 08:01:00                      First A&E Attendance
11199 2024-08-08 13:13:00                      First A&E Attendance
11200 2024-08-08 15:26:00                      First A&E Attendance
11201 2024-08-09 16:58:00                      First A&E Attendance
11202 2024-08-09 04:48:00                      First A&E Attendance
11203 2024-08-09 10:17:00                      First A&E Attendance
11204 2024-08-09 20:25:00                      First A&E Attendance
11205 2024-08-09 21:01:00                      Follow Up Attendance - Planned
11206 2024-08-09 20:25:00                      First A&E Attendance
11207 2024-08-09 16:38:00                      First A&E Attendance
11208 2024-08-10 13:42:00                      First A&E Attendance
11209 2024-08-10 20:57:00                      First A&E Attendance
11210 2024-08-10 12:42:00                      First A&E Attendance
11211 2024-08-11 18:30:00                      First A&E Attendance
11212 2024-08-11 09:27:00                      First A&E Attendance
11213 2024-08-11 21:30:00                      First A&E Attendance
11214 2024-08-12 15:52:00                      First A&E Attendance
11215 2024-08-12 17:21:00                      First A&E Attendance
11216 2024-08-12 05:07:00                      First A&E Attendance
11217 2024-08-12 14:54:00                      First A&E Attendance
11218 2024-08-13 17:49:00                      First A&E Attendance
11219 2024-08-13 07:42:00                      First A&E Attendance
11220 2024-08-14 13:12:00                      First A&E Attendance
11221 2024-08-14 14:54:00                      First A&E Attendance
11222 2024-08-14 16:22:00                      First A&E Attendance
      start_date
1     2017-08-23
2     2017-09-22
3     2017-09-23
4     2017-09-24
5     2017-09-24
6     2017-09-25
7     2017-09-25
8     2017-09-25
9     2017-09-25
10    2017-09-25
11    2017-09-25
12    2017-09-25
13    2017-09-26
14    2017-09-26
15    2017-09-26
16    2017-09-26
17    2017-09-26
18    2017-09-26
19    2017-09-27
20    2017-09-27
21    2017-09-27
22    2017-09-27
23    2017-09-27
24    2017-09-28
25    2017-09-28
26    2017-09-28
27    2017-09-29
28    2017-09-29
29    2017-09-30
30    2017-09-30
⋮     ⋮
11193 2024-08-07
11194 2024-08-07
11195 2024-08-07
11196 2024-08-07
11197 2024-08-07
11198 2024-08-07
11199 2024-08-08
11200 2024-08-08
11201 2024-08-09
11202 2024-08-09
11203 2024-08-09
11204 2024-08-09
11205 2024-08-09
11206 2024-08-09
11207 2024-08-09
11208 2024-08-10
11209 2024-08-10
11210 2024-08-10
11211 2024-08-11
11212 2024-08-11
11213 2024-08-11
11214 2024-08-12
11215 2024-08-12
11216 2024-08-12
11217 2024-08-12
11218 2024-08-13
11219 2024-08-13
11220 2024-08-14
11221 2024-08-14
11222 2024-08-14

In [110]:
AE_filtered_9900 |>
  count(person_id) |>       
  count(n) |>               
  rename(frequency = n, count = nn)

Storing counts in `nn`, as `n` already present in input
ℹ Use `name = "new_name"` to pick a new name.

     frequency count

In [63]:
inpatient_filtered_0001 <- inpatient_filtered |>
    semi_join(cohort_0001, by = "person_id") |>
    filter(stay_start_date < as.Date("2017-09-01"))

In [64]:
inpatient_filtered_0001 |>
  count(person_id) |>       
  count(n) |>               
  rename(frequency = n, count = nn)

Storing counts in `nn`, as `n` already present in input
ℹ Use `name = "new_name"` to pick a new name.

   frequency count
1    1       1256
2    2        463
3    3        164
4    4         79
5    5         41
6    6         29
7    7         12
8    8         10
9    9         10
10  10          8
11  11          3
12  12          4
13  13          1
14  18          2
15  19          2
16  20          1
17  25          1
18  50          1
19  61          1
20 134          1

In [65]:
inpatient_filtered_0102 <- inpatient_filtered |>
    semi_join(cohort_0102, by = "person_id") |>
    filter(stay_start_date < as.Date("2018-09-01"))

In [66]:
inpatient_filtered_0102 |>
  count(person_id) |>       
  count(n) |>               
  rename(frequency = n, count = nn)

Storing counts in `nn`, as `n` already present in input
ℹ Use `name = "new_name"` to pick a new name.

   frequency count
1    1       1362
2    2        470
3    3        210
4    4         85
5    5         49
6    6         20
7    7         13
8    8          9
9    9         11
10  10          5
11  11          1
12  12          2
13  13          4
14  14          2
15  15          1
16  16          1
17  18          3
18  19          1
19  21          1
20  23          1
21  25          2
22  28          1
23  32          1
24  36          1
25  37          1
26  45          1
27  59          1
28 149          1
29 153          1
30 167          1

In [67]:
inpatient_stays <- rbind(inpatient_filtered_9899, inpatient_filtered_9900, inpatient_filtered_0001, inpatient_filtered_0102)

In [68]:
head(inpatient_stays)

  person_id
1 92D116B37F94927C3909E3A0DEC93313C6E9DC8AE59A74E3741A4EC31BE423F6
2 B9BA8CA19EB91125A2D67B96A3AD8C7FAFB3B9400C431D270F1747A5B2CB3021
3 93C9C7B8080DC785358A03AA02A6F16621203AE0F5D46DAA931300E0598E15CF
4 4D7E7CCDF862ADAE8CF68EA1EFDCD2DF51FA3922CF10F3E547B611FEFF04D0BA
5 B38B8FA67AB9E90BAFF692608643CBD90DFBEBED10400C09F2FBE16BC0C8E726
6 1625A5EC5A3C4CEC388E1031C1DD98A75B05C2AB8B14C2643B5A6C70878DB23D
  stay_start_date length_of_stay
1 2006-12-30      2
2 2007-01-01      2
3 2007-01-02      2
4 2007-01-03      2
5 2007-01-04      2
6 2007-01-04      2