In [2]:
library(tidyverse)
library(dbplyr)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘dbplyr’


The following objects are masked from ‘package:dplyr’:

    ident, sql

In [24]:
# Read in data
data <- read.csv('data/additional_destinations_wide_detail.csv', header = TRUE)

In [25]:
head(data)

  person_id                                                        NCCIS_ACADYR
1 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2016/2017
2 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 2015/2016
3 000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909 2015/2016
4 00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC 2016/2017
5 0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D 2016/2017
6 00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7 2016/2017
  X9        X10       X11       X12       X1        X2
1 NA        NA        Education Education Education Education
2 Education Education Education NA        NA        Employment
3 NA        Education Education Education NA        Education
4 Education Education Education Education Education Education
5 Education Education Education Education Education Education
6 Education Education Education Education Education Education
  X3                      X4                      X5
1 Education               Education               Education
2 Employment              NA                      Employment
3 Education               NA                      Education
4 Education               Education               Education
5 NEET: Start date agreed NEET: Start date agreed NEET: Start date agreed
6 Education               Education               Education
  X6                      X7                      X8
1 Education               Education               Education
2 Employment              Employment              Employment
3 Education               NA                      NA
4 Education               Education               NA
5 NEET: Start date agreed NEET: Start date agreed NEET: Start date agreed
6 Education               Education               NA

## Prep data

In [26]:
data |>
    nrow()

[1] 17742

In [27]:
data |>
    summarise(n_distinct(person_id))

  n_distinct(person_id)
1 17742

In [28]:
data |>
    group_by(person_id) |>
    filter(n() > 1)

     person_id NCCIS_ACADYR X9 X10 X11 X12 X1 X2 X3 X4 X5 X6 X7 X8

In [29]:
# drop all NAs 
destinations_seq <- data |>
    filter(!if_all(`X9`:`X8`, is.na))

In [30]:
destinations_seq |>
    nrow()

[1] 17538

## add activity counts per row

In [31]:
destinations_counts <- destinations_seq |>
    rowwise() |>
    mutate(
    Education = sum(c_across(`X9`:`X8`) == "Education", na.rm = TRUE),
    Employment = sum(c_across(`X9`:`X8`) == "Employment", na.rm = TRUE),
    Training = sum(c_across(`X9`:`X8`) == "Training", na.rm = TRUE),
    Refused = sum(c_across(`X9`:`X8`) == "Refused", na.rm = TRUE),
    # check starts with 
    NEET = sum(grepl("^NEET", c_across(`X9`:`X8`)), na.rm = TRUE),
    NA_count = sum(is.na(c_across(`X9`:`X8`)))
        ) |>
    ungroup()

## Classify records

In [32]:
destinations_counts |>
 filter(str_starts(X9, 'NEET') & (Education == 11 | Employment == 11 | Training == 11))

   person_id
1  0772E99CADC7123F2940B90F89283CA8AFD36E0D99F083D845B5612729EECA71
2  1314C053A3BA094882EC91EF74989449A1EAFCBAEA75054B7C490BB2521CF468
3  161CDCAC6F2A4F846BB87AF3CA0496574BDBCDA96A1DAA8F17D4DCE0FA6DB3EB
4  17623045CF888706B6604C1B734B26948DED4794081F8369559D926DA3AA3C77
5  19CB3F364B8534C419E6C91A2DF2000E806A3E2E691700914297EC9DE3CEE53B
6  20121FDDC7BC077F1757E368C10056CCD4EEAAD117E0EFAF8183F90BCFC1D2C8
7  22FCCC4C1C2D332BF32E47283FDDA31D3693A659330583B6599B0036ED7B8AD0
8  2B3B49BD5A300A48C664A70EB538880F608F8D429AD8D7CEFB78A49B849F4554
9  57B2F831424726F457EBB4AD49B2A8BF3DB54BC4BF3CC4565CF8FA2DE4B9BEAB
10 6996CAFF7A43229BF3E9113C235A4AE686C0CE22AEA8147892ED89F3B5022851
11 6FC9F644A78508B4F7E18548DB3E148C3CBD730450602D87B7DFF6573CDA84E3
12 85BBD93B0E89414FC0DA5687B0F33BD95F41F1117CDF1DD92C679064F83C2ADE
13 87E9DAF2869BCFAA1786282AA40BCFDE6D4B9FC95BDA1CA84277D94F0E37881D
14 976FF98501CB2B22325B820B2D693B10C7D7B7E46FC0B437CB0F8FF40379CEC0
15 97A57D8431C94545004D69B8A2A3519982BE2D8C77ED9D9CB758D2F6D90D0162
16 9D6E66060F9211977B5D2EF3723C63F3E84771736F13E92A2A543B81A7E78473
17 A9BE16B787D5A28D4EDBC5B8CCB3B4A86E20EA1D577527C56EADD27FAD0F6D91
18 BBCB549AC31AD60E29C4A1E4B924BBC9517F567A7CC2BE122394FAE9B2E81176
19 C1EB0329997EE5BD18E523AE1325589515956DEB3AF4BA4E4BEFA0422CD07A86
20 C5B33FB7C8848675D94CDB1D7A4C4B7017FA1C68D9B712861ACFF187473D4A2A
21 F11D4C41DC94A14C7ABD8FC3277838088341754C26F5BD6E0CD7C61C9C0AF6CF
22 F7B3C3FB59D463FC687EBD80F88703C30CE9A1C3827B3F6B60DF804BB8F1B2C0
23 F85EF3297BE0264C33692EF3A12E8D3588AD91AF392E3AC8AC66DA88A21C248D
24 FBC568EEEB3861648164796996A037CC1F4D44EF49558319E47B647BEB3458C6
25 FC82E4F892DFAB469A499FBCA368CD358A5106B046EB3F90BC63D464C77F7BC9
   NCCIS_ACADYR X9                      X10        X11        X12
1  2016/2017    NEET: Not ready         Employment Employment Employment
2  2016/2017    NEET: Seeking EET       Training   Training   Training
3  2015/2016    NEET: Seeking EET       Training   Training   Training
4  2015/2016    NEET: Seeking EET       Education  Education  Education
5  2016/2017    NEET: Seeking EET       Employment Employment Employment
6  2016/2017    NEET: Seeking EET       Education  Education  Education
7  2015/2016    NEET: Seeking EET       Education  Education  Education
8  2015/2016    NEET: Seeking EET       Education  Education  Education
9  2016/2017    NEET: Teen parent       Education  Education  Education
10 2016/2017    NEET: Seeking EET       Training   Training   Training
11 2015/2016    NEET: Seeking EET       Education  Education  Education
12 2015/2016    NEET: Seeking EET       Education  Education  Education
13 2016/2017    NEET: Seeking EET       Training   Training   Training
14 2016/2017    NEET: Seeking EET       Education  Education  Education
15 2016/2017    NEET: Start date agreed Employment Employment Employment
16 2015/2016    NEET: Seeking EET       Education  Education  Education
17 2015/2016    NEET: Seeking EET       Education  Education  Education
18 2015/2016    NEET: Seeking EET       Employment Employment Employment
19 2015/2016    NEET: Start date agreed Education  Education  Education
20 2015/2016    NEET: Seeking EET       Education  Education  Education
21 2016/2017    NEET: Seeking EET       Education  Education  Education
22 2016/2017    NEET: Start date agreed Employment Employment Employment
23 2015/2016    NEET: Start date agreed Education  Education  Education
24 2016/2017    NEET: Seeking EET       Training   Training   Training
25 2016/2017    NEET: Start date agreed Employment Employment Employment
   X1         X2         X3         X4         X5         X6         X7
1  Employment Employment Employment Employment Employment Employment Employment
2  Training   Training   Training   Training   Training   Training   Training
3  Training   Training   Training   Training   Training   Training   Training
4  Education  Education  Education  Education  Education  Education  Education
5  Employment Employment Employment Employment Employment Employment Employment
6  Education  Education  Education  Education  Education  Education  Education
7  Education  Education  Education  Education  Education  Education  Education
8  Education  Education  Education  Education  Education  Education  Education
9  Education  Education  Education  Education  Education  Education  Education
10 Training   Training   Training   Training   Training   Training   Training
11 Education  Education  Education  Education  Education  Education  Education
12 Education  Education  Education  Education  Education  Education  Education
13 Training   Training   Training   Training   Training   Training   Training
14 Education  Education  Education  Education  Education  Education  Education
15 Employment Employment Employment Employment Employment Employment Employment
16 Education  Education  Education  Education  Education  Education  Education
17 Education  Education  Education  Education  Education  Education  Education
18 Employment Employment Employment Employment Employment Employment Employment
19 Education  Education  Education  Education  Education  Education  Education
20 Education  Education  Education  Education  Education  Education  Education
21 Education  Education  Education  Education  Education  Education  Education
22 Employment Employment Employment Employment Employment Employment Employment
23 Education  Education  Education  Education  Education  Education  Education
24 Training   Training   Training   Training   Training   Training   Training
25 Employment Employment Employment Employment Employment Employment Employment
   X8         Education Employment Training Refused NEET NA_count
1  Employment  0        11          0       0       1    0
2  Training    0         0         11       0       1    0
3  Training    0         0         11       0       1    0
4  Education  11         0          0       0       1    0
5  Employment  0        11          0       0       1    0
6  Education  11         0          0       0       1    0
7  Education  11         0          0       0       1    0
8  Education  11         0          0       0       1    0
9  Education  11         0          0       0       1    0
10 Training    0         0         11       0       1    0
11 Education  11         0          0       0       1    0
12 Education  11         0          0       0       1    0
13 Training    0         0         11       0       1    0
14 Education  11         0          0       0       1    0
15 Employment  0        11          0       0       1    0
16 Education  11         0          0       0       1    0
17 Education  11         0          0       0       1    0
18 Employment  0        11          0       0       1    0
19 Education  11         0          0       0       1    0
20 Education  11         0          0       0       1    0
21 Education  11         0          0       0       1    0
22 Employment  0        11          0       0       1    0
23 Education  11         0          0       0       1    0
24 Training    0         0         11       0       1    0
25 Employment  0        11          0       0       1    0

In [33]:
destinations_counts |> 
    group_by(person_id) |>
    filter(n() > 1)

     person_id NCCIS_ACADYR X9 X10 X11 X12 X1 X2 X3 X4 X5 X6 X7 X8 Education
     Employment Training Refused NEET NA_count

In [34]:
destinations_counts |>
    filter(NEET == 1)

    person_id
1   007570ED5702694AEE71FBCA3ED93584AD7C19E06FE4CB64203ED8BE71B024EA
2   013B9BA4BD97CDC7AE586437E9E9BB2C0F9C0A199AB5AB5B52F8B12D5E93A9A0
3   0145A692871133E73206BF7AEEA5D85D1E03E9876C5FC24BEEFFBCEC29566F1C
4   01C1CC6E8870E9159870D4960A30C011C7856B98A4E14EDF5697848D0C7857BC
5   0295926630EA8CABA68406F62356E89F054D4A130CED06185F9B541E3C89B7E7
6   0383BAC74CDF01BD05413B510B2961DF66D212EAF8EFBD4705FA540B501451F1
7   03874AA24F3E1A774036B356A7D82C9842E2E7B4BE068CE06C2424910ACD6EE6
8   03C67308298F1CB39B63B21FE0EA24C3AB3DD9B4062968764C5A183CB9AF3C82
9   03FB0EC85857ECEAA9D03E0855E5981B9BE3E551FC939A8957962EBC34DC49BE
10  056129E5E118171D81B2BC0BD4890FB5852504EE358F6FB85D40F7104DB6F32E
11  05A567CB36220A5A84ED3358E7FCDB003D3F1FF93A77A70930E3E2CD951F9E91
12  06143AF4F7BA90DF14AB5A9629BA58C07CF1FDCA9EEA5F60680D77FDE5953D7E
13  0614C169813351BB7F8E6599CC1AA658566641F7868CE4309AB02F0FC73141E2
14  061E7BFF81DD6F6752412B82E1852C350767D72B1CD7A39704F0C89611560F0F
15  0641A52BAB15C6ECEEE0C055C3C7D6E0C3565F2990F6061A6B8FE2368E0C735E
16  069DD966BBEF82F3A31A3DCA9F94672B808AD8938C58CAA6D4E9D14F5FDE23E6
17  0772E99CADC7123F2940B90F89283CA8AFD36E0D99F083D845B5612729EECA71
18  077FE506731D603B13FA1882D2318F445D670AE3553E197A32D7281C9146DA96
19  0875DABB597180D759C4262BF10644AF6ED01243DA20B68D137B673FBFBF4A34
20  0888DB06E89AE2BCC2943CA67C1BCCB8FB5850E0E2141FE25A02CFEE0A28E595
21  08B1BDEB8B997B1143D410E4808D2DAE4A86CCECD0411363FC0B88D3DAA3FBD1
22  09924575AF0B32AAF0D9C6CB6765245F98CFEFF406A7C84BACBE16B9A854BCFE
23  0AB9E37B82DC39BC00DE43BE0A9B567C1508CD374410289887F9181E99D221E3
24  0BBB9C3F0E70555C13BFDE626BE05880866872B6679D529B002C30CFABBCD629
25  0CF11A83B49790CB2E898B9C16CB98A07D07EF938A884155EE7A64D550F311F3
26  0E75619B7505B0650BF24F0A5A80E6C39026195248A62413AA1CE5BF1EF6DC25
27  0EF716205DC66E893BCDFDD1B4AA8F187F94E5AB5CD177CBAAB1DC7B6ED762ED
28  0F985860DD98C6096216C4FFEE1B7535F2F034500A23FE5321B3788269233734
29  10161ED0532014376A67821352EBFD100C66BA6FE9166FB8C3C60760521BB72B
30  1023DC149241CAE5AEA1512C78C9189BEB4B2C27EBBBD78B83BD2E43DDBB8C18
⋮   ⋮
312 E80854102B0B64F6BA3F90DB99AAA514FF2F4D072D0386C2039C2B38A82B07AE
313 E80A8E5E278BB72AA7EE869791AAF73C6156FDD3ACCDD143323A86CC7A1427F2
314 E934D9BF6AD89F98D530FCCC5A50F06CFF4EF4ADE33CDF6E489865EB47099BBD
315 E96AF6F613AB7C24519CC84417245697EE618F30A71FF1AD214F012D87E50C31
316 E9E150CDB094AB2E1B6E4ABAB449CC59B7040F85885BC73A795BB8E1E9430066
317 E9E83A47653D5CC27654F1CD3EB121253B0167E64B22FEFDD315679A64AC0BA5
318 EC1E5C663411A6C433B00FFB990B234492C18D9007B88CB9395C3E844F89C22F
319 EF48AADC6F1D47B0EDB45B842A168E1A0C79A6399529A5F1855EDE14DEB6715D
320 F10E92214D2CC862BDB310F60CBB8F6B0EE7823781C4AC894E21B4DAF39F7847
321 F11D4C41DC94A14C7ABD8FC3277838088341754C26F5BD6E0CD7C61C9C0AF6CF
322 F1401F8003B082F42E15D81DE6255E6C88C714680209F08B2358E98D9AE0D8EC
323 F1FC9407E687F70E41D1000F964C1EF73E68BD7C8E02ADE38DD6CBA371DCA8D4
324 F2B8135DBFDD090C779DC63B192BC5017939010E53C0B18AE4B822A0676F9400
325 F3475762D78B9B3EC11E7DA09A674E69F862E43B1C66BAA884D985B647220B50
326 F461E6E56ABA916E518D9E9DCC63987371ED29BB71288F4926909BDEBF870807
327 F4CC6C2978520F7797F5A3D64228A0526872DCA2C2C3915BB096574655D06758
328 F7B3C3FB59D463FC687EBD80F88703C30CE9A1C3827B3F6B60DF804BB8F1B2C0
329 F7ECDDB2E59F6544E7310B566466DE83957D7EBB1EED2FF2A499BBA151FC6EB4
330 F8017CBA619A1C6A8FA7645558FB394A12E24A27EB112C4E95036EF78FF5ECAA
331 F81CF5A4ECFA333FF0C9F81B7D08CD92FE0E58DC38DB2FF0AC4D32CEC8B2792B
332 F85EF3297BE0264C33692EF3A12E8D3588AD91AF392E3AC8AC66DA88A21C248D
333 F99945D5595C78EF38BB97BF107E3B846CA79E599A9E55BC4BA98A522B1A57A8
334 F9BCB44645083B90C8E57174D72CB393AC70CF80708107383F8D7D1EB9743BE8
335 FB4AC4CDA25E971EBE797840D89C81558FD461D4AB05DF6ED2691C09FD109509
336 FB5B3678F21355E8DAF615F840E695EFE04769E741B47E0DA44187317AACF66D
337 FBC568EEEB3861648164796996A037CC1F4D44EF49558319E47B647BEB3458C6
338 FC13EC7C0A85595B3E6E002E65C519EE7B397832EB11341F3A93B3B7A5E75328
339 FC82E4F892DFAB469A499FBCA368CD358A5106B046EB3F90BC63D464C77F7BC9
340 FE1E01DA0A2B8764D9B4AEB2DB7E7E8658858930A275DE8CF8A83FC222DD0E1E
341 FE865826CF1F521140082014FCC19CD99A8192B1EA848DC1D7AD997D522DDE16
    NCCIS_ACADYR X9                      X10               X11
1   2015/2016    Education               NA                Education
2   2015/2016    Education               NA                NA
3   2015/2016    NA                      NA                NA
4   2016/2017    Education               Education         NA
5   2016/2017    NA                      Education         Education
6   2016/2017    NEET: Seeking EET       Training          Training
7   2015/2016    Education               Education         Education
8   2016/2017    Education               Education         Education
9   2015/2016    Education               Education         Education
10  2015/2016    NEET: Seeking EET       Employment        Employment
11  2016/2017    Training                Training          Training
12  2016/2017    Education               Education         NA
13  2015/2016    NEET: Seeking EET       Training          Training
14  2016/2017    NEET: Seeking EET       Training          Training
15  2016/2017    Education               Education         Education
16  2015/2016    NEET: Start date agreed Training          Training
17  2016/2017    NEET: Not ready         Employment        Employment
18  2016/2017    Education               Education         NEET: Seeking EET
19  2015/2016    NA                      NA                Education
20  2016/2017    NA                      Education         NA
21  2015/2016    Education               Education         Education
22  2015/2016    Education               Education         Education
23  2015/2016    NEET: Seeking EET       Training          Training
24  2015/2016    NA                      NA                NA
25  2015/2016    Education               Education         Education
26  2015/2016    NEET: Seeking EET       Employment        Employment
27  2016/2017    Education               Education         Education
28  2015/2016    Education               Education         Education
29  2015/2016    Training                Training          Training
30  2016/2017    Education               Education         Education
⋮   ⋮            ⋮                       ⋮                 ⋮
312 2016/2017    NA                      NA                NA
313 2015/2016    Education               NEET: Seeking EET Training
314 2015/2016    NEET: Seeking EET       Training          NA
315 2015/2016    NA                      NEET: Seeking EET NA
316 2015/2016    NA                      Education         Education
317 2016/2017    Education               Education         Education
318 2015/2016    NA                      Training          Training
319 2015/2016    NA                      Education         Education
320 2015/2016    NEET: Seeking EET       Training          Training
321 2016/2017    NEET: Seeking EET       Education         Education
322 2016/2017    Education               Education         Education
323 2016/2017    NA                      Education         Education
324 2016/2017    Education               Education         Education
325 2015/2016    NA                      NA                NA
326 2016/2017    NA                      Education         Education
327 2016/2017    NA                      Education         Education
328 2016/2017    NEET: Start date agreed Employment        Employment
329 2016/2017    Education               Education         Education
330 2015/2016    NA                      NEET: Seeking EET Training
331 2015/2016    NEET: Seeking EET       NA                Employment
332 2015/2016    NEET: Start date agreed Education         Education
333 2016/2017    Education               Education         Education
334 2016/2017    Training                Training          Training
335 2015/2016    NA                      NA                NA
336 2016/2017    Education               Education         Education
337 2016/2017    NEET: Seeking EET       Training          Training
338 2016/2017    Education               Education         NA
339 2016/2017    NEET: Start date agreed Employment        Employment
340 2015/2016    Education               Education         Education
341 2015/2016    NA                      NEET: Seeking EET Employment
    X12                     X1                X2
1   Education               Education         Education
2   NEET: Seeking EET       Training          Training
3   NA                      NEET: Seeking EET Employment
4   NA                      NA                NA
5   Education               Education         Education
6   Training                Training          Training
7   Education               Education         Education
8   Education               Education         NEET: Seeking EET
9   Education               Education         Education
10  Employment              Employment        Employment
11  Training                Training          Training
12  NEET: Start date agreed Education         Education
13  Training                Training          Training
14  Training                Training          Training
15  Education               Education         Education
16  Training                NA                Education
17  Employment              Employment        Employment
18  Education               Education         Education
19  NA                      NEET: Seeking EET NA
20  NA                      NEET: Seeking EET Employment
21  Education               Education         Education
22  Education               Education         Education
23  Training                Training          Training
24  NEET: Seeking EET       Education         NA
25  Education               Education         NEET: Seeking EET
26  Employment              Employment        Employment
27  NEET: Seeking EET       Education         Education
28  Education               Education         NEET: Seeking EET
29  Training                Training          Training
30  Education               Education         Education
⋮   ⋮                       ⋮                 ⋮
312 NA                      NA                NA
313 Training                Training          Training
314 Education               NA                NA
315 Employment              NA                Employment
316 NA                      NEET: Seeking EET Education
317 Education               Education         NEET: Seeking EET
318 Training                Training          Training
319 Education               Education         Education
320 NA                      Training          NA
321 Education               Education         Education
322 Education               Education         Education
323 Education               Education         Education
324 Education               Education         Education
325 Education               NA                Education
326 Education               Education         Education
327 Education               NEET: Seeking EET Employment
328 Employment              Employment        Employment
329 Education               Education         Education
330 Training                Training          Training
331 Employment              NA                Employment
332 Education               Education         Education
333 NA                      NA                NA
334 Training                Training          NEET: Seeking EET
335 NA                      NA                NA
336 Education               Education         Education
337 Training                Training          Training
338 NEET: Start date agreed Education         Education
339 Employment              Employment        Employment
340 NA                      Education         NA
341 Employment              Employment        Employment
    X3                X4                X5
1   NEET: Seeking EET NA                Employment
2   NA                Training          Training
3   Employment        Employment        NA
4   NA                NA                NEET: Start date agreed
5   Education         Education         Education
6   Training          Training          Training
7   Education         NEET: Seeking EET Training
8   Education         Education         Education
9   Education         Education         Education
10  Employment        Training          Training
11  Training          Training          NEET: Seeking EET
12  Education         Education         Education
13  Training          Training          Training
14  Training          Training          Employment
15  Education         Education         Education
16  Education         Education         Education
17  Employment        Employment        Employment
18  Education         Education         Education
19  Education         NA                NA
20  Employment        Employment        Employment
21  Education         Education         Education
22  Education         Education         NA
23  Training          Training          Training
24  NA                Education         NA
25  Refused           Refused           Refused
26  NA                Employment        Employment
27  Education         Education         Education
28  Employment        Employment        Employment
29  Training          NEET: Seeking EET Training
30  NEET: Seeking EET Training          Training
⋮   ⋮                 ⋮                 ⋮
312 NA                NA                NA
313 Training          Training          Training
314 Education         NA                Education
315 Employment        Employment        Employment
316 NA                Education         Education
317 Training          Training          Training
318 Training          Training          Training
319 Education         Education         Education
320 Training          NA                Training
321 Education         Education         Education
322 Education         Education         Education
323 Education         Training          Education
324 NA                NA                NA
325 Education         Education         NA
326 Education         Education         Education
327 Employment        Employment        Employment
328 Employment        Employment        Employment
329 NEET: Seeking EET Training          Training
330 NA                Training          Training
331 Employment        Training          Training
332 Education         Education         Education
333 NA                NA                NEET: Seeking EET
334 Employment        Employment        Employment
335 NEET: Seeking EET Training          Training
336 NA                NEET: Seeking EET Employment
337 Training          Training          Training
338 Education         Education         Education
339 Employment        Employment        Employment
340 Education         NA                Education
341 Employment        Employment        Employment
    X6                      X7                X8                Education
1   Employment              NA                Employment         5
2   NA                      Training          Training           1
3   Employment              Employment        Employment         0
4   Employment              Employment        Employment         2
5   NEET: Seeking EET       Employment        Employment         8
6   Training                Training          NA                 0
7   Training                Training          Training           7
8   NA                      Education         Education         10
9   Education               Education         NEET: Seeking EET 11
10  Training                Training          Training           0
11  Training                Training          Training           0
12  Education               Education         Education         10
13  Training                NA                NA                 0
14  Employment              Employment        Employment         0
15  Education               Education         NEET: Seeking EET 11
16  Education               Education         Education          7
17  Employment              Employment        Employment         0
18  Education               Education         Education         11
19  Education               NA                NA                 3
20  Employment              Employment        Employment         1
21  Education               Education         NEET: Seeking EET 11
22  NA                      NEET: Seeking EET Employment         8
23  NA                      NA                NA                 0
24  NA                      Education         NA                 3
25  Refused                 Refused           Refused            5
26  NA                      Employment        Employment         0
27  Education               Education         Education         11
28  Employment              Employment        Employment         5
29  Training                Training          Training           0
30  Training                Training          Training           6
⋮   ⋮                       ⋮                 ⋮                 ⋮
312 NA                      NA                NEET: Seeking EET  0
313 NA                      NA                NA                 1
314 Education               NA                Education          5
315 Employment              NA                Employment         0
316 NA                      Education         NA                 6
317 Training                Training          Training           5
318 NEET: Start date agreed NA                NA                 0
319 Education               Education         NEET: Teen parent 10
320 Training                NA                Training           0
321 Education               Education         Education         11
322 Education               NA                NEET: Seeking EET 10
323 Education               Education         NEET: Seeking EET  9
324 NA                      NEET: Not ready   Employment         6
325 Education               NA                NEET: Seeking EET  5
326 Education               Education         NEET: Seeking EET 10
327 Employment              Employment        Employment         3
328 Employment              Employment        Employment         0
329 Training                Training          Training           6
330 Training                NA                Training           0
331 Training                NA                Training           0
332 Education               Education         Education         11
333 Employment              Employment        Employment         3
334 Employment              Employment        Employment         0
335 Training                Training          Training           0
336 Employment              Employment        Employment         6
337 Training                Training          Training           0
338 Education               Education         Education         10
339 Employment              Employment        Employment         0
340 Education               NA                NEET: Seeking EET  7
341 Employment              Employment        Employment         0
    Employment Training Refused NEET NA_count
1    3          0       0       1    3
2    0          6       0       1    4
3    6          0       0       1    5
4    3          0       0       1    6
5    2          0       0       1    1
6    0         10       0       1    1
7    0          4       0       1    0
8    0          0       0       1    1
9    0          0       0       1    0
10   6          5       0       1    0
11   0         11       0       1    0
12   0          0       0       1    1
13   0          9       0       1    2
14   4          7       0       1    0
15   0          0       0       1    0
16   0          3       0       1    1
17  11          0       0       1    0
18   0          0       0       1    0
19   0          0       0       1    8
20   7          0       0       1    3
21   0          0       0       1    0
22   1          0       0       1    2
23   0          8       0       1    3
24   0          0       0       1    8

In [35]:
destinations_counts_labelled <- destinations_counts |>
    mutate(Label = case_when(
        NEET == 0 & Refused == 0 & NA_count <= 4 ~ 'Steady EET',
        str_starts(X9, 'NEET') & (Education == 11 | Employment == 11 | Training == 11) ~ 'Steady EET',
        NEET == 0 & Refused == 0 & NA_count >= 5 ~ 'DROP',
        TRUE ~ 'Risky trajectory'
    )
          )

In [36]:
head(destinations_counts_labelled)

  person_id                                                        NCCIS_ACADYR
1 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2016/2017
2 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 2015/2016
3 000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909 2015/2016
4 00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC 2016/2017
5 0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D 2016/2017
6 00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7 2016/2017
  X9        X10       X11       X12       X1        X2
1 NA        NA        Education Education Education Education
2 Education Education Education NA        NA        Employment
3 NA        Education Education Education NA        Education
4 Education Education Education Education Education Education
5 Education Education Education Education Education Education
6 Education Education Education Education Education Education
  X3                      X4                      ⋯ X6
1 Education               Education               ⋯ Education
2 Employment              NA                      ⋯ Employment
3 Education               NA                      ⋯ Education
4 Education               Education               ⋯ Education
5 NEET: Start date agreed NEET: Start date agreed ⋯ NEET: Start date agreed
6 Education               Education               ⋯ Education
  X7                      X8                      Education Employment Training
1 Education               Education               10        0          0
2 Employment              Employment               3        6          0
3 NA                      NA                       7        0          0
4 Education               NA                      11        0          0
5 NEET: Start date agreed NEET: Start date agreed  6        0          0
6 Education               NA                      11        0          0
  Refused NEET NA_count Label
1 0       0    2        Steady EET
2 0       0    3        Steady EET
3 0       0    5        DROP
4 0       0    1        Steady EET
5 0       6    0        Risky trajectory
6 0       0    1        Steady EET

In [37]:
destinations_counts_labelled |>
    filter(Label == 'Risky trajectory')

     person_id
1    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
2    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9
3    0045ADA48CA299BC4445318E8D951610DCB89A829665CFC821E92340F0F8B30D
4    007570ED5702694AEE71FBCA3ED93584AD7C19E06FE4CB64203ED8BE71B024EA
5    013B9BA4BD97CDC7AE586437E9E9BB2C0F9C0A199AB5AB5B52F8B12D5E93A9A0
6    0145A692871133E73206BF7AEEA5D85D1E03E9876C5FC24BEEFFBCEC29566F1C
7    017BD83D33E24C2CE047BFB67D7D010694F10CAF3E02B4360C88D4EE29E119FD
8    01C1CC6E8870E9159870D4960A30C011C7856B98A4E14EDF5697848D0C7857BC
9    01D4C5437E5A02C67E1473FEF63139486A1A85EA656181F6B68633068E174AEB
10   01D5BB808C605F3206FF17738BC4011F459A59BBA3DD18AB15D8364CD1B383EF
11   02340F3F5D13AB36293E7F6DF375CE9AAE460153C9B2F3682ABF23C881A11830
12   02708FEFBB4523984E9637EFB9C005C565E5358B4E84FFBCCB79DC0A0FDB2D60
13   0295926630EA8CABA68406F62356E89F054D4A130CED06185F9B541E3C89B7E7
14   03060C7F96A4FDE490622AC70A8C554639338E2F8C6848B002E6F134F930397A
15   0339CCDC39297FEC647716BC520E3C96665DA7B6A2A330057128E4B0656F190D
16   03514C19EB4E8DBF9DDDEE28309927B3E7D26CE59FB39643EDF701E10062C5E4
17   0376757707943397945C6ECF7E45F70455ECBC77B9C590B1E4F4868D14C9D7C8
18   0377438AD33436A7D103C1FBE4E1FDBF06466C75946C3E5227494FCA5D75A28E
19   0383BAC74CDF01BD05413B510B2961DF66D212EAF8EFBD4705FA540B501451F1
20   03874AA24F3E1A774036B356A7D82C9842E2E7B4BE068CE06C2424910ACD6EE6
21   0390C9B3C796AF612692B57F080BCA4BF82FAEDD564619E748B32D68BE00190A
22   039324CF20AFEF7A40F3225DE67935B01D2314D7B0C9033377ADB9658A0F0B38
23   03C0615F2CAF195B522811E536DF0DB3D7EA412D1B05E124A8C642C683679A91
24   03C67308298F1CB39B63B21FE0EA24C3AB3DD9B4062968764C5A183CB9AF3C82
25   03FB0EC85857ECEAA9D03E0855E5981B9BE3E551FC939A8957962EBC34DC49BE
26   04122956300E6FB06C83A828D88A1910F04CF09D68D1A4A6A171D55D2965B049
27   042B83F404AD76D94366D4AB209EC7C892C76CBF00A52511D9E49E3CBFF876DF
28   044C9351C8826D8E81CC45FBF9314DABF9ECFAD35CFA7BA92603AE254CDB4E93
29   044E0B8573D5E064A915D5866DBCF7BA71C5C27D128601E54810454DC16A172A
30   0493397019BBCF1257ACF287D526C04F5F92E8C84C108FDB9B5C829E70E83E2F
⋮    ⋮
1262 F9CC6C5B971779756F25FCFD7D2C1D5CB518EDD3C03F72BE501D59CD0D3C2D08
1263 F9F3A7B7F71D4270704061D0C301CF05F0562A87F05333268D595FFCCA196E08
1264 FA151CE84AF719F01C9592E9986841E047B2BEC4E5250A686E5D3A16C73957D0
1265 FA382D11F78BB89B1757A199FF0CC916F466F7148CB2847B8E54A86749EF0752
1266 FA58413B531291D3F7D34205A2791C4C8BE769AB964A400BB092FB083FF4BF81
1267 FA7EAD1AED1B6DE33454337D15D19D3B04EC0EF96972FFB9B53EAD11804E8C68
1268 FAC404BBF214D2CF3CE816F5E18540A2E91901E40F21DF44E5F5F695BBD70135
1269 FB1C046D4229E55639D9608987EF2A5EBE37B73F9F09144EC7D12868CB663ECA
1270 FB4195621662C6F4BB8087DF4D0A7489C7ACF5E9F22FB6CE88FB44B16EC93CE1
1271 FB4AC4CDA25E971EBE797840D89C81558FD461D4AB05DF6ED2691C09FD109509
1272 FB5B3678F21355E8DAF615F840E695EFE04769E741B47E0DA44187317AACF66D
1273 FB8EE968B699DB3C48B42606CBCE770F93A39FF0760CC43DC8B5EB59BBFEE3D4
1274 FBA40C916DE5A5141F4E9BE5179B9516ADDF510E2C2D0DEC809062EA66A52478
1275 FC13EC7C0A85595B3E6E002E65C519EE7B397832EB11341F3A93B3B7A5E75328
1276 FC224D629245A48C1D2263131AF415D137E67DCE91D2290C8C2739652268A3CA
1277 FC36A9E296B3F3FC6BB09911821287929974A4DB29EC50BE63ABE684D79F8E58
1278 FCDB455797EA02ED024C33BDE6809B8BE5957A8DB9AD2DC4B301431CE9B3BC87
1279 FD00BE8AEE54CD9E103CB81159E83CC4B637CE93FF1D939A0398F65D42F7E40D
1280 FD3131DD682E8E9D4465DDDDFF75853A3864EBE754F33FF19C2E76B2BB4C30DB
1281 FD71E1FAC0B6E109416C3E52C40DC016538F74C1200512DDBC6627175D2D2489
1282 FDC4C9E1228ECAD26CAA4DCF8CDF84640593E1DD544C0D33923D503E363DC2D0
1283 FDD2C72729BE4D59FEE0CCE71DE96EAB87ADF94873A5F1FA5708AFC4CBF448F4
1284 FDD9C062BDEEB81DDBBEC46A08F00140D5EE272A3C0570E0B80B5A8AB3652712
1285 FE1E01DA0A2B8764D9B4AEB2DB7E7E8658858930A275DE8CF8A83FC222DD0E1E
1286 FE5386B1876DF6DDB25DE2BF9246B8263D80B9CC125E1DF54F885350EA454452
1287 FE82B2AD29E6876B9BCDA6F8175D2AF68D58CE0241C724E933C7928184C53858
1288 FE865826CF1F521140082014FCC19CD99A8192B1EA848DC1D7AD997D522DDE16
1289 FEFA1FD281EC85CD0065C5651DF2EB9D7A4DA197A54D391BE4D366C862D92C5A
1290 FF08B97110E8EB7A9A6C526175245D8C7993692AEC768E1052083871AF2E6EA6
1291 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
     NCCIS_ACADYR X9                X10               X11
1    2016/2017    Education         Education         Education
2    2015/2016    Education         Education         NEET: Seeking EET
3    2015/2016    NEET: Seeking EET NEET: Seeking EET Training
4    2015/2016    Education         NA                Education
5    2015/2016    Education         NA                NA
6    2015/2016    NA                NA                NA
7    2015/2016    NEET: Not ready   NEET: Not ready   NEET: Not ready
8    2016/2017    Education         Education         NA
9    2015/2016    Education         Education         Education
10   2016/2017    Education         Training          Training
11   2016/2017    NEET: Seeking EET NEET: Seeking EET NEET: Seeking EET
12   2015/2016    NA                NEET: Seeking EET NEET: Seeking EET
13   2016/2017    NA                Education         Education
14   2015/2016    Training          Training          Training
15   2015/2016    Training          NEET: Seeking EET NEET: Seeking EET
16   2015/2016    Employment        Employment        Employment
17   2015/2016    Education         Education         Education
18   2015/2016    Education         NEET: Seeking EET NEET: Seeking EET
19   2016/2017    NEET: Seeking EET Training          Training
20   2015/2016    Education         Education         Education
21   2016/2017    Education         Education         NEET: Pregnancy
22   2015/2016    NA                NA                NA
23   2016/2017    Education         Education         Education
24   2016/2017    Education         Education         Education
25   2015/2016    Education         Education         Education
26   2016/2017    Education         Education         Education
27   2016/2017    Education         Education         Education
28   2016/2017    NA                NA                NA
29   2016/2017    Training          Training          NEET: Seeking EET
30   2015/2016    Education         Education         Education
⋮    ⋮            ⋮                 ⋮                 ⋮
1262 2015/2016    NA                Education         Education
1263 2015/2016    Education         Education         Education
1264 2016/2017    NA                Education         NEET: Seeking EET
1265 2016/2017    Education         NEET: Seeking EET NEET: Seeking EET
1266 2015/2016    NEET: Seeking EET NEET: Seeking EET NEET: Seeking EET
1267 2015/2016    NA                NA                NEET: Not ready
1268 2015/2016    Education         Education         Education
1269 2015/2016    NA                NA                Refused
1270 2016/2017    NA                NEET: Illness     NEET: Illness
1271 2015/2016    NA                NA                NA
1272 2016/2017    Education         Education         Education
1273 2016/2017    Education         Education         NA
1274 2016/2017    Employment        Employment        Employment
1275 2016/2017    Education         Education         NA
1276 2016/2017    NA                Training          Training
1277 2016/2017    Education         Education         NEET: Seeking EET
1278 2015/2016    Education         NEET: Seeking EET NEET: Seeking EET
1279 2015/2016    NA                NA                NA
1280 2015/2016    NA                NA                NA
1281 2015/2016    Education         Education         Education
1282 2016/2017    Employment        Employment        Employment
1283 2015/2016    NA                Training          Training
1284 2015/2016    NA                NA                NA
1285 2015/2016    Education         Education         Education
1286 2015/2016    NA                Training          Training
1287 2016/2017    Education         Education         NA
1288 2015/2016    NA                NEET: Seeking EET Employment
1289 2015/2016    Education         NA                Education
1290 2015/2016    NA                Education         Education
1291 2016/2017    Training          Training          Training
     X12                     X1                       X2
1    Education               Education                Education
2    NEET: Seeking EET       NEET: Seeking EET        NEET: Seeking EET
3    Training                Training                 NEET: Seeking EET
4    Education               Education                Education
5    NEET: Seeking EET       Training                 Training
6    NA                      NEET: Seeking EET        Employment
7    NEET: Not ready         NEET: Not ready          NEET: Teen parent
8    NA                      NA                       NA
9    NEET: Seeking EET       NEET: Seeking EET        NEET: Seeking EET
10   NA                      NEET: Seeking EET        NEET: Seeking EET
11   NEET: Seeking EET       NA                       NA
12   NEET: Seeking EET       NEET: Seeking EET        NEET: Seeking EET
13   Education               Education                Education
14   Training                NA                       NA
15   NEET: Seeking EET       NEET: Seeking EET        NA
16   Employment              Employment               Employment
17   Education               NA                       NA
18   NEET: Seeking EET       NEET: Illness            NEET: Illness
19   Training                Training                 Training
20   Education               Education                Education
21   NEET: Pregnancy         NEET: Pregnancy          NEET: Pregnancy
22   NA                      NEET: Seeking EET        NEET: Other
23   Education               Education                Education
24   Education               Education                NEET: Seeking EET
25   Education               Education                Education
26   Education               Education                NEET: Not ready
27   Education               Education                NEET: Seeking EET
28   NEET: Seeking EET       NEET: Seeking EET        NEET: Seeking EET
29   NEET: Seeking EET       NEET: Seeking EET        NEET: Seeking EET
30   Education               Education                Education
⋮    ⋮                       ⋮                        ⋮
1262 Education               NEET: Seeking EET        NEET: Seeking EET
1263 Education               Education                Education
1264 NEET: Seeking EET       Training                 Training
1265 NEET: Seeking EET       NEET: Seeking EET        NEET: Seeking EET
1266 NEET: Seeking EET       NEET: Seeking EET        Education
1267 NEET: Not ready         NEET: Teen parent        NEET: Teen parent
1268 Education               Education                Education
1269 Refused                 Refused                  Refused
1270 NEET: Illness           Employment               Employment
1271 NA                      NA                       NA
1272 Education               Education                Education
1273 NA                      NEET: Seeking EET        NEET: Seeking EET
1274 Employment              Employment               Employment
1275 NEET: Start date agreed Education                Education
1276 Training                NA                       NEET: Seeking EET
1277 NEET: Seeking EET       NEET: Seeking EET        Employment
1278 NEET: Seeking EET       Training                 Employment
1279 NEET: Seeking EET       NEET: Seeking EET        NEET: Seeking EET
1280 NA                      NA                       NA
1281 Education               NEET: Seeking EET        NEET: Seeking EET
1282 Employment              Employment               Employment
1283 NA                      Training                 NA
1284 NA                      NA                       NEET: Seeking EET
1285 NA                      Education                NA
1286 NEET: Seeking EET       NEET: Seeking EET        NEET: Seeking EET
1287 NA                      NEET: Working: no reward NEET: Working: no reward
1288 Employment              Employment               Employment
1289 Education               Education                Education
1290 Education               Education                Education
1291 Training                Employment               Employment
     X3                      X4                      ⋯ X6
1    NEET: Start date agreed NEET: Start date agreed ⋯ NEET: Start date agreed
2    NEET: Seeking EET       NEET: Seeking EET       ⋯ NEET: Seeking EET
3    NEET: Seeking EET       NEET: Seeking EET       ⋯ NEET: Seeking EET
4    NEET: Seeking EET       NA                      ⋯ Employment
5    NA                      Training                ⋯ NA
6    Employment              Employment              ⋯ Employment
7    NEET: Teen parent       NEET: Teen parent       ⋯ NEET: Teen parent
8    NA                      NA                      ⋯ Employment
9    NEET: Seeking EET       Training                ⋯ Training
10   NEET: Seeking EET       NEET: Seeking EET       ⋯ NEET: Seeking EET
11   NA                      NA                      ⋯ NA
12   NA                      NEET: Seeking EET       ⋯ NA
13   Education               Education               ⋯ NEET: Seeking EET
14   NEET: Illness           NEET: Illness           ⋯ NEET: Illness
15   NEET: Seeking EET       NEET: Seeking EET       ⋯ NEET: Seeking EET
16   Employment              Employment              ⋯ Employment
17   NA                      NA                      ⋯ NEET: Seeking EET
18   NEET: Illness           NA                      ⋯ NEET: Illness
19   Training                Training                ⋯ Training
20   Education               NEET: Seeking EET       ⋯ Training
21   NEET: Pregnancy         NEET: Pregnancy         ⋯ NEET: Teen parent
22   NA                      NEET: Other             ⋯ NA
23   Education               NEET: Seeking EET       ⋯ NEET: Seeking EET
24   Education               Education               ⋯ NA
25   Education               Education               ⋯ Education
26   NEET: Not ready         Employment              ⋯ Employment
27   NEET: Seeking EET       NEET: Seeking EET       ⋯ NEET: Seeking EET
28   NEET: Seeking EET       NEET: Seeking EET       ⋯ NEET: Seeking EET
29   NEET: Start date agreed Training                ⋯ Training
30   Education               Education               ⋯ NEET: Seeking EET
⋮    ⋮                       ⋮                       ⋱ ⋮
1262 Employment              NEET: Seeking EET       ⋯ NEET: Seeking EET
1263 Education               Education               ⋯ Education
1264 Training                Training                ⋯ Training
1265 NEET: Seeking EET       Employment              ⋯ Employment
1266 Education               Education               ⋯ Education
1267 NEET: Teen parent       NEET: Teen parent       ⋯ NEET: Teen parent
1268 Education               Employment              ⋯ Employment
1269 Refused                 Refused                 ⋯ Refused
1270 Employment              Employment              ⋯ Employment
1271 NEET: Seeking EET       Training                ⋯ Training
1272 NA                      NEET: Seeking EET       ⋯ Employment
1273 NEET: Seeking EET       NEET: Seeking EET       ⋯ Employment
1274 Employment              Employment              ⋯ Employment
1275 Education               Education               ⋯ Education
1276 NEET: Seeking EET       NEET: Seeking EET       ⋯ NEET: Seeking EET
1277 Employment              Employment              ⋯ Employment
1278 Employment              Employment              ⋯ Training
1279 NEET: Seeking EET       NEET: Start date agreed ⋯ NEET: Start date agreed
1280 NA                      NA                      ⋯ NEET: Seeking EET
1281 Education               Education               ⋯ Training
1282 NEET: Pregnancy         NEET: Pregnancy         ⋯ NEET: Pregnancy
1283 NEET: Seeking EET       NEET: Seeking EET       ⋯ NA
1284 NA                      NA                      ⋯ NA
1285 Education               NA                      ⋯ Education
1286 NEET: Seeking EET       NEET: Seeking EET       ⋯ NEET: Seeking EET
1287 Education               NEET: Seeking EET       ⋯ NEET: Seeking EET
1288 Employment              Employment              ⋯ Employment
1289 Education               NA                      ⋯ NEET: Seeking EET
1290 NA                      Education               ⋯ NEET: Start date agreed
1291 Employment              Employment              ⋯ NEET: Seeking EET
     X7                      X8                      Education Employment
1    NEET: Start date agreed NEET: Start date agreed  6         0
2    NEET: Seeking EET       NEET: Seeking EET        2         0
3    NEET: Seeking EET       NEET: Seeking EET        0         0
4    NA                      Employment               5         3
5    Training                Training                 1         0
6    Employment              Employment               0         6
7    NEET: Teen parent       NEET: Teen parent        0         0
8    Employment              Employment               2         3
9    Training                Training                 3         0
10   NEET: Seeking EET       NEET: Seeking EET        1         0
11   NA                      NA                       0         0
12   NA                      NA                       0         0
13   Employment              Employment               8         2
14   NEET: Illness           NEET: Illness            0         0
15   NEET: Seeking EET       NEET: Seeking EET        0         0
16   NEET: Seeking EET       NEET: Seeking EET        0        10
17   NEET: Seeking EET       NEET: Seeking EET        4         0
18   NEET: Illness           NA                       1         0
19   Training                NA                       0         0
20   Training                Training                 7         0
21   NEET: Teen parent       NEET: Seeking EET        2         0
22   NA                      NEET: Other              0         0
23   NEET: Seeking EET       NEET: Seeking EET        7         0
24   Education               Education               10         0
25   Education               NEET: Seeking EET       11         0
26   Employment              Employment               5         5
27   NEET: Seeking EET       NEET: Start date agreed  5         0
28   NEET: Seeking EET       NEET: Seeking EET        0         0
29   Training                Training                 0         0
30   NEET: Seeking EET       NEET: Seeking EET        9         0
⋮    ⋮                       ⋮                       ⋮         ⋮
1262 NA                      NA                       3         1
1263 NEET: Seeking EET       NEET: Seeking EET       10         0
1264 Training                Training                 1         0
1265 Employment              Employment               1         5
1266 Education               NA                       6         0
1267 NEET: Teen parent       NEET: Teen parent        0         0
1268 NEET: Seeking EET       NEET: Start date agreed  7         3
1269 Refused                 Refused                  0         0
1270 Employment              Employment               0         8
1271 Training                Training                 0         0
1272 Employment              Employment               6         4
1273 Employment              Employment               2         4
1274 NEET: Start date agreed NEET: Start date agreed  0        10
1275 Education               Education               10         0
1276 NEET: Seeking EET       NEET: Seeking EET        0         0
1277 Employment              Employment               2         7
1278 Training                Training                 1         4
1279 Employment              Employment               0         2
1280 NEET: Seeking EET       Training                 0         0
1281 NA                      NEET: Seeking EET        6         0
1282 NEET: Pregnancy         NEET: Pregnancy          0         6

In [38]:
destinations_counts_labelled |>
    filter(str_starts(X9, 'NEET'))

    person_id
1   0045ADA48CA299BC4445318E8D951610DCB89A829665CFC821E92340F0F8B30D
2   017BD83D33E24C2CE047BFB67D7D010694F10CAF3E02B4360C88D4EE29E119FD
3   02340F3F5D13AB36293E7F6DF375CE9AAE460153C9B2F3682ABF23C881A11830
4   0383BAC74CDF01BD05413B510B2961DF66D212EAF8EFBD4705FA540B501451F1
5   056129E5E118171D81B2BC0BD4890FB5852504EE358F6FB85D40F7104DB6F32E
6   0614C169813351BB7F8E6599CC1AA658566641F7868CE4309AB02F0FC73141E2
7   061E7BFF81DD6F6752412B82E1852C350767D72B1CD7A39704F0C89611560F0F
8   069DD966BBEF82F3A31A3DCA9F94672B808AD8938C58CAA6D4E9D14F5FDE23E6
9   0772E99CADC7123F2940B90F89283CA8AFD36E0D99F083D845B5612729EECA71
10  0921207D6C8D647E1EDD0E2A4FD26E67DFD9B7B22ABAA31A9B5D1D01FD9110C0
11  0AB9E37B82DC39BC00DE43BE0A9B567C1508CD374410289887F9181E99D221E3
12  0C45C7C8C10AA2911DB1D59DF9F9382617A9FBC6723843D8EFA46156D88ED6F6
13  0E2F51A1A4C321E3B67DFDB6FF333F479F7C48D7BF9D9A2008132CA7C576F88E
14  0E75619B7505B0650BF24F0A5A80E6C39026195248A62413AA1CE5BF1EF6DC25
15  0EF0BD03F1E58C5423F4A332838C2DC40A18E076B6C72859AA8B5D677B2E4FDB
16  100FE88F173599977D446598F87ABF7B90AF77DE02506D31CEEDD41A41AC9684
17  1061F224A164848283980697806E133A405F831BD15897EFF1ED7A85B13FA8D9
18  12EA9EA6DA57E1738C21AB9FBB7E44E0F21D4419F70C47683584CAD6ED9C4D6B
19  1314C053A3BA094882EC91EF74989449A1EAFCBAEA75054B7C490BB2521CF468
20  145A2029D3F3378B9DCCE5405017EA7604C3AC14D7FA69D2267B49C9B97332D7
21  14C491E71D81077DFA518FCA76ED494273C030C8AF7E65897CD607013A537674
22  154D377E3E7ECDE96144C978A064D461711CD2CD0B85658429EB6E59448C80A2
23  15DE551ECC9723A6B7D214920E784309FDD9CFF3BA2D70DF12F897EBE710727E
24  161CDCAC6F2A4F846BB87AF3CA0496574BDBCDA96A1DAA8F17D4DCE0FA6DB3EB
25  169AA2AAC633166773B2B02818974E3B5719E99826C157CBF4528983765C57EB
26  17623045CF888706B6604C1B734B26948DED4794081F8369559D926DA3AA3C77
27  1770D14FAE36AF267DFF42CBEFBC51E9572C199B2D6287F6389BA098845AE370
28  19335255AA4C65FF51C75E51461A7799A93B8AECF84654AAB2F84AB7868C210F
29  19CB3F364B8534C419E6C91A2DF2000E806A3E2E691700914297EC9DE3CEE53B
30  1B34A2178CA2316FBF0990F851DD66F7C8A7E5E3C5329A4F90740E2814FE9519
⋮   ⋮
168 D5E91BACABD9F00FC4FB5C1BD8A4AEEAA89F7A431061CD7C50EFE26D7DB5BED1
169 D855E84CB2EB5960C0445963DA4220631BFCE717DFA91E93C378D22F72BF43AB
170 D9C8BC1699A464E4F8D5CF9AF111A83B848B7D45045DDB5C9BD0774A424CB41D
171 DC02CAF6453FE0837C28BA58C45AF0354A639AC3C2CA728696718072D534F6C7
172 DD0C9E69E46EED5B91E69CFF0D619E1BD113876D445FA79FB1DFF6767C5C30D7
173 DDE1BDBF6537D3BE8920C6670E93CCD00180FBA7464807C096355B84BE8FBBB3
174 DFC2C6416EC405ACC727C26A50444FDD374A6A903438CBA4F579544E9F2013AC
175 DFE8133A9EDE5F801B754F496489AC914EE6F19F37C187235A43143EBC2F5F6F
176 E0DAE54C3F760656BEF18C6C4A28FE3CF47A1CEF5ABF705F4A4305FB89BDFDFF
177 E4F849F6751EE0B66928FEBBAAE2DF50603D331F1B97403710890B708193025C
178 E52630F1971081368E343D1FE4F1C8940E2D9F673ACF16A3CE92264A1A45E94C
179 E6CFA976696F6423AE2EE0FE2A44A91FCC37D33A100FE73ECDD4F7833EF4FBDB
180 E7D59B1229CDA387C96AEE364A2A2D187EB97D4F022D47B854E17F6B29C0ABEE
181 E8733366BA8CD501E2F4CD3AEC3964EB3DA5A91C3EEF448689F9393D211F2901
182 E8AE55E4DFD65368659ACF591859A60311A3262CEBFE0FB632B8213B66598BB4
183 E934D9BF6AD89F98D530FCCC5A50F06CFF4EF4ADE33CDF6E489865EB47099BBD
184 ECA4535BD01E253F895FE70C46CE3F131217987CFCD77B49CFD159CCD10F4DD1
185 ECD63682C31FF4DABCE73E4E090C6836647ED6DDE30DA2B32FB657A8B00F8DEA
186 EFEE0742B0239FC3721C4140A049CA1EA017F83CBAD9D9BF38D70D2916A939AD
187 F10E92214D2CC862BDB310F60CBB8F6B0EE7823781C4AC894E21B4DAF39F7847
188 F11D4C41DC94A14C7ABD8FC3277838088341754C26F5BD6E0CD7C61C9C0AF6CF
189 F47AB9C3769EE65C138F65417357EE92AE3B897A1B03171869EE3D51C46EE53F
190 F78339B0B306A8E0FACBA9914347F6CF0EA60A0F9A17B207D6F6F95ABEB4D2D5
191 F7B3C3FB59D463FC687EBD80F88703C30CE9A1C3827B3F6B60DF804BB8F1B2C0
192 F81CF5A4ECFA333FF0C9F81B7D08CD92FE0E58DC38DB2FF0AC4D32CEC8B2792B
193 F85EF3297BE0264C33692EF3A12E8D3588AD91AF392E3AC8AC66DA88A21C248D
194 F8603D6E2FE8FE4F23114E9A4205F201959357130CFFFFF4068AC907F85423E4
195 FA58413B531291D3F7D34205A2791C4C8BE769AB964A400BB092FB083FF4BF81
196 FBC568EEEB3861648164796996A037CC1F4D44EF49558319E47B647BEB3458C6
197 FC82E4F892DFAB469A499FBCA368CD358A5106B046EB3F90BC63D464C77F7BC9
    NCCIS_ACADYR X9                      X10                 X11
1   2015/2016    NEET: Seeking EET       NEET: Seeking EET   Training
2   2015/2016    NEET: Not ready         NEET: Not ready     NEET: Not ready
3   2016/2017    NEET: Seeking EET       NEET: Seeking EET   NEET: Seeking EET
4   2016/2017    NEET: Seeking EET       Training            Training
5   2015/2016    NEET: Seeking EET       Employment          Employment
6   2015/2016    NEET: Seeking EET       Training            Training
7   2016/2017    NEET: Seeking EET       Training            Training
8   2015/2016    NEET: Start date agreed Training            Training
9   2016/2017    NEET: Not ready         Employment          Employment
10  2016/2017    NEET: Seeking EET       Education           Education
11  2015/2016    NEET: Seeking EET       Training            Training
12  2015/2016    NEET: Seeking EET       NEET: Seeking EET   Training
13  2015/2016    NEET: Pregnancy         NEET: Pregnancy     NEET: Pregnancy
14  2015/2016    NEET: Seeking EET       Employment          Employment
15  2016/2017    NEET: Seeking EET       NEET: Seeking EET   NEET: Seeking EET
16  2016/2017    NEET: Teen parent       NEET: Teen parent   NEET: Teen parent
17  2015/2016    NEET: Start date agreed Training            Training
18  2015/2016    NEET: Seeking EET       NEET: Seeking EET   NA
19  2016/2017    NEET: Seeking EET       Training            Training
20  2016/2017    NEET: Not ready         NEET: Not ready     NEET: Not ready
21  2016/2017    NEET: Pregnancy         NEET: Pregnancy     NEET: Pregnancy
22  2015/2016    NEET: Pregnancy         NEET: Pregnancy     NEET: Pregnancy
23  2016/2017    NEET: Seeking EET       NEET: Seeking EET   NEET: Seeking EET
24  2015/2016    NEET: Seeking EET       Training            Training
25  2016/2017    NEET: Seeking EET       Training            Training
26  2015/2016    NEET: Seeking EET       Education           Education
27  2015/2016    NEET: Start date agreed Training            Training
28  2015/2016    NEET: Seeking EET       NEET: Seeking EET   Training
29  2016/2017    NEET: Seeking EET       Employment          Employment
30  2015/2016    NEET: Seeking EET       NEET: Seeking EET   NEET: Seeking EET
⋮   ⋮            ⋮                       ⋮                   ⋮
168 2016/2017    NEET: Seeking EET       NEET: Seeking EET   NEET: Seeking EET
169 2015/2016    NEET: Pregnancy         NEET: Pregnancy     NEET: Pregnancy
170 2016/2017    NEET: Re-engagement     NEET: Re-engagement Training
171 2016/2017    NEET: Seeking EET       NEET: Seeking EET   NEET: Seeking EET
172 2015/2016    NEET: Seeking EET       NEET: Seeking EET   NEET: Pregnancy
173 2015/2016    NEET: Seeking EET       Education           Education
174 2016/2017    NEET: Teen parent       NEET: Teen parent   NEET: Teen parent
175 2015/2016    NEET: Seeking EET       Education           Education
176 2015/2016    NEET: Seeking EET       NEET: Seeking EET   NEET: Seeking EET
177 2016/2017    NEET: Other             NEET: Seeking EET   Employment
178 2016/2017    NEET: Seeking EET       NEET: Seeking EET   NEET: Seeking EET
179 2015/2016    NEET: Seeking EET       NEET: Not ready     NEET: Seeking EET
180 2015/2016    NEET: Seeking EET       NEET: Seeking EET   Employment
181 2015/2016    NEET: Seeking EET       NA                  NEET: Seeking EET
182 2015/2016    NEET: Seeking EET       NEET: Seeking EET   Employment
183 2015/2016    NEET: Seeking EET       Training            NA
184 2016/2017    NEET: Start date agreed Training            Training
185 2015/2016    NEET: Seeking EET       Training            Training
186 2016/2017    NEET: Seeking EET       NEET: Seeking EET   Training
187 2015/2016    NEET: Seeking EET       Training            Training
188 2016/2017    NEET: Seeking EET       Education           Education
189 2016/2017    NEET: Seeking EET       NEET: Seeking EET   NEET: Seeking EET
190 2016/2017    NEET: Seeking EET       NEET: Seeking EET   Training
191 2016/2017    NEET: Start date agreed Employment          Employment
192 2015/2016    NEET: Seeking EET       NA                  Employment
193 2015/2016    NEET: Start date agreed Education           Education
194 2015/2016    NEET: Carer             NEET: Carer         NEET: Carer
195 2015/2016    NEET: Seeking EET       NEET: Seeking EET   NEET: Seeking EET
196 2016/2017    NEET: Seeking EET       Training            Training
197 2016/2017    NEET: Start date agreed Employment          Employment
    X12               X1                  X2
1   Training          Training            NEET: Seeking EET
2   NEET: Not ready   NEET: Not ready     NEET: Teen parent
3   NEET: Seeking EET NA                  NA
4   Training          Training            Training
5   Employment        Employment          Employment
6   Training          Training            Training
7   Training          Training            Training
8   Training          NA                  Education
9   Employment        Employment          Employment
10  Education         Education           NEET: Seeking EET
11  Training          Training            Training
12  Training          Training            Training
13  NA                NA                  NA
14  Employment        Employment          Employment
15  NEET: Seeking EET NA                  NA
16  NEET: Teen parent NEET: Teen parent   NEET: Teen parent
17  NA                Training            Training
18  NEET: Seeking EET NEET: Seeking EET   NA
19  Training          Training            Training
20  NEET: Not ready   NEET: Not ready     NEET: Not ready
21  NEET: Pregnancy   NEET: Teen parent   NEET: Teen parent
22  NEET: Pregnancy   NEET: Pregnancy     NA
23  NEET: Seeking EET NEET: Seeking EET   NEET: Seeking EET
24  Training          Training            Training
25  Training          Training            Training
26  Education         Education           Education
27  Training          Training            Training
28  Training          NEET: Seeking EET   NEET: Seeking EET
29  Employment        Employment          Employment
30  NEET: Seeking EET NEET: Seeking EET   Education
⋮   ⋮                 ⋮                   ⋮
168 NEET: Seeking EET NEET: Seeking EET   NEET: Seeking EET
169 NEET: Pregnancy   NA                  NEET: Teen parent
170 Training          Training            Training
171 NEET: Seeking EET Education           Education
172 NEET: Pregnancy   NEET: Pregnancy     NEET: Pregnancy
173 NA                Education           NA
174 NEET: Teen parent NEET: Teen parent   NEET: Teen parent
175 Education         Education           Education
176 NEET: Seeking EET NEET: Re-engagement NA
177 Employment        Employment          Employment
178 Employment        Employment          Employment
179 NEET: Seeking EET NEET: Seeking EET   NEET: Seeking EET
180 Employment        Employment          Employment
181 NEET: Seeking EET NA                  NEET: Seeking EET
182 Employment        Employment          Employment
183 Education         NA                  NA
184 Training          Training            NEET: Seeking EET
185 NA                Training            NA
186 Training          Training            NA
187 NA                Training            NA
188 Education         Education           Education
189 NEET: Seeking EET NEET: Seeking EET   NEET: Start date agreed
190 Training          Training            Training
191 Employment        Employment          Employment
192 Employment        NA                  Employment
193 Education         Education           Education
194 NEET: Carer       NEET: Carer         NA
195 NEET: Seeking EET NEET: Seeking EET   Education
196 Training          Training            Training
197 Employment        Employment          Employment
    X3                      X4                      ⋯ X6
1   NEET: Seeking EET       NEET: Seeking EET       ⋯ NEET: Seeking EET
2   NEET: Teen parent       NEET: Teen parent       ⋯ NEET: Teen parent
3   NA                      NA                      ⋯ NA
4   Training                Training                ⋯ Training
5   Employment              Training                ⋯ Training
6   Training                Training                ⋯ Training
7   Training                Training                ⋯ Employment
8   Education               Education               ⋯ Education
9   Employment              Employment              ⋯ Employment
10  NEET: Seeking EET       Training                ⋯ Training
11  Training                Training                ⋯ NA
12  Training                Training                ⋯ Training
13  NA                      NA                      ⋯ NA
14  NA                      Employment              ⋯ NA
15  NA                      NA                      ⋯ NEET: Seeking EET
16  NEET: Teen parent       Education               ⋯ NEET: Teen parent
17  Training                Training                ⋯ NA
18  NA                      NEET: Seeking EET       ⋯ NA
19  Training                Training                ⋯ Training
20  NEET: Not ready         NEET: Not ready         ⋯ NEET: Not ready
21  NEET: Teen parent       NEET: Teen parent       ⋯ NEET: Teen parent
22  NEET: Pregnancy         NEET: Pregnancy         ⋯ NEET: Pregnancy
23  NEET: Seeking EET       NEET: Seeking EET       ⋯ NEET: Seeking EET
24  Training                Training                ⋯ Training
25  Training                Training                ⋯ NA
26  Education               Education               ⋯ Education
27  Training                Training                ⋯ NEET: Illness
28  NEET: Seeking EET       Training                ⋯ NEET: Start date agreed
29  Employment              Employment              ⋯ Employment
30  Education               Education               ⋯ Education
⋮   ⋮                       ⋮                       ⋱ ⋮
168 NEET: Seeking EET       NEET: Seeking EET       ⋯ NEET: Seeking EET
169 NEET: Start date agreed NEET: Start date agreed ⋯ NA
170 NEET: Other             NEET: Other             ⋯ NEET: Re-engagement
171 NEET: Seeking EET       Education               ⋯ Employment
172 NEET: Pregnancy         NEET: Pregnancy         ⋯ NEET: Pregnancy
173 NA                      Education               ⋯ NA
174 NEET: Teen parent       NEET: Teen parent       ⋯ NEET: Teen parent
175 Education               Training                ⋯ NA
176 Training                Training                ⋯ Training
177 Employment              Employment              ⋯ Employment
178 Employment              Employment              ⋯ NEET: Seeking EET
179 NEET: Seeking EET       NEET: Seeking EET       ⋯ NEET: Seeking EET
180 Employment              Employment              ⋯ Employment
181 NEET: Seeking EET       NEET: Seeking EET       ⋯ NA
182 Employment              Employment              ⋯ NEET: Seeking EET
183 Education               NA                      ⋯ Education
184 NEET: Seeking EET       NEET: Seeking EET       ⋯ NEET: Seeking EET
185 NEET: Seeking EET       NEET: Seeking EET       ⋯ NEET: Seeking EET
186 Training                Training                ⋯ NEET: Other
187 Training                NA                      ⋯ Training
188 Education               Education               ⋯ Education
189 Training                Training                ⋯ Training
190 Training                Training                ⋯ Training
191 Employment              Employment              ⋯ Employment
192 Employment              Training                ⋯ Training
193 Education               Education               ⋯ Education
194 NA                      NA                      ⋯ NA
195 Education               Education               ⋯ Education
196 Training                Training                ⋯ Training
197 Employment              Employment              ⋯ Employment
    X7                      X8                Education Employment Training
1   NEET: Seeking EET       NEET: Seeking EET  0         0          3
2   NEET: Teen parent       NEET: Teen parent  0         0          0
3   NA                      NA                 0         0          0
4   Training                NA                 0         0         10
5   Training                Training           0         6          5
6   NA                      NA                 0         0          9
7   Employment              Employment         0         4          7
8   Education               Education          7         0          3
9   Employment              Employment         0        11          0
10  Training                NA                 4         0          4
11  NA                      NA                 0         0          8
12  Training                Training           0         0         10
13  NA                      NA                 0         0          0
14  Employment              Employment         0         9          0
15  NEET: Custody           NEET: Custody      0         0          0
16  NEET: Teen parent       NEET: Teen parent  1         0          0
17  NA                      NA                 0         0          7
18  NEET: Seeking EET       Training           0         0          1
19  Training                Training           0         0         11
20  NEET: Not ready         NEET: Seeking EET  0         0          0
21  NEET: Teen parent       NEET: Teen parent  0         0          0
22  NEET: Pregnancy         NA                 0         0          0
23  NEET: Seeking EET       NEET: Seeking EET  0         0          0
24  Training                Training           0         0         11
25  NA                      NA                 0         0          7
26  Education               Education         11         0          0
27  NEET: Illness           NEET: Seeking EET  0         0          7
28  NEET: Start date agreed NEET: Illness      0         0          4
29  Employment              Employment         0        11          0
30  Education               NA                 6         0          0
⋮   ⋮                       ⋮                 ⋮         ⋮          ⋮
168 NEET: Seeking EET       NEET: Seeking EET  0         0          0
169 NEET: Start date agreed NEET: Teen parent  0         0          0
170 NEET: Re-engagement     NEET: Seeking EET  0         0          4
171 Employment              Employment         4         3          0
172 NEET: Pregnancy         Employment         0         1          0
173 Education               NA                 5         0          0
174 NEET: Teen parent       NEET: Teen parent  0         0          0
175 NA                      Training           6         0          3
176 NA                      NA                 0         0          4
177 Employment              Employment         0        10          0
178 NEET: Seeking EET       Employment         0         7          0
179 NEET: Seeking EET       NEET: Seeking EET  0         0          0
180 Employment              Employment         0        10          0
181 NEET: Seeking EET       NA                 0         0          0
182 NEET: Seeking EET       Employment         0         7          0
183 NA                      Education          5         0          1
184 NEET: Seeking EET       NEET: Seeking EET  0         0          4
185 NEET: Seeking EET       NEET: Seeking EET  0         0          3
186 NA                      NEET: Other        0         0          5
187 NA                      Training           0         0          7
188 Education               Education         11         0          0
189 Training                Training           0         0          6
190 Training                Training           0         0         10
191 Employment              Employment         0        11          0
192 NA                      Training           0         4          4

In [39]:
destinations_counts_labelled |>
    group_by(Label) |>
    tally()

  Label            n
1 DROP              2015
2 Risky trajectory  1291
3 Steady EET       14232

In [40]:
write.csv(destinations_counts_labelled, "data/additional_manual_classification.csv", row.names = FALSE)

## Extract person IDs

In [16]:
person_ids <- destinations_counts_labelled |>
    select(person_id, NCCIS_ACADYR)

In [17]:
head(person_ids)

  person_id                                                        NCCIS_ACADYR
1 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2016/2017
2 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 2015/2016
3 000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909 2015/2016
4 00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC 2016/2017
5 0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D 2016/2017
6 0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D 2016/2017

In [18]:
write.csv(person_ids, "data/additional_person_ids.csv", row.names = FALSE)