In [2]:
library(tidyverse)
library(dbplyr)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘dbplyr’


The following objects are masked from ‘package:dplyr’:

    ident, sql

In [3]:
# Read in data
data <- read.csv('data/destinations_wide_detail.csv', header = TRUE)

In [4]:
head(data)

  person_id                                                        NCCIS_ACADYR
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2017/2018
2 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2017/2018
3 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2018/2019
4 0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2018/2019
5 00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66 2017/2018
6 0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D 2017/2018
  Intended_destination X9        X10       X11       X12       X1
1 NA                   Education Education Education Education Education
2 NA                   Education Education Education Education Education
3 NA                   Education Education Education Education Education
4 NA                   Education Education Education Education Education
5 NA                   NA        Education Education Education Education
6 NA                   Education Education Education Education Education
  X2        X3              X4              X5              X6
1 Education Education       Education       Education       Education
2 Education Education       Education       Education       Education
3 Education NEET: Not ready NEET: Not ready NEET: Not ready NEET: Seeking EET
4 Education Education       Education       Education       Education
5 Education Education       Education       Education       Education
6 Education Education       Education       Education       Education
  X7                X8
1 Education         Education
2 Education         Education
3 NEET: Seeking EET NEET: Seeking EET
4 Education         Education
5 Education         NA
6 Education         Education

In [5]:
data |>
    filter(person_id == '0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D')

  person_id                                                        NCCIS_ACADYR
1 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2018/2019
  Intended_destination X9        X10       X11       X12       X1
1 NA                   Education Education Education Education Education
  X2        X3              X4              X5              X6
1 Education NEET: Not ready NEET: Not ready NEET: Not ready NEET: Seeking EET
  X7                X8
1 NEET: Seeking EET NEET: Seeking EET

## Prep data

In [3]:
data |>
    nrow()

[1] 17543

In [6]:
# drop all NAs 
destinations_seq <- data |>
    filter(!if_all(`X9`:`X8`, is.na))

In [7]:
destinations_seq |>
    nrow()

[1] 17361

## add activity counts per row

In [8]:
destinations_counts <- destinations_seq |>
    rowwise() |>
    mutate(
    Education = sum(c_across(`X9`:`X8`) == "Education", na.rm = TRUE),
    Employment = sum(c_across(`X9`:`X8`) == "Employment", na.rm = TRUE),
    Training = sum(c_across(`X9`:`X8`) == "Training", na.rm = TRUE),
    Refused = sum(c_across(`X9`:`X8`) == "Refused", na.rm = TRUE),
    # check starts with 
    NEET = sum(grepl("^NEET", c_across(`X9`:`X8`)), na.rm = TRUE),
    NA_count = sum(is.na(c_across(`X9`:`X8`)))
        ) |>
    ungroup()

## Classify records

In [24]:
destinations_counts |>
 filter(str_starts(X9, 'NEET') & (Education == 11 | Employment == 11 | Training == 11))

   person_id
1  00C46B3D88971DF1EBEFDEB5D91BD0E0DE6CAF37331A66161CDEDE3F6102ADC1
2  0A942C4DE9995D01BEDFB2C69002ACBF364847CEAB5570A59AB858B67C6A2AB6
3  0CB91494A90E3006FE6A7D64C69ABC97753D9298C2AAD15EF1D50F4C0DBEAE6D
4  0D01A21C41B86E59153B4CC7A68F41216823DF8A38E93F162DC51E6D13FD3FD0
5  0F566ADABABA91A707DE281C06841AB05A5E2BAA74C89008DEBE0642A5D75408
6  13B42FD5D363A91665B4D5A6213D9E6C184089978CA688627CC14327A3050F36
7  13D68578D64C06294A3BBFEC424A116C599368433C106C68BEDDA12FB940F086
8  267F352151AA08472D066932A8F509A8FC276127755A29A9D1843E5151E9A341
9  2A08BEF4FE2B9FC31889FD839677330CDB1876071BAA631AD1AD8572B444BADF
10 32336B9F9DB2697B01DED03ED5523D5F927BE688C537C54B02E75662DED7CBA8
11 333DB160F21BAA4D4663004ECA861E5334A39BCD48E46E031A873811697EC7DD
12 4BCD0464107A46F451627DBE908ED1C95B3E5BDD5036B4D2E6617A8079394A8D
13 5233E913BD6E93DC61B3034D44A1FECF21940117363F1890FFDEE2C7D71E0727
14 55853BF9D8F719368C8D62FB7DBB99760FCFD9F645FDDA8DB9D3052558D7D465
15 663280CAA70A58C4803A109E82F737B42B8ECE7E8306B36DC570792AC18BAE40
16 663C2EE465157EC1850BF00013CB6A8683D2680B266372E4D69D199D2C163FE4
17 682A51A0B2C620B7656CD2FC256F53B8A25B89BADD366A9237D782A5E073BD65
18 6DCF45C85B54D20C05E56A34EDEFA8A350A1DA4F95F36D1F4EAC8773DA0344F2
19 74D646C72E7ED4F8BD65493BA76400B568ABE02F3403AE7138628469FA96DBA3
20 7647EFAE6E1BCBC628733F6B1EB3C11A0C4A5AA00D7094CFDA315E89708EFC8A
21 7E4F1024166D95C1255FE926C2E386766A3792187BFF5BF30A63F5E4880D767F
22 81B02D3A5E5537C2A74F44A73F95E6753E7C850C206852D91658D0C061F4E362
23 82E7128461B5F4DC5DCBD4C9DEC27B74BD91020739F68D781F97EF97CC2186B3
24 88878EB7ACA90CB22C2A0DAF4926CA634268C7B83CDF844F564932382FBB4063
25 90971DC9096E2DBC913F9BD88232F03B32CAE61214A500E02457E7FDAC7B7485
26 9187A9B5A86BB58D08A4C24ECB68E9C3D4B3F6F1E41ABA9165D9FCAC2A02D99A
27 953C30C2D9591549CC1F1C9C3083493927768EFBEE89A523DC17CEE8FE2E5A8E
28 9BA4096913D1099789B808C3DA0C4B4BA47428CA951F6F0782E0E1ECAC815A85
29 A17CC8FA0BD4CAA038F28C1230B85F907081B88221504847B8C5338F5B3DCA3F
30 AFA9AC1E70918AB1445B5A1A11286EBAB57170757E52490D9B1E76BF57680F2B
31 B13AA6B5A263EE962BA437C44DCAC85468400E88DB9D6A89213FB680EFE9FD27
32 B196C1456625BD01A06D42A98ADA43931309CB4DF5BCF89FE9740F97AD861BEA
33 B796E81FA4A464AC02E025D8F641F5C7A1C2A4A8C03CBB5661A022E755AD67AE
34 C0546FDFF8DA0E654C6C1E120D3DE6910154E9BBE00E487A2389D07FF4B8AAA4
35 C4709433D274ABB6EA3F34FC1C195A7F6EA915F7A433D83622050A2AB70F87E1
36 CB498CFF9BE1524AD57635C849219C7677D8A3BE82B479D8A92B57D1793970E1
37 CE61E92FE42A0099CF29A397576F0CB090B1F113ECF29DE81E1C9B8E0348FC5F
38 EA670D17679586CE66161A4B2261E77502B127317602BBCA8803B0A76239C6F7
39 EFB209C7D6F2835EBC6AA82CAEC58C1469412960A7DE6F84C34685B80569EF01
40 F5B275E850CEBE99A711FC69C43D34C4E0D9351B0D60E922B1D21055ECCA3A2A
41 FA8BE148939B32FBE703D6672DAB284FABDA4303A6CD75614602C6B81C2FE47D
   NCCIS_ACADYR Intended_destination X9                      X10
1  2018/2019    NA                   NEET: Seeking EET       Education
2  2018/2019    NA                   NEET: Seeking EET       Training
3  2018/2019    NA                   NEET: Start date agreed Education
4  2018/2019    NA                   NEET: Seeking EET       Training
5  2018/2019    NA                   NEET: Seeking EET       Education
6  2018/2019    NA                   NEET: Seeking EET       Training
7  2018/2019    NA                   NEET: Seeking EET       Training
8  2017/2018    NA                   NEET: Seeking EET       Training
9  2017/2018    NA                   NEET: Seeking EET       Training
10 2018/2019    NA                   NEET: Seeking EET       Employment
11 2017/2018    NA                   NEET: Start date agreed Education
12 2018/2019    NA                   NEET: Seeking EET       Education
13 2017/2018    NA                   NEET: Seeking EET       Education
14 2018/2019    NA                   NEET: Seeking EET       Employment
15 2018/2019    NA                   NEET: Seeking EET       Employment
16 2017/2018    NA                   NEET: Seeking EET       Training
17 2017/2018    NA                   NEET: Seeking EET       Education
18 2017/2018    NA                   NEET: Seeking EET       Training
19 2017/2018    NA                   NEET: Seeking EET       Employment
20 2018/2019    NA                   NEET: Seeking EET       Education
21 2018/2019    NA                   NEET: Seeking EET       Education
22 2017/2018    NA                   NEET: Seeking EET       Employment
23 2017/2018    NA                   NEET: Seeking EET       Education
24 2018/2019    NA                   NEET: Seeking EET       Education
25 2017/2018    NA                   NEET: Seeking EET       Employment
26 2017/2018    NA                   NEET: Seeking EET       Employment
27 2018/2019    NA                   NEET: Seeking EET       Education
28 2018/2019    NA                   NEET: Seeking EET       Employment
29 2017/2018    NA                   NEET: Seeking EET       Education
30 2018/2019    NA                   NEET: Seeking EET       Education
31 2017/2018    NA                   NEET: Seeking EET       Employment
32 2017/2018    NA                   NEET: Seeking EET       Education
33 2017/2018    NA                   NEET: Seeking EET       Education
34 2017/2018    NA                   NEET: Seeking EET       Training
35 2017/2018    NA                   NEET: Seeking EET       Education
36 2017/2018    NA                   NEET: Seeking EET       Employment
37 2018/2019    NA                   NEET: Seeking EET       Education
38 2017/2018    NA                   NEET: Other             Employment
39 2017/2018    NA                   NEET: Seeking EET       Employment
40 2017/2018    NA                   NEET: Seeking EET       Training
41 2017/2018    NA                   NEET: Seeking EET       Education
   X11        X12        X1         X2         X3         ⋯ X6
1  Education  Education  Education  Education  Education  ⋯ Education
2  Training   Training   Training   Training   Training   ⋯ Training
3  Education  Education  Education  Education  Education  ⋯ Education
4  Training   Training   Training   Training   Training   ⋯ Training
5  Education  Education  Education  Education  Education  ⋯ Education
6  Training   Training   Training   Training   Training   ⋯ Training
7  Training   Training   Training   Training   Training   ⋯ Training
8  Training   Training   Training   Training   Training   ⋯ Training
9  Training   Training   Training   Training   Training   ⋯ Training
10 Employment Employment Employment Employment Employment ⋯ Employment
11 Education  Education  Education  Education  Education  ⋯ Education
12 Education  Education  Education  Education  Education  ⋯ Education
13 Education  Education  Education  Education  Education  ⋯ Education
14 Employment Employment Employment Employment Employment ⋯ Employment
15 Employment Employment Employment Employment Employment ⋯ Employment
16 Training   Training   Training   Training   Training   ⋯ Training
17 Education  Education  Education  Education  Education  ⋯ Education
18 Training   Training   Training   Training   Training   ⋯ Training
19 Employment Employment Employment Employment Employment ⋯ Employment
20 Education  Education  Education  Education  Education  ⋯ Education
21 Education  Education  Education  Education  Education  ⋯ Education
22 Employment Employment Employment Employment Employment ⋯ Employment
23 Education  Education  Education  Education  Education  ⋯ Education
24 Education  Education  Education  Education  Education  ⋯ Education
25 Employment Employment Employment Employment Employment ⋯ Employment
26 Employment Employment Employment Employment Employment ⋯ Employment
27 Education  Education  Education  Education  Education  ⋯ Education
28 Employment Employment Employment Employment Employment ⋯ Employment
29 Education  Education  Education  Education  Education  ⋯ Education
30 Education  Education  Education  Education  Education  ⋯ Education
31 Employment Employment Employment Employment Employment ⋯ Employment
32 Education  Education  Education  Education  Education  ⋯ Education
33 Education  Education  Education  Education  Education  ⋯ Education
34 Training   Training   Training   Training   Training   ⋯ Training
35 Education  Education  Education  Education  Education  ⋯ Education
36 Employment Employment Employment Employment Employment ⋯ Employment
37 Education  Education  Education  Education  Education  ⋯ Education
38 Employment Employment Employment Employment Employment ⋯ Employment
39 Employment Employment Employment Employment Employment ⋯ Employment
40 Training   Training   Training   Training   Training   ⋯ Training
41 Education  Education  Education  Education  Education  ⋯ Education
   X7         X8         Education Employment Training Refused NEET NA_count
1  Education  Education  11         0          0       0       1    0
2  Training   Training    0         0         11       0       1    0
3  Education  Education  11         0          0       0       1    0
4  Training   Training    0         0         11       0       1    0
5  Education  Education  11         0          0       0       1    0
6  Training   Training    0         0         11       0       1    0
7  Training   Training    0         0         11       0       1    0
8  Training   Training    0         0         11       0       1    0
9  Training   Training    0         0         11       0       1    0
10 Employment Employment  0        11          0       0       1    0
11 Education  Education  11         0          0       0       1    0
12 Education  Education  11         0          0       0       1    0
13 Education  Education  11         0          0       0       1    0
14 Employment Employment  0        11          0       0       1    0
15 Employment Employment  0        11          0       0       1    0
16 Training   Training    0         0         11       0       1    0
17 Education  Education  11         0          0       0       1    0
18 Training   Training    0         0         11       0       1    0
19 Employment Employment  0        11          0       0       1    0
20 Education  Education  11         0          0       0       1    0
21 Education  Education  11         0          0       0       1    0
22 Employment Employment  0        11          0       0       1    0
23 Education  Education  11         0          0       0       1    0
24 Education  Education  11         0          0       0       1    0
25 Employment Employment  0        11          0       0       1    0
26 Employment Employment  0        11          0       0       1    0
27 Education  Education  11         0          0       0       1    0
28 Employment Employment  0        11          0       0       1    0
29 Education  Education  11         0          0       0       1    0
30 Education  Education  11         0          0       0       1    0
31 Employment Employment  0        11          0       0       1    0
32 Education  Education  11         0          0       0       1    0
33 Education  Education  11         0          0       0       1    0
34 Training   Training    0         0         11       0       1    0
35 Education  Education  11         0          0       0       1    0
36 Employment Employment  0        11          0       0       1    0
37 Education  Education  11         0          0       0       1    0
38 Employment Employment  0        11          0       0       1    0
39 Employment Employment  0        11          0       0       1    0
40 Training   Training    0         0         11       0       1    0
41 Education  Education  11         0          0       0       1    0
   Label
1  NA
2  NA
3  NA
4  NA
5  NA
6  NA
7  NA
8  NA
9  NA
10 NA
11 NA
12 NA
13 NA
14 NA
15 NA
16 NA
17 NA
18 NA
19 NA
20 NA
21 NA
22 NA
23 NA
24 NA
25 NA
26 NA
27 NA
28 NA
29 NA
30 NA
31 NA
32 NA
33 NA
34 NA
35 NA
36 NA
37 NA
38 NA
39 NA
40 NA
41 NA

In [6]:
destinations_counts |>
    filter(NEET == 1)

ERROR: Error: object 'destinations_counts' not found

In [25]:
destinations_counts_labelled <- destinations_counts |>
    mutate(Label = case_when(
        NEET == 0 & Refused == 0 & NA_count <= 4 ~ 'Steady EET',
        str_starts(X9, 'NEET') & (Education == 11 | Employment == 11 | Training == 11) ~ 'Steady EET',
        NEET == 0 & Refused == 0 & NA_count >= 5 ~ 'DROP',
        TRUE ~ 'Risky trajectory'
    )
          )

In [26]:
head(destinations_counts_labelled)

  person_id                                                        NCCIS_ACADYR
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2017/2018
2 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2017/2018
3 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2018/2019
4 0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2018/2019
5 00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66 2017/2018
6 0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D 2017/2018
  Intended_destination X9        X10       X11       X12       X1
1 NA                   Education Education Education Education Education
2 NA                   Education Education Education Education Education
3 NA                   Education Education Education Education Education
4 NA                   Education Education Education Education Education
5 NA                   NA        Education Education Education Education
6 NA                   Education Education Education Education Education
  X2        X3              ⋯ X6                X7
1 Education Education       ⋯ Education         Education
2 Education Education       ⋯ Education         Education
3 Education NEET: Not ready ⋯ NEET: Seeking EET NEET: Seeking EET
4 Education Education       ⋯ Education         Education
5 Education Education       ⋯ Education         Education
6 Education Education       ⋯ Education         Education
  X8                Education Employment Training Refused NEET NA_count
1 Education         12        0          0        0       0    0
2 Education         12        0          0        0       0    0
3 NEET: Seeking EET  6        0          0        0       6    0
4 Education         12        0          0        0       0    0
5 NA                10        0          0        0       0    2
6 Education         12        0          0        0       0    0
  Label
1 Steady EET
2 Steady EET
3 Risky trajectory
4 Steady EET
5 Steady EET
6 Steady EET

In [27]:
destinations_counts_labelled |>
    filter(Label == 'Risky trajectory')

     person_id
1    0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D
2    004C012DC8B27D82CC173C9590867A88C8B60E6F4C1EAE8AF73D53403DDD94B5
3    006E3883AF0261A8C303A137715C7DD62949D75FFD52F75536E0B79CECCC90E0
4    00748B650176730AAF7158DCC2B2B974C8EB08D2BE8195BBD107F3B670619625
5    00C0B218E62078028895BA8B9A96ED2A1B86CAF3C3B653E39FB4E3DAF90F32CF
6    00D2D54BE54AA2D95A4868BF01E6147645BD35B1DE9161DC1AC32D1B2570E2E7
7    00F9642EF1D0BB625578567B677490A2EEBE306021240F417B77AD63393D181B
8    013DEF439FBB5DB5FAB8CA66A79222C46E828A7FBC647474C2F3FDCA63108D0D
9    017AA9CBE090DF46D824482BB63267EDF494C0D84BE1C2BC263D2A4300750CD6
10   01DD211111ECE9C51A992B85C0E53F8F3A604974F18AD8B5C0C2A2071C05D8DC
11   01E74FE539898CA37AFE04F3B0C019209B4EF7F64BDC6432903FBC3FB30499F9
12   020F1C3CBCBA82F471211F1C683B7ABE70CF0476AABADCC69E982AFF59D555B2
13   022EA0E9BDEA7A2C0AF53A76467D3534FC54CD50CDA1D436B128DA9C2003CC44
14   022F553C8D5DE4A0755A27CA598FF883FD25BF6F3E56FAAAF608767BC08DE454
15   0239CB13E86E69A92111DA56243394D513190F44FCA0BC9F32EDB644681F206E
16   02593FF7C3ABE5D24DF2B9A09EF95058223BBB972E0AFA4C14A2A1C44EC7B9C7
17   02595CE994DD5ECD2F333CA5DBBD7B837CBF7D7DA266D568C3E685E6548AE7C4
18   026BB132BE76E80F2D3832CA81E7F678083C092E53B4C5728A6B78EAFCC01D1F
19   0317517706435728CB50772F8043FB1DCAB138D9D2022A181C3FDF432537AD4F
20   033E241E6E358BB13B3B68DDA9EEEBC7C7551A6E91C4DDFA9C6FB58A5882F9FB
21   035BC8D747E87A7E8B6193B4023B70429A0DA0A89E2CABAB5A30BBD930968AD1
22   03771DA89236BFA5902AD7B4EAEE11A07C4B8FE9B29A5D2335694EF70B876064
23   03775A2E25D4145883BF71B42DA0A6E54F6ACECB0D883B47F5E145FC8645D83B
24   03BE328727F8B32160112E287DC848E88E6EE77A766F17ED8890BFACDAA7EC71
25   043F103AD6014F80C7D7CAB9B774D0E78339D1D45BD29F6B031C068C14AC5A5E
26   05199DA492E2CD51438EC7982A6F36031B6E7FDD594660A1BD4D7E1CF4028FF4
27   0558143D7871BA70A789D99B69FFE1F3F793AC8D59A48E31DB7933D84F870536
28   0579B034907549F982D090B28DC706287FD3C30A07DB6B11A668B79FD2E34CD1
29   05D7F2723D01B95B59DEB210822A56A43E2D6225A998496B5595628422D79987
30   05ED71E2362D0C7590E9D0D18CCFAAEA41E61FA4DE962B572F99480F2897637B
⋮    ⋮
1332 FA3E2B591A3824F495AB17AB690040D6C0919FA0808C430CB2C9FBEABBAB6197
1333 FA51CC8EDCEE91F3D48DB0C891BB1A64E874355B6068FAB55814905F6A311A97
1334 FA6D0B4F1281DDB4FDB00A1414ACAAA8231F06C992FBDDEEDEE8A5C047993328
1335 FA76E56F0496F03DFD38BA75C16C24276A1D3F8DDCA07CD49361402DD5A3079C
1336 FA9F2C8A1CD0DB3577DEC062D5CF7989684A288E27196F6C96DE787B4F922A8C
1337 FAD037C896B7A2D007A892A4EEB29E323FC63B519F8CFA6E567C3CE1DF954986
1338 FAED169A0CCB43ED5827B9E70D21E40CAA56E2F142C2B2C8A7C18A2F5FE108FF
1339 FB271D5E270BD0CCAF1921D95BE93F14CA28AD3412BF63E5A414487E1042F283
1340 FB2F56F2E6078168C52EDDC4C6627BB04B68D3B6908F5C4C933CAE63A233522D
1341 FB9A342F723ECD7C7041101DD48C4DC10DE7F8018B3FD79277D276D3FB83C9BB
1342 FC24532EEDD9382AAB92F04527471B0D5E787D01542D62E07F02F13E4F230D0F
1343 FC4A9A9ECC56374706EC415D1FA433DF7C815C0F5048A15BF7AF96DF0CEF3933
1344 FC75E971A3410652B9D9F99A9C6D74114EC2A96A693A1A296FE3CC6BA765609F
1345 FC81F57525BB9A5BE56F2ABF7EC0EFF775440408B2E36FDE51784D13E4AC911B
1346 FCC8E53CB3300C59300AED3205FAD055DAFAEFCA45C6CCD36712CAB36BDE3D1E
1347 FD1CC885BF0C1250D6D14D8DDE3371DDDBB48E86540F28D0ACFA242333C299B1
1348 FDBE0448D4959DB5165A9BB71940DA7AD6671E211F87870ACF8D6F72A6BA7A07
1349 FDC377A3B03FFD9B5BAB7E276262BCA9463A0D163952E2E666165FDBAAEBA48F
1350 FDC42D870F4E543269597251D35AF7AA029CB5D8777D8DF2B1687466931E10B4
1351 FE3895C54AD1AFAF3487E0DC4AE5D797D949AD1A6BFD767C2A250826F71E8299
1352 FE5A0494239487D87B120AC5C4A84EA18702EFCE46F18C31242D54DADB719158
1353 FE62136351D25364A03E152B58D1507820BE6872717A8FAE45AF085EA0B983FD
1354 FE737D5A827209CC32950B486BEAB7C99965AB0DFF3FE0DAAAE79ED8065E4CCA
1355 FEA4D3C284E413C68FA036CE02B6CF030FC7A2B0DF0CB5A2A60E47E83BBA4624
1356 FEBF37D66CE5EE7404F5DDEFEB7A70DFACA3FBF806F9440B856A364E84DD77A1
1357 FF166F1349783175407313E35C3E20105BB7BFACC3680798961FE9C9B8E41FA7
1358 FF3752BEEFF14D8C9F4DAF38DD5806E47CFD4A1F51CADCA375E885EE3D6CF5E2
1359 FF40E206271C27C81CBC640537EBD223DA63168EFE943D7A0352F840B8BC79BC
1360 FFD30596592DA2C82B86241FBA35E56C7384E7EF8219DB076458B4F9ACDED786
1361 FFE1AA7D705C959745A85B91C6D3F3D22A57B8E50092E9EC25046F6986F77D96
     NCCIS_ACADYR Intended_destination X9                X10
1    2018/2019    NA                   Education         Education
2    2018/2019    NA                   NA                NEET: Seeking EET
3    2017/2018    NA                   Education         Education
4    2017/2018    NA                   NA                Employment
5    2017/2018    NA                   NA                Education
6    2017/2018    NA                   NEET: Seeking EET Employment
7    2017/2018    NA                   Education         Education
8    2018/2019    NA                   NA                Education
9    2017/2018    NA                   Employment        Employment
10   2018/2019    NA                   NA                Education
11   2018/2019    EET                  Education         NEET: Seeking EET
12   2017/2018    NA                   NA                Education
13   2018/2019    NA                   Employment        Employment
14   2018/2019    NA                   NA                Training
15   2018/2019    NA                   Education         Education
16   2018/2019    NA                   NA                Training
17   2018/2019    NA                   Education         NEET: Seeking EET
18   2018/2019    NA                   Education         Education
19   2018/2019    NA                   NA                NEET: Seeking EET
20   2017/2018    NA                   Education         Education
21   2018/2019    NA                   NA                Education
22   2018/2019    NA                   NEET: Not ready   Training
23   2017/2018    NA                   NA                NA
24   2017/2018    NA                   Education         Education
25   2018/2019    NA                   Education         Education
26   2017/2018    NA                   Education         Education
27   2018/2019    NA                   NA                NA
28   2018/2019    NA                   NA                NEET: Seeking EET
29   2018/2019    NA                   NA                NA
30   2017/2018    NA                   Education         Training
⋮    ⋮            ⋮                    ⋮                 ⋮
1332 2018/2019    NA                   NEET: Seeking EET NEET: Seeking EET
1333 2018/2019    NA                   Education         Education
1334 2018/2019    NA                   NA                NEET: Not ready
1335 2018/2019    NA                   NEET: Seeking EET NEET: Other
1336 2018/2019    NA                   Education         Training
1337 2017/2018    NA                   NEET: Seeking EET Training
1338 2017/2018    NA                   NA                NEET: Seeking EET
1339 2018/2019    EET                  NEET: Illness     NEET: Illness
1340 2018/2019    NA                   NA                NEET: Seeking EET
1341 2017/2018    NA                   NA                NA
1342 2018/2019    NA                   Education         Education
1343 2018/2019    NA                   Employment        Employment
1344 2018/2019    NA                   Education         Education
1345 2017/2018    NA                   Education         Education
1346 2017/2018    NA                   Education         Education
1347 2017/2018    NA                   NEET: Seeking EET Training
1348 2018/2019    NA                   NA                NA
1349 2017/2018    NA                   Education         Education
1350 2018/2019    NA                   Education         Education
1351 2017/2018    NA                   NA                NEET: Seeking EET
1352 2017/2018    NA                   NA                NEET: Seeking EET
1353 2017/2018    NA                   NA                Education
1354 2017/2018    NA                   Education         Education
1355 2017/2018    NA                   NA                NA
1356 2017/2018    NA                   Education         Education
1357 2018/2019    NA                   Education         NEET: Seeking EET
1358 2018/2019    NA                   NA                NA
1359 2018/2019    NA                   NEET: Seeking EET NEET: Seeking EET
1360 2017/2018    NA                   NA                Training
1361 2017/2018    NA                   NA                Training
     X11                     X12                     X1
1    Education               Education               Education
2    Training                Training                Training
3    Education               Education               Education
4    Employment              NEET: Start date agreed Training
5    NEET: Start date agreed Training                Training
6    Employment              Employment              NEET: Seeking EET
7    Education               Education               Education
8    Education               Education               Education
9    Employment              Employment              NEET: Seeking EET
10   Education               Education               Education
11   NEET: Seeking EET       NEET: Seeking EET       NEET: Seeking EET
12   Education               NEET: Start date agreed Training
13   Employment              NEET: Seeking EET       NEET: Seeking EET
14   Training                Training                Training
15   Education               NEET: Seeking EET       Training
16   NEET: Seeking EET       NEET: Seeking EET       NEET: Start date agreed
17   NEET: Seeking EET       NEET: Seeking EET       NEET: Seeking EET
18   Education               Education               Education
19   NEET: Seeking EET       Training                Training
20   Education               Education               NEET: Seeking EET
21   Education               Education               NEET: Seeking EET
22   Training                Training                Training
23   NA                      NEET: Not ready         NEET: Not ready
24   NEET: Seeking EET       NEET: Seeking EET       Education
25   Education               Education               Education
26   Education               Education               Education
27   NA                      NA                      NA
28   NEET: Seeking EET       NEET: Seeking EET       Training
29   NA                      NA                      NEET: Seeking EET
30   Training                Training                NEET: Seeking EET
⋮    ⋮                       ⋮                       ⋮
1332 NEET: Seeking EET       NEET: Seeking EET       NEET: Seeking EET
1333 NEET: Seeking EET       NEET: Seeking EET       NEET: Not ready
1334 NEET: Not ready         NEET: Not ready         NEET: Not ready
1335 NEET: Seeking EET       NEET: Seeking EET       NEET: Seeking EET
1336 Training                Training                NA
1337 Training                Training                Training
1338 NEET: Seeking EET       NEET: Seeking EET       NEET: Seeking EET
1339 NEET: Illness           NEET: Illness           NEET: Illness
1340 NEET: Seeking EET       NEET: Seeking EET       NEET: Seeking EET
1341 NA                      NEET: Seeking EET       Education
1342 Education               Education               NEET: Seeking EET
1343 NA                      NA                      NA
1344 Education               Education               Education
1345 Education               Education               Education
1346 Education               Education               Education
1347 Training                Training                Employment
1348 NA                      NA                      NA
1349 Education               Education               Education
1350 Education               Education               NEET: Seeking EET
1351 NEET: Seeking EET       NEET: Seeking EET       NEET: Teen parent
1352 NEET: Seeking EET       NEET: Seeking EET       NEET: Seeking EET
1353 Training                Training                Training
1354 NEET: Start date agreed NEET: Seeking EET       Training
1355 NEET: Other             NEET: Other             NEET: Other
1356 Education               Education               Education
1357 NEET: Seeking EET       NEET: Seeking EET       NEET: Seeking EET
1358 NA                      Education               Education
1359 NEET: Seeking EET       NEET: Seeking EET       NEET: Seeking EET
1360 Training                Training                Training
1361 Training                Training                NEET: Seeking EET
     X2                      X3                      ⋯ X6
1    Education               NEET: Not ready         ⋯ NEET: Seeking EET
2    Training                Training                ⋯ NEET: Seeking EET
3    Education               NEET: Seeking EET       ⋯ NEET: Other
4    Training                Training                ⋯ NEET: Start date agreed
5    Training                Training                ⋯ Training
6    NEET: Seeking EET       NEET: Pregnancy         ⋯ NEET: Teen parent
7    Education               Education               ⋯ Education
8    Education               Education               ⋯ Education
9    NEET: Seeking EET       NEET: Seeking EET       ⋯ Training
10   Education               NEET: Seeking EET       ⋯ NEET: Seeking EET
11   NEET: Seeking EET       Education               ⋯ Education
12   Training                Training                ⋯ Training
13   NEET: Seeking EET       NEET: Seeking EET       ⋯ Employment
14   Training                Training                ⋯ Training
15   Training                Training                ⋯ NEET: Seeking EET
16   NEET: Seeking EET       NEET: Seeking EET       ⋯ Education
17   NEET: Seeking EET       NEET: Seeking EET       ⋯ NEET: Seeking EET
18   Education               Education               ⋯ NEET: Seeking EET
19   Training                Training                ⋯ Training
20   NEET: Seeking EET       NEET: Seeking EET       ⋯ Education
21   NEET: Seeking EET       NEET: Seeking EET       ⋯ NEET: Seeking EET
22   Training                NEET: Not ready         ⋯ NEET: Not ready
23   NEET: Not ready         NEET: Not ready         ⋯ NEET: Not ready
24   Education               Education               ⋯ Education
25   NEET: Start date agreed NEET: Illness           ⋯ NEET: Illness
26   Education               NEET: Start date agreed ⋯ NEET: Seeking EET
27   NA                      NA                      ⋯ NA
28   Training                Training                ⋯ Training
29   Education               Education               ⋯ Education
30   NEET: Seeking EET       NEET: Seeking EET       ⋯ Training
⋮    ⋮                       ⋮                       ⋱ ⋮
1332 NEET: Seeking EET       NEET: Seeking EET       ⋯ Employment
1333 NEET: Not ready         NEET: Not ready         ⋯ NEET: Seeking EET
1334 Employment              Employment              ⋯ Employment
1335 NEET: Carer             NEET: Carer             ⋯ NEET: Carer
1336 Refused                 Refused                 ⋯ NEET: Seeking EET
1337 Training                Training                ⋯ NEET: Seeking EET
1338 NEET: Seeking EET       NEET: Seeking EET       ⋯ NEET: Seeking EET
1339 Education               Education               ⋯ Education
1340 NEET: Seeking EET       NEET: Seeking EET       ⋯ Employment
1341 Education               Education               ⋯ Education
1342 Education               Education               ⋯ Education
1343 NA                      NEET: Seeking EET       ⋯ Employment
1344 NEET: Seeking EET       NEET: Seeking EET       ⋯ Training
1345 Education               Education               ⋯ NEET: Seeking EET
1346 NEET: Start date agreed Training                ⋯ Training
1347 Employment              Employment              ⋯ Employment
1348 NA                      NA                      ⋯ NEET: Not ready
1349 Education               Education               ⋯ Training
1350 Training                Training                ⋯ Training
1351 NEET: Teen parent       NEET: Teen parent       ⋯ NEET: Teen parent
1352 NEET: Seeking EET       NEET: Seeking EET       ⋯ NA
1353 Training                Training                ⋯ NEET: Seeking EET
1354 Training                NA                      ⋯ NEET: Seeking EET
1355 Employment              Employment              ⋯ Employment
1356 Education               Education               ⋯ NEET: Seeking EET
1357 NEET: Seeking EET       NEET: Seeking EET       ⋯ NEET: Seeking EET
1358 Education               Education               ⋯ NEET: Re-engagement
1359 NEET: Seeking EET       NEET: Seeking EET       ⋯ Refused
1360 Training                Training                ⋯ Training
1361 Training                Training                ⋯ NA
     X7                      X8                      Education Employment
1    NEET: Seeking EET       NEET: Seeking EET        6        0
2    NEET: Seeking EET       NEET: Start date agreed  0        0
3    NEET: Other             NEET: Start date agreed  6        0
4    NEET: Start date agreed NEET: Start date agreed  0        2
5    Training                NEET: Seeking EET        1        0
6    NEET: Teen parent       NEET: Teen parent        0        3
7    Education               NEET: Seeking EET       11        0
8    Education               NEET: Seeking EET       10        0
9    Training                Training                 0        4
10   NEET: Seeking EET       NEET: Start date agreed  5        0
11   Education               Education                7        0
12   Training                Training                 2        0
13   Employment              Employment               0        8
14   NA                      NEET: Seeking EET        0        0
15   Training                Training                 3        0
16   Education               Education                3        0
17   NEET: Seeking EET       NEET: Seeking EET        1        0
18   NEET: Seeking EET       NEET: Start date agreed  9        0
19   Training                NA                       0        0
20   NEET: Seeking EET       NEET: Seeking EET        5        0
21   Employment              Employment               3        2
22   NEET: Seeking EET       NEET: Seeking EET        0        0
23   NEET: Not ready         NEET: Not ready          0        0
24   Education               Education               10        0
25   NEET: Illness           NEET: Illness            5        0
26   NEET: Seeking EET       NEET: Seeking EET        6        0
27   NEET: Seeking EET       NEET: Seeking EET        0        0
28   Training                Training                 0        0
29   Education               Education                7        0
30   Training                Training                 1        0
⋮    ⋮                       ⋮                       ⋮         ⋮
1332 Employment              Employment               0        3
1333 NEET: Seeking EET       NEET: Seeking EET        2        0
1334 Employment              Employment               0        7
1335 NEET: Carer             NEET: Carer              0        0
1336 Employment              Employment               1        2
1337 NEET: Teen parent       NEET: Teen parent        0        0
1338 NEET: Seeking EET       NEET: Seeking EET        0        0
1339 Education               Education                7        0
1340 Employment              Employment               0        5
1341 Education               Education                8        0
1342 Education               Education               11        0
1343 Employment              Employment               0        6
1344 Training                NEET: Seeking EET        5        0
1345 NEET: Seeking EET       NA                       7        0
1346 Training                Training                 5        0
1347 Employment              Employment               0        8
1348 NEET: Not ready         NEET: Start date agreed  0        0
1349 Training                Training                 7        0
1350 Training                NEET: Seeking EET        4        0

In [28]:
destinations_counts_labelled |>
    filter(str_starts(X9, 'NEET'))

    person_id
1   00C46B3D88971DF1EBEFDEB5D91BD0E0DE6CAF37331A66161CDEDE3F6102ADC1
2   00D2D54BE54AA2D95A4868BF01E6147645BD35B1DE9161DC1AC32D1B2570E2E7
3   03771DA89236BFA5902AD7B4EAEE11A07C4B8FE9B29A5D2335694EF70B876064
4   063216C2332702E36554685047F070ADE599365E8193BF57918CA73D5DE2E106
5   069DA23DCA0EFEE4631389D6B2BE4E2E6C40D3F0A10B172A6BD7D63E509CC67B
6   0A2D7A763027FB15C7F1AF60925BEFD106F1D989E6994ACD2EC92CB9B3924E21
7   0A942C4DE9995D01BEDFB2C69002ACBF364847CEAB5570A59AB858B67C6A2AB6
8   0BA571FAB8736DC2F5593C7CF04A1E755E046E4A8872FB4FD224C7049107C7BE
9   0C824E388720F4BE7B318BE44F24E5B388D46DB77AB71198426BA62C12092F7A
10  0CB91494A90E3006FE6A7D64C69ABC97753D9298C2AAD15EF1D50F4C0DBEAE6D
11  0D01A21C41B86E59153B4CC7A68F41216823DF8A38E93F162DC51E6D13FD3FD0
12  0EE4D8F675C63BA9C20CBF8B8DFED61FF8544B73FF4AB968191E7FC179B98DD5
13  0F566ADABABA91A707DE281C06841AB05A5E2BAA74C89008DEBE0642A5D75408
14  0F58B15ABACF2CC2A799B53D23633B5C0DEEFC6A71596A97B6A060668D0D03D0
15  13B42FD5D363A91665B4D5A6213D9E6C184089978CA688627CC14327A3050F36
16  13D68578D64C06294A3BBFEC424A116C599368433C106C68BEDDA12FB940F086
17  15B6C949DC1B2490A59290C9A487D294631ABB9E713B4720A5A6A549F9107AB2
18  162B7DE34DC5E1E98CB7CE1C0987E20DDD3E5E9E1583AD0E440EC6B6D858AE1F
19  16CCD5CDF042931FE711F9B2D9739455275BD8F40BBBAA5A2F06DAC3BB981D77
20  1B447708FFC4AE5B5F71D27B1D7591863B4F6988EF2D50A01A64CEAFE08C0EA5
21  1BD1FC40BAB240709C7A52B2854752F62A0C388552A69AD07086866515B7CAF5
22  1ED7ADC586588E55FBFD941570D98DCB0E06146B7A42B8888E4196E9EFA11FA6
23  24C2C2D290447C32B2F004701B70EB06E3AF9BCD175E3C2A1EED4108E1E5B562
24  259BF856FEF2FC42D931FC5AF6A310188A0D1C7501345FB78DD585BE68B46840
25  267F352151AA08472D066932A8F509A8FC276127755A29A9D1843E5151E9A341
26  26DDDC021236BF2C055420ADBC21574CC07DB4A64A6FFCD921E5AEAF736F7006
27  275F75641738A297C062EA20DB43AC4FD2766FF9F68E827C558BD92262E44097
28  289F61A48786CF309648DD884C6982596FDAB88CBE5DE030B27661A3C5EA917F
29  29F07F40F78DB9EA0118980BFD428CED17A3430F65BDFEF2FAA6A9CEA08E2769
30  2A08BEF4FE2B9FC31889FD839677330CDB1876071BAA631AD1AD8572B444BADF
⋮   ⋮
162 E5F049C08E4CE7E6A2919BB213C7F8111D30B7B451D64E91DFDD52EF1D11CEFA
163 E69DFE39D952F1852B23F65D5B7916879B13F042475E3AA8765602C1C341CA76
164 E6E04020677713A99A010DAA6F60F5D5175BBD627BB6E08D36A61F73F56E21FC
165 E87B4F1DD9484F900E998382D1606F9CB39298716D1D3121D25DBCA75BDEA08B
166 E891B044F3EF5574592575824696FCB0A36088AC566895C92256707227EFE7B4
167 EA670D17679586CE66161A4B2261E77502B127317602BBCA8803B0A76239C6F7
168 EAF7DDCB07B72913D1A8E67FB136F54CE0B981EBF11CBE6C939526B9AA2758D0
169 EB6E199B7972C2A8FB4EA32E09CB6955DD8B9D5951E10D0A117C59CAED8D06A4
170 EBE8B69B74BC09CA964A765F60FCA87A8AE5B60E2D1800584D81F1E940B64224
171 ECDA0D75DEBECB8F41BAD8A9B7ED9ABA887D5BEEA5EABE8E407B650F9616B627
172 EDA9AFF3016BEC264D19916015673BFA9B430A3ADD81EB373A3C0552D8CD22E4
173 EFB209C7D6F2835EBC6AA82CAEC58C1469412960A7DE6F84C34685B80569EF01
174 F0AC583662BFDB0ED1C37CC351193E24B21FC1BA2AD227DB82639266186D6303
175 F0FF157818F23C629B905903D84A364A8FFF4F7D0D16BEE4A4D1FD16D76A77B3
176 F13E22543AB649497BCEED49068715E6A8ED5674DE63B2CEDF67C8928A22F593
177 F16767B13F01FDCA116AF71D0367B7F99031F569B8E777C1A2B4A3A3D4738DDE
178 F2A5A46DEF17BFC0B9AC678301F5EE8F1F5A8AF7457587D30C16E029548329B2
179 F310A13E5B16B568ABB0ED7908CE2B16A87942C6C554085F1C52475A43C65A49
180 F451F04C700632C188C1C712E0744F02861CCFF92EDA780D110F28D75F0CD959
181 F4551EA2A69E9DD265A9FAFAAC52126F24F8EC290E812B52F3D86C718FD59CBD
182 F47A818080871C256B377CA318295958C615E73184C59D87D9DC9DBC481EA523
183 F5B275E850CEBE99A711FC69C43D34C4E0D9351B0D60E922B1D21055ECCA3A2A
184 F5B422DA1456B61528A988BF852402C21B766AF6F4C48AF13AB8D661C01D7240
185 FA3E2B591A3824F495AB17AB690040D6C0919FA0808C430CB2C9FBEABBAB6197
186 FA76E56F0496F03DFD38BA75C16C24276A1D3F8DDCA07CD49361402DD5A3079C
187 FA8BE148939B32FBE703D6672DAB284FABDA4303A6CD75614602C6B81C2FE47D
188 FAD037C896B7A2D007A892A4EEB29E323FC63B519F8CFA6E567C3CE1DF954986
189 FB271D5E270BD0CCAF1921D95BE93F14CA28AD3412BF63E5A414487E1042F283
190 FD1CC885BF0C1250D6D14D8DDE3371DDDBB48E86540F28D0ACFA242333C299B1
191 FF40E206271C27C81CBC640537EBD223DA63168EFE943D7A0352F840B8BC79BC
    NCCIS_ACADYR Intended_destination X9
1   2018/2019    NA                   NEET: Seeking EET
2   2017/2018    NA                   NEET: Seeking EET
3   2018/2019    NA                   NEET: Not ready
4   2018/2019    NA                   NEET: Seeking EET
5   2018/2019    NA                   NEET: Seeking EET
6   2018/2019    NA                   NEET: Seeking EET
7   2018/2019    NA                   NEET: Seeking EET
8   2017/2018    NA                   NEET: Seeking EET
9   2017/2018    NA                   NEET: Not ready
10  2018/2019    NA                   NEET: Start date agreed
11  2018/2019    NA                   NEET: Seeking EET
12  2017/2018    NA                   NEET: Seeking EET
13  2018/2019    NA                   NEET: Seeking EET
14  2017/2018    NA                   NEET: Not ready
15  2018/2019    NA                   NEET: Seeking EET
16  2018/2019    NA                   NEET: Seeking EET
17  2018/2019    NA                   NEET: Seeking EET
18  2017/2018    NA                   NEET: Re-engagement
19  2017/2018    NA                   NEET: Seeking EET
20  2017/2018    NA                   NEET: Seeking EET
21  2018/2019    NA                   NEET: Seeking EET
22  2018/2019    NA                   NEET: Seeking EET
23  2018/2019    NA                   NEET: Seeking EET
24  2017/2018    NA                   NEET: Not ready
25  2017/2018    NA                   NEET: Seeking EET
26  2018/2019    NA                   NEET: Seeking EET
27  2018/2019    NA                   NEET: Other
28  2018/2019    NA                   NEET: Seeking EET
29  2017/2018    NA                   NEET: Seeking EET
30  2017/2018    NA                   NEET: Seeking EET
⋮   ⋮            ⋮                    ⋮
162 2017/2018    NA                   NEET: Seeking EET
163 2017/2018    NEET                 NEET: Re-engagement
164 2018/2019    NA                   NEET: Seeking EET
165 2017/2018    EET                  NEET: Re-engagement
166 2018/2019    NA                   NEET: Illness
167 2017/2018    NA                   NEET: Other
168 2018/2019    NA                   NEET: Seeking EET
169 2017/2018    NA                   NEET: Illness
170 2018/2019    NA                   NEET: Seeking EET
171 2017/2018    NA                   NEET: Seeking EET
172 2018/2019    NA                   NEET: Seeking EET
173 2017/2018    NA                   NEET: Seeking EET
174 2018/2019    NA                   NEET: Seeking EET
175 2017/2018    NA                   NEET: Start date agreed
176 2018/2019    NA                   NEET: Seeking EET
177 2018/2019    NA                   NEET: Seeking EET
178 2018/2019    EET                  NEET: Working: no reward
179 2017/2018    NA                   NEET: Seeking EET
180 2018/2019    NA                   NEET: Seeking EET
181 2017/2018    NA                   NEET: Seeking EET
182 2017/2018    NA                   NEET: Seeking EET
183 2017/2018    NA                   NEET: Seeking EET
184 2018/2019    NA                   NEET: Seeking EET
185 2018/2019    NA                   NEET: Seeking EET
186 2018/2019    NA                   NEET: Seeking EET
187 2017/2018    NA                   NEET: Seeking EET
188 2017/2018    NA                   NEET: Seeking EET
189 2018/2019    EET                  NEET: Illness
190 2017/2018    NA                   NEET: Seeking EET
191 2018/2019    NA                   NEET: Seeking EET
    X10                      X11                      X12
1   Education                Education                Education
2   Employment               Employment               Employment
3   Training                 Training                 Training
4   NEET: Seeking EET        NEET: Seeking EET        NEET: Seeking EET
5   Training                 Training                 Training
6   NEET: Teen parent        NEET: Teen parent        NEET: Teen parent
7   Training                 Training                 Training
8   NEET: Seeking EET        NEET: Seeking EET        NEET: Seeking EET
9   NEET: Not ready          NEET: Not ready          NEET: Not ready
10  Education                Education                Education
11  Training                 Training                 Training
12  Training                 Training                 Training
13  Education                Education                Education
14  Education                Education                Training
15  Training                 Training                 Training
16  Training                 Training                 Training
17  Employment               Employment               Education
18  NEET: Re-engagement      NEET: Re-engagement      NEET: Re-engagement
19  NEET: Not ready          NEET: Not ready          NEET: Seeking EET
20  NEET: Illness            NEET: Illness            NEET: Illness
21  NEET: Seeking EET        NEET: Seeking EET        NEET: Seeking EET
22  NEET: Seeking EET        Training                 Training
23  NEET: Seeking EET        NEET: Seeking EET        NEET: Seeking EET
24  NEET: Not ready          NEET: Not ready          NEET: Not ready
25  Training                 Training                 Training
26  Training                 Training                 Training
27  NEET: Other              NEET: Other              NEET: Other
28  NEET: Seeking EET        NEET: Seeking EET        NEET: Seeking EET
29  NA                       NA                       NA
30  Training                 Training                 Training
⋮   ⋮                        ⋮                        ⋮
162 NEET: Seeking EET        NEET: Other              NEET: Other
163 NEET: Re-engagement      NEET: Re-engagement      NEET: Re-engagement
164 Employment               Employment               Employment
165 NA                       NA                       NA
166 NEET: Illness            NEET: Illness            NEET: Illness
167 Employment               Employment               Employment
168 NEET: Seeking EET        NEET: Seeking EET        NEET: Seeking EET
169 NEET: Illness            NEET: Illness            NEET: Illness
170 NEET: Seeking EET        NEET: Seeking EET        NEET: Seeking EET
171 NEET: Not ready          NEET: Not ready          NEET: Seeking EET
172 NEET: Seeking EET        Employment               Employment
173 Employment               Employment               Employment
174 NEET: Seeking EET        NEET: Seeking EET        NEET: Seeking EET
175 Education                Education                Education
176 NEET: Seeking EET        NEET: Seeking EET        NEET: Seeking EET
177 NEET: Seeking EET        NEET: Re-engagement      NEET: Re-engagement
178 NEET: Working: no reward NEET: Working: no reward NEET: Working: no reward
179 NEET: Seeking EET        NEET: Seeking EET        NEET: Seeking EET
180 Training                 Training                 Training
181 NEET: Seeking EET        NEET: Seeking EET        NEET: Seeking EET
182 NEET: Seeking EET        NEET: Other              NEET: Other
183 Training                 Training                 Training
184 NEET: Seeking EET        NEET: Seeking EET        NEET: Seeking EET
185 NEET: Seeking EET        NEET: Seeking EET        NEET: Seeking EET
186 NEET: Other              NEET: Seeking EET        NEET: Seeking EET
187 Education                Education                Education
188 Training                 Training                 Training
189 NEET: Illness            NEET: Illness            NEET: Illness
190 Training                 Training                 Training
191 NEET: Seeking EET        NEET: Seeking EET        NEET: Seeking EET
    X1                       X2                       X3
1   Education                Education                Education
2   NEET: Seeking EET        NEET: Seeking EET        NEET: Pregnancy
3   Training                 Training                 NEET: Not ready
4   NEET: Seeking EET        NEET: Seeking EET        Education
5   Training                 Training                 Employment
6   NEET: Teen parent        Training                 Training
7   Training                 Training                 Training
8   NEET: Seeking EET        NEET: Seeking EET        NEET: Seeking EET
9   NEET: Illness            NEET: Illness            NEET: Illness
10  Education                Education                Education
11  Training                 Training                 Training
12  Employment               Employment               Employment
13  Education                Education                Education
14  Training                 Training                 Training
15  Training                 Training                 Training
16  Training                 Training                 Training
17  Education                Education                Education
18  NEET: Re-engagement      NEET: Re-engagement      NEET: Re-engagement
19  NEET: Seeking EET        NEET: Not ready          Employment
20  NEET: Illness            NEET: Illness            NEET: Illness
21  NEET: Seeking EET        NEET: Seeking EET        NEET: Pregnancy
22  Training                 Training                 Training
23  NEET: Seeking EET        NEET: Seeking EET        NEET: Seeking EET
24  Education                NEET: Not ready          NEET: Not ready
25  Training                 Training                 Training
26  Employment               Employment               Employment
27  NEET: Other              NEET: Other              NEET: Illness
28  Education                Education                Education
29  NA                       NA                       NA
30  Training                 Training                 Training
⋮   ⋮                        ⋮                        ⋮
162 NEET: Start date agreed  Training                 Training
163 NA                       NA                       NA
164 Employment               Employment               Employment
165 NA                       NA                       NA
166 NEET: Illness            NEET: Illness            NEET: Illness
167 Employment               Employment               Employment
168 NEET: Seeking EET        Training                 Training
169 NEET: Illness            NEET: Illness            NEET: Illness
170 NEET: Working: no reward NEET: Working: no reward NEET: Working: no reward
171 NEET: Seeking EET        NEET: Not ready          Employment
172 Employment               Employment               Employment
173 Employment               Employment               Employment
174 NEET: Seeking EET        Employment               Employment
175 Education                Education                Education
176 NEET: Seeking EET        Employment               Employment
177 NEET: Re-engagement      NEET: Re-engagement      NEET: Re-engagement
178 NEET: Working: no reward NEET: Seeking EET        NEET: Seeking EET
179 NEET: Seeking EET        NEET: Seeking EET        Employment
180 Training                 Employment               Employment
181 NEET: Seeking EET        NEET: Seeking EET        NEET: Seeking EET
182 NEET: Other              NEET: Other              NEET: Start date agreed
183 Training                 Training                 Training
184 NEET: Seeking EET        NEET: Seeking EET        NEET: Seeking EET
185 NEET: Seeking EET        NEET: Seeking EET        NEET: Seeking EET
186 NEET: Seeking EET        NEET: Carer              NEET: Carer
187 Education                Education                Education
188 Training                 Training                 Training
189 NEET: Illness            Education                Education
190 Employment               Employment               Employment
191 NEET: Seeking EET        NEET: Seeking EET        NEET: Seeking EET
    ⋯ X6                       X7
1   ⋯ Education                Education
2   ⋯ NEET: Teen parent        NEET: Teen parent
3   ⋯ NEET: Not ready          NEET: Seeking EET
4   ⋯ Education                Education
5   ⋯ Employment               Employment
6   ⋯ Training                 Training
7   ⋯ Training                 Training
8   ⋯ Refused                  Refused
9   ⋯ NEET: Illness            NEET: Illness
10  ⋯ Education                Education
11  ⋯ Training                 Training
12  ⋯ Employment               Employment
13  ⋯ Education                Education
14  ⋯ NEET: Seeking EET        NEET: Seeking EET
15  ⋯ Training                 Training
16  ⋯ Training                 Training
17  ⋯ NA                       NA
18  ⋯ NEET: Re-engagement      NEET: Re-engagement
19  ⋯ NEET: Seeking EET        NEET: Not ready
20  ⋯ NEET: Illness            NEET: Illness
21  ⋯ NA                       NA
22  ⋯ Training                 Employment
23  ⋯ Employment               Employment
24  ⋯ NEET: Start date agreed  NEET: Re-engagement
25  ⋯ Training                 Training
26  ⋯ Employment               Employment
27  ⋯ NEET: Illness            NEET: Illness
28  ⋯ Education                Education
29  ⋯ NA                       NA
30  ⋯ Training                 Training
⋮   ⋱ ⋮                        ⋮
162 ⋯ Training                 Training
163 ⋯ NEET: Seeking EET        NEET: Start date agreed
164 ⋯ Employment               Employment
165 ⋯ NA                       NA
166 ⋯ NEET: Illness            NEET: Illness
167 ⋯ Employment               Employment
168 ⋯ Training                 Training
169 ⋯ NEET: Illness            NEET: Illness
170 ⋯ NEET: Working: no reward NEET: Working: no reward
171 ⋯ NEET: Seeking EET        NEET: Not ready
172 ⋯ Employment               Employment
173 ⋯ Employment               Employment
174 ⋯ Employment               Employment
175 ⋯ Education                NA
176 ⋯ Employment               Employment
177 ⋯ NEET: Re-engagement      NEET: Re-engagement
178 ⋯ NEET: Start date agreed  NEET: Start date agreed
179 ⋯ Employment               Employment
180 ⋯ Employment               Employment
181 ⋯ NEET: Seeking EET        NEET: Seeking EET
182 ⋯ NEET: Other              NEET: Other
183 ⋯ Training                 Training
184 ⋯ NEET: Seeking EET        NEET: Seeking EET
185 ⋯ Employment               Employment
186 ⋯ NEET: Carer              NEET: Carer
187 ⋯ Education                Education
188 ⋯ NEET: Seeking EET        NEET: Teen parent
189 ⋯ Education                Education
190 ⋯ Employment               Employment
191 ⋯ Refused                  Refused
    X8                       Education Employment Training Refused NEET
1   Education                11        0           0       0        1
2   NEET: Teen parent         0        3           0       0        9
3   NEET: Seeking EET         0        0           5       0        7
4   Education                 6        0           0       0        6
5   Employment                0        6           5       0        1
6   Training                  0        0           7       0        5
7   Training                  0        0          11       0        1
8   Refused                   0        0           0       3        9
9   NEET: Illness             0        0           0       0       12
10  Education                11        0           0       0        1
11  Training                  0        0          11       0        1
12  Employment                0        8           3       0        1
13  Education                11        0           0       0        1
14  NEET: Seeking EET         2        0           6       0        4
15  Training                  0        0          11       0        1
16  Training                  0        0          11       0        1
17  NA                        6        2           0       0        1
18  NEET: Re-engagement       0        0           0       0       12
19  NEET: Start date agreed   0        1           0       0       11
20  NEET: Illness             0        0           0       0       12

In [29]:
destinations_counts_labelled |>
    group_by(Label) |>
    tally()

  Label            n
1 DROP               294
2 Risky trajectory  1361
3 Steady EET       15706

In [30]:
write.csv(destinations_counts_labelled, "data/manual_classification.csv", row.names = FALSE)

## Extract person IDs

In [31]:
person_ids <- destinations_counts_labelled |>
    select(person_id, NCCIS_ACADYR)

In [32]:
head(person_ids)

  person_id                                                        NCCIS_ACADYR
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2017/2018
2 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2017/2018
3 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2018/2019
4 0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2018/2019
5 00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66 2017/2018
6 0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D 2017/2018

In [33]:
write.csv(person_ids, "data/person_ids.csv", row.names = FALSE)