In [2]:
library(tidyverse)
library(dbplyr)

In [93]:
options(tibble.width = Inf)

# SEN Support, EHC plan, DOB, Gender, Ethnicity, cohort, Distance to school, IDACI score, LSOA, EAL, FSM

In [3]:
person <- read.csv("data/person_home_fsm_sen.csv", header = TRUE)

In [4]:
head(person)

  person_id
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
3 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D
4 0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7
5 00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66
6 0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D
  ever_SEN_support first_SEN_support_year SEN_support_need ever_EHC_plan
1  TRUE            2016                   ASD              FALSE
2  TRUE            2007                   MLD              FALSE
3  TRUE            2005                   SLCN, MLD         TRUE
4  TRUE            2014                   MLD              FALSE
5 FALSE              NA                   NA               FALSE
6  TRUE            2017                                    FALSE
  first_EHC_plan_year EHC_plan_need no_SEN birth_date gender CombinedEthnicity
1   NA                NA            FALSE  2001-05-15 M      White British
2   NA                NA            FALSE  2001-01-15 F      White British
3 2012                MLD           FALSE  2001-11-15 M      White British
4   NA                NA            FALSE  2002-05-15 M      Other
5   NA                NA             TRUE  2000-11-15 M      South Asian
6   NA                NA            FALSE  2001-04-15 F      White British
  cohort  DistCurrSch DistNearSch IDACIScore_Home LSOA11_Home EAL ever_fsm
1 2000/01 0.66        0.66        0.410           E01010635   0   0
2 2000/01 3.50        0.62        0.397           E01010749   0   0
3 2001/02 7.01        0.00        0.125           E01002563   0   1
4 2001/02 0.57        0.57        0.405           E01010724   1   0
5 2000/01 1.69        0.44        0.521           E01010610   1   0
6 2000/01 1.12        0.62        0.234           E01010815   0   0

In [186]:
person |> distinct(LSOA11_Home) |> pull(LSOA11_Home)

   [1] "E01010635" "E01010749" "E01002563" "E01010724" "E01010610" "E01010815"
   [7] "E01033693" "E01010663" "E01010575" "E01010704" "E01010648" "E01010598"
  [13] NA          "E01010662" "E01010729" "E01010617" "E01010800" "E01010717"
  [19] "E01010629" "E01010789" "E01001313" "E01027560" "E01010695" "E01010623"
  [25] "E01010718" "E01010638" "E01010826" "E01010921" "E01010737" "E01027583"
  [31] "E01032608" "E01013954" "E01010603" "E01033697" "E01010674" "E01027561"
  [37] "E01010808" "E01027568" "E01010605" "E01010734" "E01010804" "E01027557"
  [43] "E01010760" "E01027575" "E01010709" "E01010817" "E01011354" "E01010604"
  [49] "E01010830" "E01010688" "E01010832" "E01010621" "E01010690" "E01010852"
  [55] "E01027563" "E01011346" "E01010846" "E01010812" "E01015188" "E01010679"
  [61] "E01010735" "E01010807" "E01010668" "E01010701" "E01010607" "E01007567"
  [67] "E01010822" "E01010745" "E01010839" "E01011320" "E01027571" "E01010687"
  [73] "E01010795" "E01010666" "E01033482" "E01010931" "E01010632" "E01010601"
  [79] "E01010627" "E01010738" "E01027559" "E01010673" "E01010845" "E01010765"
  [85] "E01010667" "E01010698" "E01010736" "E01010746" "E01011277" "E01010747"
  [91] "E01010862" "E01010631" "E01010676" "E01026242" "E01010838" "E01010628"
  [97] "E01032212" "E01010761" "E01027580" "E01008138" "E01010231" "E01010831"
 [103] "E01027577" "E01010810" "E01011198" "E01010625" "E01027642" "E01011066"
 [109] "E01010703" "E01003539" "E01027555" "E01010616" "E01010787" "E01010728"
 [115] "E01010793" "E01012762" "E01010633" "E01010837" "E01005167" "E01030805"
 [121] "E01010813" "E01010779" "E01009596" "E01016511" "E01000081" "E01012952"
 [127] "E01027582" "E01010609" "E01025380" "E01010590" "E01010608" "E01010744"
 [133] "E01010606" "E01010767" "E01025147" "E01010748" "E01011244" "E01011432"
 [139] "E01010853" "E01010796" "E01010842" "E01010774" "E01031550" "E01027584"
 [145] "E01010865" "E01010649" "E01017612" "E01010861" "E01010658" "E01010594"
 [151] "E01010740" "E01010720" "E01010791" "E01010857" "E01010589" "E01011613"
 [157] "E01010699" "E01010847" "E01010591" "E01010778" "E01010809" "E01010859"
 [163] "E01010665" "E01010587" "E01025156" "E01010678" "E01010694" "E01011324"
 [169] "E01027586" "E01010705" "E01010626" "E01011236" "E01010801" "E01010754"
 [175] "E01010854" "E01010806" "E01027566" "E01010592" "E01010777" "E01011433"
 [181] "E01010630" "E01010656" "E01013566" "E01024774" "E01010850" "E01010792"
 [187] "E01011264" "E01010706" "E01011725" "E01005142" "E01010618" "E01010872"
 [193] "E01005246" "E01010677" "E01011069" "E01025227" "E01027682" "E01010742"
 [199] "E01005243" "E01010569" "E01027578" "E01027581" "E01010841" "E01011379"
 [205] "E01010597" "E01014493" "E01010693" "E01010836" "E01010811" "E01011057"
 [211] "E01010581" "E01010585" "E01008333" "E01013339" "E01010932" "E01010840"
 [217] "E01010834" "E01010732" "E01010741" "E01025186" "E01003858" "E01010602"
 [223] "E01010726" "E01027681" "E01010827" "E01010727" "E01011684" "E01018466"
 [229] "E01011569" "E01010639" "E01010600" "E01010716" "E01010619" "E01019453"
 [235] "E01010646" "E01010573" "E01000999" "E01012678" "E01010825" "E01010599"
 [241] "E01027636" "E01004345" "E01010586" "E01010781" "E01010719" "E01027798"
 [247] "E01010739" "E01010821" "E01010721" "E01010683" "E01010700" "E01010849"
 [253] "E01027376" "E01015157" "E01010733" "E01010784" "E01026128" "E01025218"
 [259] "E01010624" "E01010622" "E01011060" "E01010759" "E01012986" "E01010863"
 [265] "E01010612" "E01027556" "E01010615" "E01010816" "E01009368" "E01010640"
 [271] "E01003382" "E01010775" "E01025376" "E01010637" "E01011677" "E01011272"
 [277] "E01010571" "E01010655" "E01011061" "E01033695" "E01010743" "E01010790"
 [283] "E01010871" "E01010731" "E01027634" "E01010730" "E01010858" "E01010708"
 [289] "E01007878" "E01033696" "E01010682" "E01027565" "E01011223" "E01010786"
 [295] "E01002133" "E01010680" "E01011279" "E01014247" "E01022191" "E01011326"
 [301] "E01010644" "E01001487" "E01010669" "E01010766" "E01010768" "E01011589"
 [307] "E01010583" "E01010824" "E01010579" "E01010634" "E01010927" "E01010659"
 [313] "E01012889" "E01010702" "E01010843" "E01029358" "E01026407" "E01011059"
 [319] "E01010692" "E01002425" "E01026151" "E01010848" "E01010908" "E01011606"
 [325] "E01010584" "E01010802" "E01010814" "E01010799" "E01010783" "E01010588"
 [331] "E01013132" "E01010756" "E01009048" "E01010636" "E01010664" "E01019342"
 [337] "E01010776" "E01010711" "E01010909" "E01011058" "E01011739" "E01010870"
 [343] "E01027585" "E01010684" "E01010620" "E01013314" "E01005614" "E01009273"
 [349] "E01027830" "E01010580" "E01011762" "E01010713" "E01010670" "E01008420"
 [355] "E01010835" "E01028524" "E01008458" "E01010645" "E01005630" "E01010578"
 [361] "E01015651" "E01032893" "E01011266" "E01011595" "E01013432" "E01010934"
 [367] "E01033468" "E01010672" "E01010828" "E01027803" "E01005554" "E01004831"
 [373] "E01010725" "E01013100" "E01010867" "E01010755" "E01010829" "E01010712"
 [379] "E01005232" "E01010642" "E01011592" "E01020847" "E01022052" "E01010570"
 [385] "E01027567" "E01033328" "E01010906" "E01010614" "E01010653" "E01027576"
 [391] "E01010654" "E01010643" "E01010689" "E01010595" "E01011729" "E01005484"
 [397] "E01000349" "E01001400" "E01010671" "E01010696" "E01027906" "E01010803"
 [403] "E01033691" "E01015751" "E01001009" "E01010697" "E01015627" "E01012942"
 [409] "E01011741" "E01010922" "E01010657" "E01009061" "E01010904" "E01027365"
 [415] "E01011292" "E01011424" "E01010753" "E01010758" "E01011779" "E01013932"
 [421] "E01010818" "E01010868" "E01010576" "E01010833" "E01011134" "E01007944"
 [427] "E01010939" "E01010751" "E01011599" "E01011091" "E01005771" "E01012184"
 [433] "E01015634" "E01012968" "E01010966" "E01007353" "E01027564" "E01011801"
 [439] "E01010762" "E01027572" "E01010819" "E01010675" "E01010864" "E01010710"
 [445] "E01010752" "E01011586" "E01010686" "E01010650" "E01010652" "E01020452"
 [451] "E01011425" "E01027562" "E01010691" "E01001517" "E01011407" "E01010905"
 [457] "E01016558" "E01024660" "E01014580" "E01025096" "E01010582" "E01010881"
 [463] "E01010782" "E01026308" "E01026068" "E01014171" "E01020782" "E01005860"
 [469] "E01003691" "E01001988" "E01010750" "E01003388" "E01009346" "E01010611"
 [475] "E01000087" "E01010574" "E01013362" "E01010805" "E01011328" "E01010794"
 [481] "E01016358" "E01010797" "E01020619" "E01011547" "E01010965" "E01004822"
 [487] "E01010866" "E01010971" "E01018713" "E01011148" "E01012738" "E01010722"
 [493] "E01026188" "E01012944" "E01001078" "E01009623" "E01010900" "E01016356"
 [499] "E01011695" "E01025207" "E01010647" "E01010973" "E01010641" "E01011063"
 [505] "E01033467" "E01016804" "E01010788" "E01029060" "E01011707" "E01027579"
 [511] "E01004830" "E01009375" "E01011173" "E01010723" "E01010763" "E01013409"
 [517] "E01025192" "E01013029" "E01012667" "E01029426" "E01004850" "E01013040"
 [523] "E01019241" "E01011523" "E01010769" "E01010364" "E01007834" "E01010798"
 [529] "E01010974" "E01011056" "E01010715" "E01011597" "E01025181" "E01009658"
 [535] "E01011247" "E01010714" "E01013980" "E01013705" "E01024658" "E01011241"
 [541] "E01028461" "E01014254" "E01006848" "E01010681" "E01007130" "E01010764"
 [547] "E01025141" "E01010991" "E01010856" "E01010503" "E01018139" "E01032495"
 [553] "E01012703" "E01011280" "E01028450" "E01010930" "E01010869" "E01027574"
 [559] "E01017155" "E01001298" "E01026134" "E01007669" "E01010651" "E01010771"
 [565] "E01000008" "E01000296" "E01015654" "E01031313" "E01007524" "E01012859"
 [571] "E01027931" "E01019472" "E01021767" "E01005448" "E01009333" "E01010593"
 [577] "E01010916" "E01011648" "E01019081" "E01020493" "E01011908" "E01025229"
 [583] "E01012948" "E01007715" "E01017078" "E01004880" "E01013350" "E01012617"
 [589] "E01023669" "E01011043" "E01000484" "E01013602" "E01010851" "E01011089"
 [595] "E01005260" "E01011271" "E01013766" "E01008835" "E01001525" "E01011023"
 [601] "E01023681" "E01019580" "E01010454" "E01002404" "E01011344" "E01011434"
 [607] "E01011372" "E01011480" "E01017487" "E01011397" "E01013447" "E01010860"
 [613] "E01005481" "E01011457" "E01003087" "E01011159" "E01008044" "E01011430"
 [619] "E01028433" "E01007642" "E01027666" "E01027708" "E01011601" "E01009486"
 [625] "E01033634" "E01027893" "E01010685" "E01011913" "E01010572" "E01011454"
 [631] "E01011259" "E01013427" "E01014908" "E01024817" "E01010989" "E01001330"
 [637] "E01010613" "E01003411" "E01011608" "E01025321" "E01010874" "E01008084"
 [643] "E01032967" "E01011278" "E01033685" "E01011055" "E01019035" "E01005391"
 [649] "E01011622" "E01027910" "E01007851" "E01033692" "E01011635" "E01027619"
 [655] "E01011464" "E01011361" "E01004983" "E01020861" "E01013004" "E01002275"
 [661] "E01032886" "E01022290" "E01031691" "E01025082" "E01013651" "E01009894"
 [667] "E01007702" "E01012943" "E01010951" "E01011450" "E01011025" "E01013831"
 [673] "E01010596" "E01027569" "E01007768" "E01027735" "E01004581" "E01012734"
 [679] "E01026042" "E01013771" "E01007654" "E01011944" "E01021400" "E01022056"
 [685] "E01000169" "E01011750" "E01007058" "E01008898" "E01015764" "E01011623"
 [691] "E01007529" "E01007942" "E01012674" "E01033496" "E01010855" "E01009195"
 [697] "E01011738" "E01012680" "E01027647" "E01010059" "E01015691" "E01010568"
 [703] "E01032365" "E01006567" "E01033277" "E01027675" "E01013054" "E01011535"
 [709] "E01005351" "E01027697" "E01006737" "E01007857" "E01011034" "E01023900"
 [715] "E01016131" "E01029156" "E01033067" "E01026477" "E01011837" "E01001208"
 [721] "E01011068" "E01012415" "E01011053" "E01005344" "E01005069" "E01010914"
 [727] "E01024994" "E01005321" "E01010019" "E01010577" "E01027715" "E01011014"
 [733] "E01015603" "E01023867" "E01014793" "E01026391" "E01027428" "E01010449"
 [739] "E01011494" "E01011417" "E01011732" "E01011853" "E01013762" "E01015563"
 [745] "E01010432" "E01010936" "E01010873" "E01033644" "E01027008" "E01011507"
 [751] "E01004323" "E01005051" "E01000052" "E01011851" "E01008334" "E01011943"
 [757] "E01007349" "E01004443" "E01010978" "E01011559" "E01027733" "E01017490"
 [763] "E01011588" "E01013296" "E01013728" "E01026005" "E01027674" "E01010990"
 [769] "E01029410" "E01005432" "E01011992" "E01000825" "E01009335" "E01009703"
 [775] "E01011064" "E01025089" "E01007555" "E01010369" "E01013459" "E01005451"
 [781] "E01011888" "E01008335" "E01024690" "E01011287" "E01012886" "E01025420"
 [787] "E01012985" "E01028213" "E01012934" "E01019722" "E01012198" "E01002143"
 [793] "E01010529" "E01019539" "E01006165" "E01027772" "E01027573" "E01032499"
 [799] "E01010785" "E01011177" "E01010820" "E01027874" "E01025178" "E01023973"
 [805] "E01007874" "E01011175" "E01013810" "E01011647" "E01027600" "E01001445"
 [811] "E01011276" "E01011000" "E01025226" "E01011065" "E01013484" "E01005194"
 [817] "E01021322" "E01025102" "E01011428" "E01011003" "E01027653" "E01005948"
 [823] "E01009921" "E01015079" "E01018819" "E01013050" "E01025167" "E01033641"
 [829] "E01011227" "E01010969" "E01013663" "E01009373" "E01027629" "E01011529"
 [835] "E01027896" "E01024466" "E01025294" "E01027027" "E01005280" "E01011062"
 [841] "E01015989" "E01010880" "E01011891" "E01009980" "E01008583" "E01013872"
 [847] "E01029775" "E01033176" "E01029780" "E01007449" "E01019345" "E01025202"
 [853] "E01024515" "E01000724" "E01030261" "E01027695" "E01011427" "E01011583"
 [859] "E01032116" "E01011590" "E01011078" "E01011246" "E01013486" "E01027690"
 [865] "E01011658" "E01011518" "E01009254" "E01009643" "E01011626" "E01007494"
 [871] "E01018463" "E01012467" "E01027818" "E01033180" "E01027693" "E01008735"
 [877] "E01027701" "E01017634" "E01007085" "E01019229" "E01011196" "E01004405"
 [883] "E01011664" "E01007372" "E01010954" "E01011670" "E01007995" "E01011334"
 [889] "E01026397" "E01032489" "E01012927" "E01013326" "E01010920" "E01010707"
 [895] "E01011119" "E01015539" "E01013056" "E01028377" "E01027368" "E01011665"
 [901] "E01011284" "E01003578" "E01008094" "E01010999" "E01013379" "E01007428"
 [907] "E01021827" "E01005322" "E01005461" "E01013485" "E01012027" "E01027782"
 [913] "E01030684" "E01000488" "E01007949" "E01007680" "E01010977" "E01024076"
 [919] "E01007348" "E01020507" "E01011267" "E01011067" "E01010967" "E01010911"
 [925] "E01013048" "E01025115" "E01015048" "E01013853" "E01012568" "E01025196"
 [931] "E01011307" "E01025179" "E01025215" "E01011959" "E01011152" "E01011002"
 [937] "E01025065" "E01028474" "E01008924" "E01030826" "E01016495" "E01011220"
 [943] "E01025468" "E01001200" "E01017270" "E01011028" "E01001222" "E01009530"
 [949] "E01012052" "E01011581" "E01011624" "E01010972" "E01008905" "E01000173"
 [955] "E01030652" "E01019167" "E01017775" "E01017840" "E01013299" "E01025177"
 [961] "E01032502" "E01033645" "E01004043" "E01011046" "E01008369" "E01012748"
 [967] "E01011862" "E01011562" "E01004407" "E01011130" "E01010773" "E01011304"
 [973] "E01006463" "E01011260" "E01013871" "E01010770" "E01027180" "E01012852"
 [979] "E01003697" "E01012318" "E01014249" "E01011520" "E01007700" "E01020909"
 [985] "E01027660" "E01012761" "E01033690" "E01027750" "E01027742" "E01013329"
 [991] "E01010071" "E01025983" "E01001506" "E01007704" "E01012425" "E01031097"
 [997] "E01010943" "E01022221" "E01007301" "E01025295" "E01009138" "E01010894"
[1003] "E01003729" "E01025221" "E01008964" "E01011726" "E01019763" "E01011230"
[1009] "E01007679" "E01000359" "E01012117" "E01010375" "E01011593" "E01012938"
[1015] "E01000324" "E01013119" "E01025984" "E01013587" "E01025201" "E01012992"
[1021] "E01033556" "E01002051" "E01011496" "E01012931" "E01010065" "E01009593"
[1027] "E01007528" "E01011376" "E01011100" "E01027512" "E01011273" "E01000507"
[1033] "E01010933" "E01011706" "E01011912" "E01014251" "E01004877" "E01013568"
[1039] "E01011451" "E01015632" "E01005145" "E01026321" "E01027645" "E01010876"
[1045] "E01020610" "E01025450" "E01011830" "E01007769" "E01021973" "E01033621"
[1051] "E01011270" "E01013921" "E01005300" "E01025338" "E01022312" "E01006171"
[1057] "E01007940" "E01011610" "E01011030" "E01020668" "E01011415" "E01020696"
[1063] "E01007411" "E01013057" "E01027033" "E01011806" "E01020844" "E01011596"
[1069] "E01005086" "E01017117" "E01032799" "E01008111" "E01011578" "E01011015"
[1075] "E01005459" "E01022492" "E01011485" "E01019052" "E01011458" "E01012743"
[1081] "E01007947" "E01021690" "E01018315" "E01021224" "E01011691" "E01033689"
[1087] "E01027702" "E01013844" "E01033515" "E01005974" "E01013491" "E01027771"
[1093] "E01012932" "E01005482" "E01011838" "E01004806" "E01020763" "E01011483"
[1099] "E01028699" "E01013390" "E01008091" "E01001130" "E01004861" "E01020827"
[1105] "E01027662" "E01009639" "E01011190" "E01019312" "E01010912" "E01011571"
[1111] "E01011447" "E01033479" "E01032302" "E01025348" "E01011047" "E01025118"
[1117] "E01005546" "E01015735" "E01027776" "E01011570" "E01025442" "E01025513"
[1123] "E01005429" "E01018895" "E01010294" "E01031044" "E01026592" "E01011598"
[1129] "E01018717" "E01011167" "E01022119" "E01012064" "E01027650" "E01024895"
[1135] "E01013752" "E01030148" "E01009393" "E01008326" "E01022858" "E01027736"
[1141] "E01023136" "E01010940" "E01011472" "E01005065" "E01012423" "E01007738"
[1147] "E01026099" "E01013916" "E01011603" "E01011199" "E01005430" "E01001900"
[1153] "E01027683" "E01013128" "E01005941" "E01026231" "E01010207" "E01003820"
[1159] "E01005314" "E01010058" "E01019340" "E01024010" "E01025631" "E01011653"
[1165] "E01011422" "E01025634" "E01023746" "E01027655" "E01022707" "E01010997"
[1171] "E01009382" "E01027233" "E01005951" "E01011587" "E01026377" "E01011249"
[1177] "E01011201" "E01011572" "E01024282" "E01011867" "E01010332" "E01017748"
[1183] "E01011893" "E01027443" "E01027570" "E01029742" "E01013944" "E01011711"
[1189] "E01030707" "E01027363" "E01013080" "E01011093" "E01014283" "E01001347"
[1195] "E01012361" "E01013201" "E01003334" "E01011265" "E01012011" "E01010270"
[1201] "E01019633" "E01007369" "E01009014" "E01002656" "E01032612" "E01011045"
[1207] "E01027709" "E01011527" "E01012203" "E01011006" "E01010878" "E01027827"
[1213] "E01004089" "E01020228" "E01011294" "E01010988" "E01027661" "E01024497"
[1219] "E01027774" "E01011560" "E01013933" "E01005468" "E01022415" "E01011625"
[1225] "E01033278" "E01013120" "E01012078" "E01011639" "E01033032" "E01013471"
[1231] "E01018110" "E01012088" "E01027807" "E01028831" "E01017102" "E01009350"
[1237] "E01017486" "E01011460" "E01008314" "E01010062" "E01015262" "E01012655"
[1243] "E01016445" "E01016040" "E01025366" "E01011004" "E01025349" "E01010994"
[1249] "E01012209" "E01009699" "E01023121" "E01006976" "E01002403" "E01013449"
[1255] "E01018829" "E01033538" "E01011546" "E01011312" "E01025203" "E01024914"
[1261] "E01013300" "E01007869" "E01025200" "E01013558" "E01012208" "E01027914"
[1267] "E01031131" "E01029351" "E01016490" "E01011301" "E01020609" "E01012955"
[1273] "E01008861" "E01011039" "E01003686" "E01019851" "E01008982" "E01010938"
[1279] "E01008455" "E01032216" "E01020772" "E01010386" "E01025001" "E01011343"
[1285] "E01005349" "E01005553" "E01028893" "E01026522" "E01024768" "E01012946"
[1291] "E01005101" "E01012503" "E01011782" "E01018002" "E01010950" "E01005259"
[1297] "E01011268" "E01021702" "E01007733" "E01023670" "E01013064" "E01032921"
[1303] "E01007532" "E01003739" "E01027823" "E01009790" "E01026770" "E01005566"
[1309] "E01002151" "E01017874" "E01011239" "E01031144" "E01000915" "E01005016"
[1315] "E01016756" "E01011327" "E01025351" "E01011733" "E01006998" "E01017213"
[1321] "E01012724" "E01017691" "E01033035" "E01025791" "E01011243" "E01007632"
[1327] "E01009202" "E01025377" "E01004836" "E01011041" "E01007484" "E01014105"
[1333] "E01000526" "E01009958" "E01016657" "E01010527" "E01025331" "E01011616"
[1339] "E01011449" "E01013836" "E01025199" "E01010466" "E01030384" "E01024214"
[1345] "E01011582" "E01027621" "E01011261" "E01011297" "E01023112" "E01011316"
[1351] "E01009033" "E01019394" "E01013963" "E01011406" "E01017705" "E01027868"
[1357] "E01027744" "E01011621" "E01019387" "E01011013" "E01027739" "E01011001"
[1363] "E01027825" "E01011374" "E01012656" "E01011574" "E01024887" "E01004098"
[1369] "E01032500" "E01011484" "E01011051" "E01007902" "E01026379" "E01028175"
[1375] "E01031056" "E01012038" "E01005337" "E01009706" "E01013438" "E01007634"
[1381] "E01011018" "E01001278" "E01010949" "E01005437" "E01025816" "E01011516"
[1387] "E01018276" "E01027850" "E01010893" "E01019124" "E01029546" "E01010525"
[1393] "E01006860" "E01007664" "E01007187" "E01027745" "E01003767" "E01010877"
[1399] "E01012728" "E01000630" "E01033215" "E01013331" "E01026149" "E01005497"
[1405] "E01012926" "E01011211" "E01011463" "E01011524" "E01011027" "E01006342"
[1411] "E01015762" "E01027316" "E01033005" "E01003756" "E01026069" "E01027608"
[1417] "E01010772" "E01011584" "E01007852" "E01003569" "E01020168" "E01011325"
[1423] "E01003270" "E01013038" "E01019307" "E01013123" "E01011049" "E01019887"
[1429] "E01001422" "E01013308" "E01031303" "E01011238" "E01013073" "E01033581"
[1435] "E01010947" "E01033733" "E01007906" "E01032282" "E01024794" "E01001942"
[1441] "E01010887" "E01025329" "E01009355" "E01004049" "E01033470" "E01001263"
[1447] "E01000431" "E01025184" "E01010048" "E01010891" "E01017566" "E01003675"
[1453] "E01027668" "E01011138" "E01021647" "E01014196" "E01007139" "E01001079"
[1459] "E01033675" "E01015791" "E01027811" "E01010980" "E01011262" "E01006305"
[1465] "E01026115" "E01000260" "E01030856" "E01032587" "E01003368" "E01011019"
[1471] "E01019658" "E01011769" "E01020295" "E01016715" "E01024802" "E01005401"
[1477] "E01002960" "E01026189" "E01007645" "E01011127" "E01010191" "E01021746"
[1483] "E01009487" "E01013433" "E01010907" "E01007564" "E01021376" "E01007982"
[1489] "E01005277" "E01016039" "E01001179" "E01019404" "E01005731" "E01006082"
[1495] "E01027277" "E01011686" "E01013609" "E01011591" "E01033694" "E01011722"
[1501] "E01022838" "E01012494" "E01011758" "E01013632" "E01012951" "E01010925"
[1507] "E01016781" "E01012566" "E01026072" "E01011585" "E01013918" "E01013198"
[1513] "E01018421" "E01007847" "E01005517" "E01027743" "E01010889" "E01005935"

In [39]:
person |>
    nrow()

[1] 17224

In [41]:
n_distinct(person$person_id)

[1] 17224

# Absences: total, authorised, unauthorised

In [5]:
absence_alltime <- read.csv("data/absence_alltime_rates.csv", header = TRUE)

In [6]:
head(absence_alltime)

  person_id
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
3 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D
4 0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7
5 00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66
6 0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D
  AuthorisedAbsenceRate UnauthorisedAbsenceRate TotalAbsenceRate
1  2.687844             0.1221747                2.810018
2 21.849234             1.5312132               23.380448
3  2.957284             7.0646221               10.021906
4  1.683704             0.4209260                2.104630
5  4.911700             0.0000000                4.911700
6  3.658537             1.6688062                5.327343

In [7]:
person_absence <- person |>
    left_join(absence_alltime, by=join_by(person_id))

In [8]:
head(person_absence)

  person_id
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
3 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D
4 0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7
5 00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66
6 0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D
  ever_SEN_support first_SEN_support_year SEN_support_need ever_EHC_plan
1  TRUE            2016                   ASD              FALSE
2  TRUE            2007                   MLD              FALSE
3  TRUE            2005                   SLCN, MLD         TRUE
4  TRUE            2014                   MLD              FALSE
5 FALSE              NA                   NA               FALSE
6  TRUE            2017                                    FALSE
  first_EHC_plan_year EHC_plan_need no_SEN birth_date gender ⋯ cohort
1   NA                NA            FALSE  2001-05-15 M      ⋯ 2000/01
2   NA                NA            FALSE  2001-01-15 F      ⋯ 2000/01
3 2012                MLD           FALSE  2001-11-15 M      ⋯ 2001/02
4   NA                NA            FALSE  2002-05-15 M      ⋯ 2001/02
5   NA                NA             TRUE  2000-11-15 M      ⋯ 2000/01
6   NA                NA            FALSE  2001-04-15 F      ⋯ 2000/01
  DistCurrSch DistNearSch IDACIScore_Home LSOA11_Home EAL ever_fsm
1 0.66        0.66        0.410           E01010635   0   0
2 3.50        0.62        0.397           E01010749   0   0
3 7.01        0.00        0.125           E01002563   0   1
4 0.57        0.57        0.405           E01010724   1   0
5 1.69        0.44        0.521           E01010610   1   0
6 1.12        0.62        0.234           E01010815   0   0
  AuthorisedAbsenceRate UnauthorisedAbsenceRate TotalAbsenceRate
1  2.687844             0.1221747                2.810018
2 21.849234             1.5312132               23.380448
3  2.957284             7.0646221               10.021906
4  1.683704             0.4209260                2.104630
5  4.911700             0.0000000                4.911700
6  3.658537             1.6688062                5.327343

In [129]:
person_absence <- person_absence |>
    mutate(across(c(AuthorisedAbsenceRate, UnauthorisedAbsenceRate, TotalAbsenceRate),
                ~ replace_na(., 0)))

In [130]:
person_absence |>
    nrow()

[1] 17224

In [131]:
n_distinct(person_absence$person_id)

[1] 17224

# Ever CIN

In [132]:
cin <- read.csv("data/ever_cin.csv", header = TRUE)

In [133]:
head(cin)

  person_id                                                        ever_CIN
1 8ACF32604DD3AE67EEECA75E04FCC614520EFC1D5F4A76CEB0FDF043329DE4D2 TRUE
2 BB7570010F037F8C712D67E2E7A35608749B2EAF6C32185AAA671947AAB585B4 TRUE
3 5B893168F74F87750BDFC391A40CEBCC88A694306B9CEFD24D7D74DAC8A50788 TRUE
4 B9FDC8506D505035AFBC556C0DF197EC924E34C886E786F862FE65ADC36D3EBF TRUE
5 4CCB3C96D6416EB85EB282210215078F078A1CE0CD06C4FF750A1AC90B53789A TRUE
6 4AE5E0FEA4D6E075F07919D3677BBC906824D77A526DAC1F26B52D1B071F6298 TRUE

In [134]:
person_absence_cin <- person_absence |>
    left_join(cin, by=join_by(person_id))

In [135]:
person_absence_cin <- person_absence_cin |>
    mutate(ever_CIN = case_when(
            ever_CIN ~ TRUE,
        TRUE ~ FALSE)
           )

In [136]:
head(person_absence_cin)

  person_id
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
3 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D
4 0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7
5 00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66
6 0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D
  ever_SEN_support first_SEN_support_year SEN_support_need ever_EHC_plan
1  TRUE            2016                   ASD              FALSE
2  TRUE            2007                   MLD              FALSE
3  TRUE            2005                   SLCN, MLD         TRUE
4  TRUE            2014                   MLD              FALSE
5 FALSE              NA                   NA               FALSE
6  TRUE            2017                                    FALSE
  first_EHC_plan_year EHC_plan_need no_SEN birth_date gender ⋯ DistCurrSch
1   NA                NA            FALSE  2001-05-15 M      ⋯ 0.66
2   NA                NA            FALSE  2001-01-15 F      ⋯ 3.50
3 2012                MLD           FALSE  2001-11-15 M      ⋯ 7.01
4   NA                NA            FALSE  2002-05-15 M      ⋯ 0.57
5   NA                NA             TRUE  2000-11-15 M      ⋯ 1.69
6   NA                NA            FALSE  2001-04-15 F      ⋯ 1.12
  DistNearSch IDACIScore_Home LSOA11_Home EAL ever_fsm AuthorisedAbsenceRate
1 0.66        0.410           E01010635   0   0         2.687844
2 0.62        0.397           E01010749   0   0        21.849234
3 0.00        0.125           E01002563   0   1         2.957284
4 0.57        0.405           E01010724   1   0         1.683704
5 0.44        0.521           E01010610   1   0         4.911700
6 0.62        0.234           E01010815   0   0         3.658537
  UnauthorisedAbsenceRate TotalAbsenceRate ever_CIN
1 0.1221747                2.810018        FALSE
2 1.5312132               23.380448         TRUE
3 7.0646221               10.021906         TRUE
4 0.4209260                2.104630        FALSE
5 0.0000000                4.911700        FALSE
6 1.6688062                5.327343        FALSE

In [137]:
person_absence_cin |>
    nrow()

[1] 17224

In [138]:
n_distinct(person_absence_cin$person_id)

[1] 17224

# Exclusions

In [139]:
exclusions <- read.csv("data/exclusions.csv", header = TRUE)

In [140]:
head(exclusions)

  person_id                                                        Suspensions
1 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 1
2 0019031CD62586D59268772800516ED50CDF1EF7DE46488542BB031850F6E68A 4
3 002EF3F17C7981C3D6FD842C559E9AA0626E06B3940B670DDA2B71F7070ADF7D 3
4 004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894 8
5 006E9437536191621258B883B68946C2B0D85A0161B4CC2FE397CDE1FC1034FA 1
6 00984270C3D5F57B15FBB33EE849BA97F72C4F732D031E981D2C43395F4E5098 1
  SuspensionSessions Exclusions
1  2                 0
2 21                 0
3 14                 0
4 36                 0
5  2                 0
6 20                 0

In [141]:
person_absence_cin_excl <- person_absence_cin |>
    left_join(exclusions, by=join_by(person_id))

In [142]:
person_absence_cin_excl <- person_absence_cin_excl |>
    replace_na(list(
    Suspensions = 0,
    SuspensionSessions = 0,
    Exclusions = 0
  ))

In [143]:
head(person_absence_cin_excl)

  person_id
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
3 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D
4 0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7
5 00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66
6 0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D
  ever_SEN_support first_SEN_support_year SEN_support_need ever_EHC_plan
1  TRUE            2016                   ASD              FALSE
2  TRUE            2007                   MLD              FALSE
3  TRUE            2005                   SLCN, MLD         TRUE
4  TRUE            2014                   MLD              FALSE
5 FALSE              NA                   NA               FALSE
6  TRUE            2017                                    FALSE
  first_EHC_plan_year EHC_plan_need no_SEN birth_date gender ⋯ LSOA11_Home EAL
1   NA                NA            FALSE  2001-05-15 M      ⋯ E01010635   0
2   NA                NA            FALSE  2001-01-15 F      ⋯ E01010749   0
3 2012                MLD           FALSE  2001-11-15 M      ⋯ E01002563   0
4   NA                NA            FALSE  2002-05-15 M      ⋯ E01010724   1
5   NA                NA             TRUE  2000-11-15 M      ⋯ E01010610   1
6   NA                NA            FALSE  2001-04-15 F      ⋯ E01010815   0
  ever_fsm AuthorisedAbsenceRate UnauthorisedAbsenceRate TotalAbsenceRate
1 0         2.687844             0.1221747                2.810018
2 0        21.849234             1.5312132               23.380448
3 1         2.957284             7.0646221               10.021906
4 0         1.683704             0.4209260                2.104630
5 0         4.911700             0.0000000                4.911700
6 0         3.658537             1.6688062                5.327343
  ever_CIN Suspensions SuspensionSessions Exclusions
1 FALSE    0           0                  0
2  TRUE    1           2                  0
3  TRUE    0           0                  0
4 FALSE    0           0                  0
5 FALSE    0           0                  0
6 FALSE    0           0                  0

In [144]:
person_absence_cin_excl |>
    nrow()

[1] 17224

In [145]:
n_distinct(person_absence_cin_excl$person_id)

[1] 17224

# KS4 attainment

In [146]:
ks4 <- read.csv("data/ks4_filtered.csv", header = TRUE)

In [147]:
head(ks4)

  person_id                                                        KS4_ENTRIES
1 8162139524FD12F229AA20ECC03197D4B0D3D4C5A45956ED65A5DC4F7CC39640 2
2 B1FB0FCF737FA4E17FF717DBAE7055474EFDCC3B28A495DF554205A667D406DE 2
3 6B8EB0F5C99DD20853DA0B987C4910FABDF0D0957CCCB4F85103102EE325822D 2
4 C39E61EAFEAF90E7EC3EC092BAD9FA5A47E94A889790FC29C0B0E7F0C6989574 2
5 8C8B14978AE28DEF988E73CE511765B70921FB9C06EB9CB2D2D6F9AF459B167C 0
6 259BF856FEF2FC42D931FC5AF6A310188A0D1C7501345FB78DD585BE68B46840 1
  KS4_PASS_LEV1_PTQ_EE KS4_PASS_LEV2_PTQ_EE KS4_IDACI
1 0                    0                    0
2 0                    0                    0
3 0                    0                    0
4 0                    0                    0
5 0                    0                    0
6 0                    0                    0

In [148]:
ks4 <- distinct(ks4)

In [149]:
ks4 |>
    nrow()

[1] 16864

In [150]:
n_distinct(ks4$person_id)

[1] 16860

In [151]:
person_absence_cin_excl_ks4 <- person_absence_cin_excl |>
    left_join(ks4, by=join_by(person_id))

In [152]:
head(person_absence_cin_excl_ks4)

  person_id
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
3 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D
4 0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7
5 00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66
6 0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D
  ever_SEN_support first_SEN_support_year SEN_support_need ever_EHC_plan
1  TRUE            2016                   ASD              FALSE
2  TRUE            2007                   MLD              FALSE
3  TRUE            2005                   SLCN, MLD         TRUE
4  TRUE            2014                   MLD              FALSE
5 FALSE              NA                   NA               FALSE
6  TRUE            2017                                    FALSE
  first_EHC_plan_year EHC_plan_need no_SEN birth_date gender ⋯
1   NA                NA            FALSE  2001-05-15 M      ⋯
2   NA                NA            FALSE  2001-01-15 F      ⋯
3 2012                MLD           FALSE  2001-11-15 M      ⋯
4   NA                NA            FALSE  2002-05-15 M      ⋯
5   NA                NA             TRUE  2000-11-15 M      ⋯
6   NA                NA            FALSE  2001-04-15 F      ⋯
  UnauthorisedAbsenceRate TotalAbsenceRate ever_CIN Suspensions
1 0.1221747                2.810018        FALSE    0
2 1.5312132               23.380448         TRUE    1
3 7.0646221               10.021906         TRUE    0
4 0.4209260                2.104630        FALSE    0
5 0.0000000                4.911700        FALSE    0
6 1.6688062                5.327343        FALSE    0
  SuspensionSessions Exclusions KS4_ENTRIES KS4_PASS_LEV1_PTQ_EE
1 0                  0          12          10
2 2                  0           4           0
3 0                  0          11           7
4 0                  0          15           9
5 0                  0          12          10
6 0                  0          11           8
  KS4_PASS_LEV2_PTQ_EE KS4_IDACI
1 5                    0.41
2 0                    0.40
3 0                    0.13
4 3                    0.41
5 8                    0.52
6 3                    0.23

In [153]:
person_absence_cin_excl_ks4 |>
    nrow()

[1] 17228

In [154]:
n_distinct(person_absence_cin_excl_ks4$person_id)

[1] 17224

In [155]:
IDACI <- person_absence_cin_excl_ks4 |>
    select(person_id, IDACIScore_Home, KS4_IDACI)

In [156]:
IDACI <- IDACI |>
    mutate(IDACI = coalesce(IDACIScore_Home, KS4_IDACI)) |>
    select(person_id, IDACI)

In [157]:
person_absence_cin_excl_ks4 <- person_absence_cin_excl_ks4 |>
    left_join(IDACI, by=join_by(person_id)) |>
    select(-c(IDACIScore_Home, KS4_IDACI))

Warning message in left_join(person_absence_cin_excl_ks4, IDACI, by = join_by(person_id)):
“Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 8112 of `x` matches multiple rows in `y`.
ℹ Row 8112 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.”

In [158]:
person_absence_cin_excl_ks4 |>
    filter(person_id == '78F8E1050C2A9403F74A4B27A0A755919AA341639647570082A21617FC68F4A6')

  person_id
1 78F8E1050C2A9403F74A4B27A0A755919AA341639647570082A21617FC68F4A6
2 78F8E1050C2A9403F74A4B27A0A755919AA341639647570082A21617FC68F4A6
3 78F8E1050C2A9403F74A4B27A0A755919AA341639647570082A21617FC68F4A6
4 78F8E1050C2A9403F74A4B27A0A755919AA341639647570082A21617FC68F4A6
  ever_SEN_support first_SEN_support_year SEN_support_need ever_EHC_plan
1 TRUE             2007                   MLD              TRUE
2 TRUE             2007                   MLD              TRUE
3 TRUE             2007                   MLD              TRUE
4 TRUE             2007                   MLD              TRUE
  first_EHC_plan_year EHC_plan_need no_SEN birth_date gender ⋯
1 2012                MLD, SLD      FALSE  2001-05-15 M      ⋯
2 2012                MLD, SLD      FALSE  2001-05-15 M      ⋯
3 2012                MLD, SLD      FALSE  2001-05-15 M      ⋯
4 2012                MLD, SLD      FALSE  2001-05-15 M      ⋯
  UnauthorisedAbsenceRate TotalAbsenceRate ever_CIN Suspensions
1 2.363636                5.212121         FALSE    1
2 2.363636                5.212121         FALSE    1
3 2.363636                5.212121         FALSE    1
4 2.363636                5.212121         FALSE    1
  SuspensionSessions Exclusions KS4_ENTRIES KS4_PASS_LEV1_PTQ_EE
1 2                  0          7           1
2 2                  0          7           1
3 2                  0          7           1
4 2                  0          7           1
  KS4_PASS_LEV2_PTQ_EE IDACI
1 0                    0.158
2 0                    0.158
3 0                    0.158
4 0                    0.158

In [159]:
person_absence_cin_excl_ks4 |>
    filter(person_id == 'A7EB1BFA5E3FA735B0BC352420E4E183D7452B467D37EDE7F5B99F7988B90713')

  person_id
1 A7EB1BFA5E3FA735B0BC352420E4E183D7452B467D37EDE7F5B99F7988B90713
2 A7EB1BFA5E3FA735B0BC352420E4E183D7452B467D37EDE7F5B99F7988B90713
3 A7EB1BFA5E3FA735B0BC352420E4E183D7452B467D37EDE7F5B99F7988B90713
4 A7EB1BFA5E3FA735B0BC352420E4E183D7452B467D37EDE7F5B99F7988B90713
  ever_SEN_support first_SEN_support_year SEN_support_need ever_EHC_plan
1 TRUE             2007                   SLCN             TRUE
2 TRUE             2007                   SLCN             TRUE
3 TRUE             2007                   SLCN             TRUE
4 TRUE             2007                   SLCN             TRUE
  first_EHC_plan_year EHC_plan_need no_SEN birth_date gender ⋯
1 2009                SEMH          FALSE  2001-04-15 M      ⋯
2 2009                SEMH          FALSE  2001-04-15 M      ⋯
3 2009                SEMH          FALSE  2001-04-15 M      ⋯
4 2009                SEMH          FALSE  2001-04-15 M      ⋯
  UnauthorisedAbsenceRate TotalAbsenceRate ever_CIN Suspensions
1 3.363914                10.15291         FALSE    0
2 3.363914                10.15291         FALSE    0
3 3.363914                10.15291         FALSE    0
4 3.363914                10.15291         FALSE    0
  SuspensionSessions Exclusions KS4_ENTRIES KS4_PASS_LEV1_PTQ_EE
1 0                  0          10          4
2 0                  0          10          4
3 0                  0          10          4
4 0                  0          10          4
  KS4_PASS_LEV2_PTQ_EE IDACI
1 0                    0.206
2 0                    0.206
3 0                    0.206
4 0                    0.206

In [160]:
person_absence_cin_excl_ks4 |>
    filter(person_id == '0A69F30C79C7050090460E9093EA1D5639D43AC626C3067E754604156142CA57')

  person_id
1 0A69F30C79C7050090460E9093EA1D5639D43AC626C3067E754604156142CA57
  ever_SEN_support first_SEN_support_year SEN_support_need ever_EHC_plan
1 FALSE            NA                     NA               FALSE
  first_EHC_plan_year EHC_plan_need no_SEN birth_date gender ⋯
1 NA                  NA            TRUE   2002-03-15 F      ⋯
  UnauthorisedAbsenceRate TotalAbsenceRate ever_CIN Suspensions
1 5.580694                25.33937         FALSE    0
  SuspensionSessions Exclusions KS4_ENTRIES KS4_PASS_LEV1_PTQ_EE
1 0                  0          5           0
  KS4_PASS_LEV2_PTQ_EE IDACI
1 0                    0.156

In [161]:
person_absence_cin_excl_ks4 |>
    filter(person_id == '0A95DF5BA191CED6A61035D391F33433FC94CB07AF956305B6DF22DA83F10B3E')

  person_id
1 0A95DF5BA191CED6A61035D391F33433FC94CB07AF956305B6DF22DA83F10B3E
  ever_SEN_support first_SEN_support_year SEN_support_need ever_EHC_plan
1 TRUE             2008                   VI, SEMH         FALSE
  first_EHC_plan_year EHC_plan_need no_SEN birth_date gender ⋯
1 NA                  NA            FALSE  2001-08-15 M      ⋯
  UnauthorisedAbsenceRate TotalAbsenceRate ever_CIN Suspensions
1 0                       6.140879         TRUE     1
  SuspensionSessions Exclusions KS4_ENTRIES KS4_PASS_LEV1_PTQ_EE
1 6                  0          6           0
  KS4_PASS_LEV2_PTQ_EE IDACI
1 0                    0.106

In [162]:
person_absence_cin_excl_ks4 %>%
  count(person_id) %>%
  filter(n > 1)

  person_id                                                        n
1 78F8E1050C2A9403F74A4B27A0A755919AA341639647570082A21617FC68F4A6 4
2 A7EB1BFA5E3FA735B0BC352420E4E183D7452B467D37EDE7F5B99F7988B90713 4
3 F693FB718D5AC41EEE3982AB799D677E3F75DBFE7BE17FFF0FFB95C75CA47D6A 4
4 FFEF2AA9E8BD72D6A0E7CE50F067E4247E12738F53AE726CD94A4D9CB588C702 4

In [163]:
person_absence_cin_excl_ks4 <- distinct(person_absence_cin_excl_ks4)

In [164]:
person_absence_cin_excl_ks4 |>
    nrow()

[1] 17224

In [165]:
n_distinct(person_absence_cin_excl_ks4$person_id)

[1] 17224

# Destinations

In [166]:
destinations <- read.csv("data/manual_classification.csv", header = TRUE)

In [167]:
destinations <- destinations |>
    select(person_id, Label)

In [168]:
person_absence_cin_excl_ks4_dest <- person_absence_cin_excl_ks4 |>
    left_join(destinations, by = 'person_id')

In [169]:
head(person_absence_cin_excl_ks4_dest)

  person_id
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
3 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D
4 0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7
5 00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66
6 0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D
  ever_SEN_support first_SEN_support_year SEN_support_need ever_EHC_plan
1  TRUE            2016                   ASD              FALSE
2  TRUE            2007                   MLD              FALSE
3  TRUE            2005                   SLCN, MLD         TRUE
4  TRUE            2014                   MLD              FALSE
5 FALSE              NA                   NA               FALSE
6  TRUE            2017                                    FALSE
  first_EHC_plan_year EHC_plan_need no_SEN birth_date gender ⋯ TotalAbsenceRate
1   NA                NA            FALSE  2001-05-15 M      ⋯  2.810018
2   NA                NA            FALSE  2001-01-15 F      ⋯ 23.380448
3 2012                MLD           FALSE  2001-11-15 M      ⋯ 10.021906
4   NA                NA            FALSE  2002-05-15 M      ⋯  2.104630
5   NA                NA             TRUE  2000-11-15 M      ⋯  4.911700
6   NA                NA            FALSE  2001-04-15 F      ⋯  5.327343
  ever_CIN Suspensions SuspensionSessions Exclusions KS4_ENTRIES
1 FALSE    0           0                  0          12
2  TRUE    1           2                  0           4
3  TRUE    0           0                  0          11
4 FALSE    0           0                  0          15
5 FALSE    0           0                  0          12
6 FALSE    0           0                  0          11
  KS4_PASS_LEV1_PTQ_EE KS4_PASS_LEV2_PTQ_EE IDACI Label
1 10                   5                    0.410 Steady EET
2  0                   0                    0.397 Steady EET
3  7                   0                    0.125 Risky trajectory
4  9                   3                    0.405 Steady EET
5 10                   8                    0.521 Steady EET
6  8                   3                    0.234 Steady EET

In [170]:
person_absence_cin_excl_ks4_dest |>
    nrow()

[1] 17224

In [171]:
n_distinct(person_absence_cin_excl_ks4_dest$person_id)

[1] 17224

# Clean and re-order cols

In [172]:
glimpse(person_absence_cin_excl_ks4_dest)

Rows: 17,224
Columns: 29
$ person_id               <chr> "0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB6…
$ ever_SEN_support        <lgl> TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRU…
$ first_SEN_support_year  <int> 2016, 2007, 2005, 2014, NA, 2017, 2008, 2015, …
$ SEN_support_need        <chr> "ASD", "MLD", "SLCN, MLD", "MLD", NA, "", "PD"…
$ ever_EHC_plan           <lgl> FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE…
$ first_EHC_plan_year     <int> NA, NA, 2012, NA, NA, NA, NA, NA, NA, NA, NA, …
$ EHC_plan_need           <chr> NA, NA, "MLD", NA, NA, NA, NA, NA, NA, NA, NA,…
$ no_SEN                  <lgl> FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE…
$ birth_date              <chr> "2001-05-15", "2001-01-15", "2001-11-15", "200…
$ gender                  <chr> "M", "F", "M", "M", "M", "F", "M", "F", "M", "…
$ CombinedEthnicity       <chr> "White British", "White British", "White Briti…
$ cohort                  <chr> "2000/01", "2000/01", "2001/02", "2001/02", "2…
$ DistCurrSch             <dbl> 0.66, 3.50, 7.01, 0.57, 1.69, 1.12, 0.15, 0.57…
$ DistNearSch             <dbl> 0.66, 0.62, 0.00, 0.57, 0.44, 0.62, 0.15, 0.57…
$ LSOA11_Home             <chr> "E01010635", "E01010749", "E01002563", "E01010…
$ EAL                     <int> 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, NA, 1, 0, …
$ ever_fsm                <int> 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1…
$ AuthorisedAbsenceRate   <dbl> 2.6878436, 21.8492344, 2.9572837, 1.6837041, 4…
$ UnauthorisedAbsenceRate <dbl> 0.1221747, 1.5312132, 7.0646221, 0.4209260, 0.…
$ TotalAbsenceRate        <dbl> 2.8100183, 23.3804476, 10.0219058, 2.1046302, …
$ ever_CIN                <lgl> FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE,…
$ Suspensions             <int> 0, 1, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0…
$ SuspensionSessions      <int> 0, 2, 0, 0, 0, 0, 0, 21, 0, 0, 0, 0, 0, 0, 0, …
$ Exclusions              <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ KS4_ENTRIES             <int> 12, 4, 11, 15, 12, 11, 9, 9, 11, 13, 10, 9, 13…
$ KS4_PASS_LEV1_PTQ_EE    <dbl> 10, 0, 7, 9, 10, 8, 7, 1, 9, 9, 8, 7, 7, 10, 1…
$ KS4_PASS_LEV2_PTQ_EE    <dbl> 5.0, 0.0, 0.0, 3.0, 8.0, 3.0, 0.0, 0.0, 7.0, 6…
$ IDACI                   <dbl> 0.410, 0.397, 0.125, 0.405, 0.521, 0.234, 0.27…
$ Label                   <chr> "Steady EET", "Steady EET", "Risky trajectory"…

In [173]:
person_absence_cin_excl_ks4_dest_clean <- person_absence_cin_excl_ks4_dest |>
    select(cohort, 
           person_id, birth_date, gender, CombinedEthnicity, 
           EAL, ever_fsm, ever_CIN, 
           DistCurrSch, DistNearSch, LSOA11_Home, IDACI, 
           ever_SEN_support, first_SEN_support_year, SEN_support_need, 
           ever_EHC_plan, first_EHC_plan_year, EHC_plan_need, 
           no_SEN, 
           AuthorisedAbsenceRate, UnauthorisedAbsenceRate, TotalAbsenceRate, 
           Suspensions, SuspensionSessions, Exclusions,
           KS4_ENTRIES, KS4_PASS_LEV1_PTQ_EE, KS4_PASS_LEV2_PTQ_EE, 
           Label) |>
    rename(Ethnicity = CombinedEthnicity, 
           DOB = birth_date, 
           Gender = gender, 
           ever_FSM = ever_fsm, 
           KS4_Entries = KS4_ENTRIES,
           KS4_Passes_Level1 = KS4_PASS_LEV1_PTQ_EE, 
           KS4_Passes_Level2 = KS4_PASS_LEV2_PTQ_EE,
           Destination = Label)

In [174]:
person_absence_cin_excl_ks4_dest_clean

      cohort  person_id
1     2000/01 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2     2000/01 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
3     2001/02 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D
4     2001/02 0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7
5     2000/01 00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66
6     2000/01 0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D
7     2001/02 0018E26A40A6299391164D4918658B0B1248367C762DCE6D2FDF1AE131A9138C
8     2001/02 0019031CD62586D59268772800516ED50CDF1EF7DE46488542BB031850F6E68A
9     2000/01 001B7CEB7B4CC529920A0B9F5B83D1AC0019E5DC44B3FBB3CEF665C331C0C3B6
10    2000/01 001E539C263734CC355646811C93CF85B0C587D2EBA8B0D79290FDE8A75D6267
11    2001/02 001E5C1FFA964716BF5E84562BC0B5D64F7742B1E8126718A5C0157D485F215D
12    2001/02 001F566795F57F5D8DD92430D868A38B757699844E3E09569B33253527012932
13    2001/02 001FFD3AA96B7E4FC5BB9A2F7502CD45BFCC35882335F1C34F78DD9AE5667225
14    2000/01 00222373A6082CDBF94DA04F23E7EB4C8775BEE122FE9C29FBF521900A498EDF
15    2001/02 002AB68E0EC9459837DD6159160BF8C592504B5F0EE3160A22051398D20C3FFC
16    2000/01 002E041C5100C46E33B8A0C0220BDE85A79111C5D0E26742F6278C059930FAF6
17    2001/02 002EF3F17C7981C3D6FD842C559E9AA0626E06B3940B670DDA2B71F7070ADF7D
18    2000/01 003132A725233755576CF96E5AA2B3DF606A618754D4BDDFCDD5483849E7B946
19    2001/02 00341B29C42EC823E9D06B625E751614D66794F1096E2F045DDE51DB64C9C623
20    2000/01 0037AB0369C14AD5CA0340E2DFDAE2FFF22062A44A7889743C152A8163C08500
21    2000/01 003D2F5BDBC025915EE2AA9CCB96F54F72F003BF7DC6939849ADD6CCD1048ABC
22    2001/02 0048AA244E75570B74E82BDC60D09008D5E728E78E60FB96AA0E762DBD0E818E
23    2001/02 004AC6875C0259256CBCBC00373E9D09131E7D064B6089B9EB26F821F8297775
24    2001/02 004C012DC8B27D82CC173C9590867A88C8B60E6F4C1EAE8AF73D53403DDD94B5
25    2000/01 004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
26    2000/01 005087BCA7BEC31B79A3CA446453131C51CD1DC3296FE71B509E46AA984FFAE3
27    2001/02 0052FF7683A04EBA481AFA53811E1707DBAB62007649EA0C4CE89C8498C06C97
28    2000/01 0054192801954D860BB235F844AD1CB8A99956B2CF3D4E20F83C650DD6279B58
29    2000/01 0059AC822384B93661D2AB87E93EA6AB0847122FA139A080070E86A2F6A1910E
30    2001/02 005A3BB3D150E6AFDC0C4DDCEE6DB850E746A6E2F7760B727CF97B659BC2F483
⋮     ⋮       ⋮
17195 2001/02 FF77AAB58760E4616819BF69FA7A7D0466EC940FC1B666F5D8FC15261B05FDA7
17196 2000/01 FF785EF44C283B9E43E7F206B8848D7C550C36E7E8E5DA0A2B6267CABC0AE447
17197 2000/01 FF7AC7331F6B988DCFBCFA5C55F7984D5BA33735D4DDB4671F30E37176A7B40D
17198 2000/01 FF7B98BFE21CD2600469C9D7B3C040C06C1AAAB58F51EE3BE5A0E0CA94470300
17199 2000/01 FF7B9B8977DE09E00DDE57866479BEED54F7BC5730E38C61A15A220CAF2C507B
17200 2000/01 FF85D28F3D4272EF3EDA67E52BC94BB3A529BD2CD31D32EF21FB8157396EF57D
17201 2001/02 FF85FB47EF271836ECDF7555602263FC0E52F8A84F39868EE7B66E30E47DF618
17202 2000/01 FF8C66C8699FEF1708ABC2DADF11D78283107FADB514F81D4219017A8D26E2DE
17203 2001/02 FF9024B3D2775BB5CC65F8872CB1A8BECAD9A7E25FBB3C3DF7D46A8A1BE31AC1
17204 2000/01 FF94BC38B3E8FE01672532C523A4C00ABB2F9C7B3CDFF6C78F2DA080B544B09A
17205 2001/02 FF94D3F7FDB40C124787D0EBA0CD7660187135442D800F18C11487D380F55663
17206 2000/01 FF9B2F9502DAFBC1EFB04109BEFF47C64A04801619DE844A3DAD073DD45D99D1
17207 2001/02 FFAA13CCE7B35BA3D3A737EF1A13BCE2289A94F9778EC0C9F18CD77F1B93C979
17208 2000/01 FFACDC831FAAA09353CAB36C5828F34E508AC8BFED1B4B07999BAF198CAC4EEA
17209 2001/02 FFBCE0C32A37E3663F1C5159ECFC6F08CD5722E938464A58634F3263003F1D9F
17210 2001/02 FFC0379FDA559C1337454C579FF36F9AE82E62D16B3223D009C57DEC3731754C
17211 2001/02 FFC7129859DD885141E316248A0EB23059DB0F0DB98242C34C67F06FBBAB8041
17212 2001/02 FFC96F346EC6829E7A31F60109FD729DE208D180104B50FC8B1BFAD552D6C8FC
17213 2000/01 FFD30596592DA2C82B86241FBA35E56C7384E7EF8219DB076458B4F9ACDED786
17214 2001/02 FFD391941F3AA9CB910FFFACF24CC2CEAD0BC63EED146E9C21B2C71BA77B084A
17215 2000/01 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951
17216 2000/01 FFE1AA7D705C959745A85B91C6D3F3D22A57B8E50092E9EC25046F6986F77D96
17217 2000/01 FFE837A538A9166CC4089E844F651277391B496479F4691CE27BF1000C49223B
17218 2001/02 FFEA068077E4464D059236951F07D7DF96542C2197AAFAC3E20C036BACB9825C
17219 2000/01 FFEF2AA9E8BD72D6A0E7CE50F067E4247E12738F53AE726CD94A4D9CB588C702
17220 2000/01 FFEFD5577D0112E9304118DB7851CF61BEE4DD3D3184EEA756C076317925508F
17221 2001/02 FFFA6705A275195BFE8A443AF0BD2AA86B1AA0481D330D8665813206EB8DAD43
17222 2001/02 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77
17223 2001/02 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
17224 2000/01 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
      DOB        Gender Ethnicity     EAL ever_FSM ever_CIN DistCurrSch
1     2001-05-15 M      White British  0   0       FALSE    0.66
2     2001-01-15 F      White British  0   0        TRUE    3.50
3     2001-11-15 M      White British  0   1        TRUE    7.01
4     2002-05-15 M      Other          1   0       FALSE    0.57
5     2000-11-15 M      South Asian    1   0       FALSE    1.69
6     2001-04-15 F      White British  0   0       FALSE    1.12
7     2002-07-15 M      South Asian    1   1       FALSE    0.15
8     2001-12-15 F      Other          1   1        TRUE    0.57
9     2001-05-15 M      White British  0   0       FALSE    1.56
10    2000-10-15 M      White British  0   0       FALSE    1.79
11    2002-04-15 M      White British  0   0       FALSE    3.60
12    2002-06-15 M      White British  0   0       FALSE    0.29
13    2002-06-15 F      South Asian   NA   0       FALSE      NA
14    2000-11-15 F      South Asian    1   0       FALSE    2.52
15    2002-08-15 F      South Asian    0   0       FALSE    7.57
16    2000-12-15 M      South Asian    0   1       FALSE    1.60
17    2002-05-15 F      White British  0   1        TRUE    0.76
18    2001-07-15 M      White British  0   1       FALSE    0.33
19    2002-03-15 F      White British  0   1        TRUE    0.91
20    2000-09-15 M      White British  0   0       FALSE    1.04
21    2001-05-15 M      Other          1  NA       FALSE    1.81
22    2001-12-15 F      White British  0   1       FALSE    2.14
23    2002-01-15 M      White British  0   0       FALSE    0.50
24    2002-04-15 F      South Asian    1   1       FALSE    1.60
25    2001-01-15 F      White British  0   1        TRUE    1.81
26    2001-04-15 F      White British NA   0       FALSE      NA
27    2002-07-15 F      White British  0   0        TRUE    2.14
28    2000-11-15 F      South Asian    1   1        TRUE    1.08
29    2001-04-15 F      White British  0   0       FALSE    0.72
30    2002-04-15 M      South Asian    1   1       FALSE    0.84
⋮     ⋮          ⋮      ⋮             ⋮   ⋮        ⋮        ⋮
17195 2002-04-15 F      White British 0   1         TRUE    0.62
17196 2001-07-15 M      South Asian   1   0         TRUE    1.81
17197 2001-07-15 M      White British 0   0        FALSE    0.18
17198 2001-08-15 M      White British 0   0         TRUE    2.73
17199 2001-06-15 M      White British 0   0        FALSE    2.04
17200 2001-03-15 M      South Asian   1   0        FALSE    0.98
17201 2002-06-15 M      White British 0   1        FALSE    2.82
17202 2001-01-15 F      White British 0   1        FALSE    0.30
17203 2002-08-15 M      White British 0   0         TRUE    6.71
17204 2001-05-15 F      White British 0   0        FALSE    1.93
17205 2002-05-15 F      Other         0   0        FALSE    0.73
17206 2001-02-15 F      White British 0   0         TRUE    0.64
17207 2001-10-15 F      Other         1   0        FALSE    1.04
17208 2001-03-15 M      Other         1   1        FALSE    1.80
17209 2001-10-15 F      South Asian   1   1        FALSE    3.29
17210 2001-09-15 M      South Asian   1   0        FALSE    1.01
17211 2002-07-15 F      South Asian   1   0        FALSE    0.91
17212 2002-05-15 M      South Asian   1   1        FALSE    1.08
17213 2001-03-15 F      Other         1   1         TRUE    0.86
17214 2002-08-15 M      White British 0   1         TRUE    0.11
17215 2000-09-15 M      White British 0   0         TRUE    0.39
17216 2001-02-15 F      White British 0   1         TRUE    2.17
17217 2001-02-15 M      White British 0   0        FALSE    7.97
17218 2001-10-15 M      White British 0   0        FALSE    0.69
17219 2001-08-15 M      South Asian   0   0         TRUE    1.21
17220 2001-01-15 F      White British 0   1         TRUE    0.33
17221 2002-07-15 F      White British 0   0        FALSE    0.98
17222 2002-05-15 M      White British 0   0        FALSE    1.23
17223 2002-01-15 F      White British 0   1        FALSE    0.19
17224 2001-07-15 M      White British 0   0        FALSE    3.00
      DistNearSch ⋯ AuthorisedAbsenceRate UnauthorisedAbsenceRate
1     0.66        ⋯  2.6878436             0.1221747
2     0.62        ⋯ 21.8492344             1.5312132
3     0.00        ⋯  2.9572837             7.0646221
4     0.57        ⋯  1.6837041             0.4209260
5     0.44        ⋯  4.9116998             0.0000000
6     0.62        ⋯  3.6585366             1.6688062
7     0.15        ⋯  6.4825254             1.0710259
8     0.57        ⋯  3.2185206            10.4460757
9     1.56        ⋯  4.8298573             0.9879254
10    1.56        ⋯  4.4150110             0.0000000
11    3.60        ⋯  1.0573178             0.1112966
12    0.29        ⋯  1.8909900             0.2780868
13      NA        ⋯  0.0000000             0.0000000
14    0.61        ⋯  4.7413793             0.3694581
15    0.32        ⋯  8.3149780             0.8810573
16    0.21        ⋯  1.6620499             0.3324100
17    0.51        ⋯  5.3243574             4.4063647
18    0.33        ⋯  1.5559545             0.1196888
19    0.26        ⋯  1.5882712             0.2443494
20    1.04        ⋯  0.9922822             0.2205072
21    0.98        ⋯  4.5016077             0.0000000
22    2.14        ⋯  6.5456546             0.0000000
23    0.50        ⋯  0.6674082             0.1112347
24    0.29        ⋯  2.1951220             0.7317073
25    0.30        ⋯  5.4871221             6.3269877
26      NA        ⋯  0.0000000             0.0000000
27    2.14        ⋯  4.7304730             0.8800880
28    0.78        ⋯  1.2215436             0.4997224
29    0.72        ⋯  3.4729879             0.4410143
30    0.20        ⋯  1.7174515             0.6094183
⋮     ⋮           ⋱ ⋮                     ⋮
17195 0.62        ⋯  2.4103832            16.44004944
17196 0.98        ⋯  7.6574022             1.13442995
17197 0.18        ⋯  2.6024363             0.00000000
17198 1.78        ⋯  6.6125290             0.05800464
17199 1.99        ⋯  3.0131827             0.00000000
17200 0.60        ⋯  3.2148900             0.56401579
17201 1.09        ⋯  1.4545455             1.81818182
17202 0.30        ⋯  4.9668874             2.04194260
17203 0.66        ⋯  1.8285714             0.05714286
17204 0.97        ⋯  2.7746948             0.11098779
17205 0.73        ⋯  3.2832499             0.33388982
17206 0.64        ⋯  5.1648352             0.00000000
17207 0.46        ⋯  1.9379845             1.82724252
17208 0.81        ⋯  3.7652270             0.00000000
17209 0.36        ⋯  0.3389831             0.11299435
17210 0.68        ⋯  1.5945330             0.96810934
17211 0.80        ⋯  2.7118644             0.00000000
17212 0.39        ⋯  5.8365759             1.33407449
17213 0.41        ⋯  3.2276331             1.07587769
17214 0.11        ⋯  0.7230256             0.16685206
17215 0.39        ⋯ 32.7909887             1.37672090
17216 0.40        ⋯  8.1818182             5.17045455
17217 2.25        ⋯  6.4784053             0.71982281
17218 0.69        ⋯  2.2148394             0.00000000
17219 0.52        ⋯  0.8562691             0.85626911
17220 0.33        ⋯  7.1469087             3.34656835
17221 0.98        ⋯  0.6466784             0.58788948
17222 1.23        ⋯  0.0000000             0.00000000
17223 0.19        ⋯  4.4430919             0.18259282
17224 0.24        ⋯  7.8305520             1.47625160
      TotalAbsenceRate Suspensions SuspensionSessions Exclusions KS4_Entries
1      2.8100183       0            0                 0          12
2     23.3804476       1            2                 0           4
3     10.0219058       0            0                 0          11
4      2.1046302       0            0                 0          15
5      4.9116998       0            0                 0          12
6      5.3273427       0            0                 0          11
7      7.5535513       0            0                 0           9
8     13.6645963       4           21                 0           9
9      5.8177827       0            0                 0          11
10     4.4150110       0            0                 0          13
11     1.1686144       0            0                 0          10
12     2.1690768       0            0                 0           9
13     0.0000000       0            0                 0          13
14     5.1108374       0            0                 0          13
15     9.1960352       0            0                 0          19
16     1.9944598       0            0                 0          14
17     9.7307222       3           14                 0          10
18     1.6756433       0            0                 0          13
19     1.8326206       0            0                 0           8
20     1.2127894       0            0                 0          11
21     4.5016077       0            0                 0           8
22     6.5456546       0            0                 0          13
23     0.7786429       0            0                 0          13
24     2.9268293       0            0                 0          19
25    11.8141097       8           36                 0          11
26     0.0000000       0            0                 0          10
27     5.6105611       0            0                 0          13
28     1.7212660       0            0                 0          15
29     3.9140022       0            0                 0          11
30     2.3268698       0            0                 0          10
⋮     ⋮                ⋮           ⋮                  ⋮          ⋮
17195 18.8504326       3            4                 0           5
17196  8.7918321       0            0                 0          14
17197  2.6024363       0            0                 0          12
17198  6.6705336       0            0                 0           2
17199  3.0131827       0            0                 0          10
17200  3.7789058       0            0                 0          12
17201  3.2727273       1            1                 0          11
17202  7.0088300       0            0                 0          12
17203  1.8857143       0            0                 0          15
17204  2.8856826       0            0                 0          12
17205  3.6171397       0            0                 0          10
17206  5.1648352       0            0                 0          12
17207  3.7652270       0            0                 0          11
17208  3.7652270       0            0                 0          16
17209  0.4519774       0            0                 0          13
17210  2.5626424       0            0                 0          12
17211  2.7118644       0            0                 0          13
17212  7.1706504       1           10                 0          10
17213  4.3035108       0            0                 0          11
17214  0.8898776       0            0                 0           9
17215 34.1677096       1            2                 0           8
17216 13.3522727       6           12                 0           2
17217  7.1982281       0            0                 0          12
17218  2.2148394       0            0                 0          12
17219  1.7125382       0            0                 0          10
17220 10.4934770       0            0                 0          14
17221  1.2345679       0            0                 0          14
17222  0.0000000       0            0                 0          15
17223  4.6256847       0            0                 0          13
17224  9.3068036       0            0                 0          12
      KS4_Passes_Level1 KS4_Passes_Level2 Destination
1     10                 5.0              Steady EET
2      0                 0.0              Steady EET
3      7                 0.0              Risky trajectory
4      9                 3.0              Steady EET
5     10                 8.0              Steady EET
6      8                 3.0              Steady EET
7      7                 0.0              Steady EET
8      1                 0.0              Steady EET
9      9                 7.0              Steady EET
10     9                 6.0              Steady EET
11     8                 8.0              Steady EET
12     7                 4.0              Steady EET
13     7                 7.0              Steady EET
14    10                 0.0              Steady EET
15    12                12.0              Steady EET
16    11                10.0              Steady EET
17     6                 0.0              DROP
18    11                11.0              Steady EET
19     8                 1.5              Steady EET
20     9                 5.0              Steady EET
21     4                 0.0              Steady EET
22    11                11.0              Steady EET
23     8                 8.0              Steady EET
24     8                 0.0              Risky trajectory
25     6                 0.0              DROP
26     4                 4.0              Steady EET
27     8                 8.0              Steady EET
28    10                10.0              Steady EET
29     9                 9.0              Steady EET
30     8                 5.0              Steady EET
⋮     ⋮                 ⋮                 ⋮
17195  0                 0                Steady EET
17196 12                 9                Steady EET
17197  9                 9                Steady EET
17198  0                 0                Steady EET
17199  9                 9                Steady EET
17200  9                 9                Steady EET
17201  7                 2                Steady EET
17202 10                 8                Steady EET
17203  0                 0                Steady EET
17204  9                 5                Steady EET
17205  8                 8                Steady EET
17206  8                 4                Steady EET
17207  9                 9                Steady EET
17208 11                10                Steady EET
17209 11                11                Steady EET
17210  7                 7                Steady EET
17211 11                11                Steady EET
17212  8                 6                Steady EET
17213  4                 1                Risky trajectory
17214  7                 1                Steady EET
17215  2                 1                Steady EET
17216  0                 0                Risky trajectory
17217 10                 3                Steady EET
17218  8                 8                Steady EET
17219  8                 1                Steady EET
17220 12                 6                Steady EET
17221  9                 7                Steady EET
17222  9                 9                Steady EET
17223  9                 9                Steady EET
17224  9                 3                Steady EET

# Enrolments

In [175]:
enrolments <- read.csv("data/enrolment_wide.csv", header = TRUE)

In [176]:
head(enrolments)

  person_id                                                        NCCIS_ACADYR
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2017/2018
2 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 2017/2018
3 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 2018/2019
4 0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 2018/2019
5 00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66 2017/2018
6 0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D 2017/2018
  Y2012.2013_Term1 Y2012.2013_Term2 Y2012.2013_Term3 Y2013.2014_Term1
1 107442           107442           107442           107442
2 107429           107429           107429           107429
3     NA               NA               NA           136529
4     NA               NA               NA           107441
5 108087           108087           108087           108087
6 107366           107366           107366           107366
  Y2013.2014_Term2 Y2013.2014_Term3 Y2014.2015_Term1 Y2014.2015_Term2
1 107442           107442           107442           107442
2 107429           107429           140569           140569
3 136529           136529           136529           136529
4 107441           107441           107441           107441
5 108087           108087           108087           108087
6 107366           107366           107366           107366
  Y2014.2015_Term3 Y2015.2016_Term1 Y2015.2016_Term2 Y2015.2016_Term3
1 107442           107442           107442           107442
2 140569           140569           140569           140569
3 136529           136529           136529           136529
4 107441           107441           107441           107441
5 108087           108087           108087           108087
6 107366           107366           107366           107366
  Y2016.2017_Term1 Y2016.2017_Term2 Y2016.2017_Term3 Y2017.2018_Term1
1 143114           143114           143114               NA
2 140569           140569           140569               NA
3 136529           136529           136529           136529
4 143112           143112           143112           143112
5 108087           108087           108087               NA
6 142761           142761           142761               NA
  Y2017.2018_Term2 Y2017.2018_Term3
1     NA               NA
2     NA               NA
3 136529           136529
4 143112           143112
5     NA               NA
6     NA               NA

In [177]:
enrolments <- enrolments |>
    select(-NCCIS_ACADYR) |>
    mutate(across(everything(), as.character))

In [178]:
person_absence_cin_excl_ks4_dest_enrol <- person_absence_cin_excl_ks4_dest_clean |>
    left_join(enrolments, by = 'person_id')

In [179]:
person_absence_cin_excl_ks4_dest_enrol

      cohort  person_id
1     2000/01 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2     2000/01 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
3     2001/02 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D
4     2001/02 0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7
5     2000/01 00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66
6     2000/01 0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D
7     2001/02 0018E26A40A6299391164D4918658B0B1248367C762DCE6D2FDF1AE131A9138C
8     2001/02 0019031CD62586D59268772800516ED50CDF1EF7DE46488542BB031850F6E68A
9     2000/01 001B7CEB7B4CC529920A0B9F5B83D1AC0019E5DC44B3FBB3CEF665C331C0C3B6
10    2000/01 001E539C263734CC355646811C93CF85B0C587D2EBA8B0D79290FDE8A75D6267
11    2001/02 001E5C1FFA964716BF5E84562BC0B5D64F7742B1E8126718A5C0157D485F215D
12    2001/02 001F566795F57F5D8DD92430D868A38B757699844E3E09569B33253527012932
13    2001/02 001FFD3AA96B7E4FC5BB9A2F7502CD45BFCC35882335F1C34F78DD9AE5667225
14    2000/01 00222373A6082CDBF94DA04F23E7EB4C8775BEE122FE9C29FBF521900A498EDF
15    2001/02 002AB68E0EC9459837DD6159160BF8C592504B5F0EE3160A22051398D20C3FFC
16    2000/01 002E041C5100C46E33B8A0C0220BDE85A79111C5D0E26742F6278C059930FAF6
17    2001/02 002EF3F17C7981C3D6FD842C559E9AA0626E06B3940B670DDA2B71F7070ADF7D
18    2000/01 003132A725233755576CF96E5AA2B3DF606A618754D4BDDFCDD5483849E7B946
19    2001/02 00341B29C42EC823E9D06B625E751614D66794F1096E2F045DDE51DB64C9C623
20    2000/01 0037AB0369C14AD5CA0340E2DFDAE2FFF22062A44A7889743C152A8163C08500
21    2000/01 003D2F5BDBC025915EE2AA9CCB96F54F72F003BF7DC6939849ADD6CCD1048ABC
22    2001/02 0048AA244E75570B74E82BDC60D09008D5E728E78E60FB96AA0E762DBD0E818E
23    2001/02 004AC6875C0259256CBCBC00373E9D09131E7D064B6089B9EB26F821F8297775
24    2001/02 004C012DC8B27D82CC173C9590867A88C8B60E6F4C1EAE8AF73D53403DDD94B5
25    2000/01 004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
26    2000/01 005087BCA7BEC31B79A3CA446453131C51CD1DC3296FE71B509E46AA984FFAE3
27    2001/02 0052FF7683A04EBA481AFA53811E1707DBAB62007649EA0C4CE89C8498C06C97
28    2000/01 0054192801954D860BB235F844AD1CB8A99956B2CF3D4E20F83C650DD6279B58
29    2000/01 0059AC822384B93661D2AB87E93EA6AB0847122FA139A080070E86A2F6A1910E
30    2001/02 005A3BB3D150E6AFDC0C4DDCEE6DB850E746A6E2F7760B727CF97B659BC2F483
⋮     ⋮       ⋮
17195 2001/02 FF77AAB58760E4616819BF69FA7A7D0466EC940FC1B666F5D8FC15261B05FDA7
17196 2000/01 FF785EF44C283B9E43E7F206B8848D7C550C36E7E8E5DA0A2B6267CABC0AE447
17197 2000/01 FF7AC7331F6B988DCFBCFA5C55F7984D5BA33735D4DDB4671F30E37176A7B40D
17198 2000/01 FF7B98BFE21CD2600469C9D7B3C040C06C1AAAB58F51EE3BE5A0E0CA94470300
17199 2000/01 FF7B9B8977DE09E00DDE57866479BEED54F7BC5730E38C61A15A220CAF2C507B
17200 2000/01 FF85D28F3D4272EF3EDA67E52BC94BB3A529BD2CD31D32EF21FB8157396EF57D
17201 2001/02 FF85FB47EF271836ECDF7555602263FC0E52F8A84F39868EE7B66E30E47DF618
17202 2000/01 FF8C66C8699FEF1708ABC2DADF11D78283107FADB514F81D4219017A8D26E2DE
17203 2001/02 FF9024B3D2775BB5CC65F8872CB1A8BECAD9A7E25FBB3C3DF7D46A8A1BE31AC1
17204 2000/01 FF94BC38B3E8FE01672532C523A4C00ABB2F9C7B3CDFF6C78F2DA080B544B09A
17205 2001/02 FF94D3F7FDB40C124787D0EBA0CD7660187135442D800F18C11487D380F55663
17206 2000/01 FF9B2F9502DAFBC1EFB04109BEFF47C64A04801619DE844A3DAD073DD45D99D1
17207 2001/02 FFAA13CCE7B35BA3D3A737EF1A13BCE2289A94F9778EC0C9F18CD77F1B93C979
17208 2000/01 FFACDC831FAAA09353CAB36C5828F34E508AC8BFED1B4B07999BAF198CAC4EEA
17209 2001/02 FFBCE0C32A37E3663F1C5159ECFC6F08CD5722E938464A58634F3263003F1D9F
17210 2001/02 FFC0379FDA559C1337454C579FF36F9AE82E62D16B3223D009C57DEC3731754C
17211 2001/02 FFC7129859DD885141E316248A0EB23059DB0F0DB98242C34C67F06FBBAB8041
17212 2001/02 FFC96F346EC6829E7A31F60109FD729DE208D180104B50FC8B1BFAD552D6C8FC
17213 2000/01 FFD30596592DA2C82B86241FBA35E56C7384E7EF8219DB076458B4F9ACDED786
17214 2001/02 FFD391941F3AA9CB910FFFACF24CC2CEAD0BC63EED146E9C21B2C71BA77B084A
17215 2000/01 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951
17216 2000/01 FFE1AA7D705C959745A85B91C6D3F3D22A57B8E50092E9EC25046F6986F77D96
17217 2000/01 FFE837A538A9166CC4089E844F651277391B496479F4691CE27BF1000C49223B
17218 2001/02 FFEA068077E4464D059236951F07D7DF96542C2197AAFAC3E20C036BACB9825C
17219 2000/01 FFEF2AA9E8BD72D6A0E7CE50F067E4247E12738F53AE726CD94A4D9CB588C702
17220 2000/01 FFEFD5577D0112E9304118DB7851CF61BEE4DD3D3184EEA756C076317925508F
17221 2001/02 FFFA6705A275195BFE8A443AF0BD2AA86B1AA0481D330D8665813206EB8DAD43
17222 2001/02 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77
17223 2001/02 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
17224 2000/01 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
      DOB        Gender Ethnicity     EAL ever_FSM ever_CIN DistCurrSch
1     2001-05-15 M      White British  0   0       FALSE    0.66
2     2001-01-15 F      White British  0   0        TRUE    3.50
3     2001-11-15 M      White British  0   1        TRUE    7.01
4     2002-05-15 M      Other          1   0       FALSE    0.57
5     2000-11-15 M      South Asian    1   0       FALSE    1.69
6     2001-04-15 F      White British  0   0       FALSE    1.12
7     2002-07-15 M      South Asian    1   1       FALSE    0.15
8     2001-12-15 F      Other          1   1        TRUE    0.57
9     2001-05-15 M      White British  0   0       FALSE    1.56
10    2000-10-15 M      White British  0   0       FALSE    1.79
11    2002-04-15 M      White British  0   0       FALSE    3.60
12    2002-06-15 M      White British  0   0       FALSE    0.29
13    2002-06-15 F      South Asian   NA   0       FALSE      NA
14    2000-11-15 F      South Asian    1   0       FALSE    2.52
15    2002-08-15 F      South Asian    0   0       FALSE    7.57
16    2000-12-15 M      South Asian    0   1       FALSE    1.60
17    2002-05-15 F      White British  0   1        TRUE    0.76
18    2001-07-15 M      White British  0   1       FALSE    0.33
19    2002-03-15 F      White British  0   1        TRUE    0.91
20    2000-09-15 M      White British  0   0       FALSE    1.04
21    2001-05-15 M      Other          1  NA       FALSE    1.81
22    2001-12-15 F      White British  0   1       FALSE    2.14
23    2002-01-15 M      White British  0   0       FALSE    0.50
24    2002-04-15 F      South Asian    1   1       FALSE    1.60
25    2001-01-15 F      White British  0   1        TRUE    1.81
26    2001-04-15 F      White British NA   0       FALSE      NA
27    2002-07-15 F      White British  0   0        TRUE    2.14
28    2000-11-15 F      South Asian    1   1        TRUE    1.08
29    2001-04-15 F      White British  0   0       FALSE    0.72
30    2002-04-15 M      South Asian    1   1       FALSE    0.84
⋮     ⋮          ⋮      ⋮             ⋮   ⋮        ⋮        ⋮
17195 2002-04-15 F      White British 0   1         TRUE    0.62
17196 2001-07-15 M      South Asian   1   0         TRUE    1.81
17197 2001-07-15 M      White British 0   0        FALSE    0.18
17198 2001-08-15 M      White British 0   0         TRUE    2.73
17199 2001-06-15 M      White British 0   0        FALSE    2.04
17200 2001-03-15 M      South Asian   1   0        FALSE    0.98
17201 2002-06-15 M      White British 0   1        FALSE    2.82
17202 2001-01-15 F      White British 0   1        FALSE    0.30
17203 2002-08-15 M      White British 0   0         TRUE    6.71
17204 2001-05-15 F      White British 0   0        FALSE    1.93
17205 2002-05-15 F      Other         0   0        FALSE    0.73
17206 2001-02-15 F      White British 0   0         TRUE    0.64
17207 2001-10-15 F      Other         1   0        FALSE    1.04
17208 2001-03-15 M      Other         1   1        FALSE    1.80
17209 2001-10-15 F      South Asian   1   1        FALSE    3.29
17210 2001-09-15 M      South Asian   1   0        FALSE    1.01
17211 2002-07-15 F      South Asian   1   0        FALSE    0.91
17212 2002-05-15 M      South Asian   1   1        FALSE    1.08
17213 2001-03-15 F      Other         1   1         TRUE    0.86
17214 2002-08-15 M      White British 0   1         TRUE    0.11
17215 2000-09-15 M      White British 0   0         TRUE    0.39
17216 2001-02-15 F      White British 0   1         TRUE    2.17
17217 2001-02-15 M      White British 0   0        FALSE    7.97
17218 2001-10-15 M      White British 0   0        FALSE    0.69
17219 2001-08-15 M      South Asian   0   0         TRUE    1.21
17220 2001-01-15 F      White British 0   1         TRUE    0.33
17221 2002-07-15 F      White British 0   0        FALSE    0.98
17222 2002-05-15 M      White British 0   0        FALSE    1.23
17223 2002-01-15 F      White British 0   1        FALSE    0.19
17224 2001-07-15 M      White British 0   0        FALSE    3.00
      DistNearSch ⋯ Y2014.2015_Term3 Y2015.2016_Term1 Y2015.2016_Term2
1     0.66        ⋯ 107442           107442           107442
2     0.62        ⋯ 140569           140569           140569
3     0.00        ⋯ 136529           136529           136529
4     0.57        ⋯ 107441           107441           107441
5     0.44        ⋯ 108087           108087           108087
6     0.62        ⋯ 107366           107366           107366
7     0.15        ⋯ 139474           139474           139474
8     0.57        ⋯ 139982           139982           139982
9     1.56        ⋯ 107395           107395           107395
10    1.56        ⋯ 107439           107439           107439
11    3.60        ⋯ 136905           136905           136905
12    0.29        ⋯ 107440           107440           107440
13      NA        ⋯ NA               NA               NA
14    0.61        ⋯ 107391           107391           107391
15    0.32        ⋯ 136664           136664           136664
16    0.21        ⋯ 130909           130909           130909
17    0.51        ⋯ 107442           107442           107442
18    0.33        ⋯ 107441           107441           107441
19    0.26        ⋯ 107442           107442           107442
20    1.04        ⋯ 107395           107395           107395
21    0.98        ⋯ NA               NA               NA
22    2.14        ⋯ 136736           136736           136736
23    0.50        ⋯ 136905           136905           136905
24    0.29        ⋯ NA               136962           136962
25    0.30        ⋯ 107428           107428           107428
26      NA        ⋯ NA               NA               NA
27    2.14        ⋯ 136736           136736           136736
28    0.78        ⋯ 107413           107413           107413
29    0.72        ⋯ 107562           107562           107562
30    0.20        ⋯ 139982           139982           139982
⋮     ⋮           ⋱ ⋮                ⋮                ⋮
17195 0.62        ⋯ 107350           107350           107350
17196 0.98        ⋯ 135865           135865           135865
17197 0.18        ⋯ 136905           136905           136905
17198 1.78        ⋯ 135229           135229           135229
17199 1.99        ⋯ 121716           121716           121716
17200 0.60        ⋯ 135866           135866           135866
17201 1.09        ⋯ 135865           135865           135865
17202 0.30        ⋯ 136343           136343           136343
17203 0.66        ⋯ 137497           137497           137497
17204 0.97        ⋯ 139975           139975           139975
17205 0.73        ⋯ 136905           136905           136905
17206 0.64        ⋯ 136736           136736           136736
17207 0.46        ⋯ 139982           139982           139982
17208 0.81        ⋯ 107439           107439           107439
17209 0.36        ⋯ 137277           137277           137277
17210 0.68        ⋯ 135866           135866           135866
17211 0.80        ⋯ 137277           137277           137277
17212 0.39        ⋯ 135367           135367           135367
17213 0.41        ⋯ 139982           139982           139982
17214 0.11        ⋯ 107440           107440           107440
17215 0.39        ⋯ 136736           136736           136736
17216 0.40        ⋯ 136672           136672           136672
17217 2.25        ⋯ 121700           121700           121700
17218 0.69        ⋯ 132219           132219           132219
17219 0.52        ⋯ 107442           107442           107442
17220 0.33        ⋯ 135865           135865           135865
17221 0.98        ⋯ 135865           135865           135865
17222 1.23        ⋯ 136736           136736           136736
17223 0.19        ⋯ 107350           107350           107350
17224 0.24        ⋯ 107366           107366           107366
      Y2015.2016_Term3 Y2016.2017_Term1 Y2016.2017_Term2 Y2016.2017_Term3
1     107442           143114           143114           143114
2     140569           140569           140569           140569
3     136529           136529           136529           136529
4     107441           143112           143112           143112
5     108087           108087           108087           108087
6     107366           142761           142761           142761
7     139474           139474           139474           139474
8     139982           139982           139982           139982
9     107395           107395           107395           107395
10    107439           107439           107439           107439
11    136905           136905           136905           136905
12    107440           107440           107440           107440
13    NA               NA               NA               NA
14    107391           143113           143113           143113
15    136664           136664           136664           136664
16    130909           130909           130909           130909
17    107442           143114           143114           143114
18    107441           143112           143112           143112
19    107442           143114           143114           143114
20    107395           107395           107395           107395
21    NA               137177           137177           137177
22    136736           136736           136736           136736
23    136905           136905           136905           136905
24    136962           136962           136962           136962
25    107428           107428           107428           107428
26    NA               NA               NA               NA
27    136736           136736           136736           136736
28    107413           107413           107413           107413
29    107562           107562           107562           107562
30    139982           139982           139982           139982
⋮     ⋮                ⋮                ⋮                ⋮
17195 107350           142825           142825           142825
17196 135865           135865           135865           135865
17197 136905           136905           136905           136905
17198 135229           135229           135229           135229
17199 121716           121716           121716           121716
17200 135866           135866           135866           135866
17201 135865           135865           135865           135865
17202 136343           136343           136343           136343
17203 137497           137497           137497           137497
17204 139975           139975           139975           139975
17205 136905           136905           136905           136905
17206 136736           136736           136736           136736
17207 139982           139982           139982           139982
17208 107439           107439           107439           107439
17209 137277           137277           137277           137277
17210 135866           135866           135866           135866
17211 137277           137277           137277           137277
17212 135367           135367           135367           135367
17213 139982           139982           139982           139982
17214 107440           107440           107440           107440
17215 136736           135851           135851           135851
17216 136672           136672           136672           136672
17217 121700           121700           121700           121700
17218 132219           142590           142590           142590
17219 107442           143114           143114           143114
17220 135865           135865           135865           135865
17221 135865           135865           135865           135865
17222 136736           136736           136736           136736
17223 107350           142825           142825           142825
17224 107366           142761           142761           142761
      Y2017.2018_Term1 Y2017.2018_Term2 Y2017.2018_Term3
1     NA               NA               NA
2     NA               NA               NA
3     136529           136529           136529
4     143112           143112           143112
5     NA               NA               NA
6     NA               NA               NA
7     139474           139474           139474
8     139982           139982           139982
9     NA               NA               NA
10    NA               NA               NA
11    136905           136905           136905
12    107440           107440           107440
13    NA               NA               NA
14    NA               NA               NA
15    136664           136664           136664
16    NA               NA               NA
17    143114           143114           143114
18    NA               NA               NA
19    143114           143114           143114
20    NA               NA               NA
21    NA               NA               NA
22    136736           136736           136736
23    136905           136905           136905
24    136962           136962           136962
25    NA               NA               NA
26    NA               NA               NA
27    136736           136736           136736
28    NA               NA               NA
29    NA               NA               NA
30    139982           139982           139982
⋮     ⋮                ⋮                ⋮
17195 142825           142825           130980
17196 NA               NA               NA
17197 NA               NA               NA
17198 NA               NA               NA
17199 NA               NA               NA
17200 NA               NA               NA
17201 145173           145173           145173
17202 NA               NA               NA
17203 137497           137497           137497
17204 NA               NA               NA
17205 136905           136905           136905
17206 NA               NA               NA
17207 139982           139982           139982
17208 NA               NA               NA
17209 137277           137277           137277
17210 135866           135866           135866
17211 137277           137277           137277
17212 135367           135367           135367
17213 NA               NA               NA
17214 107440           107440           107440
17215 NA               NA               NA
17216 NA               NA               NA
17217 NA               NA               NA
17218 142590           142590           142590
17219 NA               NA               NA
17220 NA               NA               NA
17221 145173           145173           145173
17222 136736           136736           136736
17223 142825           142825           142825
17224 NA               NA               NA

# Ever AP/PRU

In [180]:
ever_AP <- read.csv("data/ever_AP_ids.csv", header = TRUE)

In [181]:
head(ever_AP)

  person_id                                                        ever_AP
1 BC99204E62FE3D7E8E4D41B6D223F300ED59636D3A2E19BE5DCBAB85A8C6CA68 TRUE
2 0F719CE1354E346BC9788D861696C41D3E12CD4E9B922C321905506B99B7F517 TRUE
3 B606CEC2C788D17D26AE9F5AD9343D6047CF3C2905F4DD428783C1906106A262 TRUE
4 F8C2444EF68664B92F9D89F8AC9DFB216B728E3FFAAC2409F420B4D7C62CD3E0 TRUE
5 197739B330DCFC024B66615A0BA3C4DF10389D593D2D669EF5AB3EDDDEB69339 TRUE
6 FC4A9A9ECC56374706EC415D1FA433DF7C815C0F5048A15BF7AF96DF0CEF3933 TRUE

In [182]:
person_absence_cin_excl_ks4_dest_enrol_ap <- person_absence_cin_excl_ks4_dest_enrol |>
    left_join(ever_AP, by=join_by(person_id))

In [183]:
person_absence_cin_excl_ks4_dest_enrol_ap <- person_absence_cin_excl_ks4_dest_enrol_ap |>
    mutate(ever_AP = case_when(
            ever_AP ~ TRUE,
            TRUE ~ FALSE)
           )

In [184]:
head(person_absence_cin_excl_ks4_dest_enrol_ap)

  cohort  person_id
1 2000/01 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2 2000/01 00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
3 2001/02 0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D
4 2001/02 0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7
5 2000/01 00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66
6 2000/01 0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D
  DOB        Gender Ethnicity     EAL ever_FSM ever_CIN DistCurrSch DistNearSch
1 2001-05-15 M      White British 0   0        FALSE    0.66        0.66
2 2001-01-15 F      White British 0   0         TRUE    3.50        0.62
3 2001-11-15 M      White British 0   1         TRUE    7.01        0.00
4 2002-05-15 M      Other         1   0        FALSE    0.57        0.57
5 2000-11-15 M      South Asian   1   0        FALSE    1.69        0.44
6 2001-04-15 F      White British 0   0        FALSE    1.12        0.62
  ⋯ Y2015.2016_Term1 Y2015.2016_Term2 Y2015.2016_Term3 Y2016.2017_Term1
1 ⋯ 107442           107442           107442           143114
2 ⋯ 140569           140569           140569           140569
3 ⋯ 136529           136529           136529           136529
4 ⋯ 107441           107441           107441           143112
5 ⋯ 108087           108087           108087           108087
6 ⋯ 107366           107366           107366           142761
  Y2016.2017_Term2 Y2016.2017_Term3 Y2017.2018_Term1 Y2017.2018_Term2
1 143114           143114           NA               NA
2 140569           140569           NA               NA
3 136529           136529           136529           136529
4 143112           143112           143112           143112
5 108087           108087           NA               NA
6 142761           142761           NA               NA
  Y2017.2018_Term3 ever_AP
1 NA               FALSE
2 NA               FALSE
3 136529           FALSE
4 143112           FALSE
5 NA               FALSE
6 NA               FALSE

In [185]:
# save as csv
write.csv(person_absence_cin_excl_ks4_dest_enrol_ap, "data/full_data.csv", row.names = FALSE)