In [1]:
library(tidyverse)
library(dbplyr)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘dbplyr’


The following objects are masked from ‘package:dplyr’:

    ident, sql

In [2]:
options(tibble.width = Inf)

# SEN Support, EHC plan, DOB, Gender, Ethnicity, cohort, Distance to school, IDACI score, LSOA, EAL, FSM

In [3]:
person <- read.csv("data/additional_person_home_fsm_sen.csv", header = TRUE)

In [4]:
head(person)

  person_id
1 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
2 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
3 000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909
4 00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC
5 0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
6 00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7
  ever_SEN_support first_SEN_support_year SEN_support_need ever_EHC_plan
1 FALSE              NA                   NA               FALSE
2  TRUE            2009                                    FALSE
3 FALSE              NA                   NA               FALSE
4 FALSE              NA                   NA               FALSE
5  TRUE            2008                                    FALSE
6  TRUE            2007                                    FALSE
  first_EHC_plan_year EHC_plan_need no_SEN birth_date gender CombinedEthnicity
1 NA                  NA             TRUE  1999-09-15 F      White British
2 NA                  NA            FALSE  1999-08-15 F      White British
3 NA                  NA             TRUE  1998-11-15 M      South Asian
4 NA                  NA             TRUE  2000-05-15 M      White British
5 NA                  NA            FALSE  2000-08-15 F      White British
6 NA                  NA            FALSE  1999-09-15 M      South Asian
  cohort  DistCurrSch IDACIScore_Home LSOA11_Home EAL ever_fsm
1 1999/00 2.45        0.04778         E01027555   0   0
2 1998/99 4.71        0.35519         E01010703   0   0
3 1998/99 0.33        0.37575         E01010742   0   0
4 1999/00 1.78        0.07161         E01010641   0   0
5 1999/00 0.76        0.44704         E01010655   0   1
6 1999/00 1.29        0.41032         E01010626   0   1

In [5]:
person |> distinct(LSOA11_Home) |> pull(LSOA11_Home)

   [1] "E01027555" "E01010703" "E01010742" "E01010641" "E01010655" "E01010626"
   [7] "E01010568" "E01010752" "E01027577" "E01010625" "E01011330" "E01010710"
  [13] "E01011792" "E01010579" "E01010663" "E01019350" "E01015222" "E01011541"
  [19] "E01010738" "E01010764" "E01010734" "E01010795" "E01010793" "E01010706"
  [25] "E01010790" "E01010967" "E01010802" "E01010772" "E01010613" "E01010580"
  [31] "E01010603" "E01020862" "E01010606" NA          "E01032492" "E01010690"
  [37] "E01010621" "E01010587" "E01010873" "E01000037" "E01027574" "E01015788"
  [43] "E01010688" "E01010679" "E01016839" "E01027576" "E01010809" "E01010872"
  [49] "E01010650" "E01010593" "E01010821" "E01010810" "E01000055" "E01015692"
  [55] "E01027585" "E01025331" "E01010666" "E01010600" "E01010832" "E01010845"
  [61] "E01010702" "E01010835" "E01010808" "E01010604" "E01010786" "E01025088"
  [67] "E01010676" "E01010607" "E01011465" "E01031144" "E01010737" "E01027581"
  [73] "E01011458" "E01027556" "E01011606" "E01013249" "E01010863" "E01010817"
  [79] "E01027565" "E01010659" "E01010763" "E01010682" "E01010715" "E01010824"
  [85] "E01012749" "E01004880" "E01010575" "E01010761" "E01010727" "E01027872"
  [91] "E01010719" "E01010729" "E01025108" "E01010778" "E01010665" "E01010610"
  [97] "E01010695" "E01010905" "E01013101" "E01033691" "E01010724" "E01010811"
 [103] "E01010653" "E01010794" "E01010744" "E01011149" "E01010819" "E01010776"
 [109] "E01010705" "E01010691" "E01010736" "E01010620" "E01010739" "E01010816"
 [115] "E01027571" "E01033183" "E01010638" "E01010754" "E01033182" "E01010758"
 [121] "E01010769" "E01010781" "E01010818" "E01010841" "E01011537" "E01027560"
 [127] "E01011596" "E01010801" "E01015642" "E01010849" "E01011000" "E01010870"
 [133] "E01010831" "E01033695" "E01010658" "E01033697" "E01011428" "E01010697"
 [139] "E01011055" "E01010645" "E01010846" "E01027575" "E01010791" "E01010711"
 [145] "E01010813" "E01026128" "E01005428" "E01028465" "E01010733" "E01007794"
 [151] "E01010712" "E01015250" "E01010589" "E01007801" "E01010591" "E01013422"
 [157] "E01010581" "E01010853" "E01010735" "E01022436" "E01011589" "E01027568"
 [163] "E01027828" "E01010745" "E01010671" "E01011093" "E01010812" "E01013049"
 [169] "E01010713" "E01010775" "E01010670" "E01010855" "E01010632" "E01010693"
 [175] "E01010732" "E01027840" "E01010723" "E01010806" "E01010569" "E01010850"
 [181] "E01010646" "E01014566" "E01010800" "E01010837" "E01010898" "E01010616"
 [187] "E01010743" "E01010586" "E01009716" "E01010675" "E01011647" "E01010673"
 [193] "E01010683" "E01010678" "E01010859" "E01010856" "E01002397" "E01010728"
 [199] "E01018940" "E01010782" "E01010747" "E01027557" "E01010838" "E01010826"
 [205] "E01026312" "E01010731" "E01010815" "E01010654" "E01010783" "E01010869"
 [211] "E01013558" "E01010687" "E01010804" "E01010669" "E01032898" "E01010595"
 [217] "E01024591" "E01010619" "E01011003" "E01010709" "E01010830" "E01026327"
 [223] "E01011521" "E01010874" "E01009485" "E01022022" "E01011570" "E01011651"
 [229] "E01011323" "E01011597" "E01006113" "E01010759" "E01011337" "E01010767"
 [235] "E01010598" "E01010609" "E01008097" "E01010644" "E01027570" "E01005429"
 [241] "E01011240" "E01021034" "E01010740" "E01013423" "E01007877" "E01027566"
 [247] "E01010788" "E01011276" "E01010716" "E01010611" "E01010753" "E01010784"
 [253] "E01010674" "E01010866" "E01027572" "E01010596" "E01010721" "E01010700"
 [259] "E01010572" "E01010686" "E01004979" "E01010803" "E01010624" "E01010950"
 [265] "E01010766" "E01010582" "E01011769" "E01011921" "E01010805" "E01010760"
 [271] "E01010627" "E01011006" "E01010842" "E01026368" "E01010657" "E01010993"
 [277] "E01000077" "E01012934" "E01010730" "E01010680" "E01027564" "E01010717"
 [283] "E01010570" "E01010605" "E01010684" "E01033696" "E01010839" "E01018041"
 [289] "E01010762" "E01010751" "E01010725" "E01010785" "E01023850" "E01010637"
 [295] "E01024876" "E01011361" "E01010796" "E01010792" "E01023645" "E01011581"
 [301] "E01010965" "E01031490" "E01010648" "E01024857" "E01027724" "E01010941"
 [307] "E01010843" "E01008096" "E01010722" "E01018020" "E01023817" "E01033686"
 [313] "E01033690" "E01010748" "E01026214" "E01013498" "E01011197" "E01010622"
 [319] "E01027569" "E01024073" "E01010588" "E01010862" "E01011270" "E01010704"
 [325] "E01010633" "E01010807" "E01033693" "E01010867" "E01007213" "E01000576"
 [331] "E01010585" "E01010908" "E01001791" "E01010640" "E01010601" "E01000482"
 [337] "E01010847" "E01011130" "E01010750" "E01025146" "E01010614" "E01027567"
 [343] "E01033694" "E01011136" "E01010755" "E01014346" "E01010615" "E01007139"
 [349] "E01027889" "E01011803" "E01027584" "E01010789" "E01025726" "E01004464"
 [355] "E01015388" "E01027583" "E01025193" "E01010608" "E01007128" "E01025117"
 [361] "E01010594" "E01010921" "E01010574" "E01011211" "E01007680" "E01024905"
 [367] "E01027726" "E01011334" "E01027165" "E01010720" "E01027579" "E01010618"
 [373] "E01010602" "E01011363" "E01014018" "E01010707" "E01010765" "E01010667"
 [379] "E01010629" "E01011051" "E01027162" "E01004847" "E01003563" "E01027586"
 [385] "E01010833" "E01032922" "E01010651" "E01003388" "E01010871" "E01010840"
 [391] "E01016728" "E01010746" "E01010768" "E01004395" "E01027893" "E01010685"
 [397] "E01000076" "E01010827" "E01010576" "E01027725" "E01011280" "E01003783"
 [403] "E01027562" "E01027635" "E01004435" "E01013373" "E01010590" "E01010677"
 [409] "E01010749" "E01010634" "E01010992" "E01010825" "E01010911" "E01010672"
 [415] "E01011712" "E01027842" "E01010623" "E01011587" "E01010573" "E01011838"
 [421] "E01012037" "E01029429" "E01007715" "E01009344" "E01011271" "E01022229"
 [427] "E01011335" "E01010779" "E01010584" "E01011056" "E01025221" "E01010949"
 [433] "E01025361" "E01025247" "E01007780" "E01002119" "E01015038" "E01027955"
 [439] "E01010519" "E01011432" "E01025466" "E01010787" "E01027582" "E01010577"
 [445] "E01023845" "E01010848" "E01027573" "E01010890" "E01010858" "E01010814"
 [451] "E01029766" "E01003041" "E01011095" "E01010599" "E01011595" "E01010592"
 [457] "E01011455" "E01011457" "E01010583" "E01013452" "E01008863" "E01012732"
 [463] "E01006379" "E01003622" "E01025251" "E01010857" "E01005222" "E01027917"
 [469] "E01032107" "E01010852" "E01008550" "E01033053" "E01010854" "E01031913"
 [475] "E01026407" "E01010664" "E01010877" "E01010578" "E01011507" "E01010649"
 [481] "E01027648" "E01006327" "E01019605" "E01013653" "E01010636" "E01010630"
 [487] "E01001836" "E01033215" "E01006323" "E01005196" "E01005465" "E01010777"
 [493] "E01027578" "E01012928" "E01010656" "E01010643" "E01010929" "E01003043"
 [499] "E01011372" "E01010925" "E01010050" "E01028334" "E01013321" "E01011077"
 [505] "E01010714" "E01010947" "E01013573" "E01010770" "E01012683" "E01011734"
 [511] "E01010652" "E01021582" "E01015220" "E01010798" "E01011192" "E01001652"
 [517] "E01000194" "E01007151" "E01003720" "E01010828" "E01010597" "E01010642"
 [523] "E01007642" "E01010951" "E01028314" "E01013383" "E01027649" "E01013665"
 [529] "E01010696" "E01011551" "E01024264" "E01010631" "E01011602" "E01011582"
 [535] "E01024975" "E01010756" "E01010635" "E01003701" "E01029060" "E01025315"
 [541] "E01027390" "E01027642" "E01007332" "E01010612" "E01010699" "E01021341"
 [547] "E01013376" "E01010851" "E01016834" "E01003537" "E01030982" "E01011065"
 [553] "E01002637" "E01010834" "E01007244" "E01010958" "E01011483" "E01031905"
 [559] "E01010668" "E01001445" "E01011362" "E01010797" "E01011107" "E01010369"
 [565] "E01027580" "E01010904" "E01027679" "E01010773" "E01012519" "E01032032"
 [571] "E01006252" "E01027723" "E01010694" "E01012056" "E01010974" "E01011187"
 [577] "E01022103" "E01025390" "E01006145" "E01025199" "E01009391" "E01010983"
 [583] "E01010829" "E01005578" "E01020689" "E01031492" "E01031615" "E01003197"
 [589] "E01021012" "E01011326" "E01025437" "E01004816" "E01000843" "E01027653"
 [595] "E01009352" "E01010692" "E01029964" "E01011067" "E01019373" "E01003556"
 [601] "E01021226" "E01011105" "E01026762" "E01011842" "E01029840" "E01015725"
 [607] "E01010718" "E01012721" "E01010861" "E01029466" "E01012599" "E01013629"
 [613] "E01008029" "E01011533" "E01010701" "E01006720" "E01010822" "E01011434"
 [619] "E01020720" "E01011069" "E01011350" "E01000244" "E01029809" "E01011170"
 [625] "E01007702" "E01010055" "E01010820" "E01010998" "E01010726" "E01011062"
 [631] "E01025943" "E01013209" "E01027559" "E01013842" "E01011180" "E01010799"
 [637] "E01024865" "E01001787" "E01011163" "E01010934" "E01013054" "E01006289"
 [643] "E01004920" "E01009944" "E01012773" "E01010910" "E01011256" "E01004285"
 [649] "E01004878" "E01028235" "E01026958" "E01021245" "E01004838" "E01011165"
 [655] "E01011664" "E01010708" "E01010681" "E01025243" "E01015426" "E01012977"
 [661] "E01011117" "E01010698" "E01015364" "E01031047" "E01005436" "E01010628"
 [667] "E01019367" "E01013186" "E01013337" "E01008054" "E01011535" "E01033692"
 [673] "E01011374" "E01012948" "E01018251" "E01011590" "E01011957" "E01003046"
 [679] "E01010879" "E01024029" "E01020334" "E01027563" "E01027661" "E01010741"
 [685] "E01011726" "E01013624" "E01010865" "E01013485" "E01033034" "E01001512"
 [691] "E01009491" "E01011061" "E01008444" "E01011699" "E01011523" "E01014305"
 [697] "E01026400" "E01024246" "E01011080" "E01018524" "E01033523" "E01007344"
 [703] "E01011379" "E01027634" "E01011001" "E01006152" "E01004861" "E01011694"
 [709] "E01019598" "E01011400" "E01010860" "E01020600" "E01031163" "E01010571"
 [715] "E01012584" "E01013076" "E01011057" "E01011751" "E01006713" "E01010647"
 [721] "E01007873" "E01032557" "E01010056" "E01003585" "E01010864" "E01006332"
 [727] "E01008062" "E01012349" "E01010919" "E01012026" "E01007130" "E01007904"
 [733] "E01010939" "E01009488" "E01011032" "E01011729" "E01021708" "E01027351"
 [739] "E01018877" "E01026449" "E01010836" "E01011862" "E01033470" "E01010932"
 [745] "E01011886" "E01026970" "E01011015" "E01022080" "E01012708" "E01024878"
 [751] "E01009396" "E01014053" "E01033021" "E01027561" "E01011427" "E01012944"
 [757] "E01011601" "E01027660" "E01011060" "E01011027" "E01011834" "E01005451"
 [763] "E01025152" "E01032510" "E01032925" "E01016381" "E01011063" "E01011277"
 [769] "E01026549" "E01019544" "E01011695" "E01011613" "E01014473" "E01005145"
 [775] "E01027600" "E01011040" "E01031308" "E01013420" "E01006661" "E01027902"
 [781] "E01029764" "E01012631" "E01031038" "E01027670" "E01007602" "E01027474"
 [787] "E01021847" "E01011128" "E01015697" "E01007870" "E01010954" "E01005072"
 [793] "E01011555" "E01010922" "E01027760" "E01010888" "E01027774" "E01004947"
 [799] "E01025253" "E01010639" "E01007119" "E01016720" "E01013225" "E01011070"
 [805] "E01031223" "E01011599" "E01027727" "E01011054" "E01011546" "E01009800"
 [811] "E01011559" "E01013489" "E01022681" "E01022883" "E01004811" "E01027884"
 [817] "E01011527" "E01010942" "E01005756" "E01011902" "E01011204" "E01010617"
 [823] "E01033588" "E01011008" "E01005014" "E01011766" "E01013752" "E01011661"
 [829] "E01005160" "E01019062" "E01011142" "E01012078" "E01010868" "E01013029"
 [835] "E01011798" "E01010989" "E01013084" "E01024891" "E01004914" "E01011108"
 [841] "E01011359" "E01013083" "E01019084" "E01017356" "E01001059" "E01010689"
 [847] "E01011167" "E01023077" "E01006285" "E01012583" "E01003089" "E01011536"
 [853] "E01026391" "E01011134" "E01032021" "E01007645" "E01001130" "E01010987"
 [859] "E01018618" "E01011281" "E01010876" "E01001577" "E01025203" "E01027558"
 [865] "E01011479" "E01019961" "E01027837" "E01032500" "E01031440" "E01006007"
 [871] "E01010771" "E01011787" "E01012347" "E01027646" "E01027695" "E01027814"
 [877] "E01015679" "E01011692" "E01024136" "E01009883" "E01017791" "E01027687"
 [883] "E01000759" "E01011659" "E01000277" "E01003421" "E01011356" "E01002418"
 [889] "E01027439" "E01017694" "E01003912" "E01006052" "E01011242" "E01003466"
 [895] "E01025081" "E01008349" "E01025136" "E01011910" "E01027535" "E01033029"
 [901] "E01027709" "E01033475" "E01013290" "E01011410" "E01016341" "E01017040"
 [907] "E01025183" "E01009347" "E01011580" "E01025191" "E01008905" "E01027692"
 [913] "E01010981" "E01019128" "E01008738" "E01011449" "E01009640" "E01013331"
 [919] "E01025069" "E01015476" "E01032126" "E01027822" "E01027735" "E01004047"
 [925] "E01011314" "E01026042" "E01012292" "E01011115" "E01001460" "E01011598"
 [931] "E01010902" "E01027812" "E01012001" "E01009748" "E01026153" "E01011278"
 [937] "E01010953" "E01025196" "E01008455" "E01025642" "E01011017" "E01025115"
 [943] "E01024900" "E01012932" "E01011610" "E01012315" "E01012696" "E01000718"
 [949] "E01033718" "E01013082" "E01015729" "E01023587" "E01011646" "E01032923"
 [955] "E01016846" "E01001980" "E01016492" "E01031168" "E01027770" "E01003703"
 [961] "E01011401" "E01009567" "E01009820" "E01030253" "E01023650" "E01010430"
 [967] "E01011573" "E01005438" "E01010662" "E01006463" "E01009399" "E01031274"
 [973] "E01012369" "E01032799" "E01011899" "E01011269" "E01007391" "E01014068"
 [979] "E01019511" "E01013459" "E01011248" "E01010928" "E01024937" "E01032094"
 [985] "E01019081" "E01011265" "E01009392" "E01026951" "E01025388" "E01004867"
 [991] "E01011348" "E01011892" "E01030079" "E01014324" "E01016097" "E01025182"
 [997] "E01028789" "E01006275" "E01024408" "E01010907" "E01027722" "E01010933"
[1003] "E01011895" "E01007806" "E01006679" "E01028602" "E01033676" "E01005965"
[1009] "E01026114" "E01010940" "E01010878" "E01016793" "E01011266" "E01005461"
[1015] "E01017332" "E01026775" "E01011775" "E01033628" "E01012931" "E01007329"
[1021] "E01032251" "E01011272" "E01009481" "E01011758" "E01011360" "E01030075"
[1027] "E01011038" "E01015854" "E01028110" "E01027736" "E01011691" "E01008557"
[1033] "E01001988" "E01005916" "E01010062" "E01009395" "E01004899" "E01032498"
[1039] "E01007700" "E01012667" "E01012992" "E01007678" "E01017435" "E01009709"
[1045] "E01016798" "E01020183" "E01033477" "E01007515" "E01007849" "E01033279"
[1051] "E01006839" "E01024998" "E01005311" "E01007341" "E01002469" "E01011327"
[1057] "E01010936" "E01012844" "E01005605" "E01013281" "E01014282" "E01011821"
[1063] "E01010931" "E01011357" "E01013844" "E01012268" "E01006867" "E01004382"
[1069] "E01025202" "E01013831" "E01001733" "E01001492" "E01003519" "E01010943"
[1075] "E01030088" "E01011552" "E01016484" "E01012670" "E01003378" "E01015603"
[1081] "E01009636" "E01005351" "E01006739" "E01018280" "E01010938" "E01019697"
[1087] "E01011937" "E01024661" "E01019131" "E01010906" "E01018830" "E01032499"
[1093] "E01010376" "E01010968" "E01011241" "E01033258" "E01010991" "E01025200"
[1099] "E01007441" "E01011267" "E01007994" "E01009609" "E01007475" "E01027827"
[1105] "E01001174" "E01007913" "E01011066" "E01026065" "E01012052" "E01007512"
[1111] "E01013303" "E01017174" "E01010976" "E01020919" "E01015683" "E01014042"
[1117] "E01007833" "E01004272" "E01013921" "E01012942" "E01010774" "E01003564"
[1123] "E01000393" "E01009348" "E01003624" "E01025320" "E01010972" "E01029929"
[1129] "E01011386" "E01032969" "E01014623" "E01032351" "E01011138" "E01032737"
[1135] "E01010914" "E01011562" "E01004975" "E01007704" "E01011346" "E01032504"
[1141] "E01007942" "E01006761" "E01025209" "E01011648" "E01012675" "E01004333"
[1147] "E01028538" "E01003261" "E01011298" "E01005950" "E01030089" "E01011518"
[1153] "E01010332" "E01019387" "E01007871" "E01018855" "E01012148" "E01011249"
[1159] "E01011592" "E01011429" "E01004453" "E01005460" "E01002490" "E01024525"
[1165] "E01010880" "E01007336" "E01005239" "E01018264" "E01018568" "E01004780"
[1171] "E01010244" "E01021075" "E01018673" "E01031563" "E01010522" "E01016462"
[1177] "E01027880" "E01005089" "E01015155" "E01025178" "E01026213" "E01033145"
[1183] "E01009229" "E01010901" "E01000626" "E01003596" "E01008117" "E01005848"
[1189] "E01009932" "E01023669" "E01013434" "E01005383" "E01011185" "E01030967"
[1195] "E01011100" "E01027756" "E01011529" "E01031613" "E01005194" "E01019135"
[1201] "E01008300" "E01033647" "E01021653" "E01011586" "E01007141" "E01012447"
[1207] "E01011351" "E01033650" "E01012673" "E01025082" "E01004872" "E01007383"
[1213] "E01028830" "E01005287" "E01011600" "E01025724" "E01005088" "E01005433"
[1219] "E01019813" "E01032488" "E01011553" "E01010935" "E01027697" "E01010927"
[1225] "E01014283" "E01010897" "E01007914" "E01017251" "E01014251" "E01003093"
[1231] "E01032490" "E01004083" "E01008695" "E01011122" "E01005165" "E01003679"
[1237] "E01013206" "E01011947" "E01003629" "E01013338" "E01002130" "E01033237"
[1243] "E01011822" "E01008657" "E01022301" "E01005545" "E01021868" "E01019245"
[1249] "E01012936" "E01032006" "E01020543" "E01011370" "E01011273" "E01027809"
[1255] "E01006143" "E01013077" "E01006949" "E01011002" "E01007413" "E01011463"
[1261] "E01019274" "E01026024" "E01004828" "E01018118" "E01008649" "E01022811"
[1267] "E01011216" "E01010988" "E01011868" "E01026410" "E01000480" "E01027694"
[1273] "E01008112" "E01026965" "E01011519" "E01011526" "E01008294" "E01003739"
[1279] "E01027156" "E01025885" "E01011083" "E01005790" "E01012770" "E01013142"
[1285] "E01000384" "E01019166" "E01001214" "E01011029" "E01019811" "E01003495"
[1291] "E01011990" "E01033542" "E01013658" "E01011275" "E01033184" "E01026514"
[1297] "E01019515" "E01013484" "E01025351" "E01012943" "E01027675" "E01025210"
[1303] "E01031138" "E01027681" "E01010891" "E01015428" "E01024284" "E01007498"
[1309] "E01032576" "E01001276" "E01003541" "E01032103" "E01007531" "E01013238"
[1315] "E01027668" "E01020845" "E01007628" "E01005655" "E01031409" "E01033231"
[1321] "E01027888" "E01033390" "E01024240" "E01025205" "E01012952" "E01011686"
[1327] "E01011407" "E01012346" "E01011603" "E01028621" "E01030165" "E01004833"
[1333] "E01012686" "E01012679" "E01001007" "E01016657" "E01028305" "E01033689"
[1339] "E01019418" "E01006673" "E01007493" "E01018399" "E01013450" "E01000552"
[1345] "E01000681" "E01017514" "E01027810" "E01025114" "E01013758" "E01027720"
[1351] "E01007604" "E01018593" "E01024910" "E01005190" "E01024090" "E01010970"
[1357] "E01011493" "E01008044" "E01011604" "E01027671" "E01026227" "E01011177"
[1363] "E01025167" "E01003601" "E01011938" "E01024498" "E01023399" "E01009329"
[1369] "E01017075" "E01012662" "E01013364" "E01028161" "E01017055" "E01007679"
[1375] "E01014108" "E01009111" "E01019329" "E01013617" "E01026949" "E01000618"
[1381] "E01006090" "E01008682" "E01010060" "E01025293" "E01013210" "E01010937"
[1387] "E01032494" "E01010999" "E01010980" "E01012225" "E01011064" "E01006568"
[1393] "E01011684" "E01025878" "E01012855" "E01025189" "E01025319" "E01025239"
[1399] "E01011101" "E01003723" "E01027588" "E01018148" "E01025192" "E01019875"
[1405] "E01013166" "E01030687" "E01024657" "E01019432" "E01011936" "E01023556"
[1411] "E01026954" "E01013223" "E01027689" "E01025042" "E01003220" "E01002403"
[1417] "E01006986" "E01006826" "E01006778" "E01014436" "E01026075" "E01025316"
[1423] "E01012945" "E01012986" "E01009098" "E01013024" "E01010952" "E01007321"
[1429] "E01023621" "E01005513" "E01022514" "E01028934" "E01007605" "E01033322"
[1435] "E01005459" "E01006908" "E01001557" "E01015740" "E01012163" "E01007629"
[1441] "E01007212" "E01011522" "E01013332" "E01010917" "E01027703" "E01027808"
[1447] "E01023342" "E01010930" "E01005448" "E01010964" "E01025198" "E01010912"
[1453] "E01007717" "E01011677" "E01026846" "E01025120" "E01027771" "E01007768"
[1459] "E01023299" "E01011228" "E01019384" "E01007875" "E01024032" "E01011538"
[1465] "E01011445" "E01010047" "E01011247" "E01010913" "E01010892" "E01027145"
[1471] "E01006929" "E01013719" "E01007971" "E01011625" "E01025998" "E01016447"
[1477] "E01026074" "E01027741" "E01011740" "E01031778" "E01004531" "E01008998"
[1483] "E01018896" "E01027782" "E01013263" "E01024353" "E01011322" "E01011223"
[1489] "E01027894" "E01011230" "E01020794" "E01000234" "E01010920" "E01013567"
[1495] "E01011446" "E01011492" "E01007533" "E01026263" "E01027834" "E01025184"
[1501] "E01013947" "E01011459" "E01010984" "E01000109" "E01031057" "E01011627"
[1507] "E01020195" "E01011295" "E01011150" "E01005434" "E01005793" "E01004249"
[1513] "E01018470" "E01011494" "E01011779" "E01010061" "E01028269" "E01009548"

In [6]:
person |>
    nrow()

[1] 17392

In [7]:
n_distinct(person$person_id)

[1] 17392

# Absences: total, authorised, unauthorised

In [8]:
absence_alltime <- read.csv("data/additional_absence_alltime_rates.csv", header = TRUE)

In [9]:
head(absence_alltime)

  person_id
1 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
2 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
3 000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909
4 00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC
5 0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
6 00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7
  AuthorisedAbsenceRate UnauthorisedAbsenceRate TotalAbsenceRate
1  1.873935              0.0000000               1.873935
2  9.112426              0.3550296               9.467456
3  1.663696              0.0000000               1.663696
4  1.704545              0.0000000               1.704545
5  1.205511             15.1549943              16.360505
6 12.600229              0.0000000              12.600229

In [10]:
person_absence <- person |>
    left_join(absence_alltime, by=join_by(person_id))

In [11]:
head(person_absence)

  person_id
1 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
2 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
3 000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909
4 00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC
5 0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
6 00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7
  ever_SEN_support first_SEN_support_year SEN_support_need ever_EHC_plan
1 FALSE              NA                   NA               FALSE
2  TRUE            2009                                    FALSE
3 FALSE              NA                   NA               FALSE
4 FALSE              NA                   NA               FALSE
5  TRUE            2008                                    FALSE
6  TRUE            2007                                    FALSE
  first_EHC_plan_year EHC_plan_need no_SEN birth_date gender CombinedEthnicity
1 NA                  NA             TRUE  1999-09-15 F      White British
2 NA                  NA            FALSE  1999-08-15 F      White British
3 NA                  NA             TRUE  1998-11-15 M      South Asian
4 NA                  NA             TRUE  2000-05-15 M      White British
5 NA                  NA            FALSE  2000-08-15 F      White British
6 NA                  NA            FALSE  1999-09-15 M      South Asian
  cohort  DistCurrSch IDACIScore_Home LSOA11_Home EAL ever_fsm
1 1999/00 2.45        0.04778         E01027555   0   0
2 1998/99 4.71        0.35519         E01010703   0   0
3 1998/99 0.33        0.37575         E01010742   0   0
4 1999/00 1.78        0.07161         E01010641   0   0
5 1999/00 0.76        0.44704         E01010655   0   1
6 1999/00 1.29        0.41032         E01010626   0   1
  AuthorisedAbsenceRate UnauthorisedAbsenceRate TotalAbsenceRate
1  1.873935              0.0000000               1.873935
2  9.112426              0.3550296               9.467456
3  1.663696              0.0000000               1.663696
4  1.704545              0.0000000               1.704545
5  1.205511             15.1549943              16.360505
6 12.600229              0.0000000              12.600229

In [12]:
person_absence <- person_absence |>
    mutate(across(c(AuthorisedAbsenceRate, UnauthorisedAbsenceRate, TotalAbsenceRate),
                ~ replace_na(., 0)))

In [13]:
person_absence |>
    nrow()

[1] 17392

In [14]:
n_distinct(person_absence$person_id)

[1] 17392

# Ever CIN

In [15]:
cin <- read.csv("data/additional_ever_cin.csv", header = TRUE)

In [16]:
head(cin)

  person_id                                                        ever_CIN
1 AAF20E0D9D31684973B137A74028F54A25D0C5EE563478BCB3702047DB25B55B TRUE
2 22A611BACA79474CB520C45004E70419C711DD1AF450F034DD0A46C1417DA708 TRUE
3 683466122ED7D987E396F81D5EB4A3F7BECBA4F8D31DE8C1CD3208005CC6741B TRUE
4 994DEBAAD8CF351CE9C31B89A669974A64F7BB43F315344C3EF31D83CC7CB92D TRUE
5 2DA907C18DD6C9C21DEA87DB2807F96B4D720850953AA25E7EE3306457C6DA9E TRUE
6 F5FD9F46523BDF5820C10C5C92C480B112402A40A9E1324915307C3BCACD5FEB TRUE

In [17]:
person_absence_cin <- person_absence |>
    left_join(cin, by=join_by(person_id))

In [18]:
person_absence_cin <- person_absence_cin |>
    mutate(ever_CIN = case_when(
            ever_CIN ~ TRUE,
        TRUE ~ FALSE)
           )

In [19]:
head(person_absence_cin)

  person_id
1 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
2 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
3 000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909
4 00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC
5 0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
6 00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7
  ever_SEN_support first_SEN_support_year SEN_support_need ever_EHC_plan
1 FALSE              NA                   NA               FALSE
2  TRUE            2009                                    FALSE
3 FALSE              NA                   NA               FALSE
4 FALSE              NA                   NA               FALSE
5  TRUE            2008                                    FALSE
6  TRUE            2007                                    FALSE
  first_EHC_plan_year EHC_plan_need no_SEN birth_date gender ⋯ cohort
1 NA                  NA             TRUE  1999-09-15 F      ⋯ 1999/00
2 NA                  NA            FALSE  1999-08-15 F      ⋯ 1998/99
3 NA                  NA             TRUE  1998-11-15 M      ⋯ 1998/99
4 NA                  NA             TRUE  2000-05-15 M      ⋯ 1999/00
5 NA                  NA            FALSE  2000-08-15 F      ⋯ 1999/00
6 NA                  NA            FALSE  1999-09-15 M      ⋯ 1999/00
  DistCurrSch IDACIScore_Home LSOA11_Home EAL ever_fsm AuthorisedAbsenceRate
1 2.45        0.04778         E01027555   0   0         1.873935
2 4.71        0.35519         E01010703   0   0         9.112426
3 0.33        0.37575         E01010742   0   0         1.663696
4 1.78        0.07161         E01010641   0   0         1.704545
5 0.76        0.44704         E01010655   0   1         1.205511
6 1.29        0.41032         E01010626   0   1        12.600229
  UnauthorisedAbsenceRate TotalAbsenceRate ever_CIN
1  0.0000000               1.873935        FALSE
2  0.3550296               9.467456        FALSE
3  0.0000000               1.663696        FALSE
4  0.0000000               1.704545        FALSE
5 15.1549943              16.360505        FALSE
6  0.0000000              12.600229         TRUE

In [20]:
person_absence_cin |>
    nrow()

[1] 17392

In [21]:
n_distinct(person_absence_cin$person_id)

[1] 17392

# Exclusions

In [22]:
exclusions <- read.csv("data/additional_exclusions.csv", header = TRUE)

In [23]:
head(exclusions)

  person_id                                                        Suspensions
1 00211975518FD5336E43850D59B5F5DDA7CD98B212760111CB40528BDECF3B1B  5
2 0025514088C52FB45B7439689844A1FEA2FB8B2753994F432CC7DDC68036BD59  1
3 0045ADA48CA299BC4445318E8D951610DCB89A829665CFC821E92340F0F8B30D  6
4 004D0B5FF90E252B2912022950FEC4929A1ACB81BA61A626F3093B3B496C93CA  1
5 007570ED5702694AEE71FBCA3ED93584AD7C19E06FE4CB64203ED8BE71B024EA 20
6 009354452C32CB442E4EEE6DF777F1EA4756148684FD6E3F75EA15F5F0E28081  5
  SuspensionSessions Exclusions
1 30                 0
2 10                 0
3 14                 0
4  6                 0
5 74                 0
6 38                 0

In [24]:
person_absence_cin_excl <- person_absence_cin |>
    left_join(exclusions, by=join_by(person_id))

In [25]:
person_absence_cin_excl <- person_absence_cin_excl |>
    replace_na(list(
    Suspensions = 0,
    SuspensionSessions = 0,
    Exclusions = 0
  ))

In [26]:
head(person_absence_cin_excl)

  person_id
1 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
2 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
3 000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909
4 00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC
5 0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
6 00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7
  ever_SEN_support first_SEN_support_year SEN_support_need ever_EHC_plan
1 FALSE              NA                   NA               FALSE
2  TRUE            2009                                    FALSE
3 FALSE              NA                   NA               FALSE
4 FALSE              NA                   NA               FALSE
5  TRUE            2008                                    FALSE
6  TRUE            2007                                    FALSE
  first_EHC_plan_year EHC_plan_need no_SEN birth_date gender ⋯ LSOA11_Home EAL
1 NA                  NA             TRUE  1999-09-15 F      ⋯ E01027555   0
2 NA                  NA            FALSE  1999-08-15 F      ⋯ E01010703   0
3 NA                  NA             TRUE  1998-11-15 M      ⋯ E01010742   0
4 NA                  NA             TRUE  2000-05-15 M      ⋯ E01010641   0
5 NA                  NA            FALSE  2000-08-15 F      ⋯ E01010655   0
6 NA                  NA            FALSE  1999-09-15 M      ⋯ E01010626   0
  ever_fsm AuthorisedAbsenceRate UnauthorisedAbsenceRate TotalAbsenceRate
1 0         1.873935              0.0000000               1.873935
2 0         9.112426              0.3550296               9.467456
3 0         1.663696              0.0000000               1.663696
4 0         1.704545              0.0000000               1.704545
5 1         1.205511             15.1549943              16.360505
6 1        12.600229              0.0000000              12.600229
  ever_CIN Suspensions SuspensionSessions Exclusions
1 FALSE    0           0                  0
2 FALSE    0           0                  0
3 FALSE    0           0                  0
4 FALSE    0           0                  0
5 FALSE    0           0                  0
6  TRUE    0           0                  0

In [27]:
person_absence_cin_excl |>
    nrow()

[1] 17392

In [28]:
n_distinct(person_absence_cin_excl$person_id)

[1] 17392

# KS4 attainment

In [29]:
ks4 <- read.csv("data/additional_ks4_filtered.csv", header = TRUE)

In [30]:
head(ks4)

  person_id                                                        KS4_ENTRIES
1 999E2FF4F0303428E1280117A02BCEC59A7B8D4CBDD61036F4760B51016F8241 2
2 69EF02A9067140DD81019ED940F066239896FA631C2C5AF68A8AA9D5B452393D 0
3 445119E057D1EB3EE45B61EDF26220F6B81154AE021CDB2070F3E655C926F859 2
4 718BA2DE45FA4B9A5D6C3FFB29F57237AB9CF920FBB68375A8FFDCC9B3BF4BE6 1
5 D4AD86463720A23BBFB0C45C8891896EE343963A9A1D09FECCD11A08A9B9BD8C 1
6 83EDFB835D4D45BA03DF5E77E77D633903DF918A876C1D24F249AE67E152C5C3 2
  KS4_PASS_LEV1_PTQ_EE KS4_PASS_LEV2_PTQ_EE KS4_IDACI
1 0                    0                    0
2 0                    0                    0
3 0                    0                    0
4 0                    0                    0
5 0                    0                    0
6 1                    0                    0

In [31]:
ks4 <- distinct(ks4)

In [32]:
ks4 |>
    nrow()

[1] 17198

In [33]:
n_distinct(ks4$person_id)

[1] 17186

In [47]:
ks4 |>
    group_by(person_id) |>
    filter(n() > 1) |>
    arrange(person_id)

     person_id KS4_ENTRIES KS4_PASS_LEV1_PTQ_EE KS4_PASS_LEV2_PTQ_EE KS4_IDACI

In [46]:
ks4 <- ks4 |>
  arrange(person_id, KS4_IDACI) |> 
  group_by(person_id) |>
  slice_tail(n = 1) |> 
  ungroup()

In [48]:
person_absence_cin_excl_ks4 <- person_absence_cin_excl |>
    left_join(ks4, by=join_by(person_id))

In [49]:
head(person_absence_cin_excl_ks4)

  person_id
1 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
2 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
3 000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909
4 00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC
5 0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
6 00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7
  ever_SEN_support first_SEN_support_year SEN_support_need ever_EHC_plan
1 FALSE              NA                   NA               FALSE
2  TRUE            2009                                    FALSE
3 FALSE              NA                   NA               FALSE
4 FALSE              NA                   NA               FALSE
5  TRUE            2008                                    FALSE
6  TRUE            2007                                    FALSE
  first_EHC_plan_year EHC_plan_need no_SEN birth_date gender ⋯
1 NA                  NA             TRUE  1999-09-15 F      ⋯
2 NA                  NA            FALSE  1999-08-15 F      ⋯
3 NA                  NA             TRUE  1998-11-15 M      ⋯
4 NA                  NA             TRUE  2000-05-15 M      ⋯
5 NA                  NA            FALSE  2000-08-15 F      ⋯
6 NA                  NA            FALSE  1999-09-15 M      ⋯
  UnauthorisedAbsenceRate TotalAbsenceRate ever_CIN Suspensions
1  0.0000000               1.873935        FALSE    0
2  0.3550296               9.467456        FALSE    0
3  0.0000000               1.663696        FALSE    0
4  0.0000000               1.704545        FALSE    0
5 15.1549943              16.360505        FALSE    0
6  0.0000000              12.600229         TRUE    0
  SuspensionSessions Exclusions KS4_ENTRIES KS4_PASS_LEV1_PTQ_EE
1 0                  0          20          14
2 0                  0          13           8
3 0                  0          18          15
4 0                  0          15          12
5 0                  0          13           7
6 0                  0          14          11
  KS4_PASS_LEV2_PTQ_EE KS4_IDACI
1 14                   0.06
2  3                   0.36
3 15                   0.38
4 12                   0.14
5  1                   0.45
6 10                   0.36

In [50]:
person_absence_cin_excl_ks4 |>
    nrow()

[1] 17392

In [51]:
n_distinct(person_absence_cin_excl_ks4$person_id)

[1] 17392

In [53]:
IDACI <- person_absence_cin_excl_ks4 |>
    select(person_id, IDACIScore_Home, KS4_IDACI)

In [54]:
IDACI <- IDACI |>
    mutate(IDACI = coalesce(IDACIScore_Home, KS4_IDACI)) |>
    select(person_id, IDACI)

In [55]:
person_absence_cin_excl_ks4 <- person_absence_cin_excl_ks4 |>
    left_join(IDACI, by=join_by(person_id)) |>
    select(-c(IDACIScore_Home, KS4_IDACI))

In [57]:
person_absence_cin_excl_ks4 %>%
  count(person_id) %>%
  filter(n > 1)

     person_id n

In [58]:
person_absence_cin_excl_ks4 |>
    nrow()

[1] 17392

In [59]:
n_distinct(person_absence_cin_excl_ks4$person_id)

[1] 17392

# Destinations

In [77]:
destinations <- read.csv("data/additional_manual_classification.csv", header = TRUE)

In [78]:
destinations <- destinations |>
    select(person_id, Label) |>
    distinct()

In [79]:
destinations |>
    nrow()

[1] 17538

In [80]:
n_distinct(destinations$person_id)

[1] 17538

In [75]:
destinations_detail <- read.csv("data/additional_destinations_wide_detail.csv", header = TRUE)

In [76]:
destinations_detail |>
    filter(person_id == '0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D')

  person_id                                                        NCCIS_ACADYR
1 0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D 2016/2017
2 0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D 2016/2017
  X9        X10       X11       X12       X1        X2
1 Education Education Education Education Education Education
2 NA        NA        NA        NA        NA        NA
  X3                      X4                      X5
1 NA                      NA                      NA
2 NEET: Start date agreed NEET: Start date agreed NEET: Start date agreed
  X6                      X7                      X8
1 NA                      NA                      NA
2 NEET: Start date agreed NEET: Start date agreed NEET: Start date agreed

In [81]:
destinations |>
    group_by(person_id) |>
    filter(n() > 1) |>
    arrange(person_id)

     person_id Label

In [82]:
person_absence_cin_excl_ks4_dest <- person_absence_cin_excl_ks4 |>
    left_join(destinations, by = 'person_id')

In [83]:
head(person_absence_cin_excl_ks4_dest)

  person_id
1 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
2 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
3 000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909
4 00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC
5 0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
6 00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7
  ever_SEN_support first_SEN_support_year SEN_support_need ever_EHC_plan
1 FALSE              NA                   NA               FALSE
2  TRUE            2009                                    FALSE
3 FALSE              NA                   NA               FALSE
4 FALSE              NA                   NA               FALSE
5  TRUE            2008                                    FALSE
6  TRUE            2007                                    FALSE
  first_EHC_plan_year EHC_plan_need no_SEN birth_date gender ⋯ TotalAbsenceRate
1 NA                  NA             TRUE  1999-09-15 F      ⋯  1.873935
2 NA                  NA            FALSE  1999-08-15 F      ⋯  9.467456
3 NA                  NA             TRUE  1998-11-15 M      ⋯  1.663696
4 NA                  NA             TRUE  2000-05-15 M      ⋯  1.704545
5 NA                  NA            FALSE  2000-08-15 F      ⋯ 16.360505
6 NA                  NA            FALSE  1999-09-15 M      ⋯ 12.600229
  ever_CIN Suspensions SuspensionSessions Exclusions KS4_ENTRIES
1 FALSE    0           0                  0          20
2 FALSE    0           0                  0          13
3 FALSE    0           0                  0          18
4 FALSE    0           0                  0          15
5 FALSE    0           0                  0          13
6  TRUE    0           0                  0          14
  KS4_PASS_LEV1_PTQ_EE KS4_PASS_LEV2_PTQ_EE IDACI   Label
1 14                   14                   0.04778 Steady EET
2  8                    3                   0.35519 Steady EET
3 15                   15                   0.37575 DROP
4 12                   12                   0.07161 Steady EET
5  7                    1                   0.44704 Risky trajectory
6 11                   10                   0.41032 Steady EET

In [84]:
person_absence_cin_excl_ks4_dest |>
    nrow()

[1] 17392

In [85]:
n_distinct(person_absence_cin_excl_ks4_dest$person_id)

[1] 17392

# Clean and re-order cols

In [86]:
glimpse(person_absence_cin_excl_ks4_dest)

Rows: 17,392
Columns: 28
$ person_id               <chr> "0002FD06417A994A32C6C24D7236F7C6D98ACD309E999…
$ ever_SEN_support        <lgl> FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, T…
$ first_SEN_support_year  <int> NA, 2009, NA, NA, 2008, 2007, 2011, 2008, NA, …
$ SEN_support_need        <chr> NA, "", NA, NA, "", "", "", "SPLD, SEMH", NA, …
$ ever_EHC_plan           <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALS…
$ first_EHC_plan_year     <int> NA, NA, NA, NA, NA, NA, NA, 2014, NA, NA, NA, …
$ EHC_plan_need           <chr> NA, NA, NA, NA, NA, NA, NA, "SEMH", NA, NA, NA…
$ no_SEN                  <lgl> TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, …
$ birth_date              <chr> "1999-09-15", "1999-08-15", "1998-11-15", "200…
$ gender                  <chr> "F", "F", "M", "M", "F", "M", "F", "M", "M", "…
$ CombinedEthnicity       <chr> "White British", "White British", "South Asian…
$ cohort                  <chr> "1999/00", "1998/99", "1998/99", "1999/00", "1…
$ DistCurrSch             <dbl> 2.45, 4.71, 0.33, 1.78, 0.76, 1.29, 1.37, 4.27…
$ LSOA11_Home             <chr> "E01027555", "E01010703", "E01010742", "E01010…
$ EAL                     <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0…
$ ever_fsm                <int> 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1…
$ AuthorisedAbsenceRate   <dbl> 1.8739353, 9.1124260, 1.6636958, 1.7045455, 1.…
$ UnauthorisedAbsenceRate <dbl> 0.0000000, 0.3550296, 0.0000000, 0.0000000, 15…
$ TotalAbsenceRate        <dbl> 1.8739353, 9.4674556, 1.6636958, 1.7045455, 16…
$ ever_CIN                <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE,…
$ Suspensions             <int> 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 1, 0, 0, 0, 0…
$ SuspensionSessions      <int> 0, 0, 0, 0, 0, 0, 0, 30, 0, 0, 0, 10, 0, 0, 0,…
$ Exclusions              <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ KS4_ENTRIES             <int> 20, 13, 18, 15, 13, 14, 13, 4, 14, 10, 16, 12,…
$ KS4_PASS_LEV1_PTQ_EE    <dbl> 14.0, 8.0, 15.0, 12.0, 7.0, 11.0, 8.0, 0.0, 9.…
$ KS4_PASS_LEV2_PTQ_EE    <dbl> 14.0, 3.0, 15.0, 12.0, 1.0, 10.0, 2.0, 0.0, 9.…
$ IDACI                   <dbl> 0.04778, 0.35519, 0.37575, 0.07161, 0.44704, 0…
$ Label                   <chr> "Steady EET", "Steady EET", "DROP", "Steady EE…

In [88]:
person_absence_cin_excl_ks4_dest_clean <- person_absence_cin_excl_ks4_dest |>
    select(cohort, 
           person_id, birth_date, gender, CombinedEthnicity, 
           EAL, ever_fsm, ever_CIN, 
           DistCurrSch, LSOA11_Home, IDACI, 
           ever_SEN_support, first_SEN_support_year, SEN_support_need, 
           ever_EHC_plan, first_EHC_plan_year, EHC_plan_need, 
           no_SEN, 
           AuthorisedAbsenceRate, UnauthorisedAbsenceRate, TotalAbsenceRate, 
           Suspensions, SuspensionSessions, Exclusions,
           KS4_ENTRIES, KS4_PASS_LEV1_PTQ_EE, KS4_PASS_LEV2_PTQ_EE, 
           Label) |>
    rename(Ethnicity = CombinedEthnicity, 
           DOB = birth_date, 
           Gender = gender, 
           ever_FSM = ever_fsm, 
           KS4_Entries = KS4_ENTRIES,
           KS4_Passes_Level1 = KS4_PASS_LEV1_PTQ_EE, 
           KS4_Passes_Level2 = KS4_PASS_LEV2_PTQ_EE,
           Destination = Label)

In [89]:
person_absence_cin_excl_ks4_dest_clean

      cohort  person_id
1     1999/00 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
2     1998/99 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
3     1998/99 000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909
4     1999/00 00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC
5     1999/00 0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
6     1999/00 00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7
7     1998/99 001F42538A9E6E496F13CD05B5E9FE91EB3B20F0CEBECA1B76CC5E7151B7A0D4
8     1998/99 00211975518FD5336E43850D59B5F5DDA7CD98B212760111CB40528BDECF3B1B
9     1998/99 00237E9C21696BB29409630166F2D9CCEC24B83FB120AEDD878DDD54C6516B3D
10    1998/99 00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9
11    1998/99 0025102C0D8E8C5F27454E3715E982A43E1431991E85562E55BCB19D9D1BD7D3
12    1999/00 0025514088C52FB45B7439689844A1FEA2FB8B2753994F432CC7DDC68036BD59
13    1999/00 00269FAEA8B5167F1239AA166C20B7673380CCB3E5F3E2F1F6FAA6034A11CE88
14    1998/99 0026BFA5D5426F421200AB505AAD52956621DCC253241A6647302BCE4764547D
15    1998/99 002D3DB2625339C740EB129CCC925A9D90E4F5AA05561B81FE166EDF990B8F65
16    1998/99 002E7A9E65A6A184952E4F1811844FCFCCE758FAE60986A1F9B9C9892FD0895D
17    1998/99 003196BCDC325A98F118130F185DF8FDDE1B8E1E4882719DAE198B2908F03A5B
18    1998/99 0032202712FAB3A372409235FFE3C0486E36F9B2FB9C9C9851B4ACAB9A3330F0
19    1999/00 0037E941FE88C2503AF508B5306803DB1693F3200533648162692820D1EA221D
20    1998/99 0043C7C252748432DF62E306CCC2DFF568A52DC78D4021140E3C4676C9D65A7E
21    1998/99 00450DFB52E0DDD50F5800AD149075B29E4A1454F36B9ACF2E106CF44B9BED55
22    1998/99 0045ADA48CA299BC4445318E8D951610DCB89A829665CFC821E92340F0F8B30D
23    1999/00 0046475B3089CF6E67A50BBAB6ACC4D6C7FA957BEE68B7F8365239D87857F197
24    1999/00 0046A4A849F346DFC497329C2BEE0509FAC101F8F4683542D6B453D1C10156BE
25    1999/00 004AA9D5C19D6B421D63DF6E9FB8BA6C671707143EF6FD6794AC73DE319156B0
26    1999/00 004CD18444BDD86E6C7F4BE1EE806175325E95085AEBC68E7CAA36A747BD2824
27    1999/00 004D0B5FF90E252B2912022950FEC4929A1ACB81BA61A626F3093B3B496C93CA
28    1999/00 004D2E4310F936F43F4D73B1BD31894B7273A1E30C1A028DAAC81939B9572966
29    1998/99 004FE0E78454FE677A07F1AD8D1226F61C6534E08B44EE01DC6C518FE2200DEA
30    1998/99 0050C79DAB376114E567D08BE22EA699565E600DFC9F3BD68705700FA49DE62C
⋮     ⋮       ⋮
17363 1998/99 FF7EFC3006B327BC644769B23FF20D6E4AFBD5EAE86EE2110BB9B3E1E7317740
17364 1998/99 FF87772E341BABD802077555E62FB0C28F67C988A30868E6E9F2DA6D557D7DF1
17365 1998/99 FF8A2758AC947462FBCFD2DCD8024A4EDC6A7C6B63C5E87AB1ABA8D7CF3DCCF0
17366 1999/00 FF8DEC4753882445FD9D524D7235E53252C52529C3B00C22A96D7C693BEEAC4C
17367 1999/00 FF8E8AF167DFF1BAF1D811D242FA37AF571E9F0D9A71C329110B911ED5BD0577
17368 1999/00 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
17369 1998/99 FF9EA711F52DA4D4DF1670062FB8E2C0AEB31E8FC6EB0797CC1A29644957872C
17370 1998/99 FFAB3C449F625A8B0527299C27FB85E818A99752883B172742E224652383116F
17371 1998/99 FFB4377E08770663A747BC594EB9DAB119751856BE2BFD42B18070EDC7F58420
17372 1998/99 FFB5122C6D8418A48E6FB924782900EF5E4605E4ECFD42FFB6C3119515E32C2F
17373 1998/99 FFB5635E90C51B5347572A1D06AD63844EBA1C885834A3FB3F09AE4CB361A019
17374 1998/99 FFB9583A0820E84F60A840CDB2D2E143E87A2BE0091320FEBFD0FC7A5C9A7C5B
17375 1998/99 FFBC13351F5A42EBF9E6A394DD518A4EF6363B0BBAEE35D691F457292C455ED8
17376 1998/99 FFBD6A3EECCC20370CAC11CC736BF0A4EC2CA96494106C8C26B3B565003833A7
17377 1998/99 FFBF093B81AF4B734782FF9C927D3A86B9581F52D2E18D059CC2DDBA97110CDA
17378 1998/99 FFC07EC8DFA7528E9E1C34B30490DC24EDC687B160DC3F750BB70DB3C45CA343
17379 1999/00 FFC53382EFC80944BF643197EFC665798C754FA8E41038787A7E7B316B99A75B
17380 1999/00 FFDE0350353E1B484F83298958E0F735D428D6B50E78471B87509497F4406002
17381 1998/99 FFE133B080FD044D5E6FDC0E74D7303B3D41419692A96B3E116D180FE9EB2F06
17382 1998/99 FFE244494ADA5394035640D578E70F7D57EBA5F67793F328CEF11B0B124491E2
17383 1999/00 FFE326BEEDD9B7453AA81BB7251D3F724AB1351CD2D45090955FC0B1EC4377EF
17384 1999/00 FFE326E526FAA00EF542D85A2BEBF681FB29C82A21EDA118DCD93D32035A203B
17385 1998/99 FFE8D30492571D5641B63115FFED00DE60D39E160D78483EC4E2BCE0A442F884
17386 1999/00 FFEBA230449490BA4B1BCEB1A68C790B1D85708DE8C6EAB8CD170D3E52F12775
17387 1998/99 FFEBA2A7088A41ADEF06DE231C6F48B615D19A0CA2D2FC917F432A964C9B2EA3
17388 1999/00 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
17389 1998/99 FFEF385FC541F397C34ACF193D6936D6BB045655B8781D7CFF18D632AAE9ED10
17390 1999/00 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB
17391 1999/00 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
17392 1998/99 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
      DOB        Gender Ethnicity     EAL ever_FSM ever_CIN DistCurrSch
1     1999-09-15 F      White British 0   0        FALSE     2.45
2     1999-08-15 F      White British 0   0        FALSE     4.71
3     1998-11-15 M      South Asian   0   0        FALSE     0.33
4     2000-05-15 M      White British 0   0        FALSE     1.78
5     2000-08-15 F      White British 0   1        FALSE     0.76
6     1999-09-15 M      South Asian   0   1         TRUE     1.29
7     1999-01-15 F      South Asian   0   1         TRUE     1.37
8     1998-10-15 M      White British 0   1         TRUE     4.27
9     1999-03-15 M      White British 0   0        FALSE     0.10
10    1999-07-15 F      Other         1   1         TRUE     2.74
11    1999-06-15 M      White British 0   1        FALSE     0.47
12    2000-04-15 M      South Asian   1   1        FALSE     1.13
13    2000-01-15 M      Other         0   1        FALSE     1.23
14    1998-09-15 F      White British 0   0        FALSE     0.61
15    1999-08-15 F      South Asian   1   1        FALSE     0.61
16    1999-05-15 F      White British 0   1        FALSE     6.72
17    1998-09-15 M      White British 0   1        FALSE     1.05
18    1999-08-15 M      Other         0   0        FALSE     0.35
19    2000-06-15 F      South Asian   0   0        FALSE     0.68
20    1998-12-15 F      White British 0   0        FALSE     1.48
21    1999-07-15 M      White British 0   1         TRUE     0.53
22    1999-07-15 M      White British 0   1         TRUE     4.99
23    1999-11-15 M      South Asian   1   0        FALSE     2.06
24    2000-01-15 F      White British 0   0        FALSE     1.29
25    2000-03-15 F      White British 0   0        FALSE     1.25
26    1999-11-15 M      White British 0   0        FALSE     3.18
27    2000-08-15 F      White British 0   1         TRUE     0.62
28    2000-08-15 F      South Asian   0   0        FALSE    12.70
29    1999-06-15 F      South Asian   1   0        FALSE     1.91
30    1999-06-15 M      White British 0   0        FALSE     0.77
⋮     ⋮          ⋮      ⋮             ⋮   ⋮        ⋮        ⋮
17363 1999-05-15 M      South Asian   1   0        FALSE    2.33
17364 1998-11-15 F      South Asian   1   0        FALSE    5.25
17365 1999-03-15 M      White British 0   0        FALSE    0.54
17366 2000-01-15 F      White British 0   0        FALSE    0.83
17367 2000-02-15 F      South Asian   1   0        FALSE    0.62
17368 1999-10-15 F      White British 0   1         TRUE    2.02
17369 1998-11-15 F      White British 0   0        FALSE    2.47
17370 1999-06-15 F      White British 0   0        FALSE    0.75
17371 1999-05-15 F      White British 0   1         TRUE    3.13
17372 1999-01-15 F      White British 0   1         TRUE    1.09
17373 1999-04-15 M      South Asian   0   0        FALSE    1.03
17374 1999-01-15 F      South Asian   1   1        FALSE    3.05
17375 1999-08-15 M      Other         1   1        FALSE    1.99
17376 1998-12-15 F      South Asian   1   1        FALSE    0.25
17377 1999-04-15 M      South Asian   0   0        FALSE    0.37
17378 1999-05-15 M      South Asian   1   0        FALSE    0.71
17379 2000-05-15 M      White British 0   0        FALSE    2.62
17380 2000-06-15 F      Other         0   0         TRUE    3.78
17381 1999-07-15 F      Other         0   0        FALSE    0.39
17382 1999-02-15 F      White British 0   0        FALSE    0.40
17383 1999-12-15 M      White British 0   1         TRUE    1.20
17384 2000-05-15 F      White British 0   1        FALSE    0.22
17385 1999-02-15 M      White British 0   1        FALSE    4.40
17386 2000-05-15 F      White British 0   1        FALSE    3.18
17387 1999-05-15 F      White British 0   0        FALSE    7.77
17388 1999-11-15 M      South Asian   0   1         TRUE    0.87
17389 1999-07-15 M      White British 0   0        FALSE    1.27
17390 2000-03-15 M      Other         1   1        FALSE    1.35
17391 2000-02-15 M      White British 0   0        FALSE    0.35
17392 1999-07-15 F      White British 0   0        FALSE    5.57
      LSOA11_Home ⋯ AuthorisedAbsenceRate UnauthorisedAbsenceRate
1     E01027555   ⋯  1.8739353             0.0000000
2     E01010703   ⋯  9.1124260             0.3550296
3     E01010742   ⋯  1.6636958             0.0000000
4     E01010641   ⋯  1.7045455             0.0000000
5     E01010655   ⋯  1.2055109            15.1549943
6     E01010626   ⋯ 12.6002291             0.0000000
7     E01010568   ⋯  6.3170441             0.1191895
8     E01010752   ⋯  6.9892473            24.2703533
9     E01027577   ⋯  3.2816229             1.0739857
10    E01010625   ⋯  9.1726619            19.4244604
11    E01011330   ⋯  5.1143201             0.2406739
12    E01010710   ⋯  2.9192547             3.7267081
13    E01011792   ⋯ 10.3092784             4.1237113
14    E01010579   ⋯  5.1466188             0.2393776
15    E01010663   ⋯ 18.2846933             0.4169148
16    E01019350   ⋯  5.7401813             0.8459215
17    E01015222   ⋯  1.7789072             0.0000000
18    E01011541   ⋯  1.7804154             0.0000000
19    E01010738   ⋯  0.6876791             0.8022923
20    E01010764   ⋯  5.7841383             0.0000000
21    E01010734   ⋯  0.8303677             0.3558719
22    E01010795   ⋯  4.0837696            16.6492147
23    E01010793   ⋯  0.1223990             0.1835985
24    E01010706   ⋯  6.9794050             0.4004577
25    E01010790   ⋯  1.2614679             0.0000000
26    E01010967   ⋯  7.6349024             9.5866820
27    E01010802   ⋯ 10.8721625             1.6726404
28    E01010772   ⋯  3.1800114             0.0000000
29    E01010613   ⋯  2.1008403             0.4801921
30    E01010580   ⋯  8.6774387             0.0000000
⋮     ⋮           ⋱ ⋮                     ⋮
17363 E01010665   ⋯  8.1162932             0.54512417
17364 E01016415   ⋯  1.8485391             0.11926058
17365 E01010603   ⋯  2.4463007             1.78997613
17366 E01010591   ⋯  2.8669725             0.68807339
17367 E01002609   ⋯  5.0770108             1.76839703
17368 E01011473   ⋯  3.9013196             2.98336202
17369 E01010750   ⋯  3.1954887             1.00250627
17370 E01010694   ⋯  3.2953865             0.05991612
17371 E01010816   ⋯  1.1663597             0.00000000
17372 E01010720   ⋯  2.0995801             6.59868026
17373 E01010835   ⋯  3.6614646             0.00000000
17374 E01010842   ⋯  2.6714159             0.89047195
17375 E01010734   ⋯  3.5287081             3.40909091
17376 E01010607   ⋯  3.4119107             5.58312655
17377 E01010719   ⋯  2.3180940             0.77269800
17378 E01015665   ⋯  5.6422569             0.66026411
17379 E01027560   ⋯  1.4772727             0.00000000
17380 E01010702   ⋯ 19.5011338             0.00000000
17381 E01010731   ⋯  0.1188354             0.00000000
17382 E01010614   ⋯  5.6648778             0.17889088
17383 E01010827   ⋯  1.6018307             0.00000000
17384 E01022024   ⋯  0.4597701             0.00000000
17385 E01010754   ⋯  8.1802015             0.77059870
17386 E01010775   ⋯ 10.5747126             2.35632184
17387 E01027834   ⋯  2.2686567             0.00000000
17388 E01010947   ⋯  2.6887872             0.85812357
17389 E01010758   ⋯  1.0676157             0.00000000
17390 E01026960   ⋯  5.6577086            15.41725601
17391 E01027585   ⋯  4.0114613             0.17191977
17392 E01010816   ⋯  2.2619048             0.05952381
      TotalAbsenceRate Suspensions SuspensionSessions Exclusions KS4_Entries
1      1.8739353       0            0                 0          20
2      9.4674556       0            0                 0          13
3      1.6636958       0            0                 0          18
4      1.7045455       0            0                 0          15
5     16.3605052       0            0                 0          13
6     12.6002291       0            0                 0          14
7      6.4362336       0            0                 0          13
8     31.2596006       5           30                 0           4
9      4.3556086       0            0                 0          14
10    28.5971223       0            0                 0          10
11     5.3549940       0            0                 0          16
12     6.6459627       1           10                 0          12
13    14.4329897       0            0                 0          13
14     5.3859964       0            0                 0          13
15    18.7016081       0            0                 0          12
16     6.5861027       0            0                 0          13
17     1.7789072       0            0                 0          15
18     1.7804154       0            0                 0          14
19     1.4899713       0            0                 0          13
20     5.7841383       0            0                 0          14
21     1.1862396       0            0                 0          15
22    20.7329843       6           14                 0           3
23     0.3059976       0            0                 0          15
24     7.3798627       0            0                 0          17
25     1.2614679       0            0                 0          12
26    17.2215844       0            0                 0          14
27    12.5448029       1            6                 0          11
28     3.1800114       0            0                 0          17
29     2.5810324       0            0                 0          14
30     8.6774387       0            0                 0          17
⋮     ⋮                ⋮           ⋮                  ⋮          ⋮
17363  8.6614173       2           6                  0          13
17364  1.9677996       0           0                  0          16
17365  4.2362768       0           0                  0          17
17366  3.5550459       0           0                  0          12
17367  6.8454079       0           0                  0          13
17368  6.8846816       0           0                  0          12
17369  4.1979950       0           0                  0          14
17370  3.3553026       0           0                  0          14
17371  1.1663597       0           0                  0          13
17372  8.6982603       1           6                  0          15
17373  3.6614646       0           0                  0          10
17374  3.5618878       0           0                  0          16
17375  6.9377990       0           0                  0          12
17376  8.9950372       0           0                  0          11
17377  3.0907920       0           0                  0          12
17378  6.3025210       0           0                  0          22
17379  1.4772727       0           0                  0          12
17380 19.5011338       0           0                  0          12
17381  0.1188354       0           0                  0          11
17382  5.8437686       0           0                  0          14
17383  1.6018307       0           0                  0          10
17384  0.4597701       0           0                  0          12
17385  8.9508002       0           0                  0          16
17386 12.9310345       0           0                  0          11
17387  2.2686567       0           0                  0          11
17388  3.5469108       0           0                  0          14
17389  1.0676157       0           0                  0          14
17390 21.0749646       2           3                  0          10
17391  4.1833811       0           0                  0          13
17392  2.3214286       0           0                  0          13
      KS4_Passes_Level1 KS4_Passes_Level2 Destination
1     14.0              14.0              Steady EET
2      8.0               3.0              Steady EET
3     15.0              15.0              DROP
4     12.0              12.0              Steady EET
5      7.0               1.0              Risky trajectory
6     11.0              10.0              Steady EET
7      8.0               2.0              DROP
8      0.0               0.0              Steady EET
9      9.7               9.7              DROP
10     2.0               0.0              Risky trajectory
11    12.0              11.0              Steady EET
12     6.0               2.0              Steady EET
13     8.0               3.0              Steady EET
14     7.0               5.0              Steady EET
15     9.0               4.0              Steady EET
16    10.0               6.0              DROP
17    12.0               6.0              Steady EET
18    12.0              11.0              Steady EET
19    10.0              10.0              Steady EET
20    10.0               5.0              Steady EET
21    10.0               8.0              DROP
22     0.0               0.0              Risky trajectory
23    11.0               3.0              Steady EET
24    11.0              11.0              Steady EET
25     9.0               8.0              Steady EET
26    10.0              10.0              Steady EET
27     8.0               1.0              Steady EET
28    13.0              13.0              Steady EET
29    10.0               6.0              Steady EET
30     9.0               8.0              Steady EET
⋮     ⋮                 ⋮                 ⋮
17363 10                 2                DROP
17364 10                 7                DROP
17365 10                 7                DROP
17366  9                 9                Steady EET
17367  9                 2                Steady EET
17368 10                 2                Risky trajectory
17369 11                 9                DROP
17370  9                 9                DROP
17371 10                 9                DROP
17372  8                 1                DROP
17373  6                 0                Steady EET
17374 11                10                Steady EET
17375  9                 0                Steady EET
17376  9                 6                Steady EET
17377  8                 0                DROP
17378 10                10                Steady EET
17379  8                 2                Steady EET
17380 10                 4                DROP
17381 10                 5                DROP
17382 10                 6                Steady EET
17383  7                 3                Steady EET
17384  8                 5                Steady EET
17385  7                 1                Steady EET
17386  8                 0                Steady EET
17387  8                 3                DROP
17388 11                11                Steady EET
17389 11                10                DROP
17390  7                 0                Steady EET
17391 11                11                Steady EET
17392  7                 6                Steady EET

# Enrolments

In [90]:
enrolments <- read.csv("data/additional_enrolment_wide.csv", header = TRUE)

In [91]:
head(enrolments)

  person_id                                                        NCCIS_ACADYR
1 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2016/2017
2 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 2015/2016
3 000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909 2015/2016
4 00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC 2016/2017
5 0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D 2016/2017
6 00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7 2016/2017
  Y2011.2012_Term1 Y2011.2012_Term2 Y2011.2012_Term3 Y2012.2013_Term1
1 136664           136664           136664           136664
2 136736           136736           136736           136736
3 130909           130909           130909           130909
4 136736           136736           136736           136736
5 107440           107440           107440           107440
6 108087           108087           108087           108087
  Y2012.2013_Term2 Y2012.2013_Term3 Y2013.2014_Term1 Y2013.2014_Term2
1 136664           136664           136664           136664
2 136736           136736           136736           136736
3 130909           130909           130909           130909
4 136736           136736           136736           136736
5 107440           107440           107440           107440
6 108087           108087           108087           108087
  Y2013.2014_Term3 Y2014.2015_Term1 Y2014.2015_Term2 Y2014.2015_Term3
1 136664           136664           136664           136664
2 136736           136736           136736           136736
3 130909           130909           130909           130909
4 136736           136736           136736           136736
5 107440           107440           107440           107440
6 108087           108087           108087           108087
  Y2015.2016_Term1 Y2015.2016_Term2 Y2015.2016_Term3 Y2010.2011_Term1
1 136664           136664           136664               NA
2     NA               NA               NA           136736
3     NA               NA               NA           130909
4 136736           136736           136736               NA
5 107440           107440           107440               NA
6 108087           108087           108087               NA
  Y2010.2011_Term2 Y2010.2011_Term3
1     NA               NA
2 136736           136736
3 130909           130909
4     NA               NA
5     NA               NA
6     NA               NA

In [92]:
enrolments <- enrolments |>
    select(-NCCIS_ACADYR) |>
    mutate(across(everything(), as.character))

In [93]:
person_absence_cin_excl_ks4_dest_enrol <- person_absence_cin_excl_ks4_dest_clean |>
    left_join(enrolments, by = 'person_id')

In [94]:
person_absence_cin_excl_ks4_dest_enrol

      cohort  person_id
1     1999/00 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
2     1998/99 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
3     1998/99 000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909
4     1999/00 00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC
5     1999/00 0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
6     1999/00 00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7
7     1998/99 001F42538A9E6E496F13CD05B5E9FE91EB3B20F0CEBECA1B76CC5E7151B7A0D4
8     1998/99 00211975518FD5336E43850D59B5F5DDA7CD98B212760111CB40528BDECF3B1B
9     1998/99 00237E9C21696BB29409630166F2D9CCEC24B83FB120AEDD878DDD54C6516B3D
10    1998/99 00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9
11    1998/99 0025102C0D8E8C5F27454E3715E982A43E1431991E85562E55BCB19D9D1BD7D3
12    1999/00 0025514088C52FB45B7439689844A1FEA2FB8B2753994F432CC7DDC68036BD59
13    1999/00 00269FAEA8B5167F1239AA166C20B7673380CCB3E5F3E2F1F6FAA6034A11CE88
14    1998/99 0026BFA5D5426F421200AB505AAD52956621DCC253241A6647302BCE4764547D
15    1998/99 002D3DB2625339C740EB129CCC925A9D90E4F5AA05561B81FE166EDF990B8F65
16    1998/99 002E7A9E65A6A184952E4F1811844FCFCCE758FAE60986A1F9B9C9892FD0895D
17    1998/99 003196BCDC325A98F118130F185DF8FDDE1B8E1E4882719DAE198B2908F03A5B
18    1998/99 0032202712FAB3A372409235FFE3C0486E36F9B2FB9C9C9851B4ACAB9A3330F0
19    1999/00 0037E941FE88C2503AF508B5306803DB1693F3200533648162692820D1EA221D
20    1998/99 0043C7C252748432DF62E306CCC2DFF568A52DC78D4021140E3C4676C9D65A7E
21    1998/99 00450DFB52E0DDD50F5800AD149075B29E4A1454F36B9ACF2E106CF44B9BED55
22    1998/99 0045ADA48CA299BC4445318E8D951610DCB89A829665CFC821E92340F0F8B30D
23    1999/00 0046475B3089CF6E67A50BBAB6ACC4D6C7FA957BEE68B7F8365239D87857F197
24    1999/00 0046A4A849F346DFC497329C2BEE0509FAC101F8F4683542D6B453D1C10156BE
25    1999/00 004AA9D5C19D6B421D63DF6E9FB8BA6C671707143EF6FD6794AC73DE319156B0
26    1999/00 004CD18444BDD86E6C7F4BE1EE806175325E95085AEBC68E7CAA36A747BD2824
27    1999/00 004D0B5FF90E252B2912022950FEC4929A1ACB81BA61A626F3093B3B496C93CA
28    1999/00 004D2E4310F936F43F4D73B1BD31894B7273A1E30C1A028DAAC81939B9572966
29    1998/99 004FE0E78454FE677A07F1AD8D1226F61C6534E08B44EE01DC6C518FE2200DEA
30    1998/99 0050C79DAB376114E567D08BE22EA699565E600DFC9F3BD68705700FA49DE62C
⋮     ⋮       ⋮
17363 1998/99 FF7EFC3006B327BC644769B23FF20D6E4AFBD5EAE86EE2110BB9B3E1E7317740
17364 1998/99 FF87772E341BABD802077555E62FB0C28F67C988A30868E6E9F2DA6D557D7DF1
17365 1998/99 FF8A2758AC947462FBCFD2DCD8024A4EDC6A7C6B63C5E87AB1ABA8D7CF3DCCF0
17366 1999/00 FF8DEC4753882445FD9D524D7235E53252C52529C3B00C22A96D7C693BEEAC4C
17367 1999/00 FF8E8AF167DFF1BAF1D811D242FA37AF571E9F0D9A71C329110B911ED5BD0577
17368 1999/00 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
17369 1998/99 FF9EA711F52DA4D4DF1670062FB8E2C0AEB31E8FC6EB0797CC1A29644957872C
17370 1998/99 FFAB3C449F625A8B0527299C27FB85E818A99752883B172742E224652383116F
17371 1998/99 FFB4377E08770663A747BC594EB9DAB119751856BE2BFD42B18070EDC7F58420
17372 1998/99 FFB5122C6D8418A48E6FB924782900EF5E4605E4ECFD42FFB6C3119515E32C2F
17373 1998/99 FFB5635E90C51B5347572A1D06AD63844EBA1C885834A3FB3F09AE4CB361A019
17374 1998/99 FFB9583A0820E84F60A840CDB2D2E143E87A2BE0091320FEBFD0FC7A5C9A7C5B
17375 1998/99 FFBC13351F5A42EBF9E6A394DD518A4EF6363B0BBAEE35D691F457292C455ED8
17376 1998/99 FFBD6A3EECCC20370CAC11CC736BF0A4EC2CA96494106C8C26B3B565003833A7
17377 1998/99 FFBF093B81AF4B734782FF9C927D3A86B9581F52D2E18D059CC2DDBA97110CDA
17378 1998/99 FFC07EC8DFA7528E9E1C34B30490DC24EDC687B160DC3F750BB70DB3C45CA343
17379 1999/00 FFC53382EFC80944BF643197EFC665798C754FA8E41038787A7E7B316B99A75B
17380 1999/00 FFDE0350353E1B484F83298958E0F735D428D6B50E78471B87509497F4406002
17381 1998/99 FFE133B080FD044D5E6FDC0E74D7303B3D41419692A96B3E116D180FE9EB2F06
17382 1998/99 FFE244494ADA5394035640D578E70F7D57EBA5F67793F328CEF11B0B124491E2
17383 1999/00 FFE326BEEDD9B7453AA81BB7251D3F724AB1351CD2D45090955FC0B1EC4377EF
17384 1999/00 FFE326E526FAA00EF542D85A2BEBF681FB29C82A21EDA118DCD93D32035A203B
17385 1998/99 FFE8D30492571D5641B63115FFED00DE60D39E160D78483EC4E2BCE0A442F884
17386 1999/00 FFEBA230449490BA4B1BCEB1A68C790B1D85708DE8C6EAB8CD170D3E52F12775
17387 1998/99 FFEBA2A7088A41ADEF06DE231C6F48B615D19A0CA2D2FC917F432A964C9B2EA3
17388 1999/00 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
17389 1998/99 FFEF385FC541F397C34ACF193D6936D6BB045655B8781D7CFF18D632AAE9ED10
17390 1999/00 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB
17391 1999/00 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
17392 1998/99 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
      DOB        Gender Ethnicity     EAL ever_FSM ever_CIN DistCurrSch
1     1999-09-15 F      White British 0   0        FALSE     2.45
2     1999-08-15 F      White British 0   0        FALSE     4.71
3     1998-11-15 M      South Asian   0   0        FALSE     0.33
4     2000-05-15 M      White British 0   0        FALSE     1.78
5     2000-08-15 F      White British 0   1        FALSE     0.76
6     1999-09-15 M      South Asian   0   1         TRUE     1.29
7     1999-01-15 F      South Asian   0   1         TRUE     1.37
8     1998-10-15 M      White British 0   1         TRUE     4.27
9     1999-03-15 M      White British 0   0        FALSE     0.10
10    1999-07-15 F      Other         1   1         TRUE     2.74
11    1999-06-15 M      White British 0   1        FALSE     0.47
12    2000-04-15 M      South Asian   1   1        FALSE     1.13
13    2000-01-15 M      Other         0   1        FALSE     1.23
14    1998-09-15 F      White British 0   0        FALSE     0.61
15    1999-08-15 F      South Asian   1   1        FALSE     0.61
16    1999-05-15 F      White British 0   1        FALSE     6.72
17    1998-09-15 M      White British 0   1        FALSE     1.05
18    1999-08-15 M      Other         0   0        FALSE     0.35
19    2000-06-15 F      South Asian   0   0        FALSE     0.68
20    1998-12-15 F      White British 0   0        FALSE     1.48
21    1999-07-15 M      White British 0   1         TRUE     0.53
22    1999-07-15 M      White British 0   1         TRUE     4.99
23    1999-11-15 M      South Asian   1   0        FALSE     2.06
24    2000-01-15 F      White British 0   0        FALSE     1.29
25    2000-03-15 F      White British 0   0        FALSE     1.25
26    1999-11-15 M      White British 0   0        FALSE     3.18
27    2000-08-15 F      White British 0   1         TRUE     0.62
28    2000-08-15 F      South Asian   0   0        FALSE    12.70
29    1999-06-15 F      South Asian   1   0        FALSE     1.91
30    1999-06-15 M      White British 0   0        FALSE     0.77
⋮     ⋮          ⋮      ⋮             ⋮   ⋮        ⋮        ⋮
17363 1999-05-15 M      South Asian   1   0        FALSE    2.33
17364 1998-11-15 F      South Asian   1   0        FALSE    5.25
17365 1999-03-15 M      White British 0   0        FALSE    0.54
17366 2000-01-15 F      White British 0   0        FALSE    0.83
17367 2000-02-15 F      South Asian   1   0        FALSE    0.62
17368 1999-10-15 F      White British 0   1         TRUE    2.02
17369 1998-11-15 F      White British 0   0        FALSE    2.47
17370 1999-06-15 F      White British 0   0        FALSE    0.75
17371 1999-05-15 F      White British 0   1         TRUE    3.13
17372 1999-01-15 F      White British 0   1         TRUE    1.09
17373 1999-04-15 M      South Asian   0   0        FALSE    1.03
17374 1999-01-15 F      South Asian   1   1        FALSE    3.05
17375 1999-08-15 M      Other         1   1        FALSE    1.99
17376 1998-12-15 F      South Asian   1   1        FALSE    0.25
17377 1999-04-15 M      South Asian   0   0        FALSE    0.37
17378 1999-05-15 M      South Asian   1   0        FALSE    0.71
17379 2000-05-15 M      White British 0   0        FALSE    2.62
17380 2000-06-15 F      Other         0   0         TRUE    3.78
17381 1999-07-15 F      Other         0   0        FALSE    0.39
17382 1999-02-15 F      White British 0   0        FALSE    0.40
17383 1999-12-15 M      White British 0   1         TRUE    1.20
17384 2000-05-15 F      White British 0   1        FALSE    0.22
17385 1999-02-15 M      White British 0   1        FALSE    4.40
17386 2000-05-15 F      White British 0   1        FALSE    3.18
17387 1999-05-15 F      White British 0   0        FALSE    7.77
17388 1999-11-15 M      South Asian   0   1         TRUE    0.87
17389 1999-07-15 M      White British 0   0        FALSE    1.27
17390 2000-03-15 M      Other         1   1        FALSE    1.35
17391 2000-02-15 M      White British 0   0        FALSE    0.35
17392 1999-07-15 F      White British 0   0        FALSE    5.57
      LSOA11_Home ⋯ Y2013.2014_Term3 Y2014.2015_Term1 Y2014.2015_Term2
1     E01027555   ⋯ 136664           136664           136664
2     E01010703   ⋯ 136736           136736           136736
3     E01010742   ⋯ 130909           130909           130909
4     E01010641   ⋯ 136736           136736           136736
5     E01010655   ⋯ 107440           107440           107440
6     E01010626   ⋯ 108087           108087           108087
7     E01010568   ⋯ 107395           107395           107395
8     E01010752   ⋯ 135732           135732           135732
9     E01027577   ⋯ 121716           121716           121716
10    E01010625   ⋯ 107366           107366           107366
11    E01011330   ⋯ 135935           135935           135935
12    E01010710   ⋯ 107441           107441           107441
13    E01011792   ⋯ 137001           137001           137001
14    E01010579   ⋯ 107439           107439           107439
15    E01010663   ⋯ 139982           139982           139982
16    E01019350   ⋯ 137338           137338           137338
17    E01015222   ⋯ 138863           138863           138863
18    E01011541   ⋯ 136392           136392           136392
19    E01010738   ⋯ 139982           139982           139982
20    E01010764   ⋯ 139975           139975           139975
21    E01010734   ⋯ 135367           135367           135367
22    E01010795   ⋯ 138099           131772           131772
23    E01010793   ⋯ 137576           137576           137576
24    E01010706   ⋯ 107439           107439           107439
25    E01010790   ⋯ 139975           139975           139975
26    E01010967   ⋯ 137036           137036           137036
27    E01010802   ⋯ 107442           107442           107442
28    E01010772   ⋯ 136664           136664           136664
29    E01010613   ⋯ 107366           107366           107366
30    E01010580   ⋯ 107439           107439           107439
⋮     ⋮           ⋱ ⋮                ⋮                ⋮
17363 E01010665   ⋯ 107391           107391           107391
17364 E01016415   ⋯ 136880           136880           136880
17365 E01010603   ⋯ 107440           107440           107440
17366 E01010591   ⋯ 139975           139975           139975
17367 E01002609   ⋯ 136103           136103           136103
17368 E01011473   ⋯ 108097           108097           108097
17369 E01010750   ⋯ 107780           107780           107780
17370 E01010694   ⋯ 136905           136905           136905
17371 E01010816   ⋯ 137487           137487           137487
17372 E01010720   ⋯ 107441           107441           107441
17373 E01010835   ⋯ 139982           139982           139982
17374 E01010842   ⋯ 137576           137576           137576
17375 E01010734   ⋯ 107366           107366           107366
17376 E01010607   ⋯ 107413           107413           107413
17377 E01010719   ⋯ 107428           107428           107428
17378 E01015665   ⋯ 110899           110899           110899
17379 E01027560   ⋯ 136736           136736           136736
17380 E01010702   ⋯ 136736           136736           136736
17381 E01010731   ⋯ 130909           130909           130909
17382 E01010614   ⋯ 135367           135367           135367
17383 E01010827   ⋯ 107440           107440           107440
17384 E01022024   ⋯ 135957           135957           135957
17385 E01010754   ⋯ 136604           136604           136604
17386 E01010775   ⋯ 139975           139975           139975
17387 E01027834   ⋯ 121714           121714           121714
17388 E01010947   ⋯ 137444           137444           137444
17389 E01010758   ⋯ 136788           136788           136788
17390 E01026960   ⋯ 139060           139060           139060
17391 E01027585   ⋯ 121690           121690           121690
17392 E01010816   ⋯ 107783           107783           107783
      Y2014.2015_Term3 Y2015.2016_Term1 Y2015.2016_Term2 Y2015.2016_Term3
1     136664           136664           136664           136664
2     136736           NA               NA               NA
3     130909           NA               NA               NA
4     136736           136736           136736           136736
5     107440           107440           107440           107440
6     108087           108087           108087           108087
7     107395           NA               NA               NA
8     135732           NA               NA               NA
9     121716           NA               NA               NA
10    107366           NA               NA               NA
11    135935           NA               NA               NA
12    107441           107441           107441           107441
13    137001           137001           137001           137001
14    107439           NA               NA               NA
15    139982           NA               NA               NA
16    137338           NA               NA               NA
17    138863           NA               NA               NA
18    136392           NA               NA               NA
19    139982           139982           139982           139982
20    139975           NA               NA               NA
21    135367           NA               NA               NA
22    131772           NA               NA               NA
23    137576           137576           137576           137576
24    107439           107439           107439           107439
25    139975           139975           139975           139975
26    137036           137036           137036           137036
27    107442           107442           107442           107442
28    136664           136664           136664           136664
29    107366           NA               NA               NA
30    107439           NA               NA               NA
⋮     ⋮                ⋮                ⋮                ⋮
17363 107391           NA               NA               NA
17364 136880           NA               NA               NA
17365 107440           NA               NA               NA
17366 139975           139975           139975           139975
17367 136103           136103           136103           136103
17368 108097           108097           108097           108097
17369 107780           NA               NA               NA
17370 136905           NA               NA               NA
17371 137487           NA               NA               NA
17372 107441           NA               NA               NA
17373 139982           NA               NA               NA
17374 137576           NA               NA               NA
17375 107366           NA               NA               NA
17376 107413           NA               NA               NA
17377 107428           NA               NA               NA
17378 110899           NA               NA               NA
17379 136736           136736           136736           136736
17380 136736           136736           136736           136736
17381 130909           NA               NA               NA
17382 135367           NA               NA               NA
17383 107440           107440           107440           107440
17384 135957           135957           135957           135957
17385 136604           NA               NA               NA
17386 139975           139975           139975           139975
17387 121714           NA               NA               NA
17388 137444           137444           137444           137444
17389 136788           NA               NA               NA
17390 139060           139060           139060           139060
17391 121690           121690           121690           121690
17392 107783           NA               NA               NA
      Y2010.2011_Term1 Y2010.2011_Term2 Y2010.2011_Term3
1     NA               NA               NA
2     136736           136736           136736
3     130909           130909           130909
4     NA               NA               NA
5     NA               NA               NA
6     NA               NA               NA
7     107395           107395           107395
8     107391           107391           107391
9     121716           121716           121716
10    132219           132219           132219
11    135935           135935           135935
12    NA               NA               NA
13    NA               NA               NA
14    107439           107439           107439
15    107414           107414           107414
16    107768           107768           107768
17    113528           113528           113528
18    136392           136392           136392
19    NA               NA               NA
20    107386           107386           107386
21    135367           135367           135367
22    107366           107366           107366
23    NA               NA               NA
24    NA               NA               NA
25    NA               NA               NA
26    NA               NA               NA
27    NA               NA               NA
28    NA               NA               NA
29    107366           107366           107366
30    107439           107439           107439
⋮     ⋮                ⋮                ⋮
17363 107391           107391           107391
17364 110096           110096           110096
17365 107440           107440           107440
17366 NA               NA               NA
17367 NA               NA               NA
17368 NA               NA               NA
17369 107772           107772           107772
17370 NA               NA               NA
17371 107755           107755           107755
17372 107441           107441           107441
17373 107297           107297           107297
17374 NA               NA               NA
17375 107366           107366           107366
17376 107413           107413           107413
17377 107428           107428           107428
17378 110899           110899           110899
17379 NA               NA               NA
17380 NA               NA               NA
17381 130909           130909           130909
17382 135367           135367           135367
17383 NA               NA               NA
17384 NA               NA               NA
17385 136604           136604           136604
17386 NA               NA               NA
17387 121714           121714           121714
17388 NA               NA               NA
17389 NA               NA               NA
17390 NA               NA               NA
17391 NA               NA               NA
17392 107783           107783           107783

# Ever AP/PRU

In [95]:
ever_AP <- read.csv("data/additional_ever_AP_ids.csv", header = TRUE)

In [96]:
head(ever_AP)

  person_id                                                        ever_AP
1 B891969D99CBDDFD25843650004166B78065AA19286746C38AC2C2BDCC9DF517 TRUE
2 8B0EF0EF12A6FC021D4C25CEEEFE5B40E652B6391509975634A16AE4693F9EED TRUE
3 2FD320DE2176D0875426B78D75636E1B998C566B5C6C5BE10686578EEC52ADD8 TRUE
4 09CAD5FFBCC56CEF7C8F4F6B461E0B27AF9B4432AF9F2616069CB27BB5F16611 TRUE
5 2C160E1145CBD3E2FC154D967298692B14D4623286F73E86F2970B408EBF018C TRUE
6 1E430896DDAE48DE8494FF0C06E5A3C5D385456DE311B49F7C155BA3502D86DE TRUE

In [97]:
person_absence_cin_excl_ks4_dest_enrol_ap <- person_absence_cin_excl_ks4_dest_enrol |>
    left_join(ever_AP, by=join_by(person_id))

In [98]:
person_absence_cin_excl_ks4_dest_enrol_ap <- person_absence_cin_excl_ks4_dest_enrol_ap |>
    mutate(ever_AP = case_when(
            ever_AP ~ TRUE,
            TRUE ~ FALSE)
           )

In [99]:
head(person_absence_cin_excl_ks4_dest_enrol_ap)

  cohort  person_id
1 1999/00 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
2 1998/99 00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
3 1998/99 000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909
4 1999/00 00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC
5 1999/00 0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
6 1999/00 00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7
  DOB        Gender Ethnicity     EAL ever_FSM ever_CIN DistCurrSch LSOA11_Home
1 1999-09-15 F      White British 0   0        FALSE    2.45        E01027555
2 1999-08-15 F      White British 0   0        FALSE    4.71        E01010703
3 1998-11-15 M      South Asian   0   0        FALSE    0.33        E01010742
4 2000-05-15 M      White British 0   0        FALSE    1.78        E01010641
5 2000-08-15 F      White British 0   1        FALSE    0.76        E01010655
6 1999-09-15 M      South Asian   0   1         TRUE    1.29        E01010626
  ⋯ Y2014.2015_Term1 Y2014.2015_Term2 Y2014.2015_Term3 Y2015.2016_Term1
1 ⋯ 136664           136664           136664           136664
2 ⋯ 136736           136736           136736           NA
3 ⋯ 130909           130909           130909           NA
4 ⋯ 136736           136736           136736           136736
5 ⋯ 107440           107440           107440           107440
6 ⋯ 108087           108087           108087           108087
  Y2015.2016_Term2 Y2015.2016_Term3 Y2010.2011_Term1 Y2010.2011_Term2
1 136664           136664           NA               NA
2 NA               NA               136736           136736
3 NA               NA               130909           130909
4 136736           136736           NA               NA
5 107440           107440           NA               NA
6 108087           108087           NA               NA
  Y2010.2011_Term3 ever_AP
1 NA               FALSE
2 136736           FALSE
3 130909           FALSE
4 NA               FALSE
5 NA               FALSE
6 NA               FALSE

In [100]:
# save as csv
write.csv(person_absence_cin_excl_ks4_dest_enrol_ap, "data/additional_full_data.csv", row.names = FALSE)