In [426]:
library(tidyverse)
library(dbplyr)
library(bigrquery)
library(lubridate)

bq_auth()

project_id = "yhcr-prd-bradfor-bia-core"

# create connection to database
con <- DBI::dbConnect(bigrquery::bigquery(), 
                      project = project_id)

print(paste0("Connected to : ", project_id))

[1] "Connected to : yhcr-prd-bradfor-bia-core"

#### Read in data and collect tables

In [427]:
person_ids <- read.csv('data/person_ids.csv', header = TRUE)

In [428]:
school_data = "CB_2489.cb_InstitutionHistory"

In [429]:
school_match = "CB_2489.cb_School"

In [430]:
school_link_data = "CB_2489.cb_InstitutionLink"

In [431]:
enrol_data = "CB_2489.cb_Enrollment"

In [432]:
school_match_table <- tbl(con, school_match) |>
    select(SchoolID, URN
           )

In [433]:
enrol_table <- tbl(con, enrol_data) |>
    select(person_id, SchoolID, AcademicYear, 
           OnRoll_1, OnRoll_2, OnRoll_3, 
           EnrolStatus, EntryDate, LeavingDate, PartTime
           )

In [434]:
school_table <- tbl(con, school_data) |>
    select(InstitutionHistoryID, InstitutionID, AcademicYear,
           InstitutionTypeDesc, URN, SchoolName,
           PhaseOfEducationDesc
           )

In [435]:
school_link_table <- tbl(con, school_link_data) |>
    select(InstitutionLinkID, InstitutionHistoryID, AcademicYear,
           person_id
           )

In [436]:
school_match_df <- collect(school_match_table)

In [437]:
head(school_match_df)

  SchoolID URN
1  3978    108234
2  1935    108274
3 21112    108314
4 11201    108189
5 14610    139568
6  3644    108238

In [438]:
school_match <- school_match_df |>
    filter(SchoolID %in% c(cohort_schools))

In [439]:
head(school_match)

  SchoolID URN
1  1935    108274
2   749    108275
3   724    108297
4  2611    108299
5  2238    108279
6 11068    135961

In [440]:
enrol_df <- collect(enrol_table)

In [441]:
school_df <- collect(school_table)

In [442]:
school_link_df <- collect(school_link_table)

In [443]:
school_link_filtered <- school_link_df |>
    filter(person_id %in% person_ids$person_id)

In [444]:
school_link_filtered

     InstitutionLinkID InstitutionHistoryID AcademicYear person_id

#### Filter enrolments table to target cohorts

In [445]:
enrol_filtered <- enrol_df |>
    filter(person_id %in% person_ids$person_id)

In [446]:
enrol_filtered |> arrange(AcademicYear) |> distinct(AcademicYear) |> pull(AcademicYear)

 [1] "2006/2007" "2007/2008" "2008/2009" "2009/2010" "2010/2011" "2011/2012"
 [7] "2012/2013" "2013/2014" "2014/2015" "2015/2016" "2016/2017" "2017/2018"
[13] "2018/2019"

In [447]:
enrol_filtered <- enrol_filtered |>
    left_join(person_ids, by = join_by(person_id))

In [448]:
enrol_filtered <- enrol_filtered |>
    filter(NCCIS_ACADYR == '2017/2018' & AcademicYear %in% c('2012/2013','2013/2014','2014/2015','2015/2016','2016/2017') | 
           NCCIS_ACADYR == '2018/2019' & AcademicYear %in% c('2013/2014','2014/2015','2015/2016','2016/2017', '2017/2018') 
           )

In [449]:
enrol_df |> 
    filter(person_id =='0D7E6767D93505F4E2D275095D8E4E341CF3F64D21181C133D076B48E194C28A')

  person_id                                                        SchoolID
1 0D7E6767D93505F4E2D275095D8E4E341CF3F64D21181C133D076B48E194C28A 6152
2 0D7E6767D93505F4E2D275095D8E4E341CF3F64D21181C133D076B48E194C28A 6152
3 0D7E6767D93505F4E2D275095D8E4E341CF3F64D21181C133D076B48E194C28A 7877
4 0D7E6767D93505F4E2D275095D8E4E341CF3F64D21181C133D076B48E194C28A 6152
5 0D7E6767D93505F4E2D275095D8E4E341CF3F64D21181C133D076B48E194C28A 6152
  AcademicYear OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate  LeavingDate
1 2011/2012    1        1        0        C           2008-09-26 <NA>
2 2008/2009    1        1        1        C           2008-09-26 <NA>
3 2006/2007    1        0        0        C           2004-01-05 2007-02-23
4 2010/2011    1        1        1        C           2008-09-26 <NA>
5 2009/2010    1        1        1        C           2008-09-26 <NA>
  PartTime
1 0
2 0
3 0
4 0
5 0

In [450]:
enrol_filtered |>
    filter(SchoolID == 1)

   person_id                                                        SchoolID
1  FE3895C54AD1AFAF3487E0DC4AE5D797D949AD1A6BFD767C2A250826F71E8299 1
2  865CD8F695ABA1CD8C7DC9652A565843C6522AD06E83B3E687037D6F31DBE3CB 1
3  4458A610F43FDE3869DF782E3CDF5D5BBD87B1440B3B034BDD3C9325CF95D2D7 1
4  C61E2B9BB83AC117227A79E3A023D60377E26D488D9B516886AA8584F2315D10 1
5  48A91215B096D39A8D6903838735D2B6F1E9A592794B102E69C81B4157C95CDD 1
6  E4FEFEA909D85AEB5E03E6E258ED980241087F9B0EAB9BE87065F6DCED31DC72 1
7  702FB1F91C19B856BFCF9AA812155786E1E44A5873EB0CBEE7D9E789250F31DD 1
8  428682AC0C308690F8194998ACED59DCC66844610B4CD8E878A66B769015116D 1
9  551B619FEC7FC59F080F7D0607E4CF9A72E1D194BBDEE479DE181E5BB7F57F0F 1
10 48226188441701D595B8833205F7F787AD32A9CA1E56E53E2C1487FAF73B38A5 1
   AcademicYear OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate  LeavingDate
1  2013/2014    NA       1        NA       C           2014-03-24 <NA>
2  2013/2014    NA       0        NA       NA          2014-03-06 2014-04-04
3  2013/2014    1        1        NA       C           2013-09-02 <NA>
4  2013/2014    0        NA       NA       C           2013-09-02 2013-12-05
5  2013/2014    1        1        NA       C           2013-11-07 <NA>
6  2013/2014    1        1        NA       C           2013-09-02 <NA>
7  2013/2014    1        1        NA       C           2013-11-11 <NA>
8  2013/2014    1        1        NA       C           2013-09-02 <NA>
9  2013/2014    0        NA       NA       C           2013-09-02 2013-12-05
10 2013/2014    1        1        NA       C           2013-09-02 <NA>
   PartTime NCCIS_ACADYR
1  0        2017/2018
2  0        2018/2019
3  0        2018/2019
4  0        2018/2019
5  0        2017/2018
6  0        2018/2019
7  0        2017/2018
8  0        2018/2019
9  0        2018/2019
10 0        2018/2019

In [451]:
enrol_filtered |> arrange(person_id, AcademicYear)

      person_id                                                        SchoolID
1     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD   980
2     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD   980
3     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD   980
4     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD   980
5     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 17485
6     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29  2204
7     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29  2204
8     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 16026
9     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 16026
10    00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 16026
11    0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 15042
12    0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 15042
13    0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 15042
14    0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 15042
15    0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 15042
16    0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7   852
17    0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7   852
18    0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7   852
19    0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 17296
20    0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 17296
21    00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66   641
22    00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66   641
23    00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66   641
24    00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66   641
25    00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66   641
26    0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D  1716
27    0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D  1716
28    0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D  1716
29    0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D  1716
30    0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D 17102
⋮     ⋮                                                                ⋮
85394 FFEF2AA9E8BD72D6A0E7CE50F067E4247E12738F53AE726CD94A4D9CB588C702  7013
85395 FFEF2AA9E8BD72D6A0E7CE50F067E4247E12738F53AE726CD94A4D9CB588C702   980
85396 FFEF2AA9E8BD72D6A0E7CE50F067E4247E12738F53AE726CD94A4D9CB588C702   980
85397 FFEF2AA9E8BD72D6A0E7CE50F067E4247E12738F53AE726CD94A4D9CB588C702   980
85398 FFEF2AA9E8BD72D6A0E7CE50F067E4247E12738F53AE726CD94A4D9CB588C702 17485
85399 FFEFD5577D0112E9304118DB7851CF61BEE4DD3D3184EEA756C076317925508F 10875
85400 FFEFD5577D0112E9304118DB7851CF61BEE4DD3D3184EEA756C076317925508F 10875
85401 FFEFD5577D0112E9304118DB7851CF61BEE4DD3D3184EEA756C076317925508F 10875
85402 FFEFD5577D0112E9304118DB7851CF61BEE4DD3D3184EEA756C076317925508F 10875
85403 FFEFD5577D0112E9304118DB7851CF61BEE4DD3D3184EEA756C076317925508F 10875
85404 FFFA6705A275195BFE8A443AF0BD2AA86B1AA0481D330D8665813206EB8DAD43 10875
85405 FFFA6705A275195BFE8A443AF0BD2AA86B1AA0481D330D8665813206EB8DAD43 10875
85406 FFFA6705A275195BFE8A443AF0BD2AA86B1AA0481D330D8665813206EB8DAD43 10875
85407 FFFA6705A275195BFE8A443AF0BD2AA86B1AA0481D330D8665813206EB8DAD43 10875
85408 FFFA6705A275195BFE8A443AF0BD2AA86B1AA0481D330D8665813206EB8DAD43 18286
85409 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77 12433
85410 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77 12433
85411 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77 12433
85412 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77 12433
85413 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77 12433
85414 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398  1340
85415 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398  1340
85416 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398  1340
85417 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 17165
85418 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 17165
85419 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92  1716
85420 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92  1716
85421 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92  1716
85422 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92  1716
85423 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 17102
      AcademicYear OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate
1     2012/2013    1        1        1        C           2012-09-04
2     2013/2014    1        1        1        C           2012-09-04
3     2014/2015    1        1        1        C           2012-09-04
4     2015/2016    1        1        NA       C           2012-09-04
5     2016/2017    1        1        0        C           2016-10-01
6     2012/2013    1        1        1        C           2012-09-04
7     2013/2014    1        1        NA       C           2012-09-04
8     2014/2015    1        1        1        C           2014-09-01
9     2015/2016    1        1        1        C           2014-09-01
10    2016/2017    1        1        0        C           2014-09-01
11    2013/2014    1        1        1        C           2013-09-03
12    2014/2015    1        1        1        C           2013-09-03
13    2015/2016    1        1        1        C           2013-09-03
14    2016/2017    1        1        1        C           2013-09-03
15    2017/2018    1        1        0        C           2013-09-03
16    2013/2014    1        1        1        C           2013-09-09
17    2014/2015    1        1        1        C           2013-09-09
18    2015/2016    1        1        NA       C           2013-09-09
19    2016/2017    1        1        1        C           2016-09-01
20    2017/2018    1        1        0        C           2016-09-01
21    2012/2013    1        1        1        C           2012-09-03
22    2013/2014    1        1        1        C           2012-09-03
23    2014/2015    1        1        1        C           2012-09-03
24    2015/2016    1        1        1        C           2012-09-03
25    2016/2017    1        1        1        C           2012-09-03
26    2012/2013    1        1        1        C           2012-09-03
27    2013/2014    1        1        1        C           2012-09-03
28    2014/2015    1        1        1        C           2012-09-03
29    2015/2016    1        1        1        C           2012-09-03
30    2016/2017    NA       1        0        C           2012-09-03
⋮     ⋮            ⋮        ⋮        ⋮        ⋮           ⋮
85394 2012/2013    1        1        0        C           2004-11-08
85395 2013/2014    1        1        1        C           2013-09-05
85396 2014/2015    1        1        1        C           2013-09-05
85397 2015/2016    1        1        NA       C           2013-09-05
85398 2016/2017    1        1        1        C           2016-10-01
85399 2012/2013    1        1        1        C           2012-09-03
85400 2013/2014    1        1        1        C           2012-09-03
85401 2014/2015    1        1        1        C           2012-09-03
85402 2015/2016    1        1        1        C           2012-09-03
85403 2016/2017    1        1        NA       C           2012-09-03
85404 2013/2014    1        1        1        C           2013-09-09
85405 2014/2015    1        1        1        C           2013-09-09
85406 2015/2016    1        1        1        C           2013-09-09
85407 2016/2017    1        1        NA       C           2013-09-09
85408 2017/2018    1        1        0        C           2017-09-01
85409 2013/2014    1        1        1        C           2013-09-02
85410 2014/2015    1        1        1        C           2013-09-02
85411 2015/2016    1        1        1        C           2013-09-02
85412 2016/2017    1        1        1        C           2013-09-02
85413 2017/2018    1        1        0        C           2013-09-02
85414 2013/2014    1        1        1        C           2013-09-02
85415 2014/2015    1        1        1        C           2013-09-02
85416 2015/2016    1        1        NA       C           2013-09-02
85417 2016/2017    1        1        1        C           2016-09-21
85418 2017/2018    1        1        0        C           2016-09-01
85419 2012/2013    1        1        1        C           2012-09-03
85420 2013/2014    1        1        1        C           2012-09-03
85421 2014/2015    1        1        1        C           2012-09-03
85422 2015/2016    1        1        1        C           2012-09-03
85423 2016/2017    NA       1        0        C           2012-09-03
      LeavingDate PartTime NCCIS_ACADYR
1     <NA>        0        2017/2018
2     <NA>        0        2017/2018
3     <NA>        0        2017/2018
4     <NA>        0        2017/2018
5     2017-06-30  0        2017/2018
6     <NA>        0        2017/2018
7     <NA>        0        2017/2018
8     <NA>        0        2017/2018
9     <NA>        0        2017/2018
10    2017-07-21  0        2017/2018
11    <NA>        0        2018/2019
12    <NA>        0        2018/2019
13    <NA>        0        2018/2019
14    <NA>        0        2018/2019
15    2018-06-29  0        2018/2019
16    <NA>        0        2018/2019
17    <NA>        0        2018/2019
18    <NA>        0        2018/2019
19    <NA>        0        2018/2019
20    2018-07-20  0        2018/2019
21    <NA>        0        2017/2018
22    <NA>        0        2017/2018
23    <NA>        0        2017/2018
24    <NA>        0        2017/2018
25    <NA>        0        2017/2018
26    <NA>        0        2017/2018
27    <NA>        0        2017/2018
28    <NA>        0        2017/2018
29    <NA>        0        2017/2018
30    2017-07-21  0        2017/2018
⋮     ⋮           ⋮        ⋮
85394 <NA>        0        2017/2018
85395 <NA>        0        2017/2018
85396 <NA>        0        2017/2018
85397 <NA>        0        2017/2018
85398 <NA>        0        2017/2018
85399 <NA>        0        2017/2018
85400 <NA>        0        2017/2018
85401 <NA>        0        2017/2018
85402 <NA>        0        2017/2018
85403 <NA>        0        2017/2018
85404 <NA>        0        2018/2019
85405 <NA>        0        2018/2019
85406 <NA>        0        2018/2019
85407 <NA>        0        2018/2019
85408 2018-06-29  0        2018/2019
85409 <NA>        0        2018/2019
85410 <NA>        0        2018/2019
85411 <NA>        0        2018/2019
85412 <NA>        0        2018/2019
85413 2018-08-31  0        2018/2019
85414 <NA>        0        2018/2019
85415 <NA>        0        2018/2019
85416 <NA>        0        2018/2019
85417 <NA>        0        2018/2019
85418 2018-07-20  0        2018/2019
85419 <NA>        0        2017/2018
85420 <NA>        0        2017/2018
85421 <NA>        0        2017/2018
85422 <NA>        0        2017/2018
85423 2017-07-21  0        2017/2018

#### Get list of school IDs in enrollments table

In [452]:
cohort_schools <- enrol_filtered |> arrange(SchoolID) |> distinct(SchoolID) |> pull(SchoolID)

In [453]:
length(cohort_schools)

[1] 2053

In [454]:
head(school_match)

  SchoolID URN
1  1935    108274
2   749    108275
3   724    108297
4  2611    108299
5  2238    108279
6 11068    135961

#### Join schools info into school match IDs

In [455]:
head(school_df)

  InstitutionHistoryID InstitutionID AcademicYear
1 968                  3198          2005/2006
2 25892                8275          2005/2006
3 40609                11287         2005/2006
4 56451                14508         2005/2006
5 123604               28104         2005/2006
6 124903               28374         2005/2006
  InstitutionTypeDesc                URN    SchoolName
1 Community school (CY)              100222 Craven Park School
2 Community school (CY)              105771 Hill Top Community Primary School
3 Community school (CY)              109069 Radstock Infant School
4 Independent schools (other) (IND)  112448 Holme Park School
5 Community school (CY)              130095 Wembley Primary School
6 Further Educational sector college 130541 Park Lane College, Leeds
  PhaseOfEducationDesc
1 Primary
2 Primary
3 Primary
4 Not applicable
5 Primary
6 16 Plus

In [456]:
school_df$URN <- as.numeric(school_df$URN)

In [457]:
schools_filtered <- school_match |>
    left_join(school_df, by = join_by(URN)) |>
    select(SchoolID, URN, AcademicYear, InstitutionTypeDesc, SchoolName, PhaseOfEducationDesc)

In [458]:
schools_filtered <- schools_filtered |>
    distinct()

In [459]:
head(schools_filtered)

  SchoolID URN    AcademicYear InstitutionTypeDesc
1 1935     108274 2005/2006    Community school (CY)
2 1935     108274 2006/2007    Community school (CY)
3 1935     108274 2007/2008    Community school (CY)
4 1935     108274 2008/2009    Community school (CY)
5 1935     108274 2009/2010    Community school (CY)
6 1935     108274 2010/2011    Community School (CY)
  SchoolName                           PhaseOfEducationDesc
1 Hemsworth Arts and Community College Secondary
2 Hemsworth Arts and Community College Secondary
3 Hemsworth Arts and Community College Secondary
4 Hemsworth Arts and Community College Secondary
5 Hemsworth Arts and Community College Secondary
6 Hemsworth Arts and Community College Secondary

In [460]:
schools_filtered |>
    filter(SchoolID == 6152)

   SchoolID URN    AcademicYear InstitutionTypeDesc
1  6152     107211 2005/2006    Community school (CY)
2  6152     107211 2006/2007    Community school (CY)
3  6152     107211 2007/2008    Community school (CY)
4  6152     107211 2008/2009    Community school (CY)
5  6152     107211 2009/2010    Community school (CY)
6  6152     107211 2010/2011    Community School (CY)
7  6152     107211 2011/2012    Community School (CY)
8  6152     107211 2012/2013    Community School (CY)
9  6152     107211 2013/2014    Community School (CY)
10 6152     107211 2014/2015    Community School (CY)
11 6152     107211 2015/2016    Community School (CY)
12 6152     107211 2016/2017    Community School (CY)
13 6152     107211 2017/2018    Community School (CY)
14 6152     107211 2018/2019    Community School (CY)
15 6152     107211 2019/2020    Community School (CY)
16 6152     107211 2020/2021    Community School (CY)
17 6152     107211 2021/2022    Community School (CY)
   SchoolName                        PhaseOfEducationDesc
1  Lapage Primary School and Nursery Primary
2  Lapage Primary School and Nursery Primary
3  Lapage Primary School and Nursery Primary
4  Lapage Primary School and Nursery Primary
5  Lapage Primary School and Nursery Primary
6  Lapage Primary School and Nursery Primary
7  Lapage Primary School and Nursery Primary
8  Lapage Primary School and Nursery Primary
9  Lapage Primary School and Nursery Primary
10 Lapage Primary School and Nursery Primary
11 Lapage Primary School and Nursery Primary
12 Lapage Primary School and Nursery Primary
13 Lapage Primary School and Nursery Primary
14 Lapage Primary School and Nursery Primary
15 Lapage Primary School and Nursery Primary
16 Lapage Primary School and Nursery Primary
17 Lapage Primary School and Nursery Primary

#### Clean up schools data

In [461]:
# fill NAs in the Phase of Edu col
schools_filtered <- schools_filtered |>
  group_by(URN) |>
  mutate(
    PhaseOfEducationDesc = if_else(
      is.na(PhaseOfEducationDesc),
      first(na.omit(PhaseOfEducationDesc)),
      PhaseOfEducationDesc
    )
  ) |>
  ungroup()

In [462]:
# keep only first row per academic year where multiple per school (e.g. change in school type mid year to academy status)
schools_filtered <- schools_filtered |>
  arrange(AcademicYear) |>
  group_by(SchoolID, URN, AcademicYear) |>
  slice(1) |>
  ungroup()

In [463]:
schools_filtered |> 
    filter(SchoolID == 21)

   SchoolID URN    AcademicYear InstitutionTypeDesc
1  21       100747 2005/2006    Community school (CY)
2  21       100747 2006/2007    Community school (CY)
3  21       100747 2007/2008    Community school (CY)
4  21       100747 2008/2009    Community school (CY)
5  21       100747 2009/2010    Community school (CY)
6  21       100747 2010/2011    Community School (CY)
7  21       100747 2011/2012    Community School (CY)
8  21       100747 2012/2013    Community School (CY)
9  21       100747 2013/2014    Community School (CY)
10 21       100747 2014/2015    Community School (CY)
11 21       100747 2015/2016    Foundation School (FD)
12 21       100747 2016/2017    Foundation School (FD)
13 21       100747 2017/2018    Foundation School (FD)
14 21       100747 2018/2019    Foundation School (FD)
15 21       100747 2019/2020    Foundation School (FD)
16 21       100747 2020/2021    Foundation School (FD)
17 21       100747 2021/2022    Foundation School (FD)
   SchoolName                            PhaseOfEducationDesc
1  Crofton School                        Secondary
2  Crofton School                        Secondary
3  Crofton School                        Secondary
4  Prendergast - Ladywell Fields College Secondary
5  Prendergast - Ladywell Fields College Secondary
6  Prendergast - Ladywell Fields College Secondary
7  Prendergast - Ladywell Fields College Secondary
8  Prendergast - Ladywell Fields College Secondary
9  Prendergast - Ladywell Fields College Secondary
10 Prendergast - Ladywell Fields College Secondary
11 Prendergast Ladywell School           Secondary
12 Prendergast Ladywell School           Secondary
13 Prendergast Ladywell School           Secondary
14 Prendergast Ladywell School           Secondary
15 Prendergast Ladywell School           Secondary
16 Prendergast Ladywell School           Secondary
17 Prendergast Ladywell School           Secondary

In [464]:
# Check if SchoolID + AcademicYear is unique 
schools_filtered |>
  count(SchoolID, AcademicYear) |>
  filter(n > 1)  # problem rows

     SchoolID AcademicYear n

#### clean up institution types

In [465]:
schools_filtered |>
    distinct(InstitutionTypeDesc)

   InstitutionTypeDesc
1  Community school (CY)
2  Community School (CY)
3  Voluntary aided school (VA)
4  Voluntary Aided School (VA)
5  Foundation School (FD)
6  Voluntary controlled school (VC)
7  Voluntary Controlled School (VC)
8  Foundation school (FD)
9  Academy (AC)
10 Academy Sponsor Led (AC)
11 Academy - Sponsor Led Mainstream (AC)
12 City technology college (CTC)
13 City technology College (CTC)
14 City Technology College (CTC)
15 Community special school (CYS)
16 Community Special School (CYS)
17 Special school not maintained by LEA (NMSS)
18 Non-Maintained Special School (NMSS)
19 Foundation special school (FDS)
20 Foundation Special School (FDS)
21 Community hospital school (CYH)
22 Academy Converters Mainstream
23 Academy Converter - Mainstream (ACC)
24 Academy Free Schools / Consortia
25 Free School - Mainstream (F)
26 Academy - Converter Special School (ACCS)
27 Pupil referral unit
28 Pupil Referral Unit
29 Pupil Referral Unit (PRU)
30 Academy - Sponsor Led Special School (ACS)
31 Academy - Converter AP (ACCAP)
32 Free School û Studio School (FSS)
33 Academy Converter Special School
34 Free School - Alternative Provision
35 Free School - Alternative Provision (FAP)
36 Free School - UTC (FUTC)
37 Free School û Studio School
38 Academy - Sponsor Led AP (ACAP)
39 Free School û 16-19 (F1619)
40 Academy Schhol

In [466]:
schools_filtered <- schools_filtered |>
  mutate(InstitutionTypeDesc = str_replace_all(InstitutionTypeDesc, "û", "-"))

In [467]:
schools_filtered <- schools_filtered |>
  mutate(InstitutionTypeDesc = InstitutionTypeDesc |> 
           str_trim())

In [468]:
schools_filtered <- schools_filtered |>
    mutate(InstitutionTypeDesc = case_when(
            InstitutionTypeDesc %in% c("Community school (CY)", "Community School (CY)") ~ 'Community school',
        
        InstitutionTypeDesc %in% c("Voluntary aided school (VA)", "Voluntary Aided School (VA)") ~ 'Voluntary aided school',
        
        InstitutionTypeDesc %in% c("Foundation School (FD)", "Foundation school (FD)") ~ 'Foundation school',
        
        InstitutionTypeDesc %in% c("Voluntary controlled school (VC)", "Voluntary Controlled School (VC)") ~ 'Voluntary controlled school',
        
        InstitutionTypeDesc %in% c("Academy (AC)", "Academy Schhol", "Academy Free Schools / Consortia") ~ 'Academy',
        
        InstitutionTypeDesc %in% c("Academy Sponsor Led (AC)", "Academy - Sponsor Led Mainstream (AC)") ~ 'Academy sponsor led',
        
        InstitutionTypeDesc %in% c("City technology college (CTC)", "City technology College (CTC)", "City Technology College (CTC)") ~ 'City technology college',
        
        InstitutionTypeDesc %in% c("Community special school (CYS)", "Community Special School (CYS)") ~ 'Community special school',
        
        InstitutionTypeDesc %in% c("Special school not maintained by LEA (NMSS)", "Non-Maintained Special School (NMSS)") ~ 'Non-maintained special school',
        
        InstitutionTypeDesc %in% c("Foundation special school (FDS)", "Foundation Special School (FDS)") ~ 'Foundation special school',
        
        InstitutionTypeDesc %in% c("Community hospital school (CYH)") ~ 'Community hospital school',
        
        InstitutionTypeDesc %in% c("Academy Converters Mainstream", "Academy Converter - Mainstream (ACC)") ~ 'Academy converter',
        
        InstitutionTypeDesc %in% c("Free School - Mainstream (F)", "Community School (CY)") ~ 'Free school',
        
        InstitutionTypeDesc %in% c("Academy - Converter Special School (ACCS)", "Academy - Sponsor Led Special School (ACS)") ~ 'Academy special school',
        
        InstitutionTypeDesc %in% c("Pupil referral unit", "Pupil Referral Unit", 
                                   'Pupil Referral Unit (PRU)', 'Academy - Converter AP (ACCAP)',
                                  'Free School - Alternative Provision', 'Academy - Sponsor Led AP (ACAP)',
                                  'Free School - Alternative Provision (FAP)') ~ 'AP/PRU',
        
        InstitutionTypeDesc %in% c("Free School - Studio School (FSS)", 'Free School - Studio School') ~ 'Studio school',
        InstitutionTypeDesc %in% c("Free School - UTC (FUTC)") ~ 'University technical college',
        InstitutionTypeDesc %in% c("Free School - Studio School (FSS)") ~ 'Studio school',
        InstitutionTypeDesc %in% c("Free School - 16-19 (F1619)") ~ 'Free school (16-19)',
    TRUE ~ InstitutionTypeDesc)
           )

#### check for schools changing name

In [469]:
schools_filtered <- schools_filtered |>
  mutate(SchoolName = gsub("[[:punct:]]", "", SchoolName))

In [470]:
schools_filtered <- schools_filtered |>
  mutate(SchoolName = SchoolName |> 
           str_trim())

In [471]:
schools_filtered |>
    group_by(URN) |> 
    filter(n_distinct(SchoolName) > 1) |> 
    arrange(URN, SchoolName)

     SchoolID URN    AcademicYear InstitutionTypeDesc
1    1706     100051 2012/2013    Community school
2    1706     100051 2013/2014    Community school
3    1706     100051 2014/2015    Community school
4    1706     100051 2015/2016    Community school
5    1706     100051 2016/2017    Community school
6    1706     100051 2017/2018    Community school
7    1706     100051 2018/2019    Community school
8    1706     100051 2019/2020    Community school
9    1706     100051 2020/2021    Community school
10   1706     100051 2021/2022    Community school
11   1706     100051 2005/2006    Community school
12   1706     100051 2006/2007    Community school
13   1706     100051 2007/2008    Community school
14   1706     100051 2008/2009    Community school
15   1706     100051 2009/2010    Community school
16   1706     100051 2010/2011    Community school
17   1706     100051 2011/2012    Community school
18   2155     100279 2005/2006    Community school
19   2155     100279 2006/2007    Community school
20   2155     100279 2007/2008    Community school
21   2155     100279 2008/2009    Community school
22   2155     100279 2009/2010    Community school
23   2155     100279 2010/2011    Community school
24   2155     100279 2011/2012    Community school
25   2155     100279 2012/2013    Community school
26   2155     100279 2013/2014    Community school
27   2155     100279 2014/2015    Community school
28   2155     100279 2015/2016    Community school
29   2155     100279 2016/2017    Community school
30   2155     100279 2017/2018    Community school
⋮    ⋮        ⋮      ⋮            ⋮
9159 18283    144991 2018/2019    Academy sponsor led
9160 18283    144991 2019/2020    Academy sponsor led
9161 18283    144991 2020/2021    Academy sponsor led
9162 18283    144991 2021/2022    Academy sponsor led
9163 18283    144991 2016/2017    Academy sponsor led
9164 17863    145327 2017/2018    Academy converter
9165 17863    145327 2018/2019    Academy converter
9166 17863    145327 2019/2020    Academy converter
9167 17863    145327 2020/2021    Academy converter
9168 17863    145327 2021/2022    Academy converter
9169 18594    145577 2018/2019    Academy sponsor led
9170 18594    145577 2019/2020    Academy sponsor led
9171 18594    145577 2020/2021    Academy sponsor led
9172 18594    145577 2021/2022    Academy sponsor led
9173 18594    145577 2017/2018    Academy sponsor led
9174 18106    145579 2017/2018    Academy converter
9175 18106    145579 2018/2019    Academy converter
9176 18106    145579 2019/2020    Academy converter
9177 18106    145579 2020/2021    Academy converter
9178 18106    145579 2021/2022    Academy converter
9179 18002    145736 2018/2019    Academy sponsor led
9180 18002    145736 2019/2020    Academy sponsor led
9181 18002    145736 2020/2021    Academy sponsor led
9182 18002    145736 2021/2022    Academy sponsor led
9183 18002    145736 2017/2018    Academy sponsor led
9184 18622    145929 2018/2019    Academy converter
9185 18622    145929 2019/2020    Academy converter
9186 18622    145929 2020/2021    Academy converter
9187 18622    145929 2021/2022    Academy converter
9188 18622    145929 2017/2018    Academy converter
     SchoolName                            PhaseOfEducationDesc
1    Regent High School                    Secondary
2    Regent High School                    Secondary
3    Regent High School                    Secondary
4    Regent High School                    Secondary
5    Regent High School                    Secondary
6    Regent High School                    Secondary
7    Regent High School                    Secondary
8    Regent High School                    Secondary
9    Regent High School                    Secondary
10   Regent High School                    Secondary
11   South Camden Community School         Secondary
12   South Camden Community School         Secondary
13   South Camden Community School         Secondary
14   South Camden Community School         Secondary
15   South Camden Community School         Secondary
16   South Camden Community School         Secondary
17   South Camden Community School         Secondary
18   Stoke Newington School                Secondary
19   Stoke Newington School                Secondary
20   Stoke Newington School                Secondary
21   Stoke Newington School                Secondary
22   Stoke Newington School                Secondary
23   Stoke Newington School and Sixth Form Secondary
24   Stoke Newington School and Sixth Form Secondary
25   Stoke Newington School and Sixth Form Secondary
26   Stoke Newington School and Sixth Form Secondary
27   Stoke Newington School and Sixth Form Secondary
28   Stoke Newington School and Sixth Form Secondary
29   Stoke Newington School and Sixth Form Secondary
30   Stoke Newington School and Sixth Form Secondary
⋮    ⋮                                     ⋮
9159 Staindrop Academy                     Secondary
9160 Staindrop Academy                     Secondary
9161 Staindrop Academy                     Secondary
9162 Staindrop Academy                     Secondary
9163 Staindrop School an Academy           Secondary
9164 Derby Moor Academy                    Secondary
9165 Derby Moor Academy                    Secondary
9166 Derby Moor Academy                    Secondary
9167 Derby Moor Academy                    Secondary
9168 Derby Moor Spencer Academy            Secondary
9169 Longfield Academy                     Secondary
9170 Longfield Academy                     Secondary
9171 Longfield Academy                     Secondary
9172 Longfield Academy                     Secondary
9173 Longfield Academy of Sport            Secondary
9174 Cathedral Academy                     Secondary
9175 Cathedral Academy                     Secondary
9176 Cathedral Academy                     Secondary
9177 Trinity Academy Cathedral             Secondary
9178 Trinity Academy Cathedral             Secondary
9179 Lord Grey Academy                     Secondary
9180 Lord Grey Academy                     Secondary
9181 Lord Grey Academy                     Secondary
9182 Lord Grey Academy                     Secondary
9183 Lord Grey School                      Secondary
9184 Goole Academy                         Secondary
9185 Goole Academy                         Secondary
9186 Goole Academy                         Secondary
9187 Goole Academy                         Secondary
9188 Goole High School                     Secondary

In [472]:
latest_names <- schools_filtered |>
    group_by(URN) |>
    slice_max(AcademicYear, n = 1, with_ties = FALSE) |>
    select(URN, SchoolName) |>
    rename(LatestSchoolName = SchoolName)

In [473]:
head(latest_names)

  URN    LatestSchoolName
1 100051 Regent High School
2 100192 The John Roan School
3 100277 Haggerston School
4 100279 Stoke Newington School and Sixth Form
5 100284 The Urswick School  A Church of England Secondary School
6 100360 Fulham Cross Girls School and Language College

In [474]:
latest_names |>
    filter(URN == 107302)

  URN    LatestSchoolName
1 107302 All Saints CofE Primary School

In [475]:
schools_filtered <- schools_filtered |>
    left_join(latest_names, by = "URN") |>
    mutate(SchoolName = coalesce(LatestSchoolName, SchoolName)) |>
    select(-LatestSchoolName)

In [476]:
head(schools_filtered)

  SchoolID URN    AcademicYear InstitutionTypeDesc SchoolName
1 1        108056 2005/2006    Community school    City of Leeds School
2 1        108056 2006/2007    Community school    City of Leeds School
3 1        108056 2007/2008    Community school    City of Leeds School
4 1        108056 2008/2009    Community school    City of Leeds School
5 1        108056 2009/2010    Community school    City of Leeds School
6 1        108056 2010/2011    Community school    City of Leeds School
  PhaseOfEducationDesc
1 Secondary
2 Secondary
3 Secondary
4 Secondary
5 Secondary
6 Secondary

#### fuzzy match for slightly different name spellings

In [243]:
install.packages('stringdist')

Installing package into ‘/home/jupyter/.R/library’
(as ‘lib’ is unspecified)

In [244]:
library(stringdist)

In [284]:
school_names <- unique(schools_filtered$SchoolName)

In [285]:
dist_matrix <- stringdistmatrix(school_names, school_names, method = "jw")

In [286]:
# Find likely duplicates based on low distance
fuzzy_matches <- which(dist_matrix < 0.1 & dist_matrix > 0, arr.ind = TRUE)

In [301]:
enrol_final |>
    filter(SchoolName == 'Queen Elizabeths School')

  person_id                                                        SchoolID
1 BB1C7F4FC50A60FF728A48C7F2A3C4496F2E6765FA62119EBBF5ABB6FB133735 16226
2 BB1C7F4FC50A60FF728A48C7F2A3C4496F2E6765FA62119EBBF5ABB6FB133735 16226
3 BB1C7F4FC50A60FF728A48C7F2A3C4496F2E6765FA62119EBBF5ABB6FB133735 16226
4 D5BC71328A6A3D4C7F394FF461AB2209C88B7569BF0CFFDA0A73A87D0AB8607C 16226
  AcademicYear OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate  LeavingDate
1 2015/2016    1        1        1        C           2015-09-01 <NA>
2 2016/2017    1        1        1        C           2015-09-01 <NA>
3 2017/2018    1        1        1        C           2015-09-01 <NA>
4 2015/2016    1        0        NA       C           2015-09-02 2016-02-26
  PartTime NCCIS_ACADYR URN    InstitutionTypeDesc SchoolName
1 0        2018/2019    141526 Academy converter   Queen Elizabeths School
2 0        2018/2019    141526 Academy converter   Queen Elizabeths School
3 0        2018/2019    141526 Academy converter   Queen Elizabeths School
4 0        2018/2019    141526 Academy converter   Queen Elizabeths School
  PhaseOfEducationDesc LatestURN
1 Secondary            141526
2 Secondary            141526
3 Secondary            141526
4 Secondary            141526

In [303]:
enrol_final |>
    filter(SchoolName == "Queen Elizabeths Grammar School")

  person_id                                                        SchoolID
1 5E067A183AF6A1DFCA5B9A38548CB42F4131EE05E131A525F083F605CCFADB55 16035
2 8F2BE8D2C898930C38AA9528327C1F76996160EED76CE10B90E666D588D3E436 11607
3 8F2BE8D2C898930C38AA9528327C1F76996160EED76CE10B90E666D588D3E436 11607
4 5E067A183AF6A1DFCA5B9A38548CB42F4131EE05E131A525F083F605CCFADB55 16035
5 8F2BE8D2C898930C38AA9528327C1F76996160EED76CE10B90E666D588D3E436 11607
6 8F2BE8D2C898930C38AA9528327C1F76996160EED76CE10B90E666D588D3E436 11607
7 5E067A183AF6A1DFCA5B9A38548CB42F4131EE05E131A525F083F605CCFADB55 16035
8 8F2BE8D2C898930C38AA9528327C1F76996160EED76CE10B90E666D588D3E436 11607
9 5E067A183AF6A1DFCA5B9A38548CB42F4131EE05E131A525F083F605CCFADB55 16035
  AcademicYear OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate  LeavingDate
1 2017/2018    1        1        1        C           2014-09-22 <NA>
2 2013/2014    1        1        1        C           2012-09-03 <NA>
3 2016/2017    1        1        1        C           2012-09-03 <NA>
4 2014/2015    1        1        1        C           2014-09-22 <NA>
5 2014/2015    1        1        1        C           2012-09-03 <NA>
6 2015/2016    1        1        1        C           2012-09-03 <NA>
7 2015/2016    1        1        1        C           2014-09-22 <NA>
8 2012/2013    1        1        1        C           2012-09-03 <NA>
9 2016/2017    1        1        1        C           2014-09-22 <NA>
  PartTime NCCIS_ACADYR URN    InstitutionTypeDesc
1 0        2018/2019    141165 Free school
2 0        2017/2018    136972 Academy converter
3 0        2017/2018    136972 Academy converter
4 0        2018/2019    141165 Free school
5 0        2017/2018    136972 Academy converter
6 0        2017/2018    136972 Academy converter
7 0        2018/2019    141165 Free school
8 0        2017/2018    136972 Academy converter
9 0        2018/2019    141165 Free school
  SchoolName                      PhaseOfEducationDesc LatestURN
1 Queen Elizabeths Grammar School NA                   136972
2 Queen Elizabeths Grammar School Secondary            136972
3 Queen Elizabeths Grammar School Secondary            136972
4 Queen Elizabeths Grammar School NA                   136972
5 Queen Elizabeths Grammar School Secondary            136972
6 Queen Elizabeths Grammar School Secondary            136972
7 Queen Elizabeths Grammar School NA                   136972
8 Queen Elizabeths Grammar School Secondary            136972
9 Queen Elizabeths Grammar School NA                   136972

In [287]:
tibble(
  name1 = school_names[fuzzy_matches[, 1]],
  name2 = school_names[fuzzy_matches[, 2]],
  distance = dist_matrix[fuzzy_matches]
) %>%
  distinct() %>%
  arrange(distance)

    name1                                 name2
1   Queen Elizabeths School               Queen Elizabeth School
2   Queen Elizabeth School                Queen Elizabeths School
3   Hinde House 216 School                Hinde House 316 School
4   Hinde House 316 School                Hinde House 216 School
5   Bedale High School                    Beal High School
6   Forest Hall School                    Forest Hill School
7   Beal High School                      Bedale High School
8   Forest Hill School                    Forest Hall School
9   Brookfield School                     Broomfield School
10  Broomfield School                     Brookfield School
11  Goole High School                     Poole High School
12  Poole High School                     Goole High School
13  Mark Hall Academy                     Park Hall Academy
14  Park Hall Academy                     Mark Hall Academy
15  Emmanuel College                      Immanuel College
16  Immanuel College                      Emmanuel College
17  Haworth Primary School                Oakworth Primary School
18  Oakworth Primary School               Haworth Primary School
19  Stanley High School                   Sale High School
20  The Kings School                      The Kingsway School
21  Sale High School                      Stanley High School
22  The Kingsway School                   The Kings School
23  Bushey Meads School                   Rushey Mead School
24  Avon Valley Academy                   Don Valley Academy
25  Rushey Mead School                    Bushey Meads School
26  Don Valley Academy                    Avon Valley Academy
27  The Warren School                     The Warriner School
28  The Warriner School                   The Warren School
29  Westfield Primary School              Nessfield Primary School
30  Nessfield Primary School              Westfield Primary School
⋮   ⋮                                     ⋮
259 Wilsden Primary School                Westfield Primary School
260 Westfield Primary School              Wilsden Primary School
261 Queen Elizabeths Grammar School       Queen Elizabeth School
262 Queen Elizabeth School                Queen Elizabeths Grammar School
263 Meridian High School                  Marden High School
264 Marden High School                    Meridian High School
265 Honley High School                    Hyde High School
266 Hyde High School                      Honley High School
267 Bosworth Academy                      Brinsworth Academy
268 Presdales School                      Priestlands School
269 Brinsworth Academy                    Bosworth Academy
270 Shavington Academy                    Paignton Academy
271 Priestlands School                    Presdales School
272 Paignton Academy                      Shavington Academy
273 Queen Elizabeths School               Queen Elizabeth High School
274 Queen Elizabeth High School           Queen Elizabeths School
275 Endon High School                     Endeavour High School
276 Endeavour High School                 Endon High School
277 Outwood Academy Freeston              Outwood Academy Carlton
278 Outwood Academy Carlton               Outwood Academy Freeston
279 St Anselms Catholic School Canterbury St Anselms Catholic School
280 St Anselms Catholic School            St Anselms Catholic School Canterbury
281 Tring School                          Trinity School
282 Trinity School                        Tring School
283 Weaverham High School                 Caterham High School
284 Caterham High School                  Weaverham High School
285 Brigshaw High School                  Brighouse High School
286 Brighouse High School                 Brigshaw High School
287 Braunton Academy                      Brayton Academy
288 Brayton Academy                       Braunton Academy
    distance
1   0.01449275
2   0.01449275
3   0.03030303
4   0.03030303
5   0.03703704
6   0.03703704
7   0.03703704
8   0.03703704
9   0.03921569
10  0.03921569
11  0.03921569
12  0.03921569
13  0.03921569
14  0.03921569
15  0.04166667
16  0.04166667
17  0.04413702
18  0.04413702
19  0.05263158
20  0.05263158
21  0.05263158
22  0.05263158
23  0.05360624
24  0.05360624
25  0.05360624
26  0.05360624
27  0.05469556
28  0.05469556
29  0.05555556
30  0.05555556
⋮   ⋮
259 0.09650072
260 0.09650072
261 0.09677419
262 0.09677419
263 0.09814815
264 0.09814815
265 0.09861111
266 0.09861111
267 0.09861111
268 0.09861111
269 0.09861111
270 0.09861111
271 0.09861111
272 0.09861111
273 0.09894842
274 0.09894842
275 0.09897292
276 0.09897292
277 0.09903382
278 0.09903382
279 0.09909910
280 0.09909910
281 0.09920635
282 0.09920635
283 0.09947090
284 0.09947090
285 0.09947090
286 0.09947090
287 0.09960317
288 0.09960317

In [ ]:
#school_names_clean <- schools_filtered |>
#    mutate(SchoolName = case_when(
#            SchoolName %in% c("Hinde House 216 School", "Hinde House 316 School") ~ 'Hinde House 2-16 School',
#        SchoolName %in% c("St Josephs Catholic College", "St Bedes and St Josephs Catholic College") ~ 'St Bedes and St Josephs Catholic College',
#        SchoolName %in% c("Oakbank School", "Beckfoot Oakbank") ~ 'Beckfoot Oakbank',
#        SchoolName %in% c("Tong High School", "Tong Leadership Academy") ~ 'Tong Leadership Academy',
#        SchoolName %in% c("St Anselms Catholic School", "St Anselms Catholic School Canterbury") ~ 'Hinde House 2-16 School',

In [307]:
enrol_final |>
    filter(SchoolName == "St Anselms Catholic School")

  person_id                                                        SchoolID
1 329745E3565E94BD632FA7AB0F347C5E1C5B5DDE0E32304B542436108D440D9F 1505
2 329745E3565E94BD632FA7AB0F347C5E1C5B5DDE0E32304B542436108D440D9F 1505
3 296E09A08A59BA0C6C6491466160F8E03009E1F05A3F75C0ADA1D848F541F631 1505
  AcademicYear OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate  LeavingDate
1 2012/2013    NA       1        1        C           2013-05-07 <NA>
2 2013/2014    1        1        1        M           2013-05-07 <NA>
3 2013/2014    1        1        1        C           2013-09-03 <NA>
  PartTime NCCIS_ACADYR URN    InstitutionTypeDesc
1 0        2017/2018    118918 Voluntary aided school
2 0        2017/2018    118918 Voluntary aided school
3 0        2018/2019    118918 Voluntary aided school
  SchoolName                 PhaseOfEducationDesc LatestURN
1 St Anselms Catholic School Secondary            118918
2 St Anselms Catholic School Secondary            118918
3 St Anselms Catholic School Secondary            118918

#### Decision - treat academisation as new school - DfE do as asign new URN

#### IGNORE check for schools changing URN because of becoming academies etc...

In [ ]:
#schools_filtered |>
    group_by(SchoolName) |> 
    filter(n_distinct(URN) > 1) |> 
    arrange(SchoolName, URN)

In [289]:
#latest_urn <- schools_filtered |>
    group_by(SchoolName) |>
    slice_max(AcademicYear, n = 1, with_ties = FALSE) |>
    select(URN, SchoolName) |>
    rename(LatestURN = URN)

In [308]:
#head(latest_urn)

In [291]:
#schools_filtered <- schools_filtered |>
  left_join(latest_urn, by = "SchoolName")

In [329]:
schools_filtered |>
    group_by(SchoolName) |> 
    filter(n_distinct(URN) > 1) |> 
    arrange(SchoolName, URN)

     SchoolID URN    AcademicYear InstitutionTypeDesc
1    10414    135622 2007/2008    Academy
2    10414    135622 2008/2009    Academy
3    10414    135622 2009/2010    Academy
4    10414    135622 2010/2011    Academy sponsor led
5    10414    135622 2011/2012    Academy sponsor led
6    10414    135622 2012/2013    Academy sponsor led
7    10414    135622 2013/2014    Academy sponsor led
8    10414    135622 2014/2015    Academy sponsor led
9    10414    135622 2015/2016    Academy sponsor led
10   10414    135622 2016/2017    Academy sponsor led
11   10414    135622 2017/2018    Academy sponsor led
12   10414    135622 2018/2019    Academy sponsor led
13   10414    135622 2019/2020    Academy sponsor led
14   10414    135622 2020/2021    Academy sponsor led
15   10414    135622 2021/2022    Academy sponsor led
16   18018    145477 2017/2018    Academy sponsor led
17   18018    145477 2018/2019    Academy sponsor led
18   18018    145477 2019/2020    Academy sponsor led
19   18018    145477 2020/2021    Academy sponsor led
20   18018    145477 2021/2022    Academy sponsor led
21   11806    136142 2009/2010    Academy
22   11806    136142 2010/2011    Academy sponsor led
23   11806    136142 2011/2012    Academy sponsor led
24   11806    136142 2012/2013    Academy sponsor led
25   11806    136142 2013/2014    Academy sponsor led
26   11806    136142 2014/2015    Academy sponsor led
27   11806    136142 2015/2016    Academy sponsor led
28   11806    136142 2016/2017    Academy sponsor led
29   11806    136142 2017/2018    Academy sponsor led
30   11806    136142 2018/2019    Academy sponsor led
⋮    ⋮        ⋮      ⋮            ⋮
3195 14641    139961 2018/2019    Academy sponsor led
3196 14641    139961 2019/2020    Academy sponsor led
3197 14641    139961 2020/2021    Academy sponsor led
3198 14641    139961 2021/2022    Academy sponsor led
3199  2535    103520 2005/2006    Community school
3200  2535    103520 2006/2007    Community school
3201  2535    103520 2007/2008    Community school
3202  2535    103520 2008/2009    Community school
3203  2535    103520 2009/2010    Community school
3204  2535    103520 2010/2011    Community school
3205  2535    103520 2011/2012    Community school
3206  2535    103520 2012/2013    Community school
3207  2535    103520 2013/2014    Community school
3208  2535    103520 2014/2015    Community school
3209  2535    103520 2015/2016    Community school
3210  2535    103520 2016/2017    Community school
3211  2535    103520 2017/2018    Community school
3212  2535    103520 2018/2019    Community school
3213  2535    103520 2019/2020    Community school
3214  2535    103520 2020/2021    Community school
3215  2535    103520 2021/2022    Community school
3216 15193    139994 2013/2014    Academy converter
3217 15193    139994 2014/2015    Academy converter
3218 15193    139994 2015/2016    Academy converter
3219 15193    139994 2016/2017    Academy converter
3220 15193    139994 2017/2018    Academy converter
3221 15193    139994 2018/2019    Academy converter
3222 15193    139994 2019/2020    Academy converter
3223 15193    139994 2020/2021    Academy converter
3224 15193    139994 2021/2022    Academy converter
     SchoolName                           PhaseOfEducationDesc
1    Academy 360                          Not applicable
2    Academy 360                          Not applicable
3    Academy 360                          Not applicable
4    Academy 360                          Not applicable
5    Academy 360                          Not applicable
6    Academy 360                          Not applicable
7    Academy 360                          Secondary
8    Academy 360                          Not applicable
9    Academy 360                          Not applicable
10   Academy 360                          Not applicable
11   Academy 360                          Not applicable
12   Academy 360                          Not applicable
13   Academy 360                          Not applicable
14   Academy 360                          Not applicable
15   Academy 360                          Not applicable
16   Academy 360                          NA
17   Academy 360                          NA
18   Academy 360                          NA
19   Academy 360                          NA
20   Academy 360                          NA
21   All Saints Church of England Academy Not applicable
22   All Saints Church of England Academy Not applicable
23   All Saints Church of England Academy Secondary
24   All Saints Church of England Academy Secondary
25   All Saints Church of England Academy Secondary
26   All Saints Church of England Academy Secondary
27   All Saints Church of England Academy Secondary
28   All Saints Church of England Academy Secondary
29   All Saints Church of England Academy Secondary
30   All Saints Church of England Academy Secondary
⋮    ⋮                                    ⋮
3195 Wrenn School                         Secondary
3196 Wrenn School                         Secondary
3197 Wrenn School                         Secondary
3198 Wrenn School                         Secondary
3199 Yardleys School                      Secondary
3200 Yardleys School                      Secondary
3201 Yardleys School                      Secondary
3202 Yardleys School                      Secondary
3203 Yardleys School                      Secondary
3204 Yardleys School                      Secondary
3205 Yardleys School                      Secondary
3206 Yardleys School                      Secondary
3207 Yardleys School                      Secondary
3208 Yardleys School                      Secondary
3209 Yardleys School                      Secondary
3210 Yardleys School                      Secondary
3211 Yardleys School                      Secondary
3212 Yardleys School                      Secondary
3213 Yardleys School                      Secondary
3214 Yardleys School                      Secondary
3215 Yardleys School                      Secondary
3216 Yardleys School                      Secondary
3217 Yardleys School                      Secondary
3218 Yardleys School                      Secondary
3219 Yardleys School                      Secondary
3220 Yardleys School                      Secondary
3221 Yardleys School                      Secondary
3222 Yardleys School                      Secondary
3223 Yardleys School                      Secondary
3224 Yardleys School                      Secondary

#### Save school info to csv

In [477]:
write.csv(schools_filtered, "data/schools_filtered.csv", row.names = FALSE)

#### Join matched schools data to enrolments table

In [480]:
enrol_final <- enrol_filtered |>
    left_join(schools_filtered, by = join_by(SchoolID, AcademicYear))

In [481]:
enrol_final |>
    arrange(person_id, AcademicYear)

      person_id                                                        SchoolID
1     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD   980
2     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD   980
3     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD   980
4     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD   980
5     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 17485
6     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29  2204
7     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29  2204
8     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 16026
9     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 16026
10    00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29 16026
11    0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 15042
12    0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 15042
13    0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 15042
14    0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 15042
15    0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D 15042
16    0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7   852
17    0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7   852
18    0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7   852
19    0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 17296
20    0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7 17296
21    00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66   641
22    00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66   641
23    00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66   641
24    00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66   641
25    00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66   641
26    0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D  1716
27    0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D  1716
28    0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D  1716
29    0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D  1716
30    0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D 17102
⋮     ⋮                                                                ⋮
85394 FFEF2AA9E8BD72D6A0E7CE50F067E4247E12738F53AE726CD94A4D9CB588C702  7013
85395 FFEF2AA9E8BD72D6A0E7CE50F067E4247E12738F53AE726CD94A4D9CB588C702   980
85396 FFEF2AA9E8BD72D6A0E7CE50F067E4247E12738F53AE726CD94A4D9CB588C702   980
85397 FFEF2AA9E8BD72D6A0E7CE50F067E4247E12738F53AE726CD94A4D9CB588C702   980
85398 FFEF2AA9E8BD72D6A0E7CE50F067E4247E12738F53AE726CD94A4D9CB588C702 17485
85399 FFEFD5577D0112E9304118DB7851CF61BEE4DD3D3184EEA756C076317925508F 10875
85400 FFEFD5577D0112E9304118DB7851CF61BEE4DD3D3184EEA756C076317925508F 10875
85401 FFEFD5577D0112E9304118DB7851CF61BEE4DD3D3184EEA756C076317925508F 10875
85402 FFEFD5577D0112E9304118DB7851CF61BEE4DD3D3184EEA756C076317925508F 10875
85403 FFEFD5577D0112E9304118DB7851CF61BEE4DD3D3184EEA756C076317925508F 10875
85404 FFFA6705A275195BFE8A443AF0BD2AA86B1AA0481D330D8665813206EB8DAD43 10875
85405 FFFA6705A275195BFE8A443AF0BD2AA86B1AA0481D330D8665813206EB8DAD43 10875
85406 FFFA6705A275195BFE8A443AF0BD2AA86B1AA0481D330D8665813206EB8DAD43 10875
85407 FFFA6705A275195BFE8A443AF0BD2AA86B1AA0481D330D8665813206EB8DAD43 10875
85408 FFFA6705A275195BFE8A443AF0BD2AA86B1AA0481D330D8665813206EB8DAD43 18286
85409 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77 12433
85410 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77 12433
85411 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77 12433
85412 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77 12433
85413 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77 12433
85414 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398  1340
85415 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398  1340
85416 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398  1340
85417 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 17165
85418 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398 17165
85419 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92  1716
85420 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92  1716
85421 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92  1716
85422 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92  1716
85423 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92 17102
      AcademicYear OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate
1     2012/2013    1        1        1        C           2012-09-04
2     2013/2014    1        1        1        C           2012-09-04
3     2014/2015    1        1        1        C           2012-09-04
4     2015/2016    1        1        NA       C           2012-09-04
5     2016/2017    1        1        0        C           2016-10-01
6     2012/2013    1        1        1        C           2012-09-04
7     2013/2014    1        1        NA       C           2012-09-04
8     2014/2015    1        1        1        C           2014-09-01
9     2015/2016    1        1        1        C           2014-09-01
10    2016/2017    1        1        0        C           2014-09-01
11    2013/2014    1        1        1        C           2013-09-03
12    2014/2015    1        1        1        C           2013-09-03
13    2015/2016    1        1        1        C           2013-09-03
14    2016/2017    1        1        1        C           2013-09-03
15    2017/2018    1        1        0        C           2013-09-03
16    2013/2014    1        1        1        C           2013-09-09
17    2014/2015    1        1        1        C           2013-09-09
18    2015/2016    1        1        NA       C           2013-09-09
19    2016/2017    1        1        1        C           2016-09-01
20    2017/2018    1        1        0        C           2016-09-01
21    2012/2013    1        1        1        C           2012-09-03
22    2013/2014    1        1        1        C           2012-09-03
23    2014/2015    1        1        1        C           2012-09-03
24    2015/2016    1        1        1        C           2012-09-03
25    2016/2017    1        1        1        C           2012-09-03
26    2012/2013    1        1        1        C           2012-09-03
27    2013/2014    1        1        1        C           2012-09-03
28    2014/2015    1        1        1        C           2012-09-03
29    2015/2016    1        1        1        C           2012-09-03
30    2016/2017    NA       1        0        C           2012-09-03
⋮     ⋮            ⋮        ⋮        ⋮        ⋮           ⋮
85394 2012/2013    1        1        0        C           2004-11-08
85395 2013/2014    1        1        1        C           2013-09-05
85396 2014/2015    1        1        1        C           2013-09-05
85397 2015/2016    1        1        NA       C           2013-09-05
85398 2016/2017    1        1        1        C           2016-10-01
85399 2012/2013    1        1        1        C           2012-09-03
85400 2013/2014    1        1        1        C           2012-09-03
85401 2014/2015    1        1        1        C           2012-09-03
85402 2015/2016    1        1        1        C           2012-09-03
85403 2016/2017    1        1        NA       C           2012-09-03
85404 2013/2014    1        1        1        C           2013-09-09
85405 2014/2015    1        1        1        C           2013-09-09
85406 2015/2016    1        1        1        C           2013-09-09
85407 2016/2017    1        1        NA       C           2013-09-09
85408 2017/2018    1        1        0        C           2017-09-01
85409 2013/2014    1        1        1        C           2013-09-02
85410 2014/2015    1        1        1        C           2013-09-02
85411 2015/2016    1        1        1        C           2013-09-02
85412 2016/2017    1        1        1        C           2013-09-02
85413 2017/2018    1        1        0        C           2013-09-02
85414 2013/2014    1        1        1        C           2013-09-02
85415 2014/2015    1        1        1        C           2013-09-02
85416 2015/2016    1        1        NA       C           2013-09-02
85417 2016/2017    1        1        1        C           2016-09-21
85418 2017/2018    1        1        0        C           2016-09-01
85419 2012/2013    1        1        1        C           2012-09-03
85420 2013/2014    1        1        1        C           2012-09-03
85421 2014/2015    1        1        1        C           2012-09-03
85422 2015/2016    1        1        1        C           2012-09-03
85423 2016/2017    NA       1        0        C           2012-09-03
      LeavingDate PartTime NCCIS_ACADYR URN    InstitutionTypeDesc
1     <NA>        0        2017/2018    107442 Foundation school
2     <NA>        0        2017/2018    107442 Foundation school
3     <NA>        0        2017/2018    107442 Foundation school
4     <NA>        0        2017/2018    107442 Foundation school
5     2017-06-30  0        2017/2018    143114 Academy sponsor led
6     <NA>        0        2017/2018    107429 Voluntary aided school
7     <NA>        0        2017/2018    107429 Voluntary aided school
8     <NA>        0        2017/2018    140569 Voluntary aided school
9     <NA>        0        2017/2018    140569 Voluntary aided school
10    2017-07-21  0        2017/2018    140569 Voluntary aided school
11    <NA>        0        2018/2019    136529 Academy converter
12    <NA>        0        2018/2019    136529 Academy converter
13    <NA>        0        2018/2019    136529 Academy converter
14    <NA>        0        2018/2019    136529 Academy converter
15    2018-06-29  0        2018/2019    136529 Academy converter
16    <NA>        0        2018/2019    107441 Foundation school
17    <NA>        0        2018/2019    107441 Foundation school
18    <NA>        0        2018/2019    107441 Foundation school
19    <NA>        0        2018/2019    143112 Academy sponsor led
20    2018-07-20  0        2018/2019    143112 Academy sponsor led
21    <NA>        0        2017/2018    108087 Community school
22    <NA>        0        2017/2018    108087 Community school
23    <NA>        0        2017/2018    108087 Foundation school
24    <NA>        0        2017/2018    108087 Foundation school
25    <NA>        0        2017/2018    108087 Foundation school
26    <NA>        0        2017/2018    107366 Foundation school
27    <NA>        0        2017/2018    107366 Foundation school
28    <NA>        0        2017/2018    107366 Foundation school
29    <NA>        0        2017/2018    107366 Foundation school
30    2017-07-21  0        2017/2018    142761 Academy sponsor led
⋮     ⋮           ⋮        ⋮            ⋮      ⋮
85394 <NA>        0        2017/2018    107203 Community school
85395 <NA>        0        2017/2018    107442 Foundation school
85396 <NA>        0        2017/2018    107442 Foundation school
85397 <NA>        0        2017/2018    107442 Foundation school
85398 <NA>        0        2017/2018    143114 Academy sponsor led
85399 <NA>        0        2017/2018    135865 Academy sponsor led
85400 <NA>        0        2017/2018    135865 Academy sponsor led
85401 <NA>        0        2017/2018    135865 Academy sponsor led
85402 <NA>        0        2017/2018    135865 Academy sponsor led
85403 <NA>        0        2017/2018    135865 Academy sponsor led
85404 <NA>        0        2018/2019    135865 Academy sponsor led
85405 <NA>        0        2018/2019    135865 Academy sponsor led
85406 <NA>        0        2018/2019    135865 Academy sponsor led
85407 <NA>        0        2018/2019    135865 Academy sponsor led
85408 2018-06-29  0        2018/2019    145173 Academy sponsor led
85409 <NA>        0        2018/2019    136736 Academy converter
85410 <NA>        0        2018/2019    136736 Academy converter
85411 <NA>        0        2018/2019    136736 Academy converter
85412 <NA>        0        2018/2019    136736 Academy converter
85413 2018-08-31  0        2018/2019    136736 Academy converter
85414 <NA>        0        2018/2019    107350 Foundation school
85415 <NA>        0        2018/2019    107350 Foundation school
85416 <NA>        0        2018/2019    107350 Foundation school
85417 <NA>        0        2018/2019    142825 Academy sponsor led
85418 2018-07-20  0        2018/2019    142825 Academy sponsor led
85419 <NA>        0        2017/2018    107366 Foundation school
85420 <NA>        0        2017/2018    107366 Foundation school
85421 <NA>        0        2017/2018    107366 Foundation school
85422 <NA>        0        2017/2018    107366 Foundation school
85423 2017-07-21  0        2017/2018    142761 Academy sponsor led
      SchoolName                                      PhaseOfEducationDesc
1     Thornton Grammar School                         Secondary
2     Thornton Grammar School                         Secondary
3     Thornton Grammar School                         Secondary
4     Thornton Grammar School                         Secondary
5     Beckfoot Thornton                               Secondary
6     St Josephs Catholic College                     Secondary
7     St Josephs Catholic College                     Secondary
8     St Bedes and St Josephs Catholic College        Secondary
9     St Bedes and St Josephs Catholic College        Secondary
10    St Bedes and St Josephs Catholic College        Secondary
11    Sunbury Manor School                            Secondary
12    Sunbury Manor School                            Secondary
13    Sunbury Manor School                            Secondary
14    Sunbury Manor School                            Secondary
15    Sunbury Manor School                            Secondary
16    Oakbank School                                  Secondary
17    Oakbank School                                  Secondary
18    Oakbank School                                  Secondary
19    Beckfoot Oakbank                                Secondary
20    Beckfoot Oakbank                                Secondary
21    Priesthorpe School                              Secondary
22    Priesthorpe School                              Secondary
23    Priesthorpe School                              Secondary
24    Priesthorpe School                              Secondary
25    Priesthorpe School                              Secondary
26    Tong High School                                Secondary
27    Tong High School                                Secondary
28    Tong High School                                Secondary
29    Tong High School                                Secondary
30    Tong Leadership Academy                         Secondary
⋮     ⋮                                               ⋮
85394 Crossley Hall Primary School                    Primary
85395 Thornton Grammar School                         Secondary
85396 Thornton Grammar School                         Secondary
85397 Thornton Grammar School                         Secondary
85398 Beckfoot Thornton                               Secondary
85399 Appleton Academy                                Not applicable
85400 Appleton Academy                                Secondary
85401 Appleton Academy                                Not applicable
85402 Appleton Academy                                Not applicable
85403 Appleton Academy                                Not applicable
85404 Appleton Academy                                Secondary
85405 Appleton Academy                                Not applicable
85406 Appleton Academy                                Not applicable
85407 Appleton Academy                                Not applicable
85408 Appleton Academy                                NA
85409 South Craven School                             Secondary
85410 South Craven School                             Secondary
85411 South Craven School                             Secondary
85412 South Craven School                             Secondary
85413 South Craven School                             Secondary
85414 Buttershaw Business and Enterprise College      Secondary
85415 Buttershaw Business and Enterprise College      Secondary
85416 Buttershaw Business and Enterprise College      Secondary
85417 Buttershaw Business  Enterprise College Academy Secondary
85418 Buttershaw Business  Enterprise College Academy Secondary
85419 Tong High School                                Secondary
85420 Tong High School                                Secondary
85421 Tong High School                                Secondary
85422 Tong High School                                Secondary
85423 Tong Leadership Academy                         Secondary

#### check how many school moves in the data

In [482]:
id_lists <- enrol_final |>
    select(person_id, SchoolName)

In [483]:
#id_lists

In [484]:
# n = 85,423
head(id_lists)

  person_id
1 F65B08C0ABA0DF84D9BD65F7FED88E1D5DAD42AAB47392CE2D9543AED4E245DD
2 F97D233CF64E3EAC93369EAAA28D9E5193785F4BA369A53A716A1B453B9FDDA2
3 3E4432F9D7005D74AB24D68A875EC38A8DA0234A2D67666F935999C059682696
4 823AECF1EFC7F8CD963B2B16D2C886922CD9F7C0CA4B478BD07E86F163685822
5 18746FF26D6AC95D757A4B4CB10B01DE6F041115B43ECC8BE0C4A0AEF575224B
6 0D5BABE74A35CC1F64DB2C1F97898AD55B2DF12975FE992FE28487B958392B33
  SchoolName
1 South Craven School
2 Appleton Academy
3 Gloucester Academy
4 Endeavour High School
5 Coop Academy Leeds
6 Appleton Academy

In [485]:
distinct(id_lists)

      person_id
1     F65B08C0ABA0DF84D9BD65F7FED88E1D5DAD42AAB47392CE2D9543AED4E245DD
2     F97D233CF64E3EAC93369EAAA28D9E5193785F4BA369A53A716A1B453B9FDDA2
3     3E4432F9D7005D74AB24D68A875EC38A8DA0234A2D67666F935999C059682696
4     823AECF1EFC7F8CD963B2B16D2C886922CD9F7C0CA4B478BD07E86F163685822
5     18746FF26D6AC95D757A4B4CB10B01DE6F041115B43ECC8BE0C4A0AEF575224B
6     0D5BABE74A35CC1F64DB2C1F97898AD55B2DF12975FE992FE28487B958392B33
7     A73E48D704D747B6822F8D7DAE261C7F719BB3B878CDB3FD1973B4C3567F41B7
8     8D925CADDE220244727D160F216F678F9D0871E5857020A5DBBAFA272F6F043C
9     E4E0CCAD6B73017977DB911E9788BB7A4147275CF81C7872FB2636976920FB14
10    F9026D7D68091400D4D012353A0D96CA356D6E3F03C6660683ED54878DE2A783
11    85C8DD46133840E7D6F386A8319895576274621CA94417B40269DA3F1E0BC709
12    F05F62154413772E633873EA13C98B2118A6AB17B2A0DDE517BF6AD279CED603
13    BADB11CB4131159369583E7DB6882DB1999CB271985F9E448E522F2B872BB1AD
14    940A5EFB039A76578CB3FD1288ADF9E47EE48F1A85ED809D2D4B74DF76389544
15    DD540D8041A729CC5EC347A0FCB773C2459B0DD561F84E910B555F987C03EB64
16    F24D230DB5A9B4CB989490D504C9BCE2E8F5451FE47B896DF9CF56417603502F
17    665E7413AF78D3C4C7BE9ECF8B4B40ADB42C29F23D9D0C96E43F68964BDD5C25
18    8106EE50D3345843123922B530177738246B986429AE6E5A743BCB734F8DFB0E
19    5C4341701F0573FB1CAA44BB7FA5ADC9554337B8821CC317E6C008FB14D27522
20    D385DBB39ACE57935F6819D4A4E69B3356961D208BE061A3905B1CE8A57941E6
21    50079893178E222D8EB23DE5A41034E88F8FFD963818FD653CCF7C7564806575
22    D6BC64956E2D60F755144D2D65C22DBC494A454498BB3D37329DB45FC17AECCC
23    73E1F808454E7D5FB573FE0C6240306077E8D65F1AD3E9E4CB38D52AACF78475
24    598D2ABA211CD1BB40BCEA62BABFFB6B278389944E40C26E6C00AAB1E3A86F2F
25    FAAEA04C1AEBF61AACCA6DE784451E4BDC718BB9B8422891BB0DA6EF8178B2AD
26    C71E884C9A517CC0F5EF391C0E8773062A70803E24286211E5027C5CC15DFE93
27    F5143F71DE209C4EBF5F5F1D076C45A36D701BE945189C654EE2F150839F47C8
28    BB1C7F4FC50A60FF728A48C7F2A3C4496F2E6765FA62119EBBF5ABB6FB133735
29    275233F9093562C88D2E0AD740F124670FD9641B2AEC1B6F77BA65E887B4E57C
30    7190286B633CCFBB92754A8A3F914CC83DA1055FF68ABA30B8E3BC19466DA3BD
⋮     ⋮
24659 D1EE08EAD61F5A0EAAA4DED9BFCB418F8FEE6645CF973C9286D4E55AAEAB0F7D
24660 460DE6421AA9296DE8E10B0636DC1C2126747B2DCF3E106DB1E92164D29B0B94
24661 15F1970C4036BDCED90AEA4B07AE94EE7A85A8D9AECE0327A582F69211A84E71
24662 A26C103463F0FCEC6212A7BCE763E627E221E9F0ABDF45246C92E7BC89F9F23E
24663 CE3CCA2E1CEC2A2CA3D32D1BBE363FDA8F1E244E62DC54FC2B9B6F9162BA740E
24664 665CB1CC4A5C9DEEFE01C7E4EA9E9008A9B87D8BF9A2D281BB8FAC4215360D63
24665 A5E508F0F25296DCD8A22510C1B4BB10FDF437A10B8F4F642EDC67C3C13BB39B
24666 94A6201DA0ED800C491A5BF2388B497383993D4DD7E07FF185F6235BB5B8E177
24667 A5769B74A26B213841A9DCF5EEA97D13667A8ACA8A7DE154C16889B5353981FD
24668 5D05E92BDA8A84E4C3ADBD1CA8FE85B55E7D975053AFDDBF8C0CC41B7ADA6490
24669 55BFDA553FFA676138363C440FA92FBA9C4FDAB8C05106C36EB63FEEE69C892C
24670 512A1F7B0432E31078ECE8C646D5A705D83C8F9D8494762478B57F149138C2C1
24671 1C13D8CFB2CDF4B3A9A4E7166CB109247B25499EFA871B6FA8C0ACC6EF9B0196
24672 0EDA649D7867C2987EE2CA4366D1E6711439C33B9EB1FC57FAB0CD9FDAA9A43F
24673 082F187839A64780AEBB97CB5E849DDFE3586BF3A40898F6DF98F88093DDD6B8
24674 7635F1CBDF80885E29AAF46C036813E6F7FDDDB85A6A782437E6E4EAB9ECFB92
24675 0EA219DB3F84A21FF1BB9214981CEC6D57529478B5B7FB349532A00DDA3590CD
24676 00BF5E6DE674A947022F50519AB58C91970094F5A233D7A8A182CC8713038FD6
24677 AF4935AEE3B6001AA88F27EB00E9E4BC036B12A47E154316A60063F6ECCDA33A
24678 03140E8ED8725036CB240A7CFD174B2C5C1508B93A547649D2DDF1DBE01CC3ED
24679 2EAD9727A95A5710435CD3494C8A56A16F3079CCDE2697603D25FC2CA4C945AC
24680 B0FB176BA5AA43DCB2395DC3E8853E41EEDC7B62A86AD3B69D73C4DB7B63100C
24681 D756F64F43E91C5D30DDBF7B4FA73611BEC007E37E42BF6C2C558B7ED46A2CFA
24682 40C31E0E3726704907E720948AF22D6565BE912A5DCFAE5A4D54C123A423BD5A
24683 EAA3977717EC734FCDF89D89A0ABB800CA87C2F7B7C6E9DE27A388B063EB6D64
24684 DF3A6AF49CDBCD9209CB85F386E1E9E22E0C5CF64991B411DC16AD7C79451798
24685 8D256B0FCD45194625B381CC022DB2476D34B2AC03F1EB1837F30AE6813D4FD2
24686 039C210169336690B964CFB3A92B4DAE819284CAE17A2755FB51C0AA733ED869
24687 05ED71E2362D0C7590E9D0D18CCFAAEA41E61FA4DE962B572F99480F2897637B
24688 1E46F1FC14ADF9BF0E9469040F116241394E8641F0BB20390E994E62B0CAC09A
      SchoolName
1     South Craven School
2     Appleton Academy
3     Gloucester Academy
4     Endeavour High School
5     Coop Academy Leeds
6     Appleton Academy
7     Appleton Academy
8     Appleton Academy
9     Appleton Academy
10    Appleton Academy
11    Appleton Academy
12    Appleton Academy
13    The Castle School
14    Cardinal Heenan Catholic High School
15    BBG Academy
16    BBG Academy
17    Hanson School
18    Hanson School
19    Tracks
20    Grange Technology College
21    Belle Vue Girls Academy
22    The Samuel Lister Academy
23    Beckfoot School
24    Outwood Grange Academy
25    Bellingham Middle School and Sports College
26    The Darley Centre
27    Beckfoot Upper Heaton
28    Allenbourn Middle School
29    Swallow Hill Community College
30    Excelsior Academy
⋮     ⋮
24659 Bingley Grammar School
24660 Dixons Kings Academy
24661 Tong High School
24662 The Challenge College
24663 Firth Park Community Arts College
24664 The Challenge College
24665 The Challenge College
24666 St Marys Catholic Comprehensive School Menston
24667 Manchester Academy
24668 St Marys Catholic Comprehensive School Menston
24669 The Challenge College
24670 The Challenge College
24671 St Marys Catholic Comprehensive School Menston
24672 Priesthorpe School
24673 Tong Leadership Academy
24674 Tong Leadership Academy
24675 Tong Leadership Academy
24676 Tong Leadership Academy
24677 Carlton Bolling College
24678 Skerton Community High School
24679 Oakbank School
24680 Thornton Grammar School
24681 Queensbury School
24682 Tong High School
24683 Immanuel College
24684 Bingley Grammar School
24685 Swallow Hill Community College
24686 Coop Academy Priesthorpe
24687 Bradford Central PRU
24688 Highfield Leadership Academy

In [486]:
# n = 24,688
id_lists_distinct <- distinct(id_lists)

In [487]:
person_counts <- table(id_lists_distinct$person_id)
summary <- table(person_counts)

In [488]:
as.data.frame(summary)

  person_counts Freq
1 1             10792
2 2              5050
3 3               808
4 4               219
5 5                70
6 6                18
7 7                 2
8 8                 3

#### Explore high school count ids

In [489]:
enrol_final |> 
    filter(person_id == '38C38B72800AB59D24A9677F19DB0C3872F37209D24BC03DA9F68E7543CF333F') |>
    arrange(AcademicYear, EntryDate)

  person_id                                                        SchoolID
1 38C38B72800AB59D24A9677F19DB0C3872F37209D24BC03DA9F68E7543CF333F  1562
2 38C38B72800AB59D24A9677F19DB0C3872F37209D24BC03DA9F68E7543CF333F  1562
3 38C38B72800AB59D24A9677F19DB0C3872F37209D24BC03DA9F68E7543CF333F 15223
4 38C38B72800AB59D24A9677F19DB0C3872F37209D24BC03DA9F68E7543CF333F   344
5 38C38B72800AB59D24A9677F19DB0C3872F37209D24BC03DA9F68E7543CF333F   344
6 38C38B72800AB59D24A9677F19DB0C3872F37209D24BC03DA9F68E7543CF333F 14447
7 38C38B72800AB59D24A9677F19DB0C3872F37209D24BC03DA9F68E7543CF333F 14447
8 38C38B72800AB59D24A9677F19DB0C3872F37209D24BC03DA9F68E7543CF333F 14447
  AcademicYear OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate  LeavingDate
1 2012/2013    1        1        1        C           2012-09-03 <NA>
2 2013/2014    1        0        0        C           2012-09-03 2014-04-03
3 2013/2014    0        NA       NA       NA          2013-09-24 2013-12-13
4 2013/2014    NA       1        1        C           2014-04-04 <NA>
5 2014/2015    1        0        0        M           2014-04-04 2015-02-23
6 2014/2015    0        NA       NA       S           2014-10-02 2014-11-14
7 2015/2016    1        1        1        C           2014-10-02 <NA>
8 2016/2017    1        1        0        C           2014-10-02 2017-06-30
  PartTime NCCIS_ACADYR URN    InstitutionTypeDesc SchoolName
1 0        2017/2018    107440 Foundation school   Hanson School
2 0        2017/2018    107440 Foundation school   Hanson School
3 0        2017/2018    133411 AP/PRU              Bradford Central PRU
4 0        2017/2018    107563 Community school    Sowerby Bridge High School
5 0        2017/2018    107563 Community school    Sowerby Bridge High School
6 0        2017/2018    133693 AP/PRU              Calderdale PRU
7 0        2017/2018    133693 AP/PRU              Calderdale PRU
8 0        2017/2018    133693 AP/PRU              Calderdale PRU
  PhaseOfEducationDesc
1 Secondary
2 Secondary
3 Not applicable
4 Secondary
5 Secondary
6 Not applicable
7 Not applicable
8 Not applicable

#### create a table of person_id and school count

In [490]:
# create a new col with count to match with destinations
school_count <- id_lists_distinct %>%
  group_by(person_id) %>%
  mutate(n_schools = n()) %>%
  ungroup()

In [491]:
head(school_count)

  person_id
1 F65B08C0ABA0DF84D9BD65F7FED88E1D5DAD42AAB47392CE2D9543AED4E245DD
2 F97D233CF64E3EAC93369EAAA28D9E5193785F4BA369A53A716A1B453B9FDDA2
3 3E4432F9D7005D74AB24D68A875EC38A8DA0234A2D67666F935999C059682696
4 823AECF1EFC7F8CD963B2B16D2C886922CD9F7C0CA4B478BD07E86F163685822
5 18746FF26D6AC95D757A4B4CB10B01DE6F041115B43ECC8BE0C4A0AEF575224B
6 0D5BABE74A35CC1F64DB2C1F97898AD55B2DF12975FE992FE28487B958392B33
  SchoolName            n_schools
1 South Craven School   2
2 Appleton Academy      3
3 Gloucester Academy    2
4 Endeavour High School 2
5 Coop Academy Leeds    1
6 Appleton Academy      2

# Pivot Long for terms then Pivot Wide for years

In [492]:
head(enrol_final)

  person_id                                                        SchoolID
1 F65B08C0ABA0DF84D9BD65F7FED88E1D5DAD42AAB47392CE2D9543AED4E245DD 12433
2 F97D233CF64E3EAC93369EAAA28D9E5193785F4BA369A53A716A1B453B9FDDA2 10875
3 3E4432F9D7005D74AB24D68A875EC38A8DA0234A2D67666F935999C059682696 11365
4 823AECF1EFC7F8CD963B2B16D2C886922CD9F7C0CA4B478BD07E86F163685822  1431
5 18746FF26D6AC95D757A4B4CB10B01DE6F041115B43ECC8BE0C4A0AEF575224B 14276
6 0D5BABE74A35CC1F64DB2C1F97898AD55B2DF12975FE992FE28487B958392B33 18286
  AcademicYear OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate  LeavingDate
1 2017/2018    1        1        1        C           <NA>       <NA>
2 2014/2015    0        0        NA       NA          2014-11-10 2015-01-08
3 2017/2018    1        1        0        C           2014-11-10 2018-06-29
4 2012/2013    1        1        0        C           2012-10-04 <NA>
5 2016/2017    1        1        0        C           2012-10-04 2017-06-30
6 2017/2018    1        1        1        C           2017-09-01 <NA>
  PartTime NCCIS_ACADYR URN    InstitutionTypeDesc SchoolName
1 0        2018/2019    136736 Academy converter   South Craven School
2 0        2017/2018    135865 Academy sponsor led Appleton Academy
3 0        2018/2019    136199 Academy sponsor led Gloucester Academy
4 0        2017/2018    133422 Community school    Endeavour High School
5 0        2017/2018    137065 Academy sponsor led Coop Academy Leeds
6 0        2018/2019    145173 Academy sponsor led Appleton Academy
  PhaseOfEducationDesc
1 Secondary
2 Not applicable
3 Secondary
4 Secondary
5 Secondary
6 NA

In [493]:
school_per_term <- enrol_final |>
    select(-c(SchoolID, PartTime, SchoolName, InstitutionTypeDesc, PhaseOfEducationDesc))

In [494]:
head(school_per_term)

  person_id                                                        AcademicYear
1 F65B08C0ABA0DF84D9BD65F7FED88E1D5DAD42AAB47392CE2D9543AED4E245DD 2017/2018
2 F97D233CF64E3EAC93369EAAA28D9E5193785F4BA369A53A716A1B453B9FDDA2 2014/2015
3 3E4432F9D7005D74AB24D68A875EC38A8DA0234A2D67666F935999C059682696 2017/2018
4 823AECF1EFC7F8CD963B2B16D2C886922CD9F7C0CA4B478BD07E86F163685822 2012/2013
5 18746FF26D6AC95D757A4B4CB10B01DE6F041115B43ECC8BE0C4A0AEF575224B 2016/2017
6 0D5BABE74A35CC1F64DB2C1F97898AD55B2DF12975FE992FE28487B958392B33 2017/2018
  OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate  LeavingDate NCCIS_ACADYR
1 1        1        1        C           <NA>       <NA>        2018/2019
2 0        0        NA       NA          2014-11-10 2015-01-08  2017/2018
3 1        1        0        C           2014-11-10 2018-06-29  2018/2019
4 1        1        0        C           2012-10-04 <NA>        2017/2018
5 1        1        0        C           2012-10-04 2017-06-30  2017/2018
6 1        1        1        C           2017-09-01 <NA>        2018/2019
  URN
1 136736
2 135865
3 136199
4 133422
5 137065
6 145173

C = Current (single registration at this school)
G = Guest (pupil not registered at this school but attending some lessons or sessions)
M = Current Main (dual registration)
S = Current Subsidiary (dual registration)
F = FE College (since 2014/15)
O = Other provider (since 2014/15)

In [495]:
school_per_term |> distinct(EnrolStatus) |> pull(EnrolStatus)

[1] "C" NA  "S" "O" "M" "F"

In [496]:
school_per_term |> 
    filter(person_id == '56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB' ) |>
    arrange(AcademicYear, EntryDate)

  person_id                                                        AcademicYear
1 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB 2012/2013
2 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB 2012/2013
3 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB 2013/2014
4 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB 2014/2015
5 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB 2014/2015
6 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB 2014/2015
7 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB 2015/2016
8 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB 2015/2016
9 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB 2016/2017
  OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate  LeavingDate NCCIS_ACADYR
1 0        NA       NA       C           2012-09-03 2012-10-05  2017/2018
2 1        1        1        C           2012-10-04 <NA>        2017/2018
3 1        1        1        C           2012-10-04 <NA>        2017/2018
4 1        1        1        M           2012-10-04 <NA>        2017/2018
5 0        NA       NA       S           2014-09-26 2014-11-27  2017/2018
6 1        0        NA       C           2014-12-10 2015-02-13  2017/2018
7 0        NA       NA       M           2012-10-04 2015-11-06  2017/2018
8 1        1        1        O           2015-11-09 <NA>        2017/2018
9 1        1        0        C           2015-11-09 2017-06-30  2017/2018
  URN
1 107366
2 135367
3 135367
4 135367
5 107350
6 133411
7 135367
8 135732
9 135732

In [497]:
enrol_final |> 
    filter(person_id == '56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB' ) |>
    arrange(AcademicYear, EntryDate)

  person_id                                                        SchoolID
1 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB  1716
2 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB  9574
3 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB  9574
4 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB  9574
5 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB  1340
6 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB 15223
7 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB  9574
8 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB 15167
9 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB 15167
  AcademicYear OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate  LeavingDate
1 2012/2013    0        NA       NA       C           2012-09-03 2012-10-05
2 2012/2013    1        1        1        C           2012-10-04 <NA>
3 2013/2014    1        1        1        C           2012-10-04 <NA>
4 2014/2015    1        1        1        M           2012-10-04 <NA>
5 2014/2015    0        NA       NA       S           2014-09-26 2014-11-27
6 2014/2015    1        0        NA       C           2014-12-10 2015-02-13
7 2015/2016    0        NA       NA       M           2012-10-04 2015-11-06
8 2015/2016    1        1        1        O           2015-11-09 <NA>
9 2016/2017    1        1        0        C           2015-11-09 2017-06-30
  PartTime NCCIS_ACADYR URN    InstitutionTypeDesc
1 0        2017/2018    107366 Foundation school
2 0        2017/2018    135367 Academy sponsor led
3 0        2017/2018    135367 Academy sponsor led
4 0        2017/2018    135367 Academy sponsor led
5 0        2017/2018    107350 Foundation school
6 0        2017/2018    133411 AP/PRU
7 0        2017/2018    135367 Academy sponsor led
8 0        2017/2018    135732 AP/PRU
9 0        2017/2018    135732 AP/PRU
  SchoolName                                 PhaseOfEducationDesc
1 Tong High School                           Secondary
2 Bradford Academy                           Not applicable
3 Bradford Academy                           Secondary
4 Bradford Academy                           Not applicable
5 Buttershaw Business and Enterprise College Secondary
6 Bradford Central PRU                       Not applicable
7 Bradford Academy                           Not applicable
8 Bradford District PRU                      Not applicable
9 Bradford District PRU                      Not applicable

#### pivot long

In [498]:
pivot_long <- school_per_term %>%
  pivot_longer(
    cols = starts_with("OnRoll_"),            
    names_to = "Term",                        # new column name for term
    values_to = "OnRoll",                     # values (0, 1, or NA)
    names_prefix = "OnRoll_"                  # remove this prefix from 'Term'
  )

In [499]:
pivot_long |>
    arrange(person_id, AcademicYear, Term)

       person_id
1      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
3      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
4      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
5      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
6      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
7      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
8      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
9      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
10     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
11     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
12     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
13     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
14     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
15     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
16     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
17     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
18     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
19     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
20     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
21     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
22     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
23     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
24     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
25     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
26     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
27     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
28     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
29     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
30     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
⋮      ⋮
256240 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
256241 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
256242 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
256243 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
256244 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
256245 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
256246 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
256247 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
256248 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
256249 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
256250 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
256251 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
256252 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
256253 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
256254 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
256255 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
256256 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
256257 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
256258 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
256259 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
256260 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
256261 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
256262 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
256263 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
256264 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
256265 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
256266 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
256267 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
256268 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
256269 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
       AcademicYear EnrolStatus EntryDate  LeavingDate NCCIS_ACADYR URN    Term
1      2012/2013    C           2012-09-04 <NA>        2017/2018    107442 1
2      2012/2013    C           2012-09-04 <NA>        2017/2018    107442 2
3      2012/2013    C           2012-09-04 <NA>        2017/2018    107442 3
4      2013/2014    C           2012-09-04 <NA>        2017/2018    107442 1
5      2013/2014    C           2012-09-04 <NA>        2017/2018    107442 2
6      2013/2014    C           2012-09-04 <NA>        2017/2018    107442 3
7      2014/2015    C           2012-09-04 <NA>        2017/2018    107442 1
8      2014/2015    C           2012-09-04 <NA>        2017/2018    107442 2
9      2014/2015    C           2012-09-04 <NA>        2017/2018    107442 3
10     2015/2016    C           2012-09-04 <NA>        2017/2018    107442 1
11     2015/2016    C           2012-09-04 <NA>        2017/2018    107442 2
12     2015/2016    C           2012-09-04 <NA>        2017/2018    107442 3
13     2016/2017    C           2016-10-01 2017-06-30  2017/2018    143114 1
14     2016/2017    C           2016-10-01 2017-06-30  2017/2018    143114 2
15     2016/2017    C           2016-10-01 2017-06-30  2017/2018    143114 3
16     2012/2013    C           2012-09-04 <NA>        2017/2018    107429 1
17     2012/2013    C           2012-09-04 <NA>        2017/2018    107429 2
18     2012/2013    C           2012-09-04 <NA>        2017/2018    107429 3
19     2013/2014    C           2012-09-04 <NA>        2017/2018    107429 1
20     2013/2014    C           2012-09-04 <NA>        2017/2018    107429 2
21     2013/2014    C           2012-09-04 <NA>        2017/2018    107429 3
22     2014/2015    C           2014-09-01 <NA>        2017/2018    140569 1
23     2014/2015    C           2014-09-01 <NA>        2017/2018    140569 2
24     2014/2015    C           2014-09-01 <NA>        2017/2018    140569 3
25     2015/2016    C           2014-09-01 <NA>        2017/2018    140569 1
26     2015/2016    C           2014-09-01 <NA>        2017/2018    140569 2
27     2015/2016    C           2014-09-01 <NA>        2017/2018    140569 3
28     2016/2017    C           2014-09-01 2017-07-21  2017/2018    140569 1
29     2016/2017    C           2014-09-01 2017-07-21  2017/2018    140569 2
30     2016/2017    C           2014-09-01 2017-07-21  2017/2018    140569 3
⋮      ⋮            ⋮           ⋮          ⋮           ⋮            ⋮      ⋮
256240 2013/2014    C           2013-09-02 <NA>        2018/2019    107350 1
256241 2013/2014    C           2013-09-02 <NA>        2018/2019    107350 2
256242 2013/2014    C           2013-09-02 <NA>        2018/2019    107350 3
256243 2014/2015    C           2013-09-02 <NA>        2018/2019    107350 1
256244 2014/2015    C           2013-09-02 <NA>        2018/2019    107350 2
256245 2014/2015    C           2013-09-02 <NA>        2018/2019    107350 3
256246 2015/2016    C           2013-09-02 <NA>        2018/2019    107350 1
256247 2015/2016    C           2013-09-02 <NA>        2018/2019    107350 2
256248 2015/2016    C           2013-09-02 <NA>        2018/2019    107350 3
256249 2016/2017    C           2016-09-21 <NA>        2018/2019    142825 1
256250 2016/2017    C           2016-09-21 <NA>        2018/2019    142825 2
256251 2016/2017    C           2016-09-21 <NA>        2018/2019    142825 3
256252 2017/2018    C           2016-09-01 2018-07-20  2018/2019    142825 1
256253 2017/2018    C           2016-09-01 2018-07-20  2018/2019    142825 2
256254 2017/2018    C           2016-09-01 2018-07-20  2018/2019    142825 3
256255 2012/2013    C           2012-09-03 <NA>        2017/2018    107366 1
256256 2012/2013    C           2012-09-03 <NA>        2017/2018    107366 2
256257 2012/2013    C           2012-09-03 <NA>        2017/2018    107366 3
256258 2013/2014    C           2012-09-03 <NA>        2017/2018    107366 1
256259 2013/2014    C           2012-09-03 <NA>        2017/2018    107366 2
256260 2013/2014    C           2012-09-03 <NA>        2017/2018    107366 3
256261 2014/2015    C           2012-09-03 <NA>        2017/2018    107366 1
256262 2014/2015    C           2012-09-03 <NA>        2017/2018    107366 2
256263 2014/2015    C           2012-09-03 <NA>        2017/2018    107366 3
256264 2015/2016    C           2012-09-03 <NA>        2017/2018    107366 1
256265 2015/2016    C           2012-09-03 <NA>        2017/2018    107366 2
256266 2015/2016    C           2012-09-03 <NA>        2017/2018    107366 3
256267 2016/2017    C           2012-09-03 2017-07-21  2017/2018    142761 1
256268 2016/2017    C           2012-09-03 2017-07-21  2017/2018    142761 2
256269 2016/2017    C           2012-09-03 2017-07-21  2017/2018    142761 3
       OnRoll
1      1
2      1
3      1
4      1
5      1
6      1
7      1
8      1
9      1
10     1
11     1
12     NA
13     1
14     1
15     0
16     1
17     1
18     1
19     1
20     1
21     NA
22     1
23     1
24     1
25     1
26     1
27     1
28     1
29     1
30     0
⋮      ⋮
256240 1
256241 1
256242 1
256243 1
256244 1
256245 1
256246 1
256247 1
256248 NA
256249 1
256250 1
256251 1
256252 1
256253 1
256254 0
256255 1
256256 1
256257 1
256258 1
256259 1
256260 1
256261 1
256262 1
256263 1
256264 1
256265 1
256266 1
256267 NA
256268 1
256269 0

In [500]:
pivot_long |>
  group_by(person_id, AcademicYear, Term) |>
  filter(n() > 1) |>
  arrange(person_id, AcademicYear, Term)

      person_id
1     004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
2     004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
3     004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
4     004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
5     004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
6     004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
7     0054192801954D860BB235F844AD1CB8A99956B2CF3D4E20F83C650DD6279B58
8     0054192801954D860BB235F844AD1CB8A99956B2CF3D4E20F83C650DD6279B58
9     0054192801954D860BB235F844AD1CB8A99956B2CF3D4E20F83C650DD6279B58
10    0054192801954D860BB235F844AD1CB8A99956B2CF3D4E20F83C650DD6279B58
11    0054192801954D860BB235F844AD1CB8A99956B2CF3D4E20F83C650DD6279B58
12    0054192801954D860BB235F844AD1CB8A99956B2CF3D4E20F83C650DD6279B58
13    0069000F2F3F16C7687450D2AE517987DAFB0E7BAF4C2F19AF109466BC5377D8
14    0069000F2F3F16C7687450D2AE517987DAFB0E7BAF4C2F19AF109466BC5377D8
15    0069000F2F3F16C7687450D2AE517987DAFB0E7BAF4C2F19AF109466BC5377D8
16    0069000F2F3F16C7687450D2AE517987DAFB0E7BAF4C2F19AF109466BC5377D8
17    0069000F2F3F16C7687450D2AE517987DAFB0E7BAF4C2F19AF109466BC5377D8
18    0069000F2F3F16C7687450D2AE517987DAFB0E7BAF4C2F19AF109466BC5377D8
19    0069000F2F3F16C7687450D2AE517987DAFB0E7BAF4C2F19AF109466BC5377D8
20    0069000F2F3F16C7687450D2AE517987DAFB0E7BAF4C2F19AF109466BC5377D8
21    0069000F2F3F16C7687450D2AE517987DAFB0E7BAF4C2F19AF109466BC5377D8
22    0069000F2F3F16C7687450D2AE517987DAFB0E7BAF4C2F19AF109466BC5377D8
23    0069000F2F3F16C7687450D2AE517987DAFB0E7BAF4C2F19AF109466BC5377D8
24    0069000F2F3F16C7687450D2AE517987DAFB0E7BAF4C2F19AF109466BC5377D8
25    00984270C3D5F57B15FBB33EE849BA97F72C4F732D031E981D2C43395F4E5098
26    00984270C3D5F57B15FBB33EE849BA97F72C4F732D031E981D2C43395F4E5098
27    00984270C3D5F57B15FBB33EE849BA97F72C4F732D031E981D2C43395F4E5098
28    00984270C3D5F57B15FBB33EE849BA97F72C4F732D031E981D2C43395F4E5098
29    00984270C3D5F57B15FBB33EE849BA97F72C4F732D031E981D2C43395F4E5098
30    00984270C3D5F57B15FBB33EE849BA97F72C4F732D031E981D2C43395F4E5098
⋮     ⋮
18175 FF77AAB58760E4616819BF69FA7A7D0466EC940FC1B666F5D8FC15261B05FDA7
18176 FF77AAB58760E4616819BF69FA7A7D0466EC940FC1B666F5D8FC15261B05FDA7
18177 FF77AAB58760E4616819BF69FA7A7D0466EC940FC1B666F5D8FC15261B05FDA7
18178 FF77AAB58760E4616819BF69FA7A7D0466EC940FC1B666F5D8FC15261B05FDA7
18179 FF77AAB58760E4616819BF69FA7A7D0466EC940FC1B666F5D8FC15261B05FDA7
18180 FF77AAB58760E4616819BF69FA7A7D0466EC940FC1B666F5D8FC15261B05FDA7
18181 FF7B98BFE21CD2600469C9D7B3C040C06C1AAAB58F51EE3BE5A0E0CA94470300
18182 FF7B98BFE21CD2600469C9D7B3C040C06C1AAAB58F51EE3BE5A0E0CA94470300
18183 FF7B98BFE21CD2600469C9D7B3C040C06C1AAAB58F51EE3BE5A0E0CA94470300
18184 FF7B98BFE21CD2600469C9D7B3C040C06C1AAAB58F51EE3BE5A0E0CA94470300
18185 FF7B98BFE21CD2600469C9D7B3C040C06C1AAAB58F51EE3BE5A0E0CA94470300
18186 FF7B98BFE21CD2600469C9D7B3C040C06C1AAAB58F51EE3BE5A0E0CA94470300
18187 FF7B98BFE21CD2600469C9D7B3C040C06C1AAAB58F51EE3BE5A0E0CA94470300
18188 FF7B98BFE21CD2600469C9D7B3C040C06C1AAAB58F51EE3BE5A0E0CA94470300
18189 FF7B98BFE21CD2600469C9D7B3C040C06C1AAAB58F51EE3BE5A0E0CA94470300
18190 FF7B98BFE21CD2600469C9D7B3C040C06C1AAAB58F51EE3BE5A0E0CA94470300
18191 FF7B98BFE21CD2600469C9D7B3C040C06C1AAAB58F51EE3BE5A0E0CA94470300
18192 FF7B98BFE21CD2600469C9D7B3C040C06C1AAAB58F51EE3BE5A0E0CA94470300
18193 FF9024B3D2775BB5CC65F8872CB1A8BECAD9A7E25FBB3C3DF7D46A8A1BE31AC1
18194 FF9024B3D2775BB5CC65F8872CB1A8BECAD9A7E25FBB3C3DF7D46A8A1BE31AC1
18195 FF9024B3D2775BB5CC65F8872CB1A8BECAD9A7E25FBB3C3DF7D46A8A1BE31AC1
18196 FF9024B3D2775BB5CC65F8872CB1A8BECAD9A7E25FBB3C3DF7D46A8A1BE31AC1
18197 FF9024B3D2775BB5CC65F8872CB1A8BECAD9A7E25FBB3C3DF7D46A8A1BE31AC1
18198 FF9024B3D2775BB5CC65F8872CB1A8BECAD9A7E25FBB3C3DF7D46A8A1BE31AC1
18199 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951
18200 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951
18201 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951
18202 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951
18203 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951
18204 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951
      AcademicYear EnrolStatus EntryDate  LeavingDate NCCIS_ACADYR URN    Term
1     2013/2014    S           2014-01-07 2014-03-19  2017/2018    133411 1
2     2013/2014    C           2012-09-04 <NA>        2017/2018    107441 1
3     2013/2014    S           2014-01-07 2014-03-19  2017/2018    133411 2
4     2013/2014    C           2012-09-04 <NA>        2017/2018    107441 2
5     2013/2014    S           2014-01-07 2014-03-19  2017/2018    133411 3
6     2013/2014    C           2012-09-04 <NA>        2017/2018    107441 3
7     2012/2013    NA          2012-09-03 2012-10-02  2017/2018    107440 1
8     2012/2013    C           2012-10-03 <NA>        2017/2018    107413 1
9     2012/2013    NA          2012-09-03 2012-10-02  2017/2018    107440 2
10    2012/2013    C           2012-10-03 <NA>        2017/2018    107413 2
11    2012/2013    NA          2012-09-03 2012-10-02  2017/2018    107440 3
12    2012/2013    C           2012-10-03 <NA>        2017/2018    107413 3
13    2015/2016    C           2015-06-10 <NA>        2018/2019    107443 1
14    2015/2016    C           2016-05-01 2016-09-26  2018/2019    142681 1
15    2015/2016    C           2015-06-10 <NA>        2018/2019    107443 2
16    2015/2016    C           2016-05-01 2016-09-26  2018/2019    142681 2
17    2015/2016    C           2015-06-10 <NA>        2018/2019    107443 3
18    2015/2016    C           2016-05-01 2016-09-26  2018/2019    142681 3
19    2016/2017    C           2016-09-26 <NA>        2018/2019    143113 1
20    2016/2017    NA          2016-05-01 2016-09-26  2018/2019    142681 1
21    2016/2017    C           2016-09-26 <NA>        2018/2019    143113 2
22    2016/2017    NA          2016-05-01 2016-09-26  2018/2019    142681 2
23    2016/2017    C           2016-09-26 <NA>        2018/2019    143113 3
24    2016/2017    NA          2016-05-01 2016-09-26  2018/2019    142681 3
25    2015/2016    C           2012-09-05 2016-06-10  2017/2018    132219 1
26    2015/2016    S           2016-03-22 <NA>        2017/2018    139975 1
27    2015/2016    C           2012-09-05 2016-06-10  2017/2018    132219 2
28    2015/2016    S           2016-03-22 <NA>        2017/2018    139975 2
29    2015/2016    C           2012-09-05 2016-06-10  2017/2018    132219 3
30    2015/2016    S           2016-03-22 <NA>        2017/2018    139975 3
⋮     ⋮            ⋮           ⋮          ⋮           ⋮            ⋮      ⋮
18175 2017/2018    C           2016-09-01 <NA>        2018/2019    142825 1
18176 2017/2018    NA          2018-02-02 2018-06-29  2018/2019    130980 1
18177 2017/2018    C           2016-09-01 <NA>        2018/2019    142825 2
18178 2017/2018    NA          2018-02-02 2018-06-29  2018/2019    130980 2
18179 2017/2018    C           2016-09-01 <NA>        2018/2019    142825 3
18180 2017/2018    NA          2018-02-02 2018-06-29  2018/2019    130980 3
18181 2014/2015    C           2014-04-03 <NA>        2017/2018    107428 1
18182 2014/2015    C           2015-03-09 <NA>        2017/2018    135229 1
18183 2014/2015    C           2014-04-03 <NA>        2017/2018    107428 2
18184 2014/2015    C           2015-03-09 <NA>        2017/2018    135229 2
18185 2014/2015    C           2014-04-03 <NA>        2017/2018    107428 3
18186 2014/2015    C           2015-03-09 <NA>        2017/2018    135229 3
18187 2015/2016    S           2015-04-13 2015-10-02  2017/2018    107428 1
18188 2015/2016    M           2015-03-09 <NA>        2017/2018    135229 1
18189 2015/2016    S           2015-04-13 2015-10-02  2017/2018    107428 2
18190 2015/2016    M           2015-03-09 <NA>        2017/2018    135229 2
18191 2015/2016    S           2015-04-13 2015-10-02  2017/2018    107428 3
18192 2015/2016    M           2015-03-09 <NA>        2017/2018    135229 3
18193 2014/2015    C           2015-01-19 <NA>        2018/2019    137497 1
18194 2014/2015    C           2013-09-02 2015-01-13  2018/2019    108075 1
18195 2014/2015    C           2015-01-19 <NA>        2018/2019    137497 2
18196 2014/2015    C           2013-09-02 2015-01-13  2018/2019    108075 2
18197 2014/2015    C           2015-01-19 <NA>        2018/2019    137497 3
18198 2014/2015    C           2013-09-02 2015-01-13  2018/2019    108075 3
18199 2014/2015    C           2012-09-03 <NA>        2017/2018    136736 1
18200 2014/2015    S           2015-02-06 2015-09-06  2017/2018    135851 1
18201 2014/2015    C           2012-09-03 <NA>        2017/2018    136736 2
18202 2014/2015    S           2015-02-06 2015-09-06  2017/2018    135851 2
18203 2014/2015    C           2012-09-03 <NA>        2017/2018    136736 3
18204 2014/2015    S           2015-02-06 2015-09-06  2017/2018    135851 3
      OnRoll
1     1
2     1
3     0
4     1
5     NA
6     1
7     0
8     1
9     NA
10    1
11    NA
12    1
13    1
14    NA
15    NA
16    NA
17    NA
18    0
19    1
20    0
21    1
22    NA
23    1
24    NA
25    1
26    NA
27    1
28    1
29    0
30    1
⋮     ⋮
18175 1
18176 NA
18177 1
18178 NA
18179 NA
18180 0
18181 1
18182 NA
18183 1
18184 NA
18185 1
18186 1
18187 0
18188 1
18189 NA
18190 1
18191 NA
18192 1
18193 NA
18194 1
18195 1
18196 0
18197 1
18198 NA
18199 1
18200 NA
18201 1
18202 1
18203 1
18204 0

In [501]:
pivot_long_clean <- pivot_long |>
    group_by(person_id, AcademicYear, Term) |>
    filter(n() > 1) |>
    mutate(
        # prioritise the record with onroll == T
        onroll_priority = ifelse(OnRoll == "1", 1, 0),
        # prioritise the record with C enrolment, then M enrolment status
        enrol_priority = case_when(
          EnrolStatus == "C" ~ 3,
          EnrolStatus == "M" ~ 2,
          TRUE ~ 1
            ),
        # combine
        priority_score = onroll_priority * 10 + enrol_priority
      ) |>
    # keep single highest priority record
    arrange(desc(priority_score)) |>
    slice_head(n = 1) |>
    ungroup()

In [502]:
non_duplicates <- pivot_long |>
  group_by(person_id, AcademicYear, Term) |>
  filter(n() == 1) |>
  ungroup()

In [503]:
pivot_long_clean <- bind_rows(pivot_long_clean, non_duplicates) |>
  arrange(person_id, AcademicYear, Term)

In [504]:
# n = 246807

In [505]:
pivot_long_clean |>
  #group_by(person_id, AcademicYear, Term) |>
  #filter(n() > 1) |>
  arrange(person_id, AcademicYear, Term)

       person_id
1      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
3      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
4      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
5      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
6      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
7      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
8      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
9      0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
10     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
11     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
12     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
13     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
14     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
15     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
16     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
17     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
18     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
19     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
20     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
21     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
22     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
23     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
24     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
25     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
26     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
27     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
28     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
29     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
30     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
⋮      ⋮
246778 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
246779 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
246780 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
246781 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
246782 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
246783 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
246784 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
246785 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
246786 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
246787 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
246788 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
246789 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
246790 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
246791 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
246792 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
246793 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
246794 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
246795 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
246796 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
246797 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
246798 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
246799 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
246800 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
246801 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
246802 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
246803 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
246804 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
246805 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
246806 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
246807 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
       AcademicYear EnrolStatus EntryDate  LeavingDate NCCIS_ACADYR URN    Term
1      2012/2013    C           2012-09-04 <NA>        2017/2018    107442 1
2      2012/2013    C           2012-09-04 <NA>        2017/2018    107442 2
3      2012/2013    C           2012-09-04 <NA>        2017/2018    107442 3
4      2013/2014    C           2012-09-04 <NA>        2017/2018    107442 1
5      2013/2014    C           2012-09-04 <NA>        2017/2018    107442 2
6      2013/2014    C           2012-09-04 <NA>        2017/2018    107442 3
7      2014/2015    C           2012-09-04 <NA>        2017/2018    107442 1
8      2014/2015    C           2012-09-04 <NA>        2017/2018    107442 2
9      2014/2015    C           2012-09-04 <NA>        2017/2018    107442 3
10     2015/2016    C           2012-09-04 <NA>        2017/2018    107442 1
11     2015/2016    C           2012-09-04 <NA>        2017/2018    107442 2
12     2015/2016    C           2012-09-04 <NA>        2017/2018    107442 3
13     2016/2017    C           2016-10-01 2017-06-30  2017/2018    143114 1
14     2016/2017    C           2016-10-01 2017-06-30  2017/2018    143114 2
15     2016/2017    C           2016-10-01 2017-06-30  2017/2018    143114 3
16     2012/2013    C           2012-09-04 <NA>        2017/2018    107429 1
17     2012/2013    C           2012-09-04 <NA>        2017/2018    107429 2
18     2012/2013    C           2012-09-04 <NA>        2017/2018    107429 3
19     2013/2014    C           2012-09-04 <NA>        2017/2018    107429 1
20     2013/2014    C           2012-09-04 <NA>        2017/2018    107429 2
21     2013/2014    C           2012-09-04 <NA>        2017/2018    107429 3
22     2014/2015    C           2014-09-01 <NA>        2017/2018    140569 1
23     2014/2015    C           2014-09-01 <NA>        2017/2018    140569 2
24     2014/2015    C           2014-09-01 <NA>        2017/2018    140569 3
25     2015/2016    C           2014-09-01 <NA>        2017/2018    140569 1
26     2015/2016    C           2014-09-01 <NA>        2017/2018    140569 2
27     2015/2016    C           2014-09-01 <NA>        2017/2018    140569 3
28     2016/2017    C           2014-09-01 2017-07-21  2017/2018    140569 1
29     2016/2017    C           2014-09-01 2017-07-21  2017/2018    140569 2
30     2016/2017    C           2014-09-01 2017-07-21  2017/2018    140569 3
⋮      ⋮            ⋮           ⋮          ⋮           ⋮            ⋮      ⋮
246778 2013/2014    C           2013-09-02 <NA>        2018/2019    107350 1
246779 2013/2014    C           2013-09-02 <NA>        2018/2019    107350 2
246780 2013/2014    C           2013-09-02 <NA>        2018/2019    107350 3
246781 2014/2015    C           2013-09-02 <NA>        2018/2019    107350 1
246782 2014/2015    C           2013-09-02 <NA>        2018/2019    107350 2
246783 2014/2015    C           2013-09-02 <NA>        2018/2019    107350 3
246784 2015/2016    C           2013-09-02 <NA>        2018/2019    107350 1
246785 2015/2016    C           2013-09-02 <NA>        2018/2019    107350 2
246786 2015/2016    C           2013-09-02 <NA>        2018/2019    107350 3
246787 2016/2017    C           2016-09-21 <NA>        2018/2019    142825 1
246788 2016/2017    C           2016-09-21 <NA>        2018/2019    142825 2
246789 2016/2017    C           2016-09-21 <NA>        2018/2019    142825 3
246790 2017/2018    C           2016-09-01 2018-07-20  2018/2019    142825 1
246791 2017/2018    C           2016-09-01 2018-07-20  2018/2019    142825 2
246792 2017/2018    C           2016-09-01 2018-07-20  2018/2019    142825 3
246793 2012/2013    C           2012-09-03 <NA>        2017/2018    107366 1
246794 2012/2013    C           2012-09-03 <NA>        2017/2018    107366 2
246795 2012/2013    C           2012-09-03 <NA>        2017/2018    107366 3
246796 2013/2014    C           2012-09-03 <NA>        2017/2018    107366 1
246797 2013/2014    C           2012-09-03 <NA>        2017/2018    107366 2
246798 2013/2014    C           2012-09-03 <NA>        2017/2018    107366 3
246799 2014/2015    C           2012-09-03 <NA>        2017/2018    107366 1
246800 2014/2015    C           2012-09-03 <NA>        2017/2018    107366 2
246801 2014/2015    C           2012-09-03 <NA>        2017/2018    107366 3
246802 2015/2016    C           2012-09-03 <NA>        2017/2018    107366 1
246803 2015/2016    C           2012-09-03 <NA>        2017/2018    107366 2
246804 2015/2016    C           2012-09-03 <NA>        2017/2018    107366 3
246805 2016/2017    C           2012-09-03 2017-07-21  2017/2018    142761 1
246806 2016/2017    C           2012-09-03 2017-07-21  2017/2018    142761 2
246807 2016/2017    C           2012-09-03 2017-07-21  2017/2018    142761 3
       OnRoll onroll_priority enrol_priority priority_score
1      1      NA              NA             NA
2      1      NA              NA             NA
3      1      NA              NA             NA
4      1      NA              NA             NA
5      1      NA              NA             NA
6      1      NA              NA             NA
7      1      NA              NA             NA
8      1      NA              NA             NA
9      1      NA              NA             NA
10     1      NA              NA             NA
11     1      NA              NA             NA
12     NA     NA              NA             NA
13     1      NA              NA             NA
14     1      NA              NA             NA
15     0      NA              NA             NA
16     1      NA              NA             NA
17     1      NA              NA             NA
18     1      NA              NA             NA
19     1      NA              NA             NA
20     1      NA              NA             NA
21     NA     NA              NA             NA
22     1      NA              NA             NA
23     1      NA              NA             NA
24     1      NA              NA             NA
25     1      NA              NA             NA
26     1      NA              NA             NA
27     1      NA              NA             NA
28     1      NA              NA             NA
29     1      NA              NA             NA
30     0      NA              NA             NA
⋮      ⋮      ⋮               ⋮              ⋮
246778 1      NA              NA             NA
246779 1      NA              NA             NA
246780 1      NA              NA             NA
246781 1      NA              NA             NA
246782 1      NA              NA             NA
246783 1      NA              NA             NA
246784 1      NA              NA             NA
246785 1      NA              NA             NA
246786 NA     NA              NA             NA
246787 1      NA              NA             NA
246788 1      NA              NA             NA
246789 1      NA              NA             NA
246790 1      NA              NA             NA
246791 1      NA              NA             NA
246792 0      NA              NA             NA
246793 1      NA              NA             NA
246794 1      NA              NA             NA
246795 1      NA              NA             NA
246796 1      NA              NA             NA
246797 1      NA              NA             NA
246798 1      NA              NA             NA
246799 1      NA              NA             NA
246800 1      NA              NA             NA
246801 1      NA              NA             NA
246802 1      NA              NA             NA
246803 1      NA              NA             NA
246804 1      NA              NA             NA
246805 NA     NA              NA             NA
246806 1      NA              NA             NA
246807 0      NA              NA             NA

In [506]:
head(pivot_long_clean)

  person_id                                                        AcademicYear
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2012/2013
2 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2012/2013
3 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2012/2013
4 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2013/2014
5 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2013/2014
6 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2013/2014
  EnrolStatus EntryDate  LeavingDate NCCIS_ACADYR URN    Term OnRoll
1 C           2012-09-04 <NA>        2017/2018    107442 1    1
2 C           2012-09-04 <NA>        2017/2018    107442 2    1
3 C           2012-09-04 <NA>        2017/2018    107442 3    1
4 C           2012-09-04 <NA>        2017/2018    107442 1    1
5 C           2012-09-04 <NA>        2017/2018    107442 2    1
6 C           2012-09-04 <NA>        2017/2018    107442 3    1
  onroll_priority enrol_priority priority_score
1 NA              NA             NA
2 NA              NA             NA
3 NA              NA             NA
4 NA              NA             NA
5 NA              NA             NA
6 NA              NA             NA

In [507]:
df_for_pivot_wide <- pivot_long_clean |>
    select(c(person_id, NCCIS_ACADYR, URN, AcademicYear, Term))

In [508]:
head(df_for_pivot_wide)

  person_id                                                        NCCIS_ACADYR
1 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2017/2018
2 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2017/2018
3 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2017/2018
4 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2017/2018
5 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2017/2018
6 0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD 2017/2018
  URN    AcademicYear Term
1 107442 2012/2013    1
2 107442 2012/2013    2
3 107442 2012/2013    3
4 107442 2013/2014    1
5 107442 2013/2014    2
6 107442 2013/2014    3

In [509]:
# Save as csv 
write.csv(df_for_pivot_wide, "data/school_urn_enrollment_perterm.csv", row.names = FALSE)

In [415]:
#enrol_final
pivot_long_clean |> 
    filter(person_id == '004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894' ) |>
    arrange(AcademicYear)

   person_id
1  004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
2  004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
3  004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
4  004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
5  004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
6  004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
7  004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
8  004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
9  004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
10 004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
11 004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
12 004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
13 004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
14 004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
15 004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
   AcademicYear EnrolStatus EntryDate  LeavingDate NCCIS_ACADYR URN    Term
1  2012/2013    C           2012-09-04 <NA>        2017/2018    107441 1
2  2012/2013    C           2012-09-04 <NA>        2017/2018    107441 2
3  2012/2013    C           2012-09-04 <NA>        2017/2018    107441 3
4  2013/2014    C           2012-09-04 <NA>        2017/2018    107441 1
5  2013/2014    C           2012-09-04 <NA>        2017/2018    107441 2
6  2013/2014    C           2012-09-04 <NA>        2017/2018    107441 3
7  2014/2015    S           2014-07-07 <NA>        2017/2018    107428 1
8  2014/2015    S           2014-07-07 <NA>        2017/2018    107428 2
9  2014/2015    S           2014-07-07 <NA>        2017/2018    107428 3
10 2015/2016    C           2014-07-07 <NA>        2017/2018    107428 1
11 2015/2016    C           2014-07-07 <NA>        2017/2018    107428 2
12 2015/2016    C           2014-07-07 <NA>        2017/2018    107428 3
13 2016/2017    C           2014-07-07 2017-07-25  2017/2018    107428 1
14 2016/2017    C           2014-07-07 2017-07-25  2017/2018    107428 2
15 2016/2017    C           2014-07-07 2017-07-25  2017/2018    107428 3
   OnRoll onroll_priority enrol_priority priority_score
1  1      NA              NA             NA
2  1      NA              NA             NA
3  1      NA              NA             NA
4  1       1               3             13
5  1       1               3             13
6  1       1               3             13
7  1      NA              NA             NA
8  1      NA              NA             NA
9  1      NA              NA             NA
10 1      NA              NA             NA
11 1      NA              NA             NA
12 1      NA              NA             NA
13 1      NA              NA             NA
14 1      NA              NA             NA
15 0      NA              NA             NA

#### Pivot Wide

In [418]:
pivot_wide <- df_for_pivot_wide |>
    arrange(person_id, AcademicYear, Term) |>
    mutate(Year_Term = paste0("Y", AcademicYear, "_", "Term", Term),
          URN = as.character(URN)) |>
    select(person_id, NCCIS_ACADYR, Year_Term, URN) |>
    pivot_wider(
        names_from = Year_Term,
        values_from = URN,
        values_fill = NA
      )

In [419]:
pivot_wide

      person_id
1     0002F12C1F92EC01CB0C05D441AA6D7AE16E9CD131BB64885744D08BA74E1FDD
2     00034E776A98176C2B6075634BC4A614400F32AA9C4D599FDDE156541F1F9A29
3     0004E60FEFC16781A48973C80F782B233869629C9CE44B741E2D2043047FCB1D
4     0013020C6ED2FF78BCA8E5F2D0B9B16E66C50B6A2AABB754FB63314CFE3A2EC7
5     00149D26484ED3BE2DEF154B8DB53A36B1A9FF0839C447A2CE19B0750225BA66
6     0014DF7EADF7C22A0FD2F6862B6F06778B199F1F2D61242125DA8EC539E6275D
7     0018E26A40A6299391164D4918658B0B1248367C762DCE6D2FDF1AE131A9138C
8     0019031CD62586D59268772800516ED50CDF1EF7DE46488542BB031850F6E68A
9     001B7CEB7B4CC529920A0B9F5B83D1AC0019E5DC44B3FBB3CEF665C331C0C3B6
10    001E539C263734CC355646811C93CF85B0C587D2EBA8B0D79290FDE8A75D6267
11    001E5C1FFA964716BF5E84562BC0B5D64F7742B1E8126718A5C0157D485F215D
12    001F566795F57F5D8DD92430D868A38B757699844E3E09569B33253527012932
13    00222373A6082CDBF94DA04F23E7EB4C8775BEE122FE9C29FBF521900A498EDF
14    002AB68E0EC9459837DD6159160BF8C592504B5F0EE3160A22051398D20C3FFC
15    002E041C5100C46E33B8A0C0220BDE85A79111C5D0E26742F6278C059930FAF6
16    002EF3F17C7981C3D6FD842C559E9AA0626E06B3940B670DDA2B71F7070ADF7D
17    003132A725233755576CF96E5AA2B3DF606A618754D4BDDFCDD5483849E7B946
18    00341B29C42EC823E9D06B625E751614D66794F1096E2F045DDE51DB64C9C623
19    0037AB0369C14AD5CA0340E2DFDAE2FFF22062A44A7889743C152A8163C08500
20    003D2F5BDBC025915EE2AA9CCB96F54F72F003BF7DC6939849ADD6CCD1048ABC
21    0048AA244E75570B74E82BDC60D09008D5E728E78E60FB96AA0E762DBD0E818E
22    004AC6875C0259256CBCBC00373E9D09131E7D064B6089B9EB26F821F8297775
23    004C012DC8B27D82CC173C9590867A88C8B60E6F4C1EAE8AF73D53403DDD94B5
24    004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
25    0052FF7683A04EBA481AFA53811E1707DBAB62007649EA0C4CE89C8498C06C97
26    0054192801954D860BB235F844AD1CB8A99956B2CF3D4E20F83C650DD6279B58
27    0059AC822384B93661D2AB87E93EA6AB0847122FA139A080070E86A2F6A1910E
28    005A3BB3D150E6AFDC0C4DDCEE6DB850E746A6E2F7760B727CF97B659BC2F483
29    005A9C0EA9BA31FEE547B2C1013A13FB33389E9459EF5DF24E61F03E57FA5192
30    005F4B5837E7E247A9A2A7A1F750EAF2B7E33ADD839287A9A654E5DEEE3657FB
⋮     ⋮
16933 FF77AAB58760E4616819BF69FA7A7D0466EC940FC1B666F5D8FC15261B05FDA7
16934 FF785EF44C283B9E43E7F206B8848D7C550C36E7E8E5DA0A2B6267CABC0AE447
16935 FF7AC7331F6B988DCFBCFA5C55F7984D5BA33735D4DDB4671F30E37176A7B40D
16936 FF7B98BFE21CD2600469C9D7B3C040C06C1AAAB58F51EE3BE5A0E0CA94470300
16937 FF7B9B8977DE09E00DDE57866479BEED54F7BC5730E38C61A15A220CAF2C507B
16938 FF85D28F3D4272EF3EDA67E52BC94BB3A529BD2CD31D32EF21FB8157396EF57D
16939 FF85FB47EF271836ECDF7555602263FC0E52F8A84F39868EE7B66E30E47DF618
16940 FF8C66C8699FEF1708ABC2DADF11D78283107FADB514F81D4219017A8D26E2DE
16941 FF9024B3D2775BB5CC65F8872CB1A8BECAD9A7E25FBB3C3DF7D46A8A1BE31AC1
16942 FF94BC38B3E8FE01672532C523A4C00ABB2F9C7B3CDFF6C78F2DA080B544B09A
16943 FF94D3F7FDB40C124787D0EBA0CD7660187135442D800F18C11487D380F55663
16944 FF9B2F9502DAFBC1EFB04109BEFF47C64A04801619DE844A3DAD073DD45D99D1
16945 FFAA13CCE7B35BA3D3A737EF1A13BCE2289A94F9778EC0C9F18CD77F1B93C979
16946 FFACDC831FAAA09353CAB36C5828F34E508AC8BFED1B4B07999BAF198CAC4EEA
16947 FFBCE0C32A37E3663F1C5159ECFC6F08CD5722E938464A58634F3263003F1D9F
16948 FFC0379FDA559C1337454C579FF36F9AE82E62D16B3223D009C57DEC3731754C
16949 FFC7129859DD885141E316248A0EB23059DB0F0DB98242C34C67F06FBBAB8041
16950 FFC96F346EC6829E7A31F60109FD729DE208D180104B50FC8B1BFAD552D6C8FC
16951 FFD30596592DA2C82B86241FBA35E56C7384E7EF8219DB076458B4F9ACDED786
16952 FFD391941F3AA9CB910FFFACF24CC2CEAD0BC63EED146E9C21B2C71BA77B084A
16953 FFDB80FEACFFB312A354D148E7516AE0ECA7DE27E3A6AB81178E149954213951
16954 FFE1AA7D705C959745A85B91C6D3F3D22A57B8E50092E9EC25046F6986F77D96
16955 FFE837A538A9166CC4089E844F651277391B496479F4691CE27BF1000C49223B
16956 FFEA068077E4464D059236951F07D7DF96542C2197AAFAC3E20C036BACB9825C
16957 FFEF2AA9E8BD72D6A0E7CE50F067E4247E12738F53AE726CD94A4D9CB588C702
16958 FFEFD5577D0112E9304118DB7851CF61BEE4DD3D3184EEA756C076317925508F
16959 FFFA6705A275195BFE8A443AF0BD2AA86B1AA0481D330D8665813206EB8DAD43
16960 FFFAAE2FCD86DD15E6F4829E094698B4B6084BA5BCD494F60F55D28C4546DD77
16961 FFFB1218D0EE1EB52B68DF474650BECD21EDE8925586F322D95209DCF47A2398
16962 FFFE52EB3D3A45D03563CF6BA5584E2BCD3B6B081033695AFA40A31F8AEBEF92
      NCCIS_ACADYR Y2012/2013_Term1 Y2012/2013_Term2 Y2012/2013_Term3
1     2017/2018    107442           107442           107442
2     2017/2018    107429           107429           107429
3     2018/2019    NA               NA               NA
4     2018/2019    NA               NA               NA
5     2017/2018    108087           108087           108087
6     2017/2018    107366           107366           107366
7     2018/2019    NA               NA               NA
8     2018/2019    NA               NA               NA
9     2017/2018    107395           107395           107395
10    2017/2018    107439           107439           107439
11    2018/2019    NA               NA               NA
12    2018/2019    NA               NA               NA
13    2017/2018    107391           107391           107391
14    2018/2019    NA               NA               NA
15    2017/2018    130909           130909           130909
16    2018/2019    NA               NA               NA
17    2017/2018    107441           107441           107441
18    2018/2019    NA               NA               NA
19    2017/2018    107395           107395           107395
20    2017/2018    NA               NA               NA
21    2018/2019    NA               NA               NA
22    2018/2019    NA               NA               NA
23    2018/2019    NA               NA               NA
24    2017/2018    107441           107441           107441
25    2018/2019    NA               NA               NA
26    2017/2018    107413           107413           107413
27    2017/2018    107562           107562           107562
28    2018/2019    NA               NA               NA
29    2018/2019    NA               NA               NA
30    2017/2018    135935           135935           135935
⋮     ⋮            ⋮                ⋮                ⋮
16933 2018/2019    NA               NA               NA
16934 2017/2018    135865           135865           135865
16935 2017/2018    136905           136905           136905
16936 2017/2018    107284           107284           107284
16937 2017/2018    NA               NA               NA
16938 2017/2018    135866           135866           135866
16939 2018/2019    NA               NA               NA
16940 2017/2018    136343           136343           136343
16941 2018/2019    NA               NA               NA
16942 2017/2018    107386           107386           107386
16943 2018/2019    NA               NA               NA
16944 2017/2018    136736           136736           136736
16945 2018/2019    NA               NA               NA
16946 2017/2018    107439           107439           107439
16947 2018/2019    NA               NA               NA
16948 2018/2019    NA               NA               NA
16949 2018/2019    NA               NA               NA
16950 2018/2019    NA               NA               NA
16951 2017/2018    134989           134989           134989
16952 2018/2019    NA               NA               NA
16953 2017/2018    136736           136736           136736
16954 2017/2018    136672           136672           136672
16955 2017/2018    121700           121700           121700
16956 2018/2019    NA               NA               NA
16957 2017/2018    107203           107203           107203
16958 2017/2018    135865           135865           135865
16959 2018/2019    NA               NA               NA
16960 2018/2019    NA               NA               NA
16961 2018/2019    NA               NA               NA
16962 2017/2018    107366           107366           107366
      Y2013/2014_Term1 Y2013/2014_Term2 Y2013/2014_Term3 Y2014/2015_Term1
1     107442           107442           107442           107442
2     107429           107429           107429           140569
3     136529           136529           136529           136529
4     107441           107441           107441           107441
5     108087           108087           108087           108087
6     107366           107366           107366           107366
7     140111           140111           140111           139474
8     139982           139982           139982           139982
9     107395           107395           107395           107395
10    107439           107439           107439           107439
11    136905           136905           136905           136905
12    107440           107440           107440           107440
13    107391           107391           107391           107391
14    136664           136664           136664           136664
15    130909           130909           130909           130909
16    107442           107442           107442           107442
17    107441           107441           107441           107441
18    107442           107442           107442           107442
19    107395           107395           107395           107395
20    NA               NA               NA               NA
21    136736           136736           136736           136736
22    136905           136905           136905           136905
23    NA               NA               NA               NA
24    107441           107441           107441           107428
25    136736           136736           136736           136736
26    107413           107413           107413           107413
27    107562           107562           107562           107562
28    139982           139982           139982           139982
29    136736           136736           136736           136736
30    135935           135935           135935           135935
⋮     ⋮                ⋮                ⋮                ⋮
16933 107350           107350           107350           107350
16934 135865           135865           135865           135865
16935 136905           136905           136905           136905
16936 107428           107428           107428           107428
16937 NA               NA               NA               121716
16938 135866           135866           135866           135866
16939 135865           135865           135865           135865
16940 136343           136343           136343           136343
16941 108075           108075           108075           108075
16942 139975           139975           139975           139975
16943 136905           136905           136905           136905
16944 136736           136736           136736           136736
16945 139982           139982           139982           139982
16946 107439           107439           107439           107439
16947 137277           137277           137277           137277
16948 135866           135866           135866           135866
16949 137277           137277           137277           137277
16950 135367           135367           135367           135367
16951 134989           134989           134989           139982
16952 107440           107440           107440           107440
16953 136736           136736           136736           136736
16954 136672           136672           136672           136672
16955 121700           121700           121700           121700
16956 132219           132219           132219           132219
16957 107442           107442           107442           107442
16958 135865           135865           135865           135865
16959 135865           135865           135865           135865
16960 136736           136736           136736           136736
16961 107350           107350           107350           107350
16962 107366           107366           107366           107366
      Y2014/2015_Term2 Y2014/2015_Term3 Y2015/2016_Term1 Y2015/2016_Term2
1     107442           107442           107442           107442
2     140569           140569           140569           140569
3     136529           136529           136529           136529
4     107441           107441           107441           107441
5     108087           108087           108087           108087
6     107366           107366           107366           107366
7     139474           139474           139474           139474
8     139982           139982           139982           139982
9     107395           107395           107395           107395
10    107439           107439           107439           107439
11    136905           136905           136905           136905
12    107440           107440           107440           107440
13    107391           107391           107391           107391
14    136664           136664           136664           136664
15    130909           130909           130909           130909
16    107442           107442           107442           107442
17    107441           107441           107441           107441
18    107442           107442           107442           107442
19    107395           107395           107395           107395
20    NA               NA               NA               NA
21    136736           136736           136736           136736
22    136905           136905           136905           136905
23    NA               NA               136962           136962
24    107428           107428           107428           107428
25    136736           136736           136736           136736
26    107413           107413           107413           107413
27    107562           107562           107562           107562
28    139982           139982           139982           139982
29    136736           136736           136736           136736
30    135935           135935           135935           135935
⋮     ⋮                ⋮                ⋮                ⋮
16933 107350           107350           107350           107350
16934 135865           135865           135865           135865
16935 136905           136905           136905           136905
16936 107428           135229           135229           135229
16937 121716           121716           121716           121716
16938 135866           135866           135866           135866
16939 135865           135865           135865           135865
16940 136343           136343           136343           136343
16941 137497           137497           137497           137497
16942 139975           139975           139975           139975
16943 136905           136905           136905           136905
16944 136736           136736           136736           136736
16945 139982           139982           139982           139982
16946 107439           107439           107439           107439
16947 137277           137277           137277           137277
16948 135866           135866           135866           135866
16949 137277           137277           137277           137277
16950 135367           135367           135367           135367
16951 139982           139982           139982           139982
16952 107440           107440           107440           107440
16953 136736           136736           136736           136736
16954 136672           136672           136672           136672
16955 121700           121700           121700           121700
16956 132219           132219           132219           132219
16957 107442           107442           107442           107442
16958 135865           135865           135865           135865
16959 135865           135865           135865           135865
16960 136736           136736           136736           136736
16961 107350           107350           107350           107350
16962 107366           107366           107366           107366
      Y2015/2016_Term3 Y2016/2017_Term1 Y2016/2017_Term2 Y2016/2017_Term3
1     107442           143114           143114           143114
2     140569           140569           140569           140569
3     136529           136529           136529           136529
4     107441           143112           143112           143112
5     108087           108087           108087           108087
6     107366           142761           142761           142761
7     139474           139474           139474           139474
8     139982           139982           139982           139982
9     107395           107395           107395           107395
10    107439           107439           107439           107439
11    136905           136905           136905           136905
12    107440           107440           107440           107440
13    107391           143113           143113           143113
14    136664           136664           136664           136664
15    130909           130909           130909           130909
16    107442           143114           143114           143114
17    107441           143112           143112           143112
18    107442           143114           143114           143114
19    107395           107395           107395           107395
20    NA               137177           137177           137177
21    136736           136736           136736           136736
22    136905           136905           136905           136905
23    136962           136962           136962           136962
24    107428           107428           107428           107428
25    136736           136736           136736           136736
26    107413           107413           107413           107413
27    107562           107562           107562           107562
28    139982           139982           139982           139982
29    136736           136736           136736           136736
30    135935           135935           135935           135935
⋮     ⋮                ⋮                ⋮                ⋮
16933 107350           142825           142825           142825
16934 135865           135865           135865           135865
16935 136905           136905           136905           136905
16936 135229           135229           135229           135229
16937 121716           121716           121716           121716
16938 135866           135866           135866           135866
16939 135865           135865           135865           135865
16940 136343           136343           136343           136343
16941 137497           137497           137497           137497
16942 139975           139975           139975           139975
16943 136905           136905           136905           136905
16944 136736           136736           136736           136736
16945 139982           139982           139982           139982
16946 107439           107439           107439           107439
16947 137277           137277           137277           137277
16948 135866           135866           135866           135866
16949 137277           137277           137277           137277
16950 135367           135367           135367           135367
16951 139982           139982           139982           139982
16952 107440           107440           107440           107440
16953 136736           135851           135851           135851
16954 136672           136672           136672           136672
16955 121700           121700           121700           121700
16956 132219           142590           142590           142590
16957 107442           143114           143114           143114
16958 135865           135865           135865           135865
16959 135865           135865           135865           135865
16960 136736           136736           136736           136736
16961 107350           142825           142825           142825
16962 107366           142761           142761           142761
      Y2017/2018_Term1 Y2017/2018_Term2 Y2017/2018_Term3
1     NA               NA               NA
2     NA               NA               NA
3     136529           136529           136529

#### Save as CSV

In [351]:
write.csv(pivot_long, "data/enrolment_by_term.csv", row.names = FALSE)

In [359]:
write.csv(pivot_long_clean, "data/enrolment_by_term_clean.csv", row.names = FALSE)

In [420]:
write.csv(pivot_wide, "data/enrolment_wide.csv", row.names = FALSE)

In [352]:
write.csv(enrol_final, "data/enrol_final.csv", row.names = FALSE)

In [353]:
write.csv(school_count, "data/school_count.csv", row.names = FALSE)

# extract from full enrolment tables whether ever attended AP/PRU

In [393]:
head(enrol_final)

  person_id                                                        SchoolID
1 F48A1CAEA9F5279772EA10D2BAA19242ABDDEFDE73A02C2EDD1047022BA8C2F6 15177
2 966C673E1F91BCECFB3887D281FE0A39081A83B07359403F7833C67EF7818557 10875
3 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB  9574
4 18746FF26D6AC95D757A4B4CB10B01DE6F041115B43ECC8BE0C4A0AEF575224B 14276
5 16AB3AC8B08A141C58F505036D9FC8AC09647F5485772F0849FC93AB9E7885EF 18286
6 BFA4C3193490CCDA1B5422595F9E974355F83B6973445546D10283E5A3EE1296 18286
  AcademicYear OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate  LeavingDate
1 2016/2017    1        1        1        C           2012-10-03 <NA>
2 2014/2015    1        1        1        C           2014-11-10 <NA>
3 2015/2016    0        NA       NA       M           2012-10-04 2015-11-06
4 2015/2016    1        1        1        C           2012-10-04 <NA>
5 2017/2018    1        1        1        C           2017-09-01 <NA>
6 2017/2018    1        1        0        C           2017-09-01 2018-06-29
  PartTime NCCIS_ACADYR URN    InstitutionTypeDesc SchoolName
1 0        2017/2018    139982 Academy converter   Grange Technology College
2 0        2017/2018    135865 Academy sponsor led Appleton Academy
3 0        2017/2018    135367 Academy sponsor led Bradford Academy
4 0        2017/2018    137065 Academy sponsor led Coop Academy Leeds
5 0        2018/2019    145173 Academy sponsor led Appleton Academy
6 0        2018/2019    145173 Academy sponsor led Appleton Academy
  PhaseOfEducationDesc
1 Secondary
2 Not applicable
3 Not applicable
4 Secondary
5 NA
6 NA

In [394]:
ever_AP <- enrol_final |>
    filter(InstitutionTypeDesc == 'AP/PRU')

In [396]:
ever_AP_ids <- ever_AP |>
    select(person_id) |>
    distinct() |>
    mutate(ever_AP = TRUE)

In [397]:
ever_AP_ids

    person_id                                                        ever_AP
1   BC99204E62FE3D7E8E4D41B6D223F300ED59636D3A2E19BE5DCBAB85A8C6CA68 TRUE
2   0F719CE1354E346BC9788D861696C41D3E12CD4E9B922C321905506B99B7F517 TRUE
3   B606CEC2C788D17D26AE9F5AD9343D6047CF3C2905F4DD428783C1906106A262 TRUE
4   F8C2444EF68664B92F9D89F8AC9DFB216B728E3FFAAC2409F420B4D7C62CD3E0 TRUE
5   197739B330DCFC024B66615A0BA3C4DF10389D593D2D669EF5AB3EDDDEB69339 TRUE
6   FC4A9A9ECC56374706EC415D1FA433DF7C815C0F5048A15BF7AF96DF0CEF3933 TRUE
7   1CC67F0522C00BB034876FCEBBF85235B31DF165136E7754A30589AAA6CE5B5D TRUE
8   3144635DF44220C33C414A245F1CD5FF2D3D95A5F3BEC9D7B86DC63C4004CC42 TRUE
9   C3976E86704D3DAA8186799F9A646B9EEF86B49204CFE99B8E18C66C67CAF8D4 TRUE
10  F5B8E8DBDE248D151B73EA0E9DBD9E0EC3FA4FFE54480146966425EF021CD25C TRUE
11  FB165195F5A0EA878DBA30DCDA52605CF5CD7C6335AC84841271F55E2A3AE98A TRUE
12  CB28D8D7E2B2EFB1EEE524550DA6B6FD9CF45B7830F230574C1CC702CD589B6B TRUE
13  C4709433D274ABB6EA3F34FC1C195A7F6EA915F7A433D83622050A2AB70F87E1 TRUE
14  1606DF3BFBC6AB74B66C645412BA8192112816F27DAB6E420F28B9BA8DDB1832 TRUE
15  48E2D12B68649EB8EC6C7349C29F41A6ACC34FDFE8235AB7AD532C79387C9C4A TRUE
16  59699AC01160227E5AC09CDFC6F311627811C90FFAF19356EDB9B82A3CD386D0 TRUE
17  DBF778B68BE23A7EF2EC0FEBF38F49A290D7991C7A968D91C53505102D9D9FA8 TRUE
18  8E623D075173AA6554453CF980A18C5A5192DB23E48DCE3147C107D79CFEC206 TRUE
19  43C5B4883CB3219AD7C8348257343F62AFC8934DD992D3CC5C3C11617E09E187 TRUE
20  6965E4DAC8C58504228D424C63CF8336004B2D6BAF943357CE6A44AA10AE6F5E TRUE
21  6FB5E22CD8825E788A477B4CCEEBAC0B4A50D56141F9322659699841DCC1E97C TRUE
22  DFE2E3E7ADCA1361902EE15B28FEDF91976180BA413C80CBFE794FA139E726D7 TRUE
23  7607F1DA05277C265745C09F4F8806014F84BE10872487ED5989E06DB8232C4D TRUE
24  32D96E787216E7E2DD9FBD3895A29020FD57D92F74199FFBBD984DFF1B5D55C2 TRUE
25  A4B7D2DC9425FE8F9088407BA82C1CF976DED7ABC36B0CECE39685D1859DBA29 TRUE
26  5FF83F26825842431CD77733612B67D6E8A749FE7C9876010959274AE775277F TRUE
27  F44F685CD76783043CA73B74C99C5080EDD070FD8AADFBC61C8D4388C3CF2BAB TRUE
28  94B60058614D6FAC0F3EF402712A30AA14C8E75D714447B68491A0B46A43C72F TRUE
29  DF9CAD900C7F7BA0AF8B64047CE6765595DF20235913375A534A41D8A3CB9A91 TRUE
30  B7391E8EEF3FF450FC019FD342B7D15FB94CABEBCC5AB072E03FEECEA010C220 TRUE
⋮   ⋮                                                                ⋮
538 14CC9C7A7762FA67C0A66E211EC9CCEB6CBD14C2B2AE3B6694D0DBCB488BBF62 TRUE
539 FE8201470B14FDA2535F4F5AF15A6A60425A7656FD6885F86C2B414154B51533 TRUE
540 9F57EAE3C26D0B582FB0D58482862E8527EA40C8AD4E98EFC0FA2D56F0F67509 TRUE
541 980BE43C74029451A0BEB8C6341B184010AF8BA3BA95E20E9F6F3500B37EF9B1 TRUE
542 144FAAF6E9F74A5CC6F118FF030D2355C371CADE648F01F39C32758A8EA843EA TRUE
543 5A1797441122B7A3AAECA83E555061507F8F36C568E894E351B8371241BC6E94 TRUE
544 BD369EA0DD0F14ED1C074C02809BB8E14C79B01468084D7781476A45E94BB1F4 TRUE
545 AC6EE7BE3E928F991197D5CE4716526ED9D7496DA9DE680A9106137437831ADD TRUE
546 D049B4F2F1FB3B85D32C9B1F54DC39637D53258766A90408F0E50CF01C429F5E TRUE
547 AFDCBE1E4E9B1A88F1F191052DE40C4DA4BE6F4747CBAA5DFC9D91C999399DE0 TRUE
548 0AD386CE3EAA4AD0C9414BC4E609733D5E4AE161F98A2417BA06F465C664B2BA TRUE
549 E293E555AC1DD09421C04853C1E2D998CF69AF402CF771DFC075F4DB709B52FA TRUE
550 79F4F3E069C81F0937AB47CC7164F13EC975F3C3464876A73D0CF274856DB8C4 TRUE
551 E822DF2372856FD8EC9B701F87E7915A9374166C34280BC70E46A9C4A3B78593 TRUE
552 8B52303081887107B651B4AD20BE384655517E2E0A99FF7C36FC68CF5FC5DCF5 TRUE
553 453A682DE8A235D237FC529E2DF2F4B7320FE0D4D47336C64668C395A807B9F6 TRUE
554 77E6C3971BB9CCB1B311CCF2B09F1AE0AAB36239FAF364709C3F3F0A05521748 TRUE
555 16A875E13E9B21ADA2F78D199E4BE2A2971F1253C502D09E3285D4B5EBA1556D TRUE
556 8A3FD8D0A8F9892256FAAEA02B699991880828270FBC74016AF4DD2AE0946AF4 TRUE
557 8755F29AF3E7E8252FCC5703EF15848B922925D02F4C09DB304D5AB878584538 TRUE
558 515752CDDFB4DDB61E3BF142E25FEC9A82D1F7778C558E0476F01461B5D08913 TRUE
559 2D0D72A2285937DE4100145C85A8EC37F7987348F6EE5F4025E5C3B32C65FF05 TRUE
560 BF843A70A33F538552D357F10F7BA1988EAAFE1F074BF6994884006CFDCCCC28 TRUE
561 F8442EA02DBD86F2994D8A5083F27F990AD2173F3A45119B12F201CD356E7E1C TRUE
562 9B63368E2BF93A06B9352C38FCBF2F1DED9A225E3D57E84C3D8F51F80E5B964E TRUE
563 131EB475143DBDEB24752B139EC32748C954EC3582C9E33F2B57C524A41DB456 TRUE
564 BB3284957F7505586D98C3BBEFD91CE381F43C6A646F17C1AEC6CF29FCD39DD0 TRUE
565 52BF5AC28980DAB8F54137ECF5D1E815C5A136830F1A6A078B897E9560AF5A0B TRUE
566 E3971916363C7DE9D79ABA042EA8496AEE0F800FEB1519FE39A269A62959B397 TRUE
567 392B01798C8CD047B8A0E8EE2648B32D5E34E2018BB05E58F9905E0375B2326D TRUE

In [398]:
write.csv(ever_AP_ids, "data/ever_AP_ids.csv", row.names = FALSE)