In [1]:
library(tidyverse)
library(dbplyr)
library(bigrquery)
library(lubridate)

bq_auth()

project_id = "yhcr-prd-bradfor-bia-core"

# create connection to database
con <- DBI::dbConnect(bigrquery::bigquery(), 
                      project = project_id)

print(paste0("Connected to : ", project_id))

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘dbplyr’


The following objects are masked from ‘package:dplyr’:

    ident, sql

[1] "Connected to : yhcr-prd-bradfor-bia-core"

#### Read in data and collect tables

In [2]:
person_ids <- read.csv('data/additional_person_ids.csv', header = TRUE)

In [3]:
school_data = "CB_2489.cb_InstitutionHistory"

In [4]:
school_match = "CB_2489.cb_School"

In [5]:
school_link_data = "CB_2489.cb_InstitutionLink"

In [6]:
enrol_data = "CB_2489.cb_Enrollment"

In [7]:
school_match_table <- tbl(con, school_match) |>
    select(SchoolID, URN
           )

In [8]:
enrol_table <- tbl(con, enrol_data) |>
    select(person_id, SchoolID, AcademicYear, 
           OnRoll_1, OnRoll_2, OnRoll_3, 
           EnrolStatus, EntryDate, LeavingDate, PartTime
           )

In [9]:
school_table <- tbl(con, school_data) |>
    select(InstitutionHistoryID, InstitutionID, AcademicYear,
           InstitutionTypeDesc, URN, SchoolName,
           PhaseOfEducationDesc
           )

In [10]:
school_link_table <- tbl(con, school_link_data) |>
    select(InstitutionLinkID, InstitutionHistoryID, AcademicYear,
           person_id
           )

In [11]:
school_match_df <- collect(school_match_table)

In [12]:
head(school_match_df)

  SchoolID URN
1  3978    108234
2  1935    108274
3 21112    108314
4 11201    108189
5 14610    139568
6  3644    108238

In [29]:
school_match <- school_match_df |>
    filter(SchoolID %in% c(cohort_schools))

In [30]:
head(school_match)

  SchoolID URN
1 1935     108274
2 1601     108280
3  712     108292
4 1338     108283
5  749     108275
6  461     108295

In [14]:
enrol_df <- collect(enrol_table)

In [15]:
school_df <- collect(school_table)

In [16]:
school_link_df <- collect(school_link_table)

In [17]:
school_link_filtered <- school_link_df |>
    filter(person_id %in% person_ids$person_id)

In [18]:
school_link_filtered

     InstitutionLinkID InstitutionHistoryID AcademicYear person_id

#### Filter enrolments table to target cohorts

In [19]:
enrol_filtered <- enrol_df |>
    filter(person_id %in% person_ids$person_id)

In [20]:
enrol_filtered |> arrange(AcademicYear) |> distinct(AcademicYear) |> pull(AcademicYear)

 [1] "2005/2006" "2006/2007" "2007/2008" "2008/2009" "2009/2010" "2010/2011"
 [7] "2011/2012" "2012/2013" "2013/2014" "2014/2015" "2015/2016"

In [21]:
enrol_filtered <- enrol_filtered |>
    left_join(person_ids, by = join_by(person_id))

Warning message in left_join(enrol_filtered, person_ids, by = join_by(person_id)):
“Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 28 of `x` matches multiple rows in `y`.
ℹ Row 8501 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.”

In [22]:
head(enrol_filtered)

  person_id                                                        SchoolID
1 A75F65A7F2D3B082CD11C6E84BEB92C794F1E36B71BE97CF675ACF317847DCA8 6589
2 35DFCB5D8F021D95483FF24CE410460A7265CE97C3E6D703CA8DAC6E3E333C47  125
3 CD414F29155D31984D61A6AFE5652D361C00277FEEFB3794FEFF130EA28F0CBB  125
4 868641B54D3700FE1E77718923B99D3A71905DA252D53EB8494816557E111548  125
5 3AF775F1DC69FD59BD020B2884CC8265B0F28DD726A1CB98C8F0091B0E3BE67B  125
6 0BFA0D59291474ECFA993CECC8B3553CB312919D1F7107A5A04EA234F4D9AEF5  125
  AcademicYear OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate  LeavingDate
1 2006/2007    1        1        1        C           2005-01-17 <NA>
2 2010/2011    1        1        1        C           2010-08-27 <NA>
3 2010/2011    1        1        1        C           2010-08-27 <NA>
4 2010/2011    1        1        1        C           2010-08-27 <NA>
5 2010/2011    1        1        1        C           2010-08-27 <NA>
6 2010/2011    1        1        1        C           2010-08-27 <NA>
  PartTime NCCIS_ACADYR
1 0        2016/2017
2 0        2015/2016
3 0        2015/2016
4 0        2015/2016
5 0        2015/2016
6 0        2015/2016

In [23]:
enrol_filtered <- enrol_filtered |>
    filter(NCCIS_ACADYR == '2015/2016' & AcademicYear %in% c('2010/2011','2011/2012','2012/2013','2013/2014','2014/2015') | 
           NCCIS_ACADYR == '2016/2017' & AcademicYear %in% c('2011/2012','2012/2013','2013/2014','2014/2015','2015/2016') 
           )

In [24]:
enrol_filtered |>
    filter(SchoolID == 1)

   person_id                                                        SchoolID
1  25F5060A19A32BB21DE8653F14808D83ADF8249605EEB64EEC27F5407032D447 1
2  E8395971480E040CEB423297E1D9DCC6BBC9D25E02567A15187154E990F86F7F 1
3  25B85E5B37238A30264AE7BFFBA79FB6BB585C93CE11D44E928189AB2A5C3982 1
4  25B85E5B37238A30264AE7BFFBA79FB6BB585C93CE11D44E928189AB2A5C3982 1
5  25B85E5B37238A30264AE7BFFBA79FB6BB585C93CE11D44E928189AB2A5C3982 1
6  25B85E5B37238A30264AE7BFFBA79FB6BB585C93CE11D44E928189AB2A5C3982 1
7  F311B88ED8899DAB06BCA8BE02AB751528FC7E2B472E86C8EF72C4B11B8BC76F 1
8  FB839E188C42610761A3BCEFD95B87EF4FA29DAB5311684F1D6BBC7EDE139D7A 1
9  0D2FC3E992EA35237C6F0D9D0AC60DAD63C93BE61C89F9BE236D217987DFF337 1
10 581ED04E267376988D18179062CC5E913D26F91A783BD4698A0F0DF2B3D27323 1
11 10F6C7A8721DD858A8049E041918A1AE799F412E50141F859F37963F4DF4C4C3 1
12 10F6C7A8721DD858A8049E041918A1AE799F412E50141F859F37963F4DF4C4C3 1
13 5B1E32EF8440708266CE735A84BC8860C4B7066A2E15A6758E96E0536E0152A6 1
14 CE3C4ADA592299841D92408004271BA973ED441588C4790A134A16E4A85CFF26 1
15 5353D2719006C22C604036AAAE753D90AC54C5767F8FE7B2D6D46CED4A2B1A7E 1
16 10F6C7A8721DD858A8049E041918A1AE799F412E50141F859F37963F4DF4C4C3 1
17 F311B88ED8899DAB06BCA8BE02AB751528FC7E2B472E86C8EF72C4B11B8BC76F 1
18 2A172F85EF84D6B1B587629BE8B368E05B8A27BF9985B146E7A63B5707305276 1
19 5B1E32EF8440708266CE735A84BC8860C4B7066A2E15A6758E96E0536E0152A6 1
20 2A172F85EF84D6B1B587629BE8B368E05B8A27BF9985B146E7A63B5707305276 1
21 CE3C4ADA592299841D92408004271BA973ED441588C4790A134A16E4A85CFF26 1
22 5B1E32EF8440708266CE735A84BC8860C4B7066A2E15A6758E96E0536E0152A6 1
23 2A172F85EF84D6B1B587629BE8B368E05B8A27BF9985B146E7A63B5707305276 1
24 FB839E188C42610761A3BCEFD95B87EF4FA29DAB5311684F1D6BBC7EDE139D7A 1
25 522D3317AA5A7D7B0F48CC0B9CA782940EFA619D95A1ACD8AB59CB1690A0EF71 1
26 5C5FFE2CF9C0A2BD8D4A9883A69B35FE7A16B10FB09A90FFC3445D406FCBAD7B 1
27 CE3C4ADA592299841D92408004271BA973ED441588C4790A134A16E4A85CFF26 1
28 95C91F8E0FE93B12A0423A3C7B1EAABE37957A048A0505ABAC96A4D843C3FE45 1
29 522D3317AA5A7D7B0F48CC0B9CA782940EFA619D95A1ACD8AB59CB1690A0EF71 1
30 5353D2719006C22C604036AAAE753D90AC54C5767F8FE7B2D6D46CED4A2B1A7E 1
31 10F6C7A8721DD858A8049E041918A1AE799F412E50141F859F37963F4DF4C4C3 1
32 CE3C4ADA592299841D92408004271BA973ED441588C4790A134A16E4A85CFF26 1
33 1A2F1FDCDF85A15B5EA7791D22E71C1329246BD1697429C6693F9A6B318E152D 1
34 3A7A55E43D31744C6589161660F3C07EA9331DAB151929218CDE8ED9F89BC2C9 1
35 95C91F8E0FE93B12A0423A3C7B1EAABE37957A048A0505ABAC96A4D843C3FE45 1
36 25F5060A19A32BB21DE8653F14808D83ADF8249605EEB64EEC27F5407032D447 1
37 25F5060A19A32BB21DE8653F14808D83ADF8249605EEB64EEC27F5407032D447 1
   AcademicYear OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate  LeavingDate
1  2012/2013    1        1        1        C           2012-03-07 <NA>
2  2013/2014    NA       1        NA       C           2014-01-21 <NA>
3  2013/2014    1        1        NA       C           2012-11-08 <NA>
4  2013/2014    1        1        NA       C           2012-11-08 <NA>
5  2012/2013    1        1        1        C           2012-11-08 <NA>
6  2012/2013    1        1        1        C           2012-11-08 <NA>
7  2013/2014    0        NA       NA       C           2012-10-10 2013-10-04
8  2012/2013    NA       1        0        C           2013-01-31 <NA>
9  2010/2011    NA       1        0        C           2011-02-15 2011-07-22
10 2013/2014    1        1        NA       C           2013-10-02 <NA>
11 2011/2012    1        1        1        C           2010-09-02 <NA>
12 2012/2013    1        1        1        C           2010-09-02 <NA>
13 2013/2014    1        1        NA       C           2012-03-07 <NA>
14 2011/2012    1        1        1        C           2010-09-02 <NA>
15 2011/2012    1        0        NA       C           2010-09-02 <NA>
16 2013/2014    1        1        NA       C           2010-09-02 <NA>
17 2012/2013    1        1        1        C           2012-10-10 <NA>
18 2011/2012    1        1        1        C           2011-09-05 <NA>
19 2012/2013    1        1        1        C           2012-03-07 <NA>
20 2012/2013    1        1        1        C           2011-09-05 <NA>
21 2010/2011    1        1        1        C           2010-09-02 <NA>
22 2011/2012    NA       1        1        C           2012-03-07 <NA>
23 2013/2014    1        1        NA       C           2011-09-05 <NA>
24 2013/2014    0        NA       NA       NA          2013-01-31 2013-09-27
25 2013/2014    1        1        NA       C           2013-05-02 <NA>
26 2010/2011    1        1        0        C           2010-09-02 2011-05-27
27 2012/2013    1        1        1        C           2010-09-02 <NA>
28 2012/2013    NA       1        1        C           2013-05-02 <NA>
29 2012/2013    NA       1        1        C           2013-05-02 <NA>
30 2010/2011    1        1        1        C           2010-09-02 <NA>
31 2010/2011    1        1        1        C           2010-09-02 <NA>
32 2013/2014    1        1        NA       C           2010-09-02 <NA>
33 2010/2011    1        0        NA       C           2010-09-02 2011-04-01
34 2013/2014    NA       1        NA       C           2014-03-24 <NA>
35 2013/2014    1        1        NA       C           2013-05-02 <NA>
36 2013/2014    1        1        NA       C           2012-03-07 <NA>
37 2011/2012    NA       1        1        C           2012-03-07 <NA>
   PartTime NCCIS_ACADYR
1  0        2015/2016
2  0        2015/2016
3  0        2016/2017
4  0        2016/2017
5  0        2016/2017
6  0        2016/2017
7  0        2015/2016
8  0        2015/2016
9  0        2015/2016
10 0        2016/2017
11 0        2015/2016
12 0        2015/2016
13 0        2016/2017
14 0        2015/2016
15 0        2015/2016
16 0        2015/2016
17 0        2015/2016
18 0        2016/2017
19 0        2016/2017
20 0        2016/2017
21 0        2015/2016
22 0        2016/2017
23 0        2016/2017
24 0        2015/2016
25 0        2015/2016
26 0        2015/2016
27 0        2015/2016
28 0        2016/2017
29 0        2015/2016
30 0        2015/2016
31 0        2015/2016
32 0        2015/2016
33 0        2015/2016
34 0        2016/2017
35 0        2016/2017
36 0        2015/2016
37 0        2015/2016

In [25]:
enrol_filtered |> arrange(person_id, AcademicYear)

      person_id                                                        SchoolID
1     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 12506
2     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 12506
3     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 12506
4     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 12506
5     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 12506
6     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 12433
7     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 12433
8     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 12433
9     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 12433
10    00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 12433
11    000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909   125
12    000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909   125
13    000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909   125
14    000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909   125
15    000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909   125
16    00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC 12433
17    00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC 12433
18    00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC 12433
19    00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC 12433
20    00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC 12433
21    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D  1562
22    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D  1562
23    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D  1562
24    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D  1562
25    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D  1562
26    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D  1562
27    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D  1562
28    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D  1562
29    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D  1562
30    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D  1562
⋮     ⋮                                                                ⋮
93628 FFEBA2A7088A41ADEF06DE231C6F48B615D19A0CA2D2FC917F432A964C9B2EA3  2376
93629 FFEBA2A7088A41ADEF06DE231C6F48B615D19A0CA2D2FC917F432A964C9B2EA3  2376
93630 FFEBA2A7088A41ADEF06DE231C6F48B615D19A0CA2D2FC917F432A964C9B2EA3  2376
93631 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC 13096
93632 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC 13096
93633 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC 13096
93634 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC 12161
93635 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC 12161
93636 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC 12161
93637 FFEF385FC541F397C34ACF193D6936D6BB045655B8781D7CFF18D632AAE9ED10 11547
93638 FFEF385FC541F397C34ACF193D6936D6BB045655B8781D7CFF18D632AAE9ED10 11547
93639 FFEF385FC541F397C34ACF193D6936D6BB045655B8781D7CFF18D632AAE9ED10 11547
93640 FFEF385FC541F397C34ACF193D6936D6BB045655B8781D7CFF18D632AAE9ED10 11547
93641 FFEF385FC541F397C34ACF193D6936D6BB045655B8781D7CFF18D632AAE9ED10 11547
93642 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB  1519
93643 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB 14095
93644 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB 14095
93645 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB 14095
93646 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB 14095
93647 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008   847
93648 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008  2077
93649 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008   847
93650 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008  2077
93651 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008  2077
93652 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008  2077
93653 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA  2680
93654 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA  2680
93655 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA  2680
93656 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA  2680
93657 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA  2680
      AcademicYear OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate
1     2011/2012    1        1        1        C           2011-09-05
2     2012/2013    1        1        1        C           2011-09-05
3     2013/2014    1        1        1        C           2011-09-05
4     2014/2015    1        1        1        C           2011-09-05
5     2015/2016    1        1        1        C           2011-09-05
6     2010/2011    1        1        1        C           2010-09-01
7     2011/2012    1        1        1        C           2010-09-01
8     2012/2013    1        1        1        C           2010-09-01
9     2013/2014    1        1        1        C           2010-09-01
10    2014/2015    1        1        0        C           2010-09-01
11    2010/2011    1        1        1        C           2010-08-27
12    2011/2012    1        1        1        C           2010-08-27
13    2012/2013    1        1        1        C           2010-08-27
14    2013/2014    1        1        1        C           2010-08-27
15    2014/2015    1        1        1        C           2010-08-27
16    2011/2012    1        1        1        C           2011-09-01
17    2012/2013    1        1        1        C           2011-09-01
18    2013/2014    1        1        1        C           2011-09-01
19    2014/2015    1        1        1        C           2011-09-01
20    2015/2016    1        1        1        C           2011-09-01
21    2011/2012    1        1        1        C           2011-09-06
22    2011/2012    1        1        1        C           2011-09-06
23    2012/2013    1        1        1        C           2011-09-06
24    2012/2013    1        1        1        C           2011-09-06
25    2013/2014    1        1        1        C           2011-09-06
26    2013/2014    1        1        1        C           2011-09-06
27    2014/2015    1        1        1        C           2011-09-06
28    2014/2015    1        1        1        C           2011-09-06
29    2015/2016    1        1        0        C           2011-09-06
30    2015/2016    1        1        0        C           2011-09-06
⋮     ⋮            ⋮        ⋮        ⋮        ⋮           ⋮
93628 2012/2013    1        1        1        C           2010-09-01
93629 2013/2014    1        1        1        C           2010-09-01
93630 2014/2015    1        1        0        C           2010-09-01
93631 2011/2012    1        1        1        C           2011-09-05
93632 2012/2013    1        1        1        C           2011-09-05
93633 2013/2014    1        0        NA       C           2011-09-05
93634 2013/2014    NA       1        1        C           2014-03-25
93635 2014/2015    1        1        1        C           2014-03-25
93636 2015/2016    1        1        0        C           2014-03-25
93637 2010/2011    1        1        1        C           2010-09-01
93638 2011/2012    1        1        1        C           2010-09-01
93639 2012/2013    1        1        1        C           2010-09-01
93640 2013/2014    1        1        1        C           2010-09-01
93641 2014/2015    1        1        1        C           2010-09-01
93642 2011/2012    0        NA       NA       C           2011-09-06
93643 2012/2013    1        1        1        C           2013-01-07
93644 2013/2014    1        1        1        C           2013-01-07
93645 2014/2015    1        1        1        C           2013-01-07
93646 2015/2016    1        1        0        C           2013-01-07
93647 2011/2012    1        1        1        C           2011-09-06
93648 2012/2013    1        1        1        C           2012-11-06
93649 2012/2013    0        NA       NA       C           2011-09-06
93650 2013/2014    1        1        1        C           2012-11-06
93651 2014/2015    1        1        1        C           2012-11-06
93652 2015/2016    1        1        0        C           2012-11-06
93653 2010/2011    1        1        1        C           2010-09-01
93654 2011/2012    1        1        1        C           2010-09-01
93655 2012/2013    1        1        1        C           2010-09-01
93656 2013/2014    1        1        1        C           2010-09-01
93657 2014/2015    1        1        1        C           2010-09-01
      LeavingDate PartTime NCCIS_ACADYR
1     <NA>        0        2016/2017
2     <NA>        0        2016/2017
3     <NA>        0        2016/2017
4     <NA>        0        2016/2017
5     <NA>        0        2016/2017
6     <NA>        0        2015/2016
7     <NA>        0        2015/2016
8     <NA>        0        2015/2016
9     <NA>        0        2015/2016
10    2015-08-31  0        2015/2016
11    <NA>        0        2015/2016
12    <NA>        0        2015/2016
13    <NA>        0        2015/2016
14    <NA>        0        2015/2016
15    <NA>        0        2015/2016
16    <NA>        0        2016/2017
17    <NA>        0        2016/2017
18    <NA>        0        2016/2017
19    <NA>        0        2016/2017
20    <NA>        0        2016/2017
21    <NA>        0        2016/2017
22    <NA>        0        2016/2017
23    <NA>        0        2016/2017
24    <NA>        0        2016/2017
25    <NA>        0        2016/2017
26    <NA>        0        2016/2017
27    <NA>        0        2016/2017
28    <NA>        0        2016/2017
29    2016-07-22  0        2016/2017
30    2016-07-22  0        2016/2017
⋮     ⋮           ⋮        ⋮
93628 <NA>        0        2015/2016
93629 <NA>        0        2015/2016
93630 2015-07-18  0        2015/2016
93631 <NA>        0        2016/2017
93632 <NA>        0        2016/2017
93633 2014-03-24  0        2016/2017
93634 <NA>        0        2016/2017
93635 <NA>        0        2016/2017
93636 2016-07-26  0        2016/2017
93637 <NA>        0        2015/2016
93638 <NA>        0        2015/2016
93639 <NA>        0        2015/2016
93640 <NA>        0        2015/2016
93641 <NA>        0        2015/2016
93642 2012-01-04  0        2016/2017
93643 <NA>        0        2016/2017
93644 <NA>        0        2016/2017
93645 <NA>        0        2016/2017
93646 2016-06-27  0        2016/2017
93647 <NA>        0        2016/2017
93648 <NA>        0        2016/2017
93649 2012-10-19  0        2016/2017
93650 <NA>        0        2016/2017
93651 <NA>        0        2016/2017
93652 2016-06-30  0        2016/2017
93653 <NA>        0        2015/2016
93654 <NA>        0        2015/2016
93655 <NA>        0        2015/2016
93656 <NA>        0        2015/2016
93657 <NA>        0        2015/2016

#### Get list of school IDs in enrollments table

In [26]:
cohort_schools <- enrol_filtered |> arrange(SchoolID) |> distinct(SchoolID) |> pull(SchoolID)

In [27]:
length(cohort_schools)

[1] 2262

In [31]:
head(school_match)

  SchoolID URN
1 1935     108274
2 1601     108280
3  712     108292
4 1338     108283
5  749     108275
6  461     108295

#### Join schools info into school match IDs

In [32]:
head(school_df)

  InstitutionHistoryID InstitutionID AcademicYear
1 968                  3198          2005/2006
2 25892                8275          2005/2006
3 40609                11287         2005/2006
4 56451                14508         2005/2006
5 123604               28104         2005/2006
6 124903               28374         2005/2006
  InstitutionTypeDesc                URN    SchoolName
1 Community school (CY)              100222 Craven Park School
2 Community school (CY)              105771 Hill Top Community Primary School
3 Community school (CY)              109069 Radstock Infant School
4 Independent schools (other) (IND)  112448 Holme Park School
5 Community school (CY)              130095 Wembley Primary School
6 Further Educational sector college 130541 Park Lane College, Leeds
  PhaseOfEducationDesc
1 Primary
2 Primary
3 Primary
4 Not applicable
5 Primary
6 16 Plus

In [33]:
school_df$URN <- as.numeric(school_df$URN)

In [48]:
schools_filtered <- school_match |>
    left_join(school_df, by = join_by(URN)) |>
    select(SchoolID, URN, AcademicYear, InstitutionTypeDesc, SchoolName, PhaseOfEducationDesc)

In [49]:
schools_filtered <- schools_filtered |>
    distinct()

In [50]:
head(schools_filtered)

  SchoolID URN    AcademicYear InstitutionTypeDesc
1 1935     108274 2005/2006    Community school (CY)
2 1935     108274 2006/2007    Community school (CY)
3 1935     108274 2007/2008    Community school (CY)
4 1935     108274 2008/2009    Community school (CY)
5 1935     108274 2009/2010    Community school (CY)
6 1935     108274 2010/2011    Community School (CY)
  SchoolName                           PhaseOfEducationDesc
1 Hemsworth Arts and Community College Secondary
2 Hemsworth Arts and Community College Secondary
3 Hemsworth Arts and Community College Secondary
4 Hemsworth Arts and Community College Secondary
5 Hemsworth Arts and Community College Secondary
6 Hemsworth Arts and Community College Secondary

In [51]:
schools_filtered |>
    filter(SchoolID == 1935)

   SchoolID URN    AcademicYear InstitutionTypeDesc
1  1935     108274 2005/2006    Community school (CY)
2  1935     108274 2006/2007    Community school (CY)
3  1935     108274 2007/2008    Community school (CY)
4  1935     108274 2008/2009    Community school (CY)
5  1935     108274 2009/2010    Community school (CY)
6  1935     108274 2010/2011    Community School (CY)
7  1935     108274 2011/2012    Community School (CY)
8  1935     108274 2012/2013    Community School (CY)
9  1935     108274 2013/2014    Community School (CY)
10 1935     108274 2014/2015    Community School (CY)
11 1935     108274 2015/2016    Community School (CY)
12 1935     108274 2016/2017    Community School (CY)
13 1935     108274 2017/2018    Community School (CY)
14 1935     108274 2018/2019    Community School (CY)
15 1935     108274 2019/2020    Community School (CY)
16 1935     108274 2020/2021    Community School (CY)
17 1935     108274 2021/2022    Community School (CY)
   SchoolName                           PhaseOfEducationDesc
1  Hemsworth Arts and Community College Secondary
2  Hemsworth Arts and Community College Secondary
3  Hemsworth Arts and Community College Secondary
4  Hemsworth Arts and Community College Secondary
5  Hemsworth Arts and Community College Secondary
6  Hemsworth Arts and Community College Secondary
7  Hemsworth Arts and Community College Secondary
8  Hemsworth Arts and Community College Secondary
9  Hemsworth Arts and Community College Secondary
10 Hemsworth Arts and Community College Secondary
11 Hemsworth Arts and Community College Secondary
12 Hemsworth Arts and Community College Secondary
13 Hemsworth Arts and Community College Secondary
14 Hemsworth Arts and Community College Secondary
15 Hemsworth Arts and Community College Secondary
16 Hemsworth Arts and Community College Secondary
17 Hemsworth Arts and Community College Secondary

#### Clean up schools data

In [52]:
# fill NAs in the Phase of Edu col
schools_filtered <- schools_filtered |>
  group_by(URN) |>
  mutate(
    PhaseOfEducationDesc = if_else(
      is.na(PhaseOfEducationDesc),
      first(na.omit(PhaseOfEducationDesc)),
      PhaseOfEducationDesc
    )
  ) |>
  ungroup()

In [53]:
# keep only first row per academic year where multiple per school (e.g. change in school type mid year to academy status)
schools_filtered <- schools_filtered |>
  arrange(AcademicYear) |>
  group_by(SchoolID, URN, AcademicYear) |>
  slice(1) |>
  ungroup()

In [54]:
schools_filtered |> 
    filter(SchoolID == 21)

     SchoolID URN AcademicYear InstitutionTypeDesc SchoolName
     PhaseOfEducationDesc

In [55]:
# Check if SchoolID + AcademicYear is unique 
schools_filtered |>
  count(SchoolID, AcademicYear) |>
  filter(n > 1)  # problem rows

     SchoolID AcademicYear n

#### clean up institution types

In [60]:
schools_filtered |>
    distinct(InstitutionTypeDesc)

   InstitutionTypeDesc
1  Community school
2  Voluntary aided school
3  Foundation school
4  Academy
5  Academy sponsor led
6  Voluntary controlled school
7  Community special school
8  Community hospital school
9  Non-maintained special school
10 Foundation special school
11 Academy converter
12 Academy special school
13 Academy Converter Special School
14 Free school
15 Free special school (16-19)
16 Studio school
17 AP/PRU
18 University technical college

In [57]:
schools_filtered <- schools_filtered |>
  mutate(InstitutionTypeDesc = str_replace_all(InstitutionTypeDesc, "û", "-"))

In [58]:
schools_filtered <- schools_filtered |>
  mutate(InstitutionTypeDesc = InstitutionTypeDesc |> 
           str_trim())

In [59]:
schools_filtered <- schools_filtered |>
    mutate(InstitutionTypeDesc = case_when(
            InstitutionTypeDesc %in% c("Community school (CY)", "Community School (CY)") ~ 'Community school',
        
        InstitutionTypeDesc %in% c("Voluntary aided school (VA)", "Voluntary Aided School (VA)") ~ 'Voluntary aided school',
        
        InstitutionTypeDesc %in% c("Foundation School (FD)", "Foundation school (FD)") ~ 'Foundation school',
        
        InstitutionTypeDesc %in% c("Voluntary controlled school (VC)", "Voluntary Controlled School (VC)") ~ 'Voluntary controlled school',
        
        InstitutionTypeDesc %in% c("Academy (AC)", "Academy Schhol", "Academy Free Schools / Consortia") ~ 'Academy',
        
        InstitutionTypeDesc %in% c("Academy Sponsor Led (AC)", "Academy - Sponsor Led Mainstream (AC)") ~ 'Academy sponsor led',
        
        InstitutionTypeDesc %in% c("City technology college (CTC)", "City technology College (CTC)", "City Technology College (CTC)") ~ 'City technology college',
        
        InstitutionTypeDesc %in% c("Community special school (CYS)", "Community Special School (CYS)") ~ 'Community special school',
        
        InstitutionTypeDesc %in% c("Special school not maintained by LEA (NMSS)", "Non-Maintained Special School (NMSS)") ~ 'Non-maintained special school',
        
        InstitutionTypeDesc %in% c("Foundation special school (FDS)", "Foundation Special School (FDS)") ~ 'Foundation special school',
        
        InstitutionTypeDesc %in% c("Community hospital school (CYH)") ~ 'Community hospital school',
        
        InstitutionTypeDesc %in% c("Academy Converters Mainstream", "Academy Converter - Mainstream (ACC)") ~ 'Academy converter',
        
        InstitutionTypeDesc %in% c("Free School - Mainstream (F)", "Community School (CY)") ~ 'Free school',
        
        InstitutionTypeDesc %in% c("Academy - Converter Special School (ACCS)", "Academy - Sponsor Led Special School (ACS)") ~ 'Academy special school',
        
        InstitutionTypeDesc %in% c("Pupil referral unit", "Pupil Referral Unit", 
                                   'Pupil Referral Unit (PRU)', 'Academy - Converter AP (ACCAP)',
                                  'Free School - Alternative Provision', 'Academy - Sponsor Led AP (ACAP)',
                                  'Free School - Alternative Provision (FAP)') ~ 'AP/PRU',
        
        InstitutionTypeDesc %in% c("Free School - Studio School (FSS)", 'Free School - Studio School') ~ 'Studio school',
        InstitutionTypeDesc %in% c("Free School - UTC (FUTC)", "Free School - UTC") ~ 'University technical college',
        InstitutionTypeDesc %in% c("Free School - Studio School (FSS)") ~ 'Studio school',
        InstitutionTypeDesc %in% c("Free School - 16-19 (F1619)") ~ 'Free school (16-19)',
        InstitutionTypeDesc %in% c("Free School - Special (FS)") ~ 'Free special school (16-19)',
    TRUE ~ InstitutionTypeDesc)
           )

#### check for schools changing name

In [61]:
schools_filtered <- schools_filtered |>
  mutate(SchoolName = gsub("[[:punct:]]", "", SchoolName))

In [62]:
schools_filtered <- schools_filtered |>
  mutate(SchoolName = SchoolName |> 
           str_trim())

In [63]:
schools_filtered |>
    group_by(URN) |> 
    filter(n_distinct(SchoolName) > 1) |> 
    arrange(URN, SchoolName)

      SchoolID URN    AcademicYear InstitutionTypeDesc
1     1512     100182 2012/2013    Community school
2     1512     100182 2013/2014    Community school
3     1512     100182 2014/2015    Community school
4     1512     100182 2015/2016    Community school
5     1512     100182 2016/2017    Community school
6     1512     100182 2017/2018    Community school
7     1512     100182 2018/2019    Community school
8     1512     100182 2019/2020    Community school
9     1512     100182 2020/2021    Community school
10    1512     100182 2021/2022    Community school
11    1512     100182 2005/2006    Community school
12    1512     100182 2006/2007    Community school
13    1512     100182 2007/2008    Community school
14    1512     100182 2008/2009    Community school
15    1512     100182 2009/2010    Community school
16    1512     100182 2010/2011    Community school
17    1512     100182 2011/2012    Community school
18    1358     100189 2012/2013    Community school
19    1358     100189 2013/2014    Community school
20    1358     100189 2014/2015    Community school
21    1358     100189 2015/2016    Community school
22    1358     100189 2016/2017    Community school
23    1358     100189 2017/2018    Community school
24    1358     100189 2018/2019    Community school
25    1358     100189 2019/2020    Community school
26    1358     100189 2020/2021    Community school
27    1358     100189 2021/2022    Community school
28    1358     100189 2005/2006    Community school
29    1358     100189 2006/2007    Community school
30    1358     100189 2007/2008    Community school
⋮     ⋮        ⋮      ⋮            ⋮
10446 16282    142061 2021/2022    Academy sponsor led
10447 16282    142061 2014/2015    Academy sponsor led
10448 16518    142088 2016/2017    Academy sponsor led
10449 16518    142088 2017/2018    Academy sponsor led
10450 16518    142088 2018/2019    Academy sponsor led
10451 16518    142088 2019/2020    Academy sponsor led
10452 16518    142088 2020/2021    Academy sponsor led
10453 16518    142088 2021/2022    Academy sponsor led
10454 16518    142088 2015/2016    Academy sponsor led
10455 16856    142135 2015/2016    AP/PRU
10456 16856    142135 2016/2017    AP/PRU
10457 16856    142135 2017/2018    AP/PRU
10458 16856    142135 2018/2019    AP/PRU
10459 16856    142135 2019/2020    AP/PRU
10460 16856    142135 2020/2021    AP/PRU
10461 16856    142135 2021/2022    AP/PRU
10462 16500    142387 2015/2016    Academy sponsor led
10463 16500    142387 2016/2017    Academy sponsor led
10464 16500    142387 2017/2018    Academy sponsor led
10465 16500    142387 2018/2019    Academy sponsor led
10466 16500    142387 2019/2020    Academy sponsor led
10467 16500    142387 2020/2021    Academy sponsor led
10468 16500    142387 2021/2022    Academy sponsor led
10469 16577    142762 2018/2019    Academy sponsor led
10470 16577    142762 2019/2020    Academy sponsor led
10471 16577    142762 2020/2021    Academy sponsor led
10472 16577    142762 2021/2022    Academy sponsor led
10473 16577    142762 2015/2016    Academy sponsor led
10474 16577    142762 2016/2017    Academy sponsor led
10475 16577    142762 2017/2018    Academy sponsor led
      SchoolName
1     Eltham Hill School
2     Eltham Hill School
3     Eltham Hill School
4     Eltham Hill School
5     Eltham Hill School
6     Eltham Hill School
7     Eltham Hill School
8     Eltham Hill School
9     Eltham Hill School
10    Eltham Hill School
11    Eltham Hill Technology College for Girls
12    Eltham Hill Technology College for Girls
13    Eltham Hill Technology College for Girls
14    Eltham Hill Technology College for Girls
15    Eltham Hill Technology College for Girls
16    Eltham Hill Technology College for Girls
17    Eltham Hill Technology College for Girls
18    Crown Woods College
19    Crown Woods College
20    Crown Woods College
21    Crown Woods College
22    Crown Woods College
23    Crown Woods College
24    Crown Woods College
25    Crown Woods College
26    Crown Woods College
27    Crown Woods College
28    Crown Woods School
29    Crown Woods School
30    Crown Woods School
⋮     ⋮
10446 EBOR Academy Filey
10447 Filey School
10448 Pleckgate High School
10449 Pleckgate High School
10450 Pleckgate High School
10451 Pleckgate High School
10452 Pleckgate High School
10453 Pleckgate High School
10454 Pleckgate High School Mathematics and Computing College
10455 The Hub Alternative Provision Centre
10456 The Hub Alternative Provision Centre
10457 The Hub School
10458 The Hub School
10459 The Hub School
10460 The Hub School
10461 The Hub School
10462 Hastingsbury Business  Enterprise College
10463 Kempston Challenger Academy
10464 Kempston Challenger Academy
10465 Kempston Challenger Academy
10466 Kempston Challenger Academy
10467 Kempston Challenger Academy
10468 Kempston Challenger Academy
10469 Coop Academy North Manchester
10470 Coop Academy North Manchester
10471 Coop Academy North Manchester
10472 Coop Academy North Manchester
10473 Manchester Creative and Media Academy
10474 Manchester Creative and Media Academy
10475 Manchester Creative and Media Academy
      PhaseOfEducationDesc
1     Secondary
2     Secondary
3     Secondary
4     Secondary
5     Secondary
6     Secondary
7     Secondary
8     Secondary
9     Secondary
10    Secondary
11    Secondary
12    Secondary
13    Secondary
14    Secondary
15    Secondary
16    Secondary
17    Secondary
18    Secondary
19    Secondary
20    Secondary
21    Secondary
22    Secondary
23    Secondary
24    Secondary
25    Secondary
26    Secondary
27    Secondary
28    Secondary
29    Secondary
30    Secondary
⋮     ⋮
10446 Secondary
10447 Secondary
10448 Secondary
10449 Secondary
10450 Secondary
10451 Secondary
10452 Secondary
10453 Secondary
10454 Secondary
10455 Not applicable
10456 Not applicable
10457 Not applicable
10458 Not applicable
10459 Not applicable
10460 Not applicable
10461 Not applicable
10462 Secondary
10463 Secondary
10464 Secondary
10465 Secondary
10466 Secondary
10467 Secondary
10468 Secondary
10469 Secondary
10470 Secondary
10471 Secondary
10472 Secondary
10473 Secondary
10474 Secondary
10475 Secondary

In [64]:
latest_names <- schools_filtered |>
    group_by(URN) |>
    slice_max(AcademicYear, n = 1, with_ties = FALSE) |>
    select(URN, SchoolName) |>
    rename(LatestSchoolName = SchoolName)

In [65]:
head(latest_names)

  URN    LatestSchoolName
1 100049 Haverstock School
2 100053 Acland Burghley School
3 100182 Eltham Hill School
4 100187 Woolwich Polytechnic School for Boys
5 100189 Crown Woods College
6 100190 Thomas Tallis School

In [474]:
latest_names |>
    filter(URN == 107302)

  URN    LatestSchoolName
1 107302 All Saints CofE Primary School

In [66]:
schools_filtered <- schools_filtered |>
    left_join(latest_names, by = "URN") |>
    mutate(SchoolName = coalesce(LatestSchoolName, SchoolName)) |>
    select(-LatestSchoolName)

In [67]:
head(schools_filtered)

  SchoolID URN    AcademicYear InstitutionTypeDesc SchoolName
1 1        108056 2005/2006    Community school    City of Leeds School
2 1        108056 2006/2007    Community school    City of Leeds School
3 1        108056 2007/2008    Community school    City of Leeds School
4 1        108056 2008/2009    Community school    City of Leeds School
5 1        108056 2009/2010    Community school    City of Leeds School
6 1        108056 2010/2011    Community school    City of Leeds School
  PhaseOfEducationDesc
1 Secondary
2 Secondary
3 Secondary
4 Secondary
5 Secondary
6 Secondary

#### fuzzy match for slightly different name spellings

In [243]:
install.packages('stringdist')

Installing package into ‘/home/jupyter/.R/library’
(as ‘lib’ is unspecified)

In [244]:
library(stringdist)

In [284]:
school_names <- unique(schools_filtered$SchoolName)

In [285]:
dist_matrix <- stringdistmatrix(school_names, school_names, method = "jw")

In [286]:
# Find likely duplicates based on low distance
fuzzy_matches <- which(dist_matrix < 0.1 & dist_matrix > 0, arr.ind = TRUE)

In [301]:
enrol_final |>
    filter(SchoolName == 'Queen Elizabeths School')

  person_id                                                        SchoolID
1 BB1C7F4FC50A60FF728A48C7F2A3C4496F2E6765FA62119EBBF5ABB6FB133735 16226
2 BB1C7F4FC50A60FF728A48C7F2A3C4496F2E6765FA62119EBBF5ABB6FB133735 16226
3 BB1C7F4FC50A60FF728A48C7F2A3C4496F2E6765FA62119EBBF5ABB6FB133735 16226
4 D5BC71328A6A3D4C7F394FF461AB2209C88B7569BF0CFFDA0A73A87D0AB8607C 16226
  AcademicYear OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate  LeavingDate
1 2015/2016    1        1        1        C           2015-09-01 <NA>
2 2016/2017    1        1        1        C           2015-09-01 <NA>
3 2017/2018    1        1        1        C           2015-09-01 <NA>
4 2015/2016    1        0        NA       C           2015-09-02 2016-02-26
  PartTime NCCIS_ACADYR URN    InstitutionTypeDesc SchoolName
1 0        2018/2019    141526 Academy converter   Queen Elizabeths School
2 0        2018/2019    141526 Academy converter   Queen Elizabeths School
3 0        2018/2019    141526 Academy converter   Queen Elizabeths School
4 0        2018/2019    141526 Academy converter   Queen Elizabeths School
  PhaseOfEducationDesc LatestURN
1 Secondary            141526
2 Secondary            141526
3 Secondary            141526
4 Secondary            141526

In [303]:
enrol_final |>
    filter(SchoolName == "Queen Elizabeths Grammar School")

  person_id                                                        SchoolID
1 5E067A183AF6A1DFCA5B9A38548CB42F4131EE05E131A525F083F605CCFADB55 16035
2 8F2BE8D2C898930C38AA9528327C1F76996160EED76CE10B90E666D588D3E436 11607
3 8F2BE8D2C898930C38AA9528327C1F76996160EED76CE10B90E666D588D3E436 11607
4 5E067A183AF6A1DFCA5B9A38548CB42F4131EE05E131A525F083F605CCFADB55 16035
5 8F2BE8D2C898930C38AA9528327C1F76996160EED76CE10B90E666D588D3E436 11607
6 8F2BE8D2C898930C38AA9528327C1F76996160EED76CE10B90E666D588D3E436 11607
7 5E067A183AF6A1DFCA5B9A38548CB42F4131EE05E131A525F083F605CCFADB55 16035
8 8F2BE8D2C898930C38AA9528327C1F76996160EED76CE10B90E666D588D3E436 11607
9 5E067A183AF6A1DFCA5B9A38548CB42F4131EE05E131A525F083F605CCFADB55 16035
  AcademicYear OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate  LeavingDate
1 2017/2018    1        1        1        C           2014-09-22 <NA>
2 2013/2014    1        1        1        C           2012-09-03 <NA>
3 2016/2017    1        1        1        C           2012-09-03 <NA>
4 2014/2015    1        1        1        C           2014-09-22 <NA>
5 2014/2015    1        1        1        C           2012-09-03 <NA>
6 2015/2016    1        1        1        C           2012-09-03 <NA>
7 2015/2016    1        1        1        C           2014-09-22 <NA>
8 2012/2013    1        1        1        C           2012-09-03 <NA>
9 2016/2017    1        1        1        C           2014-09-22 <NA>
  PartTime NCCIS_ACADYR URN    InstitutionTypeDesc
1 0        2018/2019    141165 Free school
2 0        2017/2018    136972 Academy converter
3 0        2017/2018    136972 Academy converter
4 0        2018/2019    141165 Free school
5 0        2017/2018    136972 Academy converter
6 0        2017/2018    136972 Academy converter
7 0        2018/2019    141165 Free school
8 0        2017/2018    136972 Academy converter
9 0        2018/2019    141165 Free school
  SchoolName                      PhaseOfEducationDesc LatestURN
1 Queen Elizabeths Grammar School NA                   136972
2 Queen Elizabeths Grammar School Secondary            136972
3 Queen Elizabeths Grammar School Secondary            136972
4 Queen Elizabeths Grammar School NA                   136972
5 Queen Elizabeths Grammar School Secondary            136972
6 Queen Elizabeths Grammar School Secondary            136972
7 Queen Elizabeths Grammar School NA                   136972
8 Queen Elizabeths Grammar School Secondary            136972
9 Queen Elizabeths Grammar School NA                   136972

In [287]:
tibble(
  name1 = school_names[fuzzy_matches[, 1]],
  name2 = school_names[fuzzy_matches[, 2]],
  distance = dist_matrix[fuzzy_matches]
) %>%
  distinct() %>%
  arrange(distance)

    name1                                 name2
1   Queen Elizabeths School               Queen Elizabeth School
2   Queen Elizabeth School                Queen Elizabeths School
3   Hinde House 216 School                Hinde House 316 School
4   Hinde House 316 School                Hinde House 216 School
5   Bedale High School                    Beal High School
6   Forest Hall School                    Forest Hill School
7   Beal High School                      Bedale High School
8   Forest Hill School                    Forest Hall School
9   Brookfield School                     Broomfield School
10  Broomfield School                     Brookfield School
11  Goole High School                     Poole High School
12  Poole High School                     Goole High School
13  Mark Hall Academy                     Park Hall Academy
14  Park Hall Academy                     Mark Hall Academy
15  Emmanuel College                      Immanuel College
16  Immanuel College                      Emmanuel College
17  Haworth Primary School                Oakworth Primary School
18  Oakworth Primary School               Haworth Primary School
19  Stanley High School                   Sale High School
20  The Kings School                      The Kingsway School
21  Sale High School                      Stanley High School
22  The Kingsway School                   The Kings School
23  Bushey Meads School                   Rushey Mead School
24  Avon Valley Academy                   Don Valley Academy
25  Rushey Mead School                    Bushey Meads School
26  Don Valley Academy                    Avon Valley Academy
27  The Warren School                     The Warriner School
28  The Warriner School                   The Warren School
29  Westfield Primary School              Nessfield Primary School
30  Nessfield Primary School              Westfield Primary School
⋮   ⋮                                     ⋮
259 Wilsden Primary School                Westfield Primary School
260 Westfield Primary School              Wilsden Primary School
261 Queen Elizabeths Grammar School       Queen Elizabeth School
262 Queen Elizabeth School                Queen Elizabeths Grammar School
263 Meridian High School                  Marden High School
264 Marden High School                    Meridian High School
265 Honley High School                    Hyde High School
266 Hyde High School                      Honley High School
267 Bosworth Academy                      Brinsworth Academy
268 Presdales School                      Priestlands School
269 Brinsworth Academy                    Bosworth Academy
270 Shavington Academy                    Paignton Academy
271 Priestlands School                    Presdales School
272 Paignton Academy                      Shavington Academy
273 Queen Elizabeths School               Queen Elizabeth High School
274 Queen Elizabeth High School           Queen Elizabeths School
275 Endon High School                     Endeavour High School
276 Endeavour High School                 Endon High School
277 Outwood Academy Freeston              Outwood Academy Carlton
278 Outwood Academy Carlton               Outwood Academy Freeston
279 St Anselms Catholic School Canterbury St Anselms Catholic School
280 St Anselms Catholic School            St Anselms Catholic School Canterbury
281 Tring School                          Trinity School
282 Trinity School                        Tring School
283 Weaverham High School                 Caterham High School
284 Caterham High School                  Weaverham High School
285 Brigshaw High School                  Brighouse High School
286 Brighouse High School                 Brigshaw High School
287 Braunton Academy                      Brayton Academy
288 Brayton Academy                       Braunton Academy
    distance
1   0.01449275
2   0.01449275
3   0.03030303
4   0.03030303
5   0.03703704
6   0.03703704
7   0.03703704
8   0.03703704
9   0.03921569
10  0.03921569
11  0.03921569
12  0.03921569
13  0.03921569
14  0.03921569
15  0.04166667
16  0.04166667
17  0.04413702
18  0.04413702
19  0.05263158
20  0.05263158
21  0.05263158
22  0.05263158
23  0.05360624
24  0.05360624
25  0.05360624
26  0.05360624
27  0.05469556
28  0.05469556
29  0.05555556
30  0.05555556
⋮   ⋮
259 0.09650072
260 0.09650072
261 0.09677419
262 0.09677419
263 0.09814815
264 0.09814815
265 0.09861111
266 0.09861111
267 0.09861111
268 0.09861111
269 0.09861111
270 0.09861111
271 0.09861111
272 0.09861111
273 0.09894842
274 0.09894842
275 0.09897292
276 0.09897292
277 0.09903382
278 0.09903382
279 0.09909910
280 0.09909910
281 0.09920635
282 0.09920635
283 0.09947090
284 0.09947090
285 0.09947090
286 0.09947090
287 0.09960317
288 0.09960317

In [ ]:
#school_names_clean <- schools_filtered |>
#    mutate(SchoolName = case_when(
#            SchoolName %in% c("Hinde House 216 School", "Hinde House 316 School") ~ 'Hinde House 2-16 School',
#        SchoolName %in% c("St Josephs Catholic College", "St Bedes and St Josephs Catholic College") ~ 'St Bedes and St Josephs Catholic College',
#        SchoolName %in% c("Oakbank School", "Beckfoot Oakbank") ~ 'Beckfoot Oakbank',
#        SchoolName %in% c("Tong High School", "Tong Leadership Academy") ~ 'Tong Leadership Academy',
#        SchoolName %in% c("St Anselms Catholic School", "St Anselms Catholic School Canterbury") ~ 'Hinde House 2-16 School',

In [307]:
enrol_final |>
    filter(SchoolName == "St Anselms Catholic School")

  person_id                                                        SchoolID
1 329745E3565E94BD632FA7AB0F347C5E1C5B5DDE0E32304B542436108D440D9F 1505
2 329745E3565E94BD632FA7AB0F347C5E1C5B5DDE0E32304B542436108D440D9F 1505
3 296E09A08A59BA0C6C6491466160F8E03009E1F05A3F75C0ADA1D848F541F631 1505
  AcademicYear OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate  LeavingDate
1 2012/2013    NA       1        1        C           2013-05-07 <NA>
2 2013/2014    1        1        1        M           2013-05-07 <NA>
3 2013/2014    1        1        1        C           2013-09-03 <NA>
  PartTime NCCIS_ACADYR URN    InstitutionTypeDesc
1 0        2017/2018    118918 Voluntary aided school
2 0        2017/2018    118918 Voluntary aided school
3 0        2018/2019    118918 Voluntary aided school
  SchoolName                 PhaseOfEducationDesc LatestURN
1 St Anselms Catholic School Secondary            118918
2 St Anselms Catholic School Secondary            118918
3 St Anselms Catholic School Secondary            118918

#### Decision - treat academisation as new school - DfE do as asign new URN

#### IGNORE check for schools changing URN because of becoming academies etc...

In [ ]:
#schools_filtered |>
    group_by(SchoolName) |> 
    filter(n_distinct(URN) > 1) |> 
    arrange(SchoolName, URN)

In [289]:
#latest_urn <- schools_filtered |>
    group_by(SchoolName) |>
    slice_max(AcademicYear, n = 1, with_ties = FALSE) |>
    select(URN, SchoolName) |>
    rename(LatestURN = URN)

In [308]:
#head(latest_urn)

In [291]:
#schools_filtered <- schools_filtered |>
  left_join(latest_urn, by = "SchoolName")

In [329]:
schools_filtered |>
    group_by(SchoolName) |> 
    filter(n_distinct(URN) > 1) |> 
    arrange(SchoolName, URN)

     SchoolID URN    AcademicYear InstitutionTypeDesc
1    10414    135622 2007/2008    Academy
2    10414    135622 2008/2009    Academy
3    10414    135622 2009/2010    Academy
4    10414    135622 2010/2011    Academy sponsor led
5    10414    135622 2011/2012    Academy sponsor led
6    10414    135622 2012/2013    Academy sponsor led
7    10414    135622 2013/2014    Academy sponsor led
8    10414    135622 2014/2015    Academy sponsor led
9    10414    135622 2015/2016    Academy sponsor led
10   10414    135622 2016/2017    Academy sponsor led
11   10414    135622 2017/2018    Academy sponsor led
12   10414    135622 2018/2019    Academy sponsor led
13   10414    135622 2019/2020    Academy sponsor led
14   10414    135622 2020/2021    Academy sponsor led
15   10414    135622 2021/2022    Academy sponsor led
16   18018    145477 2017/2018    Academy sponsor led
17   18018    145477 2018/2019    Academy sponsor led
18   18018    145477 2019/2020    Academy sponsor led
19   18018    145477 2020/2021    Academy sponsor led
20   18018    145477 2021/2022    Academy sponsor led
21   11806    136142 2009/2010    Academy
22   11806    136142 2010/2011    Academy sponsor led
23   11806    136142 2011/2012    Academy sponsor led
24   11806    136142 2012/2013    Academy sponsor led
25   11806    136142 2013/2014    Academy sponsor led
26   11806    136142 2014/2015    Academy sponsor led
27   11806    136142 2015/2016    Academy sponsor led
28   11806    136142 2016/2017    Academy sponsor led
29   11806    136142 2017/2018    Academy sponsor led
30   11806    136142 2018/2019    Academy sponsor led
⋮    ⋮        ⋮      ⋮            ⋮
3195 14641    139961 2018/2019    Academy sponsor led
3196 14641    139961 2019/2020    Academy sponsor led
3197 14641    139961 2020/2021    Academy sponsor led
3198 14641    139961 2021/2022    Academy sponsor led
3199  2535    103520 2005/2006    Community school
3200  2535    103520 2006/2007    Community school
3201  2535    103520 2007/2008    Community school
3202  2535    103520 2008/2009    Community school
3203  2535    103520 2009/2010    Community school
3204  2535    103520 2010/2011    Community school
3205  2535    103520 2011/2012    Community school
3206  2535    103520 2012/2013    Community school
3207  2535    103520 2013/2014    Community school
3208  2535    103520 2014/2015    Community school
3209  2535    103520 2015/2016    Community school
3210  2535    103520 2016/2017    Community school
3211  2535    103520 2017/2018    Community school
3212  2535    103520 2018/2019    Community school
3213  2535    103520 2019/2020    Community school
3214  2535    103520 2020/2021    Community school
3215  2535    103520 2021/2022    Community school
3216 15193    139994 2013/2014    Academy converter
3217 15193    139994 2014/2015    Academy converter
3218 15193    139994 2015/2016    Academy converter
3219 15193    139994 2016/2017    Academy converter
3220 15193    139994 2017/2018    Academy converter
3221 15193    139994 2018/2019    Academy converter
3222 15193    139994 2019/2020    Academy converter
3223 15193    139994 2020/2021    Academy converter
3224 15193    139994 2021/2022    Academy converter
     SchoolName                           PhaseOfEducationDesc
1    Academy 360                          Not applicable
2    Academy 360                          Not applicable
3    Academy 360                          Not applicable
4    Academy 360                          Not applicable
5    Academy 360                          Not applicable
6    Academy 360                          Not applicable
7    Academy 360                          Secondary
8    Academy 360                          Not applicable
9    Academy 360                          Not applicable
10   Academy 360                          Not applicable
11   Academy 360                          Not applicable
12   Academy 360                          Not applicable
13   Academy 360                          Not applicable
14   Academy 360                          Not applicable
15   Academy 360                          Not applicable
16   Academy 360                          NA
17   Academy 360                          NA
18   Academy 360                          NA
19   Academy 360                          NA
20   Academy 360                          NA
21   All Saints Church of England Academy Not applicable
22   All Saints Church of England Academy Not applicable
23   All Saints Church of England Academy Secondary
24   All Saints Church of England Academy Secondary
25   All Saints Church of England Academy Secondary
26   All Saints Church of England Academy Secondary
27   All Saints Church of England Academy Secondary
28   All Saints Church of England Academy Secondary
29   All Saints Church of England Academy Secondary
30   All Saints Church of England Academy Secondary
⋮    ⋮                                    ⋮
3195 Wrenn School                         Secondary
3196 Wrenn School                         Secondary
3197 Wrenn School                         Secondary
3198 Wrenn School                         Secondary
3199 Yardleys School                      Secondary
3200 Yardleys School                      Secondary
3201 Yardleys School                      Secondary
3202 Yardleys School                      Secondary
3203 Yardleys School                      Secondary
3204 Yardleys School                      Secondary
3205 Yardleys School                      Secondary
3206 Yardleys School                      Secondary
3207 Yardleys School                      Secondary
3208 Yardleys School                      Secondary
3209 Yardleys School                      Secondary
3210 Yardleys School                      Secondary
3211 Yardleys School                      Secondary
3212 Yardleys School                      Secondary
3213 Yardleys School                      Secondary
3214 Yardleys School                      Secondary
3215 Yardleys School                      Secondary
3216 Yardleys School                      Secondary
3217 Yardleys School                      Secondary
3218 Yardleys School                      Secondary
3219 Yardleys School                      Secondary
3220 Yardleys School                      Secondary
3221 Yardleys School                      Secondary
3222 Yardleys School                      Secondary
3223 Yardleys School                      Secondary
3224 Yardleys School                      Secondary

#### Save school info to csv

In [68]:
write.csv(schools_filtered, "data/additional_schools_filtered.csv", row.names = FALSE)

#### Join matched schools data to enrolments table

In [69]:
enrol_final <- enrol_filtered |>
    left_join(schools_filtered, by = join_by(SchoolID, AcademicYear))

In [70]:
enrol_final |>
    arrange(person_id, AcademicYear)

      person_id                                                        SchoolID
1     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 12506
2     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 12506
3     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 12506
4     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 12506
5     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 12506
6     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 12433
7     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 12433
8     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 12433
9     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 12433
10    00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661 12433
11    000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909   125
12    000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909   125
13    000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909   125
14    000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909   125
15    000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909   125
16    00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC 12433
17    00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC 12433
18    00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC 12433
19    00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC 12433
20    00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC 12433
21    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D  1562
22    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D  1562
23    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D  1562
24    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D  1562
25    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D  1562
26    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D  1562
27    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D  1562
28    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D  1562
29    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D  1562
30    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D  1562
⋮     ⋮                                                                ⋮
93628 FFEBA2A7088A41ADEF06DE231C6F48B615D19A0CA2D2FC917F432A964C9B2EA3  2376
93629 FFEBA2A7088A41ADEF06DE231C6F48B615D19A0CA2D2FC917F432A964C9B2EA3  2376
93630 FFEBA2A7088A41ADEF06DE231C6F48B615D19A0CA2D2FC917F432A964C9B2EA3  2376
93631 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC 13096
93632 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC 13096
93633 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC 13096
93634 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC 12161
93635 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC 12161
93636 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC 12161
93637 FFEF385FC541F397C34ACF193D6936D6BB045655B8781D7CFF18D632AAE9ED10 11547
93638 FFEF385FC541F397C34ACF193D6936D6BB045655B8781D7CFF18D632AAE9ED10 11547
93639 FFEF385FC541F397C34ACF193D6936D6BB045655B8781D7CFF18D632AAE9ED10 11547
93640 FFEF385FC541F397C34ACF193D6936D6BB045655B8781D7CFF18D632AAE9ED10 11547
93641 FFEF385FC541F397C34ACF193D6936D6BB045655B8781D7CFF18D632AAE9ED10 11547
93642 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB  1519
93643 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB 14095
93644 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB 14095
93645 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB 14095
93646 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB 14095
93647 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008   847
93648 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008  2077
93649 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008   847
93650 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008  2077
93651 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008  2077
93652 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008  2077
93653 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA  2680
93654 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA  2680
93655 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA  2680
93656 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA  2680
93657 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA  2680
      AcademicYear OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate
1     2011/2012    1        1        1        C           2011-09-05
2     2012/2013    1        1        1        C           2011-09-05
3     2013/2014    1        1        1        C           2011-09-05
4     2014/2015    1        1        1        C           2011-09-05
5     2015/2016    1        1        1        C           2011-09-05
6     2010/2011    1        1        1        C           2010-09-01
7     2011/2012    1        1        1        C           2010-09-01
8     2012/2013    1        1        1        C           2010-09-01
9     2013/2014    1        1        1        C           2010-09-01
10    2014/2015    1        1        0        C           2010-09-01
11    2010/2011    1        1        1        C           2010-08-27
12    2011/2012    1        1        1        C           2010-08-27
13    2012/2013    1        1        1        C           2010-08-27
14    2013/2014    1        1        1        C           2010-08-27
15    2014/2015    1        1        1        C           2010-08-27
16    2011/2012    1        1        1        C           2011-09-01
17    2012/2013    1        1        1        C           2011-09-01
18    2013/2014    1        1        1        C           2011-09-01
19    2014/2015    1        1        1        C           2011-09-01
20    2015/2016    1        1        1        C           2011-09-01
21    2011/2012    1        1        1        C           2011-09-06
22    2011/2012    1        1        1        C           2011-09-06
23    2012/2013    1        1        1        C           2011-09-06
24    2012/2013    1        1        1        C           2011-09-06
25    2013/2014    1        1        1        C           2011-09-06
26    2013/2014    1        1        1        C           2011-09-06
27    2014/2015    1        1        1        C           2011-09-06
28    2014/2015    1        1        1        C           2011-09-06
29    2015/2016    1        1        0        C           2011-09-06
30    2015/2016    1        1        0        C           2011-09-06
⋮     ⋮            ⋮        ⋮        ⋮        ⋮           ⋮
93628 2012/2013    1        1        1        C           2010-09-01
93629 2013/2014    1        1        1        C           2010-09-01
93630 2014/2015    1        1        0        C           2010-09-01
93631 2011/2012    1        1        1        C           2011-09-05
93632 2012/2013    1        1        1        C           2011-09-05
93633 2013/2014    1        0        NA       C           2011-09-05
93634 2013/2014    NA       1        1        C           2014-03-25
93635 2014/2015    1        1        1        C           2014-03-25
93636 2015/2016    1        1        0        C           2014-03-25
93637 2010/2011    1        1        1        C           2010-09-01
93638 2011/2012    1        1        1        C           2010-09-01
93639 2012/2013    1        1        1        C           2010-09-01
93640 2013/2014    1        1        1        C           2010-09-01
93641 2014/2015    1        1        1        C           2010-09-01
93642 2011/2012    0        NA       NA       C           2011-09-06
93643 2012/2013    1        1        1        C           2013-01-07
93644 2013/2014    1        1        1        C           2013-01-07
93645 2014/2015    1        1        1        C           2013-01-07
93646 2015/2016    1        1        0        C           2013-01-07
93647 2011/2012    1        1        1        C           2011-09-06
93648 2012/2013    1        1        1        C           2012-11-06
93649 2012/2013    0        NA       NA       C           2011-09-06
93650 2013/2014    1        1        1        C           2012-11-06
93651 2014/2015    1        1        1        C           2012-11-06
93652 2015/2016    1        1        0        C           2012-11-06
93653 2010/2011    1        1        1        C           2010-09-01
93654 2011/2012    1        1        1        C           2010-09-01
93655 2012/2013    1        1        1        C           2010-09-01
93656 2013/2014    1        1        1        C           2010-09-01
93657 2014/2015    1        1        1        C           2010-09-01
      LeavingDate PartTime NCCIS_ACADYR URN    InstitutionTypeDesc
1     <NA>        0        2016/2017    136664 Academy converter
2     <NA>        0        2016/2017    136664 Academy converter
3     <NA>        0        2016/2017    136664 Academy converter
4     <NA>        0        2016/2017    136664 Academy converter
5     <NA>        0        2016/2017    136664 Academy converter
6     <NA>        0        2015/2016    136736 Academy converter
7     <NA>        0        2015/2016    136736 Academy converter
8     <NA>        0        2015/2016    136736 Academy converter
9     <NA>        0        2015/2016    136736 Academy converter
10    2015-08-31  0        2015/2016    136736 Academy converter
11    <NA>        0        2015/2016    130909 Academy sponsor led
12    <NA>        0        2015/2016    130909 Academy sponsor led
13    <NA>        0        2015/2016    130909 Academy sponsor led
14    <NA>        0        2015/2016    130909 Academy sponsor led
15    <NA>        0        2015/2016    130909 Academy sponsor led
16    <NA>        0        2016/2017    136736 Academy converter
17    <NA>        0        2016/2017    136736 Academy converter
18    <NA>        0        2016/2017    136736 Academy converter
19    <NA>        0        2016/2017    136736 Academy converter
20    <NA>        0        2016/2017    136736 Academy converter
21    <NA>        0        2016/2017    107440 Foundation school
22    <NA>        0        2016/2017    107440 Foundation school
23    <NA>        0        2016/2017    107440 Foundation school
24    <NA>        0        2016/2017    107440 Foundation school
25    <NA>        0        2016/2017    107440 Foundation school
26    <NA>        0        2016/2017    107440 Foundation school
27    <NA>        0        2016/2017    107440 Foundation school
28    <NA>        0        2016/2017    107440 Foundation school
29    2016-07-22  0        2016/2017    107440 Foundation school
30    2016-07-22  0        2016/2017    107440 Foundation school
⋮     ⋮           ⋮        ⋮            ⋮      ⋮
93628 <NA>        0        2015/2016    121714 Voluntary aided school
93629 <NA>        0        2015/2016    121714 Voluntary aided school
93630 2015-07-18  0        2015/2016    121714 Voluntary aided school
93631 <NA>        0        2016/2017    134993 Academy sponsor led
93632 <NA>        0        2016/2017    134993 Academy sponsor led
93633 2014-03-24  0        2016/2017    134993 Academy sponsor led
93634 <NA>        0        2016/2017    137444 Academy converter
93635 <NA>        0        2016/2017    137444 Academy converter
93636 2016-07-26  0        2016/2017    137444 Academy converter
93637 <NA>        0        2015/2016        NA NA
93638 <NA>        0        2015/2016    136788 Academy converter
93639 <NA>        0        2015/2016    136788 Academy converter
93640 <NA>        0        2015/2016    136788 Academy converter
93641 <NA>        0        2015/2016    136788 Academy converter
93642 2012-01-04  0        2016/2017    107397 Foundation school
93643 <NA>        0        2016/2017    139060 Academy sponsor led
93644 <NA>        0        2016/2017    139060 Academy sponsor led
93645 <NA>        0        2016/2017    139060 Academy sponsor led
93646 2016-06-27  0        2016/2017    139060 Academy sponsor led
93647 <NA>        0        2016/2017    107562 Community school
93648 <NA>        0        2016/2017    121690 Community school
93649 2012-10-19  0        2016/2017    107562 Community school
93650 <NA>        0        2016/2017    121690 Community school
93651 <NA>        0        2016/2017    121690 Community school
93652 2016-06-30  0        2016/2017    121690 Community school
93653 <NA>        0        2015/2016    107783 Voluntary aided school
93654 <NA>        0        2015/2016    107783 Voluntary aided school
93655 <NA>        0        2015/2016    107783 Voluntary aided school
93656 <NA>        0        2015/2016    107783 Voluntary aided school
93657 <NA>        0        2015/2016    107783 Voluntary aided school
      SchoolName                                      PhaseOfEducationDesc
1     Skipton Girls High School                       Secondary
2     Skipton Girls High School                       Secondary
3     Skipton Girls High School                       Secondary
4     Skipton Girls High School                       Secondary
5     Skipton Girls High School                       Secondary
6     South Craven School                             Secondary
7     South Craven School                             Secondary
8     South Craven School                             Secondary
9     South Craven School                             Secondary
10    South Craven School                             Secondary
11    Dixons City Academy                             Not applicable
12    Dixons City Academy                             Secondary
13    Dixons City Academy                             Secondary
14    Dixons City Academy                             Secondary
15    Dixons City Academy                             Secondary
16    South Craven School                             Secondary
17    South Craven School                             Secondary
18    South Craven School                             Secondary
19    South Craven School                             Secondary
20    South Craven School                             Secondary
21    Hanson School                                   Secondary
22    Hanson School                                   Secondary
23    Hanson School                                   Secondary
24    Hanson School                                   Secondary
25    Hanson School                                   Secondary
26    Hanson School                                   Secondary
27    Hanson School                                   Secondary
28    Hanson School                                   Secondary
29    Hanson School                                   Secondary
30    Hanson School                                   Secondary
⋮     ⋮                                               ⋮
93628 St Augustines Roman Catholic School Scarborough Secondary
93629 St Augustines Roman Catholic School Scarborough Secondary
93630 St Augustines Roman Catholic School Scarborough Secondary
93631 Sandwell Academy                                Secondary
93632 Sandwell Academy                                Secondary
93633 Sandwell Academy                                Secondary
93634 Rastrick High School                            Secondary
93635 Rastrick High School                            Secondary
93636 Rastrick High School                            Secondary
93637 NA                                              NA
93638 The North Halifax Grammar School                Secondary
93639 The North Halifax Grammar School                Secondary
93640 The North Halifax Grammar School                Secondary
93641 The North Halifax Grammar School                Secondary
93642 Aire Valley School                              Secondary
93643 Lodge Park Academy                              Secondary
93644 Lodge Park Academy                              Secondary
93645 Lodge Park Academy                              Secondary
93646 Lodge Park Academy                              Secondary
93647 The Calder Learning Trust                       Secondary
93648 Upper Wharfedale School                         Secondary
93649 The Calder Learning Trust                       Secondary
93650 Upper Wharfedale School                         Secondary
93651 Upper Wharfedale School                         Secondary
93652 Upper Wharfedale School                         Secondary
93653 St John Fisher Catholic High School             Secondary
93654 St John Fisher Catholic High School             Secondary
93655 St John Fisher Catholic High School             Secondary
93656 St John Fisher Catholic High School             Secondary
93657 St John Fisher Catholic High School             Secondary

#### check how many school moves in the data

In [71]:
id_lists <- enrol_final |>
    select(person_id, SchoolName)

In [72]:
#id_lists

In [73]:
# n = 85,423
head(id_lists)

  person_id
1 35DFCB5D8F021D95483FF24CE410460A7265CE97C3E6D703CA8DAC6E3E333C47
2 CD414F29155D31984D61A6AFE5652D361C00277FEEFB3794FEFF130EA28F0CBB
3 868641B54D3700FE1E77718923B99D3A71905DA252D53EB8494816557E111548
4 3AF775F1DC69FD59BD020B2884CC8265B0F28DD726A1CB98C8F0091B0E3BE67B
5 0BFA0D59291474ECFA993CECC8B3553CB312919D1F7107A5A04EA234F4D9AEF5
6 8E783AF3FBE68119322CB54C141558117F093036F6CCA94259A8B870A8A07F73
  SchoolName
1 Dixons City Academy
2 Dixons City Academy
3 Dixons City Academy
4 Dixons City Academy
5 Dixons City Academy
6 Dixons City Academy

In [74]:
distinct(id_lists)

      person_id
1     35DFCB5D8F021D95483FF24CE410460A7265CE97C3E6D703CA8DAC6E3E333C47
2     CD414F29155D31984D61A6AFE5652D361C00277FEEFB3794FEFF130EA28F0CBB
3     868641B54D3700FE1E77718923B99D3A71905DA252D53EB8494816557E111548
4     3AF775F1DC69FD59BD020B2884CC8265B0F28DD726A1CB98C8F0091B0E3BE67B
5     0BFA0D59291474ECFA993CECC8B3553CB312919D1F7107A5A04EA234F4D9AEF5
6     8E783AF3FBE68119322CB54C141558117F093036F6CCA94259A8B870A8A07F73
7     41174C3DD06AC89C1538607F536905DD039451D7609845A86B07DFDEC9942FE7
8     1DE429B6E3EFF9706C8619FED25B2946012BEB3801945340B5346526CBE0D0DB
9     84F3FA0E59882E7FE2760EE3707F05A31F3455C34F07E1506DA4023D0B1D493B
10    7278710FBAFB13588353C0EAC591FD6DD14A0D61A1F6820558D10D4476A081DD
11    8987C4A972EAB018C1ECFDC0165653DF7E5A54D24DC6FB85E9E0EADDD3710534
12    E6D7C01FDA16A1ADBF49C66F378992E88576A0C20CC1CBA7E57970C781183EAB
13    CEEF164B90193B44E1E95AB56B865B218638528B162EEB1DB14AE3EA17D684C3
14    728D7812536E3023AE813DB41B57DB9897B0E93E3D29215EF3B7F14437C5A2D8
15    BBF9AFFE2F248EB2F730B6C776D2B9F2522CB687859B8B77A7616B4DFCB34F5C
16    38E3C20FAF4276504F303293A4454C1AEBD784804D11883019C3579844B48B14
17    18A389D1F75E7B2386F8C5A379BF4BAE4365F2E8DB012326ABEEB85FE3E59F98
18    C246F5F66A100B752B9416B6316AF4C060B55B31CE04C581BD240193062DB74F
19    521C462BF62447AD74A6D1F8518C6FF882AC7F6CF6BA57932888D3935DFEF102
20    6BBC53FDFDAE67E4D3FC8D55BC1F3BACD4558D9A9C4D28908006D866C6291F71
21    46C9187C8DA042A7323E85C99B9ACA138457CF3D02729983F023D1E618D84794
22    2AD16E96796B1B798723F6341564018E3C387876DAB1752DE37879079FE0B2BD
23    E9E4354BDC21DD313ED2C3B2EC00FBF70FAAFD93D72BD23D55F49FED4AFE91AC
24    E00B6BA90C14CD4186B28FCF84E8593BDDA6EC3BD2BEE2339388AF681C6B3030
25    26BE69AD1B80EB09E252A0737B13997A44454EF39F59CD619FE548C00ACE8713
26    152D61CC4423914F37CE9725C94BB2C46A40980012E02A11DFB5D176FD05F32E
27    E0E5C364AD2851E1ABF96281279E3252ECE591EBBD3C01524D2232C3E0E84CF2
28    9D5A04274A948A08304867603C393398C720EC2437A97F99C2DEA8EB2F25A64E
29    A951C3895CDABA153326B700C8091EC71F57C6D321E9F5C05D2B0569C0F22091
30    A940FFC98AFE2D4914BBDB58CCDF4598059E31E03362B39DBCB56EB81F3A2C54
⋮     ⋮
24150 BE8A9405966665C0FFA7F80A0CD43C0E42E2288C2EBF9E52CB637FE8A94D18AA
24151 9B98DA305BE9B6AE71BEA23AFA75FD6E29BE708B610215942941EF8580F5B624
24152 3519420EF2B34A0C667CD7B3030EBCA06BCE1CCF5B5A7A6C2FC46A3FD3340EF9
24153 4E4E6979EC5CB9F848F7B8BB808C29AEF03AF15D697DD10B9DC7F1E32D739B62
24154 0787FAEE55B6E5E4B388C805AC84534AC9E872DD23109942CE309C1738249495
24155 A26554DEF31AA3A10B8122AE0EA027C5FF2A4614400655B51B1A3AF1A3964B3F
24156 2F44F4934AD1C029A80126CBCE262B7102B122B5EB393F2E00517570D4F07D77
24157 18C744CF0AA1F469987FFBE329B398D37C805781631C7758F7C5C274BD0B614B
24158 2340E39391FB75AF560256193463618547207A42DAA5DE04C20984ABE1DB97CE
24159 FACEF74F5ABA9330A1BD94C38CCE7F96339FFD7D53ACBD22828ED96D52BD9BA9
24160 DBDA6A7AE8266386A7CBF70E6939405F0D8571F6B47450FD1D7449E6EAD89B62
24161 864EBEBE6FDFC07B9E5392793EB6AF9F126B7255EE47D44F6E0A3AB02E3F6F67
24162 F05C743962D846DE75FA7024158D9CC5E079C1DF2C931D3A0BF9434BAD8BBD19
24163 10FDEBA3A0A210EE4977BED5DD4228B91E75ADD7B2BAA1EE6D0482B3F06BCED7
24164 873571F18E5692189BEF7E16939631DB9D23DAB1F0F7E3CD9A95794B3FA595CD
24165 8379D53403EB2548478F8C18912F4D85F46E5B0F534E050DDBCBD219FDFBCCBD
24166 3FB0C7C94BC3E09F601CF105C87540F1AB893E9A6CADC6417A815BE7E328659D
24167 CCBF2AF7BE42A58AD709E8F82B4CF5185831D7E65CE00548F2CB6DEF61BAE2E2
24168 3A0D8E1223FB1C2ADBCFC4C304DD448E339F5886957D689C6DDBC9FD780B17C0
24169 A68793970B9B897508912BA4D96B2B0091B35C8F03D05CE9307F580D4688B46B
24170 EF0B845CCC412C88620420D571E11DFFAF3653EA92114AE6E3FC6E5A35C857FD
24171 A44DA627681A4261D2CA9A069DA4C7FE618F39F026D58D04A59A7481D9BDA3D7
24172 6F5922CBB9C55F7D709226BBB2FE664579529EA4E65003124F1896B0DBE36BEF
24173 15277E6AA36699CC4DB4B36FBBB9BF0F7C95E7893DF69DBBA5752749BF620522
24174 F5F38DB96EC863841CC88122F709705A8CA4375B70B5BF8EEAE03DF31B0FA6DE
24175 15AB353BD2063E84809A22E649B1A465ED45B75E9EF33E9B8B4765E0553D7CA1
24176 CB0B3168CAE0CB3C4868BF297669A8A3BD0941E0E2E6B7568B8B6D713F694A4A
24177 F9EFD335B7F94E27BFFABED6581F9F3581DBDC7633993056952DBF5B71CAEA32
24178 ABC1392EA0AAE0260046C3C32F4667406147CA9BD6249502DCD6B962A71B2C1B
24179 6837E6F6A1943957A749DF8E25B80AA6529B05185209DADF42166640C7F12F6C
      SchoolName
1     Dixons City Academy
2     Dixons City Academy
3     Dixons City Academy
4     Dixons City Academy
5     Dixons City Academy
6     Dixons City Academy
7     Dixons City Academy
8     Dixons City Academy
9     Dixons City Academy
10    Dixons City Academy
11    Dixons City Academy
12    Dixons City Academy
13    Dixons City Academy
14    Dixons City Academy
15    Dixons City Academy
16    Dixons City Academy
17    Dixons City Academy
18    Dixons City Academy
19    Dixons City Academy
20    Dixons City Academy
21    Dixons City Academy
22    Dixons City Academy
23    Dixons City Academy
24    Dixons City Academy
25    Dixons City Academy
26    Dixons City Academy
27    Dixons City Academy
28    Dixons City Academy
29    St John Fisher Catholic High School
30    Bradford Academy
⋮     ⋮
24150 Fulwood Academy
24151 West End Middle School
24152 Appleton Academy
24153 Bispham High School  An Arts College
24154 Rochdale Pupil Referral Service
24155 Bradford District PRU
24156 St Bedes and St Josephs Catholic College
24157 St Bedes and St Josephs Catholic College
24158 St Bedes and St Josephs Catholic College
24159 St Bedes and St Josephs Catholic College
24160 St Bedes and St Josephs Catholic College
24161 St Bedes and St Josephs Catholic College
24162 St Bedes and St Josephs Catholic College
24163 St Bedes and St Josephs Catholic College
24164 St Bedes and St Josephs Catholic College
24165 St Bedes and St Josephs Catholic College
24166 Hanson School
24167 Westbourne Academy
24168 Northampton Academy
24169 The Brooksbank School
24170 Appleton Academy
24171 Buttershaw Business and Enterprise College
24172 Grange Technology College
24173 The Samuel Lister Academy
24174 Bradford Central PRU
24175 The Challenge College
24176 Denholme Primary School
24177 University Academy Keighley
24178 Fearnville Primary School
24179 Laisterdyke Business and Enterprise College

In [486]:
# n = 24,688
id_lists_distinct <- distinct(id_lists)

In [487]:
person_counts <- table(id_lists_distinct$person_id)
summary <- table(person_counts)

In [488]:
as.data.frame(summary)

  person_counts Freq
1 1             10792
2 2              5050
3 3               808
4 4               219
5 5                70
6 6                18
7 7                 2
8 8                 3

#### Explore high school count ids

In [489]:
enrol_final |> 
    filter(person_id == '38C38B72800AB59D24A9677F19DB0C3872F37209D24BC03DA9F68E7543CF333F') |>
    arrange(AcademicYear, EntryDate)

  person_id                                                        SchoolID
1 38C38B72800AB59D24A9677F19DB0C3872F37209D24BC03DA9F68E7543CF333F  1562
2 38C38B72800AB59D24A9677F19DB0C3872F37209D24BC03DA9F68E7543CF333F  1562
3 38C38B72800AB59D24A9677F19DB0C3872F37209D24BC03DA9F68E7543CF333F 15223
4 38C38B72800AB59D24A9677F19DB0C3872F37209D24BC03DA9F68E7543CF333F   344
5 38C38B72800AB59D24A9677F19DB0C3872F37209D24BC03DA9F68E7543CF333F   344
6 38C38B72800AB59D24A9677F19DB0C3872F37209D24BC03DA9F68E7543CF333F 14447
7 38C38B72800AB59D24A9677F19DB0C3872F37209D24BC03DA9F68E7543CF333F 14447
8 38C38B72800AB59D24A9677F19DB0C3872F37209D24BC03DA9F68E7543CF333F 14447
  AcademicYear OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate  LeavingDate
1 2012/2013    1        1        1        C           2012-09-03 <NA>
2 2013/2014    1        0        0        C           2012-09-03 2014-04-03
3 2013/2014    0        NA       NA       NA          2013-09-24 2013-12-13
4 2013/2014    NA       1        1        C           2014-04-04 <NA>
5 2014/2015    1        0        0        M           2014-04-04 2015-02-23
6 2014/2015    0        NA       NA       S           2014-10-02 2014-11-14
7 2015/2016    1        1        1        C           2014-10-02 <NA>
8 2016/2017    1        1        0        C           2014-10-02 2017-06-30
  PartTime NCCIS_ACADYR URN    InstitutionTypeDesc SchoolName
1 0        2017/2018    107440 Foundation school   Hanson School
2 0        2017/2018    107440 Foundation school   Hanson School
3 0        2017/2018    133411 AP/PRU              Bradford Central PRU
4 0        2017/2018    107563 Community school    Sowerby Bridge High School
5 0        2017/2018    107563 Community school    Sowerby Bridge High School
6 0        2017/2018    133693 AP/PRU              Calderdale PRU
7 0        2017/2018    133693 AP/PRU              Calderdale PRU
8 0        2017/2018    133693 AP/PRU              Calderdale PRU
  PhaseOfEducationDesc
1 Secondary
2 Secondary
3 Not applicable
4 Secondary
5 Secondary
6 Not applicable
7 Not applicable
8 Not applicable

#### create a table of person_id and school count

In [490]:
# create a new col with count to match with destinations
school_count <- id_lists_distinct %>%
  group_by(person_id) %>%
  mutate(n_schools = n()) %>%
  ungroup()

In [491]:
head(school_count)

  person_id
1 F65B08C0ABA0DF84D9BD65F7FED88E1D5DAD42AAB47392CE2D9543AED4E245DD
2 F97D233CF64E3EAC93369EAAA28D9E5193785F4BA369A53A716A1B453B9FDDA2
3 3E4432F9D7005D74AB24D68A875EC38A8DA0234A2D67666F935999C059682696
4 823AECF1EFC7F8CD963B2B16D2C886922CD9F7C0CA4B478BD07E86F163685822
5 18746FF26D6AC95D757A4B4CB10B01DE6F041115B43ECC8BE0C4A0AEF575224B
6 0D5BABE74A35CC1F64DB2C1F97898AD55B2DF12975FE992FE28487B958392B33
  SchoolName            n_schools
1 South Craven School   2
2 Appleton Academy      3
3 Gloucester Academy    2
4 Endeavour High School 2
5 Coop Academy Leeds    1
6 Appleton Academy      2

# Pivot Long for terms then Pivot Wide for years

In [75]:
head(enrol_final)

  person_id                                                        SchoolID
1 35DFCB5D8F021D95483FF24CE410460A7265CE97C3E6D703CA8DAC6E3E333C47 125
2 CD414F29155D31984D61A6AFE5652D361C00277FEEFB3794FEFF130EA28F0CBB 125
3 868641B54D3700FE1E77718923B99D3A71905DA252D53EB8494816557E111548 125
4 3AF775F1DC69FD59BD020B2884CC8265B0F28DD726A1CB98C8F0091B0E3BE67B 125
5 0BFA0D59291474ECFA993CECC8B3553CB312919D1F7107A5A04EA234F4D9AEF5 125
6 8E783AF3FBE68119322CB54C141558117F093036F6CCA94259A8B870A8A07F73 125
  AcademicYear OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate  LeavingDate
1 2010/2011    1        1        1        C           2010-08-27 <NA>
2 2010/2011    1        1        1        C           2010-08-27 <NA>
3 2010/2011    1        1        1        C           2010-08-27 <NA>
4 2010/2011    1        1        1        C           2010-08-27 <NA>
5 2010/2011    1        1        1        C           2010-08-27 <NA>
6 2010/2011    1        1        1        C           2010-08-27 <NA>
  PartTime NCCIS_ACADYR URN    InstitutionTypeDesc SchoolName
1 0        2015/2016    130909 Academy sponsor led Dixons City Academy
2 0        2015/2016    130909 Academy sponsor led Dixons City Academy
3 0        2015/2016    130909 Academy sponsor led Dixons City Academy
4 0        2015/2016    130909 Academy sponsor led Dixons City Academy
5 0        2015/2016    130909 Academy sponsor led Dixons City Academy
6 0        2015/2016    130909 Academy sponsor led Dixons City Academy
  PhaseOfEducationDesc
1 Not applicable
2 Not applicable
3 Not applicable
4 Not applicable
5 Not applicable
6 Not applicable

In [76]:
school_per_term <- enrol_final |>
    select(-c(SchoolID, PartTime, SchoolName, InstitutionTypeDesc, PhaseOfEducationDesc))

In [77]:
head(school_per_term)

  person_id                                                        AcademicYear
1 35DFCB5D8F021D95483FF24CE410460A7265CE97C3E6D703CA8DAC6E3E333C47 2010/2011
2 CD414F29155D31984D61A6AFE5652D361C00277FEEFB3794FEFF130EA28F0CBB 2010/2011
3 868641B54D3700FE1E77718923B99D3A71905DA252D53EB8494816557E111548 2010/2011
4 3AF775F1DC69FD59BD020B2884CC8265B0F28DD726A1CB98C8F0091B0E3BE67B 2010/2011
5 0BFA0D59291474ECFA993CECC8B3553CB312919D1F7107A5A04EA234F4D9AEF5 2010/2011
6 8E783AF3FBE68119322CB54C141558117F093036F6CCA94259A8B870A8A07F73 2010/2011
  OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate  LeavingDate NCCIS_ACADYR
1 1        1        1        C           2010-08-27 <NA>        2015/2016
2 1        1        1        C           2010-08-27 <NA>        2015/2016
3 1        1        1        C           2010-08-27 <NA>        2015/2016
4 1        1        1        C           2010-08-27 <NA>        2015/2016
5 1        1        1        C           2010-08-27 <NA>        2015/2016
6 1        1        1        C           2010-08-27 <NA>        2015/2016
  URN
1 130909
2 130909
3 130909
4 130909
5 130909
6 130909

C = Current (single registration at this school)
G = Guest (pupil not registered at this school but attending some lessons or sessions)
M = Current Main (dual registration)
S = Current Subsidiary (dual registration)
F = FE College (since 2014/15)
O = Other provider (since 2014/15)

In [78]:
school_per_term |> distinct(EnrolStatus) |> pull(EnrolStatus)

[1] "C" NA  "S" "M" "O" "F"

In [496]:
school_per_term |> 
    filter(person_id == '56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB' ) |>
    arrange(AcademicYear, EntryDate)

  person_id                                                        AcademicYear
1 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB 2012/2013
2 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB 2012/2013
3 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB 2013/2014
4 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB 2014/2015
5 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB 2014/2015
6 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB 2014/2015
7 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB 2015/2016
8 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB 2015/2016
9 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB 2016/2017
  OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate  LeavingDate NCCIS_ACADYR
1 0        NA       NA       C           2012-09-03 2012-10-05  2017/2018
2 1        1        1        C           2012-10-04 <NA>        2017/2018
3 1        1        1        C           2012-10-04 <NA>        2017/2018
4 1        1        1        M           2012-10-04 <NA>        2017/2018
5 0        NA       NA       S           2014-09-26 2014-11-27  2017/2018
6 1        0        NA       C           2014-12-10 2015-02-13  2017/2018
7 0        NA       NA       M           2012-10-04 2015-11-06  2017/2018
8 1        1        1        O           2015-11-09 <NA>        2017/2018
9 1        1        0        C           2015-11-09 2017-06-30  2017/2018
  URN
1 107366
2 135367
3 135367
4 135367
5 107350
6 133411
7 135367
8 135732
9 135732

In [497]:
enrol_final |> 
    filter(person_id == '56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB' ) |>
    arrange(AcademicYear, EntryDate)

  person_id                                                        SchoolID
1 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB  1716
2 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB  9574
3 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB  9574
4 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB  9574
5 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB  1340
6 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB 15223
7 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB  9574
8 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB 15167
9 56F243860E60E36A69DA5A81850F00AF5B84D5F9B60B6B23DA21828857B53AFB 15167
  AcademicYear OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate  LeavingDate
1 2012/2013    0        NA       NA       C           2012-09-03 2012-10-05
2 2012/2013    1        1        1        C           2012-10-04 <NA>
3 2013/2014    1        1        1        C           2012-10-04 <NA>
4 2014/2015    1        1        1        M           2012-10-04 <NA>
5 2014/2015    0        NA       NA       S           2014-09-26 2014-11-27
6 2014/2015    1        0        NA       C           2014-12-10 2015-02-13
7 2015/2016    0        NA       NA       M           2012-10-04 2015-11-06
8 2015/2016    1        1        1        O           2015-11-09 <NA>
9 2016/2017    1        1        0        C           2015-11-09 2017-06-30
  PartTime NCCIS_ACADYR URN    InstitutionTypeDesc
1 0        2017/2018    107366 Foundation school
2 0        2017/2018    135367 Academy sponsor led
3 0        2017/2018    135367 Academy sponsor led
4 0        2017/2018    135367 Academy sponsor led
5 0        2017/2018    107350 Foundation school
6 0        2017/2018    133411 AP/PRU
7 0        2017/2018    135367 Academy sponsor led
8 0        2017/2018    135732 AP/PRU
9 0        2017/2018    135732 AP/PRU
  SchoolName                                 PhaseOfEducationDesc
1 Tong High School                           Secondary
2 Bradford Academy                           Not applicable
3 Bradford Academy                           Secondary
4 Bradford Academy                           Not applicable
5 Buttershaw Business and Enterprise College Secondary
6 Bradford Central PRU                       Not applicable
7 Bradford Academy                           Not applicable
8 Bradford District PRU                      Not applicable
9 Bradford District PRU                      Not applicable

#### pivot long

In [79]:
pivot_long <- school_per_term %>%
  pivot_longer(
    cols = starts_with("OnRoll_"),            
    names_to = "Term",                        # new column name for term
    values_to = "OnRoll",                     # values (0, 1, or NA)
    names_prefix = "OnRoll_"                  # remove this prefix from 'Term'
  )

In [80]:
pivot_long |>
    arrange(person_id, AcademicYear, Term)

       person_id
1      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
2      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
3      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
4      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
5      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
6      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
7      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
8      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
9      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
10     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
11     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
12     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
13     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
14     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
15     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
16     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
17     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
18     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
19     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
20     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
21     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
22     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
23     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
24     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
25     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
26     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
27     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
28     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
29     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
30     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
⋮      ⋮
280942 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
280943 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
280944 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
280945 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
280946 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
280947 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
280948 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
280949 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
280950 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
280951 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
280952 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
280953 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
280954 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
280955 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
280956 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
280957 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
280958 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
280959 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
280960 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
280961 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
280962 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
280963 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
280964 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
280965 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
280966 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
280967 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
280968 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
280969 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
280970 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
280971 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
       AcademicYear EnrolStatus EntryDate  LeavingDate NCCIS_ACADYR URN    Term
1      2011/2012    C           2011-09-05 <NA>        2016/2017    136664 1
2      2011/2012    C           2011-09-05 <NA>        2016/2017    136664 2
3      2011/2012    C           2011-09-05 <NA>        2016/2017    136664 3
4      2012/2013    C           2011-09-05 <NA>        2016/2017    136664 1
5      2012/2013    C           2011-09-05 <NA>        2016/2017    136664 2
6      2012/2013    C           2011-09-05 <NA>        2016/2017    136664 3
7      2013/2014    C           2011-09-05 <NA>        2016/2017    136664 1
8      2013/2014    C           2011-09-05 <NA>        2016/2017    136664 2
9      2013/2014    C           2011-09-05 <NA>        2016/2017    136664 3
10     2014/2015    C           2011-09-05 <NA>        2016/2017    136664 1
11     2014/2015    C           2011-09-05 <NA>        2016/2017    136664 2
12     2014/2015    C           2011-09-05 <NA>        2016/2017    136664 3
13     2015/2016    C           2011-09-05 <NA>        2016/2017    136664 1
14     2015/2016    C           2011-09-05 <NA>        2016/2017    136664 2
15     2015/2016    C           2011-09-05 <NA>        2016/2017    136664 3
16     2010/2011    C           2010-09-01 <NA>        2015/2016    136736 1
17     2010/2011    C           2010-09-01 <NA>        2015/2016    136736 2
18     2010/2011    C           2010-09-01 <NA>        2015/2016    136736 3
19     2011/2012    C           2010-09-01 <NA>        2015/2016    136736 1
20     2011/2012    C           2010-09-01 <NA>        2015/2016    136736 2
21     2011/2012    C           2010-09-01 <NA>        2015/2016    136736 3
22     2012/2013    C           2010-09-01 <NA>        2015/2016    136736 1
23     2012/2013    C           2010-09-01 <NA>        2015/2016    136736 2
24     2012/2013    C           2010-09-01 <NA>        2015/2016    136736 3
25     2013/2014    C           2010-09-01 <NA>        2015/2016    136736 1
26     2013/2014    C           2010-09-01 <NA>        2015/2016    136736 2
27     2013/2014    C           2010-09-01 <NA>        2015/2016    136736 3
28     2014/2015    C           2010-09-01 2015-08-31  2015/2016    136736 1
29     2014/2015    C           2010-09-01 2015-08-31  2015/2016    136736 2
30     2014/2015    C           2010-09-01 2015-08-31  2015/2016    136736 3
⋮      ⋮            ⋮           ⋮          ⋮           ⋮            ⋮      ⋮
280942 2012/2013    C           2012-11-06 <NA>        2016/2017    121690 1
280943 2012/2013    C           2011-09-06 2012-10-19  2016/2017    107562 1
280944 2012/2013    C           2012-11-06 <NA>        2016/2017    121690 2
280945 2012/2013    C           2011-09-06 2012-10-19  2016/2017    107562 2
280946 2012/2013    C           2012-11-06 <NA>        2016/2017    121690 3
280947 2012/2013    C           2011-09-06 2012-10-19  2016/2017    107562 3
280948 2013/2014    C           2012-11-06 <NA>        2016/2017    121690 1
280949 2013/2014    C           2012-11-06 <NA>        2016/2017    121690 2
280950 2013/2014    C           2012-11-06 <NA>        2016/2017    121690 3
280951 2014/2015    C           2012-11-06 <NA>        2016/2017    121690 1
280952 2014/2015    C           2012-11-06 <NA>        2016/2017    121690 2
280953 2014/2015    C           2012-11-06 <NA>        2016/2017    121690 3
280954 2015/2016    C           2012-11-06 2016-06-30  2016/2017    121690 1
280955 2015/2016    C           2012-11-06 2016-06-30  2016/2017    121690 2
280956 2015/2016    C           2012-11-06 2016-06-30  2016/2017    121690 3
280957 2010/2011    C           2010-09-01 <NA>        2015/2016    107783 1
280958 2010/2011    C           2010-09-01 <NA>        2015/2016    107783 2
280959 2010/2011    C           2010-09-01 <NA>        2015/2016    107783 3
280960 2011/2012    C           2010-09-01 <NA>        2015/2016    107783 1
280961 2011/2012    C           2010-09-01 <NA>        2015/2016    107783 2
280962 2011/2012    C           2010-09-01 <NA>        2015/2016    107783 3
280963 2012/2013    C           2010-09-01 <NA>        2015/2016    107783 1
280964 2012/2013    C           2010-09-01 <NA>        2015/2016    107783 2
280965 2012/2013    C           2010-09-01 <NA>        2015/2016    107783 3
280966 2013/2014    C           2010-09-01 <NA>        2015/2016    107783 1
280967 2013/2014    C           2010-09-01 <NA>        2015/2016    107783 2
280968 2013/2014    C           2010-09-01 <NA>        2015/2016    107783 3
280969 2014/2015    C           2010-09-01 <NA>        2015/2016    107783 1
280970 2014/2015    C           2010-09-01 <NA>        2015/2016    107783 2
280971 2014/2015    C           2010-09-01 <NA>        2015/2016    107783 3
       OnRoll
1      1
2      1
3      1
4      1
5      1
6      1
7      1
8      1
9      1
10     1
11     1
12     1
13     1
14     1
15     1
16     1
17     1
18     1
19     1
20     1
21     1
22     1
23     1
24     1
25     1
26     1
27     1
28     1
29     1
30     0
⋮      ⋮
280942 1
280943 0
280944 1
280945 NA
280946 1
280947 NA
280948 1
280949 1
280950 1
280951 1
280952 1
280953 1
280954 1
280955 1
280956 0
280957 1
280958 1
280959 1
280960 1
280961 1
280962 1
280963 1
280964 1
280965 1
280966 1
280967 1
280968 1
280969 1
280970 1
280971 1

In [81]:
pivot_long |>
  group_by(person_id, AcademicYear, Term) |>
  filter(n() > 1) |>
  arrange(person_id, AcademicYear, Term)

      person_id
1     0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
2     0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
3     0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
4     0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
5     0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
6     0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
7     0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
8     0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
9     0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
10    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
11    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
12    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
13    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
14    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
15    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
16    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
17    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
18    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
19    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
20    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
21    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
22    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
23    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
24    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
25    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
26    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
27    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
28    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
29    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
30    0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
⋮     ⋮
54373 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
54374 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
54375 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
54376 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
54377 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
54378 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
54379 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
54380 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
54381 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
54382 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
54383 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
54384 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
54385 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
54386 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
54387 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
54388 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
54389 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
54390 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
54391 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
54392 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
54393 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
54394 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
54395 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
54396 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
54397 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
54398 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
54399 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
54400 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
54401 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
54402 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
      AcademicYear EnrolStatus EntryDate  LeavingDate NCCIS_ACADYR URN    Term
1     2011/2012    C           2011-09-06 <NA>        2016/2017    107440 1
2     2011/2012    C           2011-09-06 <NA>        2016/2017    107440 1
3     2011/2012    C           2011-09-06 <NA>        2016/2017    107440 2
4     2011/2012    C           2011-09-06 <NA>        2016/2017    107440 2
5     2011/2012    C           2011-09-06 <NA>        2016/2017    107440 3
6     2011/2012    C           2011-09-06 <NA>        2016/2017    107440 3
7     2012/2013    C           2011-09-06 <NA>        2016/2017    107440 1
8     2012/2013    C           2011-09-06 <NA>        2016/2017    107440 1
9     2012/2013    C           2011-09-06 <NA>        2016/2017    107440 2
10    2012/2013    C           2011-09-06 <NA>        2016/2017    107440 2
11    2012/2013    C           2011-09-06 <NA>        2016/2017    107440 3
12    2012/2013    C           2011-09-06 <NA>        2016/2017    107440 3
13    2013/2014    C           2011-09-06 <NA>        2016/2017    107440 1
14    2013/2014    C           2011-09-06 <NA>        2016/2017    107440 1
15    2013/2014    C           2011-09-06 <NA>        2016/2017    107440 2
16    2013/2014    C           2011-09-06 <NA>        2016/2017    107440 2
17    2013/2014    C           2011-09-06 <NA>        2016/2017    107440 3
18    2013/2014    C           2011-09-06 <NA>        2016/2017    107440 3
19    2014/2015    C           2011-09-06 <NA>        2016/2017    107440 1
20    2014/2015    C           2011-09-06 <NA>        2016/2017    107440 1
21    2014/2015    C           2011-09-06 <NA>        2016/2017    107440 2
22    2014/2015    C           2011-09-06 <NA>        2016/2017    107440 2
23    2014/2015    C           2011-09-06 <NA>        2016/2017    107440 3
24    2014/2015    C           2011-09-06 <NA>        2016/2017    107440 3
25    2015/2016    C           2011-09-06 2016-07-22  2016/2017    107440 1
26    2015/2016    C           2011-09-06 2016-07-22  2016/2017    107440 1
27    2015/2016    C           2011-09-06 2016-07-22  2016/2017    107440 2
28    2015/2016    C           2011-09-06 2016-07-22  2016/2017    107440 2
29    2015/2016    C           2011-09-06 2016-07-22  2016/2017    107440 3
30    2015/2016    C           2011-09-06 2016-07-22  2016/2017    107440 3
⋮     ⋮            ⋮           ⋮          ⋮           ⋮            ⋮      ⋮
54373 2013/2014    C           2011-09-06 <NA>        2016/2017    108097 1
54374 2013/2014    C           2011-09-06 <NA>        2016/2017    108097 1
54375 2013/2014    C           2011-09-06 <NA>        2016/2017    108097 2
54376 2013/2014    C           2011-09-06 <NA>        2016/2017    108097 2
54377 2013/2014    C           2011-09-06 <NA>        2016/2017    108097 3
54378 2013/2014    C           2011-09-06 <NA>        2016/2017    108097 3
54379 2014/2015    C           2011-09-06 <NA>        2016/2017    108097 1
54380 2014/2015    C           2011-09-06 <NA>        2016/2017    108097 1
54381 2014/2015    C           2011-09-06 <NA>        2016/2017    108097 2
54382 2014/2015    C           2011-09-06 <NA>        2016/2017    108097 2
54383 2014/2015    C           2011-09-06 <NA>        2016/2017    108097 3
54384 2014/2015    C           2011-09-06 <NA>        2016/2017    108097 3
54385 2015/2016    C           2011-09-06 2016-06-30  2016/2017    108097 1
54386 2015/2016    C           2011-09-06 2016-06-30  2016/2017    108097 1
54387 2015/2016    C           2011-09-06 2016-06-30  2016/2017    108097 2
54388 2015/2016    C           2011-09-06 2016-06-30  2016/2017    108097 2
54389 2015/2016    C           2011-09-06 2016-06-30  2016/2017    108097 3
54390 2015/2016    C           2011-09-06 2016-06-30  2016/2017    108097 3
54391 2013/2014    C           2011-09-05 2014-03-24  2016/2017    134993 1
54392 2013/2014    C           2014-03-25 <NA>        2016/2017    137444 1
54393 2013/2014    C           2011-09-05 2014-03-24  2016/2017    134993 2
54394 2013/2014    C           2014-03-25 <NA>        2016/2017    137444 2
54395 2013/2014    C           2011-09-05 2014-03-24  2016/2017    134993 3
54396 2013/2014    C           2014-03-25 <NA>        2016/2017    137444 3
54397 2012/2013    C           2012-11-06 <NA>        2016/2017    121690 1
54398 2012/2013    C           2011-09-06 2012-10-19  2016/2017    107562 1
54399 2012/2013    C           2012-11-06 <NA>        2016/2017    121690 2
54400 2012/2013    C           2011-09-06 2012-10-19  2016/2017    107562 2
54401 2012/2013    C           2012-11-06 <NA>        2016/2017    121690 3
54402 2012/2013    C           2011-09-06 2012-10-19  2016/2017    107562 3
      OnRoll
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    1
28    1
29    0
30    0
⋮     ⋮
54373 1
54374 1
54375 1
54376 1
54377 1
54378 1
54379 1
54380 1
54381 1
54382 1
54383 1
54384 1
54385 1
54386 1
54387 1
54388 1
54389 0
54390 0
54391 1
54392 NA
54393 0
54394 1
54395 NA
54396 1
54397 1
54398 0
54399 1
54400 NA
54401 1
54402 NA

In [82]:
pivot_long_clean <- pivot_long |>
    group_by(person_id, AcademicYear, Term) |>
    filter(n() > 1) |>
    mutate(
        # prioritise the record with onroll == T
        onroll_priority = ifelse(OnRoll == "1", 1, 0),
        # prioritise the record with C enrolment, then M enrolment status
        enrol_priority = case_when(
          EnrolStatus == "C" ~ 3,
          EnrolStatus == "M" ~ 2,
          TRUE ~ 1
            ),
        # combine
        priority_score = onroll_priority * 10 + enrol_priority
      ) |>
    # keep single highest priority record
    arrange(desc(priority_score)) |>
    slice_head(n = 1) |>
    ungroup()

In [83]:
non_duplicates <- pivot_long |>
  group_by(person_id, AcademicYear, Term) |>
  filter(n() == 1) |>
  ungroup()

In [88]:
pivot_long_clean <- bind_rows(pivot_long_clean, non_duplicates) |>
  arrange(person_id, AcademicYear, Term) |>
    distinct()

In [85]:
# n = 246807

In [89]:
pivot_long_clean |>
  #group_by(person_id, AcademicYear, Term) |>
  #filter(n() > 1) |>
  arrange(person_id, AcademicYear, Term)

       person_id
1      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
2      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
3      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
4      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
5      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
6      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
7      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
8      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
9      0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
10     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
11     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
12     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
13     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
14     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
15     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
16     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
17     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
18     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
19     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
20     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
21     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
22     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
23     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
24     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
25     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
26     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
27     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
28     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
29     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
30     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
⋮      ⋮
249961 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
249962 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
249963 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
249964 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
249965 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
249966 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
249967 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
249968 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
249969 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
249970 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
249971 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
249972 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
249973 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
249974 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
249975 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
249976 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
249977 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
249978 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
249979 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
249980 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
249981 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
249982 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
249983 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
249984 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
249985 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
249986 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
249987 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
249988 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
249989 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
249990 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
       AcademicYear EnrolStatus EntryDate  LeavingDate NCCIS_ACADYR URN    Term
1      2011/2012    C           2011-09-05 <NA>        2016/2017    136664 1
2      2011/2012    C           2011-09-05 <NA>        2016/2017    136664 2
3      2011/2012    C           2011-09-05 <NA>        2016/2017    136664 3
4      2012/2013    C           2011-09-05 <NA>        2016/2017    136664 1
5      2012/2013    C           2011-09-05 <NA>        2016/2017    136664 2
6      2012/2013    C           2011-09-05 <NA>        2016/2017    136664 3
7      2013/2014    C           2011-09-05 <NA>        2016/2017    136664 1
8      2013/2014    C           2011-09-05 <NA>        2016/2017    136664 2
9      2013/2014    C           2011-09-05 <NA>        2016/2017    136664 3
10     2014/2015    C           2011-09-05 <NA>        2016/2017    136664 1
11     2014/2015    C           2011-09-05 <NA>        2016/2017    136664 2
12     2014/2015    C           2011-09-05 <NA>        2016/2017    136664 3
13     2015/2016    C           2011-09-05 <NA>        2016/2017    136664 1
14     2015/2016    C           2011-09-05 <NA>        2016/2017    136664 2
15     2015/2016    C           2011-09-05 <NA>        2016/2017    136664 3
16     2010/2011    C           2010-09-01 <NA>        2015/2016    136736 1
17     2010/2011    C           2010-09-01 <NA>        2015/2016    136736 2
18     2010/2011    C           2010-09-01 <NA>        2015/2016    136736 3
19     2011/2012    C           2010-09-01 <NA>        2015/2016    136736 1
20     2011/2012    C           2010-09-01 <NA>        2015/2016    136736 2
21     2011/2012    C           2010-09-01 <NA>        2015/2016    136736 3
22     2012/2013    C           2010-09-01 <NA>        2015/2016    136736 1
23     2012/2013    C           2010-09-01 <NA>        2015/2016    136736 2
24     2012/2013    C           2010-09-01 <NA>        2015/2016    136736 3
25     2013/2014    C           2010-09-01 <NA>        2015/2016    136736 1
26     2013/2014    C           2010-09-01 <NA>        2015/2016    136736 2
27     2013/2014    C           2010-09-01 <NA>        2015/2016    136736 3
28     2014/2015    C           2010-09-01 2015-08-31  2015/2016    136736 1
29     2014/2015    C           2010-09-01 2015-08-31  2015/2016    136736 2
30     2014/2015    C           2010-09-01 2015-08-31  2015/2016    136736 3
⋮      ⋮            ⋮           ⋮          ⋮           ⋮            ⋮      ⋮
249961 2011/2012    C           2011-09-06 <NA>        2016/2017    107562 1
249962 2011/2012    C           2011-09-06 <NA>        2016/2017    107562 2
249963 2011/2012    C           2011-09-06 <NA>        2016/2017    107562 3
249964 2012/2013    C           2012-11-06 <NA>        2016/2017    121690 1
249965 2012/2013    C           2012-11-06 <NA>        2016/2017    121690 2
249966 2012/2013    C           2012-11-06 <NA>        2016/2017    121690 3
249967 2013/2014    C           2012-11-06 <NA>        2016/2017    121690 1
249968 2013/2014    C           2012-11-06 <NA>        2016/2017    121690 2
249969 2013/2014    C           2012-11-06 <NA>        2016/2017    121690 3
249970 2014/2015    C           2012-11-06 <NA>        2016/2017    121690 1
249971 2014/2015    C           2012-11-06 <NA>        2016/2017    121690 2
249972 2014/2015    C           2012-11-06 <NA>        2016/2017    121690 3
249973 2015/2016    C           2012-11-06 2016-06-30  2016/2017    121690 1
249974 2015/2016    C           2012-11-06 2016-06-30  2016/2017    121690 2
249975 2015/2016    C           2012-11-06 2016-06-30  2016/2017    121690 3
249976 2010/2011    C           2010-09-01 <NA>        2015/2016    107783 1
249977 2010/2011    C           2010-09-01 <NA>        2015/2016    107783 2
249978 2010/2011    C           2010-09-01 <NA>        2015/2016    107783 3
249979 2011/2012    C           2010-09-01 <NA>        2015/2016    107783 1
249980 2011/2012    C           2010-09-01 <NA>        2015/2016    107783 2
249981 2011/2012    C           2010-09-01 <NA>        2015/2016    107783 3
249982 2012/2013    C           2010-09-01 <NA>        2015/2016    107783 1
249983 2012/2013    C           2010-09-01 <NA>        2015/2016    107783 2
249984 2012/2013    C           2010-09-01 <NA>        2015/2016    107783 3
249985 2013/2014    C           2010-09-01 <NA>        2015/2016    107783 1
249986 2013/2014    C           2010-09-01 <NA>        2015/2016    107783 2
249987 2013/2014    C           2010-09-01 <NA>        2015/2016    107783 3
249988 2014/2015    C           2010-09-01 <NA>        2015/2016    107783 1
249989 2014/2015    C           2010-09-01 <NA>        2015/2016    107783 2
249990 2014/2015    C           2010-09-01 <NA>        2015/2016    107783 3
       OnRoll onroll_priority enrol_priority priority_score
1      1      NA              NA             NA
2      1      NA              NA             NA
3      1      NA              NA             NA
4      1      NA              NA             NA
5      1      NA              NA             NA
6      1      NA              NA             NA
7      1      NA              NA             NA
8      1      NA              NA             NA
9      1      NA              NA             NA
10     1      NA              NA             NA
11     1      NA              NA             NA
12     1      NA              NA             NA
13     1      NA              NA             NA
14     1      NA              NA             NA
15     1      NA              NA             NA
16     1      NA              NA             NA
17     1      NA              NA             NA
18     1      NA              NA             NA
19     1      NA              NA             NA
20     1      NA              NA             NA
21     1      NA              NA             NA
22     1      NA              NA             NA
23     1      NA              NA             NA
24     1      NA              NA             NA
25     1      NA              NA             NA
26     1      NA              NA             NA
27     1      NA              NA             NA
28     1      NA              NA             NA
29     1      NA              NA             NA
30     0      NA              NA             NA
⋮      ⋮      ⋮               ⋮              ⋮
249961 1      NA              NA             NA
249962 1      NA              NA             NA
249963 1      NA              NA             NA
249964 1       1               3             13
249965 1       1               3             13
249966 1       1               3             13
249967 1      NA              NA             NA
249968 1      NA              NA             NA
249969 1      NA              NA             NA
249970 1      NA              NA             NA
249971 1      NA              NA             NA
249972 1      NA              NA             NA
249973 1      NA              NA             NA
249974 1      NA              NA             NA
249975 0      NA              NA             NA
249976 1      NA              NA             NA
249977 1      NA              NA             NA
249978 1      NA              NA             NA
249979 1      NA              NA             NA
249980 1      NA              NA             NA
249981 1      NA              NA             NA
249982 1      NA              NA             NA
249983 1      NA              NA             NA
249984 1      NA              NA             NA
249985 1      NA              NA             NA
249986 1      NA              NA             NA
249987 1      NA              NA             NA
249988 1      NA              NA             NA
249989 1      NA              NA             NA
249990 1      NA              NA             NA

In [87]:
head(pivot_long_clean)

  person_id                                                        AcademicYear
1 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2011/2012
2 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2011/2012
3 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2011/2012
4 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2012/2013
5 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2012/2013
6 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2012/2013
  EnrolStatus EntryDate  LeavingDate NCCIS_ACADYR URN    Term OnRoll
1 C           2011-09-05 <NA>        2016/2017    136664 1    1
2 C           2011-09-05 <NA>        2016/2017    136664 2    1
3 C           2011-09-05 <NA>        2016/2017    136664 3    1
4 C           2011-09-05 <NA>        2016/2017    136664 1    1
5 C           2011-09-05 <NA>        2016/2017    136664 2    1
6 C           2011-09-05 <NA>        2016/2017    136664 3    1
  onroll_priority enrol_priority priority_score
1 NA              NA             NA
2 NA              NA             NA
3 NA              NA             NA
4 NA              NA             NA
5 NA              NA             NA
6 NA              NA             NA

In [90]:
df_for_pivot_wide <- pivot_long_clean |>
    select(c(person_id, NCCIS_ACADYR, URN, AcademicYear, Term))

In [91]:
head(df_for_pivot_wide)

  person_id                                                        NCCIS_ACADYR
1 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2016/2017
2 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2016/2017
3 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2016/2017
4 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2016/2017
5 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2016/2017
6 0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433 2016/2017
  URN    AcademicYear Term
1 136664 2011/2012    1
2 136664 2011/2012    2
3 136664 2011/2012    3
4 136664 2012/2013    1
5 136664 2012/2013    2
6 136664 2012/2013    3

In [92]:
# Save as csv 
write.csv(df_for_pivot_wide, "data/additional_school_urn_enrollment_perterm.csv", row.names = FALSE)

In [415]:
#enrol_final
pivot_long_clean |> 
    filter(person_id == '004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894' ) |>
    arrange(AcademicYear)

   person_id
1  004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
2  004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
3  004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
4  004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
5  004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
6  004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
7  004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
8  004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
9  004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
10 004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
11 004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
12 004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
13 004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
14 004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
15 004E9574803B8B9BCE83304FE77D4DEF97CBE5F974323B03A9626E3F58F2C894
   AcademicYear EnrolStatus EntryDate  LeavingDate NCCIS_ACADYR URN    Term
1  2012/2013    C           2012-09-04 <NA>        2017/2018    107441 1
2  2012/2013    C           2012-09-04 <NA>        2017/2018    107441 2
3  2012/2013    C           2012-09-04 <NA>        2017/2018    107441 3
4  2013/2014    C           2012-09-04 <NA>        2017/2018    107441 1
5  2013/2014    C           2012-09-04 <NA>        2017/2018    107441 2
6  2013/2014    C           2012-09-04 <NA>        2017/2018    107441 3
7  2014/2015    S           2014-07-07 <NA>        2017/2018    107428 1
8  2014/2015    S           2014-07-07 <NA>        2017/2018    107428 2
9  2014/2015    S           2014-07-07 <NA>        2017/2018    107428 3
10 2015/2016    C           2014-07-07 <NA>        2017/2018    107428 1
11 2015/2016    C           2014-07-07 <NA>        2017/2018    107428 2
12 2015/2016    C           2014-07-07 <NA>        2017/2018    107428 3
13 2016/2017    C           2014-07-07 2017-07-25  2017/2018    107428 1
14 2016/2017    C           2014-07-07 2017-07-25  2017/2018    107428 2
15 2016/2017    C           2014-07-07 2017-07-25  2017/2018    107428 3
   OnRoll onroll_priority enrol_priority priority_score
1  1      NA              NA             NA
2  1      NA              NA             NA
3  1      NA              NA             NA
4  1       1               3             13
5  1       1               3             13
6  1       1               3             13
7  1      NA              NA             NA
8  1      NA              NA             NA
9  1      NA              NA             NA
10 1      NA              NA             NA
11 1      NA              NA             NA
12 1      NA              NA             NA
13 1      NA              NA             NA
14 1      NA              NA             NA
15 0      NA              NA             NA

#### Pivot Wide

In [93]:
pivot_wide <- df_for_pivot_wide |>
    arrange(person_id, AcademicYear, Term) |>
    mutate(Year_Term = paste0("Y", AcademicYear, "_", "Term", Term),
          URN = as.character(URN)) |>
    select(person_id, NCCIS_ACADYR, Year_Term, URN) |>
    pivot_wider(
        names_from = Year_Term,
        values_from = URN,
        values_fill = NA
      )

In [94]:
pivot_wide

      person_id
1     0002FD06417A994A32C6C24D7236F7C6D98ACD309E999386EFE3A04741BF3433
2     00063B7DE8D61E07E54571351684A37504385EBD55879708236F3579C4E33661
3     000709767CB306493FC46DAC5E2E6B92D691A0C8A5299139ACA3871DAE72A909
4     00131B1E9F8FD120B0E688913FCFE2F0C27F1B2C6584AE0378B38B75E74B10AC
5     0015AFB059DFAA539E96CA31373F8B3E2244BBE7737F72CD606C785A47AA862D
6     00183D5045A271DEF4B6CC51797F891551229B01E913B4C0619CCBC638EA63E7
7     001F42538A9E6E496F13CD05B5E9FE91EB3B20F0CEBECA1B76CC5E7151B7A0D4
8     00211975518FD5336E43850D59B5F5DDA7CD98B212760111CB40528BDECF3B1B
9     00237E9C21696BB29409630166F2D9CCEC24B83FB120AEDD878DDD54C6516B3D
10    00247728E0E765C3F36CF7DBDF2A3509DB16E5CED7E4707969748F4B62DA78A9
11    0025102C0D8E8C5F27454E3715E982A43E1431991E85562E55BCB19D9D1BD7D3
12    0025514088C52FB45B7439689844A1FEA2FB8B2753994F432CC7DDC68036BD59
13    00269FAEA8B5167F1239AA166C20B7673380CCB3E5F3E2F1F6FAA6034A11CE88
14    0026BFA5D5426F421200AB505AAD52956621DCC253241A6647302BCE4764547D
15    002D3DB2625339C740EB129CCC925A9D90E4F5AA05561B81FE166EDF990B8F65
16    002E7A9E65A6A184952E4F1811844FCFCCE758FAE60986A1F9B9C9892FD0895D
17    003196BCDC325A98F118130F185DF8FDDE1B8E1E4882719DAE198B2908F03A5B
18    0032202712FAB3A372409235FFE3C0486E36F9B2FB9C9C9851B4ACAB9A3330F0
19    0037E941FE88C2503AF508B5306803DB1693F3200533648162692820D1EA221D
20    0043C7C252748432DF62E306CCC2DFF568A52DC78D4021140E3C4676C9D65A7E
21    00450DFB52E0DDD50F5800AD149075B29E4A1454F36B9ACF2E106CF44B9BED55
22    0045ADA48CA299BC4445318E8D951610DCB89A829665CFC821E92340F0F8B30D
23    0046475B3089CF6E67A50BBAB6ACC4D6C7FA957BEE68B7F8365239D87857F197
24    0046A4A849F346DFC497329C2BEE0509FAC101F8F4683542D6B453D1C10156BE
25    004AA9D5C19D6B421D63DF6E9FB8BA6C671707143EF6FD6794AC73DE319156B0
26    004CD18444BDD86E6C7F4BE1EE806175325E95085AEBC68E7CAA36A747BD2824
27    004D0B5FF90E252B2912022950FEC4929A1ACB81BA61A626F3093B3B496C93CA
28    004D2E4310F936F43F4D73B1BD31894B7273A1E30C1A028DAAC81939B9572966
29    004FE0E78454FE677A07F1AD8D1226F61C6534E08B44EE01DC6C518FE2200DEA
30    0050C79DAB376114E567D08BE22EA699565E600DFC9F3BD68705700FA49DE62C
⋮     ⋮
17144 FF7EFC3006B327BC644769B23FF20D6E4AFBD5EAE86EE2110BB9B3E1E7317740
17145 FF87772E341BABD802077555E62FB0C28F67C988A30868E6E9F2DA6D557D7DF1
17146 FF8A2758AC947462FBCFD2DCD8024A4EDC6A7C6B63C5E87AB1ABA8D7CF3DCCF0
17147 FF8DEC4753882445FD9D524D7235E53252C52529C3B00C22A96D7C693BEEAC4C
17148 FF8E8AF167DFF1BAF1D811D242FA37AF571E9F0D9A71C329110B911ED5BD0577
17149 FF8F6D381F3BFF07819CBE767D827F493B3F1A4F921BC4AB2E80A8EF2A77F6C4
17150 FF9EA711F52DA4D4DF1670062FB8E2C0AEB31E8FC6EB0797CC1A29644957872C
17151 FFAB3C449F625A8B0527299C27FB85E818A99752883B172742E224652383116F
17152 FFB4377E08770663A747BC594EB9DAB119751856BE2BFD42B18070EDC7F58420
17153 FFB5122C6D8418A48E6FB924782900EF5E4605E4ECFD42FFB6C3119515E32C2F
17154 FFB5635E90C51B5347572A1D06AD63844EBA1C885834A3FB3F09AE4CB361A019
17155 FFB9583A0820E84F60A840CDB2D2E143E87A2BE0091320FEBFD0FC7A5C9A7C5B
17156 FFBC13351F5A42EBF9E6A394DD518A4EF6363B0BBAEE35D691F457292C455ED8
17157 FFBD6A3EECCC20370CAC11CC736BF0A4EC2CA96494106C8C26B3B565003833A7
17158 FFBF093B81AF4B734782FF9C927D3A86B9581F52D2E18D059CC2DDBA97110CDA
17159 FFC07EC8DFA7528E9E1C34B30490DC24EDC687B160DC3F750BB70DB3C45CA343
17160 FFC53382EFC80944BF643197EFC665798C754FA8E41038787A7E7B316B99A75B
17161 FFDE0350353E1B484F83298958E0F735D428D6B50E78471B87509497F4406002
17162 FFE133B080FD044D5E6FDC0E74D7303B3D41419692A96B3E116D180FE9EB2F06
17163 FFE244494ADA5394035640D578E70F7D57EBA5F67793F328CEF11B0B124491E2
17164 FFE326BEEDD9B7453AA81BB7251D3F724AB1351CD2D45090955FC0B1EC4377EF
17165 FFE326E526FAA00EF542D85A2BEBF681FB29C82A21EDA118DCD93D32035A203B
17166 FFE8D30492571D5641B63115FFED00DE60D39E160D78483EC4E2BCE0A442F884
17167 FFEBA230449490BA4B1BCEB1A68C790B1D85708DE8C6EAB8CD170D3E52F12775
17168 FFEBA2A7088A41ADEF06DE231C6F48B615D19A0CA2D2FC917F432A964C9B2EA3
17169 FFED614C13A2D6EFF153DB7DFFDDFC67F6E1801D61B8BE385EB8FBA01B7559EC
17170 FFEF385FC541F397C34ACF193D6936D6BB045655B8781D7CFF18D632AAE9ED10
17171 FFF3B0DACBE2C9B20A4985A8613C997452AD35FF8A1E2D5EFCB0D1AD0199D4CB
17172 FFF418E028358035D198C75ABA5A4E7C1C34C8CEC531947613359CD2FB0C6008
17173 FFFEE5F1CE2162DC4CD8DAE705972B87DCAE6AC71372B8A9867D6D487AE08DAA
      NCCIS_ACADYR Y2011/2012_Term1 Y2011/2012_Term2 Y2011/2012_Term3
1     2016/2017    136664           136664           136664
2     2015/2016    136736           136736           136736
3     2015/2016    130909           130909           130909
4     2016/2017    136736           136736           136736
5     2016/2017    107440           107440           107440
6     2016/2017    108087           108087           108087
7     2015/2016    107395           107395           107395
8     2015/2016    107391           107391           107391
9     2015/2016    121716           121716           121716
10    2015/2016    132219           107366           107366
11    2015/2016    135935           135935           135935
12    2016/2017    136198           136198           136198
13    2016/2017    137001           137001           137001
14    2015/2016    107439           107439           107439
15    2015/2016    107414           107414           107414
16    2015/2016    138111           137338           137338
17    2015/2016    113528           113528           113528
18    2015/2016    136392           136392           136392
19    2016/2017    107414           107414           107414
20    2015/2016    107386           107386           107386
21    2015/2016    135367           135367           135367
22    2015/2016    107366           107366           107366
23    2016/2017    107397           137576           137576
24    2016/2017    107439           107439           107439
25    2016/2017    107386           107386           107386
26    2016/2017    137036           137036           137036
27    2016/2017    107442           107442           107442
28    2016/2017    136664           136664           136664
29    2015/2016    107366           107366           107366
30    2015/2016    107439           107439           107439
⋮     ⋮            ⋮                ⋮                ⋮
17144 2015/2016    107391           107391           107391
17145 2015/2016    136880           136880           136880
17146 2015/2016    107440           107440           107440
17147 2016/2017    107386           107386           107386
17148 2016/2017    136103           136103           136103
17149 2016/2017    108097           108097           108097
17150 2015/2016    107772           107772           107772
17151 2015/2016    136905           136905           136905
17152 2015/2016    137487           137487           137487
17153 2015/2016    107441           107441           107441
17154 2015/2016    107414           107414           107414
17155 2015/2016    137576           137576           137576
17156 2015/2016    107366           107366           107366
17157 2015/2016    107413           107413           107413
17158 2015/2016    107428           107428           107428
17159 2015/2016    110899           110899           110899
17160 2016/2017    136736           136736           136736
17161 2016/2017    107275           107275           107275
17162 2015/2016    130909           130909           130909
17163 2015/2016    135367           135367           135367
17164 2016/2017    107305           107305           107305
17165 2016/2017    135957           135957           135957
17166 2015/2016    136604           136604           136604
17167 2016/2017    107386           107386           107386
17168 2015/2016    121714           121714           121714
17169 2016/2017    134993           134993           134993
17170 2015/2016    136788           136788           136788
17171 2016/2017    107397           107397           107397
17172 2016/2017    107562           107562           107562
17173 2015/2016    107783           107783           107783
      Y2012/2013_Term1 Y2012/2013_Term2 Y2012/2013_Term3 Y2013/2014_Term1
1     136664           136664           136664           136664
2     136736           136736           136736           136736
3     130909           130909           130909           130909
4     136736           136736           136736           136736
5     107440           107440           107440           107440
6     108087           108087           108087           108087
7     107395           107395           107395           107395
8     NA               NA               NA               135732
9     121716           121716           121716           121716
10    107366           107366           107366           107366
11    135935           135935           135935           135935
12    136198           136198           136198           136198
13    137001           137001           137001           137001
14    107439           107439           107439           107439
15    107414           107414           107414           139982
16    137338           137338           137338           137338
17    138863           138863           138863           138863
18    136392           136392           136392           136392
19    107414           107414           107414           139982
20    107386           107386           107386           139975
21    135367           135367           135367           135367
22    NA               NA               NA               138099
23    137576           137576           137576           137576
24    107439           107439           107439           107439
25    107386           107386           107386           139975
26    137036           137036           137036           137036
27    107442           107442           107442           107442
28    136664           136664           136664           136664
29    107366           107366           107366           107366
30    107439           107439           107439           107439
⋮     ⋮                ⋮                ⋮                ⋮
17144 107391           107391           107391           107391
17145 136880           136880           136880           136880
17146 107440           107440           107440           107440
17147 107386           107386           107386           139975
17148 136103           136103           136103           136103
17149 108097           108097           108097           108097
17150 107780           107780           107780           107780
17151 136905           136905           136905           136905
17152 137487           137487           137487           137487
17153 107441           107441           107441           107441
17154 107414           107414           107414           139982
17155 137576           137576           137576           137576
17156 107366           107366           107366           107366
17157 107413           107413           107413           107413
17158 107428           107428           107428           107428
17159 110899           110899           110899           110899
17160 136736           136736           136736           136736
17161 136736           136736           136736           136736
17162 130909           130909           130909           130909
17163 135367           135367           135367           135367
17164 107440           107440           107440           107440
17165 135957           135957           135957           135957
17166 136604           136604           136604           136604
17167 107386           107386           107386           139975
17168 121714           121714           121714           121714
17169 134993           134993           134993           134993
17170 136788           136788           136788           136788
17171 139060           139060           139060           139060
17172 121690           121690           121690           121690
17173 107783           107783           107783           107783
      Y2013/2014_Term2 Y2013/2014_Term3 Y2014/2015_Term1 Y2014/2015_Term2
1     136664           136664           136664           136664
2     136736           136736           136736           136736
3     130909           130909           130909           130909
4     136736           136736           136736           136736
5     107440           107440           107440           107440
6     108087           108087           108087           108087
7     107395           107395           107395           107395
8     135732           135732           135732           135732
9     121716           121716           121716           121716
10    107366           107366           107366           107366
11    135935           135935           135935           135935
12    136198           107441           107441           107441
13    137001           137001           137001           137001
14    107439           107439           107439           107439
15    139982           139982           139982           139982
16    137338           137338           137338           137338
17    138863           138863           138863           138863
18    136392           136392           136392           136392
19    139982           139982           139982           139982
20    139975           139975           139975           139975
21    135367           135367           135367           135367
22    138099           138099           131772           131772
23    137576           137576           137576           137576
24    107439           107439           107439           107439
25    139975           139975           139975           139975
26    137036           137036           137036           137036
27    107442           107442           107442           107442
28    136664           136664           136664           136664
29    107366           107366           107366           107366
30    107439           107439           107439           107439
⋮     ⋮                ⋮                ⋮                ⋮
17144 107391           107391           107391           107391
17145 136880           136880           136880           136880
17146 107440           107440           107440           107440
17147 139975           139975           139975           139975
17148 136103           136103           136103           136103
17149 108097           108097           108097           108097
17150 107780           107780           107780           107780
17151 136905           136905           136905           136905
17152 137487           137487           137487           137487
17153 107441           107441           107441           107441
17154 139982           139982           139982           139982
17155 137576           137576           137576           137576
17156 107366           107366           107366           107366
17157 107413           107413           107413           107413
17158 107428           107428           107428           107428
17159 110899           110899           110899           110899
17160 136736           136736           136736           136736
17161 136736           136736           136736           136736
17162 130909           130909           130909           130909
17163 135367           135367           135367           135367
17164 107440           107440           107440           107440
17165 135957           135957           135957           135957
17166 136604           136604           136604           136604
17167 139975           139975           139975           139975
17168 121714           121714           121714           121714
17169 137444           137444           137444           137444
17170 136788           136788           136788           136788
17171 139060           139060           139060           139060
17172 121690           121690           121690           121690
17173 107783           107783           107783           107783
      Y2014/2015_Term3 Y2015/2016_Term1 Y2015/2016_Term2 Y2015/2016_Term3
1     136664           136664           136664           136664
2     136736           NA               NA               NA
3     130909           NA               NA               NA
4     136736           136736           136736           136736
5     107440           107440           107440           107440
6     108087           108087           108087           108087
7     107395           NA               NA               NA
8     135732           NA               NA               NA
9     121716           NA               NA               NA
10    107366           NA               NA               NA
11    135935           NA               NA               NA
12    107441           107441           107441           107441
13    137001           137001           137001           137001
14    107439           NA               NA               NA
15    139982           NA               NA               NA
16    137338           NA               NA               NA
17    138863           NA               NA               NA
18    136392           NA               NA               NA
19    139982           139982           139982           139982
20    139975           NA               NA               NA
21    135367           NA               NA               NA
22    131772           NA               NA               NA
23    137576           137576           137576           137576
24    107439           107439           107439           107439
25    139975           139975           139975           139975
26    137036           137036           137036           137036
27    107442           107442           107442           107442
28    136664           136664           136664           136664
29    107366           NA               NA               NA
30    107439           NA               NA               NA
⋮     ⋮                ⋮                ⋮                ⋮
17144 107391           NA               NA               NA
17145 136880           NA               NA               NA
17146 107440           NA               NA               NA
17147 139975           139975           139975           139975
17148 136103           136103           136103           136103
17149 108097           108097           108097           108097
17150 107780           NA               NA               NA
17151 136905           NA               NA               NA
17152 137487           NA               NA               NA
17153 107441           NA               NA               NA
17154 139982           NA               NA               NA
17155 137576           NA               NA               NA
17156 107366           NA               NA               NA
17157 107413           NA               NA               NA
17158 107428           NA               NA               NA
17159 110899           NA               NA               NA
17160 136736           136736           136736           136736
17161 136736           136736           136736           136736
17162 130909           NA               NA               NA
17163 135367           NA               NA               NA
17164 107440           107440           107440           107440
17165 135957           135957           135957           135957
17166 136604           NA               NA               NA
17167 139975           139975           139975           139975
17168 121714           NA               NA               NA
17169 137444           137444           137444           137444
17170 136788           NA               NA               NA
17171 139060           139060           139060           139060
17172 121690           121690           121690           121690
17173 107783           NA               NA               NA
      Y2010/2011_Term1 Y2010/2011_Term2 Y2010/2011_Term3
1     NA               NA               NA
2     136736           136736           136736
3     130909           130909           130909

#### Save as CSV

In [95]:
write.csv(pivot_long, "data/additional_enrolment_by_term.csv", row.names = FALSE)

In [96]:
write.csv(pivot_long_clean, "data/additional_enrolment_by_term_clean.csv", row.names = FALSE)

In [97]:
write.csv(pivot_wide, "data/additional_enrolment_wide.csv", row.names = FALSE)

In [98]:
write.csv(enrol_final, "data/additional_enrol_final.csv", row.names = FALSE)

In [100]:
#write.csv(school_count, "data/additional_school_count.csv", row.names = FALSE)

# extract from full enrolment tables whether ever attended AP/PRU

In [101]:
head(enrol_final)

  person_id                                                        SchoolID
1 35DFCB5D8F021D95483FF24CE410460A7265CE97C3E6D703CA8DAC6E3E333C47 125
2 CD414F29155D31984D61A6AFE5652D361C00277FEEFB3794FEFF130EA28F0CBB 125
3 868641B54D3700FE1E77718923B99D3A71905DA252D53EB8494816557E111548 125
4 3AF775F1DC69FD59BD020B2884CC8265B0F28DD726A1CB98C8F0091B0E3BE67B 125
5 0BFA0D59291474ECFA993CECC8B3553CB312919D1F7107A5A04EA234F4D9AEF5 125
6 8E783AF3FBE68119322CB54C141558117F093036F6CCA94259A8B870A8A07F73 125
  AcademicYear OnRoll_1 OnRoll_2 OnRoll_3 EnrolStatus EntryDate  LeavingDate
1 2010/2011    1        1        1        C           2010-08-27 <NA>
2 2010/2011    1        1        1        C           2010-08-27 <NA>
3 2010/2011    1        1        1        C           2010-08-27 <NA>
4 2010/2011    1        1        1        C           2010-08-27 <NA>
5 2010/2011    1        1        1        C           2010-08-27 <NA>
6 2010/2011    1        1        1        C           2010-08-27 <NA>
  PartTime NCCIS_ACADYR URN    InstitutionTypeDesc SchoolName
1 0        2015/2016    130909 Academy sponsor led Dixons City Academy
2 0        2015/2016    130909 Academy sponsor led Dixons City Academy
3 0        2015/2016    130909 Academy sponsor led Dixons City Academy
4 0        2015/2016    130909 Academy sponsor led Dixons City Academy
5 0        2015/2016    130909 Academy sponsor led Dixons City Academy
6 0        2015/2016    130909 Academy sponsor led Dixons City Academy
  PhaseOfEducationDesc
1 Not applicable
2 Not applicable
3 Not applicable
4 Not applicable
5 Not applicable
6 Not applicable

In [102]:
ever_AP <- enrol_final |>
    filter(InstitutionTypeDesc == 'AP/PRU')

In [103]:
ever_AP_ids <- ever_AP |>
    select(person_id) |>
    distinct() |>
    mutate(ever_AP = TRUE)

In [104]:
ever_AP_ids

    person_id                                                        ever_AP
1   B891969D99CBDDFD25843650004166B78065AA19286746C38AC2C2BDCC9DF517 TRUE
2   8B0EF0EF12A6FC021D4C25CEEEFE5B40E652B6391509975634A16AE4693F9EED TRUE
3   2FD320DE2176D0875426B78D75636E1B998C566B5C6C5BE10686578EEC52ADD8 TRUE
4   09CAD5FFBCC56CEF7C8F4F6B461E0B27AF9B4432AF9F2616069CB27BB5F16611 TRUE
5   2C160E1145CBD3E2FC154D967298692B14D4623286F73E86F2970B408EBF018C TRUE
6   1E430896DDAE48DE8494FF0C06E5A3C5D385456DE311B49F7C155BA3502D86DE TRUE
7   C37FE6B9922AE18F48BC8ED4C583AD8373A292A3E83E71347364C34F43C96767 TRUE
8   13E07C3C09B0FA7310CA86A0ED66D2748561C27DA761E4552CF171D05D33DE3B TRUE
9   5355B3AC36E9993749D3F2F86C889C52EF887A925F3BA43D6B5CBAF1CC6B074E TRUE
10  2FCCFED055660A872241F7AF3F2DA36489A59922E6F2E26056586CF1C8851953 TRUE
11  D7DE9B2046E99FB34FFDF6F1FEC4F57DDEA43DC3FD9713BF4C1785093EA64458 TRUE
12  EB72BF7B34861DBA4E78C05FA080DF20F459CB5679604067F7E5311FC19EBEB7 TRUE
13  823AA0513A29E94F2EA3DB98A975BF88E02B2A3EC7D913FB4416AE5C12CC060C TRUE
14  FB4195621662C6F4BB8087DF4D0A7489C7ACF5E9F22FB6CE88FB44B16EC93CE1 TRUE
15  8E6A491213FD343A879614A7FA26C3F07EC97484B63A6A86B45BA227BE56E127 TRUE
16  7610E8C419835103ADB23AABACB96B125CB929AA1500D26336E585212735DF32 TRUE
17  0C2B20D8ACFBA9F62A3A35A3AC03A2E3B0023C883DC19E4B85B6D981EE71669C TRUE
18  F4DEC11F17717C87B8049A4350CC34ADBA6613905492016A38AF991B306ECAEB TRUE
19  0762BB946D61359408673C5C153A377C1B3618C8EEF144A77213617FA20405FB TRUE
20  784C52C31EE41254051B2246A8CD78BF26091F1DB2B4D5004418400C2921BC7C TRUE
21  31525EDF7A3503D7A6FA85AC17F78B1BDA988DA60CA16C5D68A36D4811F4B964 TRUE
22  903DE70D0BF648765D8D019CF40EEC42D549C4E86450BB5E9F93E40239BCC0E8 TRUE
23  9A6E9A2824D831E43615735AC34FA05578095EE75F77A1977B1EE9D878A0E462 TRUE
24  902C3604F1E98C1623C4507138BE631D4BD9A651731EE9EC4FBA4AB8E1E2189A TRUE
25  CA8B826A608D96E7ECC0D5ACDF070CDC8E78AC0146F021DE15AC5D014D6967A9 TRUE
26  D5AF52C18970A24DC7E4316DD96ED2CBB768FED99F0434C86F73705EBDFC091C TRUE
27  DA35AB10EC1ECDB2E21697EE674171DCA1B7ACF973E2CB8343D083BA5ACFB7D9 TRUE
28  2B61287808231C720C63753E882478D403B0E4F4A569D68AEFF37830BCCDEE60 TRUE
29  2491CFD765A99C0547B443947117A69859686831EAB4491F605FE899B1C8F5D7 TRUE
30  C382278148729B97202A80E5517BFB67B2DAE4F50C64F40F96AE32857DD51108 TRUE
⋮   ⋮                                                                ⋮
446 E8DF871B687FBECC7592F7EEB21FD9F5081C468487EB84F696E8C954D4798344 TRUE
447 E207BCC92AB07DD987D9F16F7E0E65A2432A0072EC8EB03C1DA56FEB0047FF1D TRUE
448 1ECFC4E45E15221BCE6B0D757F67034426336798BC11C12A2B390E63A95CF277 TRUE
449 834C876FC45BE41A7BBEB3232F96053DA5AB62A326C89E3D37705BD332C14888 TRUE
450 A31F646CF211D604F5440A0A4B4F1E681766C031EA52D9805649F098B99D2D1C TRUE
451 B255DF1F8E204BB34835140FC4EFA66A50C95B5CF55F552CA624D97FF0A49D94 TRUE
452 6B1D22E78BE113C02F352875896C5AAB3F0CF31E30E7DB480F1599C89CB0AAD8 TRUE
453 22EFC67F8242930E97574CE36745F06D7C30D172DC3ACCC07F3F7CBDEA900EDF TRUE
454 9648BF5C29EAFB5C61548727774EFFEF0C2F038332462FF21DD14944BE0939AE TRUE
455 C4181FF529A0EF47B8C6EEC268CD9E857EAEA41301B11317E73DE7A7542637CB TRUE
456 BB817670303F1B11BF4A4B13A9A9D7325EFB1ED4A1B454784FC11824D6A83F03 TRUE
457 86B21B17A0F9D237714BEC463DE4862B6B7619F1EB47261F2BDCD93DFC6021BB TRUE
458 1780A00B82B8F8020CAC19CBC839471BE6EB42AFBDAB395C0E82CFB36DDF20E2 TRUE
459 8B1B9C2B5EB23DFE13CFBB786964C915CBC5B9530DC1AD11678F17CDED12ADED TRUE
460 99570C5B1ED407ADA1872650BE93A8CFEAA1287AFF7ED1DE70063ECD8A6787F0 TRUE
461 856906F882ED623E38FD61324907EBD12FA8E57BE0A5E239E8AE5A9A0A13B430 TRUE
462 8C872FF9CACA138E4D4C816D864B49D7FAE833C43FC28E48C71CCD917B45EB73 TRUE
463 445C50FD7B947595058BF986110DA818BF0E91DA7CDAB22F64577BF94C2CFBB2 TRUE
464 3C379E4576CF2F1324643224D174B07F8280091633B92CD723B1020E491ABDE3 TRUE
465 6909B9BDFFA807E84298F8668B36B12BF5FF1755C8A52D1AC0B44FBCE2444D1D TRUE
466 E81DF2225EF7E554A0A1E6A0F7181A91B7A3B74EBB901FBCDD9E396CBBB9833B TRUE
467 D9B32B710BDE1C0CD7F620FA78AC9E5D1BB2947CEF9AF67CB67FE10127A619BF TRUE
468 E773044FD1B990D8AEDAB0AFB3E6A0E67EF2BD96390CF9CEDE13AFE518D1AB84 TRUE
469 7984E6B21D8EE9B4FB47F1CA978C8B317BB328999C539B16A3320BC93EF507BE TRUE
470 6692EC65CB33440758E49F5F971C69478CD63BD70BE33D620F4DFE779C6DF7A5 TRUE
471 ED1288A3CA9B054341D9B7E072A9DD3C7EA929331476EFDD187302AFB9101234 TRUE
472 B213D34AE2AA8551B395CE91826EB479FE3F8ABAEEAC9D9637337925A1C9BF6D TRUE
473 F8603D6E2FE8FE4F23114E9A4205F201959357130CFFFFF4068AC907F85423E4 TRUE
474 AB3701ED6BAF1FBC2E9D027C3D0CF2621FC26A211267B3A730107DF225EAF03B TRUE
475 E77668AE34CE60B4EEE659EF10FBBA98EEF9D76D086208F8988743373E98A8FF TRUE

In [105]:
write.csv(ever_AP_ids, "data/additional_ever_AP_ids.csv", row.names = FALSE)