In [1]:
library(tidyverse)
library(dbplyr)
library(bigrquery)
library(lubridate)

bq_auth()

project_id = "yhcr-prd-bradfor-bia-core"

# create connection to database
con <- DBI::dbConnect(bigrquery::bigquery(), 
                      project = project_id)

print(paste0("Connected to : ", project_id))

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘dbplyr’


The following objects are masked from ‘package:dplyr’:

    ident, sql

[1] "Connected to : yhcr-prd-bradfor-bia-core"

In [2]:
person_ids <- read.csv('data/additional_person_ids.csv', header = TRUE)

## CIN 2009 - 2019

In [3]:
sc_data = "CB_2489.cb_CIN_2009_to_2019"

sc_table <- tbl(con, sc_data) |>
    select(person_id,CIN_ACADYR,CIN_PrimaryNeedCode)

In [4]:
sc_df <- collect(sc_table)

In [5]:
head(sc_df)

  person_id                                                        CIN_ACADYR
1 60ED8043B497A211AC4A5398BD142426BDA0B3D96FE6AED2698D3DFC02DEEB15 2010/2011
2 1F9BB6FF8DB3BD8669EB964CE81B338AFB0D26DE652DF93746D396E29177AD01 2018/2019
3 B159AB8D75C5014034B151D01F7976544F59C57ED857447A87D0486FC65B2028 2018/2019
4 86DF4B72CC0D700A84163BBA7929456060242ACCDC4A16DFB246E808FEC37CC5 2018/2019
5 071DA72845B4CFBC9C3DD46124CEAEF73AF06812BE4088B211BDAFF25EA874F4 2018/2019
6 B577F7CF281A918EF137A9C22D6F0DC9BCF943D97613A5DE816E7136388117B4 2018/2019
  CIN_PrimaryNeedCode
1 n5
2 N1
3 N8
4 N1
5 N1
6 N1

In [6]:
sc_df |> arrange(CIN_ACADYR) |> distinct(CIN_ACADYR) |> pull(CIN_ACADYR)

 [1] "2008/2009" "2009/2010" "2010/2011" "2011/2012" "2012/2013" "2013/2014"
 [7] "2014/2015" "2015/2016" "2016/2017" "2017/2018" "2018/2019"

In [7]:
sc_df |> distinct(CIN_PrimaryNeedCode) |> pull(CIN_PrimaryNeedCode)

 [1] "n5"         "N1        " "N8        " "N4        " NA
 [6] "N0"         "N1"         "N2"         "N3"         "N4"
[11] "N5"         "N6"         "N7"         "N8"         "N9"

N1 = Abuse or neglect
N2 = Child's disability/illness
N3 = Parental Disability/illness
N4 = Family in acute stress
N5 = Family dysfunction
N6 = Socially unacceptable
N7 = Low income
N8 = Absent parenting
N9 = Cases other than Children in Need
N0 = Not stated

In [8]:
sc_df <- sc_df |> 
    mutate(CIN_PrimaryNeedCode = str_trim(CIN_PrimaryNeedCode))

In [9]:
sc_df <- sc_df |> 
    mutate(CIN_PrimaryNeedCode = case_when(
               CIN_PrimaryNeedCode == 'n5' ~ 'N5',
               TRUE ~ CIN_PrimaryNeedCode
            ))

In [10]:
sc_df |> distinct(CIN_PrimaryNeedCode) |> pull(CIN_PrimaryNeedCode)

 [1] "N5" "N1" "N8" "N4" NA   "N0" "N2" "N3" "N6" "N7" "N9"

In [11]:
sc_filtered <- sc_df |>
    filter(person_id %in% person_ids$person_id) |>
    select(person_id,CIN_ACADYR,CIN_PrimaryNeedCode)

In [12]:
sc_filtered |> group_by(CIN_PrimaryNeedCode) |> tally()

   CIN_PrimaryNeedCode n
1  N0                   376
2  N1                  8315
3  N2                   885
4  N3                   136
5  N4                   922
6  N5                  1419
7  N6                   203
8  N7                    25
9  N8                   106
10 N9                    82
11 NA                   149

In [13]:
sc_filtered |> nrow()

[1] 12618

In [14]:
sc_filtered |> 
    summarize(n_distinct(person_id))

  n_distinct(person_id)
1 3652

In [15]:
sc_merge <- sc_filtered |>
    select(-CIN_ACADYR) |>
    distinct()

In [16]:
sc_merge |> nrow()

[1] 4770

In [17]:
sc_merge |> 
    summarize(n_distinct(person_id))

  n_distinct(person_id)
1 3652

In [18]:
sc_merge |>
    group_by(person_id) |>
    filter(n() > 1) |>
    arrange(person_id)

     person_id
1    0045ADA48CA299BC4445318E8D951610DCB89A829665CFC821E92340F0F8B30D
2    0045ADA48CA299BC4445318E8D951610DCB89A829665CFC821E92340F0F8B30D
3    0093549A2B3FB44847A7880014804DB333707601AE77A4AF949EE71E538194D6
4    0093549A2B3FB44847A7880014804DB333707601AE77A4AF949EE71E538194D6
5    0093549A2B3FB44847A7880014804DB333707601AE77A4AF949EE71E538194D6
6    0093549A2B3FB44847A7880014804DB333707601AE77A4AF949EE71E538194D6
7    0093549A2B3FB44847A7880014804DB333707601AE77A4AF949EE71E538194D6
8    017BD83D33E24C2CE047BFB67D7D010694F10CAF3E02B4360C88D4EE29E119FD
9    017BD83D33E24C2CE047BFB67D7D010694F10CAF3E02B4360C88D4EE29E119FD
10   017BD83D33E24C2CE047BFB67D7D010694F10CAF3E02B4360C88D4EE29E119FD
11   01D5BB808C605F3206FF17738BC4011F459A59BBA3DD18AB15D8364CD1B383EF
12   01D5BB808C605F3206FF17738BC4011F459A59BBA3DD18AB15D8364CD1B383EF
13   01D5BB808C605F3206FF17738BC4011F459A59BBA3DD18AB15D8364CD1B383EF
14   025B83C54F43BCBF9D843EB4277A89CBBA219A4370F17F7C855801AC1BF64902
15   025B83C54F43BCBF9D843EB4277A89CBBA219A4370F17F7C855801AC1BF64902
16   02BCCAAD38F91C75D26DB382A43C96B816789C1D4D2C025B7B88F6D778C289C1
17   02BCCAAD38F91C75D26DB382A43C96B816789C1D4D2C025B7B88F6D778C289C1
18   02D438362AE45C0096D7A40626F6E135CC7B04DB78DF84F455D92360F98A7EA3
19   02D438362AE45C0096D7A40626F6E135CC7B04DB78DF84F455D92360F98A7EA3
20   03060C7F96A4FDE490622AC70A8C554639338E2F8C6848B002E6F134F930397A
21   03060C7F96A4FDE490622AC70A8C554639338E2F8C6848B002E6F134F930397A
22   0339CCDC39297FEC647716BC520E3C96665DA7B6A2A330057128E4B0656F190D
23   0339CCDC39297FEC647716BC520E3C96665DA7B6A2A330057128E4B0656F190D
24   0390C9B3C796AF612692B57F080BCA4BF82FAEDD564619E748B32D68BE00190A
25   0390C9B3C796AF612692B57F080BCA4BF82FAEDD564619E748B32D68BE00190A
26   0390C9B3C796AF612692B57F080BCA4BF82FAEDD564619E748B32D68BE00190A
27   03C67308298F1CB39B63B21FE0EA24C3AB3DD9B4062968764C5A183CB9AF3C82
28   03C67308298F1CB39B63B21FE0EA24C3AB3DD9B4062968764C5A183CB9AF3C82
29   04F04A15CAF52A948F653AEA502F9C8071FC6ABF474DD419A3E875FF0BF25209
30   04F04A15CAF52A948F653AEA502F9C8071FC6ABF474DD419A3E875FF0BF25209
⋮    ⋮
1934 FB31E3383D1D36C474D9B5D3CB1B63F74F9D57A1EE89DA826FCF6F0C5956B997
1935 FB31E3383D1D36C474D9B5D3CB1B63F74F9D57A1EE89DA826FCF6F0C5956B997
1936 FB839E188C42610761A3BCEFD95B87EF4FA29DAB5311684F1D6BBC7EDE139D7A
1937 FB839E188C42610761A3BCEFD95B87EF4FA29DAB5311684F1D6BBC7EDE139D7A
1938 FC224D629245A48C1D2263131AF415D137E67DCE91D2290C8C2739652268A3CA
1939 FC224D629245A48C1D2263131AF415D137E67DCE91D2290C8C2739652268A3CA
1940 FCD82E79857E9CDB78ED676A7AC1D17DAC92D0A3E379AF82693C797F3404C6B7
1941 FCD82E79857E9CDB78ED676A7AC1D17DAC92D0A3E379AF82693C797F3404C6B7
1942 FCD82E79857E9CDB78ED676A7AC1D17DAC92D0A3E379AF82693C797F3404C6B7
1943 FCD82E79857E9CDB78ED676A7AC1D17DAC92D0A3E379AF82693C797F3404C6B7
1944 FD3131DD682E8E9D4465DDDDFF75853A3864EBE754F33FF19C2E76B2BB4C30DB
1945 FD3131DD682E8E9D4465DDDDFF75853A3864EBE754F33FF19C2E76B2BB4C30DB
1946 FD3A8956FC7ECC4E7956E8927C26118F6A431E8E944FFC40E1D4550343B21A4A
1947 FD3A8956FC7ECC4E7956E8927C26118F6A431E8E944FFC40E1D4550343B21A4A
1948 FDA13B650DEC9DBA53E143F38E036F0CAA9FE20D3F9D1511642ADE777DC5C52C
1949 FDA13B650DEC9DBA53E143F38E036F0CAA9FE20D3F9D1511642ADE777DC5C52C
1950 FDD68FE272A6234B38E80B23B7E7AEA24B2ED63A04C981B5D046D4B1A173BB13
1951 FDD68FE272A6234B38E80B23B7E7AEA24B2ED63A04C981B5D046D4B1A173BB13
1952 FDD68FE272A6234B38E80B23B7E7AEA24B2ED63A04C981B5D046D4B1A173BB13
1953 FDD68FE272A6234B38E80B23B7E7AEA24B2ED63A04C981B5D046D4B1A173BB13
1954 FE7E0341560512618F68DB203ADB29FDF291C26185D50CB9A291C1CC4737FADD
1955 FE7E0341560512618F68DB203ADB29FDF291C26185D50CB9A291C1CC4737FADD
1956 FE7E0341560512618F68DB203ADB29FDF291C26185D50CB9A291C1CC4737FADD
1957 FE9D8EC81269617B7AE42463AA4827BBD69DE4CF0BA4BB2E19C3A4CA26A6895A
1958 FE9D8EC81269617B7AE42463AA4827BBD69DE4CF0BA4BB2E19C3A4CA26A6895A
1959 FF0E4F96548A1554A48EEB6E692699D9D511D2152C8E21BBDD82E26A97967B4A
1960 FF0E4F96548A1554A48EEB6E692699D9D511D2152C8E21BBDD82E26A97967B4A
1961 FF0E4F96548A1554A48EEB6E692699D9D511D2152C8E21BBDD82E26A97967B4A
1962 FF4C2AE50FAACEE194CF4F6FE7C8204D070615E157145637C54FCCDFED7C0A2B
1963 FF4C2AE50FAACEE194CF4F6FE7C8204D070615E157145637C54FCCDFED7C0A2B
     CIN_PrimaryNeedCode
1    NA
2    N1
3    NA
4    N1
5    N2
6    N4
7    N5
8    N1
9    N4
10   N6
11   N1
12   N4
13   N5
14   N0
15   N1
16   N1
17   N4
18   N2
19   N4
20   N1
21   N5
22   N1
23   N5
24   N0
25   N1
26   N5
27   N1
28   N6
29   N1
30   N3
⋮    ⋮
1934 NA
1935 N1
1936 N0
1937 N1
1938 N1
1939 N9
1940 NA
1941 N0
1942 N1
1943 N5
1944 N1
1945 N5
1946 N1
1947 N5
1948 N1
1949 N4
1950 N0
1951 N1
1952 N4
1953 N5
1954 N1
1955 N4
1956 N6
1957 N0
1958 N5
1959 N1
1960 N5
1961 N6
1962 NA
1963 N1

In [19]:
ever_cin <- sc_merge |>
    select(person_id) |>
    distinct() |>
    mutate(ever_CIN = TRUE)

In [20]:
ever_cin

     person_id                                                        ever_CIN
1    AAF20E0D9D31684973B137A74028F54A25D0C5EE563478BCB3702047DB25B55B TRUE
2    22A611BACA79474CB520C45004E70419C711DD1AF450F034DD0A46C1417DA708 TRUE
3    683466122ED7D987E396F81D5EB4A3F7BECBA4F8D31DE8C1CD3208005CC6741B TRUE
4    994DEBAAD8CF351CE9C31B89A669974A64F7BB43F315344C3EF31D83CC7CB92D TRUE
5    2DA907C18DD6C9C21DEA87DB2807F96B4D720850953AA25E7EE3306457C6DA9E TRUE
6    F5FD9F46523BDF5820C10C5C92C480B112402A40A9E1324915307C3BCACD5FEB TRUE
7    2B8CCDD7863772F857002F23838E6D99BFC61CE8C8985867D1A4E007CD951A17 TRUE
8    3920D247A0AF6587F5E230C2BB6623D73088D83EB8B46F9CE9A902D95C04DBA7 TRUE
9    A1C8D9F7084F25EDA5B2B67FF73C5FEB419898D875CC597E5EA9D530C71B2DC2 TRUE
10   27685AB445CD7031B6C3F3022BFFE250580A51401829E0DD054B712640458436 TRUE
11   DCCE89706CE603B61C648FD45815804EE3CCD4FD9746036850F46E9D90ECB31D TRUE
12   4397BD31671E4D26376CCFFC0D8EA49B9E40A9F3C7EBB53D2B445B2322DC2C39 TRUE
13   4F72B59C7ED4AA303D7C89C051A94F8F37ACEE0A02905948421EBBB9FB592F8F TRUE
14   80D0029966402ADFBD85EB4FBD6A82E310131A7C131449B83166F7DF682E95BE TRUE
15   7110B85663B3DC71D062BF6C53EFBB797BB79E9B1CAB09FC13CADC34061032D2 TRUE
16   52DCD93286300DCBE0AB75BD93B656851830136FCAC0C4484F01513811D44478 TRUE
17   7CB46AD1DB71E0573FE210092961295823819A7D834AB0A9E3248630C37420FB TRUE
18   DBE6B9A26ABA2D231A0BF915DB336759B4F418854F1D7BDA067ECD364CD9B22D TRUE
19   90692D480C37370D41389BC87E23B084CE470E5CEB16F572CFA272C80A021AAA TRUE
20   FCD82E79857E9CDB78ED676A7AC1D17DAC92D0A3E379AF82693C797F3404C6B7 TRUE
21   DFBC682E7D329F908B1B0AB0F451AC377FDE27C34BA0EDDBA8412ED1D1247338 TRUE
22   C382278148729B97202A80E5517BFB67B2DAE4F50C64F40F96AE32857DD51108 TRUE
23   466B06B574AD64CC3EBD9D12AEE66D3841AB6DFEB007EECC1F3BB30EBD84F197 TRUE
24   FB31E3383D1D36C474D9B5D3CB1B63F74F9D57A1EE89DA826FCF6F0C5956B997 TRUE
25   C9D882C895957A25417100BE2F3DF38AF84C470DF2C2FCDC6CE0BA3D083AB95A TRUE
26   6C991DA44624AF4AF0BA27D6EA742A54173CFCFA66757E7AB8B6B43027D2F676 TRUE
27   129725E97490434064FF1163F7EAAE39EBEE62D09BC46937F546510072D5E223 TRUE
28   F129862BAA8160F814036FE39CF9B13AF1F6C8AAC41A39EAD6392089991DE137 TRUE
29   08136BFE9D96080B12D9BC837105AF84549FFF2F2BDFDA46FFDA3C8F72218AE0 TRUE
30   46FD08045FBA3C7D8A27FEC709FD398C2140B4E9D16E44FB55FA67370AB544BD TRUE
⋮    ⋮                                                                ⋮
3623 31EE59AAAD26C2D0C83DC0F931D8B3D91AF01E1CC6B4D068C6485352A4532B08 TRUE
3624 52DFAA6AF00E1AEE2273C99ACBD4DBDA8783253354EB6200B4A5B86AD009C72D TRUE
3625 CA6D5E60CBD800E19692314BFFC31FF018F6C72E46A472A6074F8C05B5235D29 TRUE
3626 B1BF98A74C090BE5D3B3C13F8F4BA183F50C53779760CB83222F4BB7B3B1645F TRUE
3627 42F8EF56F076F03FD130497FD9CC2CCE2F9ED1F8E7764B89F4831ACE14876834 TRUE
3628 FC51AC3F2E3161E36C20858A86A990065FFE3FF7F004B02E1DFE0FE9B01675D6 TRUE
3629 C1A13DE23994AFE51D41249A9865082E2E97CC34B7F05486BB1F4575D3DE2F42 TRUE
3630 9FF8E3B1ED9D0BED4C31649C4C9FC34D120234A63A6155CC09E4D266ED261CFD TRUE
3631 C13088EECA46E7CE8028AF8D1B795DFA4351296FB5EF4D22629292C431D2C4E1 TRUE
3632 119AC8B5373BBEFB9FA2BD14FE49D7DDBAA330BEB15292D309251898DC799F9C TRUE
3633 BAB9BDE3E1699D283414CA0A77E737B80E52884A173AA3CBEBB48FE0AD162CC9 TRUE
3634 A24941C095F0537ED5288DA16110C8008A250C27E10CAADACEFB40BCDFAEA168 TRUE
3635 5F3B4603E64284319859744A07CD340EF1BA14FA8B8510763E18ECE69BD3584A TRUE
3636 3C6D165B0182D339F4C931C580E087A3E535841F0468C6B8C3F3B05566CC7EC7 TRUE
3637 841938050ED9E347D8E84980B7C09F54A88D8525C92F3F68DC134F3B46A7ED19 TRUE
3638 E7D51F55CC56C24ECD14B89DAC5265D19348DCC1FB43B3D60E6D578DCA98AA05 TRUE
3639 6EEA6C4CDACCB3943B31E8C8D25C4E926D8E41D280DF31BA614077618D30C208 TRUE
3640 2155D2B791C087E092400866AAA0643F41682E8B0B981661843B8F1F41409999 TRUE
3641 3691C9E4B25685AE468F6A7585D64BE85E214140ACB9864A55360B5F9527E5F9 TRUE
3642 5C4F7BC1B4DD6B597BFB0576392D14FF730475D64FA514D9E154FC18F09BBE9C TRUE
3643 5A0B844ECF27A5908817ACC2C416FF846CD94F4C51C1D0971BF2CFFB0AD9D18D TRUE
3644 994B992C55C1B9D14FF4D22F4C3B787330D86EEC0A5084E922348CB1B90CAEF0 TRUE
3645 25126072D470604627EE28E47A21B8F0CDCCAD0E54CC88EF9D882AF8D0B9F4AF TRUE
3646 99F49C7EEEE7ED6F7B9A02B4716E86C54DC85DB6B4A138CA252CA1D18FBCD65A TRUE
3647 F998DEBF2921BAED4CE1B942043399509EC584A1E9AB899633FBD414612F26AE TRUE
3648 242B8F535E9B3EB286CF4345CB42442CEFD3E28E22CC08E8E6B7B63FCB4715C0 TRUE
3649 8AED0F6381EEEB73427C57A5E97360A5B5F2649AEBF7D7200A3EE7262AAE0446 TRUE
3650 8C5287038F68CB5001E3D82A5B676A70959DF5D40DFFDEC2EFE7DBF6CBFC8BB5 TRUE
3651 5C168CB403DD6A14000BE8D1FA58557D773C1592A9AA9D246C0A851557A84419 TRUE
3652 219C2F4460CEBB8D2200C17FC5D43935E561B36A0DD98EAFDE0F2CB0C5AA25A1 TRUE

In [33]:
lac_extra

   person_id                                                        ever_CIN
1  765802B6591B46CCCEFCDE9D32D960FD41C6A1A49207E9B6AFC4D8BAA8789F84 TRUE
2  21922CBFE180E8946C89A59782AC1E466C80D93E85008DE64189761B1A6E8D8C TRUE
3  E2C4A8EAB1EFA92CFEFD8D2E6A091B122252B209CF2B99BA0CC72C93710DEC9C TRUE
4  82762AA35A1AB1C1175FC7956C1E03E701C55462E5BA0E49714FB47C7D05EB9C TRUE
5  59C4DF19BF86AC5D32BFC710E7A919531628BB507F8024E1BFECD192F6B569EE TRUE
6  D21CC15BDFE3DC41EAD144257AA1A7B8A96E6DD90DACA1F5F7C6F1F17014CF96 TRUE
7  5F1AD58EC267D213DF017826D51B3C9544777C6F9197ED6E2053D428A4AA7E33 TRUE
8  B6275FAD8102F90F9E123AA0D524DFEF471A00E201B68A9CA9EBA13E290DEAE9 TRUE
9  AF5F6E07B22B1FEC1F64D15E42C2FE07724BC528BA4CF668DF72AD62B7E01F51 TRUE
10 18EAC0E67AB39869749D3068D2697524BC1442A9AFDFC981C0FF6B5116774725 TRUE

In [34]:
ever_cin <- rbind(ever_cin,lac_extra)

In [35]:
ever_cin |> nrow()

[1] 3662

In [36]:
head(ever_cin)

  person_id                                                        ever_CIN
1 AAF20E0D9D31684973B137A74028F54A25D0C5EE563478BCB3702047DB25B55B TRUE
2 22A611BACA79474CB520C45004E70419C711DD1AF450F034DD0A46C1417DA708 TRUE
3 683466122ED7D987E396F81D5EB4A3F7BECBA4F8D31DE8C1CD3208005CC6741B TRUE
4 994DEBAAD8CF351CE9C31B89A669974A64F7BB43F315344C3EF31D83CC7CB92D TRUE
5 2DA907C18DD6C9C21DEA87DB2807F96B4D720850953AA25E7EE3306457C6DA9E TRUE
6 F5FD9F46523BDF5820C10C5C92C480B112402A40A9E1324915307C3BCACD5FEB TRUE

### Save csv

In [37]:
# save as csv
write.csv(ever_cin, "data/additional_ever_cin.csv", row.names = FALSE)

# CIN Disability 2009-2019

In [14]:
dis_data = "CB_2489.cb_CIN_2009_to_2019_Disability"

dis_table <- tbl(con, dis_data) |>
    select(person_id,CIN_ACADYR,CIN_Disability)

In [27]:
dis_df <- collect(dis_table)

In [28]:
head(dis_df)

  person_id                                                        CIN_ACADYR
1 EDA994097F3DDFA87825365C60773712D04CD3654F794D63C55D9E3932D484E0 2008/2009
2 DBD4209B51C4884D3BCCBA99F753B1B09189BF502241237C59D178D47810FF0A 2008/2009
3 DAC8EEC48D224CBDDAEA16BB114F1364011C78E6C1B6EF7C8941A3E231F91B16 2008/2009
4 49C7AB9FEB601D00D97784F5B4B91DAD30B87E65AA9F6777B1FC920EA3AFD43C 2008/2009
5 54CC7198D9E1CDB2182E47800199B7FA36FADF3695B08BC20DC389F69C703D93 2008/2009
6 9BBCB3B30E354EE0BBD65262E0DBA7B7654CFA72E3E1643324CE5F60C4FCBDE6 2008/2009
  CIN_Disability
1 NA
2 NA
3 NA
4 NA
5 NA
6 NA

In [24]:
dis_df |> arrange(CIN_ACADYR) |> distinct(CIN_ACADYR) |> pull(CIN_ACADYR)

 [1] "2008/2009" "2009/2010" "2010/2011" "2011/2012" "2012/2013" "2013/2014"
 [7] "2014/2015" "2015/2016" "2016/2017" "2017/2018" "2018/2019"

In [25]:
dis_df |> distinct(CIN_Disability) |> pull(CIN_Disability)

 [1] NA     "LD"   "PC"   "AUT"  "BEH"  "CON"  "DDA"  "INC"  "MOB"  "VIS"
[11] "COMM" "HAND" "HEAR" "NONE" "None" "none"

Holds a record of the type of disability(s) a child may suffer from. NONE by itself is used for no disability.

NONE = None
MOB = Mobility
HAND = Hand Function
PC = Personal Care
INC = Incontinence
COMM = Communication
LD = Learning
HEAR = Hearing
VIS = Vision
BEH = Behaviour
CON = Consciousness
AUT = Diagnosed with autism or Aspergers syndrome 
DDA = Disabled under DDA but not in above categories

In [29]:
dis_tidy <- dis_df |> 
    mutate(CIN_Disability = case_when(
        is.na(CIN_Disability) | CIN_Disability %in% c('NONE', 'None', 'none') ~ NA_character_,
        TRUE ~ CIN_Disability
    ))

In [30]:
dis_tidy |> group_by(CIN_Disability) |> tally()

   CIN_Disability n
1  AUT             1980
2  BEH             2495
3  COMM            2878
4  CON              839
5  DDA              754
6  HAND            1064
7  HEAR             701
8  INC             1581
9  LD              4084
10 MOB             2522
11 PC              2168
12 VIS             1141
13 NA             97607

In [31]:
dis_filtered <- dis_tidy |>
    filter(person_id %in% person_ids$person_id)

In [32]:
dis_filtered |> group_by(CIN_Disability) |> tally()

   CIN_Disability n
1  AUT              234
2  BEH              330
3  COMM             359
4  CON               96
5  DDA              119
6  HAND             129
7  HEAR             111
8  INC              278
9  LD               436
10 MOB              358
11 PC               294
12 VIS              169
13 NA             11456

# SS CIN

In [33]:
cin_data = "CB_2489.tbl_SocialServices_CiNP"

cin_table <- tbl(con, cin_data) |>
    select(person_id,StartDate,EndDate)

In [34]:
cin_df <- collect(cin_table)

In [35]:
head(cin_df)

  person_id                                                        StartDate
1 5356366A24004B6B14DAAAEE9ADD3EFC661545E444D05C5D4C6001494A3CC372 01/04/2019
2 D6B3B45878368C7D67E405D9F608352B0C35D272A9BB8A31DFC350445C58CE91 01/04/2019
3 63D51806BF39CD8BA75B167A225A6265CACB64C2BCC450D1CC6A8D1B7762C51A 01/04/2019
4 E891B044F3EF5574592575824696FCB0A36088AC566895C92256707227EFE7B4 01/04/2019
5 FE31EDBA16EA714C02AF362D2D38E6845D1F61EDA058E3C1FBED9BB816287D4D 01/05/2019
6 88B89CC5F7F97D31198DDA1EB490F4726DCD596D645BED3601D35F50530B9B14 01/05/2019
  EndDate
1
2 27/08/2020
3 28/09/2019
4 30/05/2019
5 04/07/2019
6 04/07/2019

In [36]:
cin_df |> arrange(StartDate) |> distinct(StartDate) |> pull(StartDate)

  [1] "01/02/2021" "01/03/2020" "01/03/2021" "01/04/2019" "01/04/2020"
  [6] "01/04/2021" "01/05/2019" "01/05/2020" "01/06/2020" "01/06/2021"
 [11] "01/07/2019" "01/08/2019" "01/09/2020" "01/10/2019" "01/10/2020"
 [16] "01/11/2019" "01/11/2020" "01/12/2020" "02/01/2020" "02/02/2021"
 [21] "02/03/2020" "02/03/2021" "02/04/2019" "02/04/2020" "02/05/2019"
 [26] "02/05/2021" "02/06/2020" "02/06/2021" "02/07/2019" "02/07/2020"
 [31] "02/08/2019" "02/09/2019" "02/09/2020" "02/10/2019" "02/10/2020"
 [36] "02/11/2020" "02/12/2019" "02/12/2020" "03/01/2020" "03/01/2021"
 [41] "03/02/2020" "03/02/2021" "03/03/2020" "03/03/2021" "03/04/2019"
 [46] "03/04/2020" "03/04/2021" "03/05/2019" "03/05/2021" "03/06/2019"
 [51] "03/06/2020" "03/06/2021" "03/07/2019" "03/07/2020" "03/08/2020"
 [56] "03/09/2019" "03/09/2020" "03/10/2019" "03/11/2019" "03/11/2020"
 [61] "03/12/2019" "03/12/2020" "04/01/2021" "04/02/2020" "04/02/2021"
 [66] "04/03/2020" "04/03/2021" "04/04/2019" "04/05/2020" "04/05/2021"
 [71] "04/06/2019" "04/06/2020" "04/06/2021" "04/07/2019" "04/08/2020"
 [76] "04/09/2019" "04/09/2020" "04/10/2019" "04/11/2019" "04/11/2020"
 [81] "04/12/2019" "04/12/2020" "05/01/2021" "05/02/2020" "05/02/2021"
 [86] "05/03/2020" "05/03/2021" "05/04/2019" "05/05/2020" "05/05/2021"
 [91] "05/06/2019" "05/06/2020" "05/07/2019" "05/08/2019" "05/08/2020"
 [96] "05/09/2019" "05/10/2020" "05/11/2019" "05/11/2020" "05/12/2019"
[101] "06/01/2020" "06/01/2021" "06/02/2020" "06/03/2020" "06/04/2020"
[106] "06/04/2021" "06/05/2019" "06/05/2020" "06/05/2021" "06/06/2019"
[111] "06/07/2020" "06/08/2019" "06/08/2020" "06/09/2019" "06/09/2020"
[116] "06/10/2019" "06/10/2020" "06/11/2019" "06/11/2020" "06/12/2019"
[121] "07/01/2020" "07/01/2021" "07/02/2020" "07/04/2020" "07/04/2021"
[126] "07/05/2019" "07/05/2020" "07/05/2021" "07/06/2021" "07/07/2019"
[131] "07/07/2020" "07/08/2019" "07/09/2020" "07/10/2019" "07/10/2020"
[136] "07/12/2020" "08/01/2020" "08/01/2021" "08/02/2021" "08/03/2021"
[141] "08/04/2019" "08/04/2020" "08/04/2021" "08/05/2019" "08/05/2020"
[146] "08/06/2020" "08/06/2021" "08/07/2019" "08/07/2020" "08/08/2019"
[151] "08/09/2020" "08/10/2019" "08/10/2020" "08/11/2019" "08/11/2020"
[156] "08/12/2020" "09/01/2020" "09/02/2021" "09/03/2020" "09/03/2021"
[161] "09/04/2019" "09/04/2020" "09/04/2021" "09/05/2019" "09/05/2021"
[166] "09/06/2020" "09/06/2021" "09/07/2019" "09/07/2020" "09/08/2019"
[171] "09/09/2019" "09/09/2020" "09/10/2019" "09/10/2020" "09/11/2019"
[176] "09/11/2020" "09/12/2019" "09/12/2020" "10/01/2020" "10/02/2020"
[181] "10/02/2021" "10/03/2020" "10/03/2021" "10/04/2019" "10/05/2019"
[186] "10/05/2021" "10/06/2019" "10/06/2020" "10/07/2019" "10/07/2020"
[191] "10/08/2020" "10/09/2019" "10/09/2020" "10/10/2019" "10/11/2020"
[196] "10/12/2019" "10/12/2020" "11/01/2021" "11/02/2020" "11/02/2021"
[201] "11/03/2020" "11/03/2021" "11/04/2019" "11/04/2021" "11/05/2019"
[206] "11/05/2020" "11/05/2021" "11/06/2019" "11/06/2020" "11/07/2019"
[211] "11/08/2020" "11/09/2019" "11/09/2020" "11/10/2019" "11/11/2019"
[216] "11/11/2020" "11/12/2019" "11/12/2020" "12/01/2021" "12/02/2020"
[221] "12/02/2021" "12/03/2020" "12/03/2021" "12/04/2019" "12/04/2021"
[226] "12/05/2019" "12/05/2020" "12/05/2021" "12/06/2019" "12/07/2019"
[231] "12/08/2020" "12/09/2019" "12/10/2020" "12/11/2019" "12/11/2020"
[236] "12/12/2019" "13/01/2020" "13/01/2021" "13/02/2020" "13/02/2021"
[241] "13/03/2020" "13/04/2019" "13/04/2020" "13/04/2021" "13/05/2019"
[246] "13/05/2020" "13/05/2021" "13/06/2019" "13/07/2019" "13/07/2020"
[251] "13/08/2019" "13/08/2020" "13/09/2019" "13/09/2020" "13/10/2019"
[256] "13/10/2020" "13/11/2019" "13/11/2020" "13/12/2019" "14/01/2020"
[261] "14/01/2021" "14/02/2020" "14/04/2019" "14/04/2020" "14/04/2021"
[266] "14/05/2019" "14/05/2020" "14/05/2021" "14/06/2019" "14/07/2020"
[271] "14/08/2019" "14/08/2020" "14/09/2020" "14/10/2019" "14/10/2020"
[276] "14/11/2019" "14/12/2020" "15/01/2020" "15/01/2021" "15/02/2020"
[281] "15/02/2021" "15/03/2021" "15/04/2019" "15/04/2020" "15/04/2021"
[286] "15/05/2019" "15/05/2020" "15/05/2021" "15/06/2020" "15/07/2019"
[291] "15/07/2020" "15/09/2019" "15/09/2020" "15/10/2019" "15/10/2020"
[296] "15/11/2019" "15/12/2020" "16/01/2020" "16/02/2021" "16/03/2020"
[301] "16/03/2021" "16/04/2019" "16/04/2020" "16/04/2021" "16/05/2019"
[306] "16/06/2020" "16/07/2019" "16/07/2020" "16/08/2019" "16/09/2019"
[311] "16/09/2020" "16/10/2019" "16/10/2020" "16/11/2020" "16/12/2019"
[316] "16/12/2020" "17/01/2020" "17/01/2021" "17/02/2020" "17/02/2021"
[321] "17/03/2020" "17/03/2021" "17/04/2019" "17/05/2019" "17/05/2021"
[326] "17/06/2019" "17/06/2020" "17/07/2019" "17/07/2020" "17/08/2019"
[331] "17/08/2020" "17/09/2019" "17/09/2020" "17/10/2019" "17/11/2020"
[336] "17/12/2019" "17/12/2020" "18/01/2021" "18/02/2020" "18/02/2021"
[341] "18/03/2020" "18/03/2021" "18/04/2019" "18/05/2020" "18/05/2021"
[346] "18/06/2019" "18/06/2020" "18/07/2019" "18/08/2020" "18/09/2019"
[351] "18/09/2020" "18/10/2019" "18/11/2019" "18/11/2020" "18/12/2019"
[356] "18/12/2020" "19/01/2021" "19/02/2020" "19/02/2021" "19/03/2020"
[361] "19/03/2021" "19/04/2021" "19/05/2020" "19/05/2021" "19/06/2019"
[366] "19/06/2020" "19/07/2019" "19/08/2019" "19/08/2020" "19/09/2019"
[371] "19/10/2020" "19/11/2019" "19/11/2020" "19/12/2019" "20/01/2020"
[376] "20/01/2021" "20/02/2020" "20/03/2020" "20/04/2019" "20/04/2020"
[381] "20/04/2021" "20/05/2019" "20/05/2020" "20/05/2021" "20/06/2019"
[386] "20/07/2019" "20/07/2020" "20/08/2019" "20/08/2020" "20/09/2019"
[391] "20/10/2020" "20/11/2019" "20/11/2020" "20/12/2019" "20/12/2020"
[396] "21/01/2020" "21/01/2021" "21/02/2020" "21/04/2020" "21/04/2021"
[401] "21/05/2019" "21/05/2020" "21/05/2021" "21/06/2019" "21/07/2020"
[406] "21/08/2019" "21/08/2020" "21/09/2020" "21/10/2019" "21/10/2020"
[411] "21/11/2019" "21/11/2020" "21/12/2020" "22/01/2020" "22/01/2021"
[416] "22/02/2021" "22/03/2021" "22/04/2020" "22/04/2021" "22/05/2019"
[421] "22/05/2020" "22/06/2020" "22/07/2019" "22/07/2020" "22/08/2019"
[426] "22/09/2020" "22/10/2019" "22/10/2020" "22/11/2019" "22/11/2020"
[431] "22/12/2020" "23/01/2020" "23/02/2020" "23/02/2021" "23/03/2020"
[436] "23/03/2021" "23/04/2019" "23/04/2020" "23/04/2021" "23/05/2019"
[441] "23/05/2020" "23/06/2020" "23/07/2019" "23/07/2020" "23/08/2019"
[446] "23/09/2019" "23/09/2020" "23/10/2019" "23/10/2020" "23/11/2020"
[451] "23/12/2020" "24/01/2020" "24/02/2020" "24/02/2021" "24/03/2020"
[456] "24/03/2021" "24/04/2020" "24/04/2021" "24/05/2019" "24/05/2021"
[461] "24/06/2019" "24/06/2020" "24/07/2019" "24/07/2020" "24/08/2020"
[466] "24/09/2019" "24/09/2020" "24/10/2019" "24/11/2020" "24/12/2019"
[471] "24/12/2020" "25/01/2021" "25/02/2020" "25/02/2021" "25/03/2020"
[476] "25/03/2021" "25/04/2019" "25/04/2021" "25/05/2019" "25/05/2021"
[481] "25/06/2019" "25/06/2020" "25/07/2019" "25/08/2020" "25/09/2019"
[486] "25/09/2020" "25/10/2019" "25/11/2019" "25/11/2020" "26/01/2020"
[491] "26/01/2021" "26/02/2020" "26/02/2021" "26/03/2020" "26/03/2021"
[496] "26/04/2019" "26/04/2021" "26/05/2020" "26/05/2021" "26/06/2019"
[501] "26/06/2020" "26/08/2020" "26/09/2019" "26/10/2020" "26/11/2019"
[506] "26/11/2020" "27/01/2020" "27/01/2021" "27/02/2020" "27/02/2021"
[511] "27/03/2020" "27/04/2020" "27/04/2021" "27/05/2020" "27/05/2021"
[516] "27/06/2019" "27/07/2020" "27/08/2019" "27/08/2020" "27/09/2019"
[521] "27/10/2020" "27/11/2019" "27/11/2020" "27/12/2019" "28/01/2020"
[526] "28/01/2021" "28/02/2020" "28/02/2021" "28/03/2021" "28/04/2019"
[531] "28/04/2020" "28/04/2021" "28/05/2019" "28/05/2021" "28/06/2019"
[536] "28/07/2019" "28/07/2020" "28/08/2019" "28/08/2020" "28/09/2020"
[541] "28/10/2019" "28/10/2020" "28/11/2019" "28/12/2019" "29/01/2020"
[546] "29/01/2021" "29/04/2019" "29/04/2020" "29/04/2021" "29/05/2019"
[551] "29/05/2020" "29/05/2021" "29/06/2020" "29/07/2019" "29/07/2020"
[556] "29/08/2019" "29/09/2020" "29/10/2019" "29/10/2020" "29/11/2019"
[561] "29/12/2020" "30/01/2020" "30/03/2020" "30/03/2021" "30/04/2019"
[566] "30/04/2020" "30/04/2021" "30/05/2019" "30/06/2020" "30/07/2019"
[571] "30/08/2019" "30/09/2019" "30/09/2020" "30/10/2019" "30/10/2020"
[576] "30/11/2019" "30/11/2020" "30/12/2020" "31/01/2020" "31/03/2020"
[581] "31/03/2021" "31/05/2019" "31/07/2019" "31/07/2020" "31/10/2019"
[586] "31/12/2019" "31/12/2020"

# LAC

In [22]:
lac_data = "CB_2489.cb_CLA_2006_to_2019"

lac_table <- tbl(con, lac_data) |>
    select(person_id,CLA_ACADYR)

In [23]:
lac_df <- collect(lac_table)

In [24]:
head(lac_df)

  person_id                                                        CLA_ACADYR
1 301A8393CBC9BC5B127B33C9BBC77D89A67932C531AB716D0AC116A29FBC03A7 2005/2006
2 4C7F526CAEFC48E30751765A0168DFFDF67E717B229E1FFAF0AAADEDA18A3773 2005/2006
3 243542528EE5BD4E50EEDE9AC7C9587633F5275D27AC69975A43E4634375A484 2005/2006
4 FF008416E57E330193805A59438F4983E43547DFFF02A162BB31742F5AACEA4D 2005/2006
5 B93124CA7B49C443CE539682B23536D8F1EB1D35609E1E730AD982CD120D45FB 2005/2006
6 EE4A1478A07E12766FF1D5DA01DF603A98A4ADE131718D071060F30142D49D3F 2005/2006

In [25]:
lac_df |> arrange(CLA_ACADYR) |> distinct(CLA_ACADYR) |> pull(CLA_ACADYR)

 [1] "2005/2006" "2006/2007" "2007/2008" "2008/2009" "2009/2010" "2010/2011"
 [7] "2011/2012" "2012/2013" "2013/2014" "2014/2015" "2015/2016" "2016/2017"
[13] "2017/2018" "2018/2019"

In [26]:
lac_filtered <- lac_df |>
    filter(person_id %in% person_ids$person_id)

In [27]:
ever_lac <- lac_filtered |>
    select(person_id) |>
    distinct() |>
    mutate(ever_LAC = TRUE)

In [28]:
ever_lac |> nrow()

[1] 536

In [29]:
sum(ever_lac$person_id %in% ever_cin$person_id)

[1] 526

In [30]:
lac_extra <- anti_join(ever_lac, ever_cin, by = "person_id")

In [31]:
lac_extra

   person_id                                                        ever_LAC
1  765802B6591B46CCCEFCDE9D32D960FD41C6A1A49207E9B6AFC4D8BAA8789F84 TRUE
2  21922CBFE180E8946C89A59782AC1E466C80D93E85008DE64189761B1A6E8D8C TRUE
3  E2C4A8EAB1EFA92CFEFD8D2E6A091B122252B209CF2B99BA0CC72C93710DEC9C TRUE
4  82762AA35A1AB1C1175FC7956C1E03E701C55462E5BA0E49714FB47C7D05EB9C TRUE
5  59C4DF19BF86AC5D32BFC710E7A919531628BB507F8024E1BFECD192F6B569EE TRUE
6  D21CC15BDFE3DC41EAD144257AA1A7B8A96E6DD90DACA1F5F7C6F1F17014CF96 TRUE
7  5F1AD58EC267D213DF017826D51B3C9544777C6F9197ED6E2053D428A4AA7E33 TRUE
8  B6275FAD8102F90F9E123AA0D524DFEF471A00E201B68A9CA9EBA13E290DEAE9 TRUE
9  AF5F6E07B22B1FEC1F64D15E42C2FE07724BC528BA4CF668DF72AD62B7E01F51 TRUE
10 18EAC0E67AB39869749D3068D2697524BC1442A9AFDFC981C0FF6B5116774725 TRUE

10 extra are dates prior to CIN dataset

In [32]:
lac_extra <- lac_extra |>
    rename(ever_CIN = ever_LAC)